cloudforet-io/console

- packages/mirinae/src/data-display/dynamic/dynamic-field/templates/badge/index.vue
- packages/mirinae/src/data-display/dynamic/dynamic-field/templates/datetime/index.vue
- packages/mirinae/src/data-display/dynamic/dynamic-field/templates/size/index.vue
- packages/mirinae/src/feedbacks/loading/skeleton/PSkeleton.vue
- packages/mirinae/src/layouts/divider/PDivider.vue
SSIA
[Refer to this (missed code)](https://github.com/cloudforet-io/console/pull/1061)
> fix(mirinae): add missed mirinae code

- .github/workflows/review.yml
> build: update review ci

- apps/web/src/services/my-page/my-account/user-account/modules/NotificationEmail.vue
- changed email invalidation message
> fix: changed email invalidation message

- packages/mirinae/src/data-display/dynamic/dynamic-field/templates/badge/index.vue
- packages/mirinae/src/data-display/dynamic/dynamic-field/templates/datetime/index.vue
- packages/mirinae/src/data-display/dynamic/dynamic-field/templates/size/index.vue
- packages/mirinae/src/feedbacks/loading/skeleton/PSkeleton.vue
- packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
- packages/mirinae/src/layouts/divider/PDivider.vue
SSIA
Fixed `storybook-build` issue by rolling back and refactoring with using `setup` function.
`storybook-build` now works fine in local environment.
This is not going to be problem again..
I don't know why `storybook-build` error occurred yet.
It is certain that the issue occurred in `PSelectDropdown` refactoring code. 
(But that code didn't have syntax problem, I think.. T^T)
> fix(storybook-build): storybook build error

- apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/cloud-service-history-detail/CloudServiceHistoryChangesTab.vue
fix [Quest-164](https://pyengine.atlassian.net/browse/QUEST-164)
before
after
> fix(cloud-service-history): fix style bug

- apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/cloud-service-history-detail/CloudServiceHistoryChangesTab.vue
> fix(cloud-service-history): fix style bug (#1077)

- apps/web/src/services/dashboards/widgets/budget-usage-summary/BudgetUsageSummaryWidget.vue
> chore(widget): set red when rate is over 100

- apps/web/src/services/administration/iam/user/modules/user-management-modal/UserManagementModal.vue
- apps/web/src/services/administration/iam/user/modules/user-management-modal/modules/NotificationEmailForm.vue
- apps/web/src/services/administration/iam/user/modules/user-management-modal/modules/UserInfoForm.vue
> feat(administration): changed verified status at notification email

- apps/web/src/services/administration/iam/user/modules/user-management-modal/modules/NotificationEmailForm.vue
> chore: remove log

- apps/web/src/services/dashboards/widgets/_components/WidgetFrame.vue
- apps/web/src/services/dashboards/widgets/_components/WidgetViewModeModal.vue
- packages/language-pack/console-translation.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
- add view-mode button to widget
- show view-mode modal
> feat(view-mode): add view-mode button and modal

- apps/web/src/services/dashboards/dashboard-detail/DashboardDetailPage.vue
- apps/web/src/services/dashboards/modules/dashboard-label/DashboardLabels.vue
> feat(dashboard-label): enable to update label in detail page

- apps/web/src/services/dashboards/store/dashboard-detail-info.ts
Fix dashboard variable dropdown bug
> fix(dashboard-detail-info): fix variable bug

- apps/web/src/services/dashboards/widgets/_components/WidgetFrame.vue
- apps/web/src/services/dashboards/widgets/_components/WidgetViewModeModal.vue
- apps/web/src/services/dashboards/widgets/_configs/config.ts
- apps/web/src/services/dashboards/widgets/_hooks/use-widget-frame-props.ts
https://github.com/cloudforet-io/console/assets/18563857/a4242329-21a3-4cb8-8e4b-63bec4fe05b5
> feat(view-mode-modal): show widget in view mode modal 

- packages/mirinae/src/data-display/markdown/PMarkdown.vue
> feat(markdown): add target attribution

- apps/web/src/common/composables/amcharts5/tree-map-helper.ts
- apps/web/src/services/dashboards/widgets/_base/base-trend/BaseTrendWidget.vue
- apps/web/src/services/dashboards/widgets/cost-map/CostMapWidget.vue
- add ellipsis attribute
- add min-hight attribute
> fix(cost-widget): fix chart ui bug

- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisHeader.vue
- apps/web/src/services/cost-explorer/cost-dashboard/cost-dashboard-customize/modules/CostDashboardCustomizeCostQuery.vue
- apps/web/src/services/cost-explorer/cost-dashboard/cost-dashboard-customize/modules/CostDashboardCustomizeCustomWidgetTab.vue
- apps/web/src/services/cost-explorer/cost-dashboard/cost-dashboard-customize/modules/CustomWidgetPreview.vue
- apps/web/src/services/cost-explorer/widgets/CustomWidget.vue
use `group_by` rather than `primary_group_by`
> fix(cost-query-set): fix bugs of cost query set

- deploy/helm/Chart.yaml
- deploy/helm/templates/deployment.yaml
- change `nginx.conf` path in helm chart
> build: change nginx.conf path

- .github/workflows/pull_request_review.yml
- .gitignore
- README.md
- dev/turbo-cache-server.sample.env
- dev/turbo_cache_server.md
SSIA. Please read the documents.
> docs: add guide of using turbo cache server on local

- apps/web/src/services/administration/iam/user/modules/user-management-modal/UserManagementModal.vue
- fixed bug when external user create
> fix(create-user): fixed bug when external user create

- apps/web/src/services/dashboards/widgets/_components/WidgetFrame.vue
- apps/web/src/services/dashboards/widgets/_components/WidgetViewModeModal.vue
https://github.com/cloudforet-io/console/assets/18563857/05403559-e2b2-4e0f-bc26-8c15e0f7d209
> feat(widget-view-mode): refresh widget when dashboard variable changed

- packages/core-lib/.eslintrc.js
- packages/core-lib/package.json
- packages/core-lib/tsconfig.build.json
> fix(core-lib): fix lint error of test files

- apps/web/src/App.vue
- apps/web/src/common/modules/modals/notification-email-modal/NotificationEmailModal.vue
- apps/web/src/lib/helper/verify-email-helper.ts
- apps/web/src/services/administration/iam/user/modules/user-management-modal/UserManagementModal.vue
- apps/web/src/services/administration/iam/user/modules/user-management-modal/modules/NotificationEmailForm.vue
- apps/web/src/services/administration/iam/user/type.ts
- apps/web/src/services/my-page/my-account/user-account/modules/NotificationEmail.vue
- apps/web/src/store/modules/user/actions.ts
- packages/language-pack/console-translation.babel
- packages/language-pack/ja.json
- packages/language-pack/ko.json
- fix bug when a logged-in user verifies their own email address
> feat(notification-email): planning QA

- .github/workflows/dispatch_daily_build.yaml
- .github/workflows/dispatch_mirinae_release.yaml
- .github/workflows/dispatch_release.yaml
- .github/workflows/dispatch_storybook_release.yaml
- .github/workflows/dispatch_versioning.yaml
- .github/workflows/pull_request_target_review.yml
- .husky/pre-commit
- apps/web/Dockerfile
- dev/turbo-cache-server.sample.env
- dev/turbo_cache_server.md
- package-lock.json
- package.json
- turbo.json
- Updated related workflows (review, etc.)
- Upgraded turbo patch version
- Updated turbo.json not make any differences of hash between local build and docker build
> ci: update workflows to use remote cache server in background

- apps/web/src/services/dashboards/widgets/_components/WidgetViewModeModal.vue
> feat: add toolset to view mode modal

- apps/web/src/lib/helper/verify-email-helper.ts
- apps/web/src/services/administration/iam/user/modules/UserManagementTable.vue
- apps/web/src/services/administration/iam/user/modules/user-management-modal/UserManagementModal.vue
- apps/web/src/services/administration/iam/user/modules/user-management-modal/modules/NotificationEmailForm.vue
- apps/web/src/store/modules/user/actions.ts
- Fix the bug where a notification email is sent when updating a user in an unverified email state.
> fix: changed emit when user update

- apps/web/src/services/dashboards/widgets/_components/WidgetFrame.vue
- apps/web/src/services/dashboards/widgets/_helpers/widget-schema-helper.ts
- apps/web/src/services/dashboards/widgets/_hooks/use-widget-frame-props.ts
- apps/web/src/services/dashboards/widgets/_hooks/use-widget-state.ts
> feat: show tooltip when there's non-inherit options in widget

- apps/web/src/store/modules/reference/cloud-service-type/actions.ts
- apps/web/src/store/modules/reference/collector/actions.ts
- apps/web/src/store/modules/reference/plugin/actions.ts
- apps/web/src/store/modules/reference/project-group/actions.ts
- apps/web/src/store/modules/reference/project/actions.ts
- apps/web/src/store/modules/reference/protocol/actions.ts
- apps/web/src/store/modules/reference/provider/actions.ts
- apps/web/src/store/modules/reference/region/actions.ts
- apps/web/src/store/modules/reference/secret/actions.ts
- apps/web/src/store/modules/reference/service-account/actions.ts
Moved the lastLoadedTime setting to the line below commit.
> fix(reference-action-bug): fix bug of reference store action

- apps/web/src/services/dashboards/modules/DashboardVariablesSelector.vue
- apps/web/src/services/dashboards/store/dashboard-detail-info.ts
- apps/web/src/services/dashboards/widgets/_components/WidgetViewModeModal.vue
- apps/web/src/services/dashboards/widgets/budget-usage-summary/BudgetUsageSummaryWidget.vue
- In view mode modal, reset to snapshot variables, **not dashboard variables**.
> feat(dashboard-toolset): add arguments to `resetVariables`

- deploy/helm/Chart.yaml
- deploy/helm/values.yaml
- [ x `Error / Warning / Lint / Type`
- Change default `production.json` in Helm Chart
> build: change default production.json

- apps/web/src/services/dashboards/dashboard-customize/DashboardCustomizePage.vue
- apps/web/src/services/dashboards/dashboard-customize/modules/VariableSelectorDropdown.vue
- apps/web/src/services/dashboards/modules/DashboardVariablesSelector.vue
- apps/web/src/services/dashboards/widgets/_components/WidgetViewModeModal.vue
https://github.com/cloudforet-io/console/assets/18563857/9fb49f87-b6ad-410f-8e0c-fa53dbfd5d62
> feat: show blue mark when schema changed

- apps/web/src/common/modules/navigations/lnb/modules/LNBMenuItem.vue
- apps/web/src/common/modules/navigations/lnb/type.ts
- apps/web/src/services/dashboards/DashboardsLNB.vue
- apps/web/src/services/dashboards/widgets/budget-usage-summary/BudgetUsageSummaryWidget.vue
- apps/web/src/services/home-dashboard/modules/trusted-advisor/TrustedAdvisorOverall.vue
- add private icon to dashboard lnb 
- fix color bug in BudgetUsageSummary widget
> feat(icon): add private icon to dashboard lnb

- apps/web/src/services/dashboards/widgets/severity-status-by-service/SeverityStatusByServiceWidget.vue
- apps/web/src/services/dashboards/widgets/severity-status-by-service/widget-config.ts
> feat(asset-widget): add severityStatusByService widget

- apps/web/src/services/home-dashboard/modules/trusted-advisor/TrustedAdvisorOverall.vue
> fix: update TrustedAdvisorOverall css

- apps/web/src/services/asset-inventory/collector/CollectorPage.vue
- apps/web/src/services/asset-inventory/collector/modules/CollectorNoData.vue
- apps/web/src/services/asset-inventory/collector/type.ts
- create UI when there is no data
> feat(collector-landing): create UI when there is no data

- apps/web/src/services/asset-inventory/collector/create-collector/CreateCollectorPage.vue
- apps/web/src/services/asset-inventory/collector/create-collector/modules/CreateCollectorStep1.vue
- apps/web/src/services/asset-inventory/collector/create-collector/modules/CreateCollectorStep2.vue
- apps/web/src/services/asset-inventory/collector/create-collector/modules/CreateCollectorStep3.vue
- apps/web/src/services/asset-inventory/collector/create-collector/modules/CreateCollectorStep4.vue
- apps/web/src/services/asset-inventory/collector/create-collector/modules/Step1SearchFilter.vue
> feat(collector-create): add markup of step1 page

- apps/web/public/config/default.json
> feat(config): update API Guide link

- apps/web/src/common/composables/amcharts5/index.ts
- apps/web/src/common/composables/amcharts5/xy-chart-helper.ts
- apps/web/src/services/dashboards/widgets/trend-of-pass-and-fail-findings/TrendOfPassAndFailFindingsWidget.vue
- apps/web/src/services/dashboards/widgets/trend-of-pass-and-fail-findings/widget-config.ts
> feat(asset-widget): add `TrendOfPassAndFailFindings` widget

- .github/workflows/pull_request_target_review.yml
> ci: update review workflow for test

- .github/workflows/pull_request_target_review.yml
> chore: test review ci lint errors

- apps/web/src/services/dashboards/widgets/__tests__/widget-helper.test.ts
> chore: fix test code

- apps/web/src/services/asset-inventory/collector/create-collector-old/CreateCollectorPage.vue
- apps/web/src/services/asset-inventory/collector/create-collector/modules/CreateCollectorStep1.vue
- apps/web/src/services/asset-inventory/collector/create-collector/modules/CreateCollectorStep2.vue
- apps/web/src/services/asset-inventory/collector/modules/CollectPluginContents.vue
- apps/web/src/services/asset-inventory/store/collector-form-store.ts
The markup work in step2 page is the main thing. A few feature implementations related to some markups have been added, and please skip tasks related to api!
> feat(collector-create): create step2 page contents

- apps/web/src/services/asset-inventory/collector/CollectorPage.vue
- apps/web/src/services/asset-inventory/collector/modules/CollectorContents.vue
- apps/web/src/services/asset-inventory/service-account/ServiceAccountPage.vue
- apps/web/src/services/asset-inventory/store/collector-page-store.ts
- apply search query
- tiny-up the collector-store-page file
> feat(collector-landing): apply search query

- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorBaseInfoSection.vue
- apps/web/src/services/asset-inventory/collector/type.ts
Applied read mode markups of `CollectorBaseInfoSection` and composite related components.
https://github.com/cloudforet-io/console/assets/26986739/407e5c35-dba5-48d6-9c1b-1be03fff2992
> feat: add CollectorBaseInfoSection read case markups

- .github/PULL_REQUEST_TEMPLATE.md
SSIA
[Precious Previous Review](https://github.com/cloudforet-io/console/pull/1060)
Please feel free to give me any opinions.
> chore: renewal pull-request template

- packages/mirinae/src/data-display/field-title/PFieldTitle.stories.mdx
- packages/mirinae/src/data-display/field-title/PFieldTitle.vue
- packages/mirinae/src/data-display/field-title/story-helper.ts
- Packages
- Apps
- Refactored `PFieldTitle` component to script setup.
- Added description to `PFieldTitle` component in mirinae package.
- Updated story of it.
- Fixed some css differences between original css and figma design. The left is new one and the right is the old(wrong) one.
Component spec in figma
> feat(field-title): add description prop and fix css

- apps/web/src/services/dashboards/default-dashboard/template-list.ts
- apps/web/src/services/dashboards/default-dashboard/templates/compliance-overview.ts
- apps/web/src/services/dashboards/widgets/_configs/config.ts
- apps/web/src/services/dashboards/widgets/_configs/widget-list-config.ts
- apps/web/src/services/dashboards/widgets/_hooks/use-widget-state.ts
- [add "Compliance Overview" dashboard template](https://github.com/cloudforet-io/console/pull/1174/commits/8cdb586673dcf6643343cc727ea90705c58309e3)
- [add asset widgets to widget-list-config](https://github.com/cloudforet-io/console/pull/1174/commits/cf39264c47c2cf5719d702de4f264a15e3c1fc88)
> feat: add "Compliance Overview" dashboard template & asset widgets

- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorScheduleSection.vue
- packages/language-pack/en.json
> feat: add CollectorScheduleSection read case markups

- apps/web/src/services/asset-inventory/collector/collector-detail/CollectorDetailPage.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorBaseInfoSection.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorOptionsSection.vue
- [refactor: move collector data to upper scope](https://github.com/cloudforet-io/console/commit/0f9c45cf626df7adbcaf1780906ca27bd76009b4)
- `CollectorBaseInfoSection` -> `CollectorDetailPage`
- [feat: add CollectorDetailPage read case markups](https://github.com/cloudforet-io/console/commit/5bcba29dc9fabdce6604e3e6ebb45737c51cb026)
- [fix: change style type of definition-table in CollectorBaseInfoSection](https://github.com/cloudforet-io/console/commit/9934ee5efc37bfa1f0ec755aa744d2336b42f18c)
> feat: add CollectorDetailPage read case markups

- apps/web/src/services/asset-inventory/collector/collector-detail/CollectorDetailPage.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorServiceAccountsSection.vue
> feat: add CollectorServiceAccountsSection read case markups

- apps/web/src/services/administration/iam/user/modules/user-management-modal/UserManagementModal.vue
- apps/web/src/services/administration/iam/user/type.ts
- edit parameter of user create API
> fix: fix payload of create api user

- apps/web/src/lib/site-initializer/dayjs.ts
> fix: fix dayjs thresholds

- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorScheduleForm.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorScheduleSection.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorServiceAccountsSection.vue
SSIA
https://github.com/cloudforet-io/console/assets/26986739/b1f7dfed-3780-4c48-853b-f040ea9719a9
> feat: add CollectorScheduleSection edit mode markups

- apps/web/src/services/dashboards/widgets/_components/WidgetFrame.vue
- apps/web/src/services/dashboards/widgets/_hooks/use-widget-state.ts
> feat: hide currency when it's not cost widget

- apps/web/src/services/administration/additional-settings/provider/ProviderPage.vue
- apps/web/src/services/administration/additional-settings/provider/provider-add/ProviderAddPage.vue
- apps/web/src/services/asset-inventory/collector/create-collector/CreateCollectorPage.vue
- apps/web/src/services/asset-inventory/collector/create-collector/modules/AttachedServiceAccountForm.vue
- apps/web/src/services/asset-inventory/collector/create-collector/modules/CreateCollectorStep1.vue
- apps/web/src/services/asset-inventory/collector/create-collector/modules/CreateCollectorStep2.vue
- apps/web/src/services/asset-inventory/collector/create-collector/modules/CreateCollectorStep3.vue
- apps/web/src/services/asset-inventory/collector/modules/CollectPluginContents.vue
- apps/web/src/services/asset-inventory/store/collector-form-store.ts
- Added new state to store(collector-form-store)
- Added CreateCollectorStep3 markup
- Added AttachedServiceAccountForm components markup & little function
Dynamic field (JSON schema) has not yet been implemented.
> feat(create-collector-step3): add step3 page component & AttachedServiceAccountForm

- apps/web/src/services/dashboards/default-dashboard/templates/compliance-overview.ts
- apps/web/src/services/dashboards/widgets/_configs/view-config.ts
- apps/web/src/services/dashboards/widgets/_configs/widget-list-config.ts
- apps/web/src/services/dashboards/widgets/total-failure-and-severity/TotalFailureAndSeverityWidget.vue
- apps/web/src/services/dashboards/widgets/total-failure-and-severity/widget-config.ts
- package.json
- packages/core-lib/src/index.ts
**Just Markup!! Not real data**
> feat: add totalFailureAndSeverity widget

- apps/web/src/common/composables/amcharts5/xy-chart-helper.ts
- apps/web/src/services/dashboards/dashboard-customize/modules/DashboardDefaultWidgetTab.vue
- apps/web/src/services/dashboards/dashboard-customize/modules/dashboard-widget-input-form/DashboardWidgetInputForm.vue
- apps/web/src/services/dashboards/widgets/__tests__/widget-helper.test.ts
- apps/web/src/services/dashboards/widgets/_components/WidgetDataTable.vue
- apps/web/src/services/dashboards/widgets/_hooks/use-widget-frame-props.ts
- apps/web/src/services/dashboards/widgets/severity-status-by-service/SeverityStatusByServiceWidget.vue
- apps/web/src/services/dashboards/widgets/severity-status-by-service/widget-config.ts
- apps/web/src/services/dashboards/widgets/total-failure-and-severity/TotalFailureAndSeverityWidget.vue
- apps/web/src/services/dashboards/widgets/trend-of-pass-and-fail-findings/TrendOfPassAndFailFindingsWidget.vue
- apps/web/src/services/dashboards/widgets/trend-of-pass-and-fail-findings/widget-config.ts
Please review the **file changes** instead of the commits!
> feat: edit minor things

- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorScheduleSection.vue
- apps/web/src/services/asset-inventory/collector/modules/CollectorScheduleForm.vue
SSIA
https://github.com/cloudforet-io/console/assets/26986739/c54c85ca-b926-426a-8121-a133768854c8
> feat: add interaction of hourly schedule in CollectorScheduleForm

- apps/web/src/services/asset-inventory/collector/collector-detail/CollectorDetailPage.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorServiceAccountsSection.vue
- apps/web/src/services/asset-inventory/collector/modules/AttachedServiceAccountForm.vue
SSIA
https://github.com/cloudforet-io/console/assets/26986739/e5530b22-079b-4434-899b-2747b0aad356
> feat: add edit mode markups to CollectorServiceAccountsSection

- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorScheduleSection.vue
- apps/web/src/services/asset-inventory/collector/modules/CollectorScheduleForm.vue
SSIA
https://github.com/cloudforet-io/console/assets/26986739/6f0ce0bf-3544-4323-a70a-5fe84cebe167
> feat: apply display times to CollectorScheduleSection

- apps/web/src/common/composables/amcharts5/index.ts
- apps/web/src/common/composables/amcharts5/pie-chart-helper.ts
- apps/web/src/services/dashboards/default-dashboard/templates/compliance-overview.ts
- apps/web/src/services/dashboards/widgets/_configs/view-config.ts
- apps/web/src/services/dashboards/widgets/_configs/widget-list-config.ts
- apps/web/src/services/dashboards/widgets/compliance-check-status/ComplianceCheckStatusWidget.vue
- apps/web/src/services/dashboards/widgets/compliance-check-status/widget-config.ts
> feat: create `complianceCheckStatus` widget

- apps/web/src/services/asset-inventory/collector/modules/CollectorScheduleForm.vue
> feat: add mobile size markup to CollectorScheduleForm

- apps/web/src/services/asset-inventory/collector/create-collector/modules/CreateCollectorStep4.vue
> feat(create-collector-step-4): add markup

- apps/web/src/services/dashboards/widgets/_configs/view-config.ts
- apps/web/src/services/dashboards/widgets/compliance-check-status/ComplianceCheckStatusWidget.vue
- Set real data except red box
> feat: set real data to `complianceCheckStatus` widget

- apps/web/src/services/dashboards/widgets/_base/base-count-of-findings/BaseCountOfFindingsWidget.vue
set real data...Please check my **api query**...
> feat: set real data to `BaseCountOfFindings` widget

- apps/web/src/services/dashboards/widgets/asset-widgets/compliance-check-status/ComplianceCheckStatusWidget.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/total-failure-and-severity/TotalFailureAndSeverityWidget.vue
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> chore: update language

- apps/web/src/services/asset-inventory/collector/CollectorPage.vue
- apps/web/src/services/asset-inventory/collector/create-collector/modules/CreateCollectorStep1.vue
- apps/web/src/services/asset-inventory/collector/create-collector/modules/Step1SearchFilter.vue
SSIA
https://github.com/cloudforet-io/console/assets/50662170/c09e39db-16c9-4954-8e55-d5bba0690c3d
> feat(create-collector-step1): apply collector api & infinite scroll

- apps/web/src/services/asset-inventory/collector/collector-detail/CollectorDetailPage.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorBaseInfoSection.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorScheduleSection.vue
- apps/web/src/services/asset-inventory/collector/modules/CollectorScheduleForm.vue
- apps/web/src/services/asset-inventory/collector/type.ts
- apps/web/src/services/asset-inventory/store/collector-form-store.ts
Please review in order of commit.
(Commit messages say it all)
https://github.com/cloudforet-io/console/assets/26986739/97bb2f58-aea4-4e79-a612-514d6b8105b6
> feat: apply data loader to CollectorScheduleForm

- apps/web/src/services/cost-explorer/budget/modules/budget-toolbox/BudgetToolbox.vue
> refactor(budget-toolbox): change to use useQueryTags composable

- apps/web/src/common/composables/amcharts5/concepts-helper.ts
- apps/web/src/common/composables/amcharts5/index.ts
- apps/web/src/services/dashboards/widgets/_base/base-count-of-findings/BaseCountOfFindingsWidget.vue
Add tooltip and bullet(text in bar chart)
> feat: update chart and edit api params

- apps/web/src/services/dashboards/widgets/asset-widgets/total-failure-and-severity/TotalFailureAndSeverityWidget.vue
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: get real data in `TotalFailureAndSeverity` widget

- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorBaseInfoSection.vue
- apps/web/src/services/asset-inventory/collector/create-collector/modules/CreateCollectorStep1.vue
- apps/web/src/services/asset-inventory/collector/shared/CollectorPluginContents.vue
> fix: update to use plugin reference data in CollectorPluginContents and CollectorBaseInfoSection

- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContents.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorItemInfo.vue
- apps/web/src/services/asset-inventory/collector/type.ts
- fixed link at collector item history button
- `View history details`  click > link collector history detail page
- apply temp link at collector job detail
- `success icon` click > link job detail page
- will be fixed the link after API completed
- apply link collector item detail
- `collector item` click > link collector item detail page
> feat(collector): apply link

- apps/web/src/services/dashboards/widgets/_base/base-count-of-findings/BaseCountOfFindingsWidget.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/compliance-check-status/ComplianceCheckStatusWidget.vue
> chore: edit minor

- apps/web/src/services/asset-inventory/collector/collector-create/CollectorCreatePage.vue
> feat: apply useGoBack composable to CollectorCreatePage

- packages/mirinae/src/feedbacks/modals/advanced/double-check-modal/PDoubleCheckModal.stories.mdx
- packages/mirinae/src/feedbacks/modals/advanced/double-check-modal/PDoubleCheckModal.vue
- packages/mirinae/src/feedbacks/modals/advanced/double-check-modal/story-helper.ts
> feat(miriane): add loading prop to DoubleCheckModal

- apps/web/src/services/asset-inventory/collector/collector-create/modules/CreateCollectorStep2.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/CollectorDetailPage.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorNameEditModal.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorNameForm.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/collector-form-store.ts
https://github.com/cloudforet-io/console/assets/26986739/90225403-b14b-4fd2-9b92-ef380cdb55bc
> feat: separate CollectorNameForm from CreateCollectorStep2 & add CollectorNameEditModal for CollectorDetailPage

- apps/web/src/services/asset-inventory/collector/collector-detail/CollectorDetailPage.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/collector-form-store.ts
- apps/web/src/services/asset-inventory/collector/type.ts
SSIA
https://github.com/cloudforet-io/console/assets/26986739/1b9491bc-304c-41e9-b2ce-52087b61a960
> feat: add collector delete modal and bind to delete button in CollectorDetailPage

- apps/web/src/services/asset-inventory/collector/collector-main/collector-page-store.ts
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContents.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorItemInfo.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorScheduleModal.vue
- apps/web/src/services/asset-inventory/collector/type.ts
- apply collector schedule modal
> feat(collector): apply collector schedule modal

- apps/web/src/lib/reference/asset-reference-config.ts
- apps/web/src/services/dashboards/config.ts
- apps/web/src/services/dashboards/dashboard-customize/modules/VariableSelectorDropdown.vue
- apps/web/src/services/dashboards/dashboard-customize/modules/dashboard-manage-variable-overlay/modules/DashboardManageVariableForm.vue
- apps/web/src/services/dashboards/managed-variables-schema.ts
- apps/web/src/services/dashboards/widgets/_configs/config.ts
- apps/web/src/services/dashboards/widgets/_configs/view-config.ts
- apps/web/src/services/dashboards/widgets/_configs/widget-schema-config.ts
- Set real value to
1) Dashboard Variables(2 variables)
2) Widget Group By (4 options)
> feat: change to real value for api

- apps/web/src/services/asset-inventory/collector/collector-main/CollectorPage.vue
- apps/web/src/services/asset-inventory/collector/collector-main/collector-page-store.ts
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContents.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorItemInfo.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorScheduleModal.vue
- apps/web/src/services/asset-inventory/collector/type.ts
- change the subject applying the schedule form store state
https://github.com/cloudforet-io/console/pull/1242#discussion_r1223999568
> feat(collector): change the subject applying the schedule form store state

- packages/core-lib/src/space-connector/error.ts
> feat(core-lib): rename makeAPIError to makeError and extend spec

- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorBaseInfoSection.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorNameEditModal.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorScheduleSection.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorScheduleForm.vue
- apps/web/src/services/asset-inventory/collector/type.ts
SSIA
Please review order by commits.
The preview below looks working wrong because it uses mock api.
https://github.com/cloudforet-io/console/assets/26986739/26e0e724-9f9d-487e-b363-d1105074a236
> fix: change to call api in CollectorScheduleSection

- apps/web/src/services/asset-inventory/collector/collector-detail/CollectorDetailPage.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorServiceAccountsSection.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/AttachedServiceAccountForm.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/collector-form-store.ts
- apps/web/src/services/asset-inventory/collector/type.ts
Please review order by commits.
> feat: apply toolbox options and api to CollectorServiceAccountsSection

- apps/web/src/services/dashboards/widgets/_configs/asset-config.ts
- apps/web/src/services/dashboards/widgets/asset-widgets/severity-status-by-service/SeverityStatusByServiceWidget.vue
> feat: set real data to SeverityStatusByService widget

- apps/web/src/services/asset-inventory/collector/CollectorPageOld.vue
- apps/web/src/services/asset-inventory/collector/collector-create/modules/CreateCollectorStep1.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/CollectorDetailPage.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorBaseInfoSection.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorNameEditModal.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorOptionsSection.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorScheduleSection.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorServiceAccountsSection.vue
- apps/web/src/services/asset-inventory/collector/collector-main/CollectorPage.vue
- apps/web/src/services/asset-inventory/collector/collector-main/collector-page-store.ts
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContents.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorItemInfo.vue
- apps/web/src/services/asset-inventory/collector/create-collector-old/CreateCollectorPage.vue
- apps/web/src/services/asset-inventory/collector/model.ts
- apps/web/src/services/asset-inventory/collector/modules-old/CollectorUpdateModal.vue
- apps/web/src/services/asset-inventory/collector/modules-old/EditScheduleModal.vue
- apps/web/src/services/asset-inventory/collector/shared/CollectorPluginContents.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/collector-form-store.ts
- apps/web/src/services/asset-inventory/collector/type.ts
- apps/web/src/services/home-dashboard/modules/CollectingProgress.vue
- apps/web/src/store/modules/reference/plugin/actions.ts
> refactor: update collector service interfaces

- packages/mirinae/src/inputs/context-menu/PContextMenu.stories.mdx
- packages/mirinae/src/inputs/context-menu/PContextMenu.vue
- packages/mirinae/src/inputs/context-menu/story-helper.ts
> feat(p-context-menu): add resetSelectedOnUnmounted props

- apps/web/src/services/asset-inventory/collector/collector-create/modules/CreateCollectorStep1.vue
> fix(create-collector-step1): fix css

- apps/web/src/services/dashboards/widgets/_components/WidgetFrame.vue
- apps/web/src/services/dashboards/widgets/_configs/asset-config.ts
- apps/web/src/services/dashboards/widgets/asset-widgets/compliance-check-status/ComplianceCheckStatusWidget.vue
> feat: set real time series data

- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorScheduleSection.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorServiceAccountsSection.vue
- apps/web/src/services/asset-inventory/collector/model.ts
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/AttachedServiceAccountForm.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorOptionsForm.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorScheduleForm.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorTagForm.vue
> feat: add hasMetadata prop to CollectorOptionsForm and add resetOnCollectorIdChange to forms

- apps/web/src/services/asset-inventory/collector/collector-detail/CollectorDetailPage.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorOptionsSection.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorOptionsForm.vue
SSIA
https://github.com/cloudforet-io/console/assets/26986739/0d204cde-efd1-4dbc-b2df-b91698a90aaf
> feat: apply save logic of CollectorOptionsSection

- apps/web/src/lib/reference/asset-reference-config.ts
- apps/web/src/services/dashboards/widgets/_configs/config.ts
- apps/web/src/services/dashboards/widgets/asset-widgets/total-failure-and-severity/TotalFailureAndSeverityWidget.vue
> feat: set real data to `totalFailureAndSeverity` widget

- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorServiceAccountsSection.vue
SSIA
https://github.com/cloudforet-io/console/assets/26986739/9b7ea99d-ee6d-4fb6-9706-e29d4d721d2a
> feat: apply saving logic to CollectorServiceAccountSection

- apps/web/src/services/asset-inventory/collector/collector-create/modules/CreateCollectorStep1.vue
- apps/web/src/services/asset-inventory/collector/collector-create/modules/CreateCollectorStep2.vue
- apps/web/src/services/asset-inventory/collector/collector-create/modules/CreateCollectorStep4.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorScheduleSection.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorServiceAccountsSection.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorScheduleModal.vue
- apps/web/src/services/asset-inventory/collector/model.ts
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/AttachedServiceAccountForm.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorScheduleForm.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/collector-form-store.ts
SSIA + small changes
Please review order by commits.
> feat(create-collector-step4): apply collector create api

- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContents.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorItemInfo.vue
- apps/web/src/services/asset-inventory/collector/model.ts
- apply collector schedule data from collector list API
- fixed collector schedule format
- will be applied 'in-progress' status after the job API checking
> feat(collector): apply collector schedule

- apps/web/src/services/asset-inventory/collector/collector-detail/CollectorDetailPage.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorBaseInfoSection.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorScheduleSection.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorScheduleForm.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/collector-form-store.ts
> feat: apply api call to CollectorScheduleForm

- apps/web/src/services/dashboards/widgets/_base/base-count-of-findings/BaseCountOfFindingsWidget.vue
- apps/web/src/services/dashboards/widgets/_configs/asset-config.ts
S...et...Real...Dat...a....
- reference should be applied. (ex. project_s2352fsdf -> 'Belkin Snow')
> feat: set real data to BaseCountOfFindings widget 

- apps/web/src/services/asset-inventory/collector/collector-create/modules/CreateCollectorStep2.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorBaseInfoSection.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorVersionForm.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/collector-form-store.ts
https://github.com/cloudforet-io/console/assets/26986739/1d6ba647-6459-4c95-b2f2-12506de5a2e0
> feat: attach '(latest)' if version is latest in CollectorBaseInfoSection

- apps/web/src/services/dashboards/widgets/asset-widgets/compliance-check-status/ComplianceCheckStatusWidget.vue
- edit markup
- edit type
Before
After
> feat: hide unused section

- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorServiceAccountsSection.vue
> fix: change to use proper queryTags state

- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorServiceAccountsSection.vue
> feat: apply reference data to CollectorServiceAccountsSection table

- apps/web/src/services/asset-inventory/collector/collector-detail/CollectorDetailPage.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorServiceAccountsSection.vue
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
https://github.com/cloudforet-io/console/assets/26986739/dd905c3d-5f68-430e-bc4f-a846d2fb5763
> feat: enable collecting by secret in CollectorServiceAccountsSection

- apps/web/src/services/dashboards/widgets/_base/base-count-of-findings/BaseCountOfFindingsWidget.vue
- apps/web/src/services/dashboards/widgets/_components/WidgetDataTable.vue
- apps/web/src/services/dashboards/widgets/_configs/view-config.ts
- apps/web/src/services/dashboards/widgets/_helpers/widget-table-helper.ts
- apps/web/src/services/dashboards/widgets/asset-widgets/total-failure-and-severity/TotalFailureAndSeverityWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-cost-trend/AWSDataTransferCostTrendWidget.vue
> feat: edit WidgetDataTable style and edit widget-table-helper

- apps/web/src/services/asset-inventory/collector/collector-main/collector-page-store.ts
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContents.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorItemInfo.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorScheduleModal.vue
- apps/web/src/services/asset-inventory/collector/collector-main/type.ts
- apps/web/src/services/asset-inventory/collector/model.ts
> feat(collector): apply job analyze API

- apps/web/src/services/asset-inventory/collector/collector-create/modules/CreateCollectorStep2.vue
- apps/web/src/services/asset-inventory/collector/collector-create/modules/CreateCollectorStep4.vue
- apps/web/src/services/asset-inventory/collector/collector-create/modules/MultipleProviderForm.vue
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat(multiple-provider-form): create component for step2

- apps/web/src/services/dashboards/widgets/asset-widgets/severity-status-by-service/SeverityStatusByServiceWidget.vue
> feat: set history data to `SeverityStatusByService` widget

- apps/web/src/services/dashboards/widgets/_base/base-count-of-findings/BaseCountOfFindingsWidget.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/trend-of-pass-and-fail-findings/TrendOfPassAndFailFindingsWidget.vue
> feat: set real data to `TrendOfPassAndFailFindings` widget

- apps/web/src/services/dashboards/widgets/_base/base-count-of-findings/BaseCountOfFindingsWidget.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/compliance-check-status/ComplianceCheckStatusWidget.vue
> chore: hide tooltip when its fail findings widget & edit order of data

- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorOptionsForm.vue
> fix(collector-options-forms): modify request params of getPluginMetadata

- apps/web/src/services/asset-inventory/collector/collector-main/CollectorPage.vue
- apps/web/src/services/asset-inventory/collector/collector-main/collector-page-store.ts
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContents.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorItemInfo.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorScheduleModal.vue
- apps/web/src/services/asset-inventory/collector/model.ts
- apply collector schedule API
- apply action at schedule toggle
- add icon at `in-progress` status
- fixed css
> feat(collector): apply API at collector item

- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContents.vue
> feat(collector): create collect data button

- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorOptionsForm.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/collector-form-store.ts
> fix(create-collector): add defense code & add event emit code if schema is null 

- apps/web/src/services/asset-inventory/collector/collector-main/CollectorPage.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorScheduleModal.vue
- apps/web/src/services/asset-inventory/collector/collector-main/type.ts
- Modification of only data requested when adjusting the schedule.
> fix: fixed schedule only query issue

- apps/web/src/services/asset-inventory/collector/collector-main/collector-page-store.ts
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContents.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorItemInfo.vue
- apps/web/src/services/asset-inventory/collector/model.ts
- apply recent job link and finished date
> feat(collector): apply recent job link and finished date

- apps/web/src/services/dashboards/dashboard-customize/modules/dashboard-widget-input-form/DashboardWidgetInputForm.vue
- Validation was not working when widget options were being added or removed. So I fixed it!
> fix: validate when widget option properties are updated

- apps/web/src/services/asset-inventory/collector/collector-main/CollectorPage.vue
- apps/web/src/services/asset-inventory/collector/collector-main/collector-page-store.ts
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContents.vue
- apply restarting API at collect data button
- the collect data button always display
> feat(collector): apply API at collect data button

- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContents.vue
- changed excel field to schedule state from collector state
> feat(collector): changed excel field

- apps/web/src/services/asset-inventory/cloud-service/cloud-service-search/CloudServiceSearchPage.vue
> fix: use like operator for the query in CloudServiceSearchPage

- apps/web/src/common/composables/amcharts5/xy-chart-helper.ts
- apps/web/src/services/dashboards/widgets/_base/base-count-of-findings/BaseCountOfFindingsWidget.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/compliance-check-status/ComplianceCheckStatusWidget.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/total-failure-and-severity/TotalFailureAndSeverityWidget.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/trend-of-pass-and-fail-findings/TrendOfPassAndFailFindingsWidget.vue
> fix: fix style bug and sorting of widgets

- apps/web/src/services/asset-inventory/collector/collector-create/modules/CreateCollectorStep1.vue
- apps/web/src/services/asset-inventory/collector/collector-create/modules/CreateCollectorStep3.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorOptionsSection.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorOptionsForm.vue
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat(collector-options-form): add No Options case

- apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/CloudServiceDetailPage.vue
https://github.com/cloudforet-io/console/assets/26986739/cb2b2a24-9ef6-4785-a93f-931e0aaefd6d
The default_sort key of the example is Requirement ID.
> feat: apply default_sort of schema in CloudServiceDetailPage

- apps/web/src/common/composables/amcharts5/index.ts
- apps/web/src/common/composables/amcharts5/xy-chart-helper.ts
- apps/web/src/services/dashboards/widgets/_base/base-count-of-findings/BaseCountOfFindingsWidget.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/compliance-check-status/ComplianceCheckStatusWidget.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/severity-status-by-service/SeverityStatusByServiceWidget.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/total-failure-and-severity/TotalFailureAndSeverityWidget.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/trend-of-pass-and-fail-findings/TrendOfPassAndFailFindingsWidget.vue
> fix: update style and tooltips of asset widgets

- apps/web/src/services/asset-inventory/collector/collector-create/CollectorCreatePage.vue
- apps/web/src/services/asset-inventory/collector/collector-create/modules/CreateCollectorStep1.vue
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> fix(create-collector-step1): fix component css style

- apps/web/src/services/asset-inventory/collector/collector-create/modules/CreateCollectorStep1.vue
- apps/web/src/services/asset-inventory/collector/collector-create/modules/Step1SearchFilter.vue
- apps/web/src/services/asset-inventory/collector/shared/CollectorPluginContents.vue
> fix(create-collector-step1): fix css style

- apps/web/src/common/composables/amcharts5/xy-chart-helper.ts
- apps/web/src/services/asset-inventory/collector/collector-history/collect-job/modules/JobTaskTable.vue
- apps/web/src/services/dashboards/dashboard-customize/modules/VariableSelectorDropdown.vue
- apps/web/src/services/dashboards/widgets/_base/base-count-of-findings/BaseCountOfFindingsWidget.vue
- apps/web/src/services/dashboards/widgets/_hooks/use-widget-state.ts
- apps/web/src/services/dashboards/widgets/asset-widgets/compliance-check-status/ComplianceCheckStatusWidget.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/severity-status-by-service/SeverityStatusByServiceWidget.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/total-failure-and-severity/TotalFailureAndSeverityWidget.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/trend-of-pass-and-fail-findings/TrendOfPassAndFailFindingsWidget.vue
> feat: get console filters for cloudServiceStats api & fix bugs

- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> chore(language): ja/ko translation updated

- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorOptionsForm.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorVersionForm.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/collector-form-store.ts
> fix(create-collector): fix step 3 validation bug & fix version form function

- apps/web/src/services/asset-inventory/collector/collector-create/modules/CreateCollectorStep4.vue
> fix: move to the details page after completing collector creation

- turbo.json
> build: update turbo input to include language-pack in web app

- apps/web/src/services/asset-inventory/collector/collector-create/modules/CreateCollectorStep1.vue
- apps/web/src/services/asset-inventory/collector/collector-create/modules/CreateCollectorStep2.vue
- apps/web/src/services/asset-inventory/collector/shared/CollectorPluginContents.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorNameForm.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorVersionForm.vue
SSIA
CollectorPluginContents Components
step1 -> sm
step2, detail -> lg
> fix(create-collect): add size prop to plugin-contents & add focus function to name-form

- apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/CloudServiceDetailPage.vue
- apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/cloud-service-usage-overview/CloudServiceUsageOverview.vue
- apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/cloud-service-usage-overview/CloudServiceUsageOverviewDetailModal.vue
This PR includes some refactoring and very simple bug fix code.
> fix: bind keyItemSets to CloudServiceUsageOverviewDetailModal and refresh filters in CloudServiceDetailPage

- apps/web/src/lib/router-query-string.ts
> fix(lib): do not stringify if value is string in primitiveToQueryString helper

- apps/web/src/services/asset-inventory/collector/collector-history/CollectorHistoryPage.vue
- apps/web/src/services/asset-inventory/collector/collector-history/modules/NoCollectorModal.vue
> refactor: separate NoCollectorModal from CollectorHistoryPage and use useQueryTags composable

- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorServiceAccountsSection.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/AttachedServiceAccountForm.vue
> fix: correct dropdown items in AttachedServiceAccountForm and bind refresh in CollectorServiceAccountsSection

- apps/web/src/services/asset-inventory/collector/collector-main/collector-page-store.ts
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContentItem.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/collector-item-info/CollectorItemStatus.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/modals/CollectorRestartModal.vue
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
- changed restart collection button design
AS-IS
TO-BE
- feat(collector): apply changed design at current status
AS-IS
TO-BE
- apply refresh API after restart collector
🚨 plz check by commits
> feat(collector): changed restart collection button design

- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContentItem.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/collector-item-info/CollectorItemStatus.vue
- apply responsive screen at collector-item
> fix: apply responsive screen at collector-item

- apps/web/src/services/asset-inventory/collector/collector-main/modules/collector-item-info/CollectorItemSchedule.vue
- fixed bug about collector schedule toggle activation
> fix: fixed bug about collector schedule toggle activation

- apps/web/src/services/asset-inventory/collector/collector-main/modules/collector-item-info/CollectorItemJobList.vue
- fixed bug with history detail navigation button click event
> fix: fixed bug with history detail navigation button click event

- apps/web/src/services/asset-inventory/collector/collector-main/collector-page-store.ts
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContents.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/collector-item-info/CollectorItemJobList.vue
- apps/web/src/services/asset-inventory/collector/collector-main/type.ts
- hide the button to navigate to the task detail page when there are no tasks in the list
> feat(collector): hide the button to navigate job detail page

- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContents.vue
- changed search query key item sets
- add schedule
- remove unnecessary key item set
> feat(collector): changed search query key item sets

- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorBaseInfoSection.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorOptionsSection.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorScheduleSection.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorServiceAccountsSection.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/AttachedServiceAccountForm.vue
- apps/web/src/services/asset-inventory/routes.ts
> fix: fix design issues in CollectorDetailPage

- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorVersionForm.vue
> fix: check only if origin collector exist in CollectorVersionForm

- apps/web/src/services/dashboards/DashboardsLNB.vue
- apps/web/src/services/dashboards/widgets/_base/base-count-of-findings/BaseCountOfFindingsWidget.vue
> fix: fix minor bugs in BaseCountOfFindingsWidget and DashboardsLNB

- apps/web/src/services/asset-inventory/collector/shared/collector-forms/AttachedServiceAccountForm.vue
> feat(attached-service-account-form): fix query filter of  api params

- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContents.vue
> fix: fixed export excel bug

- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorOptionsForm.vue
> fix: update schema when provider changes in CollectorOptionsForm

- apps/web/src/services/asset-inventory/collector/collector-main/modules/collector-item-info/CollectorItemSchedule.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorScheduleForm.vue
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
- changed text at set/edit schedule
- apply timezone at collector schedule form
> feat(collector): apply minor QA about collector schedule form

- apps/web/src/services/asset-inventory/components/ProviderList.vue
SSIA
https://github.com/cloudforet-io/console/assets/50662170/d0be16d7-6ed9-45a1-bcb8-3004abdc425f
> fix(provider-list): fix display style

- apps/web/src/services/auth/sign-in/modules/SignInRightContainer.vue
- fixed css bug at sign-in page
> fix: fixed css bug at sign-in page

- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContents.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/collector-item-info/CollectorItemSchedule.vue
- fixed bug about setOnly of api query helper
- remove state / tags
- fixed warning code about schedule state at get collector list API
> fix: fixed bug about setOnly of api query helper

- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContents.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/collector-item-info/CollectorItemSchedule.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorScheduleForm.vue
- apps/web/src/services/asset-inventory/components/ProviderList.vue
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat(collector): apply minor QA and fixed bug

- apps/web/src/common/components/forms/vue-diff/Code.vue
- apps/web/src/services/dashboards/dashboard-detail/modules/dashboard-widget-container/composables/use-widget-reformer.ts
> fix: edit css bug in cloud service history changes & add optional chaining

- apps/web/src/services/dashboards/widgets/_helpers/widget-table-helper.ts
- apps/web/src/services/dashboards/widgets/asset-widgets/total-failure-and-severity/TotalFailureAndSeverityWidget.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/trend-of-pass-and-fail-findings/TrendOfPassAndFailFindingsWidget.vue
- apps/web/src/services/dashboards/widgets/type.ts
> fix: fix data bugs in asset widgets & fix chart style

- apps/web/src/common/components/forms/vue-diff/Code.vue
- apps/web/src/common/modules/page-layouts/CenteredPageLayout.vue
- apps/web/src/services/asset-inventory/collector/collector-create/CollectorCreatePage.vue
- apps/web/src/services/asset-inventory/collector/collector-create/modules/CreateCollectorStep1.vue
- apps/web/src/services/asset-inventory/collector/collector-create/modules/Step1SearchFilter.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContents.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/collector-item-info/CollectorItemSchedule.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorScheduleForm.vue
- apps/web/src/services/asset-inventory/components/ProviderList.vue
- apps/web/src/services/dashboards/dashboard-detail/modules/dashboard-widget-container/composables/use-widget-reformer.ts
- apps/web/src/services/dashboards/widgets/_helpers/widget-table-helper.ts
- apps/web/src/services/dashboards/widgets/asset-widgets/total-failure-and-severity/TotalFailureAndSeverityWidget.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/trend-of-pass-and-fail-findings/TrendOfPassAndFailFindingsWidget.vue
- apps/web/src/services/dashboards/widgets/type.ts
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> fix: fix bugs in collector / dashboard page

- apps/web/src/services/dashboards/modules/dashboard-toolset/DashboardDateDropdown.vue
[[Minor] Dashboard - Date Selection 동작 이슈](https://pyengine.atlassian.net/browse/QA-564)
> fix: fix index error in DashboardDateDropdown

- apps/web/src/services/asset-inventory/collector/collector-create/modules/CreateCollectorStep4.vue
> fix(create-collector-step4): fix query params of create api request

- apps/web/src/services/dashboards/modules/dashboard-toolset/DashboardDateDropdown.vue
> fix: fix index error in DashboardDateDropdown (#1359)

- apps/web/src/services/asset-inventory/collector/collector-create/CollectorCreatePage.vue
- apps/web/src/services/dashboards/modules/dashboard-toolset/DashboardDateCustomRangeModal.vue
- apps/web/src/services/dashboards/modules/dashboard-toolset/DashboardDateDropdown.vue
> fix: fix bug in DashboardDateDropdown

- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorServiceAccountsSection.vue
> feat(collector-service-accounts-section): apply timezoneFormatter

- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorOptionsSection.vue
> fix: apply order to CollectorOptionsSection

- apps/web/src/services/asset-inventory/collector/collector-main/modules/collector-item-info/CollectorItemJobList.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/collector-item-info/CollectorItemStatus.vue
- fixed bug about current status
https://pyengine.atlassian.net/browse/QA-602
- fixed router link at job error icon
https://pyengine.atlassian.net/browse/QA-604
- fixed bug about current status diff time
> fix: fixed bug about collect schedule

- apps/web/src/services/asset-inventory/collector/collector-detail/CollectorDetailPage.vue
> fix: do not show collector history button if job doesn't exist in CollectorDetailPage

- apps/web/src/App.vue
- apps/web/src/common/modules/portals/HandbookButton.vue
- apps/web/src/services/alert-manager/AlertManagerContainer.vue
- apps/web/src/services/asset-inventory/AssetInventoryContainer.vue
- apps/web/src/services/cost-explorer/CostExplorerContainer.vue
- apps/web/src/services/dashboards/widgets/_components/WidgetFrame.vue
- apps/web/src/store/modules/settings/actions.ts
- apps/web/src/store/modules/settings/plugins.ts
- apps/web/src/store/modules/user/actions.ts
- apps/web/src/store/modules/user/index.ts
- apps/web/src/store/modules/user/plugins.ts
- apps/web/src/store/util.ts
> fix: apply LocalStorageAccessor

- packages/core-lib/__tests__/query/__tests__/index.test.ts
- packages/core-lib/src/query/config.ts
- packages/core-lib/src/query/type.ts
> feat(core-lib): add time diff operators to QueryHelper

- apps/web/src/router/index.ts
- apps/web/src/store/modules/user/index.ts
- packages/core-lib/src/space-connector/token-api.ts
> fix(core-lib): apply LocalStorageAccessor

- package-lock.json
- package.json
> build: update turbo version to the latest

- packages/mirinae/src/inputs/buttons/toggle-button/PToggleButton.stories.mdx
- packages/mirinae/src/inputs/buttons/toggle-button/PToggleButton.vue
- packages/mirinae/src/inputs/buttons/toggle-button/config.ts
- packages/mirinae/src/inputs/buttons/toggle-button/story-helper.ts
- spec update
- changed text 'stateText' from 'label'
- showStateText (true / false)
- position (right / left / top)
- spacing (sm = 4px, md=8px, lg=16px, space-between, none)
- plz check vue file
> feat(toggle-button):  toggle button spec update

- apps/web/package.json
- apps/web/playwright.config.ts
- package-lock.json
> build: upgrade playwright version to 1.35.1

- apps/web/src/services/administration/iam/user/modules/user-management-modal/modules/AdminRole.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/collector-item-info/CollectorItemSchedule.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorVersionForm.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisQueryFilter.vue
- apps/web/src/services/dashboards/dashboard-customize/modules/DashboardCustomizeSidebar.vue
- apps/web/src/services/notification/modules/notification-channel-item/NotificationChannelItem.vue
- apps/web/src/services/project/project-detail/project-alert/project-alert-event-rule/modules/EventRuleActionForm.vue
- packages/mirinae/src/inputs/buttons/toggle-button/PToggleButton.vue
- fixed state text style(font-size, font-weight) at mininae
- apply toggle-button new spec at console
> feat(toggle-button): apply toggle button new spec at console

- apps/web/src/common/modules/dropdown/currency-select-dropdown/CurrencySelectDropdown.vue
- apps/web/src/services/alert-manager/AlertManagerContainer.vue
- apps/web/src/services/alert-manager/alert/modules/NewAssignedAlertListCard.vue
- apps/web/src/services/alert-manager/store/alert-manager-settings-store.ts
- apps/web/src/services/asset-inventory/AssetInventoryContainer.vue
- apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/CloudServiceDetailPage.vue
- apps/web/src/services/asset-inventory/store/asset-inventory-settings-store.ts
- apps/web/src/services/cost-explorer/CostExplorerContainer.vue
- apps/web/src/services/cost-explorer/store/cost-analysis-page-store.ts
- apps/web/src/services/cost-explorer/store/cost-explorer-dashboard-store.ts
- apps/web/src/services/cost-explorer/store/cost-explorer-settings-store.ts
It was a bug caused by not maintaining the userId value in its latest state.
> fix: fix to keep userId up to date

- apps/web/src/services/alert-manager/AlertManagerContainer.vue
- apps/web/src/services/asset-inventory/AssetInventoryContainer.vue
- apps/web/src/services/cost-explorer/CostExplorerContainer.vue
I have made modifications so that the store value is saved when there is no existing user setting value in localStorage.
> fix: fix store and local storage synchronization bug

- apps/web/src/common/modules/portals/HandbookButton.vue
> fix(handbook): improved to be stored on local storage based on user ID

- apps/web/src/services/project/project-detail/project-alert/project-webhook/ProjectWebhookPage.vue
> fix: load plugin reference items on ProjectWebhookPage

- packages/mirinae/src/data-display/field-title/PFieldTitle.stories.mdx
- packages/mirinae/src/data-display/field-title/PFieldTitle.vue
- packages/mirinae/src/data-display/field-title/config.ts
- packages/mirinae/src/data-display/field-title/story-helper.ts
- update field title spec at mirinae
- left / right / button slot
- font size / font weight / color
> feat(field-title): update field title spec at mirinae

- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorVersionForm.vue
- packages/mirinae/src/data-display/field-title/PFieldTitle.stories.mdx
- packages/mirinae/src/data-display/field-title/PFieldTitle.vue
- packages/mirinae/src/data-display/field-title/story-helper.ts
- update field title spec at console
> feat(field-title):  update field title spec at console

- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorVersionForm.vue
- packages/mirinae/src/data-display/field-title/PFieldTitle.stories.mdx
- packages/mirinae/src/data-display/field-title/PFieldTitle.vue
- packages/mirinae/src/data-display/field-title/config.ts
- packages/mirinae/src/data-display/field-title/story-helper.ts
- merge to master
- update field title spec
> feat(field-title):  update field title spec

- apps/web/src/App.vue
- apps/web/src/services/cost-explorer/CostExplorerContainer.vue
- apps/web/src/services/dashboards/dashboard-detail/modules/dashboard-widget-container/DashboardWidgetContainer.vue
- apps/web/src/services/info/InfoContainer.vue
- apps/web/src/store/modules/settings/actions.ts
> fix(settings-store): add initSettings dispatch to App component

- packages/mirinae/src/data-display/field-title/PFieldTitle.vue
- packages/mirinae/src/inputs/buttons/toggle-button/PToggleButton.stories.mdx
- packages/mirinae/src/inputs/buttons/toggle-button/PToggleButton.vue
- packages/mirinae/src/inputs/buttons/toggle-button/config.ts
- packages/mirinae/src/inputs/buttons/toggle-button/story-helper.ts
- update toggle button spec at mirinae
- remove state text slot
- remove position > top
- remove spacing > none, lg
- remove style-type
> feat(toggle-button): update toggle button spec at mirinae

- apps/web/src/common/modules/navigations/lnb/LNB.vue
- apps/web/src/services/administration/iam/user/modules/user-management-modal/modules/AdminRole.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/collector-item-info/CollectorItemSchedule.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorScheduleForm.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorVersionForm.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisQueryFilter.vue
- apps/web/src/services/dashboards/dashboard-customize/modules/DashboardCustomizeSidebar.vue
- apps/web/src/services/notification/modules/notification-channel-item/NotificationChannelItem.vue
- apps/web/src/services/project/project-detail/project-alert/project-alert-event-rule/modules/EventRuleActionForm.vue
- apply updated field-title and toggle-button spec at console
> feat: apply updated field-title and toggle-button spec at console

- apps/web/src/services/notification/modules/notification-channel-item/NotificationChannelItem.vue
- fixed notification activation alert bug
> fix: fixed notification activation alert bug

- apps/web/src/common/modules/custom-table/custom-field-modal/config.ts
- packages/mirinae/src/data-display/dynamic/dynamic-field/PDynamicField.stories.mdx
- packages/mirinae/src/data-display/dynamic/dynamic-field/type/field-schema.ts
- packages/mirinae/src/data-display/dynamic/dynamic-layout/templates/query-search-table/index.vue
- packages/mirinae/src/data-display/dynamic/helper.ts
> feat(p-dynamic-field): add key_depth option

- apps/web/src/common/modules/navigations/lnb/LNB.vue
- apps/web/src/services/administration/iam/user/modules/user-management-modal/modules/AdminRole.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/collector-item-info/CollectorItemSchedule.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorScheduleForm.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorVersionForm.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisQueryFilter.vue
- apps/web/src/services/dashboards/dashboard-customize/modules/DashboardCustomizeSidebar.vue
- apps/web/src/services/notification/modules/notification-channel-item/NotificationChannelItem.vue
- apps/web/src/services/project/project-detail/project-alert/project-alert-event-rule/modules/EventRuleActionForm.vue
- packages/mirinae/src/data-display/field-title/PFieldTitle.vue
- packages/mirinae/src/inputs/buttons/toggle-button/PToggleButton.stories.mdx
- packages/mirinae/src/inputs/buttons/toggle-button/PToggleButton.vue
- packages/mirinae/src/inputs/buttons/toggle-button/config.ts
- packages/mirinae/src/inputs/buttons/toggle-button/story-helper.ts
- apply updated field-title and toggle-button spec
> feat: apply updated field-title and toggle-button spec

- apps/web/src/services/administration/iam/user/modules/user-management-modal/modules/UserInfoForm.vue
- apply administration userId validation text
> fix: apply administration userId validation text

- apps/web/src/lib/component-util/dynamic-layout/index.ts
> feat(component-util): add options parameter for excel export to dynamicFieldsToExcelDataFields

- apps/web/src/services/dashboards/shared/dashboard-variables/DashboardVariablesMoreButton.vue
- apps/web/src/services/dashboards/shared/dashboard-variables/DashboardVariablesSelectDropdown.vue
- apps/web/tests/dashboards/create-dashboards/create-compliacne-overview-dashboard.spec.ts
- apps/web/tests/dashboards/create-dashboards/entire-workspace-dashboard.spec.ts
Please focus on the **description**.
> test: add test for creating asset dashboard

- apps/web/src/common/modules/widgets/DailyUpdates.vue
- apps/web/src/services/dashboards/config.ts
- apps/web/src/services/dashboards/dashboard-create/modules/dashboard-templates/templates/compliance-overview.ts
- apps/web/src/services/home-dashboard/modules/all-summary/AllSummary.vue
- apps/web/src/services/project/project-detail/project-summary/modules/ProjectBilling.vue
please see order by commits!!!
1. [[Main Dashboard] 데이터 로딩 이슈](https://pyengine.atlassian.net/browse/QA-609)
2. [[Project Dashboard] 프로젝트별로 Daily Updates 위젯에 데이터가 없을때 표시가 다름](https://pyengine.atlassian.net/browse/QA-611)
3. received quest orally
4. [[Project Dashboard] 프로젝트별로 Billing 위젯의 [Day], [Month] 탭 정상 작동여부가 상이함](https://pyengine.atlassian.net/browse/QA-610)
> fix: fix minor issues of dashboard

- apps/web/src/services/auth/authenticator/index.ts
- apps/web/src/store/modules/settings/actions.ts
> fix: get new currency rate if value in localStorage is default value

- apps/web/src/common/modules/widgets/DailyUpdates.vue
- apps/web/src/services/auth/authenticator/index.ts
- apps/web/src/services/dashboards/config.ts
- apps/web/src/services/dashboards/dashboard-create/modules/dashboard-templates/templates/compliance-overview.ts
- apps/web/src/services/home-dashboard/modules/all-summary/AllSummary.vue
- apps/web/src/services/project/project-detail/project-summary/modules/ProjectBilling.vue
- apps/web/src/store/modules/settings/actions.ts
> chore: revert commits

- apps/web/src/services/dashboards/shared/dashboard-toolset/DashboardDateDropdown.vue
- apps/web/src/services/dashboards/shared/dashboard-toolset/DashboardDateRangeBadge.vue
- apps/web/src/services/dashboards/widgets/_base/base-pie/BasePieWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-cloud-front-cost/AWSCloudFrontCostWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-by-region/AWSDataTransferByRegionWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-by-target/BudgetUsageByTarget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region/CostByRegionWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/cost-map/CostMapWidget.vue
[[Dashboards] 커스텀으로 저장되어있는 월데이터 이슈](https://pyengine.atlassian.net/browse/QA-617)
> feat: set `undefined` to dateRange when select 'current month' 

- apps/web/src/services/administration/iam/policy/policy-create/PolicyCreatePage.vue
- apps/web/src/services/administration/iam/policy/policy-detail/PolicyDetailPage.vue
- apps/web/src/services/asset-inventory/collector/collector-create/modules/Step1SearchFilter.vue
- apps/web/src/services/cost-explorer/budget/modules/budget-form/budget-form-amount-plan/BudgetFormAmountPlanMonthly.vue
- apps/web/src/services/cost-explorer/budget/modules/budget-form/budget-form-amount-plan/BudgetFormAmountPlanUnitSelect.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-input-form/DashboardWidgetInputForm.vue
- packages/mirinae/src/inputs/forms/field-group/PFieldGroup.vue
- fixed style bug at field group and field title
> fix: fixed style bug at field group and field title

- apps/web/src/services/administration/iam/user/lib/config.ts
> feat(administration): add tag search

- apps/web/src/services/dashboards/dashboard-create/modules/DashboardTemplateForm.vue
- apps/web/src/services/project/project-detail/project-summary/modules/ProjectRegionService.vue
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
Please...see <File changed> 🙏🏻🥲
- edit typo
- hide blur when its bottom
> fix: hide blur box when its bottom

- apps/web/src/common/modules/widgets/DailyUpdates.vue
- apps/web/src/services/auth/authenticator/index.ts
- apps/web/src/services/dashboards/config.ts
- apps/web/src/services/dashboards/dashboard-create/modules/dashboard-templates/templates/compliance-overview.ts
- apps/web/src/services/home-dashboard/modules/all-summary/AllSummary.vue
- apps/web/src/services/project/project-detail/project-summary/modules/ProjectBilling.vue
- apps/web/src/store/modules/settings/actions.ts
> fix: fix minor issues of dashboard & get new currency rate if value in localStorage is default value

- apps/web/src/services/auth/authenticator/index.ts
- apps/web/src/services/auth/sign-in/DomainAdminSignInPage.vue
- apps/web/src/store/modules/error/actions.ts
- apps/web/src/store/modules/user/actions.ts
- packages/core-lib/package.json
- packages/core-lib/src/space-connector/token-api.ts
> build(core-lib): update dev script

- apps/web/src/common/modules/navigations/gnb/modules/gnb-menu/modules/dashboard-recent-favorite/modules/GNBDashboardFavorite.vue
> fix: do not capitalize inGnbDashboardFavorite

- apps/web/src/services/dashboards/dashboard-create/modules/DashboardTemplateForm.vue
> fix(dashboard-create): filter list by regex test

- apps/web/src/services/dashboards/shared/dashboard-widget-input-form/DashboardWidgetInputForm.vue
> fix: set default inherit value when its exists

- apps/web/src/services/home-dashboard/modules/all-summary/AllSummary.vue
> feat: change from skeleton to spinner in AllSummary widget

- apps/web/src/services/dashboards/dashboard-main/DashboardsMainPage.vue
- apps/web/src/services/home-dashboard/modules/all-summary/AllSummary.vue
- packages/mirinae/src/translations/language-pack/en.json
- packages/mirinae/src/translations/language-pack/ja.json
- packages/mirinae/src/translations/language-pack/ko.json
> chore: edit css and language

- apps/web/Dockerfile
- turbo.json
> build: update turbo.json and Dockerfile

- apps/web/src/services/cost-explorer/budget/modules/BudgetPeriodSelect.vue
- packages/mirinae/src/inputs/datetime-picker/PDatetimePicker.vue
Finally!!!!!!!!
I fixed it!!!!!!!
> fix: fix start/end bug in budget create page

- apps/web/src/common/composables/amcharts5/map-chart-helper.ts
- apps/web/src/services/dashboards/dashboard-create/modules/dashboard-templates/helper.ts
- apps/web/src/services/dashboards/dashboard-create/modules/dashboard-templates/templates/blank.ts
- apps/web/src/services/dashboards/widgets/_base/base-pie/BasePieWidget.vue
- apps/web/src/services/dashboards/widgets/_base/base-trend/BaseTrendWidget.vue
- apps/web/src/services/dashboards/widgets/_components/WidgetDataTable.vue
- apps/web/src/services/dashboards/widgets/_components/WidgetFrame.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-cloud-front-cost/AWSCloudFrontCostWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-by-region/AWSDataTransferByRegionWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region/CostByRegionWidget.vue
- set default dashboard variables to blank template
- disable zoom in map widgets
- fix style bug of edit mode cover in customize page
[[Dashboards] 전체데이터 클릭 후 뒤로가기 시 대시보드 표시 불가 에러 발생](https://pyengine.atlassian.net/browse/QA-636)
> feat: set default dashboard variables to blank template & fix minor bugs of widgets

- apps/web/src/services/dashboards/widgets/_components/WidgetFrame.vue
- apps/web/src/services/project/project-detail/project-summary/modules/ProjectAllSummary.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> fix: edit language bug in AllSummary widget & fix provider color bug in ProjectAllSummary

- apps/web/src/services/dashboards/widgets/_base/base-pie/BasePieWidget.vue
- apps/web/src/services/dashboards/widgets/_base/base-trend/BaseTrendWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-cloud-front-cost/AWSCloudFrontCostWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-by-region/AWSDataTransferByRegionWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-summary/BudgetUsageSummaryWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region/CostByRegionWidget.vue
- apps/web/src/services/my-page/my-account/user-api-key/modules/APIKeyHandbook.vue
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> fix: fix TypeError when refreshing all widget & edit handbook code

- apps/web/src/services/administration/iam/user/modules/UserManagementTable.vue
- apps/web/src/services/administration/iam/user/modules/user-management-modal/UserManagementModal.vue
- apps/web/src/services/administration/iam/user/type.ts
- apps/web/src/services/administration/store/user-page-store.ts
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
- Remove the reset password form for external and API users during user update.
- API User
- External User
- Change the timing of API calls to close the modal after the call is made.
- Add error case when user update. (the same as the previous password)
> fix(administration): fixed bugs at administration when user update & add error case

- packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
> fix(select-dropdown): hide the menu on outside click

- apps/web/src/services/cost-explorer/cost-dashboard/modules/CostDashboardFilter.vue
> fix: remove empty filters when updating dashboard filters

- apps/web/src/store/modules/dashboard/getters.ts
> fix(dashboards): filter dashboards by regex

- packages/mirinae/src/data-display/tables/toolbox-table/PToolboxTable.vue
> fix(p-toolbox-table): if sorting button is clicked, add option with a value of 1 for pageStart

- apps/web/src/services/asset-inventory/collector/collector-main/collector-page-store.ts
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContentItem.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContents.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/CollectorDataModal.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/README.md
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/collector-data-modal-store.ts
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/type.ts
- create and apply collect data modal
> feat(collect-modal): apply collect data modal

- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContents.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/CollectorDataModal.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/modules/CollectorDataDefaultInner.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/modules/CollectorDataDuplicationInner.vue
> feat(collect-data-modal): apply duplication case and component separation

- apps/web/src/services/dashboards/widgets/_components/WidgetDataTable.vue
> fix(widget-data-table): check ellipsis on table resizing

- apps/web/src/services/asset-inventory/collector/collector-create/modules/CreateCollectorStep1.vue
- apps/web/src/services/asset-inventory/collector/collector-create/modules/Step1SearchFilter.vue
- apps/web/src/services/asset-inventory/collector/config.ts
- apps/web/src/services/asset-inventory/collector/model.ts
- apps/web/src/services/asset-inventory/collector/shared/CollectorPluginContents.vue
- Fix duplicate key error in collector-plugin-list
- Add margin-bottom to collector-plugin-list
- add repository badge and color
> feat(collector-create): add repository badge & fix css style code

- package-lock.json
- packages/core-lib/package.json
- packages/core-lib/src/index.ts
> refactor(core-lib): remove unused util helper and removed luxon

- apps/web/src/services/dashboards/dashboard-customize/modules/DashboardCustomizePageName.vue
https://github.com/cloudforet-io/console/assets/26986739/0bd92e49-6e57-440b-9784-cabc16bdcd37
> fix(dashboard-name): always show edit mode for title

- apps/web/src/services/asset-inventory/collector/collector-main/CollectorMainPage.vue
- apps/web/src/services/asset-inventory/collector/collector-main/collector-page-store.ts
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContentItem.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContents.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/collector-item-info/CollectorItemJobList.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/collector-item-info/CollectorItemSchedule.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/modals/CollectorScheduleModal.vue
- apps/web/src/services/asset-inventory/collector/collector-main/type.ts
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/CollectorDataModal.vue
- refactor collector main store's state (loading, visible, unnecessary actions)
- remove unnecessary code like blank
> refactor(collector-main): refactor collector main store and code

- apps/web/src/common/components/modals/ConfirmBackModal.vue
- apps/web/src/services/dashboards/dashboard-create/DashboardCreatePage.vue
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
https://github.com/cloudforet-io/console/assets/26986739/60883f59-79a7-45be-9c7c-aff122f88c72
> feat(dashboard-create): apply close button

- apps/web/src/services/cost-explorer/budget/modules/BudgetPeriodSelect.vue
- apps/web/src/services/dashboards/dashboard-create/modules/DashboardTemplateForm.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-summary/BudgetUsageSummaryWidget.vue
> fix: fix datetimePicker & set text color to budget summary widget & fix blur effect

- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContents.vue
- apps/web/src/services/asset-inventory/collector/collector-main/type.ts
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/CollectorDataModal.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/collector-data-modal-store.ts
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/modules/CollectorDataDefaultInner.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/modules/CollectorDataDuplicationInner.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/type.ts
> fix: fixing the type error when activating the 'collect data' modal and refactor

- apps/web/src/common/composables/date-range-formatter/__tests__/index.test.ts
- apps/web/src/common/composables/date-range-formatter/index.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-summary/BudgetUsageSummaryWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/monthly-cost/MonthlyCostWidget.vue
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat(dashboard): change language code and use formatted date for widgets

- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContentItem.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/CollectorDataModal.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/collector-data-modal-store.ts
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/modules/CollectorDataDuplicationInner.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/type.ts
> feat(collect-data-modal): apply real data

- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisPeriodSelectDropdown.vue
- apps/web/src/services/cost-explorer/cost-dashboard/modules/CostDashboardPeriodSelectDropdown.vue
- apps/web/src/services/dashboards/shared/dashboard-toolset/DashboardDateDropdown.vue
- apps/web/src/services/dashboards/widgets/_components/CustomDateRangeModal.vue
- packages/mirinae/src/inputs/datetime-picker/PDatetimePicker.vue
Finally...fix bug of datetime picker!!!!
> fix: fix datetime picker bug

- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisPeriodSelectDropdown.vue
- apps/web/src/services/cost-explorer/cost-dashboard/modules/CostDashboardPeriodSelectDropdown.vue
- apps/web/src/services/dashboards/shared/dashboard-toolset/DashboardDateDropdown.vue
- apps/web/src/services/dashboards/widgets/_components/CustomDateRangeModal.vue
- packages/mirinae/src/inputs/datetime-picker/PDatetimePicker.vue
> fix: fix datetime picker bug (#1468)

- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContents.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/collector-item-info/CollectorItemStatus.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/CollectorDataModal.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/modules/CollectorDataDuplicationInner.vue
SSIA
- definition table column > separate area
> refactor: refactor status bar at duplication collect data modal

- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContentItem.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/collector-item-info/CollectorItemJobList.vue
SSIA
- Desktop
- Tablet
- Mobile
> feat(collector-main): apply screen reactivation

- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorServiceAccountsSection.vue
> fix(collector-detail): remove secret id at service account section

- apps/web/src/services/administration/iam/user/modules/user-management-modal/modules/NotificationEmailForm.vue
- apps/web/src/services/administration/iam/user/modules/user-management-modal/modules/UserInfoForm.vue
> feat(administration): apply spaceone placeholder for SAAS

- apps/web/src/services/asset-inventory/collector/shared/collector-forms/AttachedServiceAccountForm.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorOptionsForm.vue
- apps/web/src/services/dashboards/dashboard-create/DashboardCreatePage.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> fix(collector-create): fix page design of step3

- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat(translation): add translation

- apps/web/src/common/composables/last-item-observer/index.ts
- apps/web/src/services/asset-inventory/collector/collector-create/CollectorCreatePage.vue
- apps/web/src/services/asset-inventory/collector/collector-create/modules/CreateCollectorStep1.vue
- packages/mirinae/src/layouts/centered-layout/centered-layout-header/PCenteredLayoutHeader.vue
> feat(last-item-observer): add useLastItemObserver composable and refactor CollectorCreatePage

- apps/web/src/services/asset-inventory/collector/collector-create/modules/Step1SearchFilter.vue
- packages/mirinae/src/inputs/context-menu/PContextMenu.vue
- packages/mirinae/src/inputs/context-menu/context-menu-item/PContextMenuItem.stories.mdx
- packages/mirinae/src/inputs/context-menu/context-menu-item/PContextMenuItem.vue
- packages/mirinae/src/inputs/context-menu/context-menu-item/story-helper.ts
- packages/mirinae/src/inputs/context-menu/type.ts
> feat(p-context-menu): add iconColor props & apply to step1 search filter

- apps/web/src/services/dashboards/shared/dashboard-widget-input-form/helpers/schema-helper.ts
Fix widget create bug in blank dashboard
> fix: fix widget create bug in blank dashboard

- apps/web/src/services/asset-inventory/collector/collector-create/CollectorCreatePage.vue
- apps/web/src/services/asset-inventory/collector/collector-create/modules/CreateCollectorStep1.vue
- apps/web/src/services/dashboards/dashboard-create/DashboardCreatePage.vue
- apps/web/src/services/dashboards/dashboard-create/modules/DashboardTemplateForm.vue
- packages/mirinae/src/layouts/centered-layout/PCenteredLayout.vue
> fix: set flex-start if contents overflow the wrapper at PCenteredLayout & modify pages

- apps/web/src/services/asset-inventory/collector/collector-history/CollectorHistoryPage.vue
> feat(collector-history): changed collector history planning

- apps/web/src/services/dashboards/shared/dashboard-widget-input-form/helpers/schema-helper.ts
> fix: fix widget create bug in blank dashboard (#1482)

- packages/mirinae/src/layouts/centered-layout/centered-layout-header/PCenteredLayoutHeader.stories.mdx
- packages/mirinae/src/layouts/centered-layout/centered-layout-header/PCenteredLayoutHeader.vue
laptop size
mobile, tablet size
at web console
> fix(centered-layout-header): make close button as absolute

- .github/workflows/pull_request_review.yml
> ci: update review ci

- apps/web/src/services/dashboards/widgets/_components/CustomDateRangeModal.vue
> fix: datepicker event bug in CustomDateRangeModal

- apps/web/src/services/asset-inventory/collector/collector-create/modules/CreateCollectorStep3.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/AttachedServiceAccountForm.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorOptionsForm.vue
> fix(collector-create): fix design in step3

- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> fix: fix AllSummary text bug

- apps/web/src/services/asset-inventory/collector/collector-history/CollectorHistoryPage.vue
- apps/web/src/services/asset-inventory/collector/collector-history/collect-job/modules/JobStatusChart.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContentItem.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/collector-item-info/CollectorItemJobList.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/collector-item-info/CollectorItemSchedule.vue
- apps/web/src/services/asset-inventory/collector/collector-main/type.ts
- apps/web/src/services/asset-inventory/collector/shared/CollectorCurrentStatus.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/modules/CollectorDataDuplicationInner.vue
- apps/web/src/services/asset-inventory/collector/type.ts
- apply changed collector state types
- fixed progress bar style
- selecting and applying necessary data from props
- `IN_PROGRESS`
- `FAILURE`
- `CANCELED`
- `SUCCESS`
plz check by commits
> feat: apply changed collector state types and refactor

- apps/web/src/services/dashboards/widgets/_components/CustomDateRangeModal.vue
> fix: datepicker event bug in CustomDateRangeModal (#1490)

- packages/mirinae/src/inputs/select-status/PSelectStatus.stories.mdx
- packages/mirinae/src/inputs/select-status/PSelectStatus.vue
- packages/mirinae/src/inputs/select-status/story-helper.ts
> feat(select-status): add icon color

- packages/mirinae/src/inputs/context-menu/PContextMenu.stories.mdx
- packages/mirinae/src/inputs/context-menu/PContextMenu.vue
- packages/mirinae/src/inputs/context-menu/story-helper.ts
- packages/mirinae/src/inputs/dropdown/filterable-dropdown/PFilterableDropdown.vue
- packages/mirinae/src/inputs/dropdown/filterable-dropdown/story-helper.ts
SSIA
Could you confirm if the slot name is appropriate?
> feat(mirinae): add header slot to PContextMenu

- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/CollectorDataModal.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/modules/CollectorDataDefaultInner.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/modules/CollectorDataDuplicationInner.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/type.ts
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
- selecting and applying necessary data from props
- apply changed API spec
- add translation
> feat(collect-data-modal): apply changed collector state types and changed API spec

- apps/web/src/services/alert-manager/alert-dashboard/modules/AlertStateWidget.vue
- apps/web/src/services/alert-manager/alert/alert-detail/modules/alert-summary/AlertSummary.vue
- apps/web/src/services/alert-manager/alert/modules/AlertActions.vue
- apps/web/src/services/alert-manager/modules/AlertListItem.vue
- apps/web/src/services/asset-inventory/collector/collector-history/CollectorHistoryPage.vue
- apps/web/src/services/asset-inventory/collector/shared/CollectorCurrentStatus.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/modules/CollectorDataDuplicationInner.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorOptionsForm.vue
- apps/web/src/services/dashboards/dashboard-customize/modules/DashboardCustomizeSidebar.vue
- apps/web/src/services/dashboards/widgets/_components/WidgetFrame.vue
- apps/web/src/services/project/project-detail/project-alert/project-alert-settings/ProjectAlertSettingsPage.vue
- packages/mirinae/src/data-display/tags/PTag.vue
- packages/mirinae/src/feedbacks/alert/notice-alert/PNoticeAlert.vue
- packages/mirinae/src/feedbacks/alert/toast-alert/PToastAlert.vue
- packages/mirinae/src/feedbacks/modals/button-modal/PButtonModal.vue
> feat(ic_error-filled): apply changed icon 

- apps/web/src/common/components/editor/ColorPicker.vue
- apps/web/src/common/modules/navigations/gnb/modules/gnb-noti/modules/GNBNotiItem.vue
- apps/web/src/common/modules/navigations/gnb/modules/gnb-noti/modules/GNBNotificationsTab.vue
- apps/web/src/common/modules/navigations/gnb/modules/gnb-noti/type.ts
- apps/web/src/services/asset-inventory/collector/shared/CollectorJobStatusIcon.vue
> feat: apply changed icon

- apps/web/src/services/asset-inventory/collector/collector-history/CollectorHistoryPage.vue
- apps/web/src/services/asset-inventory/collector/collector-history/lib/formatter-helper.ts
> refactor: refactor collector history page and changed API spec

- apps/web/src/services/asset-inventory/collector/collector-history/CollectorHistoryPage.vue
- apps/web/src/services/asset-inventory/collector/collector-history/collect-job/CollectJobPage.vue
- apps/web/src/services/asset-inventory/collector/collector-history/collect-job/modules/JobBasicInformation.vue
- apps/web/src/services/asset-inventory/collector/collector-history/collect-job/modules/JobStatusChart.vue
- apps/web/src/services/asset-inventory/collector/collector-history/collect-job/modules/JobTaskTable.vue
- apps/web/src/services/asset-inventory/collector/collector-history/lib/formatter-helper.ts
- apps/web/src/services/asset-inventory/collector/collector-history/type.ts
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> refactor: refactor job task history page and changed API spec

- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorScheduleForm.vue
> feat: changed bg color at schedule form

- packages/mirinae/src/data-display/tables/toolbox-table/PToolboxTable.stories.mdx
- packages/mirinae/src/inputs/select-status/PSelectStatus.vue
- the style modification due to the 'ic_check' icon change
- fixed storybook path bug at toolbox-table
> feat(select-status): the style modification due to the 'ic_check' icon change & minor bug

- apps/web/src/services/dashboards/shared/dashboard-widget-input-form/DashboardWidgetInputForm.vue
- apps/web/src/services/dashboards/widgets/_components/WidgetViewModeModal.vue
- apps/web/src/services/dashboards/widgets/_components/WidgetViewModeSidebar.vue
> feat: add widget form sidebar to view mode modal

- apps/web/src/services/asset-inventory/collector/collector-main/collector-page-store.ts
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContentItem.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/collector-item-info/CollectorItemJobList.vue
- apps/web/src/services/asset-inventory/collector/collector-main/type.ts
- apps/web/src/services/asset-inventory/collector/model.ts
- apps/web/src/services/asset-inventory/collector/shared/CollectorCurrentStatus.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/collector-data-modal-store.ts
- Moved page related type declaration into `page-directory/type.ts`
- Renamed page related interfaces. Removed 'model' from the name.
> refactor: rename and move interfaces JobAnalyzeStatus, JobAnalyzeInfo

- apps/web/src/services/asset-inventory/collector/collector-detail/CollectorDetailPage.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/collector-job-store.ts
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectDataButtonGroup.vue
Added `collector-job-store` that is used in `CollectorDetailPage` that controls collector job information.
Added `CollectDataButtonGroup` that uses `collector-job-store`.
1. When there is recent job.
2. When there is no recent job.
> feat: add CollectDataButtonGroup and collector-job-store

- apps/web/src/services/asset-inventory/collector/shared/CollectorCurrentStatus.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/modules/CollectorDataDuplicationInner.vue
SSIA
- apply p-definition-table custom key width
- changed color
> feat: apply p-definition-table custom key width and changed style

- apps/web/src/services/asset-inventory/collector/collector-detail/CollectorDetailPage.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/collector-job-store.ts
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectDataButtonGroup.vue
Apply collecting status to the button popup.
> feat: apply CollectorCurrentStatus to CollectorDataButtonGroup

- apps/web/src/services/asset-inventory/collector/collector-history/CollectorHistoryPage.vue
- apps/web/src/services/asset-inventory/collector/collector-history/collect-job/CollectJobPage.vue
- apps/web/src/services/asset-inventory/collector/collector-history/collect-job/modules/JobStatusChart.vue
- apps/web/src/services/asset-inventory/collector/collector-history/collect-job/modules/JobTaskTable.vue
- apps/web/src/services/asset-inventory/collector/collector-main/CollectorMainPage.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContentItem.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContents.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorListNoData.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorNoData.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/collector-item-info/CollectorItemJobList.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/collector-item-info/CollectorItemSchedule.vue
> chore: changed template position at collector main & history page

- apps/web/src/services/asset-inventory/collector/collector-detail/CollectorDetailPage.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/collector-job-store.ts
https://github.com/cloudforet-io/console/assets/26986739/768bd6b2-6120-401e-a9d7-65f3507c18c1
> feat: apply job list api polling to CollectorDetailPage

- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContentItem.vue
- apps/web/src/services/asset-inventory/collector/shared/RecentCollectorJobList.vue
To reuse component, rename and move the directory.
> refactor: rename and move RecentCollectorJobList

- packages/mirinae/src/data-display/field-title/PFieldTitle.stories.mdx
- packages/mirinae/src/data-display/field-title/PFieldTitle.vue
- packages/mirinae/src/data-display/field-title/story-helper.ts
> feat(field-title): add inline prop

- apps/web/src/services/dashboards/widgets/_base/base-count-of-findings/BaseCountOfFindingsWidget.vue
- apps/web/src/services/dashboards/widgets/_base/base-pie/BasePieWidget.vue
- apps/web/src/services/dashboards/widgets/_base/base-trend/BaseTrendWidget.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/compliance-check-status/ComplianceCheckStatusWidget.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/severity-status-by-service/SeverityStatusByServiceWidget.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/total-failure-and-severity/TotalFailureAndSeverityWidget.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/trend-of-pass-and-fail-findings/TrendOfPassAndFailFindingsWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-cloud-front-cost/AWSCloudFrontCostWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-by-region/AWSDataTransferByRegionWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-cost-trend/AWSDataTransferCostTrendWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/budget-status/BudgetStatus.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-by-target/BudgetUsageByTarget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-summary/BudgetUsageSummaryWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region/CostByRegionWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/cost-map/CostMapWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/monthly-cost/MonthlyCostWidget.vue
- packages/core-lib/src/space-connector/cancallable-fetcher.ts
New helper for token cancelation!
Currently, it is only applied to the **widget**, but soon, all code that uses `cancelToken` will be modified.
> feat: add `getCancellableFetcher`

- apps/web/src/services/asset-inventory/collector/collector-create/modules/CreateCollectorStep2.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorBaseInfoSection.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorPluginInfo.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorTags.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/PluginSummaryCards.vue
- apps/web/src/services/asset-inventory/collector/shared/CollectorPluginContents.vue
> feat: update CollectorDetailPage BaseInfoSection UI

- apps/web/src/services/dashboards/widgets/_base/base-count-of-findings/BaseCountOfFindingsWidget.vue
- apps/web/src/services/dashboards/widgets/_base/base-pie/BasePieWidget.vue
- apps/web/src/services/dashboards/widgets/_base/base-trend/BaseTrendWidget.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/compliance-check-status/ComplianceCheckStatusWidget.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/severity-status-by-service/SeverityStatusByServiceWidget.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/total-failure-and-severity/TotalFailureAndSeverityWidget.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/trend-of-pass-and-fail-findings/TrendOfPassAndFailFindingsWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-cloud-front-cost/AWSCloudFrontCostWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-by-region/AWSDataTransferByRegionWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-cost-trend/AWSDataTransferCostTrendWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/budget-status/BudgetStatus.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-by-target/BudgetUsageByTarget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-summary/BudgetUsageSummaryWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region/CostByRegionWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/cost-map/CostMapWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/monthly-cost/MonthlyCostWidget.vue
- packages/core-lib/src/space-connector/cancallable-fetcher.ts
> feat: change return value of `getCancellableFetcher`

- apps/web/src/services/asset-inventory/collector/collector-detail/modules/AttachedServiceAccounts.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorServiceAccountsSection.vue
SSIA!
+ Added totalCount to the heading.
> refactor: separate table from CollectorServiceAccountSection

- packages/mirinae/src/inputs/radio/PRadio.stories.mdx
- packages/mirinae/src/inputs/radio/PRadio.vue
- packages/mirinae/src/inputs/radio/story-helper.ts
> feat(radio): add readonly prop

- apps/web/src/services/asset-inventory/collector/collector-detail/modules/AttachedServiceAccounts.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/AttachedServiceAccountForm.vue
> feat: add selected service account type to AttachedServiceAccounts

- apps/web/src/services/asset-inventory/collector/collector-detail/CollectorDetailPage.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/AttachedServiceAccounts.vue
- apps/web/src/services/asset-inventory/collector/model.ts
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/CollectorDataModal.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/collector-data-modal-store.ts
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/modules/CollectorDataDefaultInner.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/type.ts
https://github.com/cloudforet-io/console/assets/26986739/d996fbfa-a88a-4def-bbb4-710599bd5466
I think there are some bugs for collection of individual secrets in CollectorDataModal.
> feat: apply collect data modal to CollectDetailPage

- apps/web/src/services/notification/notification-add/modules/AddNotificationData.vue
SSIA
- add spaceone user channel
- add email channel
> fix: notification channel bug fixed

- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorTags.vue
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> fix: add empty case for tags in CollectorDetailPage

- apps/web/src/services/asset-inventory/collector/shared/RecentCollectorJobList.vue
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
Add empty case
Fix some of css differences from figma - make job items contents flex-end
> fix: add empty case for RecentCollectorJobList

- apps/web/src/services/asset-inventory/collector/collector-detail/CollectorDetailPage.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/collector-job-store.ts
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/AttachedServiceAccounts.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectDataButtonGroup.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorBaseInfoSection.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/PluginSummaryCards.vue
- apps/web/src/services/asset-inventory/collector/shared/CollectorCurrentStatus.vue
- apps/web/src/services/asset-inventory/collector/shared/RecentCollectorJobList.vue
> feat: apply recent collector jobs to detail page

- apps/web/src/services/asset-inventory/collector/collector-create/modules/CreateCollectorStep4.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorScheduleSection.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/modals/CollectorScheduleModal.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorScheduleForm.vue
SSIA
- schedule off
- schedule on
- edit mode
> feat: apply changed edit design at schedule form

- apps/web/package.json
- apps/web/src/lib/config.ts
- package-lock.json
- package.json
- vercel.json
> feat: use vercel

- apps/web/src/services/asset-inventory/collector/shared/CollectorJobStatusIcon.vue
- apps/web/src/services/asset-inventory/collector/shared/RecentCollectorJobList.vue
> feat: add fullMode to RecentCollectorJobList for detail page

- apps/web/src/services/dashboards/shared/dashboard-variables/DashboardVariablesSelectDropdown.vue
- apps/web/src/services/dashboards/widgets/_components/WidgetViewModeModal.vue
- apps/web/src/services/dashboards/widgets/_components/WidgetViewModeSidebar.vue
- packages/language-pack/en.json
> chore: add zoom animation and edit minor style

- apps/web/src/services/dashboards/widgets/_components/WidgetViewModeModal.vue
- apps/web/src/services/dashboards/widgets/_components/WidgetViewModeSidebar.vue
- apps/web/src/services/dashboards/widgets/_helpers/widget-schema-helper.ts
- apps/web/src/services/dashboards/widgets/_hooks/use-widget-state.ts
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: show modal and badge when saving a form with non-inherited option included

- apps/web/src/router/service-routes.ts
> fix(route): fix redirect location if user is NoPermission

- packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.stories.mdx
- packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
- Apply  truncate at text and placeholder
- Storybook alignment customization
> feat(select-dropdown): apply  truncate at text and placeholder

- apps/web/src/services/my-page/my-account/user-account/modules/BaseInformation.vue
- apps/web/src/services/my-page/my-account/user-account/modules/ChangePassword.vue
- packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.stories.mdx
- packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
- packages/mirinae/src/inputs/dropdown/select-dropdown/story-helper.ts
- packages/mirinae/src/inputs/dropdown/select-dropdown/type.ts
- packages/mirinae/src/inputs/forms/json-schema-form/PJsonSchemaForm.stories.mdx
- packages/mirinae/src/inputs/forms/json-schema-form/PJsonSchemaForm.vue
SSIA
- PSelectDropdown
-PJsonSchemaForm
Plz check after #038415d by commits
> feat: apply fixed width prop for truncate

- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectDataButtonGroup.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorBaseInfoSection.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorOptionsSection.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorScheduleSection.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorServiceAccountsSection.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/SectionHeader.vue
> fix: show icon button on mobile size

- apps/web/src/services/dashboards/shared/dashboard-variables/DashboardVariablesDropdown.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-input-form/DashboardWidgetInputForm.vue
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
https://github.com/cloudforet-io/console/assets/18563857/4cdad327-72f4-4a9b-bee5-93ab739c698b
> feat: add Return to Initial Settings button to widget form

- apps/web/src/services/dashboards/shared/dashboard-variables/DashboardVariablesSelectDropdown.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-input-form/DashboardWidgetInputForm.vue
- apps/web/src/services/dashboards/widgets/_components/WidgetViewModeModal.vue
- apps/web/src/services/dashboards/widgets/_components/WidgetViewModeSidebar.vue
> fix: init widget form when close sidebar & fix refresh bug in modal

- apps/web/src/services/asset-inventory/collector/collector-history/CollectorHistoryPage.vue
- apps/web/src/services/asset-inventory/collector/collector-history/collect-job/CollectJobPage.vue
- apps/web/src/services/asset-inventory/collector/collector-history/collect-job/modules/JobBasicInformation.vue
- apps/web/src/services/asset-inventory/collector/collector-history/collect-job/modules/JobStatusChart.vue
- apps/web/src/services/asset-inventory/collector/collector-history/collect-job/modules/JobTaskTable.vue
- apps/web/src/services/asset-inventory/collector/collector-history/lib/formatter-helper.ts
- apps/web/src/services/asset-inventory/collector/collector-history/type.ts
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContents.vue
- apps/web/src/services/asset-inventory/collector/shared/RecentCollectorJobList.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorScheduleForm.vue
apply and check api at collector main, history page
- main
- history
- job task history
> feat: apply and check API

- apps/web/tests/asset-inventory/collector/collector-details/collect-data-all-accounts.ts
- apps/web/tests/asset-inventory/collector/collector-details/collect-data-one-account.ts
- apps/web/tests/asset-inventory/collector/collector-details/edit-collector.ts
> chore: add test code files to add directory structure

- apps/web/src/services/dashboards/shared/dashboard-variables/DashboardVariablesDropdown.vue
- apps/web/src/services/dashboards/widgets/_components/WidgetViewModeModal.vue
- packages/language-pack/en.json
> chore: edit minor things in view modal

- apps/web/package.json
- apps/web/src/lib/config.ts
- package-lock.json
- package.json
- vercel.json
> feat: use vercel (#1542)

- apps/web/src/services/asset-inventory/collector/collector-create/modules/CreateCollectorStep4.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/AttachedServiceAccounts.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorServiceAccountsSection.vue
- apps/web/src/services/asset-inventory/collector/model.ts
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/AttachedServiceAccountForm.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorOptionsForm.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/collector-form-store.ts
Apply exclude option api to CollectorCreatePage & CollectorDetailPage
Please check CollectorServiceAccountsSection on the collectorDetailPage.
> feat(create-collector): apply service account exclude option to api call 

- apps/web/src/services/asset-inventory/collector/collector-detail/collector-job-store.ts
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/AttachedServiceAccounts.vue
- apps/web/src/services/asset-inventory/collector/collector-history/collect-job/modules/JobTaskTable.vue
- apps/web/src/services/asset-inventory/collector/collector-main/collector-page-store.ts
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContentItem.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContents.vue
- apps/web/src/services/asset-inventory/collector/collector-main/type.ts
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/CollectorDataModal.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/collector-data-modal-store.ts
> feat: apply duplication case at collect-data-modal

- apps/web/src/services/asset-inventory/cloud-service/modules/CloudServiceToolbox.vue
> feat(cloud-service): add type select and sorting function to excel export

- apps/web/src/services/asset-inventory/collector/collector-detail/modules/PluginSummaryCards.vue
- apps/web/src/services/asset-inventory/collector/collector-main/CollectorMainPage.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContentItem.vue
- apps/web/src/services/asset-inventory/collector/shared/CollectorCurrentStatus.vue
- apps/web/src/services/asset-inventory/collector/shared/CollectorJobStatusIcon.vue
- apps/web/src/services/asset-inventory/collector/shared/RecentCollectorJobList.vue
- add history icon at collector main
- changed job status icon size
- when in mobile size, apply gradient
> feat: changed style

- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorBaseInfoSection.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorPluginInfo.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/PluginSummaryCards.vue
- apps/web/src/services/asset-inventory/collector/shared/CollectorPluginContents.vue
- apps/web/src/services/asset-inventory/collector/shared/RecentCollectorJobList.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorScheduleForm.vue
SSIA
- apply tooltip
- adjust plugin icon position
- apply min-width at collector-summary-card
- adjust gap at time-blocks
> feat: changed design at collector detail

- apps/web/tests/asset-inventory/collector/collector-details.spec.ts
- apps/web/tests/asset-inventory/collector/collector-details/collect-data-all-accounts.ts
- apps/web/tests/asset-inventory/collector/collector-details/collect-data-one-account.ts
- apps/web/tests/asset-inventory/collector/collector-details/edit-collector.ts
> chore: add temporary test files

- apps/web/src/services/dashboards/shared/dashboard-widget-input-form/DashboardWidgetMoreOptions.vue
- apps/web/src/services/dashboards/widgets/_components/WidgetViewModeModal.vue
- apps/web/src/services/dashboards/widgets/_components/WidgetViewModeSidebar.vue
> fix: fix reset widget options bug & change sidebar to absolute position

- apps/web/tests/asset-inventory/collector/collector-main/collector-list.spec.ts
> feat: apply test code for collector list at collector main page

- apps/web/src/services/dashboards/widgets/_components/WidgetViewModeModal.vue
> chore: add slide-left transition to sidebar

- apps/web/playwright/sample.env
- apps/web/src/services/asset-inventory/collector/collector-detail/CollectorDetailPage.vue
- apps/web/tests/asset-inventory/collector/collector-details.spec.ts
> fix: update job data right after click on the collect button and add test codes

- apps/web/src/services/asset-inventory/collector/collector-history/CollectorHistoryPage.vue
- apps/web/src/services/asset-inventory/collector/collector-history/lib/formatter-helper.ts
- apps/web/tests/asset-inventory/collector/collector-main/collect-data.spec.ts
> feat: apply test code for collect data at collector main page

- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContentItem.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/collector-item-info/CollectorItemSchedule.vue
- apps/web/src/services/asset-inventory/collector/shared/CollectorCurrentStatus.vue
- apps/web/tests/asset-inventory/collector/collector-main/edit-schedule.spec.ts
- apply test code for edit schedule at collector main page
- when the toggle is in the off state, 'no schedule' is always displayed
> feat: apply test code for edit schedule at collector main page and change current status case

- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> chore(language): jp/ko translation added

- apps/web/src/services/dashboards/shared/dashboard-toolset/DashboardCurrencySelectDropdown.vue
- apps/web/src/services/dashboards/shared/dashboard-toolset/DashboardDateDropdown.vue
- apps/web/src/store/modules/settings/mutations.ts
> feat: fix minor style bug and set default currency of settings store

- apps/web/tests/asset-inventory/collector/collector-details/collect-data.spec.ts
> chore: fix lint errors in collect-data.spec.ts

- apps/web/tests/asset-inventory/collector/collector-details/collect-data.spec.ts
> feat: Check the application of modal type based on the 'in-progress' state

- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/modules/CollectorDataDuplicationInner.vue
> chore: remove todo list

- apps/web/src/common/components/forms/tags-input-group/TagsInputGroup.vue
- apps/web/tests/asset-inventory/collector/collector-details/edit-collector.spec.ts
- apps/web/tests/asset-inventory/collector/collector-main/collect-data.spec.ts
- apps/web/tests/asset-inventory/collector/collector-main/collector-list.spec.ts
- apps/web/tests/asset-inventory/collector/collector-main/edit-schedule.spec.ts
SSIA
In the case of test 10-11, since there is no additional options data for the corresponding collector, the test encounters a situation where there is no data. In such cases, the test proceeds by checking the 'p-empty' element to confirm the absence of data.
> feat: apply test code for edit collector detail page and fixed minor bug for add tags

- apps/web/.eslintignore
- apps/web/tests/asset-inventory/collector/collector-details/collect-data.spec.ts
- apps/web/tests/dashboards/create-dashboards/create-compliacne-overview-dashboard.spec.ts
- apps/web/tests/dashboards/customize-dashboard/variables/custom-dashboard-variables.spec.ts
- apps/web/tests/dashboards/customize-dashboard/variables/managed-dashboard-variables.spec.ts
> test: removed unnecessary numbering from test case & update .eslintignore

- apps/web/src/services/asset-inventory/collector/collector-detail/CollectorDetailPage.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/collector-job-store.ts
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/AttachedServiceAccounts.vue
- apps/web/src/services/asset-inventory/collector/collector-main/collector-page-store.ts
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContentItem.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContents.vue
- apps/web/src/services/asset-inventory/collector/shared/CollectorCurrentStatus.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/CollectorDataModal.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/collector-data-modal-store.ts
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/modules/CollectorDataDuplicationInner.vue
https://pyengine.atlassian.net/browse/QA-687
https://pyengine.atlassian.net/browse/QA-688
- Displaying 'In-Progress' Status Even When Schedule Is Not Set But Collection Is Underway
- Change in Timing of Job List Invocation for bug fix
> API Invocation After Changing to the Visible State of the Collect Modal
> refactor: change in Timing of Job List Invocation for bug fix 

- apps/web/src/services/asset-inventory/collector/collector-history/CollectorHistoryPage.vue
- apps/web/src/services/asset-inventory/collector/collector-history/collect-job/modules/JobStatusChart.vue
- apps/web/src/services/asset-inventory/collector/collector-main/collector-page-store.ts
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContents.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/collector-item-info/CollectorItemSchedule.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/modules/CollectorDataDuplicationInner.vue
- Apply center alignment
https://pyengine.atlassian.net/browse/QA-693
- Remove margin-top at edit icon
https://pyengine.atlassian.net/browse/QA-696
- Changed bar color and status name at jobTaskDetail, collectDataModal
https://pyengine.atlassian.net/browse/QA-707
> feat: apply design qa

- apps/web/src/common/components/select/SelectBox.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/AttachedServiceAccountForm.vue
> fix: remove hover style if box is selected

- apps/web/src/services/asset-inventory/collector/collector-create/modules/CreateCollectorStep4.vue
> fix(create-collector-step4): modify loading spinner margin value

- apps/web/src/services/asset-inventory/collector/collector-history/CollectorHistoryPage.vue
- apps/web/src/services/asset-inventory/collector/shared/RecentCollectorJobList.vue
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
- Apply tooltip messages for each state
https://pyengine.atlassian.net/browse/QA-694
- Fixed korean translation at collect data modal
https://pyengine.atlassian.net/browse/QA-709
- Removed immediate API call code to fix intermittent filter clearing bug on the collector history page
https://pyengine.atlassian.net/browse/QA-699
> fix: fixed the incorrect phrase

- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContents.vue
- apps/web/src/services/asset-inventory/collector/collector-main/type.ts
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/CollectorDataModal.vue
> fix: fixed bug causing service account count mismatch

- apps/web/src/services/administration/iam/user/modules/UserManagementTable.vue
> fix: remove excel export from user page main table

- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorVersionForm.vue
- packages/mirinae/src/data-display/heading/PHeading.vue
In the case of auto upgrade mode, version is the same as selected, so I modified it accordingly.
> fix(collector-version-form): fix versions input validation

- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorServiceAccountsSection.vue
- fix typo
- fix params of update api
- add validation for the Attached Service Account form
[issue](https://pyengine.atlassian.net/browse/QA-706)
> fix(collector-service-accounts-section): fix typo and params & add validation

- apps/web/src/services/asset-inventory/collector/collector-history/CollectorHistoryPage.vue
- apps/web/src/services/asset-inventory/collector/collector-history/collect-job/modules/JobTaskTable.vue
SSIA
https://pyengine.atlassian.net/browse/QA-718
> fix: apply computed at statusList for translation

- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorTags.vue
> fix: sort tags by keys in CollectorTags

- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectDataButtonGroup.vue
- packages/mirinae/src/data-display/popover/PPopover.vue
- packages/mirinae/src/data-display/popover/story-helper.ts
Please refer to the preview.
- Updated PPopver component.
> fix(collect-data-button-group): show current status when status is in-progress

- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorBaseInfoSection.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorPluginInfo.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorVersionForm.vue
> fix: collector detail base info style bug fix

- apps/web/src/services/asset-inventory/collector/collector-create/modules/CreateCollectorStep4.vue
> fix(create-collector-step4): fix style bug of previous button

- apps/web/src/services/asset-inventory/collector/collector-detail/CollectorDetailPage.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/collector-job-store.ts
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorBaseInfoSection.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/PluginSummaryCards.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/CollectorDataModal.vue
> fix: get all jobs count to display history button

- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/CollectorDataModal.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/collector-data-modal-store.ts
SSIA
https://pyengine.atlassian.net/browse/QA-713
> feat: add state for getting job loading

- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContentItem.vue
SSIA
- https://pyengine.atlassian.net/browse/QA-721
> fix: right alignment

- apps/web/src/services/asset-inventory/collector/collector-create/modules/CreateCollectorStep4.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorScheduleSection.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/SectionHeader.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/modals/CollectorScheduleModal.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorScheduleForm.vue
> fix(collector-schedule-form): refactor schedule form

- apps/web/tests/asset-inventory/collector/collector-details/edit-collector.spec.ts
> feat: changed test scenario

- apps/web/package.json
- apps/web/src/common/pages/NoResourcePage.vue
- apps/web/src/components.d.ts
- apps/web/src/main.ts
- apps/web/src/services/auth/password/validation-email/ValidationEmailPage.vue
- apps/web/src/services/auth/sign-in/modules/SignInLeftContainer.vue
- package-lock.json
Create new lottie-player
- Install [vue3-lottie](https://github.com/megasanjay/vue3-lottie)
- Set new `lottie-player` component
Existing `lottie-vue-player` need to be deleted. But before deletion, check `lottiefiles` directory in `public` directory.
> build: set new lottie player

- apps/web/src/common/modules/navigations/gnb/modules/GNBLogo.vue
> fix: do not use dot in the img file name

- apps/web/src/services/administration/iam/role/modules/role-management-tab/RoleDetail.vue
- apps/web/src/services/alert-manager/alert/alert-detail/modules/alert-key-info/modules/AlertInfoProject.vue
- apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/cloud-service-history-detail/CloudServiceHistoryChangesTab.vue
- apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/cloud-service-history-detail/CloudServiceHistoryDetailNoteTab.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/AttachedServiceAccounts.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectDataButtonGroup.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorPluginInfo.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorTags.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/PluginSummaryCards.vue
- apps/web/src/services/asset-inventory/collector/collector-detail/modules/SectionHeader.vue
- apps/web/src/services/asset-inventory/collector/shared/CollectorCurrentStatus.vue
- apps/web/src/services/asset-inventory/collector/shared/CollectorJobStatusIcon.vue
- apps/web/src/services/asset-inventory/collector/shared/RecentCollectorJobList.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/CollectorDataModal.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/modules/CollectorDataDefaultInner.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/modules/CollectorDataDuplicationInner.vue
- apps/web/src/services/auth/sign-in/SignInPage.vue
- apps/web/src/services/cost-explorer/budget/BudgetPage.vue
- apps/web/src/services/dashboards/dashboard-detail/modules/DashboardControlButtons.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-input-form/DashboardWidgetInputForm.vue
- apps/web/src/services/dashboards/widgets/_components/WidgetFrame.vue
- apps/web/src/services/dashboards/widgets/_components/WidgetViewModeModal.vue
- apps/web/src/services/dashboards/widgets/_components/WidgetViewModeSidebar.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/compliance-check-status/ComplianceCheckStatusWidget.vue
- apps/web/src/services/project/project-detail/project-alert/project-alert-settings/modules/ProjectAutoRecoveryUpdateModal.vue
- apps/web/src/services/project/project-detail/project-summary/modules/ProjectAllSummary.vue
- apps/web/tsconfig.json
> fix: do not use $t at template

- apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/cloud-service-usage-overview/CloudServiceUsageOverview.vue
Just migration of missed file `CloudServiceUsageOverview.vue`
> fix(cloud-service-usage-overview): migration to vue3

- apps/web/src/common/modules/custom-table/custom-field-modal/modules/SelectCloudServiceTagColumns.vue
- apps/web/src/common/modules/navigations/gnb/modules/gnb-menu/modules/Integration-menu/IntegrationSubMenu.vue
- apps/web/src/services/administration/AdministrationLNB.vue
- apps/web/src/services/administration/additional-settings/provider/provider-add/ProviderAddPage.vue
- apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/cloud-service-usage-overview/CloudServiceUsageOverviewSummary.vue
- apps/web/src/services/auth/sign-in/external/KEYCLOAK/pages/KeycloakPage.vue
- apps/web/src/services/auth/sign-out/SignOutPage.vue
- apps/web/src/services/cost-explorer/widgets/CustomWidget.vue
- apps/web/src/services/dashboards/dashboard-customize/modules/DashboardCustomize.vue
- apps/web/src/services/dashboards/shared/dashboard-toolset/DashboardCurrencySelectDropdown.vue
> fix: use useStore for vuex store and do not use i18n.t

- apps/web/src/services/dashboards/dashboard-detail/DashboardDetailPage.vue
- apps/web/src/services/dashboards/widgets/_components/WidgetViewModeModal.vue
- apps/web/src/services/dashboards/widgets/_components/WidgetViewModeSidebar.vue
> fix: fix minor bugs in dashboard pages

- apps/web/src/services/auth/sign-in/SignInPage.vue
> fix(sign-in-page): add missed t function

- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorNoData.vue
- apps/web/src/services/auth/sign-in/SignInPage.vue
- apps/web/src/services/auth/sign-in/external/KEYCLOAK/pages/KeycloakPage.vue
- apps/web/src/services/auth/sign-out/SignOutPage.vue
- apps/web/src/services/dashboards/dashboard-customize/modules/DashboardCustomize.vue
> fix: do not use SpaceRouter in the vue instance

- apps/web/src/common/modules/custom-table/custom-field-modal/modules/ColumnItem.vue
- apps/web/src/common/modules/portals/HandbookButton.vue
- apps/web/src/main.ts
- apps/web/src/services/alert-manager/alert-dashboard/modules/AlertStateWidget.vue
- apps/web/src/services/alert-manager/alert/modules/AlertAcknowledgeModal.vue
- apps/web/src/services/cost-explorer/cost-dashboard/cost-dashboard-create/modules/CostDashboardCreateDefaultFilter.vue
- apps/web/src/services/cost-explorer/cost-dashboard/modules/CostDashboardDuplicateModal.vue
- apps/web/src/services/info/notice/modules/NoticeForm.vue
- apps/web/src/services/notification/modules/AddNotificationTopic.vue
- apps/web/src/services/project/project-detail/project-alert/project-alert-event-rule/modules/EventRuleActionForm.vue
- packages/mirinae/src/data-display/tables/data-table/PDataTable.vue
- packages/mirinae/src/inputs/checkbox-group/PCheckboxGroup.stories.mdx
- packages/mirinae/src/inputs/checkbox/PCheckBox.stories.mdx
- packages/mirinae/src/inputs/checkbox/PCheckbox.vue
- packages/mirinae/src/inputs/checkbox/story-helper.ts
> fix: use selected prop as v-model arg for p-checkbox component

- apps/web/src/services/auth/sign-in/DomainAdminSignInPage.vue
> chore: fixing the Issue of Unrecognized Router and Store

- apps/web/src/common/components/editor/MenuBar.vue
- apps/web/src/common/modules/custom-table/custom-field-modal/CustomFieldModal.vue
- apps/web/src/common/modules/modals/notification-email-modal/NotificationEmailModal.vue
- apps/web/src/common/modules/navigations/gnb/modules/gnb-menu/modules/dashboard-recent-favorite/modules/GNBDashboardFavorite.vue
- apps/web/src/services/administration/iam/policy/policy-create/PolicyCreatePage.vue
- apps/web/src/services/administration/iam/policy/policy-detail/PolicyDetailPage.vue
- apps/web/src/services/alert-manager/alert/alert-detail/modules/AlertStatusUpdate.vue
- apps/web/src/services/alert-manager/alert/alert-detail/modules/AlertTitleEditModal.vue
- apps/web/src/services/alert-manager/alert/alert-detail/modules/alert-key-info/modules/AlertInfoDescription.vue
- apps/web/src/services/alert-manager/alert/modules/AlertFormModal.vue
- apps/web/src/services/alert-manager/alert/modules/AlertResolveModal.vue
- apps/web/src/services/alert-manager/escalation-policy/modules/EscalationRulesInputForm.vue
- apps/web/src/services/cost-explorer/budget/budget-detail/modules/budget-notifications/BudgetNotificationsModal.vue
- apps/web/src/services/cost-explorer/budget/modules/budget-form/budget-form-amount-plan/BudgetFormAmountPlanAutofillModal.vue
- apps/web/src/services/cost-explorer/budget/modules/budget-form/budget-form-amount-plan/BudgetFormAmountPlanTotal.vue
- apps/web/src/services/cost-explorer/cost-dashboard/cost-dashboard-customize/modules/CostDashboardCustomizeSidebar.vue
- apps/web/src/services/dashboards/dashboard-customize/modules/DashboardCustomizeSidebar.vue
- apps/web/src/services/dashboards/dashboard-customize/modules/dashboard-manage-variable-overlay/DashboardManageVariableOptionsField.vue
- apps/web/src/services/my-page/my-account/user-account/modules/BaseInformation.vue
- packages/mirinae/src/data-display/tree/PTree.stories.mdx
- packages/mirinae/src/data-display/tree/PTree.vue
- packages/mirinae/src/feedbacks/modals/advanced/double-check-modal/PDoubleCheckModal.vue
- packages/mirinae/src/inputs/forms/field-group/PFieldGroup.stories.mdx
- packages/mirinae/src/inputs/input/text-input/PTextInput.stories.mdx
- packages/mirinae/src/inputs/textarea/PTextarea.stories.mdx
- packages/mirinae/src/inputs/textarea/PTextarea.vue
> fix: use add arg to v-model for p-textarea, p-text-input, p-popover, draggable components

- apps/web/src/services/administration/routes.ts
- apps/web/src/services/alert-manager/routes.ts
- apps/web/src/services/asset-inventory/routes.ts
- apps/web/src/services/cost-explorer/routes.ts
- apps/web/src/services/info/routes.ts
- apps/web/src/services/my-page/routes.ts
- apps/web/src/services/project/routes.ts
SSIA
Dynamic route path should be written with `/`.
> fix(route): edit dynamic route path name

- apps/web/src/services/auth/password/PasswordPage.vue
- apps/web/src/services/auth/password/modules/PasswordForm.vue
- apps/web/src/services/auth/password/validation-email/ValidationEmailPage.vue
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
SSIA
- If the token is invalid > error page
- If the token or link has expired > resend page
https://pyengine.atlassian.net/browse/QUEST-310
> feat: resending functionality for user invitations and expired password reset links

- apps/web/src/services/dashboards/dashboard-detail/DashboardDetailPage.vue
- apps/web/src/services/dashboards/widgets/_components/WidgetViewModeModal.vue
- apps/web/src/services/dashboards/widgets/_components/WidgetViewModeSidebar.vue
* chore: edit sidebar title style
* fix: fix style bug in view modal
* fix: fix dashboard search bug after adding labels
---------
> fix: fix minor bugs in dashboard pages (#1629)

- apps/web/package.json
- apps/web/src/services/auth/password/PasswordPage.vue
- apps/web/src/services/auth/password/modules/PasswordForm.vue
- apps/web/src/services/auth/password/validation-email/ValidationEmailPage.vue
- package-lock.json
- package.json
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: resending functionality for user invitations and expired password reset links(1.12.dev60)

- apps/web/src/common/modules/custom-table/custom-field-modal/modules/ColumnItem.vue
- apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/CloudServiceHistoryDateSelectDropdown.vue
- apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/cloud-service-history-detail/CloudServiceHistoryDetailOverlay.vue
- apps/web/src/services/asset-inventory/service-account/modules/ServiceAccountBaseInformationForm.vue
- apps/web/src/services/asset-inventory/service-account/modules/ServiceAccountCredentialsForm.vue
- apps/web/src/services/cost-explorer/budget/modules/budget-form/budget-form-amount-plan/BudgetFormAmountPlanUnitSelect.vue
- apps/web/src/services/cost-explorer/cost-dashboard/modules/CostDashboardPeriodSelectDropdown.vue
- apps/web/src/services/project/project-detail/project-alert/project-alert-event-rule/modules/EventRuleConditionForm.vue
- packages/mirinae/src/data-display/collapsible/collapsible-toggle/PCollapsibleToggle.vue
> fix(kebab): edit component using camel case

- apps/web/src/common/modules/navigations/gnb/modules/GNBSuggestionList.vue
- apps/web/src/common/modules/navigations/gnb/modules/gnb-search/modules/GNBSearchDropdown.vue
- apps/web/src/common/modules/navigations/gnb/modules/gnb-search/modules/GNBSearchInput.vue
- apps/web/src/services/administration/AdministrationContainer.vue
- apps/web/src/services/asset-inventory/collector/collector-create/modules/CreateCollectorStep1.vue
- packages/mirinae/src/inputs/search/search/PSearch.vue
> fix(is-focused): edit camel case to kebab case

- packages/mirinae/src/data-display/tables/toolbox-table/PToolboxTable.vue
> fix(p-toolbox-table): fix wrong default props

- apps/web/src/common/modules/custom-table/custom-field-modal/CustomFieldModal.vue
- apps/web/src/common/modules/navigations/gnb/modules/gnb-menu/modules/dashboard-recent-favorite/modules/GNBDashboardFavorite.vue
- apps/web/src/services/cost-explorer/cost-dashboard/cost-dashboard-customize/modules/CostDashboardCustomizeSidebar.vue
- apps/web/src/services/dashboards/dashboard-customize/modules/DashboardCustomizeSidebar.vue
- apps/web/src/services/dashboards/dashboard-customize/modules/dashboard-manage-variable-overlay/DashboardManageVariableOptionsField.vue
> fix: fix wrong slot prop name of draggable component (element)

- apps/web/src/services/asset-inventory/collector/collector-main/CollectorMainPage.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContentItem.vue
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContents.vue
> fix: fix collector main page errors

- packages/mirinae/src/foundation/icons/p-icons/icons.js
- packages/mirinae/src/inputs/buttons/icon-button/PIconButton.vue
SSIA
- `ic_history` / `ic_collect`
> fix(svg-icon): add missed icon

- apps/web/src/common/modules/navigations/lnb/LNB.vue
- apps/web/src/common/modules/portals/HandbookButton.vue
- apps/web/src/services/alert-manager/escalation-policy/modules/EscalationPolicyDataTable.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorNameForm.vue
- apps/web/src/services/dashboards/dashboard-create/modules/DashboardScopeForm.vue
- apps/web/src/services/dashboards/dashboard-create/modules/DashboardViewerForm.vue
- apps/web/src/services/dashboards/widgets/_components/DateRangeSelector.vue
> fix(event-name-convention): edit camel named event in console

- packages/mirinae/src/inputs/link/PLink.stories.mdx
- packages/mirinae/src/inputs/link/PLink.vue
- packages/mirinae/src/inputs/link/story-helper.ts
- packages/mirinae/src/inputs/link/type.ts
console pages are not yet updated!
> feat: renewal `PLink` component

- apps/web/src/services/dashboards/dashboard-main/DashboardsMainPage.vue
- apps/web/src/services/project/modules/ProjectCardList.vue
> fix: fix minor bugs in DashboardMainPage and ProjectPage

- apps/web/src/services/project/routes.ts
- packages/mirinae/src/data-display/dynamic/dynamic-chart/PDynamicChart.vue
- packages/mirinae/src/data-display/dynamic/dynamic-field/PDynamicField.vue
- packages/mirinae/src/data-display/dynamic/dynamic-layout/PDynamicLayout.vue
- packages/mirinae/src/data-display/dynamic/dynamic-layout/type/index.ts
- packages/mirinae/src/data-display/dynamic/dynamic-widget/PDynamicWidget.vue
> fix(p-dynamic-layout): solve dynamic-layout not working issue

- apps/web/src/common/modules/custom-table/custom-field-modal/CustomFieldModal.vue
- apps/web/src/common/modules/navigations/gnb/modules/gnb-profile/GNBProfile.vue
- apps/web/src/services/administration/routes.ts
- apps/web/src/services/alert-manager/routes.ts
- apps/web/src/services/asset-inventory/AssetInventoryLNB.vue
- apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/cloud-service-usage-overview/CloudServiceUsageOverviewDetailModal.vue
- apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/cloud-service-usage-overview/CloudServiceUsageOverviewSummary.vue
- apps/web/src/services/asset-inventory/cloud-service/modules/cloud-service-list/CloudServiceListCard.vue
- apps/web/src/services/asset-inventory/components/ProviderList.vue
- apps/web/src/services/asset-inventory/routes.ts
- packages/mirinae/src/inputs/checkbox/PCheckbox.vue
- packages/mirinae/src/inputs/radio/PRadio.vue
> fix(console): edit some wrong usage

- apps/web/src/lib/access-control/redirect-route-helper.ts
- apps/web/src/services/dashboards/dashboard-create/DashboardCreatePage.vue
- apps/web/src/services/dashboards/routes.ts
> fix(dashboards): fix some light issue

- apps/web/src/common/modules/custom-table/custom-field-modal/CustomFieldModal.vue
- apps/web/src/router/admin-domain-service-routes.ts
- apps/web/src/services/administration/routes.ts
- apps/web/src/services/alert-manager/routes.ts
- apps/web/src/services/asset-inventory/routes.ts
- apps/web/src/services/auth/routes.ts
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisQueryFilter.vue
- apps/web/src/services/cost-explorer/cost-dashboard/modules/DynamicWidget.vue
- apps/web/src/services/cost-explorer/routes.ts
- apps/web/src/services/cost-explorer/widgets/CustomWidget.vue
- apps/web/src/services/dashboards/routes.ts
- apps/web/src/services/home-dashboard/routes.ts
- apps/web/src/services/info/routes.ts
- apps/web/src/services/my-page/my-account/user-account/UserAccountPage.vue
- apps/web/src/services/my-page/routes.ts
- apps/web/src/services/project/routes.ts
- packages/mirinae/src/data-display/dynamic/dynamic-field/templates/more/index.vue
- packages/mirinae/src/data-display/dynamic/dynamic-layout/templates/popup/index.vue
- packages/mirinae/src/data-display/tables/data-table/PDataTable.vue
- packages/mirinae/src/feedbacks/modals/icon-modal/PIconModal.vue
- packages/mirinae/src/inputs/input/query-input/PQueryInput.vue
> fix(dynamic-import): edit wrong usage of dynamic-import & small issues and migrations

- packages/mirinae/src/inputs/link/PLink.stories.mdx
- packages/mirinae/src/inputs/link/PLink.vue
- packages/mirinae/src/inputs/link/story-helper.ts
> chore: change props name in PLink

- apps/web/src/services/asset-inventory/cloud-service/CloudServicePage.vue
- apps/web/src/services/auth/password/validation-email/ValidationEmailPage.vue
- apps/web/src/services/dashboards/dashboard-create/DashboardCreatePage.vue
- apps/web/src/services/notification/modules/AddNotificationLevel.vue
- apps/web/src/services/notification/notification-add/modules/AddNotificationData.vue
- apps/web/src/services/notification/notification-add/modules/NotificationAddForm.vue
> fix: fixed minor issue

- packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.stories.mdx
- packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
> chore: merge commits from master

- apps/web/src/services/home-dashboard/modules/CollectingProgress.vue
> fix: get collector data additionally  in CollectingProgress because job and collector model was changed

- apps/web/src/services/home-dashboard/modules/CollectingProgress.vue
> refactor: merge remote-tracking branch 'origin/master' into feature-vue3-migration

- apps/web/package.json
- apps/web/src/main.ts
- apps/web/src/router/admin-domain-service-routes.ts
- apps/web/src/services/administration/routes.ts
- apps/web/src/services/alert-manager/routes.ts
- apps/web/src/services/asset-inventory/routes.ts
- apps/web/src/services/auth/routes.ts
- apps/web/src/services/auth/sign-out/SignOutPage.vue
- apps/web/src/services/cost-explorer/routes.ts
- apps/web/src/services/dashboards/routes.ts
- apps/web/src/services/home-dashboard/routes.ts
- apps/web/src/services/info/routes.ts
- apps/web/src/services/my-page/routes.ts
- apps/web/src/services/project/routes.ts
- apps/web/src/shims-vuex.d.ts
- package-lock.json
- package.json
> fix: do not use defineAsyncComponent when configuring route components and merge master

- apps/web/playwright.config.ts
- apps/web/src/services/asset-inventory/collector/collector-detail/CollectorDetailPage.vue
- apps/web/tests/asset-inventory/collector/collector-create/create-collector-case1.spec.ts
- apps/web/tests/auth.setup.ts
Eslint warns against using await inside the loop. How about ignoring the rules in the test code?
> feat(create-collector): add test code for create collector

- apps/web/src/services/asset-inventory/collector/shared/RecentCollectorJobList.vue
> fix: fix link bug of RecentCollectorJobList

- apps/web/src/services/dashboards/dashboard-create/DashboardCreatePage.vue
- apps/web/src/services/dashboards/dashboard-create/modules/DashboardTemplateForm.vue
> refactor: resolving missing issues during the merge

- apps/web/src/services/alert-manager/alert-dashboard/modules/CurrentProjectStatusWidget.vue
- apps/web/src/services/alert-manager/alert-dashboard/modules/alert-history-widget/AlertHistoryChart.vue
- apps/web/src/services/cost-explorer/budget/budget-detail/modules/budget-summary/BudgetSummaryChart.vue
> fix: resolve chart dispose issue

- apps/web/src/services/asset-inventory/routes.ts
- apps/web/src/services/project/project-detail/ProjectDetailPage.vue
- apps/web/src/services/project/project-detail/project-alert/ProjectAlertPage.vue
- apps/web/src/services/project/routes.ts
> fix: use keep-alive inside the router-view

- apps/web/src/router/service-routes.ts
- apps/web/src/services/dashboards/routes.ts
- apps/web/src/services/project/routes.ts
> fix: use redirect in route config in correct way

- apps/web/src/common/composables/proxy-state/index.ts
- packages/mirinae/src/hooks/proxy-state/index.ts
SSIA
- `useProxyValue` composable will be moved to `Core-lib` soon.
> fix(use-proxy-value): remove duplicated event name

- apps/web/src/services/administration/routes.ts
- apps/web/src/services/alert-manager/routes.ts
- apps/web/src/services/dashboards/routes.ts
> fix(route): remove wrong flag

- apps/web/src/common/modules/navigations/gnb/modules/gnb-menu/GNBMenu.vue
- apps/web/src/common/modules/navigations/gnb/modules/gnb-menu/GNBSubMenu.vue
- apps/web/src/common/modules/navigations/gnb/modules/gnb-noti/GNBNoti.vue
- apps/web/src/common/modules/navigations/gnb/modules/gnb-profile/GNBProfile.vue
- apps/web/src/common/modules/navigations/gnb/modules/gnb-recent-favorite/GNBRecentFavorite.vue
- apps/web/src/common/modules/navigations/gnb/modules/gnb-recent-favorite/modules/GNBRecent.vue
- apps/web/src/common/modules/navigations/gnb/modules/gnb-search/GNBSearch.vue
- apps/web/src/services/asset-inventory/service-account/ServiceAccountPage.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisDataTable.vue
> fix(gnb-menu): do not hide menu if it's not shown on click outside

- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisStackedColumnChart.vue
- apps/web/src/services/dashboards/widgets/_helpers/widget-chart-helper.ts
> feat: use amcharts5 in cost analysis

- apps/web/src/services/cost-explorer/cost-analysis/CostAnalysisPage.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisChart.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisChartQuerySection.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisDataTable.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisGroupByFilter.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisGroupByFilterMore.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisGroupByFilterMoreModal.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisHeader.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisPeriodSelectDropdown.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisQueryFilter.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisSaveQueryFormModal.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisSetQueryModal.vue
- apps/web/src/services/cost-explorer/type.ts
> refactor: change files to script setup

- apps/web/src/services/cost-explorer/cost-analysis/CostAnalysisPage.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisChart.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisDataTable.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisHeader.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisQueryFilter.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisSetQueryModal.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisStackedColumnChart.vue
- apps/web/src/services/cost-explorer/lib/helper.ts
- apps/web/src/services/cost-explorer/store/cost-analysis-page-store.ts
> feat: delete `stack` from cost analysis page

- apps/web/src/services/cost-explorer/budget/BudgetPage.vue
- apps/web/src/services/cost-explorer/budget/modules/budget-list/BudgetList.vue
> refactor(budget-page): refactor to script setup

- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisPeriodSelectDropdown.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisQueryFilter.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisSaveQueryFormModal.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisSetQueryModal.vue
> feat: delete currency selector and period text from cost analysis filter

- apps/web/src/common/modules/navigations/lnb/LNB.vue
- apps/web/src/common/modules/navigations/lnb/modules/LNBMenuItem.vue
- apps/web/src/common/modules/navigations/lnb/modules/LNBRouterMenuItem.vue
- apps/web/src/common/modules/navigations/lnb/type.ts
SSIA
- Add new LNB menu spec (Dropdown)
> feat(l-n-b): add new LNB dropdown spec & LNB minor refactoring

- apps/web/src/services/cost-explorer/budget/modules/budget-list/BudgetList.vue
- apps/web/src/services/cost-explorer/budget/modules/budget-toolbox/BudgetToolbox.vue
> refactor(budget-toolbox): refactor to script setup & fix allPage prop sync bug

- apps/web/src/services/cost-explorer/CostExplorerLNB.vue
- apps/web/src/services/cost-explorer/modules/RelocateDashboardNotification.vue
> feat(relocate-notification): relocate-notification markup

- apps/web/src/common/modules/navigations/lnb/LNB.vue
- apps/web/src/common/modules/navigations/lnb/modules/LNBMenuItem.vue
- apps/web/src/common/modules/navigations/lnb/modules/LNBRouterMenuItem.vue
- apps/web/src/services/cost-explorer/CostExplorerLNB.vue
> fix(lnb): refactor lnb to script setup

- apps/web/src/services/cost-explorer/budget/shared/budget-form/budget-form-amount-plan/BudgetFormAmountPlanLastMonthsCost.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisChart.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisDataTable.vue
> fix: convert usd_cost to cost for cost analyze api v1

- apps/web/src/services/asset-inventory/collector/collector-history/CollectorHistoryPage.vue
- packages/mirinae/src/navigation/toolbox/type.ts
> feat: add table column and fix sorting bug

- apps/web/src/common/modules/navigations/lnb/modules/LNBRouterMenuItem.vue
- apps/web/src/common/modules/navigations/lnb/type.ts
- apps/web/src/services/cost-explorer/CostExplorerLNB.vue
> fix(lnb-menu-item): add new icon spec

- apps/web/src/services/cost-explorer/CostExplorerLNB.vue
- apps/web/src/services/cost-explorer/cost-analysis/CostAnalysisPage.vue
- apps/web/src/services/cost-explorer/routes.ts
- apps/web/src/store/modules/favorite/type.ts
> feat(cost-analysis): set default params in cost-analysis & set cost-query-set store in LNB

- apps/web/src/services/dashboards/DashboardsContainer.vue
- apps/web/src/services/dashboards/DashboardsLNB.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-container/DashboardWidgetContainer.vue
- apps/web/src/services/dashboards/widgets/_base/base-count-of-findings/BaseCountOfFindingsWidget.vue
- apps/web/src/services/dashboards/widgets/_base/base-pie/BasePieWidget.vue
- apps/web/src/services/dashboards/widgets/_base/base-trend/BaseTrendWidget.vue
- apps/web/src/services/dashboards/widgets/_components/CurrencySelectDropdown.vue
- apps/web/src/services/dashboards/widgets/_components/CustomDateRangeModal.vue
- apps/web/src/services/dashboards/widgets/_components/DashboardWidgetEditModal.vue
- apps/web/src/services/dashboards/widgets/_components/DateRangeSelector.vue
- apps/web/src/services/dashboards/widgets/_components/WidgetDataTable.vue
- apps/web/src/services/dashboards/widgets/_components/WidgetFrame.vue
- apps/web/src/services/dashboards/widgets/_components/WidgetFrameHeaderDropdown.vue
- apps/web/src/services/dashboards/widgets/_components/WidgetViewModeModal.vue
- apps/web/src/services/dashboards/widgets/_components/WidgetViewModeSidebar.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/compliance-check-status/ComplianceCheckStatusWidget.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/severity-status-by-service/SeverityStatusByServiceWidget.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/total-failure-and-severity/TotalFailureAndSeverityWidget.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/trend-of-pass-and-fail-findings/TrendOfPassAndFailFindingsWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-cloud-front-cost/AWSCloudFrontCostWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-by-region/AWSDataTransferByRegionWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-cost-trend/AWSDataTransferCostTrendWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/budget-status/BudgetStatusWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/budget-status/widget-config.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-by-target/BudgetUsageByTargetWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-by-target/widget-config.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-summary/BudgetUsageSummaryWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region/CostByRegionWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/cost-map/CostMapWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/monthly-cost/MonthlyCostWidget.vue
> refactor: change dashboard container, lnb, widget related components to use script setup

- apps/web/src/services/cost-explorer/budget/shared/budget-form/BudgetFormBaseInfo.vue
- apps/web/src/services/cost-explorer/budget/shared/budget-form/budget-form-amount-plan/BudgetFormAmountPlan.vue
- apps/web/src/services/cost-explorer/budget/shared/budget-form/budget-form-amount-plan/BudgetFormAmountPlanAutofillModal.vue
- apps/web/src/services/cost-explorer/budget/shared/budget-form/budget-form-amount-plan/BudgetFormAmountPlanLastMonthsCost.vue
- apps/web/src/services/cost-explorer/budget/shared/budget-form/budget-form-amount-plan/BudgetFormAmountPlanMonthInput.vue
- apps/web/src/services/cost-explorer/budget/shared/budget-form/budget-form-amount-plan/BudgetFormAmountPlanMonthly.vue
- apps/web/src/services/cost-explorer/budget/shared/budget-form/budget-form-amount-plan/BudgetFormAmountPlanTotal.vue
- apps/web/src/services/cost-explorer/budget/shared/budget-form/budget-form-amount-plan/BudgetFormAmountPlanUnitSelect.vue
I recommend you review it in the order of commit.
> refactor(budget): refactor to script setup

- apps/web/src/common/modules/navigations/gnb/modules/GNBLogo.vue
- apps/web/src/common/modules/navigations/lnb/modules/LNBRouterMenuItem.vue
- apps/web/src/services/cost-explorer/CostExplorerLNB.vue
- apps/web/src/services/cost-explorer/modules/RelocateDashboardModal.vue
> feat(relocate-dashboard): create relocate-dashboard markup & link to local storage

- apps/web/Dockerfile
> build: merge commit from master

- apps/web/src/services/cost-explorer/budget/budget-main/modules/budget-list/BudgetList.vue
- apps/web/src/services/cost-explorer/budget/budget-main/modules/budget-toolbox/BudgetToolbox.vue
> feat(budget): remove currency dropdown and total widget

- apps/web/src/services/cost-explorer/cost-analysis/CostAnalysisPage.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisChart.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisChartQuerySection.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisGroupByFilter.vue
> feat: update style of cost analysis chart

- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisChart.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisStackedColumnChart.vue
> chore: delete unused event `rendered`

- apps/web/src/services/cost-explorer/budget/budget-create/BudgetCreatePage.vue
- apps/web/src/services/cost-explorer/budget/shared/BudgetCostTypeSelect.vue
> refactor(budget): refactor to setup script

- apps/web/src/services/cost-explorer/budget/model.ts
- apps/web/src/services/cost-explorer/budget/shared/BudgetCostTypeSelect.vue
> fix(budget-cost-type-select): remove everything except provider

- apps/web/src/services/cost-explorer/cost-analysis/CostAnalysisPage.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisChart.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisChartLegends.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisGroupByFilter.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisHeader.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisStackedColumnChart.vue
> feat: update cost analysis style

- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisChart.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisChartLegends.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisDataTable.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisGroupByFilter.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisQueryFilter.vue
- apps/web/src/services/cost-explorer/lib/config.ts
- apps/web/src/services/dashboards/shared/CustomDateRangeModal.vue
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
- packages/mirinae/src/inputs/context-menu/PContextMenu.vue
- packages/mirinae/src/inputs/dropdown/filterable-dropdown/PFilterableDropdown.vue
> fix: limit 3 groupby & do not show 'save' button when it's managed queryset

- apps/web/src/services/cost-explorer/CostExplorerLNB.vue
- apps/web/src/services/cost-explorer/modules/RelocateDashboardModal.vue
- apps/web/src/services/cost-explorer/modules/RelocateDashboardNotification.vue
> fix(cost-analysis-lnb): add translation & fix relocate modal bug

- apps/web/src/services/cost-explorer/budget/shared/BudgetDataSourceSelect.vue
- apps/web/src/services/cost-explorer/budget/shared/budget-form/BudgetFormBaseInfo.vue
- apps/web/src/services/cost-explorer/model.ts
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
Create budgetDataSourceSelect component.
> feat(budget-data-source-select): create component

- apps/web/src/services/dashboards/widgets/cost-widgets/monthly-cost/MonthlyCostWidget.vue
> refactor(widget): apply new hooks to MonthlyCostWidget

- apps/web/src/services/asset-inventory/collector/collector-history/CollectorHistoryPage.vue
> fix: fixed bug for filter not being applied

- packages/mirinae/src/inputs/dropdown/filterable-dropdown/PFilterableDropdown.vue
- packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
> refactor: refactor setup template for vue3

- apps/web/src/common/modules/navigations/gnb/modules/gnb-profile/GNBProfile.vue
> feat(gnb-profile): refactor to script setup

- apps/web/src/lib/helper/currency-helper.ts
- packages/mirinae/src/inputs/forms/json-schema-form/helper.ts
> fix(mirinae): support array value in case of string type in PJsonSchemaForm

- apps/web/src/common/modules/navigations/gnb/modules/gnb-profile/GNBProfile.vue
The Currency SelectDropdown is removed.
> feat(gnb-profile): remove currency selectDropdown

- apps/web/package.json
- apps/web/src/services/asset-inventory/collector/collector-history/CollectorHistoryPage.vue
- package-lock.json
- package.json
> build: merge 1.12.dev65 to vue3

- apps/web/src/lib/reference/reference-config.ts
- apps/web/src/services/dashboards/dashboard-customize/modules/dashboard-manage-variable-overlay/DashboardManageVariableTable.vue
- apps/web/src/services/dashboards/shared/dashboard-variables/DashboardVariablesSelectDropdown.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-container/DashboardWidgetContainer.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-container/WidgetViewModeModal.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-input-form/helpers/schema-helper.ts
- apps/web/src/services/dashboards/widgets/_base/base-pie/BasePieWidget.vue
- apps/web/src/services/dashboards/widgets/_base/base-trend/BaseTrendWidget.vue
- apps/web/src/services/dashboards/widgets/_components/WidgetDataTable.vue
- apps/web/src/services/dashboards/widgets/_components/type.ts
- apps/web/src/services/dashboards/widgets/_configs/config.ts
- apps/web/src/services/dashboards/widgets/_configs/widget-schema-config.ts
- apps/web/src/services/dashboards/widgets/_helpers/widget-chart-helper.ts
- apps/web/src/services/dashboards/widgets/_helpers/widget-schema-helper.ts
- apps/web/src/services/dashboards/widgets/_helpers/widget-table-helper.ts
- apps/web/src/services/dashboards/widgets/_hooks/use-widget/use-widget-state.ts
- apps/web/src/services/dashboards/widgets/_hooks/use-widget/use-widget.ts
- apps/web/src/services/dashboards/widgets/asset-widgets/trend-of-pass-and-fail-findings/TrendOfPassAndFailFindingsWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-cloud-front-cost/AWSCloudFrontCostWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/cost-map/CostMapWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/cost-map/widget-config.ts
- apps/web/src/store/modules/reference/getters.ts
- apps/web/src/store/modules/reference/type.ts
- apps/web/src/store/reference/all-reference-store.ts
- apps/web/src/store/reference/cost-data-source-reference-store.ts
> feat: add all-reference-store as pinia store with composition api

- apps/web/src/common/modules/navigations/lnb/LNB.vue
- apps/web/src/services/cost-explorer/CostExplorerLNB.vue
- apps/web/src/services/cost-explorer/cost-analysis/CostAnalysisPage.vue
- apps/web/src/services/cost-explorer/routes.ts
- apps/web/src/services/cost-explorer/store/cost-query-set-store.ts
SSIA
- Add `dataSourceId` params in cost analysis page.
- Create LNB dropdown by using `slot`, not `MenuItemType`.
> fix(data-source): renewal dataSource dropdown & fix cost analysis route architecture

- apps/web/src/services/dashboards/widgets/_base/base-trend/BaseTrendWidget.vue
- apps/web/src/services/dashboards/widgets/_hooks/use-widget/use-widget-state.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-by-target/BudgetUsageByTargetWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-by-target/widget-config.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-summary/BudgetUsageSummaryWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-summary/widget-config.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region/CostByRegionWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region/widget-config.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/cost-trend-stacked/widget-config.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/cost-trend/widget-config.ts
> feat: refactor to use new hooks and add data source option to BudgetUsageSummary, BudgetUsageByTarget, CostByRegion, Trend widget

- apps/web/src/services/cost-explorer/CostExplorerLNB.vue
- apps/web/src/services/cost-explorer/store/cost-query-set-store.ts
> fix(data-source): apply data-source-reference store in cost LNB

- apps/web/src/services/cost-explorer/cost-analysis/CostAnalysisPage.vue
- apps/web/src/services/cost-explorer/cost-analysis/lib/widget-data-helper.ts
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisChart.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisDataTable.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisStackedColumnChart.vue
- apps/web/src/services/cost-explorer/cost-analysis/type.ts
- apps/web/src/services/cost-explorer/lib/helper.ts
- apps/web/src/services/cost-explorer/store/cost-analysis-page-store.ts
- apps/web/src/services/cost-explorer/type.ts
> feat: use V2 cost/analyze API && edit minor types

- apps/web/src/services/cost-explorer/CostExplorerLNB.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-container/DashboardWidgetContainer.vue
- apps/web/src/services/dashboards/widgets/_hooks/use-widget-lifecycle.ts
- apps/web/src/services/dashboards/widgets/_hooks/use-widget/use-widget-state.ts
- apps/web/src/store/reference/all-reference-store.ts
- apps/web/src/store/reference/cost-data-source-reference-store.ts
> feat: make all reference store getters load on read time

- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisChart.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisDataTable.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisGroupByFilter.vue
> chore: move `return` to `catch` statement

- apps/web/src/services/dashboards/widgets/_helpers/widget-chart-helper.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/cost-map/CostMapWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/cost-map/costmap-chart-data-helper.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/cost-map/costmap-draw-chart-helper.ts
- apps/web/src/services/dashboards/widgets/type.ts
- apps/web/src/store/reference/all-reference-store.ts
> fix: refactor CostMapWidget and fix typo of webhook at all-reference-store

- apps/web/src/services/cost-explorer/cost-analysis/lib/widget-data-helper.ts
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisChart.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisDataTable.vue
- apps/web/src/services/cost-explorer/type.ts
> chore: change type name

- apps/web/src/services/cost-explorer/CostExplorerLNB.vue
- apps/web/src/services/cost-explorer/cost-analysis/CostAnalysisPage.vue
- apps/web/src/services/cost-explorer/route-config.ts
- apps/web/src/services/cost-explorer/routes.ts
- apps/web/src/services/cost-explorer/store/cost-query-set-store.ts
SSIA..
- Add cost-analysis default route for GNB
- Apply `getCancellableFetcher`
- Handle Budget page dataSource issue
> fix(cost-analysis): refactor and apply costAnalysis route & apply cancellableFetcher

- apps/web/src/services/cost-explorer/cost-analysis/config.ts
- apps/web/src/services/cost-explorer/cost-analysis/lib/period-helper.ts
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisPeriodSelectDropdown.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisQueryFilter.vue
- apps/web/src/services/cost-explorer/cost-analysis/type.ts
- apps/web/src/services/cost-explorer/lib/helper.ts
- apps/web/src/services/cost-explorer/store/cost-analysis-page-store.ts
- apps/web/src/services/cost-explorer/type.ts
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
I added the excludeToday option to distinguish between this month and last month.
> feat(relative-period): add relative-period to costQuerySet options

- apps/web/src/services/dashboards/managed-variables-schema.ts
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat(dashboards-variable): add dataSource variable & remove provider variable

- apps/web/src/services/cost-explorer/CostExplorerLNB.vue
- apps/web/src/store/modules/favorite/actions.ts
- apps/web/src/store/modules/favorite/index.ts
- apps/web/src/store/modules/favorite/mutations.ts
- apps/web/src/store/modules/favorite/type.ts
> feat(cost-analysis): add show-favorite-only in cost-analysis LNB

- apps/web/src/services/dashboards/widgets/_base/base-trend/BaseTrendWidget.vue
- apps/web/src/services/dashboards/widgets/_components/WidgetDataTable.vue
- apps/web/src/services/dashboards/widgets/_helpers/widget-chart-helper.ts
- apps/web/src/services/dashboards/widgets/_helpers/widget-table-helper.ts
- apps/web/src/services/dashboards/widgets/type.ts
- packages/core-lib/src/index.ts
> feat: add table width to base trend widget and refactor

- apps/web/src/services/cost-explorer/cost-analysis/CostAnalysisPage.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisChart.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisDataTable.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisPeriodSelectDropdown.vue
Connect route params with granularity options
And fix some bugs
- route query name of Cost analysis page
- type bug
> feat(cost-analysis-page): connect route params with granularity options

- packages/mirinae/src/inputs/dropdown/filterable-dropdown/PFilterableDropdown.vue
> chore: remove line-height

- packages/mirinae/src/inputs/dropdown/filterable-dropdown/PFilterableDropdown.stories.mdx
- packages/mirinae/src/inputs/dropdown/filterable-dropdown/PFilterableDropdown.vue
- packages/mirinae/src/inputs/dropdown/filterable-dropdown/story-helper.ts
- packages/mirinae/src/inputs/dropdown/filterable-dropdown/type.ts
> feat: merge for updated p-filterable-dropdown spec

- packages/mirinae/src/data-display/dynamic/dynamic-field/templates/badge/index.vue
- packages/mirinae/src/data-display/dynamic/dynamic-field/templates/datetime/index.vue
- packages/mirinae/src/data-display/dynamic/dynamic-field/templates/size/index.vue
- packages/mirinae/src/data-display/dynamic/dynamic-field/templates/state/index.vue
- packages/mirinae/src/data-display/dynamic/dynamic-field/templates/text/index.vue
> fix: fix bug 'target _blank' not working

- apps/web/src/common/components/marks/BetaMark.vue
- apps/web/src/common/components/marks/NewMark.vue
- apps/web/src/common/components/marks/UpdateMark.vue
- apps/web/src/common/modules/navigations/gnb/GNB.vue
- apps/web/src/common/modules/navigations/gnb/modules/SiteMap.vue
- apps/web/src/common/modules/navigations/gnb/modules/gnb-menu/GNBMenu.vue
- apps/web/src/common/modules/navigations/gnb/modules/gnb-menu/GNBSubMenu.vue
- apps/web/src/common/modules/navigations/gnb/modules/gnb-menu/modules/dashboard-recent-favorite/modules/GNBDashboardMenu.vue
- apps/web/src/lib/menu/config.ts
- apps/web/src/lib/menu/menu-info.ts
- apps/web/src/store/modules/display/getters.ts
- apps/web/src/store/modules/display/type.ts
- Integrate `isNew`, `isBeta` tags into `hightlightTag`
> fix(g-n-b): update highlight tag

- apps/web/src/services/cost-explorer/budget/budget-main/modules/budget-list/BudgetListCard.vue
> refactor(budget-list-card): refactor to setup script

- packages/mirinae/src/data-display/badge/PBadge.vue
- packages/mirinae/src/data-display/badge/type.ts
- packages/mirinae/src/inputs/context-menu/PContextMenu.vue
> refactor: refactored setup template for vue3 at badge, context-menu

- apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region/CostByRegionWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region/cost-by-region-data-hleper.ts
> refactor: remove store usage from CostByRegionWidget

- apps/web/src/services/cost-explorer/cost-analysis/config.ts
- apps/web/src/services/dashboards/widgets/_helpers/widget-chart-helper.ts
> fix: edit exclude_today of default query

- apps/web/src/services/cost-explorer/CostExplorerContainer.vue
- apps/web/src/services/cost-explorer/CostExplorerLNB.vue
- apps/web/src/services/cost-explorer/cost-analysis/CostAnalysisPage.vue
- apps/web/src/services/cost-explorer/routes.ts
- apps/web/src/services/cost-explorer/store/cost-query-set-store.ts
- Move CostQuerySet request logic to container
- Update V2
> fix(cost-query-set): refactor costQuerySet request logic

- packages/mirinae/src/inputs/dropdown/filterable-dropdown/PFilterableDropdown.stories.mdx
- packages/mirinae/src/inputs/dropdown/filterable-dropdown/PFilterableDropdown.vue
- Disabled Handler
- Selection Highlight at rounded style type
- Font weight > medium
> feat: updated rounded filterable dropdown style

- packages/mirinae/src/data-display/badge/PBadge.stories.mdx
- packages/mirinae/src/data-display/badge/PBadge.vue
- packages/mirinae/src/data-display/badge/story-helper.ts
- packages/mirinae/src/data-display/badge/type.ts
> feat: updated p-badge spec

- apps/web/src/services/cost-explorer/cost-analysis/CostAnalysisPage.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisChart.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisDataTable.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisFiltersPopper.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisQueryFilter.vue
- apps/web/src/services/cost-explorer/cost-analysis/type.ts
- apps/web/src/services/cost-explorer/lib/helper.ts
- apps/web/src/services/cost-explorer/store/cost-analysis-page-store.ts
- apps/web/src/services/cost-explorer/type.ts
> feat: add filters popover

- packages/mirinae/src/inputs/context-menu/PContextMenu.stories.mdx
- packages/mirinae/src/inputs/context-menu/PContextMenu.vue
- packages/mirinae/src/inputs/context-menu/story-helper.ts
> feat: updated p-context-menu spec

- apps/web/src/services/cost-explorer/cost-analysis/CostAnalysisPage.vue
- apps/web/src/services/cost-explorer/cost-analysis/lib/config.ts
- apps/web/src/services/cost-explorer/cost-analysis/lib/widget-data-helper.ts
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisDataTable.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisGroupByFilter.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisPeriodSelectDropdown.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisQueryFilter.vue
- apps/web/src/services/cost-explorer/store/cost-analysis-page-store.ts
- apps/web/src/services/cost-explorer/store/cost-query-set-store.ts
- apps/web/src/services/cost-explorer/type.ts
> feat: add no results case & set chartGroupBy when select new groupby

- apps/web/src/services/cost-explorer/cost-analysis/CostAnalysisPage.vue
Reflecting changes in the URL when options are modified has been **removed**.
> feat: watch only `selectedQuerySet` in CostAnalysisPage

- apps/web/src/services/cost-explorer/CostExplorerLNB.vue
> fix(data-source-currency): set default dataSource currency

- apps/web/src/common/composables/amcharts5/index.ts
- apps/web/src/services/dashboards/widgets/_base/base-trend/BaseTrendWidget.vue
- apps/web/src/services/dashboards/widgets/_helpers/widget-chart-helper.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-cloud-front-cost/AWSCloudFrontCostWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-cost-trend/AWSDataTransferCostTrendWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-summary/BudgetUsageSummaryWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-summary/widget-config.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/monthly-cost/MonthlyCostWidget.vue
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
- packages/mirinae/src/data-display/progress-bar/PProgressBar.stories.mdx
- packages/mirinae/src/data-display/progress-bar/PProgressBar.vue
- packages/mirinae/src/data-display/progress-bar/story-helper.ts
- packages/mirinae/src/data-display/progress-bar/type.ts
Main feature update: BudgetUsageSummaryWidget update
https://github.com/cloudforet-io/console/assets/26986739/3ee8b8ce-3f8a-4c63-9af3-f6dbe88bf11e
https://github.com/cloudforet-io/console/assets/26986739/a042721a-7055-4631-86cf-3530cdf24d2e
Mirinae update: added height prop to `PProgressBar` component
> feat: update design of BudgetUsageSummaryWidget

- apps/web/src/common/composables/amcharts5/concepts-helper.ts
- apps/web/src/common/composables/amcharts5/index.ts
- apps/web/src/common/composables/date-range-formatter/__tests__/index.test.ts
- apps/web/src/common/composables/date-range-formatter/index.ts
- apps/web/src/services/dashboards/widgets/_base/base-trend/BaseTrendWidget.vue
- apps/web/src/services/dashboards/widgets/_helpers/widget-table-helper.ts
- apps/web/src/services/dashboards/widgets/_hooks/use-widget-color-set.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-summary/BudgetUsageSummaryWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/monthly-cost/MonthlyCostWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/monthly-cost/widget-config.ts
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
Please review in order by commits!!
https://github.com/cloudforet-io/console/assets/26986739/ef4c96ed-68e7-401a-8c04-e16e8e09d3c8
> feat: update design of MonthlyCostWidget

- apps/web/src/services/cost-explorer/cost-analysis/config.ts
- apps/web/src/services/dashboards/widgets/_base/base-pie/BasePieWidget.vue
- apps/web/src/services/dashboards/widgets/_base/base-trend/BaseTrendWidget.vue
- apps/web/src/services/dashboards/widgets/_components/WidgetFrameNew.vue
- apps/web/src/services/dashboards/widgets/_hooks/use-widget/use-widget.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-cloud-front-cost/AWSCloudFrontCostWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-by-region/AWSDataTransferByRegionWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-cost-trend/AWSDataTransferCostTrendWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region/CostByRegionWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/cost-map/CostMapWidget.vue
SSIA
- Apply new dynamic location
- Add `newTab` props to widgetFrame
> fix(widget-location): update dataSourceId and 'dynamic' params in widgetLocation

- apps/web/src/services/dashboards/widgets/cost-widgets/budget-status/BudgetStatusWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/budget-status/widget-config.ts
> fix(budget-status-widget): refactor by new hook and dataSource

- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisChart.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisDataTable.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisGroupByFilter.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisHeader.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisQueryFilter.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisStackedColumnChart.vue
- apps/web/src/services/cost-explorer/store/cost-analysis-page-store.ts
Please see order by commits!!!!!!
> feat: minor changes in cost analysis

- apps/web/src/services/dashboards/widgets/_base/base-count-of-findings/BaseCountOfFindingsWidget.vue
> fix: reference widgetState for groupBy in BaseCountOfFindingsWidget

- apps/web/src/services/dashboards/widgets/_base/base-count-of-findings/BaseCountOfFindingsWidget.vue
- apps/web/src/services/dashboards/widgets/_components/WidgetChartNoDataOverlay.vue
> fix: add empty case and fix duplicated drawing error in BaseCountOfFindingsWidget

- apps/web/src/services/cost-explorer/cost-analysis/config.ts
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisFiltersAddMoreButton.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisFiltersPopper.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisQueryFilter.vue
- apps/web/src/services/cost-explorer/store/cost-analysis-page-store.ts
- apps/web/src/services/cost-explorer/type.ts
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/ja.json
- packages/language-pack/ko.json
https://github.com/cloudforet-io/console/assets/18563857/cb50fa16-4bf1-4245-a9b8-cab7828e3978
> feat: add `enabled_properties` to costQuerySetOption & create `Add More` button

- apps/web/src/services/cost-explorer/cost-analysis/config.ts
- apps/web/src/services/cost-explorer/cost-analysis/lib/period-helper.ts
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisPeriodSelectDropdown.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisQueryFilter.vue
- apps/web/src/services/cost-explorer/cost-analysis/type.ts
- apps/web/src/services/cost-explorer/store/cost-analysis-page-store.ts
- apps/web/src/services/cost-explorer/type.ts
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
Change to below options
Daily:
- This Month
- Last Month
- September, 2023
- August, 2023 ...
Monthly
- Last 3 Months
- Last 6 Months
- Last 1 Year
- Custom (3개년치 기간중 최대 12개월 까지 선택 가능)
Yearly
- Last 3 Years
> feat(cost-analysis-period-select-dropdown): update menu items according to granularity

- apps/web/src/services/dashboards/widgets/_base/base-count-of-findings/BaseCountOfFindingsWidget.vue
- apps/web/src/services/dashboards/widgets/_base/base-pie/BasePieWidget.vue
- apps/web/src/services/dashboards/widgets/_base/base-trend/BaseTrendWidget.vue
- apps/web/src/services/dashboards/widgets/_helpers/widget-chart-helper.ts
- apps/web/src/services/dashboards/widgets/_helpers/widget-helper.ts
- apps/web/src/services/dashboards/widgets/_helpers/widget-location-helper.ts
- apps/web/src/services/dashboards/widgets/_hooks/use-cost-widget-frame-header-dropdown.ts
- apps/web/src/services/dashboards/widgets/asset-widgets/compliance-check-status/ComplianceCheckStatusWidget.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/severity-status-by-service/SeverityStatusByServiceWidget.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/total-failure-and-severity/TotalFailureAndSeverityWidget.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/trend-of-pass-and-fail-findings/TrendOfPassAndFailFindingsWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-cloud-front-cost/AWSCloudFrontCostWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-by-region/AWSDataTransferByRegionWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-by-region/widget-config.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region/CostByRegionWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/cost-map/CostMapWidget.vue
SSIA
Sorry for bulk updates..!
> fix: update empty case and refactor asset widgets

- apps/web/src/common/composables/amcharts5/xy-chart-helper.ts
- apps/web/src/services/cost-explorer/cost-analysis/lib/period-helper.ts
- apps/web/src/services/cost-explorer/cost-analysis/lib/widget-data-helper.ts
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisChart.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisStackedColumnChart.vue
- apps/web/src/services/cost-explorer/store/cost-analysis-page-store.ts
> feat: apply daily, yearly chart 

- apps/web/src/services/dashboards/widgets/_helpers/widget-chart-helper.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-by-region/AWSDataTransferByRegionWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-by-region/widget-config.ts
> fix: apply updated api spec to AWSDataTransferByRegionWidget

- apps/web/src/lib/reference/asset-reference-config.ts
- apps/web/src/lib/reference/cost-reference-config.ts
- apps/web/src/lib/reference/reference-config.ts
- apps/web/src/services/dashboards/dashboard-create/modules/dashboard-templates/helper.ts
- apps/web/src/services/dashboards/managed-variables-schema.ts
- apps/web/src/services/dashboards/shared/dashboard-variables/DashboardVariablesDropdown.vue
- apps/web/src/services/dashboards/widgets/_configs/config.ts
- apps/web/src/services/dashboards/widgets/_configs/widget-schema-config.ts
- apps/web/src/services/dashboards/widgets/_helpers/widget-filters-helper.ts
- apps/web/src/services/dashboards/widgets/_hooks/use-widget-state-deprecated.ts
- apps/web/src/services/dashboards/widgets/_hooks/use-widget/use-widget-state.ts
- Transferred `DataSource` reference type info from `REFERENCE_TYPE_INFO` to `COST_REFERENCE_TYPE_INFO`.
> fix(variable-schema): edit dataSource variable schema and reference config

- apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-by-region/AWSDataTransferByRegionWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-by-region/widget-config.ts
> fix: remove fixed filter and add it as options in AWSDataTransferByRegionWidget

- apps/web/src/services/cost-explorer/cost-analysis/lib/widget-data-helper.ts
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisDataTable.vue
> feat(cost-analysis-data-table): add usage_quantity_sum if usage type is included in groupby

- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisDataTable.vue
- packages/mirinae/src/data-display/tables/toolbox-table/PToolboxTable.vue
- packages/mirinae/src/navigation/toolbox/PToolbox.vue
Analyze V2 has no `total_count` field, only has `more`
> feat: set dynamic pagination to CostAnalysisDataTable

- apps/web/src/services/dashboards/widgets/_base/base-pie/BasePieWidget.vue
- apps/web/src/services/dashboards/widgets/_base/base-trend/BaseTrendWidget.vue
- apps/web/src/services/dashboards/widgets/_components/WidgetDataTable.vue
- apps/web/src/services/dashboards/widgets/_helpers/widget-chart-helper.ts
- apps/web/src/services/dashboards/widgets/_helpers/widget-table-helper.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-by-region/AWSDataTransferByRegionWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-cost-trend/AWSDataTransferCostTrendWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-cost-trend/widget-config.ts
- apps/web/src/services/dashboards/widgets/type.ts
- packages/core-lib/src/index.ts
> feat: apply updated api spec and update design of AWSDataTransferCostTrendWidget

- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisHeader.vue
- apps/web/src/services/cost-explorer/store/cost-analysis-page-store.ts
SSIA
- Managed Cost Query Set
- Custom Cost Query Set
> feat(cost-analysis-header): add left-icon according to datasource & update title-right-extra icons

- apps/web/src/services/cost-explorer/routes.ts
> fix(cost-explorer-routes): remove label & copiable attributes

- apps/web/src/services/cost-explorer/budget/budget-detail/BudgetDetailPage.vue
- apps/web/src/services/cost-explorer/budget/budget-detail/modules/budget-info/AmountPlanningTypePopover.vue
- apps/web/src/services/cost-explorer/budget/budget-detail/modules/budget-info/BudgetDetailInfo.vue
- apps/web/src/services/cost-explorer/budget/budget-detail/modules/budget-summary/BudgetSummary.vue
- apps/web/src/services/cost-explorer/budget/budget-detail/modules/budget-summary/BudgetSummaryChart.vue
- apps/web/src/services/cost-explorer/budget/budget-detail/modules/budget-summary/BudgetSummaryTable.vue
> refactor(budget-detail): refactor to setup script

- apps/web/src/services/dashboards/widgets/_helpers/widget-chart-helper.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-cloud-front-cost/AWSCloudFrontCostWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-cloud-front-cost/widget-config.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/budget-status/BudgetStatusWidget.vue
> fix(aws-cloud-front-cost-widget): update api spec & refactor hooks and filter

- apps/web/src/services/dashboards/shared/dashboard-widget-input-form/helpers/reference-handler-helper.ts
- packages/mirinae/src/inputs/dropdown/filterable-dropdown/PFilterableDropdown.vue
- packages/mirinae/src/inputs/dropdown/filterable-dropdown/type.ts
- packages/mirinae/src/inputs/forms/json-schema-form/PJsonSchemaForm.vue
- packages/mirinae/src/inputs/forms/json-schema-form/helper.ts
- packages/mirinae/src/inputs/forms/json-schema-form/type.ts
Please review in order by commits. Each commit messages say it all.
> feat: update FilterableDropdown, JsonSchemaForm handler spec and apply to widget input form

- apps/web/src/common/modules/navigations/lnb/LNB.vue
- apps/web/src/services/cost-explorer/budget/budget-main/modules/budget-list/BudgetList.vue
- apps/web/src/services/cost-explorer/budget/budget-main/modules/budget-list/BudgetListCard.vue
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> chore: show loading UI in Budget List not Card

- apps/web/src/services/cost-explorer/budget/budget-detail/BudgetDetailPage.vue
- apps/web/src/services/cost-explorer/budget/budget-detail/modules/BudgetDeleteModal.vue
- apps/web/src/services/cost-explorer/budget/budget-detail/modules/budget-info/BudgetDetailInfo.vue
- apps/web/src/services/cost-explorer/budget/budget-detail/modules/budget-notifications/BudgetNotifications.vue
- apps/web/src/services/cost-explorer/budget/budget-detail/modules/budget-notifications/BudgetNotificationsModal.vue
- apps/web/src/services/cost-explorer/budget/budget-detail/modules/budget-summary/BudgetSummary.vue
- apps/web/src/services/cost-explorer/budget/budget-detail/modules/budget-summary/BudgetSummaryChart.vue
- apps/web/src/services/cost-explorer/budget/budget-detail/modules/budget-summary/BudgetSummaryTable.vue
- apps/web/src/services/cost-explorer/budget/model.ts
- apps/web/src/services/cost-explorer/store/budget-detail-page-store.ts
Check below functions, please
- apply v2 api
- dynamic cost query set link
> fix(budget-summary-table): apply v2 budget api

- apps/web/src/services/dashboards/config.ts
- apps/web/src/services/dashboards/managed-variables-schema.ts
- apps/web/src/services/dashboards/shared/dashboard-variables/DashboardVariablesDropdown.vue
- apps/web/src/services/dashboards/widgets/_helpers/widget-chart-helper.ts
> feat: make data_source variable to use auotocomplete api and make auto select for required variable

- apps/web/src/services/cost-explorer/budget/budget-detail/modules/budget-info/AmountPlanningTypePopover.vue
- apps/web/src/services/cost-explorer/budget/budget-detail/modules/budget-info/BudgetDetailInfo.vue
> fix(amount-planning-type): fix code according to v2 api spec

- apps/web/src/services/cost-explorer/cost-analysis/CostAnalysisPage.vue
- apps/web/src/services/cost-explorer/cost-analysis/lib/widget-data-helper.ts
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisChart.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisDataTable.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisPeriodSelectDropdown.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisStackedColumnChart.vue
- apps/web/src/services/cost-explorer/lib/helper.ts
- apps/web/src/services/dashboards/widgets/_helpers/widget-table-helper.ts
> fix: fix awkward timeUnit helper & fix period bug in cost analysis 

- packages/mirinae/src/data-display/board-item/PBoardItem.vue
- packages/mirinae/src/feedbacks/modals/button-modal/PButtonModal.stories.mdx
- packages/mirinae/src/inputs/datetime-picker/PDatetimePicker.stories.mdx
- packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
- packages/mirinae/src/inputs/forms/json-schema-form/PJsonSchemaForm.stories.mdx
- packages/mirinae/src/inputs/forms/json-schema-form/PJsonSchemaForm.vue
- packages/mirinae/src/navigation/toolbox/PToolbox.vue
> feat: apply updated select-dropdown at mirinae

- apps/web/src/services/cost-explorer/budget/shared/BudgetDataSourceSelect.vue
- apps/web/src/services/cost-explorer/budget/shared/budget-form/BudgetFormBaseInfo.vue
- apps/web/src/store/reference/cost-data-source-reference-store.ts
- apply real data to dataSourceSelect component
- update create api params
> feat(budget-data-source-select): modify to real dataSource data

- apps/web/src/common/composables/amcharts5/xy-chart-helper.ts
- apps/web/src/services/cost-explorer/budget/budget-detail/modules/budget-summary/BudgetSummary.vue
- apps/web/src/services/cost-explorer/budget/budget-detail/modules/budget-summary/BudgetSummaryChart.vue
- apps/web/src/services/cost-explorer/store/budget-detail-page-store.ts
> feat: change from am4 to am5 of budget chart

- apps/web/src/services/cost-explorer/routes.ts
> fix(cost-explorer-routes): roll back route label

- apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-by-region/AWSDataTransferByRegionWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-cost-trend/AWSDataTransferCostTrendWidget.vue
> fix(widget-location): set widget location dataSource params

- apps/web/src/services/cost-explorer/budget/budget-detail/modules/budget-summary/BudgetSummaryTable.vue
- apps/web/src/services/cost-explorer/budget/budget-main/modules/budget-toolbox/BudgetToolbox.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisFiltersPopper.vue
> feat: add 'Data Source' to budget search & set budget summary table link 

- apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-by-target/BudgetUsageByTargetWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-summary/BudgetUsageSummaryWidget.vue
> fix: fix BudgetUsageByTarget, BudgetUsageSummary widget 

- apps/web/src/services/cost-explorer/budget/budget-detail/modules/budget-notifications/BudgetNotifications.vue
- apps/web/src/services/cost-explorer/budget/budget-detail/modules/budget-notifications/BudgetNotificationsChannel.vue
- apps/web/src/services/cost-explorer/budget/budget-detail/modules/budget-notifications/BudgetNotificationsModal.vue
> refactor(budget-notification): refactor to setup script

- apps/web/src/services/cost-explorer/budget/budget-detail/modules/budget-summary/BudgetSummaryTable.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisDataTable.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisFiltersAddMoreButton.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisFiltersPopper.vue
- apps/web/src/services/cost-explorer/store/cost-analysis-page-store.ts
> chore: add sort to cost analysis data table

- apps/web/src/services/cost-explorer/budget/budget-detail/modules/budget-notifications/BudgetNotificationsChannel.vue
- apps/web/src/services/cost-explorer/budget/budget-detail/modules/budget-notifications/BudgetNotificationsModal.vue
- apps/web/src/services/cost-explorer/budget/model.ts
- apps/web/src/services/cost-explorer/store/budget-detail-page-store.ts
> fix(budget-notification): apply v2 api spec & fix feature bug

- apps/web/src/services/cost-explorer/budget/budget-detail/modules/budget-info/BudgetDetailInfo.vue
> fix(budget-detail-info): fix costType(provider) value logic

- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisPeriodSelectDropdown.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisQueryFilter.vue
- apps/web/src/services/cost-explorer/store/cost-analysis-page-store.ts
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat(cost-analysis-query-filter): add period invalid status to page

- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisPeriodSelectDropdown.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisQueryFilter.vue
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat(cost-analysis): apply label to dropdown

- apps/web/src/services/dashboards/shared/dashboard-toolset/DashboardDateDropdown.vue
- apps/web/src/services/dashboards/widgets/_base/base-pie/BasePieWidget.vue
- apps/web/src/services/dashboards/widgets/_base/base-pie/widget-config.ts
- apps/web/src/services/dashboards/widgets/_base/base-trend/BaseTrendWidget.vue
- apps/web/src/services/dashboards/widgets/_helpers/widget-location-helper.ts
- apps/web/src/services/dashboards/widgets/_hooks/use-widget/use-merged-widget-state.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-cloud-front-cost/AWSCloudFrontCostWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-by-region/AWSDataTransferByRegionWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-cost-trend/AWSDataTransferCostTrendWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/budget-status/BudgetStatusWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-by-target/BudgetUsageByTargetWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region/CostByRegionWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region/widget-config.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/cost-map/CostMapWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/cost-map/widget-config.ts
> feat: set 'full data' link to dashboard widgets &  use `YYYY-MM` in dashboard date dropdown

- apps/web/src/common/components/editor/ColorPicker.vue
- apps/web/src/common/components/editor/MenuBar.vue
- apps/web/src/common/modules/dropdown/currency-select-dropdown/CurrencySelectDropdown.vue
- apps/web/src/common/modules/dropdown/service-provider-dropdown/ServiceProviderDropdown.vue
- apps/web/src/services/alert-manager/alert/alert-detail/modules/alert-summary/AlertSummary.vue
- apps/web/src/services/asset-inventory/collector/collector-create/modules/Step1SearchFilter.vue
- apps/web/src/services/cost-explorer/CostExplorerLNB.vue
- apps/web/src/services/cost-explorer/budget/budget-detail/modules/budget-notifications/BudgetNotificationsModal.vue
- apps/web/src/services/cost-explorer/budget/shared/BudgetDataSourceSelect.vue
- apps/web/src/services/dashboards/shared/dashboard-toolset/DashboardCurrencySelectDropdown.vue
- apps/web/src/services/dashboards/shared/dashboard-toolset/DashboardDateDropdown.vue
- packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
- packages/mirinae/src/inputs/dropdown/select-dropdown/components/dropdown-button.vue
> feat: apply dropdown-button slot at console

- apps/web/src/services/dashboards/shared/dashboard-toolset/DashboardDateDropdown.vue
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
- Apply design and label
- Translation
> fix(dashboard-date-dropdown): apply design, label and translation

- apps/web/src/services/cost-explorer/budget/budget-main/modules/budget-toolbox/BudgetToolbox.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisChartLegends.vue
- apps/web/src/services/dashboards/dashboard-customize/modules/dashboard-manage-variable-overlay/DashboardManageVariableForm.vue
- apps/web/src/services/dashboards/dashboard-main/modules/DashboardMainSelectFilter.vue
- apps/web/src/services/dashboards/shared/dashboard-toolset/DashboardCurrencySelectDropdown.vue
- apps/web/src/services/dashboards/shared/dashboard-toolset/DashboardDateDropdown.vue
- apps/web/src/services/info/notice/modules/NoticeList.vue
- apps/web/src/services/my-page/my-account/user-api-key/modules/APIKeyTable.vue
- apps/web/src/services/notification/modules/AddNotificationLevel.vue
- apps/web/src/services/project/project-detail/project-alert/project-webhook/ProjectWebhookPage.vue
- apps/web/src/services/project/project-detail/project-member/modules/ProjectMemberTab.vue
> chore: remove relative

- apps/web/src/services/dashboards/widgets/_hooks/use-widget/use-widget-state.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/budget-status/widget-config.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-by-target/widget-config.ts
> feat: delete 'provider' option from budget widgets & delete `cost_types.` prefix from budget filters key

- apps/web/src/services/cost-explorer/CostExplorerLNB.vue
- apps/web/src/services/cost-explorer/modules/RelocateDashboardModal.vue
> refactor(cost-analysis): refactor url query for dashboard route

- apps/web/src/services/cost-explorer/budget/budget-main/modules/budget-toolbox/BudgetToolbox.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/budget-status/BudgetStatusWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/budget-status/widget-config.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-by-target/BudgetUsageByTargetWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-by-target/widget-config.ts
- apps/web/src/services/dashboards/widgets/type.ts
> feat: set budget name to BudgetUsageByTarget widget

- apps/web/src/services/dashboards/shared/dashboard-widget-container/DashboardWidgetContainer.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-container/WidgetViewModeModal.vue
- apps/web/src/services/dashboards/widgets/_base/base-pie/BasePieWidget.vue
- apps/web/src/services/dashboards/widgets/_components/WidgetDataTable.vue
- apps/web/src/services/dashboards/widgets/_configs/config.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-by-target/BudgetUsageByTargetWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region/CostByRegionWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/cost-map/CostMapWidget.vue
> feat: remove currency rates from dashboard widgets and related components

- apps/web/src/services/dashboards/dashboard-create/DashboardCreatePage.vue
- apps/web/src/services/dashboards/dashboard-customize/modules/DashboardCustomizeSidebar.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-input-form/DashboardWidgetInputForm.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-input-form/DashboardWidgetMoreOptions.vue
> refactor: reorder script and template or apply script setup to dashboard components

- apps/web/src/services/dashboards/shared/dashboard-variables/DashboardVariablesDropdown.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-container/DashboardWidgetContainer.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-container/WidgetViewModeModal.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-container/WidgetViewModeSidebar.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-input-form/DashboardWidgetInputForm.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-input-form/helpers/form-data-helper.ts
- apps/web/src/services/dashboards/shared/dashboard-widget-input-form/helpers/schema-helper.ts
- apps/web/src/services/dashboards/store/dashboard-detail-info.ts
- apps/web/src/services/dashboards/store/widget-form.ts
- apps/web/src/services/dashboards/widgets/_configs/config.ts
- apps/web/src/services/dashboards/widgets/_hooks/use-widget-lifecycle.ts
- apps/web/src/services/dashboards/widgets/_hooks/use-widget-pagination.ts
- apps/web/src/services/dashboards/widgets/_hooks/use-widget/use-merged-widget-state.ts
- apps/web/src/services/dashboards/widgets/_hooks/use-widget/use-widget-frame.ts
- apps/web/src/services/dashboards/widgets/asset-widgets/count-of-fail-findings/widget-config.ts
- apps/web/src/services/dashboards/widgets/asset-widgets/count-of-pass-and-fail-findings/widget-config.ts
- apps/web/src/services/dashboards/widgets/asset-widgets/trend-of-pass-and-fail-findings/widget-config.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-cloud-front-cost/widget-config.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-cost-trend/widget-config.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/cost-donut/widget-config.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/cost-map/widget-config.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/cost-pie/widget-config.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/cost-trend-stacked/widget-config.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/cost-trend/widget-config.ts
> fix: use merged widget state in widget-form store and set first variable item correctly in DashboardVariablesDropdown

- apps/web/src/services/home-dashboard/modules/all-summary/AllSummary.vue
- apps/web/src/services/home-dashboard/modules/all-summary/AllSummaryDataSummary.vue
SSIA!!!
I'll add refactoring commits for Vue3, soon
> feat: change to v2 analyze api in home-dashboard widget

- apps/web/src/services/dashboards/shared/dashboard-toolset/DashboardDateDropdown.vue
> chore: add flex-glow style

- apps/web/src/services/auth/authenticator/index.ts
- apps/web/src/services/cost-explorer/budget/budget-detail/BudgetDetailPage.vue
- apps/web/src/services/cost-explorer/budget/budget-main/modules/budget-list/BudgetListCard.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisDataTable.vue
- apps/web/src/store/modules/settings/actions.ts
- apps/web/src/store/modules/settings/config.ts
- apps/web/src/store/modules/settings/index.ts
- apps/web/src/store/modules/settings/mutations.ts
- apps/web/src/store/modules/settings/plugins.ts
- apps/web/src/store/modules/settings/type.ts
> refactor: remove store exchange rate

- apps/web/src/services/cost-explorer/budget/budget-detail/BudgetDetailPage.vue
- apps/web/src/services/cost-explorer/budget/budget-main/modules/budget-list/BudgetListCard.vue
- apps/web/src/services/cost-explorer/budget/shared/budget-form/budget-form-amount-plan/BudgetFormAmountPlanLastMonthsCost.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisChart.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisDataTable.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisHeader.vue
- apps/web/src/store/modules/settings/getters.ts
- apps/web/src/store/modules/settings/index.ts
- apps/web/src/store/modules/settings/mutations.ts
- apps/web/src/store/modules/settings/type.ts
> refactor: remove store currency

- apps/web/src/services/dashboards/dashboard-customize/modules/dashboard-manage-variable-overlay/DashboardManageVariableTable.vue
- apps/web/src/services/dashboards/shared/dashboard-variables/DashboardVariablesDropdown.vue
- apps/web/src/services/dashboards/shared/dashboard-variables/DashboardVariablesMoreButton.vue
Please, see it in order by commit.
- You can't delete or clear required variable
- You can't toggle required variable use in manage-variable-overlay
- You can't remove or clear required variable use in more-variable-dropdown
https://github.com/cloudforet-io/console/assets/83635051/890afcb0-1958-45dd-be8f-c5313dca256c
> fix(required-variable): you can't handle required variable, you can just select variable option

- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisDataTable.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisHeader.vue
> fix: set dataSource currency to cost analysis page

- apps/web/src/services/home-dashboard/modules/all-summary/AllSummary.vue
- apps/web/src/services/home-dashboard/modules/all-summary/AllSummaryDataSummary.vue
> refactor: refactor AllSummary widget for vue3 and change from am4 to am5

- apps/web/src/App.vue
- apps/web/src/services/cost-explorer/CostExplorerContainer.vue
- apps/web/src/services/cost-explorer/CostExplorerLNB.vue
- apps/web/src/services/cost-explorer/routes.ts
> fix: fix some bugs at cost explorer service and app.vue

- apps/web/src/services/cost-explorer/CostExplorerLNB.vue
- apps/web/src/services/cost-explorer/store/cost-query-set-store.ts
> fix(data-source-dropdown): add empty icon case

- apps/web/src/services/dashboards/shared/dashboard-widget-input-form/DashboardWidgetInputForm.vue
> chore: test

- apps/web/src/services/dashboards/shared/dashboard-variables/DashboardVariablesDropdown.vue
> refactor: reorder script and template in DashboardVariablesDropdown

- apps/web/src/services/asset-inventory/collector/collector-detail/modules/SectionHeader.vue
> fix(section-header): add click event handler to edit button

- apps/web/src/services/dashboards/shared/dashboard-variables/DashboardVariablesDropdown.vue
> fix: do not init required variable if exists in DashboardVariablesDropdown

- apps/web/src/services/dashboards/store/widget-form.ts
> fix: give initial title in initWidgetForm at widget-form store

- apps/web/src/services/dashboards/shared/dashboard-widget-input-form/DashboardWidgetInputForm.vue
> fix: init schema and form data on reset at DashboardWsidgetInputForm

- apps/web/src/lib/config.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/monthly-cost/MonthlyCostWidget.vue
> fix: update grid location of MonthlyCostWidget and add debug code for edge config check

- apps/web/src/services/cost-explorer/budget/budget-main/modules/budget-list/BudgetList.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisDataTable.vue
- apps/web/src/store/modules/file/actions.ts
Since the console API has not been deployed yet, you will need to **run local server to test it.**🥲
> feat: add `version` to payload of excel export API

- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisQueryFormModal.vue
SSIA
- quest: https://pyengine.atlassian.net/browse/QA-757
> fix: add disabled case at costAnalysisQueryFormModal

- apps/web/src/services/alert-manager/alert-dashboard/modules/alert-history-widget/AlertHistoryChart.vue
SSIA
- quest: https://pyengine.atlassian.net/browse/QA-728
> fix(alert-dashboard): fixed loading status

- apps/web/src/services/dashboards/widgets/cost-widgets/aws-cloud-front-cost/widget-config.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-by-region/widget-config.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-cost-trend/widget-config.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-summary/BudgetUsageSummaryWidget.vue
> fix: use options.filters for default value of widget schema and remove minus in case of exceed at BudgetUsageSummaryWidget

- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisPeriodSelectDropdown.vue
- apps/web/src/services/dashboards/shared/CustomDateRangeModal.vue
[QA-740
](https://pyengine.atlassian.net/browse/QA-740)
> fix(custom-date-range-modal): limit selectable range

- apps/web/src/common/modules/navigations/lnb/modules/LNBRouterMenuItem.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisChartLegends.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisGroupByFilter.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisHeader.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisPeriodSelectDropdown.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisQueryFilter.vue
- packages/mirinae/src/inputs/dropdown/filterable-dropdown/PFilterableDropdown.vue
- packages/mirinae/src/inputs/dropdown/select-dropdown/components/dropdown-button.vue
SSIA
- quest
- https://pyengine.atlassian.net/browse/QA-758
- https://pyengine.atlassian.net/browse/QA-760
> feat(cost-analysis): apply design QA

- apps/web/src/services/project/project-detail/project-summary/modules/ProjectBilling.vue
> feat: set analyze v2 api to ProjectBilling widget

- apps/web/src/services/dashboards/dashboard-detail/DashboardDetailPage.vue
- apps/web/src/services/dashboards/shared/dashboard-variables/DashboardVariablesDropdown.vue
> fix: reset dashboard detail info store and remove url query string

- apps/web/src/services/project/project-detail/project-summary/modules/ProjectBilling.vue
> refactor: change to setup script

- apps/web/src/services/dashboards/shared/dashboard-widget-input-form/DashboardWidgetInputForm.vue
> fix: project filter must be fixed for project dashboard at DashboardWidgetInputForm

- apps/web/src/services/dashboards/dashboard-create/modules/dashboard-templates/helper.ts
- apps/web/src/services/dashboards/shared/dashboard-widget-input-form/DashboardWidgetInputForm.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-input-form/composables/use-widget-more-options.ts
- apps/web/src/services/dashboards/shared/dashboard-widget-input-form/helpers/schema-helper.ts
- apps/web/src/services/dashboards/widgets/_configs/config.ts
Please review in order by commits! Commit message says it all.
> fix: getWidgetOptionSchema does not return undefined and separate more options related logics as composable

- apps/web/src/services/dashboards/config.ts
- apps/web/src/services/dashboards/managed-variables-schema.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/budget-status/widget-config.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-by-target/widget-config.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-summary/widget-config.ts
> fix: remove region, provider and cost filter from budget widget configs and revive the provider variable

- apps/web/src/services/cost-explorer/budget/budget-detail/BudgetDetailPage.vue
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat(budget-detail-page): add budget infos to header

- apps/web/src/services/cost-explorer/budget/budget-main/modules/budget-toolbox/BudgetToolboxUsageRange.vue
> refactor(budget-toolbox-usage-range): refactor to setup script

- apps/web/src/services/cost-explorer/CostExplorerContainer.vue
- apps/web/src/services/cost-explorer/CostExplorerLNB.vue
- apps/web/src/services/cost-explorer/modules/RelocateDashboardModal.vue
- apps/web/src/services/cost-explorer/store/cost-explorer-settings-store.ts
- apps/web/src/store/modules/settings/actions.ts
[QA - 727](https://pyengine.atlassian.net/browse/QA-727)
- Create `cost-explorer-settings-store.ts`.
- Apply settings store.
- Registered in `CostExplorerContatiner.vue`.
- Apply `CostExplorerLNB.vue`, `RelocateModal`, `RelocateNotification`.
- Fix settings vuex store issue.
> fix(relocate-dashboard): fix relocate-dashboard issue

- apps/web/src/common/modules/navigations/lnb/modules/LNBRouterMenuItem.vue
- apps/web/src/services/cost-explorer/budget/budget-detail/modules/budget-info/BudgetDetailInfo.vue
- apps/web/src/services/cost-explorer/budget/budget-main/BudgetMainPage.vue
- apps/web/src/services/cost-explorer/budget/shared/budget-form/budget-form-amount-plan/BudgetFormAmountPlanMonthly.vue
- apps/web/src/services/cost-explorer/budget/type.ts
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
SSIA
- quest: https://pyengine.atlassian.net/browse/QA-766
> feat(budget): apply design qa

- apps/web/src/common/components/editor/ColorPicker.vue
- apps/web/src/common/components/editor/MenuBar.vue
- packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
- packages/mirinae/src/inputs/dropdown/select-dropdown/story-helper.ts
- packages/mirinae/src/inputs/forms/json-schema-form/PJsonSchemaForm.vue
- packages/mirinae/src/navigation/toolbox/PToolbox.vue
> fix: apply dropdown-button slot and initial min-width

- packages/language-pack/en.json
- packages/mirinae/src/inputs/forms/field-group/PFieldGroup.vue
> fix: update language BUDGET_USAGE_SUMMARY.EXCEED

- apps/web/src/services/cost-explorer/budget/budget-detail/modules/budget-info/BudgetDetailInfo.vue
> fix(budget-detail-info): fix display type of viewAll

- apps/web/src/services/administration/iam/role/modules/role-managemnet-table/RoleManagementTable.vue
- apps/web/src/services/administration/iam/user/modules/UserManagementTable.vue
- apps/web/src/services/alert-manager/alert/alert-detail/modules/alert-summary/AlertSummary.vue
- apps/web/src/services/alert-manager/escalation-policy/EscalationPolicyPage.vue
- apps/web/src/services/asset-inventory/collector/collector-create/modules/Step1SearchFilter.vue
- apps/web/src/services/cost-explorer/CostExplorerLNB.vue
- apps/web/src/services/cost-explorer/budget/shared/BudgetDataSourceSelect.vue
- apps/web/src/services/dashboards/shared/dashboard-toolset/DashboardDateDropdown.vue
- packages/mirinae/src/inputs/dropdown/select-dropdown/components/dropdown-button.vue
> feat: apply justify-between at dropdown button

- apps/web/package.json
- apps/web/src/services/dashboards/widgets/cost-widgets/monthly-cost/MonthlyCostWidget.vue
- package-lock.json
> fix: refresh on initWidget at MonthlyCostWidget and upgrade amcharts5 version

- apps/web/src/services/dashboards/dashboard-create/modules/DashboardScopeForm.vue
- apps/web/src/services/dashboards/dashboard-create/modules/DashboardTemplateForm.vue
- apps/web/src/services/dashboards/dashboard-create/modules/DashboardViewerForm.vue
- apps/web/src/services/dashboards/shared/DashboardLabels.vue
- apps/web/src/services/dashboards/shared/dashboard-toolset/DashboardDateDropdown.vue
- apps/web/src/services/dashboards/shared/dashboard-variables/DashboardVariablesDropdown.vue
- Adjusting radio form `spacing`(https://pyengine.atlassian.net/browse/QA-771)
- Apply `P-Link` and arrow design modification(https://pyengine.atlassian.net/browse/QA-773)
- Variable filter `hover&active design` modification(https://pyengine.atlassian.net/browse/QA-776)
🌟 Remove index-mode and dropdown-button slot for selection-label and change labels width
(https://pyengine.atlassian.net/browse/QA-774,  https://pyengine.atlassian.net/browse/QA-775)
The last commit was for adjusting the width, so please review each commit excluding this one.
> refactor(create-dashboard): change style and component attributes.

- apps/web/src/services/dashboards/shared/dashboard-widget-container/DashboardWidgetContainer.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-container/WidgetViewModeModal.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-input-form/DashboardWidgetInputForm.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-input-form/composables/use-widget-more-options.ts
- apps/web/src/services/dashboards/shared/dashboard-widget-input-form/helpers/form-data-helper.ts
- apps/web/src/services/dashboards/shared/dashboard-widget-input-form/widget-form-store.ts
- apps/web/src/services/dashboards/shared/helpers/dashboard-widget-info-helper.ts
- apps/web/src/services/dashboards/widgets/_helpers/widget-schema-helper.ts
- apps/web/src/services/dashboards/widgets/_helpers/widget-validation-helper.ts
- apps/web/src/services/dashboards/widgets/_hooks/use-widget-lifecycle.ts
- apps/web/src/services/dashboards/widgets/_hooks/use-widget/use-merged-widget-state.ts
- apps/web/src/services/dashboards/widgets/_hooks/use-widget/use-widget-state.ts
> fix: validate widget with schemaProperties and emit updated widget info

- apps/web/src/services/cost-explorer/CostExplorerLNB.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisHeader.vue
- apps/web/src/services/cost-explorer/store/cost-analysis-page-store.ts
> fix: fix reactivity bug of nested pinia

- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisGroupByFilter.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisHeader.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisQueryFilter.vue
> feat: add period badge when its custom/dynamic cost & fix: hide edit/delete button for dynamic query set 

- apps/web/src/services/dashboards/shared/DashboardWidgetEditModal.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-container/WidgetViewModeSidebar.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-input-form/composables/use-widget-more-options.ts
- apps/web/src/services/dashboards/shared/dashboard-widget-input-form/helpers/schema-helper.ts
- apps/web/src/services/dashboards/shared/dashboard-widget-input-form/widget-form-store.ts
> fix: do not store all config data to dashboard layout widget

- apps/web/src/common/modules/navigations/gnb/modules/gnb-menu/modules/dashboard-recent-favorite/modules/GNBDashboardMenu.vue
- apps/web/src/common/modules/navigations/gnb/modules/gnb-recent-favorite/modules/GNBFavorite.vue
- apps/web/src/lib/helper/config-data-helper.ts
- apps/web/src/services/cost-explorer/type.ts
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
**_Please see order by commits._**
> fix(g-n-b-favorite): add Dashboards and CostAnalysis favorite in GNB Favorite

- apps/web/src/services/cost-explorer/cost-analysis/config.ts
> fix(cost-query-set): udpate managed cost query set 

- apps/web/src/services/asset-inventory/cloud-service/modules/CloudServices.vue
- apps/web/src/services/dashboards/dashboard-customize/modules/DashboardCustomizePageName.vue
- apps/web/src/services/dashboards/dashboard-detail/DashboardDetailPage.vue
- apps/web/src/services/dashboards/dashboard-detail/modules/DashboardControlButtons.vue
- apps/web/src/services/dashboards/shared/DashboardCloneModal.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-container/WidgetViewModeSidebar.vue
- public icon alignment adjustment(https://pyengine.atlassian.net/browse/QA-778)
- align the dashboard name input in custom mode and create mode(https://pyengine.atlassian.net/browse/QA-779)
- apply the private icon to the clone modal(https://pyengine.atlassian.net/browse/QA-789)
- And some minor style adjustments.
plz review each commit!!
> refactor(dashboard): change style and apply qa.

- apps/web/src/services/cost-explorer/budget/budget-detail/modules/budget-notifications/BudgetNotifications.vue
- apps/web/src/services/cost-explorer/budget/budget-detail/modules/budget-notifications/BudgetNotificationsModal.vue
SSIA
https://pyengine.atlassian.net/browse/QA-794
> fix(budget-notifications-modal): fix condition list bug

- apps/web/src/services/dashboards/dashboard-customize/modules/dashboard-widget-add-modal/DashboardWidgetAddModal.vue
> refactor: update DashboardWidgetAddModal to script setup

- apps/web/src/services/dashboards/shared/DashboardCloneModal.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-container/WidgetViewModeSidebar.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-input-form/DashboardWidgetInputForm.vue
- apps/web/src/services/dashboards/widgets/_helpers/widget-validation-helper.ts
> fix: do nothing for fixed widget option on variable deletion

- apps/web/src/services/cost-explorer/budget/budget-detail/BudgetDetailPage.vue
> fix(budget-detail-page): fix style of header

- apps/web/src/lib/helper/notice-alert-helper.ts
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisGroupByFilter.vue
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
https://pyengine.atlassian.net/browse/QA-812
> feat: change toast message in cost analysis page

- apps/web/src/services/dashboards/shared/dashboard-widget-container/WidgetViewModeModal.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-container/WidgetViewModeSidebar.vue
> refactor: do not use the outside's concern as the event name

- apps/web/src/services/dashboards/config.ts
- apps/web/src/services/dashboards/dashboard-create/modules/dashboard-templates/helper.ts
- apps/web/src/services/dashboards/dashboard-create/modules/dashboard-templates/templates/blank.ts
You can handle `DataSource` variable, when you choose the `BLANK` dashboard template!
> fix(blank-dashboard): add BLANK Dashboard Label & apply dataSource

- apps/web/src/services/dashboards/shared/dashboard-widget-container/WidgetViewModeModal.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-container/WidgetViewModeSidebar.vue
> fix: do not refresh on init sidebar on widget view mode

- apps/web/src/services/cost-explorer/modules/RelocateDashboardModal.vue
> fix(relocate-dashboard): edit relocate dashboard image & apply srcset

- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisDataTable.vue
> fix(cost-analysis-data-table): fix field value from 0 to unknown

- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisDataTable.vue
> fix(cost-analysis-data-table): if usage_unit is undefined, use '--'

- apps/web/src/common/composables/amcharts5/xy-chart-helper.ts
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisChartLegends.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisStackedColumnChart.vue
Solve these
https://pyengine.atlassian.net/browse/QA-730
https://pyengine.atlassian.net/browse/QA-731
> fix: fix date text bug in cost analysis chart & add date to chart tooltip 

- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisQueryFormModal.vue
- packages/language-pack/console-translation-2.8.babel
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> fix(duplicated-query): add cost query name validation

- apps/web/src/services/dashboards/shared/dashboard-widget-container/WidgetViewModeSidebar.vue
- apps/web/src/services/dashboards/widgets/_components/WidgetFrame.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-cost-trend/AWSDataTransferCostTrendWidget.vue
- apply text color and hide zoomOutButton at widget chart
- quest: https://pyengine.atlassian.net/browse/QA-780
> refactor(dashboard-widget): apply qa

- apps/web/src/common/composables/amcharts5/index.ts
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisStackedColumnChart.vue
- apps/web/src/services/home-dashboard/modules/all-summary/AllSummary.vue
- apps/web/src/services/project/project-detail/project-summary/modules/ProjectBilling.vue
> fix: fix wrong index for dataSource in AllSummary widget & feat: add tooltip for AllSummary widget 

- apps/web/src/common/modules/navigations/gnb/modules/gnb-recent-favorite/modules/GNBFavorite.vue
- apps/web/src/common/modules/navigations/lnb/modules/LNBRouterMenuItem.vue
- apps/web/src/common/modules/navigations/lnb/type.ts
- apps/web/src/lib/helper/config-data-helper.ts
- apps/web/src/services/asset-inventory/AssetInventoryLNB.vue
- apps/web/src/services/cost-explorer/CostExplorerLNB.vue
- apps/web/src/services/cost-explorer/cost-analysis/config.ts
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisQueryFormModal.vue
- apps/web/src/services/cost-explorer/routes.ts
- apps/web/src/services/cost-explorer/store/cost-query-set-store.ts
- apps/web/src/services/dashboards/DashboardsLNB.vue
- apps/web/src/store/modules/favorite/type.ts
SSIA
Please see order by commits.
> fix(favorite): apply new method managing manged-cost-query-set-favorite-key

- apps/web/src/common/composables/amcharts5/xy-chart-helper.ts
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisDataTable.vue
- apps/web/src/store/modules/file/actions.ts
> feat: export excel with data 

- packages/mirinae/src/inputs/dropdown/filterable-dropdown/PFilterableDropdown.stories.mdx
- packages/mirinae/src/inputs/dropdown/filterable-dropdown/PFilterableDropdown.vue
- packages/mirinae/src/inputs/dropdown/filterable-dropdown/story-helper.ts
> feat(mirinae): add initSelectedWithHandler prop to PFilterableDropdown

- apps/web/src/services/dashboards/shared/dashboard-widget-input-form/DashboardWidgetInputForm.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-input-form/helpers/form-data-helper.ts
- apps/web/src/services/dashboards/widgets/__tests__/_helpers/widget-inherit-options-helper.test.ts
- apps/web/src/services/dashboards/widgets/_configs/config.ts
- apps/web/src/services/dashboards/widgets/_helpers/widget-inherit-options-helper.ts
- apps/web/src/services/dashboards/widgets/_helpers/widget-options-helper.ts
- apps/web/src/services/dashboards/widgets/_helpers/widget-schema-helper.ts
- apps/web/src/services/dashboards/widgets/_hooks/use-widget/use-merged-widget-state.ts
> fix: consider variable is used or not on init inherit options

- apps/web/src/common/modules/navigations/gnb/modules/gnb-menu/GNBSubMenu.vue
- apps/web/src/services/cost-explorer/CostExplorerLNB.vue
SSIA
[QA-796](https://pyengine.atlassian.net/browse/QA-796)
[QA-801](https://pyengine.atlassian.net/browse/QA-801)
> fix(qa-796): fix data source dropdown style issue & fix(qa-801): fix dashboard gnb submenu style issue

- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisStackedColumnChart.vue
- packages/core-lib/src/index.ts
- packages/mirinae/src/feedbacks/alert/toast-alert/PToastAlert.vue
> feat: add `targetMin` args to `numberFormatter()` & feat: delete `capitalize` from `PToastAlert` title

- apps/web/src/services/dashboards/shared/dashboard-variables/DashboardVariablesMoreButton.vue
- apps/web/src/services/dashboards/shared/dashboard-variables/DashboardVariablesSelectDropdown.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/cost-trend/widget-config.ts
> fix: hide dashboard variable more button on view mode modal

- apps/web/src/common/modules/navigations/gnb/modules/gnb-recent-favorite/modules/GNBRecent.vue
- apps/web/src/lib/helper/router-recent-helper.ts
- apps/web/src/store/modules/recent/actions.ts
- apps/web/src/store/modules/recent/index.ts
- apps/web/src/store/modules/recent/mutations.ts
- apps/web/src/store/modules/recent/type.ts
SSIA
[QA - 809](https://pyengine.atlassian.net/browse/QA-809)
CostAnalysis recent is still not working. After console-api updated, I will be working..
Please see order by commits.
> fix(recent): apply Dashboard/CostAnalysis GNB recent

- apps/web/src/services/dashboards/config.ts
- apps/web/src/services/dashboards/managed-variables-schema.ts
- apps/web/src/services/dashboards/shared/dashboard-variables/DashboardVariablesDropdown.vue
> fix: add default_path to variable schema to separate required and default value setting

- apps/web/src/services/asset-inventory/collector/collector-create/modules/CreateCollectorStep2.vue
- apps/web/src/services/asset-inventory/collector/collector-create/modules/MultipleProviderForm.vue
- apps/web/src/services/asset-inventory/collector/collector-create/modules/Step1SearchFilter.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorNameForm.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorTagForm.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorVersionForm.vue
- Initialize value of multipleProviderForm with first value.
- Add validation to provider form of step2.
> fix(collector-create): fix the form bug of step 2

- apps/web/src/services/dashboards/shared/dashboard-variables/DashboardVariablesSelectDropdown.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-container/WidgetViewModeModal.vue
> fix: do not hide more button on isManageable prop

- apps/web/src/services/dashboards/dashboard-create/modules/dashboard-templates/helper.ts
- apps/web/src/services/dashboards/shared/dashboard-widget-container/WidgetViewModeModal.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-container/WidgetViewModeSidebar.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-input-form/DashboardWidgetInputForm.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-input-form/helpers/form-data-helper.ts
- apps/web/src/services/dashboards/shared/dashboard-widget-input-form/widget-form-store.ts
- apps/web/src/services/dashboards/shared/helpers/dashboard-variable-schema-helper.ts
- apps/web/src/services/dashboards/widgets/__tests__/_helpers/widget-inherit-options-helper.test.ts
- apps/web/src/services/dashboards/widgets/_components/WidgetFrame.vue
- apps/web/src/services/dashboards/widgets/_helpers/widget-inherit-options-helper.ts
- apps/web/src/services/dashboards/widgets/_helpers/widget-schema-helper.ts
- apps/web/src/services/dashboards/widgets/_helpers/widget-validation-helper.ts
- apps/web/src/services/dashboards/widgets/_hooks/use-widget-lifecycle.ts
- apps/web/src/services/dashboards/widgets/_hooks/use-widget/use-merged-widget-state.ts
- apps/web/src/services/dashboards/widgets/_hooks/use-widget/use-widget-frame.ts
> fix: inherit error messages must be calculated with variables schema

- apps/web/src/services/cost-explorer/cost-analysis/CostAnalysisPage.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisFiltersAddMoreButton.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisFiltersPopper.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisGroupByFilter.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisQueryFilter.vue
- packages/mirinae/src/hooks/context-menu-controller/index.ts
- packages/mirinae/src/hooks/context-menu-fixed-style/index.ts
- packages/mirinae/src/inputs/dropdown/select-dropdown/components/dropdown-button.vue
https://pyengine.atlassian.net/browse/QA-807
https://pyengine.atlassian.net/browse/QA-815
+ add) when `useFixedStyle` is enabled, the context menu's position is adjusted relative to the target, and it closes when scrolling for someday...
https://pyengine.atlassian.net/browse/QA-817
plz check by commits!!
> refactor: apply design QA at cost analysis detail page

- apps/web/src/services/cost-explorer/cost-analysis/CostAnalysisPage.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisFiltersPopper.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisQueryFilter.vue
> fix: bug fix for abnormal styling

- apps/web/src/services/cost-explorer/budget/budget-main/modules/budget-list/BudgetUsageProgressBar.vue
> fix(budget-usage-progress-bar): apply computed to percentage state

- apps/web/src/services/dashboards/dashboard-create/modules/DashboardViewerForm.vue
- packages/language-pack/en.json
- fix(lnb): update translation
[QA - 824](https://pyengine.atlassian.net/browse/QA-824)
- fix(dashboard-create): edit dashboard create viewer form style
[QA - 825](https://pyengine.atlassian.net/browse/QA-825)
> fix(lnb): update translation & fix(dashboard-create): edit dashboard create viewer form style

- apps/web/src/services/asset-inventory/collector/collector-main/CollectorMainPage.vue
- apps/web/src/services/asset-inventory/collector/collector-main/collector-page-store.ts
- apps/web/src/services/asset-inventory/collector/collector-main/lib/reference-value-helper.ts
- apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContents.vue
> feat: modify to display 'name' instead of 'id' when searching by plugin and add related handlers

- apps/web/src/common/modules/project/ProjectSelectDropdown.vue
- apps/web/src/services/administration/iam/user/modules/user-management-modal/modules/UserInfoForm.vue
- apps/web/src/services/alert-manager/alert/alert-detail/modules/alert-responder/AlertResponder.vue
- apps/web/src/services/asset-inventory/cloud-service/modules/CloudServiceFilterSearchDropdown.vue
- apps/web/src/services/asset-inventory/collector/shared/collector-forms/AttachedServiceAccountForm.vue
- apps/web/src/services/info/notice/modules/NoticeForm.vue
- apps/web/src/services/my-page/my-account/user-account/modules/BaseInformation.vue
- apps/web/src/services/my-page/my-account/user-account/modules/ChangePassword.vue
- apps/web/src/services/notification/modules/AddNotificationMemberGroup.vue
- apps/web/src/services/project/project-detail/project-member/modules/ProjectMemberAddModal.vue
- apps/web/src/services/project/project-detail/project-member/modules/ProjectMemberUpdateModal.vue
> refactor: update template to script setup

- apps/web/src/services/dashboards/dashboard-customize/modules/dashboard-manage-variable-overlay/DashboardManageVariableOverlay.vue
- apps/web/src/services/dashboards/shared/dashboard-variables/DashboardVariablesMoreButton.vue
SSIA
[QA - 818](https://pyengine.atlassian.net/browse/QA-818)
> fix(dashboard-variable): fix manage-variable overlay issue

- apps/web/src/services/project/project-detail/project-member/modules/ProjectMemberAddModal.vue
- apps/web/src/services/project/project-detail/project-member/modules/ProjectMemberUpdateModal.vue
- apps/web/src/services/project/project-detail/project-member/type.ts
> fix: fixing the change value at select-dropdown

- apps/web/src/services/cost-explorer/cost-analysis/CostAnalysisPage.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisQueryFilter.vue
> refactor: apply horizontal scroll to the entire content

- apps/web/src/lib/reference/asset-reference-config.ts
- apps/web/src/lib/reference/reference-config.ts
- apps/web/src/services/dashboards/managed-variables-schema.ts
- apps/web/src/services/dashboards/widgets/_base/base-count-of-findings/BaseCountOfFindingsWidget.vue
- apps/web/src/services/dashboards/widgets/_configs/config.ts
- apps/web/src/services/dashboards/widgets/_configs/widget-schema-config.ts
- apps/web/src/services/dashboards/widgets/_helpers/widget-schema-helper.ts
- apps/web/src/services/dashboards/widgets/asset-widgets/compliance-status/ComplianceStatusWidget.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/compliance-status/widget-config.ts
- apps/web/src/services/dashboards/widgets/asset-widgets/count-of-fail-findings/widget-config.ts
- apps/web/src/services/dashboards/widgets/asset-widgets/count-of-pass-and-fail-findings/widget-config.ts
- apps/web/src/services/dashboards/widgets/asset-widgets/severity-status-by-service/SeverityStatusByServiceWidget.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/severity-status-by-service/widget-config.ts
- apps/web/src/services/dashboards/widgets/asset-widgets/total-fail-findings-status/TotalFailFindingsStatusWidget.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/total-fail-findings-status/widget-config.ts
- apps/web/src/services/dashboards/widgets/asset-widgets/trend-of-pass-and-fail-findings/TrendOfPassAndFailFindingsWidget.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/trend-of-pass-and-fail-findings/widget-config.ts
- apps/web/src/store/reference/all-reference-store.ts
- apps/web/src/store/reference/asset-query-set-reference-store.ts
- In dashboard variables
- In widget options
> feat: add `asset_query_set` to managed variables and widget options

- apps/web/src/services/cost-explorer/cost-analysis/CostAnalysisPage.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisFiltersPopper.vue
- apps/web/src/services/my-page/my-account/user-account/modules/BaseInformation.vue
> chore: margin and width adjustment

- apps/web/src/services/dashboards/shared/dashboard-widget-input-form/DashboardWidgetInputForm.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-input-form/widget-form-store.ts
> fix: do not return if widgetKey is not given at widget-form-store initWIdgetForm

- apps/web/src/lib/helper/notice-alert-helper.ts
- apps/web/src/lib/helper/verify-email-helper.ts
- apps/web/src/services/administration/iam/user/modules/UserManagementTable.vue
- apps/web/src/services/auth/password/PasswordPage.vue
- apps/web/src/services/my-page/my-account/user-account/modules/ChangePassword.vue
- packages/core-lib/src/space-connector/error.ts
> fix(core-lib): fix error response format of spaceConnector

- apps/web/src/services/dashboards/dashboard-create/DashboardCreatePage.vue
- apps/web/src/services/dashboards/dashboard-create/modules/DashboardTemplateForm.vue
> feat: apply `p-link` and fix top alignment on the create dashboard 2nd step

- apps/web/src/services/dashboards/widgets/_base/base-count-of-findings/BaseCountOfFindingsWidget.vue
- apps/web/src/services/dashboards/widgets/_configs/asset-config.ts
- apps/web/src/services/dashboards/widgets/asset-widgets/compliance-status/ComplianceStatusWidget.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/severity-status-by-service/SeverityStatusByServiceWidget.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/total-fail-findings-status/TotalFailFindingsStatusWidget.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/trend-of-pass-and-fail-findings/TrendOfPassAndFailFindingsWidget.vue
Just fix request query for updated api.
> feat: update api query of asset widgets 

- apps/web/src/services/project/project-detail/project-member/modules/ProjectMemberAddModal.vue
- apps/web/src/services/project/project-detail/project-member/modules/ProjectMemberUpdateModal.vue
- packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.stories.mdx
- packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
- packages/mirinae/src/inputs/dropdown/select-dropdown/story-helper.ts
> feat: apply initSelectedWithHandler at select-dropdown storybook

- apps/web/src/services/cost-explorer/budget/shared/budget-form/budget-form-amount-plan/BudgetFormAmountPlanMonthly.vue
- packages/core-lib/src/index.ts
[This Issue](https://pyengine.atlassian.net/browse/QA-833)
> fix: fix auto-fill logic & fix floating-point bug

- apps/web/src/services/dashboards/shared/dashboard-variables/DashboardVariablesDropdown.vue
> fix(default-variable): solve default variable issue

- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisHeader.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisQueryFilter.vue
> feat: check manage permission in cost analysis page

- apps/web/src/services/dashboards/dashboard-create/modules/DashboardTemplateForm.vue
> fix: fix PLink bug in DashboardTemplateForm

- apps/web/src/services/cost-explorer/budget/budget-detail/modules/budget-summary/BudgetSummaryTable.vue
- apps/web/src/services/cost-explorer/cost-analysis/lib/widget-data-helper.ts
> refactor: change from router link to PLink

- apps/web/src/services/dashboards/shared/DashboardWidgetEditModal.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-container/DashboardWidgetContainer.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-input-form/DashboardWidgetInputForm.vue
- apps/web/src/services/dashboards/widgets/_helpers/widget-options-helper.ts
- apps/web/src/services/dashboards/widgets/_helpers/widget-validation-helper.ts
- apps/web/src/services/dashboards/widgets/_hooks/use-widget/use-merged-widget-state.ts
> fix: do not use i18n.t at helper (it causes vue error) and refresh widget on widget edit modal cancel

- apps/web/src/services/dashboards/shared/dashboard-widget-container/DashboardWidgetContainer.vue
- apps/web/src/services/dashboards/widgets/_components/WidgetDataTable.vue
- apps/web/src/services/dashboards/widgets/_components/type.ts
- apps/web/src/services/dashboards/widgets/_helpers/widget-chart-helper.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-cloud-front-cost/widget-config.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-cost-trend/AWSDataTransferCostTrendWidget.vue
> fix: apply updated spec for usage_unit to aws cost trend widget and update widget data table

- apps/web/src/services/dashboards/widgets/_components/type.ts
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-cloud-front-cost/AWSCloudFrontCostWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-by-region/AWSDataTransferByRegionWidget.vue
> feat: update widgets for usage_unit 

- apps/web/src/services/cost-explorer/cost-analysis/lib/data-table-helper.ts
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisDataTable.vue
Updated
- Always display the cost/usage dropdown.
- When querying, fetch the `usage_quantity_sum` or `cost_sum` based on the selected option in the dropdown.
- If the `usage` option is chosen in the cost/usage dropdown, display the "Usage Unit" column only when the `usage_type` is selected in the group_by.
> fix(cost-analysis-data-table): fix and improve incorrect features

- apps/web/src/services/dashboards/shared/DashboardWidgetEditModal.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-container/WidgetViewModeSidebar.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-cloud-front-cost/AWSCloudFrontCostWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-by-region/AWSDataTransferByRegionWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-cost-trend/AWSDataTransferCostTrendWidget.vue
> feat: display 'Unknown' if column is `null` & hide chart when `usage_unit` is null

- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisDataTable.vue
> feat(cost-analysis-data-table): apply usageUnitFormatter

- apps/web/src/services/dashboards/widgets/cost-widgets/aws-cloud-front-cost/AWSCloudFrontCostWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-by-region/AWSDataTransferByRegionWidget.vue
> chore: set additional sort to request api

- apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-by-region/AWSDataTransferByRegionWidget.vue
- apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-cost-trend/AWSDataTransferCostTrendWidget.vue
> fix: fix widget link bug

- apps/web/src/services/dashboards/managed-variables-schema.ts
- apps/web/src/services/dashboards/shared/helpers/dashboard-widget-info-helper.ts
- apps/web/src/services/dashboards/widgets/_helpers/widget-inherit-options-helper.ts
- apps/web/src/services/dashboards/widgets/_helpers/widget-validation-helper.ts
> fix: remove user selected option if it is inherited

- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisHeader.vue
- Fix favorite list sync error. ([ticket](https://pyengine.atlassian.net/browse/QA-843))
> fix(cost-analysis-header): fix favorite button of managedCostQuerySet

- apps/web/src/lib/reference/asset-reference-config.ts
- apps/web/src/services/dashboards/managed-variables-schema.ts
- apps/web/src/services/dashboards/widgets/_configs/widget-schema-config.ts
- apps/web/src/services/dashboards/widgets/_helpers/widget-schema-helper.ts
> chore: change typo from 'Query Set' to 'Compliance Overview'

- apps/web/src/lib/helper/config-data-helper.ts
[QA - 844](https://pyengine.atlassian.net/browse/QA-844)
SSIA
> fix(recent): handle removed data source case in cost analysis recent

- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisFiltersPopper.vue
> fix(cost-analysis-filters-popper): fix distinct search feature

- apps/web/src/services/administration/iam/user/modules/UserManagementTable.vue
> feat: hide excel export from user table

- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisGroupByFilter.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-container/DashboardWidgetContainer.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-container/helpers/widget-width-helper.ts
- apps/web/src/services/dashboards/store/dashboard-detail-info.ts
- apps/web/src/services/dashboards/widgets/_base/base-trend/BaseTrendWidget.vue
- apps/web/src/services/home-dashboard/modules/all-summary/AllSummary.vue
> fix: set data_source_id filter to tags menuHandler & add defense code to widget helpers

- .github/PULL_REQUEST_TEMPLATE.md
> chore: edit `PULL_REQUEST_TEMPLATE`

- apps/web/src/services/dashboards/widgets/asset-widgets/compliance-status/ComplianceStatusWidget.vue
> fix: fix api query in ComplianceStatusWidget

- apps/web/src/common/modules/dropdown/service-provider-dropdown/ServiceProviderDropdown.vue
- apps/web/src/services/cost-explorer/store/cost-analysis-page-store.ts
- apps/web/src/services/dashboards/shared/dashboard-widget-container/DashboardWidgetContainer.vue
- apps/web/src/services/dashboards/shared/dashboard-widget-container/WidgetViewModeModal.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/compliance-status/ComplianceStatusWidget.vue
- apps/web/src/services/dashboards/widgets/asset-widgets/severity-status-by-service/SeverityStatusByServiceWidget.vue
> fix: fix innerChart bug in ComplianceStatusWidget & fix api query in Severity Status By Service widget 

- apps/web/src/services/dashboards/dashboard-create/modules/DashboardScopeForm.vue
- apps/web/src/store/modules/reference/provider/actions.ts
> fix: remove sort from provider/list api query

- apps/web/src/App.vue
> chore: chore

- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisDataTable.vue
> fix: show original data in cost analysis excel

- .github/workflows/pull_request_review.yml
> fix(review-ci): remove apps(storybook, web) build step

- apps/web/src/services/cost-explorer/cost-analysis/lib/widget-data-helper.ts
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisHeader.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisQueryFilter.vue
- apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisStackedColumnChart.vue
- apps/web/src/services/cost-explorer/store/cost-analysis-page-store.ts
https://pyengine.atlassian.net/browse/QUEST-788
https://pyengine.atlassian.net/browse/QUEST-785
and fix minor bugs
> fix: set 'no data' to cost analysis chart & fix bugs in cost analysis page

- apps/web/src/services/cost-explorer/CostExplorerHome.vue
> fix(cost-landing-page): solve img src issue

- apps/web/src/common/composables/amcharts5/xy-chart-helper.ts
- apps/web/src/services/alert-manager/alert-dashboard/modules/alert-history-widget/AlertHistoryChart.vue
- apps/web/src/services/alert-manager/alert-dashboard/modules/alert-history-widget/AlertHistoryWidget.vue
> feat: change AlertHistoryChart from am4 to am5 

- packages/mirinae/src/navigation/breadcrumbs/PBreadcrumbs.vue
- Overall Template Restructuring for Removing Leading Spaces in Breadcrumb Text.
- quest: https://pyengine.atlassian.net/browse/QUEST-616
> refactor: changing the template structure and style

- apps/web/src/common/composables/amcharts5/pie-chart-helper.ts
- apps/web/src/services/home-dashboard/modules/ServiceAccounts.vue
> refactor: change `ServiceAccount` chart from am4 to am5
