cloudforet-io/console

apps/web/src/services/home-dashboard/modules/TopProjects.vue

refactor: change `TopProjects` chart from am4 to am5

---

apps/web/src/services/cost-explorer/CostExplorerHome.vue

fix(cost-landing): solve landing img issue

---

apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/CloudServiceDetail.vue

refactor(cloud-service-detail): refactor to setup script

---

apps/web/src/services/cost-explorer/routes.ts

- Move `beforeEnter` to empty cost-analysis route in children
Before
https://github.com/cloudforet-io/console/assets/83635051/f76e81ec-a25d-4214-85cd-4174528239f3
After
https://github.com/cloudforet-io/console/assets/83635051/420f0668-0f6f-4420-a0a3-c6e96cd476aa
Thanks @sulmoJ

fix(cost-analysis): solve GNB-access issue

---

apps/web/src/services/dashboards/shared/dashboard-widget-input-form/DashboardWidgetInputForm.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/DashboardWidgetSchemaForm.vue

refactor: split schema form as separated component

---

apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorOptionsForm.vue

fix(collector-options-form): fix empty case validation bug

---

apps/web/src/services/dashboards/dashboard-customize/modules/dashboard-manage-variable-overlay/DashboardManageVariableTable.vue

fix(manage-variable-table): add defensive code

---

apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisFiltersAddMoreButton.vue

feat: add tags menu to cost analysis filters

---

apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorBaseInfoSection.vue
apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorOptionsForm.vue

fix(collector): modify to wait for loading process & fix event name

---

apps/web/src/services/dashboards/widgets/_configs/widget-config.ts

feat: add widget-config.ts for new widget config options_schema spec

---

apps/web/src/services/my-page/my-account/user-api-key/UserAPIKeyPage.vue

refactor(user-api-key-page): refactor to setup script

---

apps/web/src/services/dashboards/widgets/_configs/config.ts
apps/web/src/services/dashboards/widgets/_configs/widget-options-schema-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/aws-cloud-front-cost/AWSCloudFrontCostWidget.vue

refactor: rename the file name for widget options schema

---

apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisFiltersPopper.vue

fix: add tags filter to popper

---

packages/core-lib/src/space-connector/index.ts

fix(core-lib): fix v2 reflection api path

---

apps/web/src/services/my-page/my-account/user-api-key/UserAPIKeyPage.vue
apps/web/src/services/my-page/my-account/user-api-key/modules/GRPCEndpointsTab.vue
apps/web/src/services/my-page/my-account/user-api-key/modules/RestEndpointsTab.vue

feat(api-key): add rest api endpoint information

---

apps/web/src/services/my-page/my-account/user-api-key/UserAPIKeyPage.vue
apps/web/src/services/my-page/my-account/user-api-key/modules/GRPCEndpointsTab.vue
apps/web/src/services/my-page/my-account/user-api-key/modules/RestEndpointsTab.vue
packages/core-lib/src/space-connector/index.ts

feat(support-rest-api): merge feature to master

---

apps/web/src/services/dashboards/widgets/_configs/widget-options-schema-config.ts
packages/mirinae/src/hooks/context-menu-controller/context-menu-attach.ts
packages/mirinae/src/hooks/context-menu-controller/index.ts
packages/mirinae/src/inputs/context-menu/type.ts
packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.stories.mdx
packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
packages/mirinae/src/inputs/dropdown/select-dropdown/components/dropdown-button.vue
packages/mirinae/src/inputs/dropdown/select-dropdown/story-helper.ts

https://github.com/cloudforet-io/console/assets/26986739/80a3323e-6ded-4823-b185-ddbad1735358

feat(mirinae): allow multiple handler (PSelectDropdown)

---

apps/web/src/services/dashboards/widgets/_base/base-count-of-findings/BaseCountOfFindingsWidget.vue
apps/web/src/services/dashboards/widgets/_base/base-count-of-findings/widget-config.ts
apps/web/src/services/dashboards/widgets/_components/WidgetFrame.vue
apps/web/src/services/dashboards/widgets/_configs/config.ts
apps/web/src/services/dashboards/widgets/_hooks/use-widget/use-widget-frame.ts
apps/web/src/services/dashboards/widgets/asset-widgets/compliance-status/ComplianceStatusWidget.vue
apps/web/src/services/dashboards/widgets/asset-widgets/compliance-status/widget-config.ts
apps/web/src/services/dashboards/widgets/asset-widgets/severity-status-by-service/SeverityStatusByServiceWidget.vue
apps/web/src/services/dashboards/widgets/asset-widgets/severity-status-by-service/widget-config.ts
apps/web/src/services/dashboards/widgets/asset-widgets/trend-of-pass-and-fail-findings/widget-config.ts
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: add `data_criteria` to WidgetConfig type & set real-time text/icon to WidgetFrame

---

apps/web/src/services/dashboards/widgets/_configs/asset-config.ts
apps/web/src/services/dashboards/widgets/asset-widgets/compliance-status/ComplianceStatusWidget.vue
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

chore: add tooltip to ComplianceStatusWidget

---

apps/web/src/models/widget/index.ts
apps/web/src/services/dashboards/config.ts
apps/web/src/services/dashboards/dashboard-customize/modules/dashboard-manage-variable-overlay/DashboardManageVariableForm.vue
apps/web/src/services/dashboards/shared/dashboard-variables/DashboardVariablesDropdown.vue
apps/web/src/services/dashboards/widgets/_configs/widget-options-schema-config.ts

refactor: standardization of model options

---

apps/web/src/services/asset-inventory/collector/shared/RecentCollectorJobList.vue
apps/web/src/services/home-dashboard/modules/all-summary/AllSummary.vue
apps/web/src/services/home-dashboard/modules/all-summary/AllSummaryDataSummary.vue
apps/web/src/services/project/project-detail/project-summary/modules/ProjectBilling.vue

https://pyengine.atlassian.net/browse/QUEST-811

feat: delete billing chart from AllSummary widget & add dataSource dropdown to ProjectBilling widget 

---

apps/web/src/services/dashboards/shared/dashboard-widget-container/WidgetViewModeModal.vue

fix: hide view-mode button in view mode modal

---

apps/web/src/services/dashboards/widgets/_base/base-count-of-findings/BaseCountOfFindingsWidget.vue
apps/web/src/services/dashboards/widgets/_hooks/use-widget/use-widget-state.ts
apps/web/src/services/dashboards/widgets/asset-widgets/compliance-status/ComplianceStatusWidget.vue
apps/web/src/services/dashboards/widgets/asset-widgets/compliance-status/widget-config.ts
apps/web/src/services/dashboards/widgets/asset-widgets/severity-status-by-service/SeverityStatusByServiceWidget.vue
apps/web/src/services/dashboards/widgets/asset-widgets/severity-status-by-service/widget-config.ts
apps/web/src/store/reference/asset-query-set-reference-store.ts

refactor: use `cloud-service/analyze` API to realtime widgets 

---

apps/web/src/services/dashboards/widgets/_hooks/use-widget/use-widget-state.ts
apps/web/src/services/dashboards/widgets/asset-widgets/total-fail-findings-status/TotalFailFindingsStatusWidget.vue
apps/web/src/services/dashboards/widgets/asset-widgets/total-fail-findings-status/widget-config.ts
apps/web/src/services/dashboards/widgets/asset-widgets/trend-of-pass-and-fail-findings/TrendOfPassAndFailFindingsWidget.vue

feat: update design and api of `TotalFailFindingsStatus` widget

---

apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/CloudServiceDetailPage.vue
apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/ExcelExportOptionModal.vue
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat(excel-export-option-modal): create new component

---

apps/web/src/services/dashboards/managed-variables-schema.ts
apps/web/src/services/dashboards/shared/dashboard-variables/DashboardVariablesDropdown.vue

fix: add compatibility code for resource_key 

---

apps/web/src/services/dashboards/widgets/asset-widgets/total-fail-findings-status/TotalFailFindingsStatusWidget.vue
apps/web/src/services/dashboards/widgets/asset-widgets/trend-of-pass-and-fail-findings/TrendOfPassAndFailFindingsWidget.vue

chore: fix minor bugs

---

apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/CloudServiceDetailPage.vue
apps/web/src/services/asset-inventory/server/ServerPage.vue

refactor(cloud-service-detail-page): refactor to setup script

---

apps/web/src/services/dashboards/widgets/_base/base-count-of-findings/BaseCountOfFindingsWidget.vue
apps/web/src/services/dashboards/widgets/_hooks/use-widget/use-widget-state.ts
apps/web/src/services/dashboards/widgets/asset-widgets/compliance-status/ComplianceStatusWidget.vue
apps/web/src/services/dashboards/widgets/asset-widgets/severity-status-by-service/SeverityStatusByServiceWidget.vue
apps/web/src/services/dashboards/widgets/asset-widgets/total-fail-findings-status/TotalFailFindingsStatusWidget.vue

feat: set `widgetLocation` to asset widgets

---

apps/web/src/lib/variable-models/_base/resource-name-variable-model.ts
apps/web/src/lib/variable-models/managed/cloud-service-query-set-variable-model.ts
apps/web/src/lib/variable-models/managed/cloud-service-type-variable-model.ts
apps/web/src/lib/variable-models/managed/collector-variable-model.ts
apps/web/src/lib/variable-models/managed/index.ts
apps/web/src/lib/variable-models/managed/project-group-variable-model.ts
apps/web/src/lib/variable-models/managed/project-variable-model.ts
apps/web/src/lib/variable-models/managed/provider-variable-model.ts
apps/web/src/lib/variable-models/managed/region-variable-model.ts
apps/web/src/lib/variable-models/managed/secret-variable-model.ts
apps/web/src/lib/variable-models/managed/service-account-variable-model.ts
apps/web/src/lib/variable-models/managed/user-variable-model.ts
apps/web/src/lib/variable-models/managed/webhook-variable-model.ts

feat: apply auto-complate-config to variable-model

---

apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/CloudServiceDetailPage.vue
apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/CloudServiceDetailTabs.vue

refactor(cloud-service-detail-page): separate the component & remove unused component

---

apps/web/src/services/asset-inventory/cloud-service/modules/CloudServiceToolbox.vue

refactor(cloud-service-toolbox): refactor to setup script

---

apps/web/src/lib/variable-models/_base/resource-name-variable-model.ts
apps/web/src/lib/variable-models/managed/cloud-service-type-variable-model.ts
apps/web/src/lib/variable-models/managed/project-variable-model.ts
apps/web/src/lib/variable-models/managed/region-variable-model.ts

fix: update resource name variable model

---

apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisDataTable.vue
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: add Original Data toggle button to cost analysis table 

---

apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisDataTable.vue
apps/web/src/services/project/project-detail/project-summary/modules/ProjectBilling.vue

fix: use temp custom comma helper

---

apps/web/src/services/dashboards/shared/dashboard-variables/DashboardVariablesDropdown.vue

fix: fix dashboard variable initializing

---

apps/web/src/services/dashboards/widgets/_configs/config.ts
apps/web/src/services/dashboards/widgets/_configs/widget-options-schema.ts
apps/web/src/services/dashboards/widgets/_helpers/widget-schema-helper.ts
apps/web/src/services/dashboards/widgets/asset-widgets/compliance-status/widget-config.ts
apps/web/src/services/dashboards/widgets/asset-widgets/count-of-fail-findings/widget-config.ts
apps/web/src/services/dashboards/widgets/asset-widgets/count-of-pass-and-fail-findings/widget-config.ts
apps/web/src/services/dashboards/widgets/asset-widgets/severity-status-by-service/widget-config.ts
apps/web/src/services/dashboards/widgets/asset-widgets/total-fail-findings-history/widget-config.ts
apps/web/src/services/dashboards/widgets/asset-widgets/total-fail-findings-status/widget-config.ts
apps/web/src/services/dashboards/widgets/asset-widgets/trend-of-pass-and-fail-findings/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/aws-cloud-front-cost/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-by-region/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-cost-trend/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/budget-status/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-by-target/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-summary/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-donut/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-map/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-pie/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-trend-stacked/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-trend/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/monthly-cost/widget-config.ts

feat: modification of options_schema in widget-config

---

apps/web/src/services/dashboards/shared/dashboard-widget-input-form/widget-form-store.ts

chore: remove deleted code

---

apps/web/src/common/modules/custom-table/custom-field-modal/CustomFieldModal.vue

fix(custom-field-modal): fix tag option logic

---

apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionDropdown.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionsForm.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/widget-form-store.ts
apps/web/src/services/dashboards/widgets/_configs/config.ts
apps/web/src/services/dashboards/widgets/_configs/widget-options-schema.ts
apps/web/src/services/dashboards/widgets/_helpers/__tests__/widget-helper.test.ts

fix: use property key with prefix 'filters.' if that is filter option

---

apps/web/src/common/composables/amcharts5/pie-chart-helper.ts
apps/web/src/common/composables/amcharts5/tree-map-helper.ts
apps/web/src/common/composables/amcharts5/xy-chart-helper.ts
apps/web/src/lib/helper/currency-helper.ts
apps/web/src/lib/helper/usage-formatter.ts
apps/web/src/services/cost-explorer/budget/budget-detail/modules/budget-info/AmountPlanningTypePopover.vue
apps/web/src/services/cost-explorer/budget/budget-detail/modules/budget-summary/BudgetSummaryTable.vue
apps/web/src/services/cost-explorer/budget/budget-main/modules/budget-list/BudgetListCard.vue
apps/web/src/services/cost-explorer/budget/shared/budget-form/budget-form-amount-plan/BudgetFormAmountPlanLastMonthsCost.vue
apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisDataTable.vue
apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisStackedColumnChart.vue
apps/web/src/services/dashboards/widgets/_base/base-trend/BaseTrendWidget.vue
apps/web/src/services/dashboards/widgets/_components/WidgetDataTable.vue
apps/web/src/services/dashboards/widgets/cost-widgets/aws-cloud-front-cost/AWSCloudFrontCostWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-cost-trend/AWSDataTransferCostTrendWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-summary/BudgetUsageSummaryWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/monthly-cost/MonthlyCostWidget.vue
apps/web/src/services/project/project-detail/project-summary/modules/ProjectBilling.vue

feat: update `currencyMoneyFormatter`

---

apps/web/src/services/dashboards/shared/dashboard-variables/DashboardVariablesMoreButton.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/widget-form-store.ts
apps/web/src/services/dashboards/store/dashboard-detail-info.ts
apps/web/src/services/dashboards/widgets/_configs/config.ts
apps/web/src/services/dashboards/widgets/_helpers/__tests__/widget-inherit-options-helper.test.ts
apps/web/src/services/dashboards/widgets/_helpers/widget-validation-helper.ts
apps/web/src/services/dashboards/widgets/_hooks/use-widget/use-merged-widget-state.ts

feat: update widget info inherit options spec

---

apps/web/src/services/dashboards/store/dashboard-detail-info.ts
apps/web/src/services/dashboards/widgets/_helpers/widget-inherit-options-helper.ts

feat: add conversion codes to fit updated option key & update getInitialWidgetInheritOptions to fit updated spec

---

apps/web/src/common/components/charts/metric-chart/MetricChart.vue
apps/web/src/common/composables/amcharts5/xy-chart-helper.ts
apps/web/src/common/modules/navigations/gnb/modules/gnb-noti/GNBNoti.vue
apps/web/src/lib/helper/usage-formatter.ts
apps/web/src/services/alert-manager/alert-dashboard/modules/AlertStateWidget.vue
apps/web/src/services/alert-manager/alert-dashboard/modules/alert-history-widget/AlertHistoryWidget.vue
apps/web/src/services/alert-manager/alert/modules/AlertDataTable.vue
apps/web/src/services/cost-explorer/budget/budget-detail/BudgetDetailPage.vue
apps/web/src/services/cost-explorer/budget/budget-detail/modules/budget-notifications/BudgetNotifications.vue
apps/web/src/services/cost-explorer/budget/budget-detail/modules/budget-summary/BudgetSummaryChart.vue
apps/web/src/services/cost-explorer/budget/shared/budget-form/budget-form-amount-plan/BudgetFormAmountPlanAutofillModal.vue
apps/web/src/services/cost-explorer/budget/shared/budget-form/budget-form-amount-plan/BudgetFormAmountPlanMonthInput.vue
apps/web/src/services/cost-explorer/budget/shared/budget-form/budget-form-amount-plan/BudgetFormAmountPlanTotal.vue
apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisStackedColumnChart.vue
apps/web/src/services/dashboards/widgets/asset-widgets/compliance-status/ComplianceStatusWidget.vue
apps/web/src/services/dashboards/widgets/asset-widgets/total-fail-findings-history/TotalFailFindingsHistoryWidget.vue
apps/web/src/services/dashboards/widgets/asset-widgets/total-fail-findings-status/TotalFailFindingsStatusWidget.vue
apps/web/src/services/home-dashboard/modules/all-summary/AllSummary.vue
apps/web/src/services/home-dashboard/modules/all-summary/AllSummaryDataSummary.vue
apps/web/src/services/project/project-detail/ProjectDetailPage.vue
apps/web/src/services/project/project-detail/project-summary/modules/ProjectAlertWidget.vue
apps/web/src/services/project/project-detail/project-summary/modules/ProjectAllSummary.vue
apps/web/src/services/project/project-detail/project-summary/modules/ProjectBilling.vue
packages/core-lib/src/index.ts

feat: refactor `numberFormatter` and delete `commaFormatter`

---

apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisDataTable.vue

fix: fix `getIsRaised()` in cost analysis data table

---

apps/web/src/lib/helper/currency-helper.ts
apps/web/src/lib/helper/usage-formatter.ts
apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisDataTable.vue
packages/core-lib/src/index.ts

fix: return original value when its not number

---

apps/web/src/lib/variable-models/managed/cost-data-field-variable-model.ts
apps/web/src/lib/variable-models/managed/index.ts
apps/web/src/services/dashboards/widgets/_configs/widget-options-schema.ts
apps/web/src/services/dashboards/widgets/asset-widgets/compliance-status/widget-config.ts
apps/web/src/services/dashboards/widgets/asset-widgets/count-of-fail-findings/widget-config.ts
apps/web/src/services/dashboards/widgets/asset-widgets/count-of-pass-and-fail-findings/widget-config.ts
apps/web/src/services/dashboards/widgets/asset-widgets/severity-status-by-service/widget-config.ts
apps/web/src/services/dashboards/widgets/asset-widgets/total-fail-findings-history/widget-config.ts
apps/web/src/services/dashboards/widgets/asset-widgets/total-fail-findings-status/widget-config.ts
apps/web/src/services/dashboards/widgets/asset-widgets/trend-of-pass-and-fail-findings/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/aws-cloud-front-cost/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-by-region/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-cost-trend/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/budget-status/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-by-target/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-summary/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-donut/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-map/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-pie/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-trend-stacked/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-trend/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/monthly-cost/widget-config.ts

feat: apply widget option schema helper

---

apps/web/src/services/asset-inventory/cloud-service/modules/CloudServiceFilterSearchDropdown.vue

fix: fix for selected item text not displaying

---

apps/web/public/config/default.json
apps/web/src/App.vue
apps/web/src/services/administration/iam/user/modules/user-management-modal/UserManagementModal.vue
apps/web/src/services/administration/iam/user/modules/user-management-modal/modules/PasswordForm.vue
apps/web/src/services/administration/iam/user/modules/user-management-tab/UserDetail.vue
apps/web/src/services/auth/sign-in/local/template/ID_PW.vue
apps/web/src/services/my-page/my-account/user-account/UserAccountPage.vue

https://pyengine.atlassian.net/browse/QUEST-836

feat: add `SMTP_ENABLED` to config

---

apps/web/src/services/project/project-detail/project-summary/modules/ProjectBilling.vue

fix: fix wrong currency symbol in ProjectBilling

---

apps/web/src/services/auth/sign-in/external/KEYCLOAK/authenticator/keycloak-auth.ts

This issue arose because the format of the Keycloak authentication server URL is not fixed. 
I have modified the logic for generating the authentication URL to be more flexible and clear.

fix(keycloak-auth): fix config value for keyCloak object creation

---

apps/web/src/lib/variable-models/managed/cost-default-field-variable-model.ts
apps/web/src/lib/variable-models/managed/index.ts
apps/web/src/services/dashboards/widgets/_configs/widget-options-schema.ts

fix: fixed cost default field

---

apps/web/src/services/dashboards/widgets/_configs/widget-options-schema.ts

feat: injecting dependencies for filters with cost_data_source

---

apps/web/src/services/dashboards/widgets/_configs/config.ts
apps/web/src/services/dashboards/widgets/_configs/widget-options-schema.ts
apps/web/src/services/dashboards/widgets/cost-widgets/aws-cloud-front-cost/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-by-region/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/budget-status/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-by-target/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-summary/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-donut/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-map/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-pie/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-trend-stacked/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-trend/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/monthly-cost/widget-config.ts

feat: add filter options & apply default item option and readonly

---

apps/web/src/lib/variable-models/_base/resource-value-variable-model.ts
apps/web/src/lib/variable-models/variable-model-menu-handler.ts
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionDropdown.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionsForm.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/widget-form-store.ts
apps/web/src/services/dashboards/shared/helpers/dashboard-variable-schema-helper.ts
apps/web/src/services/dashboards/store/dashboard-detail-info.ts
apps/web/src/services/dashboards/widgets/_helpers/__tests__/widget-schema-helper.test.ts
apps/web/src/services/dashboards/widgets/_helpers/widget-schema-helper.ts
apps/web/src/services/dashboards/widgets/_helpers/widget-validation-helper.ts

feat: connect dependencies to variable model menu handler

---

apps/web/src/lib/variable-models/managed/region-variable-model.ts
apps/web/src/services/dashboards/dashboard-create/modules/dashboard-templates/templates/compliance-overview.ts
apps/web/src/services/dashboards/store/dashboard-detail-info.ts
apps/web/src/services/dashboards/widgets/_base/base-count-of-findings/widget-config.ts
apps/web/src/services/dashboards/widgets/_configs/config.ts
apps/web/src/services/dashboards/widgets/_configs/widget-options-schema.ts
apps/web/src/services/dashboards/widgets/_hooks/use-widget/use-widget-state.ts
apps/web/src/services/dashboards/widgets/asset-widgets/count-of-fail-findings/widget-config.ts
apps/web/src/services/dashboards/widgets/asset-widgets/count-of-pass-and-fail-findings/widget-config.ts
apps/web/src/services/dashboards/widgets/asset-widgets/trend-of-pass-and-fail-findings/widget-config.ts

Please see order by commits!!!!!!

fix: change from `asset_group_by` to `asset_data_field` & fix `selection_type` of some widget options 

---

apps/web/src/lib/helper/notice-alert-helper.ts
apps/web/src/services/my-page/my-account/user-api-key/modules/APIKeyTable.vue
apps/web/src/store/modules/display/actions.ts
packages/mirinae/src/feedbacks/alert/toast-alert/PToastAlert.vue

This is a usability change and improvement for our alert system. 
We are using the "vue-notification" library to display toast alerts on the screen.
I added a feature "id" attribute that allows us to manage the lifecycle of the components.
Your attention and feedback are highly appreciated!
[ID spec](https://github.com/euvl/vue-notification#programatic-closing)

feat(notice-alert-helper): add id & group params to some helpers

---

apps/web/src/lib/variable-models/_base/types.ts
apps/web/src/lib/variable-models/index.ts
apps/web/src/lib/variable-models/managed/project-variable-model.ts
apps/web/src/lib/variable-models/variable-model-menu-handler.ts
apps/web/src/services/dashboards/shared/dashboard-variables/DashboardVariablesDropdown.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionsForm.vue
apps/web/src/services/dashboards/widgets/_configs/widget-options-schema.ts
apps/web/src/services/dashboards/widgets/asset-widgets/total-fail-findings-status/TotalFailFindingsStatusWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/cost-pie/widget-config.ts

I apologize for the misunderstood commit.😥
Please see **FILE CHANGES**

feat: create `getVariableModelMenuHandler()` in widget form & update `item_options` of `cost_data_field`

---

apps/web/src/services/dashboards/widgets/asset-widgets/total-fail-findings-status/TotalFailFindingsStatusWidget.vue

chore: fix template

---

apps/web/src/lib/variable-models/managed/asset-additional-info-key-variable-model.ts
apps/web/src/lib/variable-models/managed/asset-data-key-variable-model.ts
apps/web/src/lib/variable-models/managed/asset-default-field-variable-model.ts
apps/web/src/lib/variable-models/managed/cost-additional-info-key-variable-model.ts
apps/web/src/lib/variable-models/managed/cost-data-key-variable-model.ts
apps/web/src/lib/variable-models/managed/cost-tag-key-variable-model.ts
apps/web/src/lib/variable-models/managed/index.ts
apps/web/src/services/dashboards/widgets/_configs/widget-options-schema.ts

feat: add AssetDefaultField, AssetAdditionalInfoKey models & update query & update `item_options`

---

apps/web/src/services/dashboards/widgets/cost-widgets/aws-cloud-front-cost/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-by-region/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-summary/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-donut/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-map/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-pie/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-trend-stacked/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-trend/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/monthly-cost/widget-config.ts

feat: add cost_additional_info_value and cost_tag_value filter option

---

apps/web/src/services/dashboards/widgets/_configs/widget-options-schema.ts

feat: add `asset_data_type` to widget options

---

apps/web/src/lib/variable-models/managed/cost-additional-info-key-variable-model.ts
apps/web/src/services/dashboards/dashboard-create/modules/dashboard-templates/templates/cdn-and-traffic-cost.ts
apps/web/src/services/dashboards/widgets/_configs/config.ts
apps/web/src/services/dashboards/widgets/_configs/widget-options-schema.ts
apps/web/src/services/dashboards/widgets/_helpers/widget-schema-helper.ts
apps/web/src/services/dashboards/widgets/_helpers/widget-validation-helper.ts
apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-by-region/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-trend/widget-config.ts

fix: separate WidgetFilterOptionKey and WidgetFilterKey

---

apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardCostWidgetValueOptionDropdown.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionDropdown.vue

feat: creating and positioning a value dropdown component

---

apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionDropdown.vue
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: add translation when no items are selected

---

apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionDropdown.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionsForm.vue
apps/web/src/services/dashboards/widgets/_configs/widget-options-schema.ts

apply PR review comment (https://github.com/cloudforet-io/console/pull/2154)

refactor: conditional processing using keys instead of labels

---

apps/web/src/lib/variable-models/managed/cost-additional-info-key-variable-model.ts
apps/web/src/services/dashboards/widgets/_base/base-count-of-findings/BaseCountOfFindingsWidget.vue
apps/web/src/services/dashboards/widgets/_configs/widget-options-schema.ts
apps/web/src/services/dashboards/widgets/cost-widgets/budget-status/BudgetStatusWidget.vue

fix: fix request query (group_by) of BudgetStatus widget & fix `selection_type` of asset data field

---

apps/web/src/lib/reference/asset-reference-config.ts
apps/web/src/lib/reference/reference-config.ts
apps/web/src/services/dashboards/store/dashboard-detail-info.ts
apps/web/src/services/dashboards/widgets/_configs/config.ts
apps/web/src/services/dashboards/widgets/_hooks/use-widget/use-widget-state.ts
apps/web/src/services/dashboards/widgets/asset-widgets/total-fail-findings-history/TotalFailFindingsHistoryWidget.vue
apps/web/src/services/dashboards/widgets/asset-widgets/trend-of-pass-and-fail-findings/TrendOfPassAndFailFindingsWidget.vue
apps/web/src/store/reference/all-reference-store.ts
apps/web/src/store/reference/cloue-service-query-set-reference-store.ts

fix: change variable from `asset_query_set` to `cloud_service_query_set`

---

apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/CloudServiceDetailPage.vue
apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/ExcelExportOptionModal.vue
apps/web/src/services/asset-inventory/cloud-service/modules/CloudServiceToolbox.vue

feat: apply real data(clodServiceType meta data) to excel download option modal

---

apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/CloudServiceDetailPage.vue
apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/ExcelExportOptionModal.vue

The Excel download range shown in the image should currently include data for both the table items and the detailed information for each item.
However, some parts of the API are still incomplete. 
So I have prioritized applying the existing download scope for now.

feat(excel-export-option-modal): appl new export api

---

apps/web/src/services/dashboards/dashboard-create/modules/dashboard-templates/templates/cdn-and-traffic-cost.ts
apps/web/src/services/dashboards/widgets/_base/base-trend/BaseTrendWidget.vue
apps/web/src/services/dashboards/widgets/_configs/config.ts
apps/web/src/services/dashboards/widgets/_configs/widget-list-config.ts
apps/web/src/services/dashboards/widgets/_helpers/widget-chart-helper.ts
apps/web/src/services/dashboards/widgets/_helpers/widget-table-helper.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region-multi-fields/CostByRegionMultiFieldsWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region-multi-fields/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-summary-multi-fields/CostSummaryMultiFieldsWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/cost-summary-multi-fields/widget-config.ts
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: change hard coded widget spec for two widgets

---

apps/web/src/services/dashboards/shared/dashboard-widget-container/WidgetViewModeSidebar.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionDropdown.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionsForm.vue

https://github.com/cloudforet-io/console/assets/18563857/fc68b5e0-610e-4f46-b771-82d0db13f37f

feat: set validation and refactor code in dashboard widget options form

---

apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/CloudServiceDetailPage.vue
apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/lib/helper.ts
apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/lib/type.ts
apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/CloudServiceDetailTabs.vue
apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/ExcelExportOptionModal.vue

I open a Pull Request (PR) combining the small tasks. Please read it in the order of commits.

feat: add plan details for cloudService excel download

---

apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionDropdown.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionsForm.vue

https://github.com/cloudforet-io/console/assets/18563857/579e2c44-5be1-4bac-9827-aff0b8a7eba5

feat: add refresh event to widget form

---

apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardCostWidgetValueOptionDropdown.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionDropdown.vue
apps/web/src/services/dashboards/widgets/_configs/widget-options-schema.ts
packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue

SSIA
plz check only last commit!!

feat: apply filter option component for cost-tags/cost-additional_info

---

apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionDropdown.vue

chore: apply is-fixed-width at select-dropdown

---

apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionsForm.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/widget-form-store.ts

refactor: move `returnToInitialSettings` from page to store action

---

apps/web/src/lib/variable-models/_base/enum-variable-model.ts
apps/web/src/lib/variable-models/managed/cost-data-key-variable-model.ts
apps/web/src/lib/variable-models/managed/granularity-variable-model.ts
apps/web/src/lib/variable-models/managed/index.ts
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/DashboardWidgetForm.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/composables/use-widget-title-input.ts
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionDropdown.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/widget-form-store.ts
apps/web/src/services/dashboards/store/dashboard-detail-info.ts
apps/web/src/services/dashboards/widgets/_base/base-trend/BaseTrendWidget.vue
apps/web/src/services/dashboards/widgets/_base/base-trend/widget-config.ts
apps/web/src/services/dashboards/widgets/_components/WidgetDataTable.vue
apps/web/src/services/dashboards/widgets/_configs/widget-options-schema.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region-multi-fields/CostByRegionMultiFieldsWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/cost-trend-stacked/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-trend/widget-config.ts

Plz review in order by commits

fix: add granularity option schema and update base trend related widgets

---

apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionDropdown.vue
apps/web/src/services/dashboards/widgets/_helpers/__tests__/widget-inherit-options-helper.test.ts
apps/web/src/services/dashboards/widgets/_helpers/widget-inherit-options-helper.ts

fix: fix update bug of filters (non-inherit case)  & fix bug for non-inherit case in `getInitialWidgetInheritOptions`

---

apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardCostWidgetValueOptionDropdown.vue

feat: apply selected menu list at context-menu

---

apps/web/src/services/dashboards/shared/DashboardWidgetEditModal.vue
apps/web/src/services/dashboards/widgets/_base/base-pie/BasePieWidget.vue
apps/web/src/services/dashboards/widgets/_configs/config.ts
apps/web/src/services/dashboards/widgets/_hooks/use-widget/use-widget-date-range.ts
apps/web/src/services/dashboards/widgets/_hooks/use-widget/use-widget-location.ts
apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-by-target/BudgetUsageByTargetWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-by-target/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-summary/BudgetUsageSummaryWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region-multi-fields/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region/CostByRegionWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-donut/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-map/CostMapWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/cost-map/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-pie/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-summary-multi-fields/CostSummaryMultiFieldsWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/cost-summary-multi-fields/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/monthly-cost/widget-config.ts

fix: check cost widgets for common usages and fix minor bugs

---

apps/web/src/lib/variable-models/_base/resource-name-variable-model.ts
apps/web/src/lib/variable-models/_base/resource-value-variable-model.ts

fix: except empty string case when list() resource variable model

---

apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionsForm.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/widget-form-store.ts
apps/web/src/services/dashboards/widgets/_configs/widget-options-schema.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region-multi-fields/CostByRegionMultiFieldsWidget.vue

feat: apply error case for global scope of widget option is not selected

---

apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardCostWidgetValueOptionDropdown.vue

feat: apply show more button at context-menu

---

apps/web/src/lib/variable-models/managed/asset-additional-info-key-variable-model.ts
apps/web/src/lib/variable-models/managed/asset-data-key-variable-model.ts

fix: add prefix `additional_info.` to asset additional info key model & fix `ReturnType` of asset data key model

---

apps/web/src/services/dashboards/shared/dashboard-variables/DashboardVariablesDropdown.vue

solve the bug where 'selected' wasn't updating

fix: fix select bug in dashboard variable dropdown

---

apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionDropdown.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/widget-form-store.ts

PLEASE SEE **Files changed**
https://pyengine.atlassian.net/browse/QA-848

fix: set `variable_key` when merge widget info

---

apps/web/src/services/dashboards/widgets/_helpers/widget-schema-helper.ts

fix: fix tooltip text of widget frame

---

apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/CloudServiceDetailTabs.vue
apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/cloud-service-history-detail/CloudServiceMultipleSelectedData.vue

The "Base Information" for multiple choices has been separately implemented to be displayed in a table. 
In the future, tables with MongoDB's unwind functionality will also be implemented as part of the plan.

feat(cloud-service-multiple-selected-data): create new component

---

apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionDropdown.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionsForm.vue
apps/web/src/services/dashboards/widgets/_components/WidgetDataTable.vue
apps/web/src/services/dashboards/widgets/_configs/widget-options-schema.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region-multi-fields/CostByRegionMultiFieldsWidget.vue

fix: all widget's null case key is 'Unknown'

---

apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionDropdown.vue

fix: do not show inherit toggle if inheritance mode is NONE

---

apps/web/src/services/dashboards/shared/DashboardRefreshDropdown.vue
apps/web/src/services/dashboards/widgets/asset-widgets/total-fail-findings-status/TotalFailFindingsStatusWidget.vue

chore: edit minor style issue

---

apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region/CostByRegionWidget.vue

fix: fix the height of the region chart

---

apps/web/src/services/dashboards/shared/dashboard-widget-container/WidgetViewModeModal.vue

fix: apply changes by refreshing widget after one tick at view mode modal

---

apps/web/src/lib/component-util/dynamic-layout/index.ts
apps/web/src/models/export/index.ts
apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/cloud-service-history-detail/CloudServiceMultipleSelectedData.vue

plz, check in order by commit.

feat: apply unwind spec to 'list' and 'export' api excluding search function

---

apps/web/src/services/dashboards/widgets/_base/base-trend/BaseTrendWidget.vue
apps/web/src/services/dashboards/widgets/_helpers/__tests__/widget-value-label-helper.test.ts
apps/web/src/services/dashboards/widgets/_helpers/widget-value-label-helper.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region-multi-fields/CostByRegionMultiFieldsWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/cost-summary-multi-fields/CostSummaryMultiFieldsWidget.vue

fix: apply reference value with usage unit in 3 widgets

---

apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/config.ts
apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/lib/helper.ts
apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/ExcelExportOptionModal.vue
apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/cloud-service-history-detail/CloudServiceMultipleSelectedData.vue

Now, we can download each options.
The API is expected to undergo changes soon, with the removal of the rootPath. Although this modification is imminent, I have proceeded with the implementation of the functionality.

feat(excel-export-option-modal): apply unwind spec to excel export api

---

apps/web/src/models/export/index.ts
apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/lib/helper.ts
apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/ExcelExportOptionModal.vue
apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/cloud-service-history-detail/CloudServiceMultipleSelectedData.vue
packages/mirinae/src/data-display/dynamic/dynamic-layout/type/layout-schema.ts

feat: add query search to cloudServiceMultipleSelectedData & modify to updated unwind spec

---

apps/web/src/lib/component-util/dynamic-layout/index.ts
apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/lib/helper.ts
apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/CloudServiceDetail.vue
apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/ExcelExportOptionModal.vue
apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/cloud-service-history-detail/CloudServiceMultipleSelectedData.vue

feat: remove get-data api and change to list api

---

apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardCostWidgetValueOptionDropdown.vue

refactor: implementing a context-menu from scratch & apply search-bar

---

apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/ExcelExportOptionModal.vue

fix: change value of dataLoader props.data

---

apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/ExcelExportOptionModal.vue

fix: add is_multiple option to schema api

---

apps/web/src/services/asset-inventory/cloud-service/modules/cloud-service-list/CloudServiceListCard.vue

[Quest-859](https://pyengine.atlassian.net/browse/QUEST-859)
Apply multiple ellipsis style to `cloud-service-list-card`.
Before
After

fix(cloud-service-card): fix cloud-service-card text overflow issue

---

apps/web/src/lib/variable-models/managed/cloud-service-query-set-variable-model.ts
apps/web/src/services/dashboards/config.ts
apps/web/src/services/dashboards/dashboard-create/modules/dashboard-templates/helper.ts
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionDropdown.vue
apps/web/src/services/dashboards/widgets/asset-widgets/total-fail-findings-history/TotalFailFindingsHistoryWidget.vue
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

It's simple!!!
Please see order by commits!

fix: enable complianceFramework in Blank template & etc

---

apps/web/src/services/asset-inventory/cloud-service/modules/cloud-service-list/CloudServiceListCard.vue

SSIA
https://github.com/cloudforet-io/console/pull/2207

fix(cloud-service-card): fix cloud-service-card text overflow issue (#2207)

---

apps/web/src/services/dashboards/shared/dashboard-widget-container/WidgetViewModeModal.vue
apps/web/src/services/dashboards/shared/dashboard-widget-container/WidgetViewModeSidebar.vue

fix: fix sidebar open/close issue

---

apps/web/src/services/dashboards/shared/dashboard-widget-container/WidgetViewModeModal.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionDropdown.vue

use `widgetFormGetters.updatedWidgetInfo` instead of local state

fix: fix init but when reopen sidebar

---

apps/web/src/services/dashboards/shared/dashboard-widget-container/WidgetViewModeModal.vue

fix: close sidebar on view mode initializing

---

apps/web/src/lib/variable-models/managed/index.ts
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionDropdown.vue

feat: add `referenceKey` to `MANAGED_VARIABLE_MODEL_CONFIGS`

---

apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionDropdown.vue

fix: init after global option is initiated

---

apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionDropdown.vue

fix: init menu handlers before init selected menu items

---

apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionDropdown.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/widget-form-store.ts

fix: reset init states on update inherit toggle

---

apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionDropdown.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/widget-form-store.ts

fix: watch listQueryOptions for init

---

apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionDropdown.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionsForm.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/widget-form-store.ts

fix: fix initOptionsValidMap() bug 

---

apps/web/src/lib/variable-models/managed/cost-additional-info-key-variable-model.ts
apps/web/src/lib/variable-models/managed/cost-tag-key-variable-model.ts
apps/web/src/services/dashboards/shared/dashboard-widget-container/WidgetViewModeSidebar.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/DashboardWidgetForm.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/DashboardWidgetMoreOptions.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionDropdown.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionsForm.vue

fix: do not watch object(listQueryOptions) instead, watch primitive type

---

apps/web/src/services/dashboards/shared/dashboard-widget-container/WidgetViewModeModal.vue
apps/web/src/services/dashboards/shared/dashboard-widget-container/WidgetViewModeSidebar.vue
apps/web/src/services/dashboards/widgets/_components/WidgetFrame.vue
apps/web/src/services/dashboards/widgets/asset-widgets/total-fail-findings-status/TotalFailFindingsStatusWidget.vue

fix: fix `update:widget-info` bug & fix no-data bug in TotalFailFindingsStatus widget

---

apps/web/src/services/my-page/my-account/user-account/modules/MultiFactorAuthentication.vue
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

refactor: apply changed translation

---

apps/web/src/models/export/index.ts
apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/CloudServiceDetailPage.vue
apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/ExcelExportOptionModal.vue
apps/web/src/services/asset-inventory/cloud-service/modules/CloudServiceToolbox.vue
apps/web/src/services/asset-inventory/store/cloud-service-detail-page-store.ts

feat: add file name and sheet title

---

apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionDropdown.vue
apps/web/src/services/dashboards/widgets/_configs/widget-options-schema.ts

fix: set SINGLE `selectionType` if it's inherit option

---

apps/web/src/services/dashboards/dashboard-customize/modules/dashboard-widget-add-modal/DashboardDefaultWidgetTab.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/widget-form-store.ts

fix: use mergedWidgetInfo in `returnToInitialSettings()`

---

apps/web/src/lib/variable-models/variable-model-menu-handler.ts
apps/web/src/services/dashboards/shared/dashboard-variables/DashboardVariableDropdown.vue
apps/web/src/services/dashboards/shared/dashboard-widget-container/WidgetViewModeSidebar.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionDropdown.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/widget-form-store.ts
packages/mirinae/src/hooks/context-menu-controller/context-menu-attach.ts
packages/mirinae/src/hooks/context-menu-controller/index.ts
packages/mirinae/src/inputs/context-menu/PContextMenu.vue
packages/mirinae/src/inputs/context-menu/type.ts
packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.stories.mdx
packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
packages/mirinae/src/inputs/dropdown/select-dropdown/mock.ts
packages/mirinae/src/inputs/dropdown/select-dropdown/type.ts

https://github.com/cloudforet-io/console/assets/26986739/802ecc40-bcbd-4d3a-a9e9-35888ee608e7

feat: apply updated handler spec and reset init states after update selected, skip updating if visible is false

---

apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisDataTable.vue
apps/web/src/services/dashboards/widgets/_base/base-trend/BaseTrendWidget.vue

solve [this](https://pyengine.atlassian.net/browse/QA-913)

fix: fix `widgetLocation` of BaseTrendWidget

---

apps/web/src/lib/variable-models/managed/cost-default-field-variable-model.ts
apps/web/src/services/dashboards/widgets/_configs/config.ts

fix: update cost data field's product key

---

apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionDropdown.vue

fix: show select marker on dashboard widget option dropdown

---

apps/web/src/lib/variable-models/_base/resource-name-variable-model.ts
apps/web/src/lib/variable-models/_base/resource-value-variable-model.ts
apps/web/src/lib/variable-models/_base/types.ts
apps/web/src/services/dashboards/shared/dashboard-variables/DashboardVariableDropdown.vue

feat: set `more` to response of resource variable models & fix `@click-show-more` event bug

---

apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionDropdown.vue

https://pyengine.atlassian.net/browse/QA-923

fix: fix inherit toggle bug in widget options form

---

apps/web/src/services/dashboards/shared/dashboard-variables/DashboardVariableDropdown.vue
apps/web/src/services/dashboards/shared/dashboard-variables/DashboardVariables.vue

fix: fix bug when reset dashboard variables

---

apps/web/src/services/dashboards/managed-variables-schema.ts

https://pyengine.atlassian.net/browse/QA-876

fix: enable data source/compliance framework in all dashboards

---

apps/web/src/lib/variable-models/_base/resource-name-variable-model.ts
apps/web/src/lib/variable-models/managed/cloud-service-type-variable-model.ts
apps/web/src/lib/variable-models/managed/project-variable-model.ts
apps/web/src/lib/variable-models/managed/region-variable-model.ts
apps/web/src/services/dashboards/widgets/_components/WidgetFrame.vue
apps/web/src/services/dashboards/widgets/_helpers/date-range-helper.ts
apps/web/src/services/dashboards/widgets/_hooks/use-widget/use-widget-frame.ts

fix: apply yearly granularity to date range label at WidgetFrame

---

apps/web/src/lib/site-initializer/index.ts
apps/web/src/lib/site-initializer/resource-prefetch.ts
apps/web/src/lib/variable-models/_base/resource-value-variable-model.ts
apps/web/src/lib/variable-models/_base/types.ts
apps/web/src/lib/variable-models/managed/index.ts
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionDropdown.vue

fix: prefetch some variable model resources for data cache at backend

---

apps/web/src/common/composables/amcharts5/xy-chart-helper.ts
apps/web/src/services/dashboards/widgets/_configs/view-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/monthly-cost/MonthlyCostWidget.vue

https://pyengine.atlassian.net/browse/QA-904
https://pyengine.atlassian.net/browse/QA-895

fix: show yAxis label in MonthlyCostWidget

---

apps/web/src/lib/variable-models/_base/resource-value-variable-model.ts
apps/web/src/services/dashboards/widgets/_components/WidgetDataTable.vue

fix: apply filters query to resource value variable model

---

apps/web/src/lib/variable-models/_base/enum-variable-model.ts
apps/web/src/lib/variable-models/_base/resource-name-variable-model.ts
apps/web/src/lib/variable-models/_base/resource-value-variable-model.ts
apps/web/src/lib/variable-models/managed/asset-additional-info-key-variable-model.ts
apps/web/src/lib/variable-models/managed/asset-data-key-variable-model.ts
apps/web/src/lib/variable-models/managed/cost-additional-info-key-variable-model.ts
apps/web/src/lib/variable-models/managed/cost-data-key-variable-model.ts
apps/web/src/lib/variable-models/managed/cost-product-variable-model.ts
apps/web/src/lib/variable-models/managed/cost-tag-key-variable-model.ts
apps/web/src/lib/variable-models/managed/cost-usage-type-variable-model.ts
apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisFiltersAddMoreButton.vue
apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisFiltersPopper.vue
apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisQueryFilter.vue
apps/web/src/services/dashboards/dashboard-create/modules/dashboard-templates/helper.ts
apps/web/src/services/dashboards/managed-variables-schema.ts
apps/web/src/services/dashboards/shared/dashboard-variables/DashboardVariableDropdown.vue
apps/web/src/services/dashboards/shared/dashboard-variables/DashboardVariablesMoreButton.vue
apps/web/src/services/dashboards/shared/dashboard-widget-container/WidgetViewModeSidebar.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionDropdown.vue
apps/web/src/services/dashboards/store/dashboard-detail-info.ts
packages/mirinae/src/hooks/context-menu-controller/context-menu-attach.ts
packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue

fix: apply sort to dashboard variable and fix some bugs of cost anlaysis page filters

---

apps/web/src/models/export/index.ts
apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/CloudServiceDetail.vue
apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/ExcelExportOptionModal.vue
apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/cloud-service-history-detail/CloudServiceMultipleSelectedData.vue
apps/web/src/services/asset-inventory/cloud-service/modules/CloudServiceToolbox.vue
apps/web/src/services/asset-inventory/store/cloud-service-detail-page-store.ts

If you check this PR, please review in commit order.

fix: fix QA bug of cloudServiceExcelExport 

---

apps/web/src/lib/variable-models/managed/asset-additional-info-key-variable-model.ts
apps/web/src/lib/variable-models/managed/cost-additional-info-key-variable-model.ts
apps/web/src/lib/variable-models/managed/cost-tag-key-variable-model.ts
apps/web/src/services/dashboards/dashboard-create/modules/dashboard-templates/helper.ts
apps/web/src/services/dashboards/shared/dashboard-variables/DashboardVariableDropdown.vue
apps/web/src/services/dashboards/shared/dashboard-variables/DashboardVariablesMoreButton.vue
apps/web/src/services/dashboards/store/dashboard-detail-info.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region-multi-fields/widget-config.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-summary-multi-fields/widget-config.ts

fix: delete wrong filtering in `list()` of variable models

---

packages/mirinae/src/data-display/text-list/PTextList.vue

I fixed to an operator that can check nullable.

fix(mirinae): fix display bug of PTextList

---

packages/mirinae/src/data-display/dynamic/dynamic-layout/mock.ts
packages/mirinae/src/data-display/dynamic/dynamic-layout/templates/html/index.vue

https://pyengine.atlassian.net/browse/QUEST-858

fix: fix a tag bug in dynamic layout

---

apps/web/src/lib/variable-models/_base/enum-variable-model.ts
apps/web/src/lib/variable-models/managed/asset-additional-info-key-variable-model.ts
apps/web/src/lib/variable-models/managed/asset-data-key-variable-model.ts
apps/web/src/lib/variable-models/managed/cost-additional-info-key-variable-model.ts
apps/web/src/lib/variable-models/managed/cost-data-key-variable-model.ts
apps/web/src/lib/variable-models/managed/cost-tag-key-variable-model.ts
apps/web/src/services/dashboards/widgets/_components/WidgetFrame.vue

https://pyengine.atlassian.net/browse/QA-930
https://pyengine.atlassian.net/browse/QA-931

fix: fix start/limit bug in `list()` of variable models

---

apps/web/src/lib/component-util/dynamic-layout/index.ts
apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/CloudServiceDetail.vue
apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/ExcelExportOptionModal.vue
apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/cloud-service-history-detail/CloudServiceMultipleSelectedData.vue

fix: fix QA bug of cloud service excel export

---

apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/CloudServiceDetail.vue
apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/cloud-service-history-detail/CloudServiceMultipleSelectedData.vue

fix(qa-927): apply query search composable

---

apps/web/src/lib/variable-models/_base/enum-variable-model.ts
apps/web/src/lib/variable-models/managed/asset-additional-info-key-variable-model.ts
apps/web/src/lib/variable-models/managed/asset-data-key-variable-model.ts
apps/web/src/lib/variable-models/managed/cost-additional-info-key-variable-model.ts
apps/web/src/lib/variable-models/managed/cost-data-key-variable-model.ts
apps/web/src/lib/variable-models/managed/cost-tag-key-variable-model.ts
apps/web/src/services/dashboards/widgets/_components/WidgetFrame.vue

* chore: hide date text when it's sm widget
* fix: fix start/limit bug in `list()`
---------

fix: fix start/limit bug in `list()` of variable models (#2252)

---

apps/web/src/services/dashboards/store/dashboard-detail-info.ts
apps/web/src/services/dashboards/widgets/_helpers/widget-schema-helper.ts

fix: add conversion code for widget schema properties

---

apps/web/src/common/modules/modals/multi-factor-authentication-email-modal/MultiFactorAuthenticationEmailModal.vue
apps/web/src/services/my-page/my-account/user-account/modules/MultiFactorAuthentication.vue
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

SSIA
Plz check based on the changed files

feat: create mfa modal component and apply

---

apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/CloudServiceDetailPage.vue
apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/CloudServiceDetail.vue
apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/ExcelExportOptionModal.vue
apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/cloud-service-history-detail/CloudServiceMultipleSelectedData.vue
apps/web/src/services/asset-inventory/store/cloud-service-detail-page-store.ts

fix(cloud-service): fix excel options of cloud service page

---

apps/web/src/services/asset-inventory/collector/shared/CollectorCurrentStatus.vue
apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/CollectorDataModal.vue
apps/web/src/services/dashboards/store/dashboard-detail-info.ts

fix: add conversion code for old dashboard

---

apps/web/src/services/dashboards/widgets/_components/WidgetFrame.vue

chore: show 'Real time' text in sm size widget

---

apps/web/src/common/modules/monitoring/Monitoring.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-noti/modules/GNBNotificationsTab.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-search/GNBSearch.vue
apps/web/src/services/asset-inventory/cloud-service/CloudServicePage.vue
apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/CloudServiceLogTab.vue
apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/cloud-service-usage-overview/CloudServiceUsageOverview.vue
apps/web/src/services/cost-explorer/budget/shared/BudgetProviderSelect.vue

refactor: apply `getCancellableFetcher` to pages

---

apps/web/src/common/modules/navigations/lnb/LNB.vue
apps/web/src/lib/component-util/getUUID.ts
apps/web/src/lib/helper/notice-alert-helper.ts
apps/web/src/lib/random-id-generator.ts
apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/cloud-service-usage-overview/CloudServiceUsageOverviewSummary.vue
apps/web/src/services/cost-explorer/budget/budget-detail/modules/budget-notifications/BudgetNotifications.vue
apps/web/src/services/dashboards/dashboard-create/modules/dashboard-templates/config.ts
apps/web/src/services/dashboards/dashboard-create/modules/dashboard-templates/helper.ts
apps/web/src/services/dashboards/dashboard-customize/modules/dashboard-manage-variable-overlay/DashboardManageVariableForm.vue
apps/web/src/services/dashboards/dashboard-customize/modules/dashboard-manage-variable-overlay/DashboardManageVariableOptionsField.vue
apps/web/src/services/dashboards/dashboard-customize/modules/dashboard-manage-variable-overlay/DashboardManageVariableOverlay.vue
apps/web/src/services/dashboards/dashboard-customize/modules/dashboard-widget-add-modal/DashboardWidgetAddModal.vue
apps/web/src/services/dashboards/shared/dashboard-widget-container/WidgetViewModeSidebar.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionDropdown.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionsForm.vue
apps/web/src/services/dashboards/store/dashboard-detail-info.ts
apps/web/src/services/dashboards/widgets/_components/WidgetFrame.vue

SSIA
https://github.com/cloudforet-io/console/security/code-scanning/29

feat: create getRandomId function

---

apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/CloudServiceDetail.vue

fix: fix excel file name

---

apps/web/src/services/auth/route-config.ts
apps/web/src/services/auth/routes.ts
apps/web/src/services/auth/sign-in/DomainAdminSignInPage.vue
apps/web/src/services/auth/sign-in/MultiFactorAuthenticationPage.vue
apps/web/src/services/auth/sign-in/SignInPage.vue
apps/web/src/services/auth/sign-in/modules/SignInContainer.vue

refactor: separate 'sign-in' container for page branching and remove unnecessary code

---

apps/web/src/services/dashboards/dashboard-create/modules/dashboard-templates/templates/cdn-and-traffic-cost.ts
apps/web/src/services/dashboards/store/dashboard-detail-info.ts

https://pyengine.atlassian.net/browse/QUEST-878

fix: fix filter bug in cdn dashboard template & delete conversion code for old dashboard

---

apps/web/src/services/project/modules/ProjectCardList.vue
apps/web/src/services/project/pages/ProjectDetailPage.vue
apps/web/src/services/project/pages/ProjectMaintenanceWindowPage.vue
apps/web/src/services/project/project-detail/modules/MaintenanceHappeningList.vue
apps/web/src/services/project/project-detail/modules/MaintenanceWindowFormModal.vue
apps/web/src/services/project/project-detail/modules/ProjectFormModal.vue
apps/web/src/services/project/project-detail/project-alert/project-alert-event-rule/modules/EventRuleConditionForm.vue
apps/web/src/services/project/project-detail/project-alert/project-alert-settings/modules/ProjectAutoRecoveryUpdateModal.vue
apps/web/src/services/project/project-detail/project-alert/project-maintenance-window/lib/config.ts
apps/web/src/services/project/types/type.ts

refactor: use setup script in project

---

apps/web/src/services/auth/sign-in/DomainAdminSignInPage.vue
apps/web/src/services/auth/sign-in/MultiFactorAuthenticationPage.vue
apps/web/src/services/auth/sign-in/SignInPage.vue
apps/web/src/services/auth/sign-in/modules/SignInContainer.vue

refactor: utilizing components based on route name

---

apps/web/src/schema/monitoring/alert/constants.ts
apps/web/src/schema/monitoring/alert/model.ts
apps/web/src/services/alert-manager/components/AlertDashboardAlertStateWidget.vue
apps/web/src/services/alert-manager/components/AlertDashboardProjectSearchWidgetAlertList.vue
apps/web/src/services/alert-manager/components/AlertDetailInfoTable.vue
apps/web/src/services/alert-manager/components/AlertDetailResponder.vue
apps/web/src/services/alert-manager/components/AlertDetailSummary.vue
apps/web/src/services/alert-manager/components/AlertListItem.vue
apps/web/src/services/alert-manager/components/AlertMainAcknowledgeModal.vue
apps/web/src/services/alert-manager/components/AlertMainAlertCreateModal.vue
apps/web/src/services/alert-manager/components/AlertMainDataTable.vue
apps/web/src/services/alert-manager/components/AlertMainDataTableActions.vue
apps/web/src/services/alert-manager/components/AlertMainDataTableBottomFilters.vue
apps/web/src/services/alert-manager/components/AlertMainNewAssignedAlertListCard.vue
apps/web/src/services/alert-manager/components/AlertMainResolveModal.vue
apps/web/src/services/alert-manager/components/EscalationPolicyDataTable.vue
apps/web/src/services/alert-manager/composables/alert-info.ts
apps/web/src/services/alert-manager/composables/alert-state-i18n.ts
apps/web/src/services/alert-manager/composables/alert-urgency-i18n.ts
apps/web/src/services/alert-manager/constants/alert-constant.ts
apps/web/src/services/alert-manager/helpers/alert-badge-helper.ts
apps/web/src/services/alert-manager/pages/AlertPage.vue
apps/web/src/services/alert-manager/stores/alert-page-store.ts
apps/web/src/services/alert-manager/stores/escalation-policy-form.ts
apps/web/src/services/alert-manager/types/alert-type.ts
apps/web/src/services/project/components/ProjectSummaryAlertWidget.vue
apps/web/src/services/project/pages/ProjectAlertListPage.vue
apps/web/src/services/project/pages/ProjectDetailPage.vue
apps/web/src/services/project/stores/project-detail-page-store.ts

refactor: move the type, constant, and model to their locations

---

apps/web/src/services/dashboards/components/DashboardWidgetOptionDropdown.vue

chore: import constant

---

apps/web/src/common/modules/modals/multi-factor-authentication-modal/MultiFactorAuthenticationEmailModal.vue
apps/web/src/lib/helper/multi-factor-authentication-helper.ts
apps/web/src/services/my-page/my-account/user-account/modules/MultiFactorAuthentication.vue

- Delete Functionality Related to Email Change
- Display Modal Only on API Success (`identity/user/enable-mfa`)

refactor: refactor minor changed

---

apps/web/src/services/auth/authenticator/index.ts
apps/web/src/services/auth/sign-in/MultiFactorAuthenticationPage.vue
apps/web/src/services/auth/sign-in/local/authenticator/space-auth.ts
apps/web/src/services/auth/sign-in/local/template/ID_PW.vue
apps/web/src/store/modules/user/actions.ts
apps/web/src/store/modules/user/type.ts

feat: changed the api to token-issue when the confirm button click

---

apps/web/src/lib/variable-models/managed/cost-default-field-variable-model.ts
apps/web/src/schema/dashboard/_constants/widget-constant.ts

fix: fix key of `cost_usage_type`

---

apps/web/src/schema/_common/model.ts
apps/web/src/schema/cost-analysis/budget-usage/model.ts
apps/web/src/schema/identity/project/model.ts

chore: update minor things in schema models

---

packages/mirinae/src/data-display/text-list/PTextList.vue

fix(p-text-list): fix nullish coalescing operator parsing bug

---

apps/web/src/common/modules/page-layouts/CenteredPageLayout.vue
apps/web/src/common/pages/ErrorPage.vue
apps/web/src/lib/access-control/redirect-route-helper.ts
apps/web/src/lib/site-initializer/index.ts
apps/web/src/router/constant.ts
apps/web/src/router/error-routes.ts
apps/web/src/router/index.ts
apps/web/src/router/service-routes.ts
apps/web/src/services/auth/pages/PasswordPage.vue

If the domain name does not exist, the router does not have any routes except for the errorPage.
So, I removed routing buttons if the domain name does not exist.

fix(error-page): remove button section if domain name is undefined

---

apps/web/src/services/dashboards/components/DashboardManageVariableForm.vue
apps/web/src/services/dashboards/widgets/_helpers/widget-validation-helper.ts

fix: enable manage variable overlay at dashboard

---

apps/web/src/services/cost-explorer/components/BudgetCreateFormAmountPlanLastMonthsCost.vue
apps/web/src/services/cost-explorer/components/CostAnalysisChart.vue
apps/web/src/services/cost-explorer/components/CostAnalysisDataTable.vue
apps/web/src/services/cost-explorer/components/CostAnalysisDataTableDataTypeDropdown.vue
apps/web/src/services/cost-explorer/constants/cost-explorer-constant.ts
apps/web/src/services/cost-explorer/helpers/cost-explorer-chart-data-helper.ts
apps/web/src/services/cost-explorer/types/cost-explorer-query-type.ts
apps/web/src/services/dashboards/widgets/_helpers/widget-chart-data-helper.ts
apps/web/src/services/dashboards/widgets/_helpers/widget-chart-helper.ts
apps/web/src/services/dashboards/widgets/_helpers/widget-table-helper.ts
apps/web/src/services/dashboards/widgets/base-widgets/base-pie/BasePieWidget.vue
apps/web/src/services/dashboards/widgets/base-widgets/base-trend/BaseTrendWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region/CostByRegionWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region/cost-by-region-data-hleper.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-map/CostMapWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/cost-map/costmap-chart-data-helper.ts
apps/web/src/services/dashboards/widgets/cost-widgets/monthly-cost/MonthlyCostWidget.vue
apps/web/src/services/project/components/ProjectSummaryBillingWidget.vue

just change typo and remove unused function

refactor: change analyze api request from `cost_sum` to `value_sum` & generalize the displayed data type in cost analysis

---

apps/web/src/services/dashboards/widgets/_helpers/__tests__/widget-chart-data-helper.test.ts

chore: edit variable in test file

---

apps/web/src/router/index.ts
apps/web/src/store/modules/display/getters.ts
apps/web/src/store/modules/user/getters.ts

fix: add empty role bypass code

---

apps/web/src/services/asset-inventory/components/CloudServiceListCard.vue
apps/web/src/services/dashboards/components/DashboardVariableDropdown.vue
apps/web/src/services/dashboards/widgets/_composables/use-widget/use-widget-console-filters.ts
apps/web/src/services/dashboards/widgets/_composables/use-widget/use-widget-location.ts
packages/mirinae/src/navigation/pagination/text-pagination/PTextPagination.vue

fix(dashboard): automatically set first variable if data does not exist in the list

---

apps/web/src/services/asset-inventory/components/CloudServiceListCard.vue

fix: set icon with compound key at cloud service list card

---

.github/workflows/dispatch_mirinae_release.yaml

fix(mirinae-release): remove turbo services

---

apps/web/src/common/modules/modals/multi-factor-authentication-modal/MultiFactorAuthenticationEmailModal.vue
apps/web/src/common/modules/modals/multi-factor-authentication-modal/modules/CollapsibleContents.vue
apps/web/src/common/modules/modals/multi-factor-authentication-modal/modules/EmailInfo.vue
apps/web/src/services/my-page/my-account/user-account/modules/MultiFactorAuthentication.vue
apps/web/src/store/modules/user/actions.ts
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

refactor: componentization for modal utilization and add translation

---

apps/web/src/common/modules/modals/multi-factor-authentication-modal/MultiFactorAuthenticationEmailModal.vue
apps/web/src/common/modules/modals/multi-factor-authentication-modal/MultiFactorAuthenticationModal.vue
apps/web/src/common/modules/modals/multi-factor-authentication-modal/modules/CollapsibleContent.vue
apps/web/src/common/modules/modals/multi-factor-authentication-modal/modules/CollapsibleContents.vue
apps/web/src/common/modules/modals/multi-factor-authentication-modal/modules/EmailInfo.vue
apps/web/src/common/modules/modals/multi-factor-authentication-modal/modules/EmailInfoContent.vue
apps/web/src/lib/helper/multi-factor-authentication-helper.ts
apps/web/src/services/my-page/my-account/user-account/modules/MultiFactorAuthentication.vue

feat: apply mfa change modal

---

apps/web/src/common/modules/project/ProjectSelectDropdown.vue
apps/web/src/schema/_common/model.ts
apps/web/src/schema/identity/project-group/model.ts
apps/web/src/schema/identity/project/model.ts
apps/web/src/services/project/components/ProjectMainProjectTree.vue
apps/web/src/services/project/composables/use-project-tree.ts
apps/web/src/services/project/stores/project-page-store.ts
apps/web/src/services/project/types/project-tree-type.ts

feat: apply v2 api to project tree & use local hook instead of project/tree api 

---

apps/web/src/common/modules/modals/multi-factor-authentication-modal/MultiFactorAuthenticationModal.vue
apps/web/src/common/modules/modals/multi-factor-authentication-modal/modules/EmailInfoContent.vue
apps/web/src/lib/helper/multi-factor-authentication-helper.ts

feat: create an input form modal for email change

---

apps/web/src/services/administration/iam/user/lib/config.ts
apps/web/src/services/administration/iam/user/lib/helper.ts
apps/web/src/services/administration/iam/user/modules/UserManagementTable.vue
apps/web/src/services/administration/iam/user/modules/user-management-tab/UserDetail.vue
apps/web/src/services/administration/iam/user/type.ts
apps/web/src/services/administration/store/user-page-store.ts
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: add mfa state to the administration main page

---

apps/web/src/common/modules/modals/multi-factor-authentication-modal/modules/CollapsibleContent.vue
apps/web/src/common/modules/modals/multi-factor-authentication-modal/modules/EmailInfoContent.vue
apps/web/src/lib/helper/multi-factor-authentication-helper.ts
apps/web/src/services/administration/iam/user/modules/user-management-modal/UserManagementModal.vue
apps/web/src/services/administration/iam/user/modules/user-management-modal/modules/MultiFactorAuth.vue
apps/web/src/services/administration/iam/user/type.ts
apps/web/src/store/modules/user/type.ts
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: apply mfa state at update modal

---

apps/web/src/services/asset-inventory/components/CloudServiceToolbox.vue
apps/web/src/services/asset-inventory/pages/CloudServicePage.vue
packages/mirinae/src/data-display/dynamic/dynamic-layout/type/layout-schema.ts
packages/mirinae/src/feedbacks/modals/button-modal/story-helper.ts
packages/mirinae/src/inputs/text-editor/PTextEditor.vue

fix: do not skip update pagination in cloud service toolbox and make apply style immediately on PTextEditor

---

apps/web/src/schema/identity/project/api-verbs/add-user-groups.ts
apps/web/src/schema/identity/project/api-verbs/add-users.ts
apps/web/src/schema/identity/project/api-verbs/change-project-group.ts
apps/web/src/schema/identity/project/api-verbs/create.ts
apps/web/src/schema/identity/project/api-verbs/delete.ts
apps/web/src/schema/identity/project/api-verbs/get.ts
apps/web/src/schema/identity/project/api-verbs/list.ts
apps/web/src/schema/identity/project/api-verbs/remove-user-groups.ts
apps/web/src/schema/identity/project/api-verbs/remove-users.ts
apps/web/src/schema/identity/project/api-verbs/udpate.ts
apps/web/src/schema/identity/project/api-verbs/update-project-type.ts
apps/web/src/schema/identity/project/model.ts
apps/web/src/schema/identity/project/type.ts

feat: update project api-verbs

---

apps/web/src/services/project/components/ProjectMemberAddModal.vue
apps/web/src/services/project/components/ProjectMemberTab.vue
apps/web/src/services/project/components/ProjectMemberUpdateModal.vue
apps/web/src/services/project/pages/ProjectPage.vue

project group member is deleted!

feat: deleted code related to project group members

---

packages/mirinae/src/data-display/dynamic/dynamic-layout/templates/raw/index.vue

fix(mirinae): do not make data from root_path as array at raw type of  dynamic layout

---

apps/web/src/schema/identity/project/api-verbs/add-user-groups.ts
apps/web/src/schema/identity/project/api-verbs/add-users.ts
apps/web/src/schema/identity/project/api-verbs/change-project-group.ts
apps/web/src/schema/identity/project/api-verbs/create.ts
apps/web/src/schema/identity/project/api-verbs/delete.ts
apps/web/src/schema/identity/project/api-verbs/get.ts
apps/web/src/schema/identity/project/api-verbs/list.ts
apps/web/src/schema/identity/project/api-verbs/remove-user-groups.ts
apps/web/src/schema/identity/project/api-verbs/remove-users.ts
apps/web/src/schema/identity/project/api-verbs/udpate.ts
apps/web/src/schema/identity/project/api-verbs/update-project-type.ts
apps/web/src/services/alert-manager/components/AlertDetailSummaryAssignModal.vue
apps/web/src/services/asset-inventory/components/CloudServiceAdmin.vue
apps/web/src/services/my-page/components/NotificationAddMemberGroup.vue
apps/web/src/services/project/components/ProjectMemberInviteModal.vue
apps/web/src/services/project/components/ProjectMemberTab.vue

feat: change from 'project/member' v1 api to v2

---

apps/web/src/lib/access-control/page-permission-helper.ts
apps/web/src/lib/helper/file-download-helper/type.ts
apps/web/src/schema/identity/service-account/model.ts
apps/web/src/schema/identity/service-account/type.ts
apps/web/src/services/asset-inventory/components/ServiceAccountAccountType.vue
apps/web/src/services/asset-inventory/components/ServiceAccountBadge.vue
apps/web/src/services/asset-inventory/components/ServiceAccountBaseInformation.vue
apps/web/src/services/asset-inventory/components/ServiceAccountCredentials.vue
apps/web/src/services/asset-inventory/components/ServiceAccountCredentialsForm.vue
apps/web/src/services/asset-inventory/components/ServiceAccountProject.vue
apps/web/src/services/asset-inventory/components/ServiceAccountProjectDetail.vue
apps/web/src/services/asset-inventory/pages/ServiceAccountAddPage.vue
apps/web/src/services/asset-inventory/pages/ServiceAccountDetailPage.vue
apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue
apps/web/src/store/modules/reference/project-group/actions.ts
apps/web/src/store/modules/reference/project/actions.ts
apps/web/src/store/modules/reference/provider/actions.ts
apps/web/src/store/modules/reference/service-account/actions.ts

refactor(service-account): apply v2 api & update UI for identity v2

---

apps/web/src/schema/identity/service-account/api-verbs/list.ts
apps/web/src/schema/identity/service-account/type.ts
apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue
apps/web/src/services/my-page/components/UserAPIKeyGRPCEndpointsTab.vue
apps/web/src/services/my-page/components/UserAPIKeyTable.vue

feat: apply api-v2 to endpoint.list

---

apps/web/src/schema/identity/project-group/api-verbs/change-parent-group.ts
apps/web/src/schema/identity/project-group/api-verbs/create.ts
apps/web/src/schema/identity/project-group/api-verbs/delete.ts
apps/web/src/schema/identity/project-group/api-verbs/get.ts
apps/web/src/schema/identity/project-group/api-verbs/list.ts
apps/web/src/schema/identity/project-group/api-verbs/update.ts

feat: add project group api-verbs

---

apps/web/vite.config.js

fix: add utils alias to web app

---

apps/web/src/common/composables/amcharts5/xy-chart-helper.ts
apps/web/src/services/cost-explorer/components/CostAnalysisStackedColumnChart.vue

fix: check the value is 0 before division

---

apps/web/src/common/composables/breadcrumbs/index.ts
apps/web/src/lib/menu/config.ts
apps/web/src/services/asset-inventory/pages/ServiceAccountAddPage.vue
apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue
apps/web/src/services/asset-inventory/routes/routes.ts
apps/web/src/shims-vue-router.d.ts
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: update service account UI according to identity v2 & add new option to breadcrumbs

---

apps/web/src/common/modules/modals/multi-factor-auth-modal/modules/EmailInfoContent.vue
apps/web/src/lib/helper/multi-factor-auth-helper.ts
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

refactor: changing text based on modal type

---

apps/web/src/services/asset-inventory/components/ServiceAccountBaseInformationForm.vue
apps/web/src/services/asset-inventory/pages/ServiceAccountAddPage.vue
apps/web/src/services/asset-inventory/types/service-account-page-type.ts

I modified only the UI that have changed.
The`ServiceAccountBaseInfomation` component is used on both the update and add pages.
This PR only contains changes for the add page. In the next PR, I'll improve the code to consider updates as well.
As I've changed it to a setup script, please read the commits in order!
As is
To be

fix: include projectForm in baseInfoForm

---

apps/web/src/services/project/composables/use-project-tree.ts
apps/web/src/store/modules/reference/project-group/actions.ts
apps/web/src/store/modules/reference/project/actions.ts
apps/web/src/store/modules/reference/project/type.ts

feat: apply v2 response to project, project group store

---

apps/web/src/schema/identity/domain/api-verbs/get-auth-info.ts
apps/web/src/store/modules/domain/actions.ts

fix: use get-auth-info api for domain check

---

packages/core-lib/src/space-connector/index.ts

fix(core-lib): execute in mock mode only mock config is enabled

---

apps/web/src/services/administration/components/RoleCreateEditHandbook.vue
apps/web/src/services/administration/components/RoleDeleteModal.vue
apps/web/src/services/administration/components/RoleManagementTab.vue
apps/web/src/services/administration/components/RoleManagementTabDetail.vue
apps/web/src/services/administration/components/RoleManagementTable.vue
apps/web/src/services/administration/components/RoleUpdateForm.vue
apps/web/src/services/administration/components/RoleUpdatePageAccessForm.vue
apps/web/src/services/administration/components/RoleUpdatePageAccessMenuItem.vue
apps/web/src/services/administration/components/RoleUpdatePageBaseInformation.vue
apps/web/src/services/administration/helpers/role-page-permission-helpert.ts
apps/web/src/services/administration/pages/RoleCreatePage.vue
apps/web/src/services/administration/pages/RolePage.vue
apps/web/src/services/administration/pages/RoleUpdatePage.vue

refactor: changing the template structure

---

apps/web/src/schema/identity/role-binding/api-verbs/create.ts
apps/web/src/schema/identity/role-binding/api-verbs/delete.ts
apps/web/src/schema/identity/role-binding/api-verbs/list.ts
apps/web/src/schema/identity/role-binding/model.ts
apps/web/src/schema/identity/role-binding/type.ts
apps/web/src/schema/identity/user/api-verbs/create-workspace-user.ts
apps/web/src/schema/identity/user/api-verbs/create.ts
apps/web/src/schema/identity/user/api-verbs/delete.ts
apps/web/src/schema/identity/user/api-verbs/disable.ts
apps/web/src/schema/identity/user/api-verbs/enable.ts
apps/web/src/schema/identity/user/api-verbs/get.ts
apps/web/src/schema/identity/user/api-verbs/list-summary.ts
apps/web/src/schema/identity/user/api-verbs/list.ts
apps/web/src/schema/identity/user/api-verbs/set-required-actions.ts
apps/web/src/schema/identity/user/api-verbs/update.ts
apps/web/src/schema/identity/user/model.ts
apps/web/src/services/administration/components/UserManagementFormModal.vue
apps/web/src/services/administration/components/UserManagementStatusModal.vue
apps/web/src/services/administration/components/UserManagementTabAssignedRole.vue
apps/web/src/services/administration/components/UserManagementTabDetail.vue
apps/web/src/services/administration/components/UserManagementTable.vue
apps/web/src/services/administration/helpers/user-management-form-validations.ts
apps/web/src/services/administration/store/user-page-store.ts
apps/web/src/services/alert-manager/components/AlertDetailResponder.vue
apps/web/src/services/project/components/ProjectFormModal.vue
apps/web/src/services/project/components/ProjectMainCardList.vue
apps/web/src/services/project/composables/use-project-tree.ts
apps/web/src/services/project/pages/ProjectDetailPage.vue
apps/web/src/store/modules/reference/project/actions.ts

Please...see...order...by...commits....

feat: change user api from v1 to v2

---

apps/web/src/common/composables/query-tags/index.ts
apps/web/src/services/asset-inventory/components/CloudServiceDetailExcelExportOptionModal.vue
apps/web/src/services/asset-inventory/pages/CloudServiceDetailPage.vue
apps/web/src/services/asset-inventory/stores/cloud-service-detail-page-store.ts

fix(cloud-service-detail): add search filters to excel download options

---

apps/web/src/schema/identity/role/api-verbs/create.ts
apps/web/src/services/administration/components/RoleManagementTabDetail.vue
apps/web/src/services/administration/components/RoleUpdateForm.vue
apps/web/src/services/administration/pages/RoleCreatePage.vue
apps/web/src/services/administration/store/role-page-store.ts

feat: change api from v1 to v2 at role create page

---

apps/web/src/services/administration/store/role-page-store.ts
apps/web/src/services/asset-inventory/components/ServiceAccountAttachedGeneralAccounts.vue
apps/web/src/services/asset-inventory/components/ServiceAccountBaseInformationForm.vue
apps/web/src/services/project/components/ProjectMainProjectGroupFormModal.vue
apps/web/src/services/project/components/ProjectMemberInviteModal.vue
apps/web/src/services/project/stores/project-page-store.ts
apps/web/src/store/modules/reference/project-group/actions.ts
apps/web/src/store/modules/user/actions.ts
packages/core-lib/src/space-connector/index.ts

refactor: update type and move list response type usage

---

apps/web/src/lib/access-control/redirect-route-helper.ts
apps/web/src/services/alert-manager/AlertManagerLNB.vue

SSIA 🙏
**You can merge it right after the review..**

fix(route-redirect): fix missed menu-id issues

---

apps/web/src/schema/identity/role-binding/api-verbs/create.ts
apps/web/src/schema/identity/role-binding/api-verbs/delete.ts
apps/web/src/schema/identity/role-binding/api-verbs/list.ts
apps/web/src/services/administration/components/UserManagementTable.vue
apps/web/src/services/administration/constants/user-table-constant.ts
apps/web/src/services/administration/store/user-page-store.ts

refactor: refactor administration user page

---

apps/web/src/services/home-dashboard/components/AllSummary.vue
apps/web/src/services/project/components/ProjectAlertSettingsEscalationPolicy.vue
apps/web/src/services/project/components/ProjectAlertSettingsEscalationPolicyChangeModal.vue
apps/web/src/services/project/components/ProjectAlertSettingsNotificationPolicyUpdateModal.vue
apps/web/src/services/project/components/ProjectAlertWebhookAddModal.vue
apps/web/src/services/project/components/ProjectAlertWebhookUpdateModal.vue
apps/web/src/services/project/components/ProjectFormModal.vue
apps/web/src/services/project/components/ProjectSummaryAlertWidget.vue
apps/web/src/services/project/components/ProjectSummaryAllSummaryWidget.vue
apps/web/src/services/project/components/ProjectSummaryPersonalHealthDashboardWidget.vue
apps/web/src/services/project/components/ProjectSummaryServiceAccountsWidget.vue
apps/web/src/services/project/components/ProjectSummaryTrustedAdvisorWidget.vue
apps/web/src/services/project/pages/ProjectDetailPage.vue
packages/mirinae/src/navigation/breadcrumbs/PBreadcrumbs.vue
packages/mirinae/src/navigation/breadcrumbs/type.ts

refactor: refactor and fix minor things in project service

---

apps/web/src/services/home-dashboard/components/AllSummary.vue
apps/web/src/services/project/components/ProjectAlertSettingsEscalationPolicy.vue
apps/web/src/services/project/components/ProjectAlertSettingsEscalationPolicyChangeModal.vue
apps/web/src/services/project/components/ProjectAlertSettingsNotificationPolicyUpdateModal.vue
apps/web/src/services/project/components/ProjectAlertWebhookAddModal.vue
apps/web/src/services/project/components/ProjectAlertWebhookUpdateModal.vue
apps/web/src/services/project/components/ProjectFormModal.vue
apps/web/src/services/project/components/ProjectSummaryAlertWidget.vue
apps/web/src/services/project/components/ProjectSummaryAllSummaryWidget.vue
apps/web/src/services/project/components/ProjectSummaryPersonalHealthDashboardWidget.vue
apps/web/src/services/project/components/ProjectSummaryServiceAccountsWidget.vue
apps/web/src/services/project/components/ProjectSummaryTrustedAdvisorWidget.vue
apps/web/src/services/project/pages/ProjectDetailPage.vue
packages/mirinae/src/navigation/breadcrumbs/PBreadcrumbs.vue
packages/mirinae/src/navigation/breadcrumbs/type.ts

refactor: use setup script & fix minor bugs

---

apps/web/src/services/auth/authenticator/index.ts
apps/web/src/services/auth/authenticator/local/authenticator/space-auth.ts
apps/web/src/services/auth/authenticator/local/template/ID_PW.vue
apps/web/src/services/auth/components/SignInContainer.vue
apps/web/src/services/auth/components/SignInLeftContainer.vue
apps/web/src/services/auth/pages/MultiFactorAuthPage.vue

feat: apply mfa at sign-in process

---

apps/web/src/common/modules/navigations/gnb/modules/gnb-noti/GNBNoti.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-noti/modules/GNBNotiItem.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-noti/modules/GNBNoticeTab.vue
apps/web/src/common/modules/popup/notice/NoticePopup.vue
apps/web/src/common/modules/popup/notice/modules/NoticePopupItem.vue
apps/web/src/schema/board/post/api-verbs/get.ts
apps/web/src/schema/board/post/api-verbs/list.ts
apps/web/src/schema/board/post/model.ts
apps/web/src/services/info/components/NoticeForm.vue
apps/web/src/services/info/components/NoticeList.vue
apps/web/src/services/info/pages/NoticeDetailPage.vue
apps/web/src/services/info/pages/NoticeUpdatePage.vue
apps/web/src/store/notice/index.ts

This PR includes many refactoring.

fix: change board notice apis to v2

---

apps/web/src/store/modules/reference/actions.ts
apps/web/src/store/reference/all-reference-store.ts
apps/web/src/store/reference/project-store.ts

refactor: use pinia for project reference store

---

apps/web/src/services/project/components/ProjectMainCardList.vue
apps/web/src/services/project/components/ProjectMainProjectCreateModal.vue
apps/web/src/services/project/components/ProjectMainProjectGroupDeleteCheckModal.vue
apps/web/src/services/project/components/ProjectMainProjectGroupFormModal.vue
apps/web/src/services/project/components/ProjectMainProjectTree.vue
apps/web/src/services/project/components/ProjectUpdateModal.vue
apps/web/src/services/project/pages/ProjectDetailPage.vue
apps/web/src/services/project/pages/ProjectPage.vue
apps/web/src/services/project/stores/project-page-store.ts

refactor: change `projectPageStore` from option to setup store

---

apps/web/src/router/index.ts
apps/web/src/store/modules/user/actions.ts
apps/web/src/store/modules/user/mutations.ts

fix: fix typo and add roleType in user mutation

---

apps/web/src/services/administration/routes/admin/routes.ts

fix(administration): fix redirect issue

---

apps/web/src/schema/identity/workspace-user/api-verbs/get.ts
apps/web/src/schema/identity/workspace-user/model.ts
apps/web/src/services/project/components/ProjectMemberTab.vue
apps/web/src/services/project/helpers/workspace-user-helper.ts
apps/web/src/services/project/pages/ProjectDetailPage.vue
apps/web/src/services/project/stores/project-page-store.ts

feat: update WorkspaceUserModel & apply permission to project page

---

apps/web/src/services/project/components/ProjectFormModal.vue
apps/web/src/services/project/components/ProjectMainCardList.vue
apps/web/src/services/project/components/ProjectMainProjectTree.vue
apps/web/src/services/project/components/ProjectMemberTab.vue
apps/web/src/services/project/pages/ProjectAlertListPage.vue
apps/web/src/services/project/pages/ProjectAlertPage.vue
apps/web/src/services/project/pages/ProjectAlertSettingsPage.vue
apps/web/src/services/project/pages/ProjectDetailPage.vue
apps/web/src/services/project/pages/ProjectMaintenanceWindowPage.vue
apps/web/src/services/project/pages/ProjectMemberPage.vue
apps/web/src/services/project/pages/ProjectNotificationPage.vue
apps/web/src/services/project/pages/ProjectPage.vue
apps/web/src/services/project/pages/ProjectTagPage.vue
apps/web/src/services/project/pages/ProjectWebhookPage.vue
apps/web/src/services/project/stores/project-page-store.ts

feat: use `role_type` instead of `pagePermission` on the project page

---

apps/web/src/services/project/components/ProjectMemberTab.vue
apps/web/src/services/project/pages/ProjectDetailPage.vue
apps/web/src/services/project/stores/project-detail-page-store.ts
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: add description to project member tab

---

apps/web/src/services/project/components/ProjectMainProjectTree.vue
apps/web/src/services/project/components/ProjectMemberTab.vue

SSIA!!
```
PUBLIC project: show workspace users
PRIVATE project: show project members
```

feat: get workspace user list when its public project

---

apps/web/src/common/modules/project/ProjectSelectDropdown.vue
apps/web/src/services/cost-explorer/components/BudgetCreateFormBaseInfo.vue
apps/web/src/services/cost-explorer/components/BudgetCreateTargetSelect.vue
apps/web/src/services/cost-explorer/constants/cost-explorer-constant.ts

feat: delete project group from cost explorer 

---

apps/web/src/services/project/components/ProjectMainProjectTree.vue

feat: hide edit, delete button from project tree

---

apps/web/src/services/dashboards/DashboardsLNB.vue
apps/web/src/services/dashboards/components/DashboardMainSelectFilter.vue
apps/web/src/services/dashboards/components/DashboardScopeForm.vue
apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
apps/web/src/services/dashboards/routes/admin/routes.ts
apps/web/src/services/dashboards/routes/routes.ts
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

chore(dashboard): change word from 'Entire Workspace' to 'Workspace' 

---

apps/web/src/services/administration/components/UserManagementAddRole.vue
apps/web/src/services/administration/store/user-modal-setting-store.ts
apps/web/src/services/asset-inventory/components/CollectorFormAttachedServiceAccount.vue
packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
packages/mirinae/src/inputs/dropdown/select-dropdown/story-helper.ts

I re-submitted the '[PR](https://github.com/cloudforet-io/console/pull/2425)' with the same content as the previous one for GPG key authentication!

feat: apply role type icon and menu handler

---

apps/web/src/services/project/components/ProjectMainCardList.vue

feat: apply api to project card

---

apps/web/src/schema/identity/role/constant.ts
apps/web/src/services/auth/helpers/default-route-helper.ts
apps/web/src/store/modules/user/actions.ts

SSIA
Create page-permissions generation helper for manged role.

fix(role): apply new managed role in user action

---

apps/web/src/services/administration/components/UserManagementAddRole.vue
apps/web/src/services/administration/components/UserManagementAddUser.vue
apps/web/src/services/administration/store/user-modal-setting-store.ts
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: apply user list detail

---

apps/web/src/common/modules/navigations/gnb/modules/gnb-menu/modules/dashboard-recent-favorite/modules/GNBDashboardMenu.vue
apps/web/src/router/index.ts
apps/web/src/store/modules/display/getters.ts

SSIA
You don't need to inject admin-route name directly!
Just use general route name in both admin and workspace!
SpaceRoute will handle your routeName!

fix(router): add admin to admin handing case

---

apps/web/src/schema/identity/api-key/api-verbs/list.ts
apps/web/src/schema/identity/api-key/model.ts
apps/web/src/services/my-page/components/UserAPIKeyTable.vue
apps/web/src/store/app-context/workspace/workspace-store.ts
package-lock.json

feat: add domain_id to space connector globally by the time backend is ready

---

apps/web/src/lib/menu/menu-info.ts
apps/web/src/services/auth/authenticator/index.ts
apps/web/src/store/app-context/workspace/workspace-store.ts
apps/web/src/store/modules/display/getters.ts

SSIA
Refactoring usage of workspaceId

fix(gnb-menu): fix gnb menu invisible issue

---

apps/web/src/lib/menu/config.ts
apps/web/src/lib/menu/menu-architecture.ts
apps/web/src/lib/menu/menu-info.ts
apps/web/src/lib/reference/referenceRouter.ts
apps/web/src/services/asset-inventory/AssetInventoryLNB.vue
apps/web/src/services/asset-inventory/routes/admin/routes.ts
apps/web/src/services/asset-inventory/routes/route-constant.ts
apps/web/src/services/asset-inventory/routes/routes.ts

SSIA
Already done....merge mistake

fix: rollback the server menu of asset inventory

---

apps/web/src/services/alert-manager/components/AlertDetailInfoTableDescription.vue
apps/web/src/services/alert-manager/components/AlertDetailSummary.vue
apps/web/src/services/alert-manager/components/AlertDetailTabsDetails.vue
apps/web/src/services/alert-manager/components/AlertDetailTabsPushedEventVerticalTimeline.vue
apps/web/src/services/alert-manager/pages/AlertDetailPage.vue
packages/mirinae/src/data-display/tables/definition-table/PDefinitionTable.vue
packages/mirinae/src/data-display/tables/definition-table/definition/PDefinition.vue
packages/mirinae/src/data-display/tables/definition-table/definition/type.ts

fix: apply collapsible panel to alert description and fix css bugs in alert detail page

---

apps/web/src/services/alert-manager/components/AlertDetailTabsPushedEventVerticalTimeline.vue

fix: apply collapsible panel to history in alert detail

---

apps/web/src/common/modules/project/ProjectSelectDropdown.vue
apps/web/src/services/project/components/ProjectMainProjectGroupMoveModal.vue
apps/web/src/services/project/composables/use-project-tree.ts
apps/web/src/services/project/pages/ProjectPage.vue
apps/web/src/services/project/types/project-tree-type.ts
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: add project group move modal & update ProjectSelectDropdown

---

apps/web/src/services/administration/AdministrationLNB.vue
apps/web/src/services/asset-inventory/AssetInventoryLNB.vue
apps/web/src/services/dashboards/DashboardsLNB.vue
apps/web/src/store/app-context/app-context-store.ts

SSIA
- Dashboards
- Asset-Inventory
- Administration

refactor(lnb): refactor LNB & apply admin routes

---

apps/web/src/schema/identity/role-binding/api-verbs/create.ts
apps/web/src/schema/identity/user/api-verbs/get.ts
apps/web/src/schema/identity/user/api-verbs/list.ts
apps/web/src/schema/identity/workspace-user/api-verbs/create.ts
apps/web/src/schema/identity/workspace-user/api-verbs/get.ts
apps/web/src/services/administration/components/UserManagementAddModal.vue
apps/web/src/services/administration/components/UserManagementAddPassword.vue
apps/web/src/services/administration/components/UserManagementAddRole.vue
apps/web/src/services/administration/components/UserManagementAddUser.vue
apps/web/src/services/administration/components/UserManagementTabDetail.vue
apps/web/src/services/administration/components/UserManagementTable.vue
apps/web/src/services/administration/store/user-modal-setting-store.ts
apps/web/src/store/app-context/workspace/workspace-store.ts

feat: apply create function at invitation modal

---

README.md
apps/web/src/lib/site-initializer/api-client.ts
packages/core-lib/src/space-connector/index.ts
packages/core-lib/src/space-connector/type.ts

feat(core-lib): add enabled for auth config

---

apps/web/src/common/modules/navigations/gnb/modules/gnb-recent-favorite/modules/GNBFavorite.vue
apps/web/src/services/asset-inventory/components/CollectorMainContents.vue
apps/web/src/services/asset-inventory/pages/CollectorMainPage.vue
apps/web/src/services/cost-explorer/CostExplorerLNB.vue
apps/web/src/services/cost-explorer/components/BudgetCreateDataSourceSelect.vue
apps/web/src/services/cost-explorer/components/BudgetCreateFormAmountPlanLastMonthsCost.vue
apps/web/src/services/cost-explorer/components/BudgetDetailInfo.vue
apps/web/src/services/cost-explorer/components/BudgetMainListCard.vue
apps/web/src/services/cost-explorer/components/BudgetMainToolbox.vue
apps/web/src/services/dashboards/components/DashboardManageVariableTable.vue
apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-by-target/BudgetUsageByTargetWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region/CostByRegionWidget.vue
apps/web/src/services/home-dashboard/components/FavoritesWidget.vue
apps/web/src/services/project/components/ProjectMainProjectGroupFormModal.vue
apps/web/src/services/project/components/ProjectMainProjectGroupMoveModal.vue
apps/web/src/services/project/components/ProjectSummaryBillingWidget.vue
apps/web/src/services/project/components/ProjectSummaryServiceAccountsWidget.vue
apps/web/src/services/project/pages/ProjectPage.vue
apps/web/src/store/modules/reference/actions.ts
apps/web/src/store/reference/all-reference-store.ts
apps/web/src/store/reference/project-group-store.ts

feat: add projectGroup pinia store & refactor usage of allReferenceStore 

---

apps/web/src/services/project/components/ProjectFormModal.vue
apps/web/src/services/project/components/ProjectMainProjectGroupDeleteCheckModal.vue
apps/web/src/services/project/components/ProjectMainProjectGroupFormModal.vue
apps/web/src/services/project/stores/project-page-store.ts
apps/web/src/store/reference/cloue-service-query-set-reference-store.ts
apps/web/src/store/reference/cost-data-source-reference-store.ts
apps/web/src/store/reference/project-group-store.ts
apps/web/src/store/reference/project-store.ts

fix: check state.items before load in reference store getters & refactor project-page-store

---

apps/web/src/services/cost-explorer/pages/admin/AdminBudgetCreatePage.vue
apps/web/src/services/cost-explorer/pages/admin/AdminBudgetMainPage.vue
apps/web/src/services/cost-explorer/routes/admin/routes.ts

feat: add budget pages for admin

---

apps/web/src/services/administration/components/UserManagementAddModal.vue
apps/web/src/services/administration/components/UserManagementAddRole.vue
apps/web/src/services/administration/components/UserManagementHeader.vue
apps/web/src/services/administration/components/UserManagementTable.vue
apps/web/src/services/administration/composables/refined-user-data.ts
apps/web/src/services/administration/pages/UserPage.vue
apps/web/src/services/administration/store/user-page-store.ts
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: apply remove workspace user at main table

---

apps/web/src/schema/identity/role/api-verbs/list.ts
apps/web/src/services/administration/components/UserManagementAddRole.vue
apps/web/src/services/administration/components/UserManagementFormAdminRole.vue
apps/web/src/services/administration/components/UserManagementFormInfoForm.vue
apps/web/src/services/administration/components/UserManagementFormNotificationEmailForm.vue
apps/web/src/services/administration/components/UserManagementFormPasswordForm.vue
apps/web/src/services/administration/components/UserManagementFormTags.vue
apps/web/src/services/administration/components/UserManagementTab.vue
apps/web/src/services/administration/components/UserManagementTabDetail.vue
apps/web/src/services/administration/components/UserManagementTable.vue
apps/web/src/services/administration/pages/UserPage.vue
apps/web/src/services/administration/store/role-page-store.ts
apps/web/src/services/administration/store/user-page-store.ts
apps/web/src/services/administration/types/user-type.ts
apps/web/src/store/modules/user/actions.ts
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: apply user detail tab

---

apps/web/src/schema/cost-analysis/budget/model.ts
apps/web/src/services/cost-explorer/components/BudgetCreateForm.vue
apps/web/src/services/cost-explorer/components/BudgetCreateFormAmountPlan.vue
apps/web/src/services/cost-explorer/components/BudgetCreateFormAmountPlanLastMonthsCost.vue
apps/web/src/services/cost-explorer/components/BudgetCreateFormBaseInfo.vue
apps/web/src/services/cost-explorer/components/BudgetCreateTargetSelect.vue
apps/web/src/services/cost-explorer/components/BudgetMainList.vue
apps/web/src/services/cost-explorer/components/BudgetMainListCard.vue

Please take a quick look😅
- `project_group_id` is removed from budget data!
- `workspace_id` is added to budget data!

feat: apply admin mode to budget components

---

apps/web/src/common/modules/navigations/gnb/modules/GNBHeader.vue
apps/web/src/common/modules/navigations/gnb/modules/GNBToolset.vue
apps/web/src/common/modules/navigations/gnb/modules/SiteMap.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-noti/GNBNoti.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-profile/GNBProfile.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-recent-favorite/GNBRecentFavorite.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-search/GNBSearch.vue

SSIA 
Almost markup
Please read order by commits
User Mode
Admin Mode

fix(gnb-header & gnb-toolset): new design markup

---

apps/web/src/common/modules/navigations/gnb/modules/gnb-menu/GNBInvisibleMenuDropdown.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-menu/GNBMenu.vue

SSIA
User Mode
Admin Mode
AFTER THIS PR,,, new GNB PR is coming..

fix(gnb-menu): add GNBInvisibleMenuDropdown & apply new design to menu

---

apps/web/src/schema/cost-analysis/budget-usage/api-verbs/analyze.ts
apps/web/src/services/cost-explorer/components/BudgetMainList.vue
apps/web/src/services/cost-explorer/components/BudgetMainListCard.vue
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: add badge to budget card & fix query filter of budget analyze 

---

apps/web/src/common/modules/navigations/gnb/GNB.vue
apps/web/src/common/modules/navigations/gnb/composables/use-gnb-container-width.ts

Please read order by commit!
- `use-gnb-container-width` file is almost copy of `use-dashboard-conatiner-width` hook!
https://github.com/cloudforet-io/console/assets/83635051/f60672c9-2595-445a-b85a-7b83e91e2110

fix(gnb): create dynamic menu visibility on GNB resize

---

apps/web/src/common/modules/navigations/gnb/GNB.vue
packages/core-lib/src/space-connector/index.ts
packages/core-lib/src/space-connector/service-api.ts
packages/core-lib/src/space-connector/type.ts

fix(core-lib): check if response is undefined (res interceptor issue)

---

apps/web/src/common/modules/navigations/gnb/modules/GNBAdminToggleButton.vue
apps/web/src/common/modules/navigations/gnb/modules/GNBToolset.vue

SSIA
Just markup
https://github.com/cloudforet-io/console/assets/83635051/d03f5c88-e4aa-4cb0-9bf1-adaaba604659

fix(admin-toggle): create and apply GNBAdminToggleButton

---

apps/web/src/services/asset-inventory/components/CollectorFormSchedule.vue
apps/web/src/services/asset-inventory/components/CollectorMainContentItem.vue
apps/web/src/services/asset-inventory/components/CollectorMainItemSchedule.vue
apps/web/src/services/asset-inventory/components/CollectorMainScheduleModal.vue
apps/web/src/services/asset-inventory/stores/collector-page-store.ts
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json
packages/mirinae/src/inputs/buttons/toggle-button/PToggleButton.stories.mdx
packages/mirinae/src/inputs/buttons/toggle-button/PToggleButton.vue
packages/mirinae/src/inputs/buttons/toggle-button/story-helper.ts

- Add view mode of Schedule Modal
- Add view mode of CollectorMainItemSchedule

feat: add User Mode features of Collector Main Page

---

apps/web/src/schema/add-ons/favorite/list.ts
apps/web/src/schema/add-ons/favorite/model.ts
apps/web/src/schema/config/domain-config/model.ts
apps/web/src/schema/config/user-config/model.ts
apps/web/src/services/info/pages/admin/AdminNoticeDetailPage.vue
apps/web/src/services/info/pages/admin/AdminNoticeMainPage.vue
apps/web/src/store/modules/favorite/actions.ts

refactor: apply user config, domain config schema

---

apps/web/src/lib/menu/menu-info.ts
apps/web/src/services/administration/AdministrationLNB.vue
apps/web/src/services/administration/components/DomainSettingsBaseInformation.vue
apps/web/src/services/administration/components/DomainSettingsBrandAssets.vue
apps/web/src/services/administration/components/DomainSettingsChangeAdminEmailModal.vue
apps/web/src/services/administration/components/DomainSettingsTimezoneAndLanguage.vue
apps/web/src/services/administration/pages/admin/AdminDomainSettingsPage.vue
apps/web/src/services/administration/routes/admin/routes.ts
apps/web/src/store/modules/display/getters.ts
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: add domain settings page and components

---

apps/web/src/schema/inventory/collector/api-verbs/collect.ts
apps/web/src/schema/inventory/collector/api-verbs/create.ts
apps/web/src/services/asset-inventory/components/CollectorBaseInfoSection.vue
apps/web/src/services/asset-inventory/components/CollectorCollectorStep2.vue
apps/web/src/services/asset-inventory/components/CollectorCreateStep1SearchFilter.vue
apps/web/src/services/asset-inventory/components/CollectorCreateStep3.vue
apps/web/src/services/asset-inventory/components/CollectorCreateStep4.vue
apps/web/src/services/asset-inventory/components/CollectorDataModal.vue
apps/web/src/services/asset-inventory/components/CollectorDetailNameEditModal.vue
apps/web/src/services/asset-inventory/components/CollectorDetailOptionsSection.vue
apps/web/src/services/asset-inventory/components/CollectorDetailScheduleSection.vue
apps/web/src/services/asset-inventory/components/CollectorDetailServiceAccountsSection.vue
apps/web/src/services/asset-inventory/components/CollectorFormSchedule.vue
apps/web/src/services/asset-inventory/pages/CollectorDetailPage.vue
apps/web/src/services/asset-inventory/stores/collector-page-store.ts
apps/web/src/store/modules/reference/collector/actions.ts

feat: modify continue button style

---

apps/web/src/schema/identity/user/api-verbs/get-workspaces.ts
apps/web/src/schema/identity/workspace-user/api-verbs/get.ts
apps/web/src/services/alert-manager/components/AlertDetailSummaryAssignModal.vue
apps/web/src/services/asset-inventory/components/CloudServiceAdmin.vue
apps/web/src/services/asset-inventory/components/ServiceAccountBaseInformation.vue
apps/web/src/services/asset-inventory/components/ServiceAccountBaseInformationForm.vue
apps/web/src/services/asset-inventory/components/ServiceAccountCredentialsForm.vue
apps/web/src/services/asset-inventory/pages/ServiceAccountAddPage.vue
apps/web/src/services/asset-inventory/pages/ServiceAccountDetailPage.vue
apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue
apps/web/src/services/asset-inventory/stores/service-account-schema-store.ts
apps/web/src/services/my-page/components/NotificationAddMemberGroup.vue
apps/web/src/services/project/components/ProjectMainCardList.vue
apps/web/src/services/project/components/ProjectMainProjectTree.vue
apps/web/src/services/project/components/ProjectMemberInviteModal.vue
apps/web/src/services/project/components/ProjectMemberTab.vue
apps/web/src/services/project/helpers/workspace-user-helper.ts
apps/web/src/services/project/pages/ProjectAlertEventRulePage.vue
apps/web/src/services/project/pages/ProjectDetailPage.vue
apps/web/src/services/project/stores/project-detail-page-store.ts
apps/web/src/store/modules/reference/project-group/actions.ts
apps/web/src/store/modules/reference/project/actions.ts
apps/web/src/store/modules/reference/provider/actions.ts
apps/web/src/store/modules/reference/service-account/actions.ts
apps/web/src/store/modules/reference/trusted-account/actions.ts
apps/web/src/store/modules/user/actions.ts

feat: delete unnecessary domain_id from api request

---

apps/web/src/schema/_common/constant.ts
apps/web/src/schema/_common/type.ts
apps/web/src/schema/identity/role-binding/api-verbs/create.ts
apps/web/src/schema/identity/role-binding/api-verbs/list.ts
apps/web/src/schema/identity/role-binding/model.ts
apps/web/src/schema/identity/role/api-verbs/create.ts
apps/web/src/schema/identity/role/api-verbs/update.ts
apps/web/src/schema/identity/role/model.ts
apps/web/src/services/administration/components/RoleDeleteModal.vue
apps/web/src/services/administration/components/RoleManagementTab.vue
apps/web/src/services/administration/components/RoleManagementTabDetail.vue
apps/web/src/services/administration/components/RoleManagementTable.vue
apps/web/src/services/administration/constants/role-constant.ts
apps/web/src/services/administration/store/role-page-store.ts
apps/web/src/store/app-context/workspace/workspace-store.ts
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: apply function at role detail tab

---

apps/web/src/store/modules/user/actions.ts

fix: set domain_id until backend is ready

---

apps/web/src/services/dashboards/pages/DashboardCustomizePage.vue
apps/web/src/services/dashboards/pages/DashboardDetailPage.vue
apps/web/src/services/dashboards/pages/DashboardsMainPage.vue

refactor: use setup script

---

apps/web/src/schema/_common/constant.ts
apps/web/src/schema/dashboard/_types/dashboard-type.ts
apps/web/src/schema/dashboard/dashboard/api-verbs/create.ts
apps/web/src/schema/dashboard/dashboard/api-verbs/delete.ts
apps/web/src/schema/dashboard/dashboard/api-verbs/get.ts
apps/web/src/schema/dashboard/dashboard/api-verbs/list.ts
apps/web/src/schema/dashboard/dashboard/api-verbs/update.ts
apps/web/src/schema/dashboard/dashboard/model.ts
apps/web/src/schema/identity/role-binding/api-verbs/create.ts
apps/web/src/schema/identity/role-binding/api-verbs/list.ts
apps/web/src/schema/identity/role-binding/model.ts

feat: add new dashboard model and api-verbs

---

apps/web/src/schema/cost-analysis/budget-usage/api-verbs/analyze.ts
apps/web/src/schema/identity/role-binding/type.ts
apps/web/src/schema/inventory/collector/api-verbs/list.ts
apps/web/src/schema/inventory/collector/model.ts
apps/web/src/schema/secret/secret/api-verbs/create.ts
apps/web/src/schema/secret/secret/api-verbs/list.ts
apps/web/src/schema/secret/secret/model.ts
apps/web/src/schema/secret/trusted-secret/api-verbs/create.ts
apps/web/src/schema/secret/trusted-secret/api-verbs/list.ts
apps/web/src/schema/secret/trusted-secret/model.ts
apps/web/src/services/asset-inventory/components/CollectorBaseInfoSection.vue
apps/web/src/services/asset-inventory/components/CollectorCreateStep1.vue
apps/web/src/services/asset-inventory/components/CollectorDetailOptionsSection.vue
apps/web/src/services/asset-inventory/components/CollectorDetailScheduleSection.vue
apps/web/src/services/asset-inventory/components/CollectorDetailSectionHeader.vue
apps/web/src/services/asset-inventory/components/CollectorDetailServiceAccountsSection.vue
apps/web/src/services/asset-inventory/pages/CollectorDetailPage.vue
apps/web/src/services/asset-inventory/stores/collector-detail-page-store.ts
apps/web/src/services/asset-inventory/stores/collector-form-store.ts

SSIA
- Change 'permissionGroup' to 'resourceGroup'
- Create CollectorDetailPageStore

feat: implement managed collector to be modified only in Admin mode

---

apps/web/src/schema/identity/token/api-verbs/issue.ts
apps/web/src/schema/identity/user/type.ts
apps/web/src/store/modules/user/actions.ts
packages/core-lib/src/space-connector/index.ts
packages/core-lib/src/space-connector/token-api.ts

API spec is not fixed, so It must be tested after api is completed.
It is just the concept. I will fix it after api is completed if necessary.

feat: add grantRole action to user store action

---

apps/web/src/services/dashboards/components/DashboardCloneModal.vue
apps/web/src/services/dashboards/components/DashboardControlButtons.vue
apps/web/src/services/dashboards/components/DashboardCustomize.vue
apps/web/src/services/dashboards/components/DashboardCustomizePageName.vue
apps/web/src/services/dashboards/components/DashboardDeleteModal.vue
apps/web/src/services/dashboards/components/DashboardLabels.vue
apps/web/src/services/dashboards/components/DashboardMainBoardList.vue
apps/web/src/services/dashboards/components/DashboardMainSelectFilter.vue
apps/web/src/services/dashboards/components/DashboardManageVariableForm.vue
apps/web/src/services/dashboards/components/DashboardManageVariableOptionsField.vue
apps/web/src/services/dashboards/components/DashboardManageVariableOverlay.vue
apps/web/src/services/dashboards/components/DashboardManageVariableTable.vue
apps/web/src/services/dashboards/components/DashboardNameEditModal.vue
apps/web/src/services/dashboards/components/DashboardRefreshDropdown.vue
apps/web/src/services/dashboards/components/DashboardScopeForm.vue
apps/web/src/services/dashboards/components/DashboardTemplateForm.vue
apps/web/src/services/dashboards/components/DashboardToolset.vue
apps/web/src/services/dashboards/components/DashboardToolsetDateDropdown.vue
apps/web/src/services/dashboards/components/DashboardVariablesMoreButton.vue
apps/web/src/services/dashboards/components/DashboardViewerForm.vue

refactor(dashboard): use script setup

---

apps/web/src/services/my-page/components/UserAccountBaseInformation.vue

fix: hide role type if it's not domain admin in account page

---

apps/web/src/services/administration/components/AppManagementFormModal.vue
apps/web/src/services/administration/components/AppManagementTable.vue
apps/web/src/services/administration/pages/AppPage.vue
apps/web/src/services/administration/store/app-page-store.ts

feat: apply update UI for app

---

apps/web/src/common/components/scoped-notification/ScopedNotification.vue
apps/web/src/common/modules/page-layouts/VerticalPageLayout.vue
apps/web/src/services/asset-inventory/pages/CollectorDetailPage.vue
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: add ScopedNotification to CollectorDetailpage

---

apps/web/src/lib/site-initializer/api-client.ts
apps/web/src/lib/site-initializer/domain.ts
apps/web/src/lib/site-initializer/index.ts
apps/web/src/lib/site-initializer/user-auth.ts

fix(site-init): add checking user-auth in site-init

---

apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: change table design of serviceAccountMainPage

---

apps/web/src/services/administration/components/AppManagementFormModal.vue
apps/web/src/services/administration/components/AppManagementStatusModal.vue
apps/web/src/services/administration/components/AppManagementTable.vue
apps/web/src/services/administration/pages/AppPage.vue
apps/web/src/services/administration/store/app-page-store.ts
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: create (delete,enable,disable,regenerate) modals at app page

---

apps/web/src/schema/identity/role/model.ts
apps/web/src/schema/identity/token/api-verbs/grant.ts
apps/web/src/schema/identity/token/api-verbs/token.ts
apps/web/src/schema/identity/token/type.ts
apps/web/src/schema/identity/user/type.ts
apps/web/src/store/modules/user/actions.ts
apps/web/src/store/modules/user/index.ts
apps/web/src/store/modules/user/mutations.ts
apps/web/src/store/modules/user/type.ts

SSIA
Please read order by commits... not that difficult (to me)

fix(token-grant): apply token grant in user-store actions

---

apps/web/src/router/index.ts
apps/web/src/store/modules/user/actions.ts
packages/core-lib/src/space-connector/index.ts

fix(token-grant): apply API-Key grant in router navigation guard & create getAccessToken method in SpaceConnector

---

apps/web/src/schema/identity/token/api-verbs/issue.ts
apps/web/src/schema/identity/token/model.ts
apps/web/src/store/app-context/workspace/workspace-store.ts
apps/web/src/store/modules/user/actions.ts

fix(user): apply token grant in user/actions

---

apps/web/src/common/modules/navigations/gnb/modules/gnb-menu/modules/dashboard-recent-favorite/modules/GNBDashboardFavorite.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-menu/modules/dashboard-recent-favorite/modules/GNBDashboardMenu.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-menu/modules/dashboard-recent-favorite/modules/GNBDashboardRecent.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-recent-favorite/modules/GNBFavorite.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-recent-favorite/modules/GNBRecent.vue
apps/web/src/lib/helper/router-recent-helper.ts
apps/web/src/lib/menu/config.ts
apps/web/src/lib/menu/menu-architecture.ts
apps/web/src/lib/menu/menu-info.ts
apps/web/src/services/dashboards/DashboardsLNB.vue
apps/web/src/services/dashboards/components/DashboardCloneModal.vue
apps/web/src/services/dashboards/components/DashboardControlButtons.vue
apps/web/src/services/dashboards/components/DashboardMainBoardList.vue
apps/web/src/services/dashboards/components/DashboardMainSelectFilter.vue
apps/web/src/services/dashboards/components/DashboardManageVariableOverlay.vue
apps/web/src/services/dashboards/components/DashboardScopeForm.vue
apps/web/src/services/dashboards/components/DashboardTemplateForm.vue
apps/web/src/services/dashboards/components/DashboardVariablesMoreButton.vue
apps/web/src/services/dashboards/pages/DashboardCreatePage.vue
apps/web/src/services/dashboards/pages/DashboardCustomizePage.vue
apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
apps/web/src/services/dashboards/routes/admin/routes.ts
apps/web/src/services/dashboards/routes/route-constant.ts
apps/web/src/services/dashboards/routes/routes.ts
apps/web/src/store/dashboard/dashboard-store.ts

feat: delete `PROJECT_DASHBOARDS`, `WORKSPACE_DASHBOARDS` from `MENU_ID`

---

apps/web/src/common/composables/page-manage-permission/index.ts
apps/web/src/lib/access-control/config.ts
apps/web/src/lib/access-control/index.ts
apps/web/src/lib/access-control/page-permission-helper.ts
apps/web/src/lib/access-control/redirect-route-helper.ts
apps/web/src/router/index.ts
apps/web/src/services/administration/routes/routes.ts
apps/web/src/services/alert-manager/routes/routes.ts
apps/web/src/services/asset-inventory/routes/routes.ts
apps/web/src/services/cost-explorer/routes/routes.ts
apps/web/src/services/dashboards/routes/routes.ts
apps/web/src/services/home-dashboard/routes/routes.ts
apps/web/src/services/info/routes/routes.ts
apps/web/src/services/my-page/routes/routes.ts
apps/web/src/services/project/routes/routes.ts
apps/web/src/store/modules/display/getters.ts
apps/web/src/store/modules/user/actions.ts
apps/web/src/store/modules/user/config.ts
apps/web/src/store/modules/user/getters.ts
packages/core-lib/src/space-connector/index.ts
packages/core-lib/src/space-connector/token-api.ts

refactor(page-access): update new page-access & access level

---

apps/web/src/store/app-context/workspace/workspace-store.ts

fix: remove workspace interceptor

---

apps/web/src/common/modules/navigations/gnb/modules/gnb-menu/modules/dashboard-recent-favorite/modules/GNBDashboardMenu.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-recent-favorite/modules/GNBFavorite.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-recent-favorite/modules/GNBRecent.vue
apps/web/src/services/dashboards/DashboardsContainer.vue
apps/web/src/services/dashboards/components/DashboardCustomizePageName.vue
apps/web/src/services/dashboards/components/DashboardNameEditModal.vue
apps/web/src/services/dashboards/components/DashboardTemplateForm.vue
apps/web/src/store/reference/workspace-store.ts

feat: load dashboardStore in right place

---

apps/web/src/services/dashboards/DashboardsLNB.vue
apps/web/src/services/dashboards/components/DashboardDeleteModal.vue
apps/web/src/services/dashboards/components/DashboardMainBoardList.vue
apps/web/src/services/dashboards/pages/admin/AdminDashboardMainPage.vue
apps/web/src/services/dashboards/routes/admin/routes.ts
apps/web/src/store/dashboard/dashboard-store.ts

feat: add `DashboardMainPage` for admin & update `DashboardsLNB`

---

apps/web/src/lib/site-initializer/domain.ts
apps/web/src/lib/site-initializer/index.ts
apps/web/src/lib/site-initializer/workspace.ts
apps/web/src/router/index.ts

refactor(site-init): use one try catch block

---

apps/web/src/services/dashboards/components/DashboardTemplateForm.vue
apps/web/src/services/dashboards/pages/admin/AdminDashboardCreatePage.vue
apps/web/src/services/dashboards/routes/admin/routes.ts

feat: add DashboardCreatePage for admin

---

apps/web/src/common/modules/navigations/gnb/modules/GNBHeader.vue

fix: edit default logo path

---

apps/web/src/lib/site-initializer/user-auth.ts

fix: solve issue

---

apps/web/src/schema/board/post/api-verbs/list.ts
apps/web/src/schema/cost-analysis/budget-usage/api-verbs/analyze.ts
apps/web/src/schema/identity/trusted-account/api-verbs/create.ts
apps/web/src/schema/identity/trusted-account/api-verbs/list.ts
apps/web/src/schema/identity/trusted-account/model.ts
apps/web/src/schema/inventory/collector/api-verbs/list.ts
apps/web/src/schema/secret/secret/api-verbs/create.ts
apps/web/src/schema/secret/secret/api-verbs/list.ts
apps/web/src/schema/secret/secret/model.ts
apps/web/src/schema/secret/trusted-secret/api-verbs/create.ts
apps/web/src/schema/secret/trusted-secret/api-verbs/list.ts
apps/web/src/schema/secret/trusted-secret/model.ts
apps/web/src/services/asset-inventory/components/ServiceAccountCredentials.vue
apps/web/src/services/asset-inventory/helpers/dynamic-ui-schema-generator/dynamic-layout-schema-template.ts
apps/web/src/services/asset-inventory/pages/ServiceAccountAddPage.vue
apps/web/src/store/modules/reference/trusted-account/actions.ts

feat: change name from `permission_group` to `resource_group`

---

apps/web/src/schema/config/user-config/api-verbs/create.ts
apps/web/src/schema/config/user-config/api-verbs/delete.ts
apps/web/src/schema/config/user-config/api-verbs/get.ts
apps/web/src/schema/config/user-config/api-verbs/list.ts
apps/web/src/schema/config/user-config/api-verbs/set.ts
apps/web/src/schema/config/user-config/api-verbs/update.ts
apps/web/src/schema/config/user-config/model.ts
apps/web/src/services/asset-inventory/helpers/dynamic-ui-schema-generator/index.ts
apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue

fix: fix dynamicLayout bug in serviceAccountTable & add userConfig schema

---

apps/web/src/services/dashboards/components/DashboardDetailHeader.vue
apps/web/src/services/dashboards/pages/DashboardCreatePage.vue
apps/web/src/services/dashboards/pages/DashboardDetailPage.vue
apps/web/src/services/dashboards/pages/admin/AdminDashboardCustomizePage.vue
apps/web/src/services/dashboards/pages/admin/AdminDashboardDetailPage.vue
apps/web/src/services/dashboards/routes/admin/routes.ts

feat: add DashboardDetailPage for admin

---

apps/web/src/router/index.ts
apps/web/src/services/administration/pages/admin/RolePage.vue

fix(role-page): edit target route name

---

apps/web/src/common/modules/navigations/gnb/modules/gnb-profile/GNBProfile.vue
apps/web/src/services/administration/pages/UserManageNotificationPage.vue
apps/web/src/services/info/components/NoticeDetail.vue
apps/web/src/services/info/components/NoticeForm.vue
apps/web/src/services/info/components/NoticeListItem.vue
apps/web/src/services/info/pages/admin/AdminNoticeDetailPage.vue
apps/web/src/services/info/pages/admin/AdminNoticeMainPage.vue
apps/web/src/services/info/pages/admin/AdminNoticeUpdatePage.vue
apps/web/src/store/modules/user/getters.ts

refactor(user-getters): refactoring with new roleType

---

apps/web/src/lib/menu/menu-architecture.ts
apps/web/src/router/index.ts
apps/web/src/services/administration/routes/routes.ts

fix(administration): change administration to user-mode IAM

---

apps/web/src/common/modules/navigations/gnb/GNB.vue
apps/web/src/common/modules/navigations/gnb/modules/SiteMap.vue

User Mode
- As is, but IAM need to have administration icon
Admin Mode
- Site map need to show low menus like 'User', 'Domain settings' .... instead of 'IAM', 'Preference'

fix(site-map): apply new site map menu

---

apps/web/src/common/modules/custom-table/custom-field-modal/CustomFieldModal.vue
apps/web/src/services/asset-inventory/helpers/dynamic-ui-schema-generator/index.ts
apps/web/src/services/asset-inventory/pages/CloudServiceDetailPage.vue
apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue

feat(custom-field-modal): apply setup script

---

apps/web/src/common/modules/navigations/gnb/modules/gnb-menu/modules/dashboard-recent-favorite/modules/GNBDashboardMenu.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-recent-favorite/modules/GNBFavorite.vue
apps/web/src/services/dashboards/components/DashboardCloneModal.vue
apps/web/src/services/dashboards/components/DashboardManageVariableTable.vue
apps/web/src/services/dashboards/components/DashboardTemplateForm.vue
apps/web/src/services/dashboards/pages/DashboardCreatePage.vue
apps/web/src/services/dashboards/pages/DashboardDetailPage.vue
apps/web/src/services/dashboards/pages/admin/AdminDashboardCreatePage.vue
apps/web/src/services/dashboards/pages/admin/AdminDashboardDetailPage.vue
apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
apps/web/src/store/dashboard/dashboard-store.ts

fix: set projectId based on the `resource_group` value

---

apps/web/src/common/modules/custom-table/custom-field-modal/CustomFieldModal.vue
apps/web/src/services/asset-inventory/components/ServiceAccountBaseInformationDetail.vue
apps/web/src/services/asset-inventory/helpers/dynamic-ui-schema-generator/index.ts
apps/web/src/services/asset-inventory/helpers/dynamic-ui-schema-generator/type.ts
apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue
apps/web/src/services/asset-inventory/stores/service-account-schema-store.ts

Now, We can use the above modal in serviceAccountPage.

feat: apply userConfig api to customFieldModal

---

apps/web/src/services/dashboards/components/DashboardCloneModal.vue
apps/web/src/services/dashboards/components/DashboardCustomize.vue
apps/web/src/services/dashboards/components/DashboardCustomizePageName.vue
apps/web/src/services/dashboards/components/DashboardCustomizeSidebar.vue
apps/web/src/services/dashboards/components/DashboardDetailHeader.vue
apps/web/src/services/dashboards/components/DashboardLabels.vue
apps/web/src/services/dashboards/components/DashboardManageVariableOverlay.vue
apps/web/src/services/dashboards/components/DashboardManageVariableTable.vue
apps/web/src/services/dashboards/components/DashboardNameEditModal.vue
apps/web/src/services/dashboards/components/DashboardRefreshDropdown.vue
apps/web/src/services/dashboards/components/DashboardToolset.vue
apps/web/src/services/dashboards/components/DashboardVariableDropdown.vue
apps/web/src/services/dashboards/components/DashboardVariables.vue
apps/web/src/services/dashboards/components/DashboardVariablesMoreButton.vue
apps/web/src/services/dashboards/components/DashboardWidgetContainer.vue
apps/web/src/services/dashboards/components/DashboardWidgetForm.vue
apps/web/src/services/dashboards/components/WidgetViewModeModal.vue
apps/web/src/services/dashboards/components/WidgetViewModeModalSidebar.vue
apps/web/src/services/dashboards/pages/DashboardCreatePage.vue
apps/web/src/services/dashboards/pages/DashboardCustomizePage.vue
apps/web/src/services/dashboards/pages/DashboardDetailPage.vue
apps/web/src/services/dashboards/pages/admin/AdminDashboardCreatePage.vue
apps/web/src/services/dashboards/pages/admin/AdminDashboardCustomizePage.vue
apps/web/src/services/dashboards/pages/admin/AdminDashboardDetailPage.vue
apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
apps/web/src/services/dashboards/stores/widget-form-store.ts
apps/web/src/store/dashboard/dashboard-store.ts

refactor(dashboard-detail-info-store): implement setup pinia store

---

apps/web/src/schema/identity/service-account/api-verbs/create.ts
apps/web/src/schema/identity/trusted-account/api-verbs/create.ts
apps/web/src/schema/identity/trusted-account/api-verbs/get.ts
apps/web/src/services/asset-inventory/components/ServiceAccountBaseInformationForm.vue
apps/web/src/services/asset-inventory/components/ServiceAccountCredentialsForm.vue
apps/web/src/services/asset-inventory/components/ServiceAccountProjectForm.vue
apps/web/src/services/asset-inventory/pages/ServiceAccountAddPage.vue
apps/web/src/services/asset-inventory/pages/ServiceAccountDetailPage.vue
apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue

feat: apply the updated identity API to add page

---

apps/web/src/lib/variable-models/managed/project-variable-model.ts
apps/web/src/services/alert-manager/types/alert-type.ts
apps/web/src/services/project/composables/use-project-tree.ts

fix: do not get `project_group_info` from project (it's deprecated)

---

apps/web/src/services/dashboards/pages/DashboardCreatePage.vue
apps/web/src/services/dashboards/pages/admin/AdminDashboardCreatePage.vue
apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
apps/web/src/store/dashboard/dashboard-store.ts

fix: fix minor bugs in dashboard

---

apps/web/src/services/project/stores/project-page-store.ts

fix: fix `role_type` bug in project-page-store

---

apps/web/src/common/modules/navigations/gnb/modules/gnb-menu/GNBMenu.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-noti/GNBNoti.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-profile/GNBProfile.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-recent-favorite/GNBRecentFavorite.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-search/modules/GNBSearchDropdown.vue
apps/web/src/lib/access-control/index.ts
apps/web/src/router/index.ts

fix: fix gnb-issues & grant-issue

---

apps/web/src/schema/identity/service-account/api-verbs/change-trusted-account.ts
apps/web/src/schema/identity/service-account/api-verbs/create.ts
apps/web/src/schema/identity/service-account/api-verbs/detele-secret-data.ts
apps/web/src/schema/identity/service-account/api-verbs/detele.ts
apps/web/src/schema/identity/service-account/api-verbs/get.ts
apps/web/src/schema/identity/service-account/api-verbs/list.ts
apps/web/src/schema/identity/service-account/api-verbs/stat.ts
apps/web/src/schema/identity/service-account/api-verbs/update-secret-data.ts
apps/web/src/schema/identity/service-account/api-verbs/update.ts
apps/web/src/schema/identity/service-account/model.ts
apps/web/src/schema/identity/trusted-account/api-verbs/create.ts
apps/web/src/schema/identity/trusted-account/api-verbs/detele.ts
apps/web/src/schema/identity/trusted-account/api-verbs/get.ts
apps/web/src/schema/identity/trusted-account/api-verbs/list.ts
apps/web/src/schema/identity/trusted-account/api-verbs/stat.ts
apps/web/src/schema/identity/trusted-account/api-verbs/update-secret-data.ts
apps/web/src/schema/identity/trusted-account/api-verbs/update.ts
apps/web/src/schema/identity/trusted-account/model.ts
apps/web/src/services/asset-inventory/components/ServiceAccountBaseInformationDetail.vue
apps/web/src/services/asset-inventory/components/ServiceAccountCredentials.vue
apps/web/src/services/asset-inventory/components/ServiceAccountCredentialsDetail.vue
apps/web/src/services/asset-inventory/components/ServiceAccountDeleteModal.vue

feat: apply the updated identity API to ServiceAccountDetailPage

---

packages/mirinae/src/data-display/dynamic/dynamic-field/PDynamicField.stories.mdx
packages/mirinae/src/data-display/dynamic/dynamic-field/templates/badge/index.vue
packages/mirinae/src/data-display/dynamic/dynamic-field/templates/datetime/index.vue
packages/mirinae/src/data-display/dynamic/dynamic-field/templates/size/index.vue
packages/mirinae/src/data-display/dynamic/dynamic-field/templates/state/index.vue
packages/mirinae/src/data-display/dynamic/dynamic-field/templates/text/index.vue

fix(p-dynamic-field): apply the changed PLink spec

---

apps/web/src/common/pages/ErrorPage.vue
apps/web/src/router/index.ts
apps/web/src/store/modules/user/actions.ts
apps/web/src/store/modules/user/mutations.ts

If you access none-access workspace or mode, your permission will be empty

fix(grant): apply grant-fail scenario

---

apps/web/src/services/project/components/ProjectMainCardList.vue
apps/web/src/services/project/composables/use-project-tree.ts

- show root project in project select dropdown
- hide private(and not invited) project from project list

fix: show root project in project select dropdown & hide private(and not invited) project from project list 

---

apps/web/src/App.vue
apps/web/src/common/modules/page-layouts/VerticalPageLayout.vue
apps/web/src/store/global-ui/global-ui-store.ts

Before
After
Added 'global-ui-store' (pinia) which is gonna replace display store module(vuex).

fix: do not show scroller when top notification is shown

---

apps/web/src/App.vue
apps/web/src/common/modules/navigations/gnb/MyPageGNB.vue
apps/web/src/common/modules/navigations/gnb/modules/GNBAdminToggleButton.vue
apps/web/src/common/modules/navigations/gnb/modules/MyPageGNBHeader.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-noti/GNBNoti.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-profile/GNBProfile.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-recent-favorite/GNBRecentFavorite.vue
apps/web/src/lib/access-control/page-access-permission-helper.ts
apps/web/src/services/my-page/routes/routes.ts
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

SSIA
Please read order by commits!

fix(my-page): create my-page gnb & edit small issue

---

apps/web/src/schema/identity/role-binding/api-verbs/create.ts
apps/web/src/schema/identity/user/api-verbs/create.ts
apps/web/src/services/administration/components/UserManagementAddAdminRole.vue
apps/web/src/services/administration/components/UserManagementAddModal.vue
apps/web/src/services/administration/components/UserManagementAddPassword.vue
apps/web/src/services/administration/components/UserManagementAddTag.vue
apps/web/src/services/administration/components/UserManagementAddUser.vue
apps/web/src/services/administration/components/UserManagementFormTags.vue
apps/web/src/services/administration/components/UserManagementTable.vue
apps/web/src/services/administration/components/UserManagementTableToolbox.vue
apps/web/src/services/administration/pages/UserPage.vue
apps/web/src/services/administration/store/user-page-store.ts

feat: connecting user creation feature

---

apps/web/src/lib/site-initializer/index.ts
apps/web/src/router/integral-routes.ts

fix(redirect): solve workspace redirect issue

---

apps/web/src/services/asset-inventory/components/ServiceAccountAttachedGeneralAccounts.vue
apps/web/src/services/asset-inventory/components/ServiceAccountBaseInformation.vue
apps/web/src/services/asset-inventory/components/ServiceAccountBaseInformationForm.vue
apps/web/src/services/asset-inventory/components/ServiceAccountCredentialsDetail.vue
apps/web/src/services/asset-inventory/components/ServiceAccountCredentialsForm.vue
apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue

This is the final PR for the Service Account page. 
I have fixed the incorrectly requested API query and addressed minor bugs.

fix: fix workspace_id of the api request params & fix minor things

---

apps/web/src/services/asset-inventory/components/ServiceAccountDeleteModal.vue
apps/web/src/services/asset-inventory/pages/ServiceAccountDetailPage.vue

feat: apply the v2 apis to serviceAccountDeleteModal

---

apps/web/src/common/pages/ErrorPage.vue
apps/web/src/router/integral-routes.ts

SSIA
Handle admin url direct access case without domain-admin role

fix(workspace-route): handle 403 error case

---

apps/web/src/lib/access-control/index.ts

Use matched instead of target route's menuId

fix(page-access): refactor getUserAccessLevel helper

---

apps/web/src/common/modules/modals/notification-email-modal/NotificationEmailModal.vue
apps/web/src/lib/helper/multi-factor-auth-helper.ts
apps/web/src/lib/helper/verify-email-helper.ts
apps/web/src/schema/identity/role-binding/api-verbs/update.ts
apps/web/src/schema/identity/role/api-verbs/list.ts
apps/web/src/schema/identity/user/api-verbs/disable-mfa.ts
apps/web/src/schema/identity/user/api-verbs/verify-email.ts
apps/web/src/services/administration/components/UserManagementAddAdminRole.vue
apps/web/src/services/administration/components/UserManagementAddModal.vue
apps/web/src/services/administration/components/UserManagementAddRole.vue
apps/web/src/services/administration/components/UserManagementAddTag.vue
apps/web/src/services/administration/components/UserManagementAddUser.vue
apps/web/src/services/administration/components/UserManagementFormInfoForm.vue
apps/web/src/services/administration/components/UserManagementFormModal.vue
apps/web/src/services/administration/components/UserManagementFormMultiFactorAuth.vue
apps/web/src/services/administration/components/UserManagementFormNotificationEmailForm.vue
apps/web/src/services/administration/components/UserManagementFormPasswordForm.vue
apps/web/src/services/administration/components/UserManagementTable.vue
apps/web/src/services/administration/pages/UserMainPage.vue
apps/web/src/services/administration/types/user-type.ts
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

refactor: reflecting user update

---

apps/web/src/common/pages/ErrorPage.vue

fix(error-page): solve 403 prison issue

---

apps/web/src/schema/inventory/collector/model.ts
apps/web/src/schema/repository/plugin/api-verbs/deregister.ts
apps/web/src/schema/repository/plugin/api-verbs/disable.ts
apps/web/src/schema/repository/plugin/api-verbs/enable.ts
apps/web/src/schema/repository/plugin/api-verbs/get-versions.ts
apps/web/src/schema/repository/plugin/api-verbs/get.ts
apps/web/src/schema/repository/plugin/api-verbs/list.ts
apps/web/src/schema/repository/plugin/api-verbs/register.ts
apps/web/src/schema/repository/plugin/api-verbs/stat.ts
apps/web/src/schema/repository/plugin/api-verbs/update.ts
apps/web/src/schema/repository/plugin/constant.ts
apps/web/src/schema/repository/plugin/model.ts
apps/web/src/schema/repository/plugin/type.ts
apps/web/src/schema/repository/repository/api-verbs/list.ts
apps/web/src/schema/repository/repository/model.ts
apps/web/src/services/asset-inventory/components/CollectorCreateStep1.vue
apps/web/src/services/asset-inventory/components/CollectorCreateStep1SearchFilter.vue

feat: update repository schema

---

apps/web/src/services/dashboards/components/DashboardCloneModal.vue
apps/web/src/services/dashboards/components/DashboardDetailHeader.vue
apps/web/src/services/dashboards/components/DashboardVariables.vue
apps/web/src/services/dashboards/pages/DashboardCreatePage.vue
apps/web/src/services/dashboards/pages/DashboardDetailPage.vue
apps/web/src/services/dashboards/pages/admin/AdminDashboardCreatePage.vue
apps/web/src/services/dashboards/pages/admin/AdminDashboardDetailPage.vue
apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
apps/web/src/services/dashboards/types/dashboard-api-schema-type.ts
apps/web/src/store/dashboard/dashboard-store.ts

refactor: refactor dashboard-detail-info-store & apply it to the pages & fix clone dashboard logic

---

apps/web/src/schema/inventory/collector/api-verbs/update-plugin.ts
apps/web/src/schema/inventory/collector/constant.ts
apps/web/src/schema/inventory/collector/model.ts
apps/web/src/schema/inventory/collector/type.ts
apps/web/src/schema/plugin/plugin/api-verbs/get-plugin-endpoint.ts
apps/web/src/schema/plugin/plugin/api-verbs/get-plugin-metadata.ts
apps/web/src/schema/plugin/plugin/api-verbs/notify_failure.ts
apps/web/src/schema/plugin/plugin/constant.ts
apps/web/src/schema/plugin/plugin/type.ts
apps/web/src/services/asset-inventory/components/CollectorBaseInfoSection.vue
apps/web/src/services/asset-inventory/components/CollectorCreateStep1.vue
apps/web/src/services/asset-inventory/components/CollectorCreateStep1SearchFilter.vue
apps/web/src/services/asset-inventory/stores/collector-form-store.ts

feat: update plugin schema & fix minor things

---

apps/web/src/router/index.ts

fix(grant): solve wrong grant target issue

---

apps/web/src/services/dashboards/components/DashboardCloneModal.vue
apps/web/src/services/dashboards/components/DashboardCustomizePageName.vue
apps/web/src/services/dashboards/components/DashboardNameEditModal.vue
apps/web/src/store/dashboard/dashboard-store.ts

feat: implement adminMode to dashboard clone modal

---

apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
apps/web/src/store/dashboard/dashboard-store.ts

fix: fix update/delete dashboard bug (wrong dashboardType)

---

apps/web/src/schema/repository/plugin/model.ts
apps/web/src/schema/repository/repository/model.ts
apps/web/src/services/asset-inventory/components/CollectorBaseInfoSection.vue
apps/web/src/services/asset-inventory/components/CollectorCreateStep1SearchFilter.vue
apps/web/src/services/asset-inventory/components/CollectorFormOptions.vue
apps/web/src/services/asset-inventory/stores/collector-form-store.ts
apps/web/src/services/project/components/ProjectAlertWebhookAddModal.vue
apps/web/src/store/modules/reference/plugin/actions.ts

fix: apply repository and plugin v2 api

---

apps/web/src/App.vue
apps/web/src/common/modules/navigations/gnb/GNB.vue
apps/web/src/store/modules/user/getters.ts

fix(gnb): solve workspace-member gnb issue & refactor script setup in gnb

---

apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
apps/web/src/services/dashboards/pages/admin/AdminDashboardMainPage.vue
apps/web/src/store/dashboard/dashboard-store.ts

fix: fix search bug in dashboard main page

---

apps/web/src/schema/identity/role-binding/api-verbs/create.ts
apps/web/src/services/administration/components/UserManagementAddModal.vue
apps/web/src/services/administration/components/UserManagementAddRole.vue
apps/web/src/services/administration/components/UserManagementAddUser.vue
apps/web/src/services/administration/components/UserManagementTab.vue
apps/web/src/services/administration/components/UserManagementTabDetail.vue
apps/web/src/services/administration/components/UserManagementTable.vue
apps/web/src/services/administration/store/user-page-store.ts
apps/web/src/services/administration/types/user-type.ts

refactor: modify user mode tab data and fix bug

---

apps/web/src/common/modules/project/ProjectSelectDropdown.vue
apps/web/src/services/project/components/ProjectMainCardList.vue
apps/web/src/services/project/components/ProjectMemberTab.vue
apps/web/src/store/reference/project-reference-store.ts

fix: fix minor bug

---

apps/web/src/services/dashboards/DashboardsLNB.vue
apps/web/src/services/project/pages/ProjectTagPage.vue

fix: fix minor

---

apps/web/src/schema/identity/provider/model.ts
apps/web/src/schema/monitoring/alert/api-verbs/assign-user.ts
apps/web/src/schema/monitoring/alert/api-verbs/create.ts
apps/web/src/schema/monitoring/alert/api-verbs/delete.ts
apps/web/src/schema/monitoring/alert/api-verbs/get.ts
apps/web/src/schema/monitoring/alert/api-verbs/update-state.ts
apps/web/src/schema/monitoring/alert/api-verbs/update.ts
apps/web/src/schema/monitoring/project-alert-config/api-verbs/create.ts
apps/web/src/schema/monitoring/project-alert-config/api-verbs/delete.ts
apps/web/src/schema/monitoring/project-alert-config/api-verbs/get.ts
apps/web/src/schema/monitoring/project-alert-config/api-verbs/list.ts
apps/web/src/schema/monitoring/project-alert-config/api-verbs/update.ts
apps/web/src/schema/monitoring/project-alert-config/model.ts
apps/web/src/schema/monitoring/project-alert-config/type.ts
apps/web/src/services/alert-manager/components/AlertMainAlertCreateModal.vue
apps/web/src/services/project/pages/ProjectAlertPage.vue
packages/mirinae/src/hooks/context-menu-fixed-style/index.ts

fix: use api v2 for project alert config create at project alert page

---

apps/web/src/common/modules/navigations/gnb/GNB.vue
apps/web/src/common/modules/navigations/gnb/MyPageGNB.vue
apps/web/src/common/modules/navigations/gnb/modules/MyPageGNBHeader.vue
apps/web/src/common/modules/navigations/gnb/modules/MyPageGNBToolset.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-profile/GNBProfile.vue
apps/web/src/store/modules/user/actions.ts
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

refactor(my-page-gnb): apply design & handle gnb by role type

---

apps/web/src/services/administration/components/DomainSettingsBaseInformation.vue
apps/web/src/services/administration/components/DomainSettingsBrandAssets.vue
apps/web/src/services/administration/components/DomainSettingsChangeAdminEmailModal.vue
apps/web/src/services/administration/components/DomainSettingsTimezoneAndLanguage.vue
apps/web/src/services/administration/pages/admin/AdminDomainSettingsPage.vue
apps/web/src/store/domain-config/domain-config-store.ts
apps/web/src/store/domain-settings/domain-settings-store.ts
apps/web/src/store/modules/domain/type.ts

fix: fix api request of domain-config & set initial value of domain config

---

apps/web/src/services/project/components/ProjectAlertWebhookAddModal.vue
apps/web/src/services/project/components/ProjectAlertWebhookUpdateModal.vue
apps/web/src/services/project/pages/ProjectWebhookPage.vue
apps/web/src/store/modules/reference/webhook/actions.ts

fix: fix i18n bug in ProjectWebhookPage & change monitoring/webhook api to v2

---

apps/web/src/store/modules/domain/type.ts

fix: fix domain config name for domain settings

---

apps/web/src/schema/inventory/collector/api-verbs/create.ts
apps/web/src/services/asset-inventory/components/CollectorCreateStep4.vue
apps/web/src/services/asset-inventory/components/CollectorMainContentItem.vue
apps/web/src/services/asset-inventory/components/CollectorMainContents.vue
apps/web/src/services/asset-inventory/components/CollectorMainItemSchedule.vue
apps/web/src/services/asset-inventory/components/CollectorMainScheduleModal.vue
apps/web/src/services/asset-inventory/pages/CollectorMainPage.vue
apps/web/src/services/asset-inventory/pages/ServiceAccountDetailPage.vue
apps/web/src/services/asset-inventory/stores/collector-page-store.ts
apps/web/src/services/asset-inventory/types/collector-main-page-type.ts

refactor(collector-page-store): modify to setup store(pinia) & fix minor bug

---

apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue
apps/web/src/store/modules/user/getters.ts

SSIA
WorkspaceMember can't create trustedAccount.

feat(service-account): apply access permission of workspace member case

---

apps/web/src/schema/identity/app/api-verbs/create.ts
apps/web/src/services/administration/components/AppManagementFormModal.vue
apps/web/src/services/administration/components/AppManagementStatusModal.vue
apps/web/src/services/administration/components/AppManagementTable.vue
apps/web/src/services/administration/components/UserManagementAddAdminRole.vue
apps/web/src/services/administration/components/UserManagementAddRole.vue
apps/web/src/services/administration/components/UserManagementAddUser.vue
apps/web/src/services/administration/components/UserManagementTabProjects.vue
apps/web/src/services/administration/components/UserManagementTabWorkspace.vue
apps/web/src/services/administration/components/UserManagementTable.vue
apps/web/src/services/administration/constants/app-constant.ts
apps/web/src/services/administration/pages/AppMainPage.vue
apps/web/src/services/administration/store/app-page-store.ts
apps/web/src/services/administration/store/user-page-store.ts

refactor: minor bug fix at app page

---

apps/web/src/schema/cost-analysis/budget/api-verbs/create.ts
apps/web/src/schema/cost-analysis/budget/api-verbs/delete.ts
apps/web/src/schema/cost-analysis/budget/api-verbs/get.ts
apps/web/src/schema/cost-analysis/budget/api-verbs/list.ts
apps/web/src/schema/cost-analysis/budget/api-verbs/set-notification.ts
apps/web/src/schema/cost-analysis/budget/api-verbs/stat.ts
apps/web/src/schema/cost-analysis/budget/api-verbs/update.ts
apps/web/src/schema/cost-analysis/budget/model.ts
apps/web/src/schema/cost-analysis/budget/type.ts
apps/web/src/schema/cost-analysis/cost/api-verbs/analyze.ts
apps/web/src/schema/cost-analysis/cost/api-verbs/create.ts
apps/web/src/schema/cost-analysis/cost/api-verbs/delete.ts
apps/web/src/schema/cost-analysis/cost/api-verbs/get.ts
apps/web/src/schema/cost-analysis/cost/api-verbs/list.ts
apps/web/src/schema/cost-analysis/cost/api-verbs/stat.ts
apps/web/src/schema/cost-analysis/cost/model.ts

feat: add Budget, Cost schema

---

apps/web/src/lib/variable-models/_base/resource-name-variable-model.ts
apps/web/src/lib/variable-models/managed/project-variable-model.ts

feat: get project group in project-variable-model

---

apps/web/src/services/administration/components/UserManagementFormModal.vue
apps/web/src/services/administration/components/UserManagementTab.vue
apps/web/src/services/administration/components/UserManagementTabDetail.vue
apps/web/src/services/administration/components/UserManagementTable.vue
apps/web/src/services/administration/components/user-management-form-admin-role.vue
apps/web/src/services/administration/pages/UserMainPage.vue
apps/web/src/services/administration/store/user-page-store.ts

refactor: modify table and update form, tap api

---

apps/web/src/lib/site-initializer/domain-settings.ts
apps/web/src/lib/site-initializer/index.ts
apps/web/src/schema/cost-analysis/budget-usage/api-verbs/analyze.ts
apps/web/src/services/auth/components/SignInContainer.vue
apps/web/src/services/auth/components/SignInLeftContainer.vue
apps/web/src/store/modules/domain/actions.ts
apps/web/src/store/modules/domain/index.ts
apps/web/src/store/modules/domain/mutations.ts
apps/web/src/store/modules/domain/type.ts

Customize whatever you want!!!!!!! 💗

feat: add `config` state to domain vuex store & add `initDomainSettings` to site-initializer

---

apps/web/src/common/modules/modals/notification-email-modal/NotificationEmailModal.vue
apps/web/src/lib/helper/multi-factor-auth-helper.ts
apps/web/src/lib/helper/verify-email-helper.ts
apps/web/src/schema/identity/user-profile/api-verbs/confirm-email.ts
apps/web/src/schema/identity/user-profile/api-verbs/confirm-mfa.ts
apps/web/src/schema/identity/user-profile/api-verbs/disable-mfa.ts
apps/web/src/schema/identity/user-profile/api-verbs/enable-mfa.ts
apps/web/src/schema/identity/user-profile/api-verbs/get-workspaces.ts
apps/web/src/schema/identity/user-profile/api-verbs/update.ts
apps/web/src/schema/identity/user-profile/api-verbs/verify-email.ts
apps/web/src/schema/identity/user/api-verbs/disable-mfa.ts
apps/web/src/schema/identity/user/api-verbs/get-workspaces.ts
apps/web/src/schema/identity/user/api-verbs/verify-email.ts
apps/web/src/services/administration/components/UserManagementFormNotificationEmailForm.vue
apps/web/src/services/administration/components/UserManagementTabDetail.vue
apps/web/src/services/my-page/components/UserAccountMultiFactorAuth.vue
apps/web/src/services/my-page/components/UserAccountMultiFactorAuthModal.vue
apps/web/src/services/my-page/components/UserAccountMultiFactorAuthModalEmailInfo.vue
apps/web/src/services/my-page/components/UserAccountMultiFactorAuthModalFolding.vue
apps/web/src/services/my-page/components/UserAccountNotificationEmail.vue
apps/web/src/store/modules/user/actions.ts

feat: apply user profile API

---

apps/web/src/services/administration/components/UserManagementAddModal.vue
apps/web/src/services/administration/components/UserManagementAddUser.vue
apps/web/src/services/administration/components/UserManagementFormAdminRole.vue
apps/web/src/services/administration/components/UserManagementFormModal.vue
apps/web/src/services/administration/components/UserManagementTabWorkspace.vue
apps/web/src/services/administration/components/UserManagementTable.vue
apps/web/src/services/administration/store/user-page-store.ts

feat: reflect planning and bug fix updates

---

apps/web/src/services/cost-explorer/components/BudgetDetailDeleteModal.vue
apps/web/src/services/cost-explorer/components/BudgetDetailInfo.vue
apps/web/src/services/cost-explorer/components/BudgetDetailInfoAmountPlanningTypePopover.vue
packages/mirinae/src/feedbacks/modals/advanced/double-check-modal/PDoubleCheckModal.vue

refactor: refactor minor things in budget components

---

apps/web/src/lib/access-control/page-access-permission-helper.ts

fix(page-access): solve issue in usePageAccessDefinitionTableData helper

---

apps/web/src/schema/notification/protocol/api-verbs/create.ts
apps/web/src/schema/notification/protocol/api-verbs/delete.ts
apps/web/src/schema/notification/protocol/api-verbs/disable.ts
apps/web/src/schema/notification/protocol/api-verbs/enable.ts
apps/web/src/schema/notification/protocol/api-verbs/get.ts
apps/web/src/schema/notification/protocol/api-verbs/list.ts
apps/web/src/schema/notification/protocol/api-verbs/update-plugin.ts
apps/web/src/schema/notification/protocol/api-verbs/update.ts
apps/web/src/schema/notification/protocol/model.ts
apps/web/src/schema/notification/protocol/type.ts

feat: remove additional responder, project dependency from event rule

---

apps/web/src/services/my-page/components/UserAccountChangePassword.vue

fix(change-password): apply identity v2

---

apps/web/src/services/administration/components/RoleDeleteModal.vue
apps/web/src/services/administration/components/RoleManagementTab.vue
apps/web/src/services/administration/components/RoleManagementTabDetail.vue
apps/web/src/services/administration/components/RoleManagementTable.vue
apps/web/src/services/administration/components/RoleUpdateForm.vue
apps/web/src/services/administration/components/RoleUpdateFormAccess.vue
apps/web/src/services/administration/components/RoleUpdateFormAccessMenuItem.vue
apps/web/src/services/administration/components/RoleUpdateFormPermissionForm.vue
apps/web/src/services/administration/components/RoleUpdateFormPolicy.vue
apps/web/src/services/administration/composables/page-access-definition-table-data.ts
apps/web/src/services/administration/constants/role-constant.ts
apps/web/src/services/administration/helpers/role-page-permission-helper.ts
apps/web/src/services/administration/pages/admin/RoleCreatePage.vue
apps/web/src/services/administration/pages/admin/RoleUpdatePage.vue
apps/web/src/services/administration/store/role-page-store.ts
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

refactor: reapply data in tabs and create function

---

apps/web/src/services/asset-inventory/components/CollectorDetailAttachedServiceAccounts.vue
apps/web/src/services/asset-inventory/components/CollectorDetailScheduleSection.vue
apps/web/src/services/asset-inventory/components/CollectorDetailServiceAccountsSection.vue
apps/web/src/services/asset-inventory/components/CollectorFormAttachedServiceAccount.vue
apps/web/src/services/asset-inventory/pages/CollectorDetailPage.vue
apps/web/src/services/asset-inventory/stores/collector-detail-page-store.ts

fix(collector): update to v2 api params (related to secret)

---

apps/storybook/package.json
apps/web/package.json
package-lock.json
packages/mirinae/package.json

https://github.com/vuejs/vue/pull/13070
Users who are in the process of migrating to Vue 3 and are utilizing Pinia are in need of a crucial update. This update aims to restore the proper functionality of Pinia getters that were not working correctly.

feat: update vue version(2.7.14 -> 2.7.15)

---

packages/core-lib/src/space-connector/helper.ts
packages/core-lib/src/space-connector/type.ts

feat(core-lib): update sort spec for api query helper

---

apps/web/src/lib/site-initializer/user-auth.ts

feat: set timezone, language when init user in site-inistializer

---

apps/web/src/schema/cost-analysis/budget-usage/api-verbs/list.ts
apps/web/src/services/cost-explorer/components/BudgetCreateForm.vue
apps/web/src/services/cost-explorer/components/BudgetDetailDeleteModal.vue
apps/web/src/services/cost-explorer/components/BudgetMainList.vue
apps/web/src/services/cost-explorer/components/BudgetMainListCard.vue
apps/web/src/services/cost-explorer/helpers/budget-usage-analyze-api-query-helper.ts
apps/web/src/services/cost-explorer/stores/budget-detail-page-store.ts

fix: fix budget/create api request parameters & fix budget-usage/analyze request query

---

apps/web/src/common/modules/navigations/gnb/modules/gnb-profile/GNBProfile.vue
apps/web/src/router/index.ts
apps/web/src/store/app-context/app-context-store.ts
apps/web/src/store/modules/user/actions.ts
apps/web/src/store/modules/user/getters.ts
apps/web/src/store/reference/all-reference-store.ts
apps/web/src/store/reference/user-reference-store.ts
apps/web/src/store/reference/workspace-reference-store.ts

fix(grant-role&reference): refactor grant role & apply reference load

---

apps/web/src/common/modules/project/ProjectSelectDropdown.vue
apps/web/src/schema/monitoring/alert/api-verbs/update.ts
apps/web/src/services/alert-manager/components/AlertDetailInfoTableProject.vue
apps/web/src/services/alert-manager/components/AlertDetailSummaryAssignModal.vue
apps/web/src/services/alert-manager/components/AlertMainAcknowledgeModal.vue
apps/web/src/services/alert-manager/components/AlertMainDataTable.vue
apps/web/src/services/alert-manager/components/AlertMainDataTableActions.vue
apps/web/src/services/alert-manager/components/AlertMainResolveModal.vue
apps/web/src/services/alert-manager/components/EscalationPolicyDataTable.vue
apps/web/src/services/alert-manager/components/EscalationPolicyForm.vue
apps/web/src/services/alert-manager/components/EscalationPolicyFormRulesInput.vue
apps/web/src/services/alert-manager/composables/alert-info.ts
apps/web/src/services/alert-manager/helpers/alert-badge-helper.ts
apps/web/src/services/alert-manager/stores/alert-page-store.ts
apps/web/src/services/cost-explorer/components/BudgetMainList.vue
apps/web/src/services/project/components/ProjectAlertSettingsEscalationPolicyChangeModal.vue
apps/web/src/services/project/components/ProjectMainProjectTree.vue
apps/web/src/services/project/composables/use-project-tree.ts
apps/web/src/store/reference/all-reference-store.ts
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

fix: fix alert bugs

---

apps/web/src/router/index.ts
apps/web/src/store/app-context/app-context-store.ts
apps/web/src/store/index.ts
apps/web/src/store/modules/reference/actions.ts
apps/web/src/store/modules/reference/index.ts

SSIA
`app-context-store` -> `router/index`

fix(load-reference): refactor load reference by granted role

---

apps/web/src/services/cost-explorer/constants/managed-cost-analysis-query-sets.ts
apps/web/src/services/cost-explorer/routes/admin/routes.ts
apps/web/src/store/reference/all-reference-store.ts
apps/web/src/store/reference/project-reference-store.ts

fix: revive snake_case ReferenceType & add users data in project-reference-store `sync()`

---

apps/web/src/common/modules/navigations/gnb/GNB.vue
apps/web/src/schema/identity/domain/api-verbs/get-auth-info.ts
apps/web/src/store/modules/domain/actions.ts
apps/web/src/store/modules/domain/getters.ts

feat: get 'console:ext-menu' from `domain/get-auth-info`

---

apps/web/src/services/cost-explorer/stores/cost-analysis-page-store.ts
apps/web/src/services/home-dashboard/components/CollectingProgress.vue
apps/web/src/services/home-dashboard/components/PersonalHealthDashboard.vue
apps/web/src/services/home-dashboard/components/TopProjects.vue
apps/web/src/services/home-dashboard/components/TrustedAdvisor.vue

fix: fix CollectingProgress widget in Home Dashboard & fix bug by calling vuex store (project)

---

apps/web/src/store/reference/project-group-reference-store.ts
apps/web/src/store/reference/project-reference-store.ts
apps/web/src/store/reference/user-reference-store.ts
apps/web/src/store/reference/workspace-reference-store.ts

fix: init `lastLoadedTime` when flush reference stores

---

apps/web/src/schema/inventory/cloud-service-query-set/api-verbs/list.ts
apps/web/src/schema/inventory/cloud-service-query-set/model.ts
apps/web/src/schema/inventory/cloud-service-query-set/type.ts
apps/web/src/schema/inventory/cloud-service-stats/api-verbs/analyze.ts
apps/web/src/schema/inventory/cloud-service-stats/api-verbs/list.ts
apps/web/src/schema/inventory/cloud-service-stats/api-verbs/stat.ts
apps/web/src/schema/inventory/cloud-service-stats/model.ts
apps/web/src/services/asset-inventory/components/CloudServiceDetail.vue
apps/web/src/services/asset-inventory/components/CloudServiceDetailMultipleSelectedData.vue
apps/web/src/services/asset-inventory/components/CloudServiceTagsPanel.vue
apps/web/src/services/asset-inventory/components/CloudServiceToolbox.vue
apps/web/src/services/asset-inventory/components/CloudServiceUsageOverview.vue
apps/web/src/services/asset-inventory/components/CollectorDetailOptionsSection.vue
apps/web/src/services/asset-inventory/components/CollectorFormSchedule.vue
apps/web/src/services/asset-inventory/pages/CloudServiceDetailPage.vue
apps/web/src/services/asset-inventory/pages/CloudServicePage.vue
apps/web/src/services/asset-inventory/pages/CollectorDetailPage.vue
apps/web/src/services/dashboards/widgets/asset-widgets/compliance-status/ComplianceStatusWidget.vue
apps/web/src/services/dashboards/widgets/asset-widgets/severity-status-by-service/SeverityStatusByServiceWidget.vue
apps/web/src/services/dashboards/widgets/asset-widgets/total-fail-findings-status/TotalFailFindingsStatusWidget.vue
apps/web/src/services/dashboards/widgets/base-widgets/base-count-of-findings/BaseCountOfFindingsWidget.vue
apps/web/src/services/home-dashboard/components/CollectingProgress.vue
apps/web/src/services/project/components/ProjectMainCardList.vue

feat: add api schema (cloudSerivceStats, cloudServiceQuerySet) & apply api fetcher type

---

apps/web/src/schema/inventory/change-history/model.ts
apps/web/src/schema/inventory/job-task/api-verbs/list.ts
apps/web/src/schema/inventory/job-task/model.ts
apps/web/src/schema/inventory/job/type.ts
apps/web/src/services/asset-inventory/components/CloudServiceHistory.vue
apps/web/src/services/asset-inventory/components/CollectorFormSchedule.vue
apps/web/src/services/asset-inventory/components/CollectorHistoryJobTaskErrorList.vue
apps/web/src/services/asset-inventory/components/CollectorHistoryJobTaskTable.vue
apps/web/src/services/asset-inventory/pages/CollectorHistoryPage.vue
apps/web/src/services/asset-inventory/stores/cloud-service-detail-page-store.ts
apps/web/src/store/modules/reference/cloud-service-type/actions.ts
apps/web/src/store/modules/reference/region/actions.ts

feat(collector): apply v2 api & check collector page API operation

---

apps/web/src/services/asset-inventory/components/CloudServiceToolbox.vue
apps/web/src/services/asset-inventory/pages/CloudServicePage.vue

fix(cloud-service-page): add refresh event

---

apps/web/src/services/asset-inventory/components/ServiceAccountCredentials.vue

fix: fix the service account update bug

---

apps/web/src/services/administration/components/UserManagementAddAdminRole.vue
apps/web/src/services/administration/components/UserManagementAddModal.vue
apps/web/src/services/administration/components/UserManagementTabTag.vue
apps/web/src/services/administration/components/UserManagementTabWorkspace.vue
apps/web/src/services/administration/store/user-page-store.ts

feat: apply update tag at user's tag tab and minor change

---

apps/web/src/services/administration/components/AppManagementFormModal.vue
apps/web/src/services/administration/components/AppManagementTable.vue

refactor: changed item state at api key create modal

---

apps/web/src/lib/helper/multi-factor-auth-helper.ts
apps/web/src/lib/helper/verify-email-helper.ts
apps/web/src/schema/identity/user-profile/api-verbs/confirm-email.ts
apps/web/src/schema/identity/user-profile/api-verbs/confirm-mfa.ts
apps/web/src/schema/identity/user-profile/api-verbs/disable-mfa.ts
apps/web/src/schema/identity/user-profile/api-verbs/enable-mfa.ts
apps/web/src/schema/identity/user-profile/api-verbs/reset-password.ts
apps/web/src/services/auth/pages/PasswordPage.vue

refactor: apply user profile api at reset password

---

apps/web/src/common/modules/navigations/gnb/modules/gnb-profile/GNBProfile.vue
apps/web/src/services/my-page/components/UserAccountBaseInformation.vue
apps/web/src/store/modules/user/getters.ts
apps/web/src/store/modules/user/index.ts
apps/web/src/store/modules/user/mutations.ts
apps/web/src/store/modules/user/type.ts

fix(user-role): update user-role by new role

---

apps/web/src/router/index.ts

fix(gnb-issue): solve gnb menu issue in admin to workspace case

---

apps/web/src/common/modules/navigations/gnb/GNB.vue
apps/web/src/common/modules/navigations/gnb/modules/GNBHeader.vue

fix(gnb): apply changed design

---

apps/web/src/services/cost-explorer/components/BudgetDetailHeading.vue
apps/web/src/services/cost-explorer/components/BudgetDetailInfo.vue
apps/web/src/services/cost-explorer/pages/BudgetMainPage.vue
apps/web/src/services/dashboards/pages/DashboardsMainPage.vue

feat(budget, dashboard): set page access by role type

---

apps/web/src/common/modules/modals/notification-email-modal/NotificationEmailModal.vue
apps/web/src/lib/helper/multi-factor-auth-helper.ts
apps/web/src/lib/helper/verify-email-helper.ts
apps/web/src/schema/identity/user-profile/api-verbs/verify-email.ts
apps/web/src/schema/identity/user/api-verbs/disable-mfa.ts
apps/web/src/schema/identity/user/api-verbs/verify-email.ts
apps/web/src/services/administration/components/UserManagementFormModal.vue
apps/web/src/services/administration/components/UserManagementFormMultiFactorAuth.vue
apps/web/src/services/administration/components/UserManagementFormNotificationEmailForm.vue
apps/web/src/services/administration/components/UserManagementTabDetail.vue
apps/web/src/services/my-page/components/UserAccountMultiFactorAuthModalEmailInfo.vue
apps/web/src/services/my-page/components/UserAccountMultiFactorAuthModalFolding.vue
apps/web/src/services/my-page/components/UserAccountNotificationEmail.vue

chore: separate user and user profile API

---

apps/web/src/schema/inventory/note/api-verbs/create.ts
apps/web/src/schema/inventory/note/api-verbs/delete.ts
apps/web/src/schema/inventory/note/api-verbs/list.ts
apps/web/src/schema/inventory/note/api-verbs/stat.ts
apps/web/src/schema/inventory/note/api-verbs/update.ts
apps/web/src/schema/inventory/note/model.ts
apps/web/src/services/asset-inventory/components/CloudServiceHistory.vue
apps/web/src/services/asset-inventory/components/CloudServiceHistoryDetailNoteTab.vue

feat: update api params of Note service

---

apps/web/src/common/modules/navigations/gnb/modules/GNBAdminToggleButton.vue
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

fix(admin-toggle): apply toast message

---

apps/web/src/common/modules/navigations/gnb/modules/gnb-noti/GNBNoti.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-profile/GNBProfile.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-recent-favorite/GNBRecentFavorite.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-search/modules/GNBSearchDropdown.vue

fix(gnb-toolsets): apply design changes

---

apps/web/src/schema/cost-analysis/data-source/model.ts
apps/web/src/services/cost-explorer/components/BudgetCreateDataSourceSelect.vue
apps/web/src/services/cost-explorer/components/BudgetCreateFormAmountPlan.vue
apps/web/src/services/cost-explorer/components/BudgetCreateFormAmountPlanAutofillModal.vue
apps/web/src/services/cost-explorer/components/BudgetCreateFormAmountPlanMonthly.vue
apps/web/src/services/cost-explorer/components/BudgetCreateFormAmountPlanTotal.vue
apps/web/src/services/cost-explorer/components/BudgetCreateFormBaseInfo.vue
apps/web/src/services/cost-explorer/components/BudgetMainList.vue
apps/web/src/services/cost-explorer/components/BudgetMainToolbox.vue
apps/web/src/store/reference/cost-data-source-reference-store.ts

fix: fix sort bug in budget page & in admin mode, set data source items after selecting target

---

apps/web/src/common/modules/widgets/DailyUpdates.vue
apps/web/src/services/administration/components/WorkspaceManagementTable.vue
apps/web/src/services/administration/constants/workspace-constant.ts
apps/web/src/services/asset-inventory/components/CloudServiceUsageOverviewDetailModal.vue
apps/web/src/services/asset-inventory/components/CloudServiceUsageOverviewSummary.vue
apps/web/src/services/cost-explorer/components/BudgetCreateDataSourceSelect.vue
apps/web/src/services/cost-explorer/components/BudgetCreateFormBaseInfo.vue
apps/web/src/services/cost-explorer/components/BudgetDetailInfo.vue
apps/web/src/services/home-dashboard/components/CollectingProgress.vue
apps/web/src/services/home-dashboard/components/PersonalHealthDashboard.vue
apps/web/src/services/home-dashboard/pages/HomeDashboardPage.vue
apps/web/src/services/total-dashboard/TotalDashboardPage.vue
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

fix: fix minor bugs in home dashboard widgets

---

apps/web/src/router/integral-routes.ts

fix(root-route): solve access-to-'/' issue

---

apps/web/src/services/administration/components/UserManagementAddModal.vue
apps/web/src/services/administration/components/UserManagementAddUser.vue
apps/web/src/services/administration/components/WorkspacesCreateModal.vue
apps/web/src/services/administration/pages/admin/AdminWorkspacesPage.vue
apps/web/src/services/administration/store/user-page-store.ts

fix(workspace-invite): apply user invite after workspace created

---

apps/web/src/common/modules/monitoring/Monitoring.vue
apps/web/src/common/modules/monitoring/config.ts
apps/web/src/schema/monitoring/data-source/api-verbs/list.ts
apps/web/src/schema/monitoring/data-source/constant.ts
apps/web/src/schema/monitoring/data-source/model.ts
apps/web/src/schema/monitoring/data-source/type.ts
apps/web/src/schema/monitoring/log/api-verbs/list.ts
apps/web/src/schema/monitoring/log/model.ts
apps/web/src/schema/repository/plugin/type.ts
apps/web/src/services/asset-inventory/components/CloudServiceLogTab.vue

feat: add  monitoring schema(log, data-source) & update api params

---

apps/web/src/common/components/editor/extensions/image/type.ts
apps/web/src/common/composables/file-attachments/index.ts
apps/web/src/common/composables/file-uploader/index.ts
apps/web/src/common/modules/popup/notice/modules/NoticePopupItem.vue
apps/web/src/lib/file-manager/index.ts
apps/web/src/lib/file-manager/type.ts
apps/web/src/schema/board/post/model.ts
apps/web/src/schema/file-manager/api-verbs/add.ts
apps/web/src/schema/file-manager/api-verbs/delete.ts
apps/web/src/schema/file-manager/api-verbs/get-download-url.ts
apps/web/src/schema/file-manager/api-verbs/get.ts
apps/web/src/schema/file-manager/api-verbs/list.ts
apps/web/src/schema/file-manager/api-verbs/update.ts
apps/web/src/schema/file-manager/model.ts
apps/web/src/schema/file-manager/type.ts
apps/web/src/services/info/components/NoticeDetail.vue
apps/web/src/services/info/components/NoticeForm.vue
apps/web/src/services/info/pages/admin/AdminNoticeMainPage.vue

feat: remove system role related features from notice and apply api v2 to file manager api

---

apps/web/src/schema/cost-analysis/data-source/api-verbs/list.ts
apps/web/src/schema/cost-analysis/data-source/constant.ts
apps/web/src/schema/cost-analysis/data-source/model.ts
apps/web/src/schema/cost-analysis/data-source/type.ts
apps/web/src/schema/inventory/cloud-service-query-set/api-verbs/list.ts
apps/web/src/services/cost-explorer/components/BudgetCreateDataSourceSelect.vue
apps/web/src/services/cost-explorer/components/BudgetCreateFormAmountPlanMonthly.vue
apps/web/src/services/cost-explorer/components/BudgetCreateFormAmountPlanTotal.vue
apps/web/src/store/reference/cloue-service-query-set-reference-store.ts
apps/web/src/store/reference/cost-data-source-reference-store.ts

fix: init `lastLoadedTime` when `flush()` & update `CloudServiceQuerySetModel`

---

apps/web/src/services/auth/authenticator/index.ts
apps/web/src/store/modules/user/actions.ts
apps/web/src/store/modules/user/getters.ts

fix(page-access-permission): solve no-role issue

---

apps/web/src/common/modules/popup/notice/NoticePopup.vue
apps/web/src/common/modules/popup/notice/modules/NoticePopupItem.vue
apps/web/src/services/info/components/NoticeForm.vue
apps/web/src/services/info/components/NoticeListItem.vue
apps/web/src/services/info/pages/admin/AdminNoticeCreatePage.vue

refactor: change to script setup

---

apps/web/src/schema/inventory/region/api-verbs/list.ts
apps/web/src/schema/inventory/region/model.ts
apps/web/src/services/my-page/components/UserAccountBaseInformation.vue
apps/web/src/store/modules/reference/provider/actions.ts
apps/web/src/store/modules/reference/region/actions.ts
apps/web/src/store/modules/reference/secret/actions.ts
apps/web/src/store/modules/reference/service-account/actions.ts
apps/web/src/store/modules/user/getters.ts

fix: add defense code for no data in reference stores

---

apps/web/src/services/info/components/NoticeDetail.vue
apps/web/src/services/info/components/NoticeForm.vue
apps/web/src/services/info/components/NoticeList.vue
apps/web/src/services/info/components/NoticeListItem.vue
apps/web/src/services/info/pages/admin/AdminNoticeCreatePage.vue
apps/web/src/services/info/stores/notice-detail-store.ts
packages/mirinae/src/feedbacks/loading/data-loader/PDataLoader.vue

fix: apply loader to notice (css, ux issue) & remove state data in post create page

---

apps/web/src/services/auth/components/SignInContainer.vue
apps/web/src/store/modules/reference/actions.ts

solve [this](https://pyengine.atlassian.net/browse/QA-946)

fix: fix wordType logo bug in SignIn page

---

apps/web/src/App.vue
apps/web/src/common/components/modals/HasNoWorkspaceModal.vue
apps/web/src/services/administration/pages/admin/AdminWorkspacesPage.vue
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

fix(create-workspace): handle no workspace case with has no workspace modal

---

apps/web/src/App.vue
apps/web/src/services/administration/pages/admin/AdminWorkspacesPage.vue

fix(create-modal): handle issue after first workspace created

---

apps/web/src/services/administration/components/WorkspaceManagementTable.vue
apps/web/src/services/administration/components/WorkspacesSetEnableModal.vue
apps/web/src/store/app-context/workspace/workspace-store.ts
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat(workspace-enable): create workspaces enable

---

apps/web/src/App.vue
apps/web/src/common/composables/file-uploader/index.ts
apps/web/src/common/modules/navigations/gnb/MyPageGNB.vue
apps/web/src/common/modules/navigations/gnb/modules/GNBAdminToggleButton.vue
apps/web/src/common/modules/navigations/gnb/modules/GNBHeader.vue
apps/web/src/common/modules/navigations/gnb/modules/MyPageGNBToolset.vue
apps/web/src/lib/site-initializer/workspace.ts
apps/web/src/router/integral-routes.ts
apps/web/src/services/administration/pages/admin/AdminWorkspacesPage.vue
apps/web/src/services/auth/authenticator/index.ts
apps/web/src/services/auth/pages/KB_SSOPage.vue
apps/web/src/services/auth/pages/MultiFactorAuthPage.vue
apps/web/src/services/auth/pages/SignInPage.vue
apps/web/src/services/home-dashboard/pages/HomeDashboardPage.vue
apps/web/src/store/app-context/app-context-store.ts
apps/web/src/store/app-context/workspace/user-workspace-store.ts
apps/web/src/store/dashboard/dashboard-store.ts
apps/web/src/store/modules/display/getters.ts

refactor: edit workspace store name

---

apps/web/src/lib/helper/multi-factor-auth-helper.ts
apps/web/src/services/administration/components/UserManagementAddAdminRole.vue
apps/web/src/services/administration/components/UserManagementFormModal.vue
apps/web/src/services/administration/components/UserManagementTable.vue

chore: fixed minor bug

---

apps/web/src/services/administration/components/RoleUpdateFormBaseInformation.vue
apps/web/src/services/administration/components/UserManagementFormInfoForm.vue

chore: fixed css

---

apps/web/src/schema/monitoring/alert/api-verbs/update.ts
apps/web/src/schema/monitoring/data-source/model.ts
apps/web/src/schema/monitoring/escalation-policy/api-verbs/list.ts
apps/web/src/schema/monitoring/escalation-policy/model.ts
apps/web/src/schema/monitoring/escalation-policy/type.ts
apps/web/src/schema/monitoring/event-rule/api-verbs/create.ts
apps/web/src/schema/monitoring/event-rule/api-verbs/list.ts
apps/web/src/schema/monitoring/event-rule/model.ts
apps/web/src/schema/monitoring/event-rule/type.ts
apps/web/src/schema/monitoring/log/api-verbs/list.ts
apps/web/src/schema/monitoring/log/model.ts
apps/web/src/services/alert-manager/components/EscalationPolicyDataTable.vue
apps/web/src/services/alert-manager/components/EscalationPolicyForm.vue
apps/web/src/services/alert-manager/components/EscalationPolicyFormRulesInput.vue
apps/web/src/services/alert-manager/composables/alert-info.ts
apps/web/src/services/alert-manager/helpers/alert-badge-helper.ts
apps/web/src/services/alert-manager/pages/EscalationPolicyPage.vue
apps/web/src/services/alert-manager/stores/escalation-policy-form-store.ts
apps/web/src/services/project/pages/ProjectAlertSettingsPage.vue

feat: update api schema of monitoring

---

apps/web/src/services/asset-inventory/pages/ServiceAccountDetailPage.vue

fix: fix provider external link bug

---

apps/web/src/services/asset-inventory/pages/ServiceAccountDetailPage.vue

fix: fix routing bug in serviceAccountDetailPage

---

apps/web/src/common/modules/navigations/gnb/modules/gnb-profile/GNBProfile.vue

SSIA
[QA-974](https://pyengine.atlassian.net/browse/QA-974)

fix: change showing roleType in profile

---

apps/web/src/services/auth/components/SignInContainer.vue
apps/web/src/services/auth/components/SignInLeftContainer.vue

Fix [this](https://pyengine.atlassian.net/browse/QA-960)

feat: set symbol image to signIn page

---

apps/web/src/services/asset-inventory/components/CollectorMainContents.vue
apps/web/src/services/asset-inventory/types/collector-main-page-type.ts

fix: fix the DOMAIN collector UI bug

---

apps/web/src/services/administration/components/WorkspaceManagementTable.vue
apps/web/src/services/cost-explorer/components/BudgetMainList.vue

fix [excel export bug](https://pyengine.atlassian.net/browse/QA-963)

fix: fix excel export error

---

apps/web/src/common/modules/portals/TopNotification.vue
apps/web/src/store/modules/user/getters.ts
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

SSIA
[QA-972](https://pyengine.atlassian.net/browse/QA-972)

fix: solve wrong top noti case

---

apps/web/src/common/modules/navigations/gnb/GNB.vue

SSIA
[QA-969](https://pyengine.atlassian.net/browse/QA-969)

fix: add defensive code at GNB invisibleMenu

---

apps/web/src/common/modules/navigations/gnb/GNB.vue
apps/web/src/common/modules/navigations/gnb/modules/GNBHeader.vue

SSIA
[QA-953](https://pyengine.atlassian.net/browse/QA-953)

fix: solve gnb early rendering issue

---

apps/web/src/lib/access-control/config.ts
apps/web/src/lib/access-control/page-access-helper.ts
apps/web/src/store/modules/user/getters.ts

SSIA
[QA-970](https://pyengine.atlassian.net/browse/QA-970)

fix: refactor minimal page access

---

apps/web/src/common/modules/navigations/gnb/modules/GNBAdminToggleButton.vue
apps/web/src/common/modules/navigations/gnb/modules/GNBToolset.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-profile/GNBProfile.vue

SSIA
[QA-961](https://pyengine.atlassian.net/browse/QA-961)

fix: apply changed gnb design

---

apps/web/src/services/asset-inventory/helpers/dynamic-ui-schema-generator/index.ts
apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue

[QA ticket
](https://pyengine.atlassian.net/browse/QA-990)

fix(service-account-main-page): fix the data loading bug

---

apps/web/src/common/modules/custom-table/custom-field-modal/CustomFieldModal.vue
apps/web/src/services/asset-inventory/components/ServiceAccountBaseInformationDetail.vue
apps/web/src/services/asset-inventory/helpers/dynamic-ui-schema-generator/dynamic-layout-schema-template.ts
apps/web/src/services/asset-inventory/helpers/dynamic-ui-schema-generator/index.ts

[QA ticket](https://pyengine.atlassian.net/browse/QA-993)

fix: fix the table, detail schema in serviceAccount

---

apps/web/src/common/modules/project/ProjectSelectDropdown.vue
apps/web/src/services/project/components/ProjectMemberTab.vue
apps/web/src/services/project/pages/ProjectDetailPage.vue

feat: add group move button to project detail page

---

apps/web/src/common/modules/navigations/gnb/modules/GNBHeader.vue
apps/web/src/router/index.ts
apps/web/src/services/dashboards/routes/routes.ts

SSIA
[QA-1018](https://pyengine.atlassian.net/browse/QA-1018)

fix: apply changed workspace toggle scenario

---

apps/web/src/router/index.ts

To handle new planning...
- User can access directly my page in admin mode.

refactor: refactor admin to admin router case

---

apps/web/src/common/modules/portals/TopNotification.vue
apps/web/src/router/index.ts

fix: create variable for more readable code

---

apps/web/src/lib/helper/verify-email-helper.ts
apps/web/src/services/administration/AdministrationLNB.vue
apps/web/src/services/administration/components/AppManagementStatusModal.vue
apps/web/src/services/administration/components/UserManagementAddAdminRole.vue
apps/web/src/services/administration/components/UserManagementAddModal.vue
apps/web/src/services/administration/components/UserManagementAddRole.vue
apps/web/src/services/administration/components/UserManagementAddTag.vue
apps/web/src/services/administration/components/UserManagementAddUser.vue
apps/web/src/services/administration/components/UserManagementFormAdminRole.vue
apps/web/src/services/my-page/pages/UserAccountPage.vue
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

chore: fixed minor qa issue

---

apps/web/src/schema/identity/workspace/api-verbs/update.ts
apps/web/src/services/administration/components/WorkspaceManagementTable.vue
apps/web/src/services/administration/components/WorkspacesCreateModal.vue
apps/web/src/services/administration/pages/admin/AdminWorkspacesPage.vue
apps/web/src/services/administration/store/workspace-page-store.ts

fix(workspace-edit): create workspace edit & move modals to page from table

---

apps/web/src/services/asset-inventory/pages/CloudServicePage.vue

fix(cloud-service): fix no data routing

---

apps/web/src/services/asset-inventory/components/CollectorBaseInfoSection.vue
apps/web/src/services/asset-inventory/components/CollectorCurrentStatus.vue
apps/web/src/services/asset-inventory/components/CollectorDetailOptionsSection.vue
apps/web/src/services/asset-inventory/components/CollectorDetailScheduleSection.vue
apps/web/src/services/asset-inventory/components/CollectorDetailSectionHeader.vue
apps/web/src/services/asset-inventory/pages/CollectorDetailPage.vue
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

[qa-ticket](https://pyengine.atlassian.net/browse/QA-1009)

fix(collector-detail-page): remove edit,delete button & add detail-job link

---

apps/web/src/router/admin-routes.ts

Hide pages that have not yet been developed.

fix: remove admin mode of asset-inventory

---

apps/web/src/services/asset-inventory/components/CollectorCreateStep3.vue

fix: fix style bug in collector create step3

---

apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
apps/web/src/services/dashboards/stores/widget-form-store.ts
apps/web/src/services/dashboards/widgets/_composables/use-widget/merge-base-widget-state.ts

fix: do not return false in isAllVariablesInitialized

---

apps/web/src/common/composables/breadcrumbs/index.ts
apps/web/src/common/modules/navigations/gnb/modules/gnb-noti/modules/GNBNoticeTab.vue
apps/web/src/services/info/pages/admin/AdminNoticeDetailPage.vue
apps/web/src/services/info/routes/admin/routes.ts
apps/web/src/services/info/routes/routes.ts

fix: fix gnb notice item bug

---

apps/web/src/lib/menu/menu-architecture.ts

fix: temporarily remove menu

---

apps/web/src/common/modules/navigations/gnb/modules/MyPageGNBHeader.vue
apps/web/src/common/modules/navigations/lnb/LNB.vue
apps/web/src/services/my-page/MyPageLNB.vue

SSIA
[QA-1043](https://pyengine.atlassian.net/browse/QA-1043)

fix(my-page): apply changed gnb/lnb design

---

apps/web/src/services/administration/components/RoleManagementTabDetail.vue
apps/web/src/services/administration/components/RoleUpdateFormPolicy.vue
apps/web/src/services/administration/components/UserManagementAddUser.vue
apps/web/src/services/administration/pages/admin/RoleCreatePage.vue
apps/web/src/services/administration/pages/admin/RoleUpdatePage.vue

- [apply icon at page access](https://pyengine.atlassian.net/browse/QA-979)
- hide permission editor (will be updated in the next step.)

feat: apply QA issue at role page

---

apps/web/src/services/administration/pages/admin/AdminWorkspacesPage.vue

SSIA
[QA-952](https://pyengine.atlassian.net/browse/QA-952)

fix(workspace): solve no workspace modal issue

---

apps/web/src/services/cost-explorer/pages/BudgetMainPage.vue
apps/web/src/services/dashboards/DashboardsLNB.vue
apps/web/src/services/dashboards/components/DashboardMainSelectFilter.vue
apps/web/src/services/dashboards/components/DashboardScopeForm.vue
apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
apps/web/src/services/project/components/ProjectMainCardList.vue

fix: fix qa things

---

.github/workflows/dispatch_dev_build.yaml

feat: add dev_build action

---

apps/web/src/services/administration/components/UserManagementAddUser.vue

SSIA
- quest: https://pyengine.atlassian.net/browse/QA-980

fix: fixing automatic ID input error when inviting users

---

apps/web/src/services/cost-explorer/components/BudgetCreateFormAmountPlanMonthly.vue
apps/web/src/services/cost-explorer/components/BudgetCreateFormAmountPlanTotal.vue
apps/web/src/services/cost-explorer/components/BudgetCreateTargetSelect.vue
apps/web/src/services/dashboards/components/DashboardVariableDropdown.vue
apps/web/src/services/dashboards/components/DashboardWidgetContainer.vue
apps/web/src/services/dashboards/components/WidgetViewModeModal.vue
apps/web/src/services/dashboards/pages/DashboardDetailPage.vue

fix(dashboard-variable-dropdown): change event from `update:select` to `select`

---

apps/web/src/services/administration/components/UserManagementTabWorkspace.vue
apps/web/src/services/administration/components/UserManagementTable.vue
apps/web/src/services/administration/composables/refined-table-data.ts
apps/web/src/services/administration/pages/UserMainPage.vue

SSIA
- quest: https://pyengine.atlassian.net/browse/QA-1046

refactor: changed role select dropdown component

---

apps/web/src/services/administration/components/RoleUpdateForm.vue
apps/web/src/services/administration/components/RoleUpdateFormRoleType.vue

SSIA
- quest: https://pyengine.atlassian.net/browse/QA-1001

feat: unable to apply role change

---

apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
apps/web/src/services/dashboards/pages/admin/AdminDashboardMainPage.vue
packages/mirinae/src/navigation/toolbox/PToolbox.vue

fix: fix style bug in all dashboard page

---

apps/web/src/services/cost-explorer/components/BudgetCreateDataSourceSelect.vue
apps/web/src/services/cost-explorer/components/BudgetCreateTargetSelect.vue
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: add 'data source' invalid case for admin mode

---

apps/web/src/services/auth/authenticator/local/template/ID_PW.vue
apps/web/src/services/auth/pages/MultiFactorAuthPage.vue
apps/web/src/services/my-page/components/UserAccountMultiFactorAuthModalEmailInfo.vue

- [apply email for multi factor auth](https://pyengine.atlassian.net/browse/QA-1035)
- Displaying user's MFA email instead of user ID during MFA authentication
- [add disabled condition](https://pyengine.atlassian.net/browse/QA-1040)
- Disabling Send Button After Sending MFA Email Change Confirmation

feat: apply QA issue

---

apps/web/src/services/administration/components/AppManagementTable.vue

chore: apply only domain admin app at app list

---

apps/web/src/App.vue
apps/web/src/store/modules/display/actions.ts
apps/web/src/store/modules/display/getters.ts
apps/web/src/store/modules/display/index.ts
apps/web/src/store/modules/display/mutations.ts
apps/web/src/store/modules/display/type.ts
apps/web/src/store/modules/user/actions.ts

SSIA
https://github.com/cloudforet-io/console/assets/83635051/70622d8e-97b3-40cd-a0e1-575100c40f47

fix(grant): add 'isGrantInProgress' state for rendering after grant

---

apps/web/src/common/modules/navigations/gnb/modules/gnb-profile/GNBProfile.vue
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

fix(profile): add admin role type in profile

---

apps/web/src/common/modules/navigations/gnb/modules/gnb-profile/GNBProfile.vue

fix: apply changed role type in profile

---

apps/web/src/services/project/components/ProjectMemberTab.vue

feat: fetch project members when update project settings

---

apps/web/src/services/project/pages/ProjectDetailPage.vue

fix: hide project group from breadcrumb when there's no projectGroupInfo

---

apps/web/src/common/modules/navigations/lnb/modules/LNBMenuItem.vue
apps/web/src/services/dashboards/DashboardsLNB.vue
apps/web/src/services/dashboards/components/DashboardMainBoardList.vue
apps/web/src/services/dashboards/components/DashboardScopeForm.vue

chore: edit style for private dashboard

---

apps/web/src/common/modules/navigations/gnb/modules/gnb-profile/GNBProfile.vue
apps/web/src/store/modules/domain/actions.ts

feat: update domain state & add copy button to gnb profile

---

apps/web/src/services/administration/components/UserManagementAddUser.vue

feat: apply user external auth option

---

apps/web/src/services/project/components/ProjectMemberTab.vue
apps/web/src/store/reference/project-reference-store.ts
apps/web/src/store/reference/user-reference-store.ts

feat: refactor reference stores & add 'Role' field to project member table  

---

apps/web/src/common/components/modals/UserAPIKeyModal.vue
apps/web/src/schema/identity/app/model.ts
apps/web/src/services/administration/components/AppManagementTable.vue
apps/web/src/services/administration/store/app-page-store.ts
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

SSIA
client_secret > api_key
client_id > api_key_id

feat: apply changed api for api_key

---

apps/web/src/services/administration/components/UserManagementTabDetail.vue

fix(user-management-tab-detail): fix style bug

---

apps/web/src/services/info/pages/admin/AdminNoticeMainPage.vue

fix(admin-notice-main-page): fix routing target

---

apps/web/src/common/modules/navigations/gnb/modules/gnb-recent-favorite/modules/GNBFavorite.vue
apps/web/src/common/modules/navigations/lnb/modules/LNBMenuItem.vue
apps/web/src/common/modules/navigations/lnb/modules/LNBRouterMenuItem.vue

fix(lnb-favorite): fix admin lnb favorite bug

---

apps/web/src/common/components/modals/HasNoWorkspaceModal.vue
apps/web/src/common/modules/navigations/gnb/modules/GNBAdminToggleButton.vue
apps/web/src/common/modules/navigations/gnb/modules/GNBToolset.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-profile/GNBProfile.vue
apps/web/src/common/pages/ErrorPage.vue
apps/web/src/lib/site-initializer/mode-setting.ts
apps/web/src/services/auth/pages/SignInPage.vue
apps/web/src/services/cost-explorer/CostExplorerLNB.vue
apps/web/src/services/dashboards/DashboardsLNB.vue
apps/web/src/services/dashboards/components/DashboardMainBoardList.vue
apps/web/src/store/app-context/app-context-store.ts

SSIA
[QA-1052](https://pyengine.atlassian.net/browse/QA-1052)

fix: apply admin route in lnb

---

apps/web/src/common/modules/favorites/favorite-button/FavoriteButton.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-recent-favorite/modules/GNBFavorite.vue
apps/web/src/schema/add-ons/favorite/model.ts
apps/web/src/services/project/pages/ProjectPage.vue
apps/web/src/store/modules/favorite/actions.ts
apps/web/src/store/modules/favorite/type.ts

fix: apply workspace id in favorite api

---

apps/web/src/common/modules/project/ProjectSelectDropdown.vue
apps/web/src/services/alert-manager/components/AlertMainAlertCreateModal.vue
apps/web/src/services/alert-manager/components/AlertMainDataTable.vue
apps/web/src/services/info/pages/admin/AdminNoticeDetailPage.vue
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ko.json

fix: fix minor alert manager issues

---

apps/web/src/common/modules/navigations/gnb/modules/gnb-search/GNBSearch.vue

SSIA
[QA-1081](https://pyengine.atlassian.net/browse/QA-1081)

fix: edit gnb search location (menuId -> routeName)

---

apps/web/src/schema/identity/workspace-user/api-verbs/list.ts
apps/web/src/services/administration/components/WorkspaceManagementTable.vue
apps/web/src/services/administration/components/WorkspacesUserManagementTab.vue
apps/web/src/services/administration/components/WorkspacesUserManagementTabContents.vue
apps/web/src/services/administration/constants/workspace-constant.ts
apps/web/src/services/administration/pages/admin/AdminWorkspacesPage.vue
apps/web/src/services/administration/store/workspace-page-store.ts
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat(workspaces): create workspace page user tab

---

apps/web/src/common/modules/navigations/lnb/modules/LNBMenuItem.vue

chore: fix icon size

---

apps/web/src/services/project/components/ProjectFormModal.vue

chore: edit minor css

---

apps/web/src/services/project/components/ProjectMemberTab.vue

chore: edit button size

---

apps/web/src/common/composables/proper-route-location/index.ts
apps/web/src/common/modules/navigations/gnb/modules/gnb-menu/modules/dashboard-recent-favorite/modules/GNBDashboardMenu.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-profile/GNBProfile.vue
apps/web/src/router/helpers/route-helper.ts
apps/web/src/router/index.ts
apps/web/src/router/integral-routes.ts
apps/web/src/services/administration/AdministrationLNB.vue
apps/web/src/services/administration/components/RoleManagementTable.vue
apps/web/src/services/administration/pages/admin/RolePage.vue
apps/web/src/services/asset-inventory/AssetInventoryLNB.vue
apps/web/src/services/cost-explorer/CostExplorerLNB.vue
apps/web/src/services/cost-explorer/components/BudgetDetailInfo.vue
apps/web/src/services/cost-explorer/components/CostExplorerLNBRelocateDashboardModal.vue
apps/web/src/services/cost-explorer/pages/admin/AdminBudgetMainPage.vue
apps/web/src/services/dashboards/DashboardsLNB.vue
apps/web/src/services/dashboards/components/DashboardMainBoardList.vue
apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
apps/web/src/services/info/pages/admin/AdminNoticeDetailPage.vue
apps/web/src/services/info/pages/admin/AdminNoticeMainPage.vue
apps/web/src/store/modules/user/actions.ts
apps/web/src/store/modules/user/getters.ts
apps/web/src/store/modules/user/index.ts
apps/web/src/store/modules/user/mutations.ts
apps/web/src/store/modules/user/type.ts

SSIA
This need explanation & discussion

fix(grant): add browser back button handling case & optimize grant api

---

apps/web/src/common/modules/favorites/favorite-button/FavoriteButton.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-recent-favorite/modules/GNBRecent.vue
apps/web/src/lib/helper/config-data-helper.ts
apps/web/src/lib/helper/router-recent-helper.ts
apps/web/src/router/index.ts
apps/web/src/store/modules/recent/actions.ts
apps/web/src/store/modules/recent/type.ts

fix(recent): apply workspace id in recent

---

apps/web/src/common/composables/date-range-formatter/__tests__/index.test.ts

chore: disable broken test case

---

apps/web/src/common/modules/navigations/gnb/modules/gnb-profile/GNBProfile.vue
apps/web/src/lib/helper/router-recent-helper.ts
apps/web/src/services/administration/AdministrationLNB.vue
apps/web/src/services/asset-inventory/AssetInventoryLNB.vue
apps/web/src/services/cost-explorer/components/BudgetDetailInfo.vue
apps/web/src/services/dashboards/DashboardsLNB.vue

fix: ref minor issue

---

apps/web/src/common/modules/navigations/gnb/modules/gnb-profile/GNBProfile.vue
apps/web/src/services/administration/components/DomainSettingsTimezoneAndLanguage.vue
apps/web/src/services/dashboards/pages/DashboardDetailPage.vue
apps/web/src/services/dashboards/pages/admin/AdminDashboardDetailPage.vue

fix(dashboard): set is-manageable true to variable more button & fix selected item bug(domain-settings)

---

apps/web/src/common/modules/favorites/favorite-button/FavoriteButton.vue
apps/web/src/common/modules/navigations/gnb/modules/GNBHeader.vue
apps/web/src/lib/helper/router-recent-helper.ts
apps/web/src/router/index.ts
apps/web/src/services/alert-manager/routes/routes.ts
apps/web/src/services/asset-inventory/routes/routes.ts
apps/web/src/services/cost-explorer/routes/routes.ts
apps/web/src/services/project/pages/ProjectPage.vue
apps/web/src/services/project/routes/routes.ts

refactor: usage of pinia in space-router

---

apps/web/src/common/modules/favorites/favorite-button/FavoriteButton.vue

fix: add defensive code in favorite button

---

apps/web/src/services/administration/components/WorkspacesCreateModal.vue
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

SSIA
[QA-951](https://pyengine.atlassian.net/browse/QA-951)

fix(workspace-edit): add edit case modal text

---

apps/web/src/App.vue
apps/web/src/common/modules/modals/notification-email-modal/NotificationEmailModal.vue
apps/web/src/services/my-page/components/UserAccountNotificationEmail.vue

feat: remove domain Id and apply notification email when user log-in

---

apps/web/src/services/my-page/MyPageLNB.vue
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

fix: fix the icon img of mypage profile & remove favorite buttons

---

apps/web/src/lib/helper/verify-email-helper.ts
apps/web/src/services/administration/components/UserManagementFormAdminRole.vue
apps/web/src/services/administration/components/UserManagementFormModal.vue
apps/web/src/services/administration/components/UserManagementFormMultiFactorAuth.vue

SSIA
- quest: https://pyengine.atlassian.net/browse/QA-1078

feat: apply delete role binding at user form modal

---

apps/web/src/common/components/charts/metric-chart/MetricChart.vue
apps/web/src/common/components/marks/BetaMark.vue
apps/web/src/common/components/marks/GNBNewIcon.vue
apps/web/src/common/components/marks/NewMark.vue
apps/web/src/common/components/marks/UpdateMark.vue
apps/web/src/common/modules/modals/notification-email-modal/NotificationEmailModal.vue
apps/web/src/common/modules/navigations/gnb/modules/GNBLogo.vue
apps/web/src/common/modules/navigations/gnb/modules/GNBSuggestionList.vue
apps/web/src/common/modules/navigations/gnb/modules/GNBToolset.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-noti/GNBNoti.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-noti/modules/GNBNotiItem.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-noti/modules/GNBNoticeTab.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-noti/modules/GNBNotificationsTab.vue
apps/web/src/common/modules/navigations/lnb/LNB.vue
apps/web/src/common/modules/navigations/lnb/modules/LNBMenuItem.vue
apps/web/src/common/modules/project/ProjectSelectDropdown.vue
apps/web/src/services/alert-manager/components/AlertDetailSummary.vue
apps/web/src/services/alert-manager/components/AlertDetailSummaryAssignModal.vue
apps/web/src/services/alert-manager/components/AlertDetailTabs.vue
apps/web/src/services/alert-manager/components/AlertDetailTabsDetails.vue
apps/web/src/services/alert-manager/components/AlertDetailTitleEditModal.vue
apps/web/src/services/alert-manager/components/AlertListItem.vue
apps/web/src/services/alert-manager/components/AlertMainDataTableBottomFilters.vue
apps/web/src/services/alert-manager/components/ProjectChannelList.vue
apps/web/src/services/alert-manager/pages/AlertDetailPage.vue
apps/web/src/services/alert-manager/stores/alert-page-store.ts
apps/web/src/services/cost-explorer/CostExplorerLNB.vue
apps/web/src/services/info/components/NoticeListItemTitle.vue
apps/web/src/services/project/components/ProjectAlertSettingsEscalationPolicy.vue
apps/web/src/services/project/components/ProjectAlertWebhookAddModal.vue

fix: update plugin list parameter in add webhook modal

---

apps/web/src/common/modules/navigations/gnb/modules/gnb-recent-favorite/modules/GNBRecent.vue
apps/web/src/services/administration/components/WorkspaceManagementTable.vue
apps/web/src/services/administration/store/workspace-page-store.ts

fix: refactor recent select by using route name & apply link in workspace table

---

apps/web/src/common/modules/navigations/gnb/MyPageGNB.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-profile/GNBProfile.vue
apps/web/src/services/my-page/MyPageLNB.vue
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

fix: fix back link text value & add specific route location

---

apps/web/src/services/alert-manager/components/AlertMainDataTable.vue
apps/web/src/services/alert-manager/pages/EscalationPolicyPage.vue

fix: fix minor issues in alert pages

---

apps/web/src/services/administration/components/AppManagementFormModal.vue
apps/web/src/services/administration/components/AppManagementStatusModal.vue
apps/web/src/services/administration/components/UserManagementAddTag.vue
apps/web/src/services/administration/components/UserManagementAddUser.vue
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

SSIA
- quest: https://pyengine.atlassian.net/browse/QA-1059, https://pyengine.atlassian.net/browse/QA-1084

chore: apply minor QA issue

---

apps/web/src/services/dashboards/components/DashboardDetailHeader.vue
apps/web/src/services/dashboards/components/DashboardMainBoardList.vue
apps/web/src/services/dashboards/components/DashboardManageVariableOverlay.vue
apps/web/src/services/dashboards/components/DashboardVariablesMoreButton.vue

fix [qa-1105](https://pyengine.atlassian.net/browse/QA-1105)

fix: fix router for dashboard manage variable

---

apps/web/src/services/asset-inventory/components/CollectorDetailScheduleSection.vue
apps/web/src/services/asset-inventory/components/CollectorFormSchedule.vue

fix(collector-detail-schedule-section): fix css bug

---

apps/web/src/services/administration/components/WorkspaceManagementTable.vue
apps/web/src/services/administration/store/workspace-page-store.ts

SSIA
[QA-1090](https://pyengine.atlassian.net/browse/QA-1090)

fix(workspaces): edit workspace management table query

---

apps/web/src/services/alert-manager/components/AlertDetailSummary.vue
apps/web/src/services/alert-manager/components/AlertMainDataTable.vue

fix: alert urgency color

---

apps/web/src/services/alert-manager/components/AlertMainAcknowledgeModal.vue

fix: update default value of alert assign checkbox

---

apps/web/src/services/alert-manager/components/AlertDetailNote.vue
packages/mirinae/src/data-display/collapsible/collapsible-list/PCollapsibleList.stories.mdx
packages/mirinae/src/data-display/collapsible/collapsible-list/PCollapsibleList.vue
packages/mirinae/src/data-display/collapsible/collapsible-list/story-helper.ts
packages/mirinae/src/data-display/collapsible/collapsible-panel/PCollapsiblePanel.vue

fix(mirinae): add no styled title slot to collapsible list & add pad to collapsible panel

---

apps/web/src/services/administration/components/UserNotifications.vue
apps/web/src/services/my-page/components/NotificationAddForm.vue
apps/web/src/services/my-page/components/NotificationChannelList.vue
apps/web/src/services/my-page/pages/UserNotificationAddPage.vue
apps/web/src/services/my-page/pages/UserNotificationPage.vue
apps/web/src/services/my-page/routes/routes.ts
apps/web/src/services/my-page/types/user-notification-add-page-url-query-type.ts
apps/web/src/services/project/routes/routes.ts
apps/web/src/store/modules/reference/plugin/actions.ts

fix: update plugin api in reference store

---

apps/web/src/services/administration/components/AppManagementTable.vue
apps/web/src/services/administration/components/RoleManagementTable.vue
apps/web/src/services/administration/components/UserManagementTableToolbox.vue
apps/web/src/services/administration/components/WorkspaceManagementTable.vue
apps/web/src/services/alert-manager/components/AlertMainDataTableActions.vue
apps/web/src/services/alert-manager/pages/EscalationPolicyPage.vue
apps/web/src/services/project/pages/ProjectWebhookPage.vue
packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.stories.mdx
packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
packages/mirinae/src/inputs/dropdown/select-dropdown/story-helper.ts

Resolve the issue of persistent selection in the action dropdown even after choosing an item.

feat: reset selection in the action dropdown

---

apps/web/src/services/administration/components/WorkspacesUserManagementTabContents.vue
packages/core-lib/src/component-util/query-search/index.ts

SSIA
- Add `extraParams` to `makeDistinctValueHandler`

fix: add missed workspace_id in workspaceUser stat & apply extra params to makeDistinctValueHandler

---

apps/web/src/common/modules/navigations/gnb/modules/GNBAdminToggleButton.vue
apps/web/src/common/modules/navigations/gnb/modules/GNBHeader.vue

fix: update css of gnb

---

apps/web/src/services/administration/components/UserManagementAddModal.vue
apps/web/src/services/dashboards/components/DashboardCustomizePageName.vue
apps/web/src/services/dashboards/components/DashboardVariableDropdown.vue

[[Minor][Dashboards] 이름 중복 유효성 검사 missing](https://pyengine.atlassian.net/browse/QA-1118)
[[Major][Dashboards] Data source가 2개이상 선택되는 이슈](https://pyengine.atlassian.net/browse/QA-1117)
[[Major][Preferences] 도메인 타임존 반영 안됨 ](https://pyengine.atlassian.net/browse/QA-1115)

fix: fix name validation in dashboard create page & fix selection bug in dashboard variable

---

apps/web/src/store/modules/domain/actions.ts

fix: revive domain config

---

packages/core-lib/src/space-connector/index.ts
packages/core-lib/src/space-connector/token-api.ts

SSIA
- Console is no longer storing accessToken in localStorage. (This will be completed with next PR, this code is only a part)
- Token invalid check is changed to using 6min from 10sec.

fix(access-token): change management logic of access token

---

apps/web/src/services/info/components/NoticeList.vue

fix: apply proper route location in info/notice

---

apps/web/src/store/modules/user/actions.ts

fix: remove grant in signIn action & apply grant fail scenario

---

apps/web/src/services/info/components/NoticeDetail.vue

fix: apply proper router in notice detail page

---

apps/web/src/common/modules/navigations/gnb/modules/GNBAdminToggleButton.vue
apps/web/src/lib/site-initializer/api-client.ts
apps/web/src/store/modules/settings/actions.ts
packages/core-lib/src/space-connector/token-api.ts

fix(access-token): improved access token management method

---

apps/web/src/services/cost-explorer/CostExplorerLNB.vue
apps/web/src/services/cost-explorer/components/CostAnalysisFiltersPopper.vue
apps/web/src/services/cost-explorer/constants/cost-explorer-constant.ts
apps/web/src/services/cost-explorer/constants/managed-cost-analysis-query-sets.ts
apps/web/src/services/cost-explorer/routes/admin/routes.ts
apps/web/src/services/cost-explorer/stores/cost-analysis-page-store.ts
apps/web/src/services/my-page/components/NotificationAddFormData.vue

feat: add 'workspace' groupby/filter to cost analysis

---

apps/web/src/services/cost-explorer/components/BudgetDetailSummaryChart.vue
apps/web/src/services/project/components/ProjectMainCardList.vue
apps/web/src/services/project/components/ProjectMemberTab.vue
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

fix: fix y axis text in budget chart & fix(project-member): hide remove button in public mode

---

apps/web/src/common/modules/navigations/gnb/MyPageGNB.vue
apps/web/src/common/modules/navigations/lnb/modules/LNBMenuItem.vue
apps/web/src/common/modules/navigations/lnb/modules/LNBRouterMenuItem.vue
apps/web/src/common/modules/navigations/lnb/type.ts
apps/web/src/common/modules/popup/notice/NoticePopup.vue
apps/web/src/services/cost-explorer/CostExplorerLNB.vue
apps/web/src/services/info/components/NoticeForm.vue
apps/web/src/services/my-page/MyPageLNB.vue

fix: fix typo and apply mypage no role case

---

apps/web/src/schema/monitoring/log/model.ts
apps/web/src/services/asset-inventory/components/CloudServiceLogTab.vue

fix: fix log data model

---

apps/web/src/common/modules/navigations/gnb/modules/gnb-menu/modules/dashboard-recent-favorite/modules/GNBDashboardMenu.vue
apps/web/src/services/cost-explorer/components/BudgetDetailSummaryTable.vue
apps/web/src/services/project/components/ProjectMainCardList.vue

fix: fix budget link

---

apps/web/src/common/modules/widgets/DailyUpdates.vue
apps/web/src/services/asset-inventory/components/CloudServices.vue
apps/web/src/services/home-dashboard/components/AllSummary.vue
apps/web/src/services/home-dashboard/components/AllSummaryDataSummary.vue
apps/web/src/services/home-dashboard/components/PersonalHealthDashboard.vue
apps/web/src/services/home-dashboard/components/ResourceMap.vue
apps/web/src/services/home-dashboard/components/ServiceAccounts.vue
apps/web/src/services/home-dashboard/components/TopProjects.vue
apps/web/src/services/home-dashboard/components/TrustedAdvisor.vue
apps/web/src/services/home-dashboard/components/TrustedAdvisorOverall.vue
apps/web/src/services/project/components/ProjectSummaryAllSummaryWidget.vue
apps/web/src/services/project/components/ProjectSummaryAllSummaryWidgetRegionService.vue
apps/web/src/services/project/components/ProjectSummaryPersonalHealthDashboardWidget.vue
apps/web/src/services/project/components/ProjectSummaryServiceAccountsWidget.vue
apps/web/src/services/project/components/ProjectSummaryTrustedAdvisorWidget.vue

feat: set `workspace_id` parameter to statistics/topic api

---

apps/web/src/services/cost-explorer/components/BudgetDetailInfo.vue

fix: fix the target link in budget detail page

---

apps/web/src/services/project/pages/ProjectAlertEventRulePage.vue
apps/web/src/services/project/pages/ProjectDetailPage.vue

fix: fix breadcrumb in project page

---

apps/web/src/lib/site-initializer/api-client.ts
apps/web/src/services/cost-explorer/stores/cost-analysis-page-store.ts
apps/web/src/services/dashboards/components/DashboardVariables.vue
apps/web/src/services/dashboards/components/DashboardWidgetContainer.vue
apps/web/src/services/dashboards/components/WidgetViewModeModal.vue
apps/web/src/services/dashboards/stores/all-reference-type-info-store.ts
apps/web/src/services/dashboards/widgets/_components/WidgetDataTable.vue
apps/web/src/services/dashboards/widgets/_helpers/__tests__/widget-value-label-helper.test.ts
apps/web/src/services/dashboards/widgets/_helpers/widget-chart-data-helper.ts
apps/web/src/services/dashboards/widgets/_helpers/widget-chart-helper.ts
apps/web/src/services/dashboards/widgets/_helpers/widget-table-helper.ts
apps/web/src/services/dashboards/widgets/_helpers/widget-value-label-helper.ts
apps/web/src/services/dashboards/widgets/_types/widget-type.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-map/costmap-chart-data-helper.ts
apps/web/src/services/my-page/routes/routes.ts
apps/web/src/store/modules/reference/type.ts
apps/web/src/store/reference/all-reference-store.ts
apps/web/src/store/reference/cloue-service-query-set-reference-store.ts
apps/web/src/store/reference/cost-data-source-reference-store.ts
apps/web/src/store/reference/project-group-reference-store.ts
apps/web/src/store/reference/project-reference-store.ts
apps/web/src/store/reference/user-reference-store.ts
apps/web/src/store/reference/workspace-reference-store.ts

fix: fix breadcrumbs of my page notification channel page & do not load reference data if grant scope is user

---

apps/web/src/services/administration/components/UserManagementAddUser.vue
apps/web/src/services/administration/pages/admin/AdminWorkspacesPage.vue

- apply workspace name at invitation modal
- [component modification due to input keyboard event bug](https://pyengine.atlassian.net/browse/QA-1149)

fix: fixed bugs for QA issue

---

apps/web/src/services/auth/components/SignInLeftContainer.vue
apps/web/src/services/my-page/components/NotificationAddFormData.vue
apps/web/src/services/my-page/components/NotificationAddMemberGroup.vue

fix: show domain settings image rather than newYear image & fix: get proper member list in notification member dropdown

---

apps/web/src/common/components/editor/TextEditorViewer.vue
apps/web/src/common/components/editor/text-editor-nodes.pcss
apps/web/src/common/modules/popup/notice/modules/NoticePopupItem.vue
apps/web/src/services/my-page/pages/UserNotificationAddPage.vue
apps/web/src/services/my-page/routes/routes.ts
apps/web/src/services/project/pages/ProjectNotificationAddPage.vue
packages/mirinae/src/navigation/breadcrumbs/PBreadcrumbs.vue

fix: update notification add page breadcrumbs

---

apps/web/src/services/dashboards/widgets/_composables/use-widget/use-base-widget-state.ts
apps/web/src/services/dashboards/widgets/_composables/use-widget/use-widget-console-filters.ts
apps/web/src/services/dashboards/widgets/_composables/use-widget/use-widget-location.ts
apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-by-target/BudgetUsageByTargetWidget.vue

fix: fix typo error

---

apps/web/src/services/dashboards/widgets/_composables/use-widget/use-base-widget-state.ts
apps/web/src/services/dashboards/widgets/_composables/use-widget/use-widget-console-filters.ts
apps/web/src/services/dashboards/widgets/_composables/use-widget/use-widget-location.ts
apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-by-target/BudgetUsageByTargetWidget.vue

fix: do not reference wrong name of allReferenceTypeInfo

---

apps/web/src/services/alert-manager/pages/EscalationPolicyPage.vue

fix: fix infinite loop bug 

---

apps/web/src/services/cost-explorer/components/CostAnalysisDataTable.vue
apps/web/src/services/cost-explorer/routes/routes.ts

fix: set workspaceId to cost-explorer route & hide link in admin mode (cost analysis data table)

---

apps/web/src/common/modules/navigations/gnb/modules/GNBAdminToggleButton.vue
apps/web/src/lib/site-initializer/api-client.ts
apps/web/src/lib/site-initializer/workspace.ts
apps/web/src/router/integral-routes.ts
apps/web/src/services/auth/helpers/default-route-helper.ts
apps/web/src/services/auth/pages/KB_SSOPage.vue
apps/web/src/services/auth/pages/MultiFactorAuthPage.vue
apps/web/src/services/auth/pages/SignInPage.vue
apps/web/src/store/app-context/workspace/user-workspace-store.ts
apps/web/src/store/modules/user/actions.ts

fix: apply last-accessed-workspace-id

---

apps/web/src/common/modules/navigations/gnb/modules/GNBAdminToggleButton.vue
apps/web/src/lib/site-initializer/api-client.ts
apps/web/src/lib/site-initializer/workspace.ts
apps/web/src/router/integral-routes.ts
apps/web/src/services/auth/helpers/default-route-helper.ts
apps/web/src/services/auth/pages/KB_SSOPage.vue
apps/web/src/services/auth/pages/MultiFactorAuthPage.vue
apps/web/src/services/auth/pages/SignInPage.vue
apps/web/src/store/app-context/workspace/user-workspace-store.ts
apps/web/src/store/modules/user/actions.ts

This reverts commit e9dde15247b509672229c916ef543add88f6f6b9.

Revert "fix: apply last-accessed-workspace-id (#2786)"

---

apps/web/src/services/cost-explorer/routes/admin/routes.ts

chore: set menu id to admin budget route

---

apps/web/src/services/dashboards/components/DashboardVariableDropdown.vue
apps/web/src/services/dashboards/pages/DashboardDetailPage.vue
packages/mirinae/src/feedbacks/modals/button-modal/PButtonModal.vue

fix: fix selection in dashboard variable & feat: delete 'inline-block' of PButtonModal

---

apps/web/src/common/modules/navigations/gnb/modules/GNBAdminToggleButton.vue
apps/web/src/lib/site-initializer/api-client.ts
apps/web/src/lib/site-initializer/workspace.ts
apps/web/src/router/index.ts
apps/web/src/router/integral-routes.ts
apps/web/src/services/auth/helpers/default-route-helper.ts
apps/web/src/services/auth/pages/KB_SSOPage.vue
apps/web/src/services/auth/pages/MultiFactorAuthPage.vue
apps/web/src/services/auth/pages/SignInPage.vue
apps/web/src/store/app-context/workspace/user-workspace-store.ts
apps/web/src/store/modules/user/actions.ts

fix: apply last accessed workspace 

---

apps/web/src/App.vue

feat: add loading spinner if the grant is InProgress

---

apps/web/src/common/modules/navigations/gnb/modules/GNBAdminToggleButton.vue
apps/web/src/common/modules/navigations/gnb/modules/GNBHeader.vue
apps/web/src/lib/site-initializer/workspace.ts
apps/web/src/services/auth/pages/SignInPage.vue
apps/web/src/store/modules/user/actions.ts

fix: solve workspaceId issue

---

apps/web/src/router/index.ts
apps/web/src/services/administration/pages/admin/AdminWorkspacesPage.vue
apps/web/src/store/modules/user/actions.ts

refactor(grant): refactor condition & handle deleted workspace enter scenario

---

apps/web/src/services/asset-inventory/components/ServiceAccountCredentials.vue

SSIA
Fixed Tickets
- [QA-1213](https://pyengine.atlassian.net/browse/QA-1213)
- [QA-1221](https://pyengine.atlassian.net/browse/QA-1221)

fix: fix the update api code of serviceAccount

---

apps/web/src/common/modules/navigations/gnb/modules/gnb-recent-favorite/modules/GNBFavorite.vue

fix: fix bug when getting favorite item

---

apps/web/src/services/cost-explorer/components/CostAnalysisQuerySection.vue
apps/web/src/services/project/stores/project-page-store.ts

fix: fix project page breadcrumb

---

apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue

fix: fix style bug in serviceAccount Table

---

apps/web/src/services/project/components/ProjectMainCardList.vue
apps/web/src/services/project/components/ProjectMainProjectGroupMoveModal.vue
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

fix: update language of project group move modal

---

apps/web/src/common/modules/navigations/gnb/modules/GNBAdminToggleButton.vue
apps/web/src/lib/site-initializer/last-accessed-workspace.ts
apps/web/src/lib/site-initializer/workspace.ts
apps/web/src/services/administration/components/WorkspacesUserManagementTabContents.vue
apps/web/src/services/auth/pages/SignInPage.vue
apps/web/src/store/modules/user/actions.ts

SSIA
- [QA-959](https://pyengine.atlassian.net/browse/QA-959)
- [QA-1189](https://pyengine.atlassian.net/browse/QA-1189)

fix: solve small QA

---

apps/web/src/services/asset-inventory/components/CollectorCurrentStatus.vue
apps/web/src/services/asset-inventory/components/CollectorDetailCollectDataButtonGroup.vue
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

Fixed Tickets
- [QA-1207](https://pyengine.atlassian.net/browse/QA-1207)
- [QA-1240](https://pyengine.atlassian.net/browse/QA-1240)

fix: fix translate bug & remove wrong link

---

apps/web/src/store/modules/user/actions.ts

fix: remove ErrorHandler in grant

---

apps/web/src/schema/inventory/collector/api-verbs/create.ts
apps/web/src/schema/inventory/collector/model.ts
apps/web/src/services/asset-inventory/components/CollectorBaseInfoSection.vue
apps/web/src/services/asset-inventory/components/CollectorMainContents.vue
apps/web/src/services/asset-inventory/types/collector-main-page-type.ts
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

fix: update language for project dropdown and fix other minor things

---

apps/web/src/common/components/buttons/PdfDownloadButton.vue
apps/web/src/common/components/editor/ColorPicker.vue
apps/web/src/common/components/editor/MenuBar.vue
apps/web/src/common/components/editor/TextEditor.vue
apps/web/src/common/components/editor/TextEditorViewer.vue
apps/web/src/common/components/forms/tags-input-group/TagsInputGroup.vue
apps/web/src/common/components/titles/sidebar-title/SidebarTitle.vue
apps/web/src/common/modules/modals/RecommendedBrowserModal.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-menu/GNBMenu.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-menu/GNBSubMenu.vue
apps/web/src/common/modules/portals/TopNotification.vue
apps/web/src/common/modules/tags/tags-panel/TagsPanel.vue
apps/web/src/common/modules/tags/tags-panel/modules/TagsOverlay.vue
apps/web/src/common/pages/NoResourcePage.vue
apps/web/src/services/asset-inventory/components/CloudServiceDetailTabs.vue
apps/web/src/services/asset-inventory/components/CloudServiceTagsPanel.vue
packages/mirinae/src/inputs/text-editor/PTextEditor.vue

refactor: update to script setup

---

apps/web/src/common/components/editor/text-editor-nodes.pcss

fix: update css of text editor

---

apps/web/src/services/dashboards/components/DashboardVariableDropdown.vue

fix: fix select event bug in dashboard variables

---

apps/web/src/lib/menu/menu-architecture.ts
apps/web/src/services/administration/routes/admin/routes.ts

fix: change administration route order

---

apps/web/src/services/asset-inventory/components/CollectorBaseInfoSection.vue
apps/web/src/services/asset-inventory/components/CollectorDetailServiceAccountsSection.vue
apps/web/src/services/asset-inventory/components/ServiceAccountCredentials.vue
apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue

- [QA-1209](https://pyengine.atlassian.net/browse/QA-1209)
- [QA-1216](https://pyengine.atlassian.net/browse/QA-1216)
- [QA-1200](https://pyengine.atlassian.net/browse/QA-1200)

fix: fix qa-bugs (collector, serviceAccount)

---

apps/web/src/services/asset-inventory/components/CollectorDataDefaultInner.vue
apps/web/src/services/asset-inventory/components/CollectorDataModal.vue
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

- [QA-1218](https://pyengine.atlassian.net/browse/QA-1218)
- [QA-1222](https://pyengine.atlassian.net/browse/QA-1222)

fix: fix collectDataModal bugs

---

apps/web/src/lib/site-initializer/api-client.ts
apps/web/src/services/cost-explorer/components/CostAnalysisPeriodSelectDropdown.vue
apps/web/src/services/cost-explorer/helpers/cost-explorer-chart-data-helper.ts
apps/web/src/services/cost-explorer/routes/admin/routes.ts
apps/web/src/services/cost-explorer/routes/routes.ts
apps/web/src/store/reference/cost-data-source-reference-store.ts

fix: set workspace label to cost analysis legend & etc

---

apps/web/src/services/cost-explorer/components/BudgetDetailInfo.vue

fix: fix budget target link issue

---

apps/web/src/services/cost-explorer/components/BudgetDetailInfo.vue

chore: minor css

---

apps/web/src/common/modules/navigations/gnb/modules/GNBAdminToggleButton.vue

fix(g-n-b-admin-toggle-button): fix hard core click bug

---

apps/web/src/common/components/editor/text-editor-nodes.pcss
apps/web/src/common/modules/navigations/gnb/modules/GNBHeader.vue
apps/web/src/services/alert-manager/components/AlertDetailSummary.vue
apps/web/src/services/alert-manager/components/AlertDetailSummaryAssignModal.vue
apps/web/src/services/alert-manager/stores/alert-page-store.ts
apps/web/src/services/info/pages/admin/AdminNoticeUpdatePage.vue
packages/mirinae/src/hooks/context-menu-controller/index.ts
packages/mirinae/src/inputs/context-menu/type.ts
packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.stories.mdx
packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
packages/mirinae/src/inputs/dropdown/select-dropdown/mock.ts
packages/mirinae/src/inputs/dropdown/select-dropdown/story-helper.ts

feat(mirinae): add hideHeaderWithoutItems to select dropdown and apply appliy it to gnb header

---

apps/web/src/services/asset-inventory/components/CollectorMainContents.vue
apps/web/src/services/asset-inventory/components/ServiceAccountDeleteModal.vue

fix: fix minor bugs (collector, service account)

---

apps/web/src/services/project/components/ProjectAlertSettingsEscalationPolicyChangeModal.vue

fix: add '*' for project id filter for escalation policy list api

---

apps/web/src/schema/identity/workspace-user/api-verbs/find.ts
apps/web/src/services/administration/components/UserManagementAddUser.vue
apps/web/src/services/administration/components/UserManagementStatusModal.vue
apps/web/src/services/administration/components/UserManagementTabDetail.vue
apps/web/src/services/administration/components/UserManagementTable.vue
apps/web/src/services/administration/composables/refined-table-data.ts
apps/web/src/services/administration/constants/user-constant.ts
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

- [apply role icon](https://pyengine.atlassian.net/browse/QA-1235)
- [changed column at user delete modal](https://pyengine.atlassian.net/browse/QA-1224)
- Admin mode
- User mode
- [fixed user context menu when user invite](https://pyengine.atlassian.net/browse/QA-1242)

feat: apply QA issue at user

---

apps/web/src/services/administration/components/RoleCreateEditHandbook.vue
apps/web/src/services/administration/components/UserManagementAddAdminRole.vue
apps/web/src/services/administration/components/UserManagementAddRole.vue
apps/web/src/services/administration/components/UserManagementFormAdminRole.vue
packages/mirinae/src/feedbacks/alert/toast-alert/PToastAlert.vue
packages/mirinae/src/inputs/dropdown/select-dropdown/components/dropdown-button.vue

chore: changed css style

---

apps/web/src/services/asset-inventory/components/CloudServiceAdmin.vue

fix(cloud-service): fix related member tab bugs

---

apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue
apps/web/src/services/asset-inventory/stores/service-account-schema-store.ts

feat: modified to maintain account type

---

apps/web/src/services/cost-explorer/CostExplorerLNB.vue

feat: hide 'go to dashboard' in admin mode

---

apps/web/src/services/asset-inventory/pages/CloudServicePage.vue
apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue

SSIA
[QA-1254](https://pyengine.atlassian.net/browse/QA-1254)

fix: fix search key of cloudServiceTable

---

apps/web/src/common/modules/navigations/gnb/modules/gnb-menu/GNBMenu.vue
apps/web/src/lib/menu/menu-architecture.ts
apps/web/src/store/modules/display/type.ts

fix: update administration gnb sub menu

---

apps/web/src/common/modules/navigations/gnb/modules/GNBAdminToggleButton.vue
apps/web/src/lib/site-initializer/api-client.ts
apps/web/src/lib/site-initializer/workspace.ts
apps/web/src/router/index.ts
apps/web/src/router/integral-routes.ts
apps/web/src/services/auth/authenticator/index.ts
apps/web/src/store/app-context/workspace/user-workspace-store.ts
apps/web/src/store/modules/error/index.ts
apps/web/src/store/modules/error/mutations.ts
apps/web/src/store/modules/error/type.ts
apps/web/src/store/modules/user/actions.ts

SSIA
I think it's better to explain verbally than by text description.

fix: handle disable or deleted workspace access case

---

apps/web/src/services/administration/components/RoleManagementTabDetail.vue
apps/web/src/services/administration/constants/role-constant.ts

chore: changed basic managed role's page access

---

apps/web/src/common/modules/navigations/gnb/modules/GNBHeader.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-noti/modules/GNBNoticeTab.vue
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

fix: update some languages

---

apps/web/src/services/alert-manager/components/AlertDashboardAlertHistoryWidget.vue
apps/web/src/services/alert-manager/components/AlertDashboardAlertStateWidget.vue
apps/web/src/services/alert-manager/components/AlertDashboardCurrentProjectStatusWidget.vue
apps/web/src/services/alert-manager/components/AlertDashboardProjectSearchWidget.vue
apps/web/src/services/alert-manager/components/AlertDashboardTop5ProjectActivityWidget.vue

feat: set `workspace_id` to alert dashboard widgets

---

apps/web/src/services/administration/store/workspace-page-store.ts

fix: change type of `users` from number to string

---

apps/web/src/services/cost-explorer/CostExplorerContainer.vue
apps/web/src/services/cost-explorer/stores/cost-explorer-settings-store.ts

refactor: set settings in action not through `$onAction`

---

apps/web/src/services/auth/pages/KeycloakPage.vue

fix: edit new onSignIn callback to keycloak

---

apps/web/src/services/administration/components/UserManagementAddUser.vue
apps/web/src/services/administration/components/UserManagementStatusModal.vue
apps/web/src/services/administration/constants/user-constant.ts

chore: fixed minor changed

---

apps/web/src/common/modules/navigations/gnb/modules/gnb-menu/GNBMenu.vue

fix: change from v-show to v-if of GNBDashboardMenu

---

apps/web/src/services/administration/components/UserManagementAddUser.vue
apps/web/src/services/administration/components/UserManagementStatusModal.vue
apps/web/src/services/administration/components/UserManagementTab.vue
apps/web/src/services/administration/constants/user-constant.ts

chore: apply isAdminMode at table field

---

apps/web/src/App.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-menu/modules/dashboard-recent-favorite/modules/GNBDashboardMenu.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-noti/GNBNoti.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-noti/modules/GNBNotiItem.vue
apps/web/src/common/modules/popup/notice/NoticePopup.vue
apps/web/src/services/administration/components/UserManagementAddUser.vue
apps/web/src/services/administration/components/UserManagementTab.vue
apps/web/src/services/alert-manager/components/AlertDetailInfoTableDescription.vue
apps/web/src/store/notice/index.ts

fix: apply highlight term to add user dropdown & add margin right to user role type

---

apps/web/src/services/asset-inventory/pages/ServiceAccountDetailPage.vue

fix: add error handling code

---

apps/web/src/router/integral-routes.ts
apps/web/src/services/auth/authenticator/index.ts
apps/web/src/store/app-context/workspace/user-workspace-store.ts

fix: reset workspace list on sign out

---

apps/web/src/App.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-menu/GNBMenu.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-menu/modules/dashboard-recent-favorite/modules/GNBDashboardMenu.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-noti/GNBNoti.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-noti/modules/GNBNotiItem.vue
apps/web/src/common/modules/popup/notice/NoticePopup.vue
apps/web/src/router/integral-routes.ts
apps/web/src/services/administration/components/UserManagementAddUser.vue
apps/web/src/services/administration/components/UserManagementStatusModal.vue
apps/web/src/services/administration/components/UserManagementTab.vue
apps/web/src/services/administration/constants/user-constant.ts
apps/web/src/services/alert-manager/components/AlertDetailInfoTableDescription.vue
apps/web/src/services/asset-inventory/pages/ServiceAccountDetailPage.vue
apps/web/src/services/auth/authenticator/index.ts
apps/web/src/services/auth/pages/KeycloakPage.vue
apps/web/src/store/app-context/workspace/user-workspace-store.ts
apps/web/src/store/notice/index.ts

Merge 'cloudforet-io/feature-workspace-fundametals' by pull request #2854

---

apps/web/src/services/administration/components/UserManagementFormAdminRole.vue
apps/web/src/services/administration/components/UserManagementFormModal.vue
packages/mirinae/src/inputs/dropdown/select-dropdown/components/dropdown-button.vue

fix: user self edit issue

---

apps/web/src/services/project/pages/ProjectDetailPage.vue

fix: give height 100 to project detail page

---

apps/web/src/store/reference/project-group-reference-store.ts
apps/web/src/store/reference/project-reference-store.ts

fix: do not call project-group/get in reference store

---

apps/web/src/services/administration/components/UserManagementFormAdminRole.vue
apps/web/src/services/administration/components/UserManagementFormModal.vue
apps/web/src/services/project/pages/ProjectDetailPage.vue
packages/mirinae/src/inputs/dropdown/select-dropdown/components/dropdown-button.vue

feat: merge to master

---

apps/web/src/services/auth/authenticator/external/GOOGLE_OAUTH2/authenticator/google-auth.ts
apps/web/src/services/auth/authenticator/external/GOOGLE_OAUTH2/template/GOOGLE_OAUTH2.vue
apps/web/src/services/auth/pages/MultiFactorAuthPage.vue

feat: apply google oauth

---

apps/web/src/services/auth/authenticator/external/KEYCLOAK_OIDC/authenticator/keycloak-auth.ts
apps/web/src/services/auth/pages/KeycloakPage.vue

feat: apply MFA at keycloak

---

apps/web/src/services/dashboards/pages/DashboardsMainPage.vue

fix: fix minor bug in dashboard main list

---

apps/web/src/store/modules/user/actions.ts

fix: handle grant 500 error

---

apps/web/src/services/auth/authenticator/external/GOOGLE_OAUTH2/authenticator/google-auth.ts
apps/web/src/services/auth/authenticator/external/GOOGLE_OAUTH2/template/GOOGLE_OAUTH2.vue
apps/web/src/services/auth/authenticator/local/template/ID_PW.vue
apps/web/src/services/auth/pages/KeycloakPage.vue
apps/web/src/services/auth/pages/MultiFactorAuthPage.vue

refactor: changed code position for error handler at sign-in page

---

apps/web/src/services/auth/authenticator/external/GOOGLE_OAUTH2/authenticator/google-auth.ts
apps/web/src/services/auth/authenticator/external/GOOGLE_OAUTH2/template/GOOGLE_OAUTH2.vue
apps/web/src/services/auth/authenticator/external/KEYCLOAK_OIDC/authenticator/keycloak-auth.ts
apps/web/src/services/auth/authenticator/local/template/ID_PW.vue
apps/web/src/services/auth/pages/KeycloakPage.vue
apps/web/src/services/auth/pages/MultiFactorAuthPage.vue
apps/web/src/services/project/pages/ProjectDetailPage.vue

feat: apply mfa at google/keycloak oAuth

---

apps/web/src/router/index.ts
apps/web/src/store/app-context/workspace/user-workspace-store.ts
apps/web/src/store/modules/user/actions.ts

fix: apply missed handling error

---

apps/web/src/services/administration/components/WorkspacesCreateModal.vue

fix: after workspace created, check workspace count

---

apps/web/src/services/administration/components/UserManagementTable.vue
apps/web/src/services/administration/pages/UserMainPage.vue

By using `isGrantInProgress` instead of `isAdminMode`

fix: fix userMainPage type error issue

---

apps/web/src/App.vue
apps/web/src/common/modules/navigations/gnb/MyPageGNB.vue
apps/web/src/common/modules/navigations/gnb/modules/GNBAdminToggleButton.vue
apps/web/src/common/modules/navigations/gnb/modules/GNBHeader.vue
apps/web/src/common/modules/navigations/gnb/modules/MyPageGNBHeader.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-menu/modules/dashboard-recent-favorite/modules/GNBDashboardMenu.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-profile/GNBProfile.vue
apps/web/src/common/modules/popup/notice/NoticePopup.vue
apps/web/src/services/administration/pages/UserMainPage.vue
apps/web/src/store/app-context/app-context-store.ts
apps/web/src/store/modules/display/actions.ts
apps/web/src/store/modules/display/getters.ts
apps/web/src/store/modules/display/index.ts
apps/web/src/store/modules/display/mutations.ts
apps/web/src/store/modules/display/type.ts
apps/web/src/store/modules/user/actions.ts

SSIA
Please read order by commits

fix(grant): apply extended global grant loading

---

apps/web/src/common/modules/navigations/gnb/modules/GNBHeader.vue
apps/web/src/services/administration/pages/admin/AdminWorkspacesPage.vue
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

SSIA
Plz read order by commits

fix: solve feedback issues

---

apps/web/src/services/asset-inventory/pages/CloudServiceSearchPage.vue
apps/web/src/services/home-dashboard/components/PersonalHealthDashboard.vue
apps/web/src/services/project/components/ProjectSummaryPersonalHealthDashboardWidget.vue

fix: fix route bugs of personal health dashboard

---

apps/web/src/router/index.ts

fix: browser back button issue

---

apps/web/src/services/administration/components/UserManagementFormModal.vue
apps/web/src/services/administration/components/UserManagementFormNotificationEmailForm.vue
apps/web/src/services/my-page/components/UserAccountNotificationEmail.vue

fix: fixed notification validation

---

apps/web/src/common/modules/navigations/gnb/modules/GNBHeader.vue
apps/web/src/router/index.ts

fix: solve minor issue

---

apps/web/src/services/project/components/ProjectSummaryPersonalHealthDashboardWidget.vue

fix: fix phd routing bug

---

apps/web/src/router/index.ts
apps/web/src/services/alert-manager/components/AlertDetailInfoTable.vue
apps/web/src/services/alert-manager/components/AlertDetailResponder.vue
apps/web/src/services/alert-manager/components/AlertDetailSummary.vue
apps/web/src/services/alert-manager/components/AlertDetailSummaryAssignModal.vue
apps/web/src/services/alert-manager/components/AlertDetailTabsDetails.vue
apps/web/src/services/alert-manager/components/AlertDetailTitleEditModal.vue
apps/web/src/services/alert-manager/components/AlertMainAcknowledgeModal.vue
apps/web/src/services/alert-manager/pages/AlertDetailPage.vue
apps/web/src/services/alert-manager/stores/alert-assign-user-store.ts
apps/web/src/services/alert-manager/stores/alert-page-store.ts
packages/core-lib/src/space-connector/service-api.ts
packages/core-lib/src/space-connector/token-api.ts

fix: make all workspace member can be assigned to alert

---

apps/web/src/common/components/editor/TextEditorViewer.vue
apps/web/src/common/components/scoped-notification/ScopedNotification.vue
apps/web/src/common/modules/navigations/gnb/modules/GNBHeader.vue
apps/web/src/common/modules/popup/notice/modules/NoticePopupItem.vue
apps/web/src/router/index.ts
apps/web/src/services/administration/components/UserManagementAddUser.vue
apps/web/src/services/alert-manager/components/AlertDetailInfoTable.vue
apps/web/src/services/alert-manager/components/AlertDetailResponder.vue
apps/web/src/services/alert-manager/components/AlertDetailSummary.vue
apps/web/src/services/alert-manager/components/AlertDetailSummaryAssignModal.vue
apps/web/src/services/alert-manager/components/AlertDetailTabsDetails.vue
apps/web/src/services/alert-manager/components/AlertDetailTitleEditModal.vue
apps/web/src/services/alert-manager/components/AlertMainAcknowledgeModal.vue
apps/web/src/services/alert-manager/components/EscalationPolicyDataTable.vue
apps/web/src/services/alert-manager/components/EscalationPolicyForm.vue
apps/web/src/services/alert-manager/pages/AlertDetailPage.vue
apps/web/src/services/alert-manager/stores/alert-assign-user-store.ts
apps/web/src/services/alert-manager/stores/alert-page-store.ts
apps/web/src/services/auth/pages/KeycloakPage.vue
apps/web/src/services/cost-explorer/pages/BudgetDetailPage.vue
apps/web/src/services/home-dashboard/components/AllSummary.vue
apps/web/src/services/project/components/ProjectMainCardList.vue
apps/web/src/services/project/components/ProjectSummaryAllSummaryWidget.vue
apps/web/src/services/project/components/ProjectSummaryPersonalHealthDashboardWidget.vue
packages/core-lib/src/space-connector/service-api.ts
packages/core-lib/src/space-connector/token-api.ts
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

Merge 'cloudforet-io/feature-workspace-fundamental' by PR #2883

---

apps/web/src/services/administration/components/UserManagementAddUser.vue

SSIA
- quest: https://pyengine.atlassian.net/browse/QA-1287

feat: apply auty type at user invitation modal

---

apps/web/src/common/modules/navigations/gnb/modules/GNBHeader.vue
apps/web/src/router/index.ts

fix: apply proper router to all workspaces button & handle browser back button

---

apps/web/src/common/modules/tags/tags-panel/TagsPanel.vue
apps/web/src/services/administration/components/UserManagementHeader.vue
apps/web/src/services/administration/components/UserManagementTabTag.vue
apps/web/src/services/alert-manager/components/EscalationPolicyFormRulesInput.vue
apps/web/src/services/asset-inventory/components/ServiceAccountBaseInformation.vue
apps/web/src/services/asset-inventory/components/ServiceAccountCredentials.vue
apps/web/src/services/asset-inventory/pages/CollectorDetailPage.vue
apps/web/src/services/dashboards/components/DashboardManageVariableOverlay.vue
apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
apps/web/src/services/dashboards/pages/admin/AdminDashboardMainPage.vue
apps/web/src/services/project/components/ProjectMainProjectTree.vue
apps/web/src/services/project/pages/ProjectNotificationAddPage.vue
packages/language-pack/console-translation-2.8.babel
packages/language-pack/ja.json
packages/language-pack/ko.json
packages/mirinae/src/data-display/heading/PHeading.vue
packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.stories.mdx
packages/mirinae/src/inputs/dropdown/select-dropdown/components/dropdown-button.vue

- (console) [Adjusting Text Length with Flex](https://pyengine.atlassian.net/browse/QA-1294)
- (translation) [ Add translation at workspace dropdown list](https://pyengine.atlassian.net/browse/QA-1297)
- (console) [Remove duplicate instances of the 'general-page-layout' component](https://pyengine.atlassian.net/browse/QA-1298)
- (mirinae) [Apply truncate at select dropdown button's text at badge case](https://pyengine.atlassian.net/browse/QA-1303)
- (mirinae) [Apply justify-end at heading's extra slot](https://pyengine.atlassian.net/browse/QA-1305)

refactor: apply QA issue 

---

apps/web/src/services/asset-inventory/components/CollectorMainContents.vue

fix(collector-main-page): fix query search bug

---

apps/web/src/router/admin-domain-service-routes.ts
apps/web/src/router/index.ts
apps/web/src/router/integral-routes.ts

Revert "fix: do not warn no workspaceId param on routing"

---

apps/web/src/common/modules/navigations/gnb/constants/constant.ts
apps/web/src/common/modules/navigations/gnb/helpers/gnb-logo-helper.ts
apps/web/src/common/modules/navigations/gnb/modules/GNBHeader.vue
apps/web/src/common/modules/navigations/gnb/modules/GNBLogoIcon.vue
apps/web/src/common/modules/navigations/gnb/modules/MyPageGNBHeader.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-menu/GNBMenu.vue
apps/web/src/common/modules/navigations/gnb/types/type.ts
apps/web/src/services/administration/components/WorkspacesCreateModal.vue

fix(workspace-icon): create workspace theme icon

---

apps/web/src/lib/menu/menu-architecture.ts
apps/web/src/lib/reference/referenceRouter.ts
apps/web/src/lib/reference/type.ts
apps/web/src/router/admin-routes.ts
apps/web/src/services/asset-inventory/AssetInventoryLNB.vue
apps/web/src/services/asset-inventory/components/CollectorBaseInfoSection.vue
apps/web/src/services/asset-inventory/components/CollectorCreateStep3.vue
apps/web/src/services/asset-inventory/components/CollectorHistoryJobTaskDetails.vue
apps/web/src/services/asset-inventory/components/CollectorHistoryJobTaskErrorList.vue
apps/web/src/services/asset-inventory/components/CollectorHistoryJobTaskTable.vue
apps/web/src/services/asset-inventory/components/CollectorMainContents.vue
apps/web/src/services/asset-inventory/pages/CollectorDetailPage.vue
apps/web/src/services/asset-inventory/pages/admin/AdminCollectHistoryJobPage.vue
apps/web/src/services/asset-inventory/pages/admin/AdminCollectorCreatePage.vue
apps/web/src/services/asset-inventory/pages/admin/AdminCollectorDetailPage.vue
apps/web/src/services/asset-inventory/pages/admin/AdminCollectorHistoryPage.vue
apps/web/src/services/asset-inventory/pages/admin/AdminCollectorMainPage.vue
apps/web/src/services/asset-inventory/routes/admin/routes.ts
apps/web/src/services/asset-inventory/stores/collector-page-store.ts

feat(collector-admin): add collector admin mode

---

apps/web/src/common/modules/navigations/gnb/modules/gnb-header/GNBHeader.vue
apps/web/src/services/administration/components/WorkspacesCreateModal.vue

fix(workspace-create): add additional validation (theme)

---

apps/web/src/services/asset-inventory/components/CollectorJobStatusIcon.vue
apps/web/src/services/asset-inventory/components/RecentCollectorJobList.vue
apps/web/src/services/asset-inventory/types/collector-main-page-type.ts

fix(collector-main-page): fix job icon Routing error

---

apps/web/src/services/administration/components/WorkspacesCreateModal.vue

fix(workspace-create): edit style

---

apps/web/src/common/composables/grant-scope-guard/index.ts
apps/web/src/common/modules/navigations/gnb/modules/gnb-menu/modules/dashboard-recent-favorite/modules/GNBDashboardMenu.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-noti/modules/GNBNoticeTab.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-recent-favorite/modules/GNBFavorite.vue
apps/web/src/common/modules/navigations/gnb/modules/gnb-recent-favorite/modules/GNBRecent.vue
apps/web/src/common/modules/popup/notice/NoticePopup.vue
apps/web/src/common/modules/widgets/DailyUpdates.vue
apps/web/src/services/administration/pages/UserMainPage.vue
apps/web/src/services/administration/pages/admin/AdminWorkspacesPage.vue
apps/web/src/services/asset-inventory/components/CloudServices.vue
apps/web/src/services/home-dashboard/components/AllSummary.vue
apps/web/src/services/home-dashboard/components/AllSummaryDataSummary.vue
apps/web/src/services/home-dashboard/components/CollectingProgress.vue
apps/web/src/services/home-dashboard/components/FavoritesWidget.vue
apps/web/src/services/home-dashboard/components/PersonalHealthDashboard.vue
apps/web/src/services/home-dashboard/components/ResourceMap.vue
apps/web/src/services/home-dashboard/components/ServiceAccounts.vue
apps/web/src/services/home-dashboard/components/TopProjects.vue
apps/web/src/services/home-dashboard/components/TrustedAdvisor.vue
apps/web/src/services/home-dashboard/components/TrustedAdvisorOverall.vue

SSIA
Plz read order by commits

fix: create grant-scope-guard hook and apply

---

apps/web/src/services/asset-inventory/components/CollectorCreateStep4.vue
apps/web/src/services/asset-inventory/pages/admin/AdminCollectorDetailPage.vue
apps/web/src/services/asset-inventory/stores/collector-job-store.ts

fix: fix qa bugs of collector admin center

---

apps/web/src/services/asset-inventory/components/CloudServiceDetail.vue

fix: change the wrong api client

---

apps/web/src/common/modules/navigations/gnb/modules/gnb-header/GNBHeader.vue

fix: apply workspace router

---

apps/web/src/services/alert-manager/components/AlertDetailTitleEditModal.vue

SSIA
- quest: https://pyengine.atlassian.net/browse/QA-1293

chore: changed loading default state

---

packages/core-lib/src/space-connector/token-api.ts

fix: change accessToken expire-check-time

---

apps/web/src/services/alert-manager/components/AlertDetailTitleEditModal.vue

fix: fixed minor bug

---

apps/web/src/services/project/components/ProjectMainCardList.vue

fix: fix project card undefined bug

---

apps/web/src/services/cost-explorer/components/BudgetCreatePeriodSelect.vue
apps/web/src/services/cost-explorer/pages/BudgetDetailPage.vue

fix: fix case for scoped notification in budget detail page & set min, max for budget period

---

apps/web/src/router/index.ts
apps/web/src/store/modules/user/actions.ts

fix(grant): combine grant and load reference

---

apps/web/src/common/modules/navigations/gnb/GNB.vue
apps/web/src/router/index.ts
apps/web/src/store/modules/user/actions.ts

fix: add router catch to router duplicate-call case

---

apps/web/src/common/pages/NoResourcePage.vue
apps/web/src/services/asset-inventory/pages/CloudServiceSearchPage.vue
apps/web/src/services/asset-inventory/pages/CloudServiceTypeSearchPage.vue
apps/web/src/services/asset-inventory/routes/routes.ts

fix: fix no-resource routing bug

---

apps/web/src/services/dashboards/widgets/asset-widgets/severity-status-by-service/SeverityStatusByServiceWidget.vue

fix: do not show null service in widget

---

apps/web/src/services/dashboards/widgets/_base-widgets/base-count-of-findings/BaseCountOfFindingsWidget.vue
apps/web/src/services/dashboards/widgets/asset-widgets/severity-status-by-service/SeverityStatusByServiceWidget.vue

fix: fix temp query

---

apps/web/src/services/asset-inventory/components/ServiceAccountCredentials.vue
apps/web/src/services/asset-inventory/pages/ServiceAccountDetailPage.vue

fix: fix the data loader rendering bug

---

apps/web/src/services/dashboards/stores/widget-form-store.ts
apps/web/src/services/dashboards/widgets/asset-widgets/total-fail-findings-history/TotalFailFindingsHistoryWidget.vue
apps/web/src/services/dashboards/widgets/asset-widgets/trend-of-pass-and-fail-findings/TrendOfPassAndFailFindingsWidget.vue

fix(compliance-widget): fix key for finding_count

---

apps/web/src/services/cost-explorer/components/CostAnalysisDataTable.vue

fix: fix filter key

---

apps/web/src/services/asset-inventory/components/ServiceAccountCredentials.vue
apps/web/src/services/asset-inventory/pages/ServiceAccountDetailPage.vue
apps/web/src/services/cost-explorer/components/CostAnalysisDataTable.vue
apps/web/src/services/dashboards/stores/widget-form-store.ts
apps/web/src/services/dashboards/widgets/asset-widgets/total-fail-findings-history/TotalFailFindingsHistoryWidget.vue
apps/web/src/services/dashboards/widgets/asset-widgets/trend-of-pass-and-fail-findings/TrendOfPassAndFailFindingsWidget.vue

Feature workspace fundametals

---

apps/web/src/services/asset-inventory/components/CloudServiceListCard.vue
apps/web/src/services/asset-inventory/components/CloudServicePeriodFilter.vue
apps/web/src/services/asset-inventory/components/CloudServiceToolbox.vue
apps/web/src/services/asset-inventory/pages/CloudServiceDetailPage.vue

fix: fix period bug in cloud service page

---

apps/web/src/services/dashboards/components/DashboardCostWidgetValueOptionDropdown.vue

fix: apply no item

---

apps/web/src/services/asset-inventory/components/CollectorCurrentStatus.vue
apps/web/src/services/asset-inventory/components/CollectorHistoryJobBasicInformation.vue

fix: fix routing bugs (collector, job history)

---

apps/web/src/services/cost-explorer/components/BudgetDetailHeading.vue

fix: set back location in budget detail page

---

apps/web/src/common/modules/widgets/DailyUpdates.vue

fix(DailyUpdates): fix params

---

apps/web/src/services/dashboards/widgets/asset-widgets/total-fail-findings-history/TotalFailFindingsHistoryWidget.vue

fix: use current date

---

apps/web/src/services/asset-inventory/components/CloudServiceDetail.vue
apps/web/src/services/asset-inventory/components/CollectorMainContentItem.vue

SSIA
[QA-1278](https://pyengine.atlassian.net/browse/QA-1278)

fix: fix keyword search bugs(cloud service detail) & update the badge design of collector

---

apps/web/src/common/modules/navigations/gnb/modules/gnb-header/GNBHeader.vue

fix: edit public image path for build error

---

apps/web/src/services/dashboards/components/DashboardManageVariableTable.vue

SSIA
[QA-1352](https://pyengine.atlassian.net/browse/QA-1352)

fix(variable): apply variable type filtering

---

apps/web/src/App.vue
apps/web/src/common/modules/navigations/gnb/modules/GNBToolset.vue
apps/web/src/services/auth/pages/SignInPage.vue
apps/web/src/store/modules/user/actions.ts

fix: add clearing grant info

---

packages/mirinae/src/inputs/context-menu/PContextMenu.vue

[QA-1349](https://pyengine.atlassian.net/browse/QA-1349)

fix(context-menu): edit clear-all menu style

---

apps/web/src/services/asset-inventory/components/ServiceAccountBaseInformationDetail.vue
apps/web/src/services/asset-inventory/helpers/dynamic-ui-schema-generator/index.ts
apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue
apps/web/src/services/asset-inventory/stores/service-account-schema-store.ts
apps/web/src/store/modules/reference/provider/actions.ts

[QA-1263](https://pyengine.atlassian.net/browse/QA-1263)

refactor: refactor the api request of serviceAccountPage

---

packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

fix: update value of field label

---

apps/web/src/services/asset-inventory/pages/CloudServiceDetailPage.vue

fix: add query filter to excelQueryHelper when page is initiated

---

apps/web/src/services/alert-manager/components/AlertMainDataTable.vue

fix: separate duration and created field at alert data table
