apps/web/src/services/asset-inventory/stores/service-account-schema-store.ts
=> fix: fix the service account schema bug

apps/web/src/services/cost-explorer/components/CostAnalysisDataTable.vue, apps/web/src/services/cost-explorer/components/CostAnalysisDataTableDataTypeDropdown.vue, apps/web/src/store/reference/cost-data-source-reference-store.ts
=> feat: add the cost_data_keys option to costAnalysisDataTable

apps/web/src/services/asset-inventory/components/CollectorFormAttachedServiceAccount.vue
=> fix: add use-fixed-menu-style option

apps/web/src/services/dashboards/components/WidgetViewModeModalSidebar.vue, apps/web/src/services/dashboards/widgets/_composables/use-widget/merge-base-widget-state.ts, apps/web/src/services/dashboards/widgets/_composables/use-widget/use-widget-frame.ts, apps/web/src/services/dashboards/widgets/_helpers/__tests__/widget-schema-helper.test.ts, apps/web/src/services/dashboards/widgets/_helpers/widget-schema-helper.ts
=> fix: update getNonInheritedWidgetOptionsAmongUsedVariables to fix dashboard option edit bug

apps/web/src/services/asset-inventory/components/CollectorFormAttachedServiceAccount.vue, packages/mirinae/src/hooks/context-menu-controller/index.ts, packages/mirinae/src/hooks/context-menu-fixed-style/index.ts, packages/mirinae/src/inputs/context-menu/PContextMenu.vue, packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
https://github.com/cloudforet-io/console/assets/50662170/9cf5ba68-f841-434f-96a9-56c58d855f35
https://github.com/cloudforet-io/console/assets/50662170/46c2f14f-a60f-4298-8b51-f3b20d2ed395
=> fix(mirinae): fix the ui bug of contextMenu

apps/web/src/common/modules/navigations/gnb/modules/gnb-menu/GNBMenu.vue
=> fix(gnb-menu): apply loading to gnb menu selected indicator

apps/web/src/App.vue, apps/web/src/common/modules/navigations/gnb/modules/gnb-profile/GNBProfile.vue, apps/web/src/common/modules/popup/notice/NoticePopup.vue, apps/web/src/lib/access-control/index.ts, apps/web/src/lib/site-initializer/api-client.ts, apps/web/src/lib/site-initializer/workspace.ts, apps/web/src/router/constant.ts, apps/web/src/router/helpers/route-helper.ts, apps/web/src/router/index.ts, apps/web/src/router/integral-routes.ts, apps/web/src/router/type.ts, apps/web/src/services/auth/helpers/default-route-helper.ts, apps/web/src/services/auth/pages/SignInPage.vue, apps/web/src/services/my-page/routes/routes.ts, apps/web/src/shims-vue-router.d.ts, apps/web/src/store/modules/display/getters.ts, apps/web/src/store/modules/user/actions.ts, packages/core-lib/src/space-connector/index.ts
=> refactor: router & grant

apps/web/src/router/index.ts
=> fix: add workspace to workspace case

apps/web/src/common/composables/proper-route-location/index.ts, apps/web/src/common/modules/favorites/favorite-list/FavoriteList.vue, apps/web/src/services/administration/AdministrationLNB.vue, apps/web/src/services/alert-manager/AlertManagerLNB.vue, apps/web/src/services/asset-inventory/AssetInventoryLNB.vue, apps/web/src/services/cost-explorer/CostExplorerLNB.vue
=> fix: apply workspaceId in useProperRoute hook

apps/web/src/App.vue, apps/web/src/common/composables/error/errorHandler.ts, apps/web/src/common/modules/navigations/gnb/GNB.vue, apps/web/src/lib/access-control/index.ts, apps/web/src/router/index.ts, apps/web/src/services/auth/pages/KB_SSOPage.vue, apps/web/src/services/auth/pages/KeycloakPage.vue
=> fix: remove access-level helpers & apply refactored sign-in callback

apps/web/src/lib/access-control/config.ts, apps/web/src/lib/access-control/index.ts, apps/web/src/router/error-routes.ts, apps/web/src/router/index.ts, apps/web/src/router/integral-routes.ts, apps/web/src/services/administration/routes/routes.ts, apps/web/src/services/alert-manager/routes/routes.ts, apps/web/src/services/asset-inventory/routes/routes.ts, apps/web/src/services/auth/routes/routes.ts, apps/web/src/services/cost-explorer/routes/routes.ts, apps/web/src/services/dashboards/routes/routes.ts, apps/web/src/services/home-dashboard/routes/routes.ts, apps/web/src/services/info/routes/admin/routes.ts, apps/web/src/services/info/routes/routes.ts, apps/web/src/services/my-page/routes/routes.ts, apps/web/src/services/project/pages/ProjectDetailPage.vue, apps/web/src/services/project/routes/routes.ts, apps/web/src/shims-vue-router.d.ts
=> fix: remove access-level

apps/web/src/App.vue, apps/web/src/common/modules/navigations/gnb/modules/gnb-recent-favorite/modules/GNBFavorite.vue, apps/web/src/common/modules/navigations/gnb/modules/gnb-recent-favorite/modules/GNBRecent.vue, apps/web/src/common/modules/popup/notice/NoticePopup.vue
=> fix: solve small issues after router-improvement

apps/web/src/services/alert-manager/components/AlertMainAcknowledgeModal.vue
=> fix: assign to me checkbox must be enabled only for workspace members

apps/web/src/services/dashboards/components/DashboardVariableDropdown.vue
=> fix: add clear-selection event to dashboard variable dropdown

apps/web/src/common/composables/proper-route-location/index.ts, apps/web/src/router/index.ts, apps/web/src/services/administration/components/UserManagementTabAssignedRole.vue, apps/web/src/services/administration/components/UserManagementTabProjects.vue, apps/web/src/services/alert-manager/components/AlertDetailInfoTable.vue, apps/web/src/services/alert-manager/components/AlertDetailInfoTableProject.vue, apps/web/src/services/alert-manager/components/AlertListItem.vue, apps/web/src/services/alert-manager/components/AlertMainDataTable.vue, apps/web/src/services/alert-manager/components/AlertMainDataTableTriggeredByField.vue, apps/web/src/services/alert-manager/components/EscalationPolicyDataTable.vue, apps/web/src/services/alert-manager/components/EscalationPolicyForm.vue, apps/web/src/services/alert-manager/components/EscalationPolicyFormRulesInput.vue, apps/web/src/services/asset-inventory/components/CollectorDetailAttachedServiceAccounts.vue, apps/web/src/services/asset-inventory/components/CollectorHistoryJobBasicInformation.vue, apps/web/src/services/asset-inventory/components/CollectorHistoryJobTaskTable.vue, apps/web/src/services/asset-inventory/components/CollectorPluginContents.vue, apps/web/src/services/asset-inventory/components/ServiceAccountAttachedGeneralAccounts.vue, apps/web/src/services/asset-inventory/components/ServiceAccountCredentials.vue, apps/web/src/services/asset-inventory/components/ServiceAccountProjectDetail.vue, apps/web/src/services/asset-inventory/pages/admin/AdminCollectorDetailPage.vue, apps/web/src/services/cost-explorer/components/BudgetDetailInfo.vue, apps/web/src/services/cost-explorer/components/BudgetDetailNotifications.vue, apps/web/src/services/cost-explorer/components/BudgetDetailNotificationsConditionSettingModal.vue, apps/web/src/services/project/components/ProjectAlertEventRuleContent.vue, apps/web/src/services/project/components/ProjectAlertSettingsEscalationPolicy.vue, apps/web/src/services/project/components/ProjectSummaryPersonalHealthDashboardWidget.vue
=> fix: apply getProperRouteLocation to new-tab

apps/web/src/services/asset-inventory/components/CloudServiceDetail.vue, apps/web/src/services/asset-inventory/components/CloudServiceDetailMultipleSelectedData.vue, apps/web/src/services/asset-inventory/components/ServiceAccountBaseInformationDetail.vue, apps/web/src/services/asset-inventory/components/ServiceAccountCredentialsDetail.vue, apps/web/src/services/asset-inventory/pages/CloudServiceDetailPage.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue
=> fix: apply workspace_id to referenceFieldFormatter

apps/web/src/services/asset-inventory/pages/CloudServiceSearchPage.vue, apps/web/src/services/asset-inventory/pages/CloudServiceTypeSearchPage.vue
=> fix: apply new workspace path

apps/web/src/common/modules/navigations/gnb/modules/GNBToolset.vue, apps/web/src/common/modules/navigations/gnb/modules/gnb-search/GNBSearch.vue, apps/web/src/common/modules/navigations/gnb/modules/gnb-search/modules/GNBSearchInput.vue, apps/web/src/services/dashboards/components/DashboardCustomize.vue, apps/web/src/services/dashboards/components/DashboardCustomizePageName.vue
- (Create Dashboard) [fixing the issue of 'invalid message'](https://pyengine.atlassian.net/browse/QA-1370)
- (GNB) [fixed tooltip issue at search input](https://pyengine.atlassian.net/browse/QA-1372)
=> fix: fixed QA issue

apps/web/src/services/dashboards/widgets/_base-widgets/base-pie/BasePieWidget.vue, apps/web/src/services/dashboards/widgets/_types/widget-data-table-type.ts, apps/web/src/services/dashboards/widgets/asset-widgets/trend-of-pass-and-fail-findings/TrendOfPassAndFailFindingsWidget.vue, apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region-multi-fields/CostByRegionMultiFieldsWidget.vue, apps/web/src/services/dashboards/widgets/cost-widgets/cost-summary-multi-fields/CostSummaryMultiFieldsWidget.vue
=> fix: fix wrong import

apps/web/src/services/asset-inventory/helpers/dynamic-ui-schema-generator/dynamic-layout-schema-template.ts, apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue
=> fix: fix wrong type referencing issue

apps/web/src/services/project/components/ProjectAlertEventRuleConditionForm.vue, packages/mirinae/src/hooks/context-menu-controller/index.ts, packages/mirinae/src/hooks/context-menu-fixed-style/index.ts, packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
=> feat(mirinae): when 'useFixedMenuStyle' is true, the menu stays visible for multiple selections

apps/web/src/common/modules/navigations/gnb/modules/gnb-noti/GNBNoti.vue, apps/web/src/common/modules/popup/notice/NoticePopup.vue, apps/web/src/router/index.ts, apps/web/src/services/info/pages/admin/AdminNoticeMainPage.vue
=> fix: improve router common process

apps/web/src/services/administration/components/UserManagementHeader.vue, apps/web/src/services/administration/components/UserManagementTabDetail.vue, apps/web/src/services/administration/components/UserManagementTabTag.vue, apps/web/src/services/administration/components/UserManagementTabWorkspace.vue, apps/web/src/services/administration/components/UserManagementTable.vue, apps/web/src/services/auth/pages/SignInPage.vue, apps/web/src/services/info/pages/admin/AdminNoticeMainPage.vue
=> fix: edit button design & add router defensive code

apps/web/src/services/asset-inventory/stores/service-account-schema-store.ts
=> chore: modified to show default schema when there is no schema

apps/web/src/services/administration/components/UserManagementAddAdminRole.vue, apps/web/src/services/administration/components/UserManagementAddModal.vue, apps/web/src/services/asset-inventory/components/CloudServiceFilterModal.vue, apps/web/src/services/asset-inventory/components/CloudServiceFilterSearchDropdown.vue, apps/web/src/services/dashboards/components/DashboardWidgetAddModalDefaultTab.vue, apps/web/src/services/dashboards/components/DashboardWidgetOptionDropdown.vue, apps/web/src/services/project/components/ProjectMemberInviteModal.vue, packages/mirinae/src/feedbacks/modals/button-modal/PButtonModal.stories.mdx, packages/mirinae/src/feedbacks/modals/button-modal/PButtonModal.vue, packages/mirinae/src/feedbacks/modals/button-modal/story-helper.ts, packages/mirinae/src/hooks/context-menu-controller/index.ts, packages/mirinae/src/hooks/context-menu-fixed-style/index.ts, packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.stories.mdx, packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue, packages/mirinae/src/inputs/dropdown/select-dropdown/story-helper.ts
=> feat: assigning the id attribute to the necessary element

packages/mirinae/src/inputs/forms/json-schema-form/PJsonSchemaForm.stories.mdx, packages/mirinae/src/inputs/forms/json-schema-form/PJsonSchemaForm.vue, packages/mirinae/src/inputs/forms/json-schema-form/components/PEMKeyFormat.vue, packages/mirinae/src/inputs/forms/json-schema-form/custom-schema.ts, packages/mirinae/src/inputs/forms/json-schema-form/helpers/inner-schema-helper.ts, packages/mirinae/src/inputs/forms/json-schema-form/mock.ts, packages/mirinae/src/inputs/forms/json-schema-form/type.ts
=> feat(mirinae): add pem_key format to PJSONSchemaFrom

.github/workflows/dispatch_dev_build.yaml
=> feat: update dispatch_dev_build.yaml

.github/workflows/dispatch_dev_build.yaml
=> chore: update dispatch_dev_build.yaml

apps/web/src/common/modules/navigations/gnb/modules/gnb-header/GNBHeader.vue, apps/web/src/router/index.ts, apps/web/src/store/modules/error/getters.ts, apps/web/src/store/modules/user/actions.ts
- Remove all workspaces menu in gnb header workspace menu
- Edit grant fail scenario
=> fix: remove all workspace menu in gnb & apply scenario

apps/web/src/schema/cost-analysis/cost-report-config/api-verbs/list.ts, apps/web/src/schema/cost-analysis/cost-report-config/api-verbs/update-recipients.ts, apps/web/src/schema/cost-analysis/cost-report-config/api-verbs/update.ts, apps/web/src/schema/cost-analysis/cost-report-config/model.ts, apps/web/src/schema/cost-analysis/cost-report-config/type.ts, apps/web/src/schema/cost-analysis/cost-report-data/api-verbs/analyze.ts, apps/web/src/schema/cost-analysis/cost-report-data/api-verbs/list.ts, apps/web/src/schema/cost-analysis/cost-report-data/model.ts, apps/web/src/schema/cost-analysis/cost-report-data/type.ts, apps/web/src/schema/cost-analysis/cost-report/api-verbs/get-url.ts, apps/web/src/schema/cost-analysis/cost-report/api-verbs/get.ts, apps/web/src/schema/cost-analysis/cost-report/api-verbs/list.ts, apps/web/src/schema/cost-analysis/cost-report/api-verbs/send.ts, apps/web/src/schema/cost-analysis/cost-report/model.ts, apps/web/src/schema/cost-analysis/cost-report/type.ts
=> feat: add api schema of cost report

apps/web/src/schema/cost-analysis/cost-report-config/model.ts, apps/web/src/schema/cost-analysis/cost-report-data/model.ts, apps/web/src/schema/cost-analysis/cost-report/model.ts
=> chore: fix typo error

apps/web/src/schema/cost-analysis/cost-report-config/api-verbs/list.ts, apps/web/src/schema/cost-analysis/cost-report-config/api-verbs/update-recipients.ts, apps/web/src/schema/cost-analysis/cost-report-config/api-verbs/update.ts, packages/mirinae/src/navigation/pagination/date-pagination/PDatePagination.vue, packages/mirinae/src/navigation/pagination/date-pagination/story-helper.ts
=> feat(PDatePagination): add disableNextButton props

apps/web/src/services/cost-explorer/components/CostReportMonthlyTotalAmountSummaryCard.vue, apps/web/src/services/cost-explorer/components/CostReportOverviewCostTrendCard.vue, apps/web/src/services/cost-explorer/stores/cost-report-page-store.ts
=> feat: add cost-report-page-store.ts & update minor in pages

apps/web/src/services/cost-explorer/components/CostReportMonthlyTotalAmountSummaryCard.vue, apps/web/src/services/cost-explorer/components/CostReportSettingsModal.vue, apps/web/src/services/cost-explorer/components/CostReportUpcomingReportCard.vue, apps/web/src/services/cost-explorer/stores/cost-report-page-store.ts, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: update logic for upcoming issue date

apps/web/src/schema/cost-analysis/cost-report-config/api-verbs/update.ts, apps/web/src/services/cost-explorer/components/CostReportMonthlyTotalAmountSummaryCard.vue, apps/web/src/services/cost-explorer/components/CostReportOverviewCardTemplate.vue, apps/web/src/services/cost-explorer/components/CostReportUpcomingReportCard.vue
=> chore: fix minor style & type

apps/web/src/schema/cost-analysis/cost-report-data/api-verbs/analyze.ts, apps/web/src/services/cost-explorer/components/CostReportOverviewCostTrendCard.vue, apps/web/src/services/cost-explorer/components/CostReportRecipientsCard.vue
=> fix: fix logic for updating recipients

apps/web/src/lib/menu/menu-architecture.ts, apps/web/src/services/asset-inventory/AssetInventoryLNB.vue, apps/web/src/services/asset-inventory/routes/admin/routes.ts, apps/web/src/services/auth/pages/MultiFactorAuthPage.vue, apps/web/src/services/dashboards/components/DashboardCustomize.vue, apps/web/src/services/dashboards/components/DashboardCustomizePageName.vue
=> feat: apply admin route for asset inventory's admin mode

apps/web/src/services/dashboards/components/DashboardCustomizePageName.vue
=> fix: changed validation condition at create dashboard

apps/web/src/common/pages/ExpiredLinkPage.vue, apps/web/src/lib/site-initializer/sso.ts, apps/web/src/router/constant.ts, apps/web/src/router/error-routes.ts, apps/web/src/services/auth/components/ConsoleLogo.vue, apps/web/src/services/auth/components/SignInContainer.vue, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: add ExpiredLinkPage component

apps/web/src/schema/cost-analysis/cost-report-data/api-verbs/analyze.ts, apps/web/src/services/cost-explorer/components/CostReportMonthlyTotalAmountSummaryCard.vue, apps/web/src/services/cost-explorer/components/CostReportOverviewCostTrendCard.vue, apps/web/src/services/cost-explorer/components/CostReportOverviewCostTrendContent.vue
=> feat: set real api data to summary card

apps/web/src/services/cost-explorer/components/CostReportOverviewCostTrendCard.vue, apps/web/src/services/cost-explorer/components/CostReportOverviewCostTrendChart.vue, apps/web/src/services/cost-explorer/types/cost-report-data-type.ts, apps/web/src/services/project/components/ProjectMainCardList.vue
=> refactor: refactor components

apps/web/src/schema/cost-analysis/cost-report/model.ts, apps/web/src/services/cost-explorer/components/CostReportReportsTab.vue, apps/web/src/services/cost-explorer/stores/cost-report-page-store.ts
=> feat: apply link and period

apps/web/src/services/cost-explorer/components/CostReportMonthlyTotalAmountSummaryCard.vue, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> chore: update language and style

apps/web/src/services/cost-explorer/components/CostReportMonthlyTotalAmountSummaryCard.vue, apps/web/src/services/cost-explorer/components/CostReportReportsTab.vue
=> feat: minor change for QA

apps/web/src/lib/menu/menu-architecture.ts, apps/web/src/services/cost-explorer/CostExplorerLNB.vue, apps/web/src/services/cost-explorer/components/CostReportMonthlyTotalAmountSummaryCard.vue, apps/web/src/services/cost-explorer/pages/CostReportPage.vue, apps/web/src/services/cost-explorer/routes/routes.ts
=> feat: add cost report page for workspace owner

apps/web/src/services/cost-explorer/components/CostReportMonthlyTotalAmountSummaryCard.vue, apps/web/src/services/cost-explorer/components/CostReportOverviewCardTemplate.vue, apps/web/src/services/cost-explorer/components/CostReportOverviewCostTrendCard.vue, apps/web/src/services/cost-explorer/components/CostReportOverviewCostTrendChart.vue
=> fix: implement currencyMoneyFormatter

apps/web/src/services/cost-explorer/components/CostReportMonthlyTotalAmountSummaryCard.vue, apps/web/src/services/cost-explorer/components/CostReportOverviewCostTrendCard.vue, apps/web/src/services/cost-explorer/components/CostReportRecipientsCard.vue, apps/web/src/services/cost-explorer/components/CostReportUpcomingReportCard.vue, packages/language-pack/en.json
=> feat: update style for workspace owner

apps/web/src/services/cost-explorer/components/CostReportMonthlyTotalAmountSummaryCard.vue, apps/web/src/services/cost-explorer/components/CostReportOverviewCostTrendCard.vue, apps/web/src/services/cost-explorer/components/CostReportOverviewCostTrendChart.vue, apps/web/src/services/cost-explorer/components/CostReportUpcomingReportCard.vue, apps/web/src/services/cost-explorer/stores/cost-report-page-store.ts
=> chore: add loading logic in overview page

apps/web/src/schema/cost-analysis/cost-report-data/api-verbs/analyze.ts, apps/web/src/services/cost-explorer/components/CostReportMonthlyTotalAmountSummaryCard.vue, apps/web/src/services/cost-explorer/components/CostReportOverviewCostTrendCard.vue
=> fix: set `is_confirmed` params to analyze query

apps/web/src/services/cost-explorer/components/CostReportReportsTab.vue, apps/web/src/services/cost-explorer/pages/CostReportPage.vue, apps/web/src/services/cost-explorer/pages/admin/AdminCostReportPage.vue, apps/web/src/services/cost-explorer/stores/cost-report-page-store.ts
SSIA!! Please see order by commits
=> refactor: change function name and edit minor things & fetch cost-report-config when mount report page

apps/web/src/services/cost-explorer/components/CostReportMonthlyTotalAmountSummaryCard.vue
=> chore: set provider color to provider data

apps/web/src/common/components/cost-report-page/table-header.vue, apps/web/src/common/pages/CostReportPage.vue, apps/web/src/router/integral-routes.ts, apps/web/src/schema/monitoring/data-source/api-verbs/list.ts
=> feat(cost-report-page): apply table data & ui

apps/web/src/router/helpers/route-helper.ts
=> fix: add optional chaining

apps/web/src/services/cost-explorer/components/CostReportReportsTab.vue, apps/web/src/services/cost-explorer/components/CostReportResendModal.vue, apps/web/src/services/cost-explorer/pages/CostReportPage.vue, apps/web/src/services/cost-explorer/pages/admin/AdminCostReportPage.vue, apps/web/src/services/cost-explorer/stores/cost-report-page-store.ts
- Apply search
- Apply report link at resend modal
- quest: https://pyengine.atlassian.net/browse/QA-1382
=> refactor: apply search and report link

apps/web/src/services/cost-explorer/components/CostReportReportsTab.vue
=> fix: remove reverse

apps/web/src/services/cost-explorer/components/CostReportReportsTab.vue
=> chore: changed filter target

apps/web/src/services/cost-explorer/components/CostReportReportsTab.vue
=> feat: apply filter at makeDistinctValueHandler

apps/web/src/common/pages/CostReportPage.vue
=> fix: add default data for noData UI

apps/web/src/common/pages/CostReportDetailPage.vue, apps/web/src/router/integral-routes.ts, apps/web/src/services/auth/components/ConsoleLogo.vue
=> fix: change file name & apply mobile view port & modify to enable pdf download & fix logo bug

apps/web/src/common/modules/navigations/gnb/modules/gnb-menu/GNBSubMenu.vue, apps/web/src/lib/menu/menu-info.ts, apps/web/src/services/cost-explorer/CostExplorerLNB.vue, apps/web/src/services/cost-explorer/components/CostReportMonthlyTotalAmountSummaryCard.vue
=> feat: implement 'see details' link

apps/web/src/services/cost-explorer/components/CostReportOverviewCostTrendCard.vue, packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.stories.mdx
=> chore: remove deep at select-dropdown

apps/web/src/services/cost-explorer/components/CostReportReportsTab.vue
=> fix: fixed period query filter

apps/web/src/App.vue, apps/web/src/common/pages/CostReportDetailPage.vue, apps/web/src/lib/site-initializer/sso.ts, apps/web/src/router/constant.ts
- [QA-1399](https://pyengine.atlassian.net/browse/QA-1399)
- [QA-1416](https://pyengine.atlassian.net/browse/QA-1416)
=> fix: change formatter method & remove unnecessary modal

apps/web/src/schema/cost-analysis/cost-report-config/api-verbs/update.ts, apps/web/src/schema/cost-analysis/cost-report-config/model.ts, apps/web/src/services/cost-explorer/components/CostReportSettingsModal.vue, apps/web/src/services/cost-explorer/components/CostReportUpcomingReportCard.vue, apps/web/src/services/cost-explorer/stores/cost-report-page-store.ts, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
CostReportSettingsModal.vue
CostReportUpcomingReportCard.vue
=> feat: add language to report settings

apps/web/src/common/pages/CostReportDetailPage.vue, apps/web/src/router/additional-routes.ts, apps/web/src/router/integral-routes.ts, packages/mirinae/src/inputs/link/PLink.stories.mdx, packages/mirinae/src/inputs/link/PLink.vue, packages/mirinae/src/inputs/link/story-helper.ts
- Add `use-hash-scroll` to `p-link`
- Apply hash-scroll to `cost-report-detail-page`
Plz read order by commits~
=> fix(report-detail): apply hash-scroll

apps/web/src/services/cost-explorer/components/CostReportRecipientsCard.vue
=> chore: change style of role page button

apps/web/src/common/pages/CostReportDetailPage.vue
=> fix: fix page scroll bug in CostReportDetailPage & change currencyMoneyFormatter option

apps/web/src/services/cost-explorer/components/CostReportSettingsModal.vue
=> chore: set default badge to KRW

apps/web/src/common/modules/navigations/gnb/modules/gnb-noti/modules/GNBNotificationsTab.vue
=> fix: apply line break and fix link css issue of gnb noti modal

apps/web/src/services/cost-explorer/components/CostReportOverviewCostTrendChart.vue
Solve [this](https://pyengine.atlassian.net/browse/QA-1386)
https://github.com/cloudforet-io/console/assets/18563857/37f6c01d-e055-4f2d-82cf-8f64c64bda1d
=> feat: custom tooltip of trend chart

apps/web/src/services/cost-explorer/components/CostReportReportsTab.vue
=> chore: changed css

apps/web/src/common/pages/CostReportDetailPage.vue, packages/mirinae/src/inputs/link/PLink.vue
=> fix: fix anchor scroll bug & add loading process to costReportDetailPage

apps/web/src/common/composables/amcharts5/index.ts, apps/web/src/services/cost-explorer/components/CostReportMonthlyTotalAmountSummaryCard.vue, apps/web/src/services/cost-explorer/components/CostReportOverviewCostTrendChart.vue
=> fix: show perfect tooltip

apps/web/src/common/pages/CostReportDetailPage.vue, apps/web/src/services/cost-explorer/components/CostReportMonthlyTotalAmountSummaryCard.vue, apps/web/src/services/cost-explorer/components/CostReportOverviewCostTrendChart.vue
=> fix(cost-report): set label to provider name

apps/web/src/common/composables/date-range-formatter/__tests__/index.test.ts, apps/web/src/lib/menu/menu-architecture.ts, apps/web/src/services/asset-inventory/AssetInventoryLNB.vue, apps/web/src/services/asset-inventory/components/CloudServiceDetail.vue, apps/web/src/services/asset-inventory/components/CloudServiceDetailExcelExportOptionModal.vue, apps/web/src/services/asset-inventory/components/CloudServiceDetailMultipleSelectedData.vue, apps/web/src/services/asset-inventory/components/CloudServiceDetailTabs.vue, apps/web/src/services/asset-inventory/components/CloudServiceListCard.vue, apps/web/src/services/asset-inventory/components/CloudServiceToolbox.vue, apps/web/src/services/asset-inventory/pages/CloudServiceDetailPage.vue, apps/web/src/services/asset-inventory/routes/admin/routes.ts, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json, packages/mirinae/src/data-display/dynamic/dynamic-layout/templates/item/index.vue, packages/mirinae/src/data-display/dynamic/dynamic-layout/templates/list/index.vue, packages/mirinae/src/data-display/dynamic/dynamic-layout/templates/simple-table/index.vue
=> feat: apply admin mode at asset inventory

apps/web/src/services/asset-inventory/AssetInventoryLNB.vue
=> chore: fixed state status

apps/web/src/App.vue, apps/web/src/common/composables/date-range-formatter/__tests__/index.test.ts, apps/web/src/lib/site-initializer/sso.ts, apps/web/src/router/additional-routes.ts, apps/web/src/router/constant.ts
=> feat: change route name from 'cost-report' to 'cost-report-detail'

apps/web/src/services/asset-inventory/routes/admin/routes.ts
=> chore: apply redirect at base asset inventory page

apps/web/src/common/pages/CostReportDetailPage.vue, apps/web/src/services/cost-explorer/components/CostReportReportsTab.vue, apps/web/src/services/cost-explorer/components/CostReportResendModal.vue
=> feat: refactor and apply sorting to table data

apps/web/src/services/asset-inventory/AssetInventoryLNB.vue
=> fix: apply admin routes at asset inventory lnb

apps/web/src/services/cost-explorer/components/CostReportOverviewCostTrendCard.vue
=> fix: fix minor qa

apps/web/src/common/pages/CostReportDetailPage.vue, apps/web/src/services/cost-explorer/components/CostReportMonthlyTotalAmountSummaryCard.vue, apps/web/src/services/cost-explorer/components/CostReportUpcomingReportCard.vue, apps/web/src/services/cost-explorer/pages/CostReportPage.vue, apps/web/src/services/cost-explorer/stores/cost-report-page-store.ts, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> fix: fix minor qa things

apps/web/src/services/cost-explorer/CostExplorerContainer.vue, apps/web/src/services/cost-explorer/components/CostReportMonthlyTotalAmountSummaryCard.vue
=> fix: fix overflow bug in cost explorer & fix 'see detail' not shown in init

apps/web/src/common/composables/amcharts5/index.ts, apps/web/src/services/cost-explorer/components/CostReportMonthlyTotalAmountSummaryCard.vue
=> fix: fix chart overflow-x bug

apps/web/src/common/pages/CostReportDetailPage.vue
=> fix(cost-report-dtail-page): fix the width of table

apps/web/src/common/modules/navigations/gnb/modules/gnb-header/GNBHeader.vue, apps/web/src/common/modules/navigations/gnb/modules/gnb-header/WorkspaceLogoIcon.vue, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: apply markup

apps/web/src/services/cost-explorer/components/CostReportMonthlyTotalAmountSummaryCard.vue, apps/web/src/services/cost-explorer/components/CostReportOverviewCostTrendCard.vue, apps/web/src/services/cost-explorer/components/CostReportUpcomingReportCard.vue, apps/web/src/services/cost-explorer/pages/CostReportPage.vue, apps/web/src/services/cost-explorer/stores/cost-report-page-store.ts
=> feat: use recent report/issue date from api (not calculated value)

apps/web/src/services/asset-inventory/components/CollectorMainContentItem.vue
=> fix: fix status ui bug of collector card

apps/web/src/services/cost-explorer/components/CostReportMonthlyTotalAmountSummaryCard.vue
=> fix(cost-report): fix chart rendering bug

apps/web/src/services/cost-explorer/components/CostReportMonthlyTotalAmountSummaryCard.vue, apps/web/src/services/cost-explorer/components/CostReportUpcomingReportCard.vue
- **Bug Description**: Incorrect calculation of 'upcoming report date'.
- **Cause**: The 'upcoming date' was being calculated based on the published report, which resulted in unexpected dates when there was no report.
- **Resolution**: Calculate the 'upcoming report date' mechanically, not based on the published report.
=> fix: fix upcoming date

apps/web/src/lib/site-analytics/gtag.ts, apps/web/src/lib/site-initializer/analysis.ts
=> feat: change the page title value

apps/web/src/store/modules/domain/getters.ts
=> fix(integration): edit ext-menu spec

apps/web/src/services/asset-inventory/components/CloudServiceExcelExportOptionModal.vue, apps/web/src/services/asset-inventory/components/CloudServiceToolbox.vue, apps/web/src/services/asset-inventory/helpers/cloud-service-analyze-query-helper.ts, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat(cloud-service): create all data option to excel download

apps/web/src/common/modules/navigations/gnb/modules/gnb-header/GNBHeader.vue, apps/web/src/common/modules/portals/TopNotification.vue, apps/web/src/router/index.ts, apps/web/src/router/integral-routes.ts
=> fix(router): refactor router core logic

apps/web/src/services/asset-inventory/components/CloudServiceExcelExportOptionModal.vue
=> fix: fix so that when reopening the modal, the option is initialized to false

apps/web/src/schema/dashboard/_types/widget-type.ts, apps/web/src/services/dashboards/components/DashboardWidgetContainer.vue, apps/web/src/services/dashboards/components/WidgetFullModeModal.vue, apps/web/src/services/dashboards/components/WidgetFullModeModalSidebar.vue, apps/web/src/services/dashboards/widgets/_components/WidgetFrame.vue, apps/web/src/services/dashboards/widgets/_composables/use-widget/use-widget-frame.ts, apps/web/src/services/dashboards/widgets/_types/widget-type.ts, apps/web/src/services/dashboards/widgets/cost-widgets/monthly-cost/MonthlyCostWidget.vue
=> chore: change variable, component name & delete unused type property

apps/web/src/services/dashboards/components/DashboardWidgetContainer.vue
=> chore: fix minor mistake

apps/web/src/common/modules/navigations/gnb/modules/GNBToolset.vue, apps/web/src/common/modules/navigations/gnb/modules/gnb-search-clone/GNBSearch.vue, apps/web/src/common/modules/navigations/gnb/modules/gnb-search-clone/config.ts, apps/web/src/common/modules/navigations/gnb/modules/gnb-search-clone/modules/GNBSearchDropdown.vue, apps/web/src/common/modules/navigations/gnb/modules/gnb-search-clone/modules/GNBSearchInput.vue, apps/web/src/common/modules/navigations/gnb/modules/gnb-search-clone/type.ts
=> feat: clone gnbSearch component & refactor to setup script

apps/web/src/services/asset-inventory/components/CloudServiceExcelExportOptionModal.vue, packages/language-pack/en.json
=> fix: fix translation & minor bug

apps/web/src/common/modules/custom-table/custom-field-modal/CustomFieldModal.vue, apps/web/src/services/asset-inventory/pages/CloudServiceDetailPage.vue
=> refactor: hide workspace column at user mode

apps/web/src/services/cost-explorer/routes/admin/routes.ts, apps/web/src/services/cost-explorer/routes/routes.ts
=> feat: show landing page to cost report page

apps/web/src/common/modules/navigations/gnb/modules/GNBAdminToggleButton.vue
=> fix: fix admin toggle issue

apps/web/src/services/cost-explorer/routes/admin/routes.ts
=> fix(cost-explorer-landing): set admin route

apps/web/src/services/asset-inventory/stores/cloud-service-detail-page-store.ts
=> fix: remove dup item

apps/web/src/common/modules/navigations/gnb/GNB.vue, apps/web/src/common/modules/navigations/gnb/modules/GNBToolset.vue, apps/web/src/common/modules/navigations/gnb/modules/gnb-search-clone/GNBSearch.vue, apps/web/src/common/modules/navigations/gnb/modules/gnb-search-clone/modules/GNBSearchDropdown.vue, apps/web/src/common/modules/navigations/gnb/modules/gnb-search-clone/modules/GNBSearchInput.vue, apps/web/src/common/modules/navigations/gnb/modules/gnb-search-clone/store.ts, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
There was a style change that can be seen in the video.
https://github.com/cloudforet-io/console/assets/50662170/4dbd2f90-e162-4ef9-974e-807c098245f8
=> feat: update gnb style (Partially completed)

apps/web/src/services/dashboards/widgets/_composables/use-widget-lifecycle.ts, apps/web/src/services/dashboards/widgets/cost-widgets/monthly-cost/MonthlyCostWidget.vue
=> fix: delete width props from MonthlyCostWidget & set custom xaxis format

apps/web/src/App.vue, apps/web/src/common/modules/navigations/gnb/GNBContainer.vue, apps/web/src/common/modules/navigations/gnb/modules/GNBToolbox.vue, apps/web/src/common/modules/navigations/gnb/modules/gnb-menu/GNBInvisibleMenuDropdown.vue, apps/web/src/common/modules/navigations/gnb/modules/gnb-menu/GNBMenu.vue, apps/web/src/common/modules/navigations/gnb/modules/gnb-noti/GNBNoti.vue, apps/web/src/common/modules/navigations/gnb/modules/gnb-noti/modules/GNBNoticeTab.vue, apps/web/src/common/modules/navigations/gnb/modules/gnb-noti/modules/GNBNotificationsTab.vue, apps/web/src/common/modules/navigations/gnb/modules/gnb-profile/GNBProfile.vue, apps/web/src/common/modules/navigations/gnb/modules/gnb-recent-favorite/GNBRecentFavorite.vue, apps/web/src/common/modules/navigations/gnb/modules/gnb-recent-favorite/modules/GNBFavorite.vue, apps/web/src/common/modules/navigations/gnb/modules/gnb-recent-favorite/modules/GNBRecent.vue, apps/web/src/common/modules/navigations/gnb/modules/gnb-search-clone/GNBSearch.vue, apps/web/src/common/modules/navigations/gnb/modules/gnb-search-clone/modules/GNBSearchDropdown.vue, apps/web/src/common/modules/navigations/gnb/modules/gnb-search/GNBSearch.vue, apps/web/src/common/modules/navigations/gnb/modules/gnb-search/modules/GNBSearchDropdown.vue, apps/web/src/common/modules/page-layouts/OverlayPageLayout.vue, apps/web/src/common/modules/tags/tags-panel/modules/TagsOverlay.vue, apps/web/src/services/asset-inventory/components/CloudServiceHistoryDetailOverlay.vue, apps/web/src/store/global-ui/global-ui-store.ts, apps/web/src/styles/variables.cjs, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json, packages/mirinae/src/styles/variables.cjs
=> feat: create gnb toolbox

apps/web/src/App.vue, apps/web/src/common/modules/navigations/gnb/NavigationRail.vue, apps/web/src/common/modules/navigations/gnb/Toolbox.vue, apps/web/src/common/modules/page-layouts/LayoutContainer.vue
=> refactor: refactor rail icons

apps/web/src/common/modules/navigations/gnb/modules/gnb-search-clone/GNBSearch.vue, apps/web/src/common/modules/navigations/gnb/modules/gnb-search-clone/modules/GNBSearchDropdown.vue, apps/web/src/common/modules/navigations/gnb/modules/gnb-search-clone/modules/GNBSearchInput.vue, apps/web/src/common/modules/navigations/gnb/modules/gnb-search-clone/modules/gnb-search-dropdown/GNBSearchDropdown.vue, apps/web/src/common/modules/navigations/gnb/modules/gnb-search-clone/modules/gnb-search-dropdown/modules/GNBSearchEmpty.vue, apps/web/src/common/modules/navigations/gnb/modules/gnb-search-clone/modules/gnb-search-dropdown/modules/GNBSearchServiceTab.vue, apps/web/src/common/modules/navigations/gnb/modules/gnb-search-clone/modules/gnb-search-dropdown/modules/GNBSearchWorkspaceFilter.vue
=> feat: update gnbSearchDropdown architecture

apps/web/src/services/dashboards/components/DashboardCreateStep1.vue, apps/web/src/services/dashboards/components/DashboardCreateStep1SearchFilter.vue, apps/web/src/services/dashboards/pages/DashboardCreatePage.vue
=> fix(create-step1): markup

apps/web/src/schema/dashboard/_types/widget-type.ts, apps/web/src/services/dashboards/components/DashboardWidgetOptionDropdown.vue, apps/web/src/services/dashboards/stores/widget-form-store.ts
=> feat: delete `optional` type from `WidgetOptionsSchemaProperty`

apps/web/src/services/asset-inventory/components/ServiceAccountCredentialsForm.vue
=> feat: add provider filter to credentialsForm

apps/web/src/App.vue, apps/web/src/common/modules/navigations/gnb/NavigationRail.vue, apps/web/src/common/modules/page-layouts/LayoutContainer.vue, apps/web/src/lib/menu/menu-info.ts
=> feat: apply menu at navigation rail

apps/web/src/common/modules/navigations/gnb/modules/GNBToolset.vue, apps/web/src/common/modules/navigations/gnb/modules/gnb-search-clone/GNBSearch.vue, apps/web/src/common/modules/navigations/gnb/modules/gnb-search-clone/helper.ts, apps/web/src/common/modules/navigations/gnb/modules/gnb-search-clone/modules/GNBSearchInput.vue, apps/web/src/common/modules/navigations/gnb/modules/gnb-search-clone/modules/gnb-search-dropdown/GNBSearchDropdown.vue, apps/web/src/common/modules/navigations/gnb/modules/gnb-search-clone/modules/gnb-search-dropdown/modules/GNBSearchServiceTab.vue, apps/web/src/common/modules/navigations/gnb/modules/gnb-search-clone/store.ts
=> feat: refactor interaction event architecture & apply service tab

apps/web/src/services/cost-explorer/CostExplorerContainer.vue, apps/web/src/services/dashboards/DashboardsContainer.vue, apps/web/src/services/info/InfoContainer.vue, packages/mirinae/src/layouts/vertical-layout/PVerticalLayout.vue, packages/mirinae/src/translations/language-pack/babel.babel, packages/mirinae/src/translations/language-pack/en.json, packages/mirinae/src/translations/language-pack/ja.json, packages/mirinae/src/translations/language-pack/ko.json
=> feat: update PVerticalLayout

apps/web/src/common/modules/navigations/gnb/GNBToolbox.vue, packages/mirinae/src/navigation/breadcrumbs/PBreadcrumbs.vue, packages/mirinae/src/navigation/breadcrumbs/modules/BreadcrumbsEllipsisItem.vue, packages/mirinae/src/navigation/breadcrumbs/modules/BreadcrumbsItem.vue
=> feat: update PBreadcrumbs spec

apps/web/src/lib/variable-models/_base/resource-variable-model.ts, apps/web/src/lib/variable-models/_base/types.ts, apps/web/src/lib/variable-models/_helpers/resource-variable-list-helper.ts, apps/web/src/lib/variable-models/index.ts, apps/web/src/lib/variable-models/managed-model-config/base-managed-model-config.ts, apps/web/src/lib/variable-models/managed-model-config/dashboard-managed-variables-models-config.ts, apps/web/src/lib/variable-models/managed/custom-resource-model/asset-additional-info-key-variable-model.ts, apps/web/src/lib/variable-models/managed/resource-model/cloud-service-query-set-variable-model.ts, apps/web/src/lib/variable-models/managed/resource-model/cloud-service-type-variable-model.ts, apps/web/src/lib/variable-models/managed/resource-model/cloud-service-variable-model.ts, apps/web/src/lib/variable-models/managed/resource-model/collector-variable-model.ts, apps/web/src/lib/variable-models/managed/resource-model/cost-data-source-variable-model.ts, apps/web/src/lib/variable-models/managed/resource-model/cost-variable-model.ts, apps/web/src/lib/variable-models/managed/resource-model/project-group-variable-model.ts, apps/web/src/lib/variable-models/managed/resource-model/project-variable-model.ts, apps/web/src/lib/variable-models/managed/resource-model/provider-variable-model.ts, apps/web/src/lib/variable-models/managed/resource-model/region-variable-model.ts, apps/web/src/lib/variable-models/managed/resource-model/secret-variable-model.ts, apps/web/src/lib/variable-models/managed/resource-model/service-account-variable-model.ts, apps/web/src/lib/variable-models/managed/resource-model/user-variable-model.ts, apps/web/src/lib/variable-models/managed/resource-model/webhook-variable-model.ts, apps/web/src/lib/variable-models/managed/resource-model/workspace-variable-model.ts, apps/web/src/services/dashboards/constants/dashboard-managed-variables-schema.ts
=> feat: update

apps/web/src/common/modules/navigations/gnb/GNBToolbox.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-header/store.ts, apps/web/src/services/project/pages/ProjectDetailPage.vue
=> feat: apply id at toolbox

apps/web/src/common/modules/page-layouts/LayoutContainer.vue, packages/mirinae/src/inputs/buttons/copy-button/PCopyButton.vue, packages/mirinae/src/navigation/breadcrumbs/PBreadcrumbs.vue, packages/mirinae/src/navigation/breadcrumbs/modules/BreadcrumbsItem.vue
- apply useWindowSize for reactivation
- apply height at main component
=> feat: fixed some bugs

apps/web/src/lib/variable-models/managed/resource-model/cost-variable-model.ts, apps/web/src/store/reference/project-group-reference-store.ts
=> chore: delete unused code and edit minor

apps/web/src/common/composables/breadcrumbs/index.ts, apps/web/src/common/modules/navigations/gnb/GNBToolbox.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-header/store.ts, apps/web/src/services/cost-explorer/CostExplorerContainer.vue, apps/web/src/services/cost-explorer/CostExplorerLSB.vue, apps/web/src/services/cost-explorer/components/CostAnalysisHeader.vue, apps/web/src/services/cost-explorer/routes/routes.ts, apps/web/src/services/dashboards/DashboardsLSB.vue, apps/web/src/services/dashboards/components/DashboardCustomize.vue, apps/web/src/services/dashboards/components/DashboardDeleteModal.vue, apps/web/src/services/dashboards/components/DashboardDetailHeader.vue, apps/web/src/services/dashboards/pages/DashboardCreatePage.vue, apps/web/src/services/dashboards/pages/DashboardDetailPage.vue, apps/web/src/services/dashboards/pages/admin/AdminDashboardCreatePage.vue, apps/web/src/services/dashboards/pages/admin/AdminDashboardDetailPage.vue, apps/web/src/services/dashboards/routes/admin/routes.ts, apps/web/src/services/dashboards/routes/routes.ts, apps/web/src/services/project/pages/ProjectDetailPage.vue, apps/web/src/services/project/pages/ProjectMainPage.vue
Plz check it except the last 2 commits!
=> feat: apply starred at toolbox

apps/web/src/common/modules/custom-table/custom-field-modal/CustomFieldModal.vue, apps/web/src/services/asset-inventory/pages/CloudServiceDetailPage.vue
=> fix: fixed bug

apps/web/src/lib/variable-models/_base/enum-variable-model.ts, apps/web/src/lib/variable-models/index.ts
=> fix: variable model factory

apps/web/src/common/modules/tags/tags-panel/TagsPanel.vue, apps/web/src/services/asset-inventory/components/CloudServiceDetailTabs.vue, apps/web/src/services/asset-inventory/pages/CloudServiceDetailPage.vue, apps/web/src/store/modules/user/getters.ts
=> fix(cloud-service-custom-tag): fix permission error

apps/web/src/lib/variable-models/index.ts, apps/web/src/lib/variable-models/managed-model-config/base-managed-model-config.ts, apps/web/src/services/cost-explorer/components/CostAnalysisFiltersPopper.vue, apps/web/src/services/dashboards/stores/all-reference-type-info-store.ts
=> fix: refactor all-reference-type-info-store & apply VariableModelFactory in popper

apps/web/src/services/dashboards/widgets/_helpers/widget-options-helper.ts
=> feat: use `setFilterAndGetWidgetFiltersMap` helper in widget-options-helper

apps/web/src/store/modules/reference/type.ts, apps/web/src/store/reference/cloue-service-query-set-reference-store.ts, apps/web/src/store/reference/cost-data-source-reference-store.ts, apps/web/src/store/reference/project-group-reference-store.ts, apps/web/src/store/reference/project-reference-store.ts, apps/web/src/store/reference/user-reference-store.ts, apps/web/src/store/reference/workspace-reference-store.ts
=> feat: use model prototype for reference store info

apps/web/src/lib/site-initializer/index.ts, apps/web/src/lib/site-initializer/resource-prefetch.ts, apps/web/src/lib/variable-models/_base/types.ts
=> feat: delete prefetch from site-initializer

apps/web/src/common/modules/navigations/lsb/LSB.vue, apps/web/src/common/modules/navigations/lsb/modules/LSBCollapsibleMenuItem.vue, apps/web/src/common/modules/navigations/lsb/modules/LSBDividerMenuItem.vue, apps/web/src/common/modules/navigations/lsb/modules/LSBMenuItem.vue, apps/web/src/common/modules/navigations/lsb/modules/LSBRouterMenuItem.vue, apps/web/src/common/modules/navigations/lsb/type.ts, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-header/TopBarHeader.vue, apps/web/src/common/modules/page-layouts/LayoutContainer.vue, apps/web/src/services/dashboards/DashboardsLSB.vue, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: apply dashboard new LSB

apps/web/src/common/modules/navigations/top-bar/modules/TopBarSuggestionList.vue, apps/web/src/common/modules/navigations/top-bar/modules/gnb-search-clone/modules/gnb-search-dropdown/GNBSearchDropdown.vue, apps/web/src/common/modules/navigations/top-bar/modules/gnb-search-clone/modules/gnb-search-dropdown/modules/GNBSearchServiceTab.vue, apps/web/src/common/modules/navigations/top-bar/modules/gnb-search-clone/modules/gnb-search-dropdown/modules/SearchTabContent.vue, apps/web/src/common/modules/navigations/top-bar/modules/gnb-search-clone/modules/gnb-search-dropdown/modules/TopBarSearchServiceAccountTab.vue, apps/web/src/common/modules/navigations/top-bar/modules/gnb-search-clone/modules/gnb-search-dropdown/modules/TopBarSearchWorkspaceFilter.vue, apps/web/src/common/modules/navigations/top-bar/modules/gnb-search-clone/store.ts, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
plz, check order by commit.
https://github.com/cloudforet-io/console/assets/50662170/632c1c06-1e54-467f-ae99-d27776481f08
=> feat: create SearchTabContent

apps/web/src/lib/site-initializer/index.ts, apps/web/src/lib/site-initializer/resource-prefetch.ts, apps/web/src/lib/variable-models/_base/resource-variable-model.ts, apps/web/src/lib/variable-models/index.ts, apps/web/src/lib/variable-models/managed-model/resource-model/cost-variable-model.ts, apps/web/src/services/dashboards/components/DashboardVariableDropdown.vue, apps/web/src/services/dashboards/constants/dashboard-managed-variables-schema.ts, apps/web/src/services/dashboards/dashboard-template/helpers/dashboard-template-generator.ts
=> fix: refactor dashboard variable 

apps/web/src/lib/variable-models/_base/resource-variable-model.ts, apps/web/src/lib/variable-models/_base/types.ts, apps/web/src/lib/variable-models/index.ts, apps/web/src/lib/variable-models/managed-model/resource-model/cloud-service-query-set-variable-model.ts, apps/web/src/lib/variable-models/managed-model/resource-model/cloud-service-type-variable-model.ts, apps/web/src/lib/variable-models/managed-model/resource-model/cloud-service-variable-model.ts, apps/web/src/lib/variable-models/managed-model/resource-model/collector-variable-model.ts, apps/web/src/lib/variable-models/managed-model/resource-model/cost-data-source-variable-model.ts, apps/web/src/lib/variable-models/managed-model/resource-model/cost-variable-model.ts, apps/web/src/lib/variable-models/managed-model/resource-model/project-variable-model.ts, apps/web/src/lib/variable-models/managed-model/resource-model/provider-variable-model.ts, apps/web/src/lib/variable-models/managed-model/resource-model/region-variable-model.ts, apps/web/src/lib/variable-models/managed-model/resource-model/secret-variable-model.ts, apps/web/src/lib/variable-models/managed-model/resource-model/service-account-variable-model.ts
=> feat: change `properties` from private to public

apps/web/src/lib/variable-models/_base/resource-variable-model.ts, apps/web/src/lib/variable-models/managed-model/resource-model/cost-variable-model.ts
=> fix: fix `generateProperty()` in ResourceVariableModel

packages/mirinae/src/data-display/dynamic/dynamic-layout/templates/html/index.vue
=> fix: restore br tag feature

apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/modules/TopBarSearchInput.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/modules/top-bar-search-dropdown/TopBarSearchDropdown.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/modules/top-bar-search-dropdown/modules/SearchTabContent.vue
=> fix: fix overflow height bug

apps/web/src/common/components/titles/sidebar-title/SidebarTitle.vue, apps/web/src/common/modules/favorites/favorite-list/FavoriteList.vue, apps/web/src/common/modules/navigations/lsb/LSB.vue, apps/web/src/common/modules/navigations/lsb/modules/LSBCollapsibleMenuItem.vue, apps/web/src/common/modules/navigations/lsb/modules/LSBRouterMenuItem.vue, apps/web/src/services/asset-inventory/AssetInventoryLSB.vue, apps/web/src/services/asset-inventory/routes/admin/routes.ts, apps/web/src/services/asset-inventory/routes/routes.ts, apps/web/src/services/cost-explorer/CostExplorerLSB.vue, apps/web/src/services/dashboards/DashboardsLSB.vue, apps/web/src/services/project/ProjectLSB.vue, apps/web/src/services/project/components/ProjectMainProjectTree.vue, apps/web/src/styles/variables.cjs, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json, packages/mirinae/src/inputs/radio-group/PRadioGroup.vue
- Project
- Asset Inventory > Detail
- Cost Analysis
=> feat: apply new LSB layout

apps/web/src/lib/variable-models/index.ts, apps/web/src/schema/dashboard/_types/dashboard-type.ts, apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
=> fix: create variable schema refining helper 

apps/web/src/lib/site-initializer/resource-prefetch.ts, apps/web/src/lib/variable-models/managed-model/enum-model/asset-default-field-variable-model.ts, apps/web/src/lib/variable-models/managed-model/enum-model/cost-default-data-type-variable-model.ts, apps/web/src/lib/variable-models/managed-model/enum-model/cost-default-field-variable-model.ts, apps/web/src/lib/variable-models/managed-model/enum-model/granularity-variable-model.ts, apps/web/src/lib/variable-models/managed-model/resource-model/cloud-service-query-set-variable-model.ts, apps/web/src/lib/variable-models/managed-model/resource-model/cloud-service-type-variable-model.ts, apps/web/src/lib/variable-models/managed-model/resource-model/cloud-service-variable-model.ts, apps/web/src/lib/variable-models/managed-model/resource-model/collector-variable-model.ts, apps/web/src/lib/variable-models/managed-model/resource-model/cost-data-source-variable-model.ts, apps/web/src/lib/variable-models/managed-model/resource-model/cost-variable-model.ts, apps/web/src/lib/variable-models/managed-model/resource-model/project-group-variable-model.ts, apps/web/src/lib/variable-models/managed-model/resource-model/project-variable-model.ts, apps/web/src/lib/variable-models/managed-model/resource-model/provider-variable-model.ts, apps/web/src/lib/variable-models/managed-model/resource-model/region-variable-model.ts, apps/web/src/lib/variable-models/managed-model/resource-model/secret-variable-model.ts, apps/web/src/lib/variable-models/managed-model/resource-model/service-account-variable-model.ts, apps/web/src/lib/variable-models/managed-model/resource-model/user-variable-model.ts, apps/web/src/lib/variable-models/managed-model/resource-model/webhook-variable-model.ts, apps/web/src/lib/variable-models/managed-model/resource-model/workspace-variable-model.ts
=> fix: add meta setting to model constructor

apps/web/src/services/dashboards/components/DashboardManageVariableTable.vue
=> fix: edit variable schema usage in managed variable overlay

apps/web/src/services/dashboards/components/DashboardVariableDropdown.vue, apps/web/src/services/dashboards/widgets/_helpers/widget-options-filters-helper.ts
=> fix: fix filters helper of widget

apps/web/src/lib/variable-models/managed-model/resource-model/provider-variable-model.ts
=> fix: fix idKey of provider variable model

apps/web/src/common/modules/navigations/stores/favorite-store.ts, apps/web/src/common/modules/navigations/stores/recent-store.ts, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/modules/top-bar-search-dropdown/modules/TopBarSearchServiceTab.vue, apps/web/src/router/index.ts
=> feat: create recent API

apps/web/src/common/modules/navigations/gnb/GNBNavigationRail.vue, apps/web/src/common/modules/navigations/gnb/GNBToolbox.vue, apps/web/src/common/modules/navigations/top-bar/TopBarMyPage.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-header/MyPageTopBarHeader.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-header/TopBarHeader.vue, apps/web/src/common/modules/page-layouts/LayoutContainer.vue, apps/web/src/services/my-page/pages/UserAccountPage.vue, apps/web/src/styles/variables.cjs, packages/mirinae/src/navigation/breadcrumbs/PBreadcrumbs.vue, packages/mirinae/src/styles/variables.cjs
=> feat: fixed minor bug, apply changed design

apps/web/src/lib/variable-models/_base/enum-variable-model.ts, apps/web/src/schema/dashboard/_constants/widget-constant.ts, apps/web/src/services/dashboards/components/DashboardWidgetOptionDropdown.vue, apps/web/src/services/dashboards/stores/widget-form-store.ts, apps/web/src/services/dashboards/widgets/_constants/managed-widget-options-schema.ts, apps/web/src/services/dashboards/widgets/_helpers/__tests__/widget-schema-helper.test.ts, apps/web/src/services/dashboards/widgets/_helpers/widget-schema-helper.ts
=> feat: add fixedOptions to mergedWidgetInfo

apps/web/src/schema/dashboard/_types/dashboard-type.ts, apps/web/src/services/dashboards/components/DashboardCreateStep1.vue, apps/web/src/services/dashboards/components/DashboardCreateStep1SearchFilter.vue, apps/web/src/services/dashboards/components/DashboardCreateStep2.vue, apps/web/src/services/dashboards/components/DashboardCreateTemplateBoard.vue, packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
=> fix: additional dashboard-create markup

apps/web/src/schema/dashboard/_types/dashboard-type.ts, apps/web/src/services/dashboards/components/DashboardManageVariableForm.vue, apps/web/src/services/dashboards/dashboard-template/helpers/dashboard-template-generator.ts, apps/web/src/services/dashboards/dashboard-template/templates/aws-cdn-and-traffic.ts, apps/web/src/services/dashboards/dashboard-template/templates/aws-monthly-cost-summary.ts, apps/web/src/services/dashboards/dashboard-template/templates/azure-monthly-cost-summary.ts, apps/web/src/services/dashboards/dashboard-template/templates/google-monthly-cost-summary.ts
=> feat(dashboard-template): delete helper and set pure variables_schema

apps/web/src/lib/variable-models/managed-model/resource-model/cloud-service-query-set-variable-model.ts, apps/web/src/services/dashboards/dashboard-template/templates/aws-cdn-and-traffic.ts, apps/web/src/services/dashboards/dashboard-template/templates/aws-monthly-cost-summary.ts, apps/web/src/services/dashboards/dashboard-template/templates/azure-monthly-cost-summary.ts, apps/web/src/services/dashboards/dashboard-template/templates/d-clo-compliance-overview.ts, apps/web/src/services/dashboards/dashboard-template/templates/google-monthly-cost-summary.ts, apps/web/src/services/dashboards/dashboard-template/templates/prowler-compliance-overview.ts
=> fix: edit template and cloud service query set model

apps/web/src/services/dashboards/dashboard-template/templates/aws-cdn-and-traffic.ts, apps/web/src/services/dashboards/dashboard-template/templates/aws-monthly-cost-summary.ts, apps/web/src/services/dashboards/dashboard-template/templates/azure-monthly-cost-summary.ts, apps/web/src/services/dashboards/dashboard-template/templates/google-monthly-cost-summary.ts, apps/web/src/services/dashboards/pages/DashboardCreatePage.vue, apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
=> fix: add fixed_options to dashboard info

apps/web/src/common/composables/go-back/index.ts, apps/web/src/services/dashboards/components/DashboardCreateStep1SearchFilter.vue, apps/web/src/services/dashboards/constants/dashboard-labels.ts, apps/web/src/services/dashboards/dashboard-template/templates/aws-cdn-and-traffic.ts, apps/web/src/services/dashboards/dashboard-template/templates/aws-monthly-cost-summary.ts, apps/web/src/services/dashboards/dashboard-template/templates/azure-monthly-cost-summary.ts, apps/web/src/services/dashboards/dashboard-template/templates/d-clo-compliance-overview.ts, apps/web/src/services/dashboards/dashboard-template/templates/google-monthly-cost-summary.ts, apps/web/src/services/dashboards/dashboard-template/templates/prowler-compliance-overview.ts
=> feat: create DASHBOARD_LABELS

apps/web/src/services/dashboards/dashboard-template/template-list.ts, apps/web/src/services/dashboards/dashboard-template/templates/d-clo-compliance-overview.ts, apps/web/src/services/dashboards/dashboard-template/templates/prowler-compliance-overview.ts, apps/web/src/services/dashboards/widgets/asset-widgets/compliance-status/widget-config.ts, apps/web/src/services/dashboards/widgets/asset-widgets/count-of-pass-and-fail-findings/widget-config.ts, apps/web/src/services/dashboards/widgets/asset-widgets/total-fail-findings-history/widget-config.ts, apps/web/src/services/dashboards/widgets/asset-widgets/total-fail-findings-status/widget-config.ts
=> fix: edit widget config

apps/web/src/lib/variable-models/_helpers/dependency-helper.ts, apps/web/src/lib/variable-models/managed-model-config/base-managed-model-config.ts, apps/web/src/services/dashboards/widgets/_helpers/widget-table-helper.ts
=> fix: fix type error

apps/web/src/common/components/scoped-notification/ScopedNotification.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/modules/top-bar-search-dropdown/TopBarSearchDropdown.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/modules/top-bar-search-dropdown/modules/SearchTabContent.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/modules/top-bar-search-dropdown/modules/TopBarSearchWorkspaceFilter.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/store.ts, apps/web/src/schema/search/resource/api-verbs/search.ts, apps/web/src/schema/search/resource/config.ts, apps/web/src/schema/search/resource/model.ts, apps/web/src/schema/search/resource/type.ts, apps/web/src/store/reference/workspace-reference-store.ts
SSIA
https://github.com/cloudforet-io/console/assets/50662170/2a398b09-172c-4a37-b729-ebd3aaffdcb3
=> feat: create workspace filter 

apps/web/src/services/dashboards/dashboard-template/templates/d-clo-compliance-overview.ts
=> fix: small fix

apps/web/src/services/cost-explorer/components/CostReportMonthlyTotalAmountSummaryCard.vue, apps/web/src/services/cost-explorer/stores/cost-report-page-store.ts
=> fix(cost-report): fix style issue in card data table

apps/web/src/lib/site-initializer/last-accessed-workspace.ts, apps/web/src/router/index.ts
SSIA
If your lastAccessedWorkspace is removed, you can access workspace mode.
This PR solved that case.
=> fix: solve router issue (workspace delete case)

apps/web/src/common/composables/date-range-formatter/__tests__/index.test.ts, apps/web/src/common/composables/date-range-formatter/index.ts
=> fix(date-range-formatter): fix formatting bug and test

apps/web/src/services/dashboards/components/DashboardCreateStep2.vue
SSIA
[QA-1468](https://pyengine.atlassian.net/browse/QA-1468)
=> fix: edit wrong event name

apps/web/src/services/asset-inventory/components/ServiceAccountBaseInformationForm.vue
=> fix: solve service account issue

apps/web/src/common/modules/favorites/favorite-list/FavoriteList.vue, apps/web/src/common/modules/navigations/gnb/GNBNavigationRail.vue, apps/web/src/common/modules/navigations/gnb/GNBToolbox.vue, apps/web/src/common/modules/navigations/stores/gnb-store.ts, apps/web/src/common/modules/navigations/top-bar/TopBar.vue, apps/web/src/common/modules/navigations/top-bar/TopBarMyPage.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-header/TopBarHeader.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-header/WorkspaceLogoIcon.vue, apps/web/src/common/modules/page-layouts/LayoutContainer.vue, apps/web/src/common/modules/page-layouts/OverlayPageLayout.vue, apps/web/src/common/modules/page-layouts/VerticalPageLayout.vue, apps/web/src/services/asset-inventory/AssetInventoryLSB.vue, apps/web/src/services/asset-inventory/components/AssetInventoryLSBToggleMenuItem.vue, apps/web/src/services/cost-explorer/CostExplorerLSB.vue, apps/web/src/services/cost-explorer/components/CostAnalysisHeader.vue, apps/web/src/services/dashboards/DashboardsLSB.vue, apps/web/src/services/dashboards/pages/DashboardDetailPage.vue, apps/web/src/services/project/ProjectContainer.vue, apps/web/src/services/project/ProjectLSB.vue, apps/web/src/services/project/pages/ProjectDetailPage.vue, apps/web/src/services/project/pages/ProjectMainPage.vue, apps/web/src/services/project/routes/routes.ts, packages/mirinae/src/layouts/vertical-layout/PVerticalLayout.vue, packages/mirinae/src/navigation/breadcrumbs/PBreadcrumbs.vue
=> feat: apply QA review

apps/web/src/services/dashboards/components/DashboardCustomizePageName.vue, apps/web/src/services/dashboards/dashboard-template/templates/azure-monthly-cost-summary.ts, apps/web/src/services/dashboards/dashboard-template/templates/google-monthly-cost-summary.ts, apps/web/src/services/dashboards/widgets/_helpers/widget-options-filters-helper.ts, packages/mirinae/src/data-display/board-item/PBoardItem.vue
=> feat: add budgetUsageByTarget widget to monthly cost dashboard & set default name input when create dashboard

apps/web/src/schema/dashboard/_types/dashboard-type.ts, apps/web/src/services/dashboards/dashboard-template/templates/aws-cdn-and-traffic.ts, apps/web/src/services/dashboards/dashboard-template/templates/aws-monthly-cost-summary.ts, apps/web/src/services/dashboards/dashboard-template/templates/azure-monthly-cost-summary.ts, apps/web/src/services/dashboards/dashboard-template/templates/d-clo-compliance-overview.ts, apps/web/src/services/dashboards/dashboard-template/templates/google-monthly-cost-summary.ts, apps/web/src/services/dashboards/dashboard-template/templates/prowler-compliance-overview.ts
=> fix: add dashboard template field(id, type) to dashboard model & apply to template

apps/web/src/services/dashboards/components/DashboardCreateStep1.vue, apps/web/src/services/dashboards/components/DashboardCreateTemplateBoard.vue
[[Minor] Dashboard 생성시 서치 부분에 소문자도 결과값 노출되도록 요청](https://pyengine.atlassian.net/browse/QA-1486)
[[Minor] Create Dashboard step 1 > 카드 목록, 모바일에서 카드 클릭시 바로 다음단계로 넘어갈 수 있도록 수정](https://pyengine.atlassian.net/browse/QA-1491)
=> fix: fix dashboard create search

apps/web/src/common/modules/navigations/top-bar/modules/top-bar-header/WorkspaceLogoIcon.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/modules/top-bar-search-dropdown/TopBarSearchDropdown.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/modules/top-bar-search-dropdown/modules/SearchTabContent.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/modules/top-bar-search-dropdown/modules/TopBarSearchWorkspaceFilter.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/store.ts
SSIA
https://github.com/cloudforet-io/console/assets/50662170/b626c195-68a9-40bd-bfa6-799538bd1318
=> feat: create search-items of Service Account tab

apps/web/src/services/dashboards/components/DashboardMainBoardList.vue
=> fix: apply new dashboard main page design

apps/web/src/schema/dashboard/private-dashboard/api-verbs/create.ts, apps/web/src/schema/dashboard/public-dashboard/api-verbs/create.ts, apps/web/src/services/dashboards/components/DashboardCloneModal.vue, apps/web/src/services/dashboards/pages/DashboardCreatePage.vue, apps/web/src/services/dashboards/pages/admin/AdminDashboardCreatePage.vue
=> feat: set `template_id`, `template_type` when create dashboard

apps/web/src/services/cost-explorer/components/CostAnalysisFiltersPopper.vue, apps/web/src/services/dashboards/widgets/_base-widgets/base-pie/BasePieWidget.vue, apps/web/src/services/dashboards/widgets/_base-widgets/base-trend/BaseTrendWidget.vue, apps/web/src/services/dashboards/widgets/_components/WidgetDataTable.vue, apps/web/src/services/dashboards/widgets/_composables/use-widget/use-widget-location.ts, apps/web/src/services/dashboards/widgets/_helpers/widget-location-helper.ts, apps/web/src/services/dashboards/widgets/asset-widgets/trend-of-pass-and-fail-findings/TrendOfPassAndFailFindingsWidget.vue, apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-by-target/BudgetUsageByTargetWidget.vue, apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region-multi-fields/CostByRegionMultiFieldsWidget.vue, apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region/CostByRegionWidget.vue, apps/web/src/services/dashboards/widgets/cost-widgets/cost-summary-multi-fields/CostSummaryMultiFieldsWidget.vue
=> feat: set link to row of widget data table

apps/web/src/schema/dashboard/_types/dashboard-type.ts, apps/web/src/schema/dashboard/public-dashboard/api-verbs/create.ts, apps/web/src/services/dashboards/pages/DashboardCreatePage.vue, apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
=> fix: apply template info to dashboard create

apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/helper.ts, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/modules/top-bar-search-dropdown/TopBarSearchDropdown.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/modules/top-bar-search-dropdown/modules/SearchTabContent.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/modules/top-bar-search-dropdown/modules/TopBarSearchWorkspaceFilter.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/store.ts, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/type.ts
SSIA
We can now route from search items.
=> feat: apply routing function(reference router)

apps/web/src/App.vue, apps/web/src/common/modules/navigations/gnb/GNBNavigationRail.vue, apps/web/src/common/modules/navigations/gnb/GNBToolbox.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-header/TopBarHeader.vue, apps/web/src/common/modules/page-layouts/LayoutContainer.vue, apps/web/src/services/cost-explorer/components/CostAnalysisHeader.vue, apps/web/src/services/cost-explorer/components/CostReportReportsTab.vue, apps/web/src/services/dashboards/components/DashboardCustomizePageName.vue, apps/web/src/services/my-page/pages/UserAccountPage.vue, apps/web/src/services/project/pages/ProjectMainPage.vue, packages/mirinae/src/data-display/heading/PHeading.vue
=> feat: apply qa

apps/web/src/services/dashboards/components/DashboardWidgetAddModalDefaultTab.vue, apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
=> feat: show only widgets belonging to the template

apps/web/src/services/dashboards/components/DashboardToolsetDateCustomModal.vue, apps/web/src/services/dashboards/components/DashboardToolsetDateDropdown.vue, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> chore: change words in dashboard custom date dropdown

apps/web/src/services/dashboards/components/DashboardCustomizePageName.vue, apps/web/src/services/dashboards/components/DashboardDetailHeader.vue, apps/web/src/services/dashboards/pages/DashboardDetailPage.vue
=> fix: apply template name & display info in dashboard header 

apps/web/src/services/dashboards/components/DashboardMainBoardList.vue, apps/web/src/services/dashboards/components/DashboardManageVariableOverlay.vue, apps/web/src/services/dashboards/components/DashboardManageVariableTable.vue, apps/web/src/services/dashboards/components/DashboardVariableDropdown.vue
=> chore(dashboard-variable): fix minor style bug of dropdown

apps/web/index.html, apps/web/src/lib/site-initializer/domain-settings.ts
=> feat: set og meta tag

apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/modules/top-bar-search-dropdown/modules/SearchTabContent.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/modules/top-bar-search-dropdown/modules/TopBarSearchListItem.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/modules/top-bar-search-dropdown/modules/TopBarSearchRecentListItem.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/modules/top-bar-search-dropdown/modules/TopBarSearchWorkspaceFilter.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/store.ts, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json
=> fix: fix qa items

apps/web/src/services/cost-explorer/components/CostAnalysisPeriodSelectDropdown.vue, apps/web/src/services/dashboards/components/DashboardToolsetDateDropdown.vue, packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.stories.mdx, packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue, packages/mirinae/src/inputs/dropdown/select-dropdown/story-helper.ts
=> feat(p-select-dropdown): add `disableProxy` props

apps/web/src/common/modules/navigations/top-bar/modules/TopBarSuggestionList.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/modules/TopBarSearchInput.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/modules/top-bar-search-dropdown/TopBarSearchDropdown.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/modules/top-bar-search-dropdown/modules/SearchTabContent.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/modules/top-bar-search-dropdown/modules/TopBarSearchServiceTab.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/store.ts
=> fix: fix qa bugs

apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-favorite/modules/TopBarFavoriteContextMenu.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-integration/modules/TopBarIntegrationContextMenu.vue, apps/web/src/lib/helper/config-data-helper.ts, apps/web/src/services/project/composables/use-project-favorite.ts
=> refactor: changed convert func

apps/web/src/services/dashboards/components/DashboardToolsetDateDropdown.vue, packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.stories.mdx, packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue, packages/mirinae/src/inputs/dropdown/select-dropdown/story-helper.ts
=> chore(p-select-dropdown): delete unnecessary props

apps/web/src/schema/dashboard/_types/dashboard-type.ts, apps/web/src/services/dashboards/constants/dashboard-labels.ts, apps/web/src/services/dashboards/dashboard-template/helpers/dashboard-template-generator.ts, apps/web/src/services/dashboards/dashboard-template/templates/aws-cdn-and-traffic.ts, apps/web/src/services/dashboards/dashboard-template/templates/aws-monthly-cost-summary.ts, apps/web/src/services/dashboards/dashboard-template/templates/azure-monthly-cost-summary.ts, apps/web/src/services/dashboards/dashboard-template/templates/d-clo-compliance-overview.ts, apps/web/src/services/dashboards/dashboard-template/templates/google-monthly-cost-summary.ts, apps/web/src/services/dashboards/dashboard-template/templates/prowler-compliance-overview.ts
=> fix: apply template_widget_id to managed template

apps/web/src/services/dashboards/components/DashboardWidgetContainer.vue, apps/web/src/services/dashboards/components/DashboardWidgetEditModal.vue, apps/web/src/services/dashboards/components/DashboardWidgetForm.vue, apps/web/src/services/dashboards/dashboard-template/template-list.ts, apps/web/src/services/dashboards/stores/widget-form-store.ts
=> fix(widget-edit-form): apply widget options reset planning to edit modal

apps/web/src/common/modules/popup/notice/NoticePopup.vue
=> fix: fix huge notice popup bug

apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/modules/top-bar-search-dropdown/TopBarSearchDropdown.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/modules/top-bar-search-dropdown/modules/SearchTabContent.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/modules/top-bar-search-dropdown/modules/TopBarSearchListItem.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/modules/top-bar-search-dropdown/modules/TopBarSearchServiceTab.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/modules/top-bar-search-dropdown/modules/TopBarSearchWorkspaceFilter.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/store.ts
I fixed overall loading process.
=> fix: fix loading process

apps/web/src/common/modules/popup/notice/NoticePopup.vue, apps/web/src/services/administration/components/UserManagementFormNotificationEmailForm.vue
=> fix(user-notification-email): fix notification email update bug

apps/web/src/lib/variable-models/managed-model/enum-model/cost-default-field-variable-model.ts, apps/web/src/services/dashboards/components/DashboardWidgetEditModal.vue, apps/web/src/services/dashboards/components/DashboardWidgetOptionDropdown.vue
=> fix: fix 'additional_info.Usage Type Details' bug

apps/web/src/common/modules/navigations/top-bar/modules/top-bar-header/TopBarHeader.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-favorite/modules/TopBarFavoriteContextMenu.vue, apps/web/src/common/modules/page-layouts/GeneralPageLayout.vue, apps/web/src/services/my-page/MyPageContainer.vue, packages/language-pack/ko.json, packages/mirinae/src/inputs/dropdown/select-dropdown/components/dropdown-button.vue, packages/mirinae/src/inputs/dropdown/select-dropdown/story-helper.ts
=> feat: apply minor qa

apps/web/src/services/dashboards/components/WidgetFullModeModal.vue, apps/web/src/services/dashboards/components/WidgetFullModeModalSidebar.vue
=> fix: apply template widget id to full modal

apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/modules/top-bar-search-dropdown/modules/TopBarSearchRecentListItem.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/store.ts, apps/web/src/services/cost-explorer/components/BudgetMainListCard.vue, apps/web/src/store/modules/reference/service-account/actions.ts, apps/web/src/store/modules/reference/service-account/type.ts, apps/web/src/store/modules/reference/type.ts, packages/mirinae/src/layouts/vertical-layout/PVerticalLayout.vue
=> fix: fix search UI bug

apps/web/src/services/dashboards/components/DashboardWidgetAddModalDefaultTab.vue, apps/web/src/services/dashboards/stores/widget-form-store.ts
SSIA
If you add new widgets in widget-add-form, they will be template widgets.
=> fix(widget-add-form): handle widget-add case by template

apps/web/src/services/project/components/ProjectSummaryPersonalHealthDashboardWidget.vue
=> fix: fix import error

apps/web/src/common/modules/navigations/gnb/GNBToolbox.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-favorite/modules/TopBarFavoriteContextMenu.vue
=> fix: fixed route bug

apps/web/src/services/dashboards/components/DashboardWidgetForm.vue, apps/web/src/services/dashboards/components/DashboardWidgetOptionsForm.vue, apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts, apps/web/src/services/dashboards/stores/widget-form-store.ts, apps/web/src/services/dashboards/widgets/asset-widgets/count-of-fail-findings/widget-config.ts, apps/web/src/services/dashboards/widgets/asset-widgets/severity-status-by-service/widget-config.ts, apps/web/src/services/dashboards/widgets/asset-widgets/trend-of-pass-and-fail-findings/widget-config.ts
=> fix(widget-form): solve widget form bugs

apps/web/src/common/modules/favorites/favorite-button/FavoriteButton.vue, apps/web/src/common/modules/navigations/gnb/GNBToolbox.vue, apps/web/src/common/modules/navigations/stores/gnb-store.ts, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-favorite/TopBarFavorite.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-favorite/modules/TopBarFavoriteContextMenu.vue, apps/web/src/lib/helper/config-data-helper.ts, apps/web/src/services/cost-explorer/CostExplorerLSB.vue
=> refactor: changed fetchCostQuerySet position

apps/web/src/common/modules/navigations/stores/recent-store.ts, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/store.ts
=> fix: fix recent undefined case

apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-favorite/modules/TopBarFavoriteContextMenu.vue, apps/web/src/services/dashboards/DashboardsContainer.vue, apps/web/src/services/dashboards/DashboardsLSB.vue
=> fix: apply grant guard to dashboard load

apps/web/src/common/composables/grant-scope-guard/index.ts, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/TopBarSearch.vue, apps/web/src/services/asset-inventory/AssetInventoryLSB.vue
=> fix: apply grant guard to cloud service type

apps/web/src/services/cost-explorer/components/CostAnalysisDataTable.vue, apps/web/src/services/cost-explorer/constants/cost-explorer-constant.ts, apps/web/src/services/cost-explorer/stores/cost-analysis-page-store.ts
=> feat(cost-analysis): add project group, project to admin page

apps/web/src/services/project/components/ProjectGroupMemberManagementModal.vue, apps/web/src/services/project/pages/ProjectMainPage.vue, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: add project group member modal

apps/web/src/services/alert-manager/AlertManagerContainer.vue, apps/web/src/services/asset-inventory/AssetInventoryContainer.vue, apps/web/src/services/dashboards/DashboardsLSB.vue, apps/web/src/services/dashboards/constants/dashboard-constant.ts, apps/web/src/services/dashboards/pages/DashboardDetailPage.vue, apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts, apps/web/src/services/dashboards/types/dashboard-view-type.ts, apps/web/src/services/iam/IamContainer.vue, apps/web/src/services/info/InfoContainer.vue, apps/web/src/services/preference/PreferenceContainer.vue
SSIA
- Apply custom breadcrumbs route to dashboard detail page.
https://github.com/cloudforet-io/console/assets/83635051/85b7f5f5-81d1-428e-b3c5-b6102f745fdd
- Remove unnecessary usage of `useBreadcrumbs` hook
=> fix(breadcrumbs): apply custom breadcrumbs in dashborad detail & small fix

apps/web/src/services/iam/components/RoleUpdateFormAccessMenuItem.vue
SSIA 
[Feedback](https://www.notion.so/spaceone-io/Role-Home-87bfb75ef50a4ef1a47c023b7bdfe92b?pvs=4)
=> fix(role-update-form): apply 'disable' in home-dashboard access toggle

apps/web/src/services/asset-inventory/components/ServiceAccountBaseInformation.vue
SSIA
Don't make schema_id by using provider name, such as `'${state.provider}'-service-account`.
=> fix: solve get-schema with wrong schema_id

apps/web/src/common/modules/favorites/favorite-button/FavoriteButton.vue, apps/web/src/common/modules/navigations/gnb/GNBNavigationRail.vue, apps/web/src/common/modules/navigations/top-bar/modules/TopBarSuggestionList.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-favorite/modules/TopBarFavoriteContextMenu.vue, apps/web/src/lib/helper/config-data-helper.ts, apps/web/src/services/cost-explorer/components/CostAnalysisHeader.vue, apps/web/src/services/iam/components/UserManagementAddUser.vue, apps/web/src/services/iam/components/UserManagementFormNotificationEmailForm.vue, apps/web/src/services/iam/store/user-page-store.ts, apps/web/src/services/project/components/ProjectMainProjectGroupDeleteCheckModal.vue, apps/web/src/services/project/pages/ProjectDetailPage.vue, apps/web/src/store/dashboard/dashboard-store.ts, packages/mirinae/src/feedbacks/loading/lazy-img/PLazyImg.vue
=> feat: apply feedback

apps/web/src/lib/site-initializer/domain-settings.ts
=> feat: delete og code

apps/web/src/lib/site-initializer/user-auth.ts, apps/web/src/services/auth/pages/PasswordPage.vue, apps/web/src/store/modules/user/mutations.ts
=> feat: apply domain setting language

apps/web/src/services/cost-explorer/CostExplorerContainer.vue
=> fix: apply grant scope guard to cost expolorer container

apps/web/src/router/helpers/route-helper.ts, apps/web/src/router/index.ts
SSIA
https://lucid.app/lucidchart/da24edff-920c-4444-a04d-13464d5b09c9/edit?page=0_0#
=> refactor: refactor SpaceRouter Before each

apps/web/src/services/asset-inventory/AssetInventoryContainer.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue
=> fix(service-account): apply grant guard to service account page

apps/web/src/lib/menu/menu-architecture.ts, apps/web/src/services/asset-inventory/constants/service-account-constant.ts, apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue, apps/web/src/services/asset-inventory/routes/admin/routes.ts
=> fix(service-account): apply service account admin mode

apps/web/src/services/iam/components/UserManagementFormModal.vue, apps/web/src/services/iam/components/UserManagementFormNotificationEmailForm.vue
=> fix: fixed email verification

apps/web/src/lib/menu/menu-info.ts, apps/web/src/services/asset-inventory/AssetInventoryContainer.vue, apps/web/src/services/asset-inventory/components/CloudServiceDetailTabs.vue, apps/web/src/services/asset-inventory/components/CloudServiceLSB.vue, apps/web/src/services/asset-inventory/components/CloudServiceLSBToggleMenuItem.vue, apps/web/src/services/asset-inventory/components/SecurityLSB.vue, apps/web/src/services/asset-inventory/pages/CloudServiceDetailPage.vue, apps/web/src/services/asset-inventory/pages/SecurityPage.vue, apps/web/src/services/asset-inventory/routes/routes.ts, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: create security page

apps/web/src/services/asset-inventory/AssetInventoryContainer.vue, apps/web/src/services/asset-inventory/AssetInventoryLSB.vue
=> fix(asset-inventory): refactor lsb

apps/web/src/services/asset-inventory/pages/ServiceAccountAddPage.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue
=> fix(service-account-add): apply account name to add page

apps/web/src/schema/cost-analysis/cost-report-data/api-verbs/analyze.ts, apps/web/src/services/cost-explorer/components/CostReportMonthlyTotalAmountSummaryCard.vue, apps/web/src/services/cost-explorer/components/CostReportOverviewCostTrendCard.vue, apps/web/src/services/cost-explorer/stores/cost-report-page-store.ts
=> feat: set `cost_report_config_id` param to 'cost-report-data/analyze' API

apps/web/src/services/asset-inventory/components/MetricExplorerGranularityDropdown.vue, apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts, apps/web/src/services/asset-inventory/types/metric-explorer-type.ts
=> feat: create metric-explorer-page-store & implement store to granularity dropdown

apps/web/src/services/project/components/ProjectMainCardList.vue
Fix [resource sync bug](https://cloudone-mz.slack.com/archives/C02U6M1L0LX/p1710473178522069) in project main page
=> fix: fix sync error in project landing page

apps/web/src/common/modules/navigations/lsb/modules/LSBMenuItem.vue, apps/web/src/services/asset-inventory/AssetInventoryLSB.vue, apps/web/src/services/asset-inventory/components/CloudServiceLSB.vue, apps/web/src/services/asset-inventory/components/SecurityLSB.vue, apps/web/src/services/asset-inventory/routes/routes.ts, apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts, apps/web/src/services/asset-inventory/types/metric-explorer-type.ts, apps/web/src/services/cost-explorer/CostExplorerLSB.vue, apps/web/src/services/dashboards/DashboardsLSB.vue
=> fix(metric-lsb): edit lsb component & update metric page store for metric lsb 

apps/web/src/services/asset-inventory/components/SecurityLSB.vue, apps/web/src/services/asset-inventory/pages/CloudServiceDetailPage.vue, apps/web/src/services/asset-inventory/pages/SecurityPage.vue, apps/web/src/services/asset-inventory/stores/security-page-store.ts
=> refactor: refactor api position

apps/web/src/common/modules/navigations/lsb/modules/LSBCollapsibleMenuItem.vue, apps/web/src/common/modules/navigations/lsb/type.ts, apps/web/src/services/asset-inventory/components/CollectorDetailNameEditModal.vue, apps/web/src/services/asset-inventory/components/CollectorHistoryNoCollectorModal.vue, apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue, packages/mirinae/src/data-display/field-title/PFieldTitle.vue
=> feat(metric-explorer): create metric explorer lsb & edit collapsible lsb menu

apps/web/src/common/components/custom-date-modal/CustomDateModal.vue, apps/web/src/services/asset-inventory/components/MetricExplorerPeriodDropdown.vue, apps/web/src/services/asset-inventory/helpers/metric-explorer-period-helper.ts, apps/web/src/services/cost-explorer/components/CostAnalysisGranularityPeriodDropdown.vue
=> fix: set correct dateformat for day type 

apps/web/src/services/cost-explorer/pages/CostReportPage.vue, apps/web/src/services/cost-explorer/stores/cost-report-page-store.ts
=> feat: set `cost_report_config_id` to cost-report/list API

apps/web/src/services/home-dashboard/components/ResourceMap.vue
=> fix: fix bug with latitude, longitude in ResourceMap widget

apps/web/src/common/modules/navigations/lsb/modules/LSBCollapsibleMenuItem.vue, apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue, apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts, apps/web/src/services/asset-inventory/types/metric-explorer-type.ts
=> fix(metric-namespace): apply namespace data by using cloud service type & add img spec to collapsible menu

apps/web/src/common/modules/navigations/gnb/GNBToolbox.vue, apps/web/src/lib/menu/menu-architecture.ts, apps/web/src/services/asset-inventory/components/CloudServiceDetail.vue, apps/web/src/services/asset-inventory/components/CloudServiceDetailMultipleSelectedData.vue, apps/web/src/services/asset-inventory/components/CloudServiceDetailTabs.vue, apps/web/src/services/asset-inventory/components/SecurityLSB.vue, apps/web/src/services/asset-inventory/pages/CloudServiceDetailPage.vue, apps/web/src/services/asset-inventory/pages/SecurityPage.vue, apps/web/src/services/asset-inventory/routes/admin/routes.ts, apps/web/src/services/asset-inventory/stores/security-page-store.ts
=> feat: refactor and apply qa issue

apps/web/src/common/modules/navigations/lsb/type.ts, apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue
SSIA
https://github.com/cloudforet-io/console/assets/83635051/5eb710b8-4c4f-4f2f-9ea6-6e4ccef879e4
=> feat(metric-lsb): create metric selection mode in lsb

apps/web/src/services/asset-inventory/components/MetricExplorerGroupBy.vue, apps/web/src/services/asset-inventory/pages/MetricExplorerMainPage.vue, apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: create metric group by component

apps/web/src/services/asset-inventory/components/MetricExplorerChart.vue, apps/web/src/services/asset-inventory/components/MetricExplorerChartLegends.vue, apps/web/src/services/asset-inventory/constants/metric-explorer-constant.ts, apps/web/src/services/asset-inventory/pages/MetricExplorerMainPage.vue, apps/web/src/services/asset-inventory/types/metric-explorer-type.ts, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: add chart, legend section to metric page

apps/web/src/services/asset-inventory/components/AddCustomMetricModal.vue, apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue
=> feat(custom-metric-modal): create custom metric modal markup

apps/web/src/common/modules/navigations/stores/recent-store.ts, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/helper.ts, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/modules/top-bar-search-dropdown/TopBarSearchDropdown.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/modules/top-bar-search-dropdown/modules/SearchTabContent.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/modules/top-bar-search-dropdown/modules/TopBarSearchRecentListItem.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/modules/top-bar-search-dropdown/modules/TopBarSearchServiceTab.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/store.ts, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/type.ts, apps/web/src/common/modules/navigations/type.ts, apps/web/src/lib/helper/router-recent-helper.ts
=> fix: change the search resource from cloudServiceType to cloudService

apps/web/src/services/asset-inventory/AssetInventoryContainer.vue, apps/web/src/services/asset-inventory/components/SecurityLSB.vue, apps/web/src/services/asset-inventory/pages/CloudServiceDetailPage.vue, apps/web/src/services/asset-inventory/pages/SecurityPage.vue, apps/web/src/services/asset-inventory/stores/security-page-store.ts
=> feat: addition if data is absent

apps/web/src/services/asset-inventory/components/MetricExplorerPeriodDropdown.vue, apps/web/src/services/asset-inventory/constants/metric-explorer-constant.ts, apps/web/src/services/asset-inventory/helpers/metric-explorer-period-helper.ts, apps/web/src/services/asset-inventory/types/metric-explorer-type.ts, apps/web/src/services/cost-explorer/components/CostAnalysisChartLegends.vue
Not that important...Just refactoring
=> refactor: refactor period helper 

apps/web/src/services/asset-inventory/components/MetricExplorerDataTable.vue, apps/web/src/services/asset-inventory/helpers/metric-explorer-data-table-helper.ts, apps/web/src/services/asset-inventory/pages/MetricExplorerMainPage.vue
=> feat: add metric data table and helper

apps/web/src/lib/menu/menu-info.ts, apps/web/src/services/asset-inventory/pages/CloudServiceDetailPage.vue, apps/web/src/services/asset-inventory/stores/security-page-store.ts
=> chore: apply minor changed

apps/web/src/services/asset-inventory/components/ServiceAccountBaseInformationDetail.vue, apps/web/src/services/asset-inventory/helpers/dynamic-ui-schema-generator/dynamic-layout-schema-template.ts, apps/web/src/services/asset-inventory/helpers/dynamic-ui-schema-generator/index.ts, apps/web/src/services/asset-inventory/helpers/dynamic-ui-schema-generator/type.ts, apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue, apps/web/src/services/asset-inventory/stores/service-account-schema-store.ts
=> feat: add auto_sync field to trustedAccountSchema

apps/web/src/services/asset-inventory/pages/MetricExplorerDetailPage.vue, apps/web/src/services/asset-inventory/pages/MetricExplorerMainPage.vue, apps/web/src/services/asset-inventory/routes/route-constant.ts, apps/web/src/services/asset-inventory/routes/routes.ts
=> feat: add MetricExplorerDetailPage

apps/web/src/services/asset-inventory/pages/MetricExplorerMainPage.vue
=> feat: add MetricExplorerMainPage markup

apps/web/src/services/auth/authenticator/loader.ts, apps/web/src/services/auth/pages/MultiFactorAuthPage.vue
=> fix: fixed mfa bug

apps/web/src/common/modules/navigations/lsb/modules/LSBCollapsibleMenuItem.vue, apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue, apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts
=> fix(metric-lsb): add keyword search & apply data-loader

apps/web/src/schema/identity/role/constant.ts, apps/web/src/schema/identity/role/model.ts, apps/web/src/schema/identity/role/type.ts, apps/web/src/services/iam/components/AppManagementFormModal.vue, apps/web/src/services/iam/components/UserManagementAddAdminRole.vue, apps/web/src/services/iam/components/UserManagementAddRole.vue, apps/web/src/services/iam/components/UserManagementFormAdminRole.vue, apps/web/src/services/iam/components/UserManagementTabWorkspace.vue, apps/web/src/services/iam/components/UserManagementTable.vue, apps/web/src/services/iam/store/app-page-store.ts, apps/web/src/services/iam/store/role-page-store.ts, apps/web/src/services/iam/store/user-page-store.ts, apps/web/src/services/preference/store/workspace-page-store.ts, apps/web/src/store/reference/user-reference-store.ts
=> feat: add state to role model & set 'state' filter to role/list query

apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> fix(metric-lsb): edit usage of collapsible menu

apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue
=> fix: edit service account table title

apps/web/src/schema/identity/provider/api-verbs/get.ts, apps/web/src/services/asset-inventory/components/ServiceAccountBaseInformation.vue, apps/web/src/services/asset-inventory/components/ServiceAccountBaseInformationDetail.vue, apps/web/src/services/asset-inventory/components/ServiceAccountBaseInformationForm.vue, apps/web/src/services/asset-inventory/components/ServiceAccountCredentials.vue, apps/web/src/services/asset-inventory/components/ServiceAccountEditModal.vue, apps/web/src/services/asset-inventory/helpers/dynamic-ui-schema-generator/dynamic-layout-schema-template.ts, apps/web/src/services/asset-inventory/pages/ServiceAccountDetailPage.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue
=> fix: fix changed UIs of ServiceAccountPages

apps/web/src/lib/site-initializer/domain.ts, apps/web/src/router/helpers/route-helper.ts
=> fix: handle no domain case in route navigation

apps/web/src/services/asset-inventory/pages/CloudServicePage.vue, apps/web/src/services/asset-inventory/pages/SecurityPage.vue, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: apply empty components at CloudService, Security page

apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
=> chore: fix total count of dashboard header

apps/web/src/services/asset-inventory/components/SecurityLSB.vue
=> fix: apply action for excel file name

apps/web/src/services/project/components/ProjectGroupMemberManagementModal.vue
=> chore: commit for vercel deploy

apps/web/src/schema/inventory/metric-data/api-verbs/analyze.ts, apps/web/src/schema/inventory/metric-data/api-verbs/list.ts, apps/web/src/schema/inventory/metric-data/model.ts, apps/web/src/schema/inventory/metric/api-verbs/create.ts, apps/web/src/schema/inventory/metric/api-verbs/delete.ts, apps/web/src/schema/inventory/metric/api-verbs/get.ts, apps/web/src/schema/inventory/metric/api-verbs/list.ts, apps/web/src/schema/inventory/metric/api-verbs/update.ts, apps/web/src/schema/inventory/metric/constant.ts, apps/web/src/schema/inventory/metric/model.ts, apps/web/src/schema/inventory/metric/type.ts, apps/web/src/schema/inventory/namespace/api-verbs/get.ts, apps/web/src/schema/inventory/namespace/api-verbs/list.ts, apps/web/src/schema/inventory/namespace/constant.ts, apps/web/src/schema/inventory/namespace/model.ts, apps/web/src/schema/inventory/namespace/type.ts
=> feat: add schema for namespace, metric, metric-data

apps/web/src/services/asset-inventory/pages/MetricExplorerDetailPage.vue, apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: add fetchMetric() and etc to metric page store

apps/web/src/services/asset-inventory/components/ServiceAccountAddClusterModal.vue, apps/web/src/services/asset-inventory/components/ServiceAccountAddClusterScriptField.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountAddPage.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
SSIA
https://github.com/cloudforet-io/console/assets/83635051/016fa873-5fa3-485b-b240-625efa2c02a0
=> feat: create add-cluster step 2

apps/web/src/services/asset-inventory/components/SecurityLSB.vue
=> chore: change css style

apps/web/src/services/asset-inventory/components/MetricExplorerFiltersPopper.vue, apps/web/src/services/asset-inventory/components/MetricExplorerQuerySection.vue, apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts
=> feat: add filters popper to metric page

apps/web/src/common/modules/favorites/favorite-list/FavoriteList.vue, apps/web/src/common/modules/navigations/gnb/GNBNavigationRail.vue, apps/web/src/services/project/ProjectContainer.vue, apps/web/src/services/project/ProjectLSB.vue, apps/web/src/services/project/components/ProjectFavoriteList.vue, apps/web/src/services/project/composables/use-project-favorite.ts, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
- Project's LSB
- minor change (css, translation)
=> feat: apply feedbacks

apps/web/src/services/asset-inventory/stores/cloud-service-page-store.ts
=> feat: add filter

apps/web/src/services/asset-inventory/components/ServiceAccountAddClusterModal.vue, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> fix: apply step title & step button 

apps/web/src/router/helpers/route-helper.ts, apps/web/src/router/index.ts
SSIA
Solve Issue (can not access forget password page)
=> fix: edit handling exclude auth route

apps/web/src/common/modules/custom-table/custom-field-modal/CustomFieldModal.vue, apps/web/src/services/asset-inventory/components/ServiceAccountEditModal.vue, apps/web/src/services/asset-inventory/helpers/dynamic-ui-schema-generator/dynamic-layout-schema-template.ts, apps/web/src/services/asset-inventory/helpers/dynamic-ui-schema-generator/index.ts, apps/web/src/services/asset-inventory/helpers/dynamic-ui-schema-generator/type.ts, apps/web/src/services/asset-inventory/pages/ServiceAccountDetailPage.vue, apps/web/src/services/asset-inventory/stores/service-account-schema-store.ts, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: update serviceAccount table schema & fix minor bugs

apps/web/src/schema/inventory/metric-data/model.ts, apps/web/src/schema/inventory/metric/model.ts, apps/web/src/services/asset-inventory/components/MetricExplorerGroupBy.vue, apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts
=> feat: delete tags groupby code and use store data

apps/web/src/services/auth/pages/PasswordPage.vue
=> fix: solve reset-password issue

apps/web/src/services/project/components/ProjectGroupMemberManagementModal.vue, apps/web/src/services/project/components/ProjectMemberTab.vue, apps/web/src/services/project/pages/ProjectDetailPage.vue, apps/web/src/services/project/pages/ProjectMainPage.vue, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: show project group button to invited member

apps/web/src/services/asset-inventory/components/SecurityLSB.vue, apps/web/src/services/asset-inventory/pages/CloudServiceDetailPage.vue, apps/web/src/services/asset-inventory/pages/CloudServicePage.vue, apps/web/src/services/asset-inventory/pages/SecurityPage.vue, apps/web/src/services/asset-inventory/stores/security-page-store.ts, apps/web/src/services/asset-inventory/types/type.ts, apps/web/src/services/iam/components/UserManagementFormModal.vue, apps/web/src/services/iam/components/UserManagementFormNotificationEmailForm.vue
=> feat: apply qa issue for Security

apps/web/src/services/cost-explorer/components/BudgetCreateFormAmountPlanMonthInput.vue, apps/web/src/services/cost-explorer/components/BudgetCreateFormAmountPlanMonthly.vue
=> chore: show proper currency in budget create form

apps/web/src/services/asset-inventory/pages/CloudServicePage.vue, apps/web/src/services/asset-inventory/pages/SecurityPage.vue
=> chore: changed translation

apps/web/src/services/asset-inventory/components/SecurityLSB.vue
=> chore: add immediate at watch

apps/web/src/services/dashboards/widgets/_components/WidgetDataTable.vue, apps/web/src/services/dashboards/widgets/cost-widgets/cost-summary-multi-fields/CostSummaryMultiFieldsWidget.vue
=> feat: set 10 limits to column data & update style of th in widget data table

apps/web/src/common/components/inputs/TagsInput.vue, apps/web/src/services/asset-inventory/components/ServiceAccountBaseInformationForm.vue, apps/web/src/services/asset-inventory/components/ServiceAccountCredentialsForm.vue, apps/web/src/services/asset-inventory/components/ServiceAccountProjectForm.vue, apps/web/src/services/asset-inventory/helpers/dynamic-ui-schema-generator/dynamic-layout-schema-template.ts, apps/web/src/services/iam/components/UserManagementAddTag.vue, apps/web/src/services/iam/components/UserManagementFormModal.vue, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ko.json
=> feat: create TagsInput component & minor changed

apps/web/src/lib/menu/menu-info.ts, apps/web/src/services/asset-inventory/components/MetricExplorerChartLegends.vue, apps/web/src/services/asset-inventory/components/MetricExplorerFiltersPopper.vue, apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue, apps/web/src/services/asset-inventory/pages/MetricExplorerDetailPage.vue, apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts
=> feat: update metric legend, filters popper & load metric when init metric detail page

apps/web/src/router/helpers/route-helper.ts
=> fix: solve cost-report redirect issue

apps/web/src/common/pages/CostReportDetailPage.vue
=> fix(cost-report-detail-page): fix icon bug

apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue, apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts
=> fix(metric-lsb): apply namespace api & model

apps/web/src/common/modules/navigations/gnb/GNBNavigationRail.vue
=> chore: change hover style

apps/web/src/services/alert-manager/components/AlertDetailInfoTable.vue, apps/web/src/services/asset-inventory/components/ServiceAccountCredentials.vue, apps/web/src/services/asset-inventory/components/ServiceAccountCredentialsDetail.vue, apps/web/src/services/asset-inventory/components/ServiceAccountCredentialsForm.vue, apps/web/src/services/asset-inventory/helpers/dynamic-ui-schema-generator/dynamic-layout-schema-template.ts, apps/web/src/services/asset-inventory/pages/ServiceAccountAddPage.vue, apps/web/src/services/asset-inventory/types/service-account-page-type.ts, packages/mirinae/src/data-display/dynamic/dynamic-layout/templates/item/index.vue, packages/mirinae/src/data-display/dynamic/dynamic-layout/type/layout-schema.ts, packages/mirinae/src/data-display/tables/definition-table/PDefinitionTable.vue
=> feat: add DynamicLayout item type spec & fix PDefinitionTable css

apps/web/src/services/asset-inventory/pages/CloudServiceDetailPage.vue
=> fix: add filter for cloud service list at security page

apps/web/src/schema/identity/role/constant.ts, apps/web/src/schema/identity/role/model.ts, apps/web/src/schema/identity/role/type.ts, apps/web/src/services/iam/components/AppManagementFormModal.vue, apps/web/src/services/iam/components/UserManagementAddAdminRole.vue, apps/web/src/services/iam/components/UserManagementAddRole.vue, apps/web/src/services/iam/components/UserManagementFormAdminRole.vue, apps/web/src/services/iam/components/UserManagementTabWorkspace.vue, apps/web/src/services/iam/components/UserManagementTable.vue, apps/web/src/services/iam/store/app-page-store.ts, apps/web/src/services/iam/store/role-page-store.ts, apps/web/src/services/iam/store/user-page-store.ts, apps/web/src/services/preference/store/workspace-page-store.ts, apps/web/src/store/reference/user-reference-store.ts
* feat: add `state` to role model
* feat: set 'state' filter to role/list query
---------
=> feat: add state to role model & set 'state' filter to role/list query(#3330)

apps/web/src/services/dashboards/widgets/cost-widgets/cost-summary-multi-fields/CostSummaryMultiFieldsWidget.vue
=> chore: fix minor tooltip bug

apps/web/src/common/modules/navigations/lsb/modules/LSBRouterMenuItem.vue, apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue, apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts
=> fix: apply metric api to metric lsb 

apps/web/src/common/modules/navigations/lsb/LSB.vue, apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue, apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts
=> fix: refactor data loading ui & update some ui & update lsb slot-type spec 

apps/web/src/schema/monitoring/event-rule/type.ts, apps/web/src/services/project/components/ProjectAlertEventRuleActionForm.vue, apps/web/src/services/project/components/ProjectAlertEventRuleContent.vue, apps/web/src/services/project/components/ProjectAlertEventRuleForm.vue, apps/web/src/store/reference/all-reference-store.ts, apps/web/src/store/reference/escalation-policy-reference-store.ts, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> fix(event-rule): enhance event-rule with escalation policy & create escalation-policy reference store

apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue
=> fix: apply metric lsb scenario in metric detail page

apps/web/src/common/components/mapping-method/MappingMethod.vue, apps/web/src/common/components/mapping-method/type.ts, apps/web/src/services/asset-inventory/components/ServiceAccountAutoSyncForm.vue, apps/web/src/services/asset-inventory/components/ServiceAccountDeleteModal.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountAddPage.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountDetailPage.vue, apps/web/src/services/asset-inventory/stores/service-account-page-store.ts, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: add autoSyncForm markup

apps/web/src/services/dashboards/widgets/_constants/managed-widget-options-schema.ts
=> feat: add project_group to `MANAGED_WIDGET_FILTERS_SCHEMA_PROPERTIES`

apps/web/src/common/modules/navigations/lsb/modules/LSBCollapsibleMenuItem.vue, apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> fix(metric-lsb): apply new planning

apps/web/src/services/asset-inventory/AssetInventoryLSB.vue, apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue
=> fix: edit bug & typo

apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue, apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> fix: solve metric detail lsb error

apps/web/src/services/asset-inventory/components/MetricExplorerChart.vue, apps/web/src/services/asset-inventory/components/MetricExplorerLineChart.vue, apps/web/src/services/asset-inventory/constants/metric-explorer-constant.ts, apps/web/src/services/asset-inventory/helpers/metric-explorer-chart-data-helper.ts, apps/web/src/services/asset-inventory/types/metric-explorer-type.ts
=> feat: add metric line chart & helper, types, constants

apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> fix(metric-lsb): add empty case at keyword search

apps/web/src/services/asset-inventory/components/MetricExplorerChart.vue, apps/web/src/services/asset-inventory/components/MetricExplorerOperatorDropdown.vue, apps/web/src/services/asset-inventory/helpers/metric-explorer-chart-data-helper.ts, apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts, apps/web/src/services/asset-inventory/types/metric-explorer-type.ts
=> feat: add `selectedOperator` state to metric page store and use it

apps/web/src/common/modules/favorites/favorite-button/FavoriteButton.vue, apps/web/src/common/modules/navigations/top-bar/TopBar.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-header/TopBarWorkspaces.vue, apps/web/src/lib/helper/config-data-helper.ts, apps/web/src/services/landing/components/LandingContents.vue, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: apply favorite at workspace dropdown

apps/web/src/common/modules/navigations/stores/recent-store.ts, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-header/TopBarWorkspaces.vue, apps/web/src/common/modules/navigations/type.ts, apps/web/src/lib/helper/config-data-helper.ts, apps/web/src/services/landing/components/LandingAllWorkspaces.vue, apps/web/src/services/landing/components/LandingContents.vue, apps/web/src/services/landing/components/LandingRecentVisits.vue, apps/web/src/services/landing/components/LandingWorkspaceBoard.vue, apps/web/src/services/landing/type/type.ts
=> feat: apply recent

apps/web/src/services/landing/components/LandingContents.vue
=> chore: changed file path

apps/web/src/services/asset-inventory/components/MetricExplorerChart.vue, apps/web/src/services/asset-inventory/components/MetricExplorerDonutChart.vue, apps/web/src/services/asset-inventory/components/MetricExplorerLineChart.vue, apps/web/src/services/asset-inventory/helpers/metric-explorer-chart-data-helper.ts, apps/web/src/services/asset-inventory/types/metric-explorer-type.ts
=> feat: add donut chart to metric page & create donut chart helper

apps/web/src/services/asset-inventory/components/ServiceAccountAutoSyncForm.vue, apps/web/src/services/asset-inventory/components/WorkspaceDropdown.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountAddPage.vue, apps/web/src/services/asset-inventory/stores/service-account-page-store.ts, packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
SSIA
https://github.com/cloudforet-io/console/assets/50662170/792f3556-5b45-449f-bcea-d33b06a23f40
=> feat: create Workspace Mapping

apps/web/src/services/asset-inventory/components/MetricExplorerChart.vue, apps/web/src/services/asset-inventory/components/MetricExplorerDonutChart.vue, apps/web/src/services/asset-inventory/components/MetricExplorerTreeMapChart.vue, apps/web/src/services/asset-inventory/helpers/metric-explorer-chart-data-helper.ts, apps/web/src/services/asset-inventory/types/metric-explorer-type.ts
=> feat: add treemap chart to metric page 

apps/web/src/services/asset-inventory/components/MetricExplorerChart.vue, apps/web/src/services/asset-inventory/components/MetricExplorerHorizontalColumnChart.vue
=> feat: add column chart to metric page

apps/web/src/services/asset-inventory/components/ServiceAccountAutoSyncForm.vue, apps/web/src/services/asset-inventory/components/ServiceAccountAutoSyncMappingMethod.vue, apps/web/src/services/asset-inventory/components/WorkspaceDropdown.vue, apps/web/src/services/asset-inventory/stores/service-account-page-store.ts
=> fix: refactor used pinia store method & feat minor things

apps/web/src/services/alert-manager/components/EscalationPolicyFormModal.vue, apps/web/src/services/project/components/ProjectAlertSettingsEscalationPolicyChangeModal.vue
=> fix(escalation-policy): apply reference sync to escalation policy create/edit

apps/web/src/services/project/components/ProjectAlertEventRuleActionForm.vue, apps/web/src/store/reference/escalation-policy-reference-store.ts
=> fix(event-rule): apply escalation-policy filtering in event-rule action form

apps/web/src/services/asset-inventory/components/ServiceAccountCredentialsForm.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountAddPage.vue, apps/web/src/services/asset-inventory/types/service-account-page-type.ts
=> fix: rollback jsonSchema tab

apps/web/src/common/modules/favorites/favorite-button/FavoriteButton.vue, apps/web/src/common/modules/favorites/favorite-button/store/favorite-store.ts, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-header/TopBarWorkspaces.vue, apps/web/src/services/landing/components/LandingContents.vue, apps/web/src/services/landing/components/LandingWorkspaceBoard.vue
=> refactor: separate API for fetching workspaces in the 'favorite' config

apps/web/src/common/modules/navigations/top-bar/modules/top-bar-header/TopBarWorkspaces.vue, apps/web/src/services/landing/components/LandingContents.vue, apps/web/src/services/landing/components/LandingSearch.vue, apps/web/src/services/landing/components/LandingWorkspaceBoard.vue
=> feat: apply search

apps/web/src/services/landing/components/LandingContents.vue, apps/web/src/services/landing/components/LandingWorkspaceBoard.vue, apps/web/src/services/landing/pages/LandingPage.vue
=> feat: apply mobile reactivation

apps/web/src/services/landing/components/LandingContents.vue, apps/web/src/services/preference/components/WorkspaceManagementTable.vue, apps/web/src/services/preference/components/WorkspacesUserManagementTab.vue, apps/web/src/services/preference/components/WorkspacesUserManagementTabContents.vue, apps/web/src/services/preference/pages/admin/AdminWorkspacesPage.vue
=> feat: update workspace page

apps/web/src/schema/identity/provider/model.ts, apps/web/src/services/asset-inventory/components/ServiceAccountAutoSyncForm.vue, apps/web/src/services/asset-inventory/stores/service-account-page-store.ts, apps/web/src/services/asset-inventory/stores/service-account-schema-store.ts, apps/web/src/store/reference/provider-reference-store.ts, apps/web/src/store/reference/type.ts
=> feat: apply real additional options

apps/web/src/services/asset-inventory/components/CollectorFormSchedule.vue, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: display error message when setting more than 2 schedules

apps/web/src/common/composables/amcharts5/pie-chart-helper.ts, apps/web/src/common/composables/amcharts5/tree-map-helper.ts, apps/web/src/common/pages/CostReportDetailPage.vue, apps/web/src/services/cost-explorer/components/CostReportMonthlyTotalAmountSummaryCard.vue, apps/web/src/services/dashboards/widgets/_base-widgets/base-pie/BasePieWidget.vue, apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region/CostByRegionWidget.vue, apps/web/src/services/dashboards/widgets/cost-widgets/cost-map/CostMapWidget.vue
Just update chart tooltip helper
=> feat: use valueFormatter rather than currency in tooltip helper

apps/web/src/schema/identity/workspace/model.ts, apps/web/src/services/auth/helpers/default-route-helper.ts, apps/web/src/services/auth/pages/SignInPage.vue, apps/web/src/services/landing/components/LandingWorkspaceBoard.vue
=> feat: apply landing page

apps/web/src/schema/identity/trusted-account/api-verbs/create.ts, apps/web/src/services/asset-inventory/components/ServiceAccountAutoSyncForm.vue, apps/web/src/services/asset-inventory/components/ServiceAccountCredentials.vue, apps/web/src/services/asset-inventory/components/ServiceAccountCredentialsForm.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountAddPage.vue, apps/web/src/services/asset-inventory/stores/service-account-page-store.ts, apps/web/src/services/asset-inventory/types/service-account-page-type.ts
=> feat: apply AutoSyncForm validation & apply trustedAccount create api in Admin mode

apps/web/src/services/asset-inventory/components/ServiceAccountAutoSyncForm.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountDetailPage.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue
=> feat: add auto sync section to workspace mode

apps/web/src/schema/identity/trusted-account/api-verbs/update.ts, apps/web/src/schema/identity/trusted-account/model.ts, apps/web/src/services/asset-inventory/components/ServiceAccountAutoSync.vue, apps/web/src/services/asset-inventory/components/ServiceAccountAutoSyncDetail.vue, apps/web/src/services/asset-inventory/components/ServiceAccountAutoSyncForm.vue, apps/web/src/services/asset-inventory/components/ServiceAccountAutoSyncMappingMethod.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountAddPage.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountDetailPage.vue, apps/web/src/services/asset-inventory/stores/service-account-page-store.ts, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: apply autoSync to ServiceAccountDetailPage

apps/web/src/services/asset-inventory/components/MetricExplorerChart.vue, apps/web/src/services/asset-inventory/components/MetricExplorerChartLegends.vue, apps/web/src/services/asset-inventory/components/MetricExplorerDonutChart.vue, apps/web/src/services/asset-inventory/components/MetricExplorerHorizontalColumnChart.vue, apps/web/src/services/asset-inventory/components/MetricExplorerLineChart.vue, apps/web/src/services/asset-inventory/components/MetricExplorerTreeMapChart.vue, apps/web/src/services/asset-inventory/helpers/metric-explorer-chart-data-helper.ts, apps/web/src/services/asset-inventory/types/metric-explorer-type.ts, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: set custom color to charts & update legends

packages/mirinae/src/styles/colors.cjs
gray150 and violet150 have been added.
- [x] Not that difficult
🍀
=> feat: add new colors

apps/web/src/services/cost-explorer/components/CostAnalysisChart.vue, apps/web/src/services/cost-explorer/components/CostAnalysisDataTable.vue, apps/web/src/services/cost-explorer/components/CostAnalysisDataTypeDropdown.vue, apps/web/src/services/cost-explorer/components/CostAnalysisQuerySection.vue, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: move data type dropdown to query section & update analyze query

apps/web/src/services/asset-inventory/components/ServiceAccountAttachedGeneralAccounts.vue, apps/web/src/services/asset-inventory/components/ServiceAccountAutoSync.vue, apps/web/src/services/asset-inventory/components/ServiceAccountAutoSyncDetail.vue, apps/web/src/services/asset-inventory/components/ServiceAccountAutoSyncMappingMethod.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountAddPage.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountDetailPage.vue, apps/web/src/services/asset-inventory/stores/service-account-page-store.ts, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: add direct sync button & fix UI bug of AutoSync section

apps/web/src/common/modules/navigations/lsb/modules/LSBMenuItem.vue, apps/web/src/common/modules/navigations/lsb/modules/LSBStarredMenuItem.vue, apps/web/src/common/modules/navigations/lsb/type.ts, apps/web/src/services/dashboards/DashboardsLSB.vue, apps/web/src/services/landing/components/LandingContents.vue, apps/web/src/services/landing/components/LandingWorkspaceBoard.vue, apps/web/src/services/landing/store/landing-page-store.ts, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json
=> feat: create starred type at lsb menu item and minor change

apps/web/src/services/asset-inventory/components/ServiceAccountAttachedGeneralAccounts.vue, apps/web/src/store/app-context/workspace/user-workspace-store.ts
=> feat: update table fields & route

apps/web/src/services/asset-inventory/components/ServiceAccountAttachedGeneralAccounts.vue
=> fix: fix payload value of sync request

apps/web/src/common/composables/error/errorHandler.ts, apps/web/src/services/asset-inventory/components/ServiceAccountAttachedGeneralAccounts.vue, apps/web/src/services/asset-inventory/components/ServiceAccountAutoSyncForm.vue, apps/web/src/services/asset-inventory/components/ServiceAccountDeleteModal.vue, apps/web/src/services/asset-inventory/components/ServiceAccountEditModal.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountAddPage.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountDetailPage.vue
=> fix: fix auto-sync qa bugs

apps/web/src/services/asset-inventory/components/CollectorFormSchedule.vue, apps/web/src/services/asset-inventory/stores/collector-form-store.ts
=> refactor: switching to using store state

apps/web/src/services/asset-inventory/components/ServiceAccountAttachedGeneralAccounts.vue, apps/web/src/services/asset-inventory/components/ServiceAccountAutoSync.vue, apps/web/src/services/asset-inventory/components/ServiceAccountAutoSyncDetail.vue, apps/web/src/services/asset-inventory/components/ServiceAccountAutoSyncForm.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountAddPage.vue
=> fix: fix service account bugs

apps/web/src/services/project/components/ProjectMainTree.vue, apps/web/src/services/project/components/SSSProjectMainProjectTree.vue, apps/web/src/services/project/tree/TreeItem.vue, apps/web/src/services/project/tree/TreeView.vue, apps/web/src/services/project/tree/type.ts, apps/web/src/services/project/tree/use-project-tree-data.ts
=> feat(tree): create new tree component & create project tree

apps/web/src/services/cost-explorer/components/CostAnalysisDataTable.vue, apps/web/src/services/preference/components/DomainSettingsBaseInformation.vue
=> fix: show document title as 'SpaceONE' when there's no domain name

apps/web/src/services/iam/components/UserManagementAddAdminRole.vue
=> feat: show only enabled workspaces in user management modal

apps/web/src/services/asset-inventory/pages/CollectorHistoryPage.vue
=> fix: fix pagination bug in collector history

apps/web/src/common/modules/navigations/lsb/modules/LSBButtonTitleMenuItem.vue, apps/web/src/common/modules/navigations/lsb/modules/LSBDropdownMenuItem.vue, apps/web/src/common/modules/navigations/lsb/modules/LSBMenuItem.vue, apps/web/src/common/modules/navigations/lsb/modules/LSBRouterMenuItem.vue, apps/web/src/common/modules/navigations/lsb/modules/LSBStarredMenuItem.vue, apps/web/src/common/modules/navigations/lsb/modules/LSBTopTitleMenuItem.vue, apps/web/src/common/modules/navigations/lsb/type.ts, apps/web/src/services/dashboards/DashboardsLSB.vue
=> refactor: componentization of menu items and addition of button-title type

apps/web/src/services/asset-inventory/components/ServiceAccountAttachedGeneralAccounts.vue, apps/web/src/services/asset-inventory/components/ServiceAccountAutoSync.vue, apps/web/src/services/asset-inventory/components/ServiceAccountAutoSyncForm.vue, apps/web/src/services/asset-inventory/components/ServiceAccountAutoSyncMappingMethod.vue, apps/web/src/services/asset-inventory/components/WorkspaceDropdown.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountAddPage.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountDetailPage.vue, apps/web/src/services/asset-inventory/stores/service-account-page-store.ts
=> feat: show auto-sync form if It is main provider & fix minor things

apps/web/src/schema/identity/service-account/model.ts, apps/web/src/services/asset-inventory/components/ServiceAccountConnectCluster.vue, apps/web/src/services/asset-inventory/components/ServiceAccountConnectClusterDetail.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountDetailPage.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue
=> feat(service-account): create agent mode markup

apps/web/src/services/asset-inventory/components/ServiceAccountBaseInformation.vue, apps/web/src/services/asset-inventory/components/ServiceAccountBaseInformationDetail.vue, apps/web/src/services/asset-inventory/components/ServiceAccountBaseInformationForm.vue, apps/web/src/services/asset-inventory/components/ServiceAccountEditModal.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountAddPage.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountDetailPage.vue, apps/web/src/services/asset-inventory/stores/service-account-page-store.ts
=> fix: refactor baseInformation form of serviceAccount

apps/web/src/services/project/components/ProjectMainCardList.vue
=> feat: set '...' to long service accounts and update style

packages/language-pack/console-translation-2.8.babel, packages/language-pack/ja.json, packages/language-pack/ko.json
=> chore: Add translation - from [English] to [Korean/Japanese]

apps/web/src/common/modules/navigations/top-bar/modules/top-bar-header/WorkspaceLogoIcon.vue
=> fix: applying special character exceptions for workspace names

apps/web/src/schema/identity/job/api-verbs/delete.ts, apps/web/src/schema/identity/job/api-verbs/get.ts, apps/web/src/schema/identity/job/api-verbs/list.ts, apps/web/src/schema/identity/job/api-verbs/stat.ts, apps/web/src/schema/identity/job/model.ts, apps/web/src/schema/identity/job/type.ts, apps/web/src/services/asset-inventory/components/ServiceAccountAttachedGeneralAccounts.vue, apps/web/src/services/asset-inventory/components/ServiceAccountAutoSyncMappingMethod.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountAddPage.vue, apps/web/src/services/asset-inventory/stores/service-account-page-store.ts, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: add Last Synced to ServiceAccountDetailPage

apps/web/src/services/asset-inventory/components/ServiceAccountAttachedGeneralAccounts.vue, apps/web/src/services/asset-inventory/components/ServiceAccountAutoSyncDetail.vue, apps/web/src/services/asset-inventory/stores/service-account-page-store.ts, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: add auto sync job indicator

apps/web/src/services/asset-inventory/components/ServiceAccountAttachedGeneralAccounts.vue, apps/web/src/services/asset-inventory/stores/service-account-page-store.ts, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: add loading for Sync processing

apps/web/src/schema/identity/agent/api-verbs/create.ts, apps/web/src/schema/identity/agent/api-verbs/delete.ts, apps/web/src/schema/identity/agent/api-verbs/disable.ts, apps/web/src/schema/identity/agent/api-verbs/enable.ts, apps/web/src/schema/identity/agent/api-verbs/get.ts, apps/web/src/schema/identity/agent/api-verbs/list.ts, apps/web/src/schema/identity/agent/api-verbs/regenerate.ts, apps/web/src/schema/identity/agent/model.ts
=> feat(schema): create agent resource schema

apps/web/src/services/asset-inventory/components/ServiceAccountAutoSync.vue, apps/web/src/services/asset-inventory/helpers/dynamic-ui-schema-generator/dynamic-layout-schema-template.ts, apps/web/src/services/asset-inventory/pages/ServiceAccountDetailPage.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue, apps/web/src/store/reference/trusted-account-reference-store.ts
=> feat: add new field to generalAccount table

apps/web/src/services/asset-inventory/components/ServiceAccountAutoSync.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountAddPage.vue, apps/web/src/services/asset-inventory/stores/service-account-page-store.ts
=> feat: add docs link to autoSync section

apps/web/src/services/asset-inventory/components/ServiceAccountAddClusterModal.vue, apps/web/src/services/asset-inventory/components/ServiceAccountConnectCluster.vue, apps/web/src/services/asset-inventory/components/ServiceAccountConnectClusterDetail.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountDetailPage.vue, apps/web/src/services/asset-inventory/stores/service-account-agent-store.ts
=> fix(add-cluster): apply store & some refactoring

apps/web/src/services/workspace-home/components/Bookmark.vue, apps/web/src/services/workspace-home/components/BookmarkBoard.vue, apps/web/src/services/workspace-home/components/BookmarkFullMode.vue, apps/web/src/services/workspace-home/components/BookmarkHeader.vue, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
SSIA
- normal mode
- full mode
=> feat: markup bookmark section

apps/web/src/services/cost-explorer/components/CostAnalysisDataTypeDropdown.vue
=> chore: add optional code

apps/web/src/services/asset-inventory/components/ServiceAccountAttachedGeneralAccounts.vue, apps/web/src/services/asset-inventory/components/ServiceAccountAutoSync.vue, apps/web/src/services/asset-inventory/components/ServiceAccountAutoSyncForm.vue, apps/web/src/services/asset-inventory/components/ServiceAccountAutoSyncMappingMethod.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountAddPage.vue, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> fix: fix auto-sync quest qa bugs

apps/web/src/services/alert-manager/pages/EscalationPolicyPage.vue
SSIA
[Feedback Link](https://www.notion.so/Escalation-Policy-filter-8a0f954a48fb4481806c4c8383d26721?pvs=4)
=> fix(escalation-policy): add filters & edit keyItemSets name

apps/web/src/common/modules/favorites/favorite-button/type.ts, apps/web/src/common/modules/navigations/top-bar/modules/TopBarSuggestionList.vue, apps/web/src/common/modules/navigations/type.ts, apps/web/src/lib/helper/config-data-helper.ts, apps/web/src/services/landing/components/LandingContents.vue, apps/web/src/services/workspace-home/components/UserConfigRecent.vue, apps/web/src/services/workspace-home/components/UserConfigs.vue, apps/web/src/services/workspace-home/components/UserConfigsItem.vue, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: create recent section

apps/web/src/schema/identity/project/model.ts, apps/web/src/schema/identity/service-account/model.ts, apps/web/src/schema/identity/workspace/model.ts, apps/web/src/services/asset-inventory/components/ServiceAccountDeleteModal.vue, apps/web/src/services/preference/components/WorkspacesDeleteModal.vue, apps/web/src/services/project/pages/ProjectDetailPage.vue, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json, packages/mirinae/src/feedbacks/modals/advanced/double-check-modal/PDoubleCheckModal.vue, packages/mirinae/src/inputs/forms/field-group/PFieldGroup.vue
=> feat(workspace): add deleteModal for synced service account

apps/web/src/common/modules/favorites/favorite-button/type.ts, apps/web/src/services/workspace-home/components/UserConfigRecent.vue, apps/web/src/services/workspace-home/components/UserConfigStarred.vue, apps/web/src/services/workspace-home/components/UserConfigs.vue, packages/language-pack/console-translation-2.8.babel, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: create starred section

apps/web/src/schema/identity/agent/model.ts, apps/web/src/services/asset-inventory/components/ServiceAccountDeleteModal.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountDetailPage.vue
=> feat(agent-account): apply agent delete warning

apps/web/src/schema/identity/agent/model.ts, apps/web/src/services/asset-inventory/components/ServiceAccountAddClusterModal.vue, apps/web/src/services/asset-inventory/components/ServiceAccountCluster.vue, apps/web/src/services/asset-inventory/components/ServiceAccountClusterDetail.vue
=> feat(cluster): apply real api to cluster table & modal

apps/web/src/services/asset-inventory/components/ServiceAccountAddClusterModal.vue, apps/web/src/services/asset-inventory/components/ServiceAccountCluster.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountAddPage.vue, apps/web/src/services/asset-inventory/stores/service-account-agent-store.ts
=> fix(agent-mode): solve small issues

apps/web/src/services/asset-inventory/components/ServiceAccountCluster.vue, apps/web/src/services/asset-inventory/components/ServiceAccountClusterDetail.vue, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> chore: translation

apps/web/src/services/asset-inventory/components/ServiceAccountAddClusterModal.vue, apps/web/src/services/asset-inventory/components/ServiceAccountCluster.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue
=> fix: agent mode QA

apps/web/src/schema/inventory/metric/model.ts, apps/web/src/services/asset-inventory/components/MetricExplorerChart.vue, apps/web/src/services/asset-inventory/components/MetricExplorerDonutChart.vue, apps/web/src/services/asset-inventory/components/MetricExplorerLineChart.vue, apps/web/src/services/asset-inventory/constants/metric-explorer-constant.ts, apps/web/src/services/asset-inventory/helpers/metric-explorer-chart-data-helper.ts, apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts, apps/web/src/services/asset-inventory/types/metric-explorer-type.ts
=> feat: apply real data to metric chart

apps/web/src/services/asset-inventory/components/MetricExplorerDataTable.vue, apps/web/src/services/asset-inventory/helpers/metric-explorer-data-table-helper.ts, apps/web/src/services/cost-explorer/CostExplorerLSB.vue
=> feat: apply real data to metric data table

apps/web/src/services/asset-inventory/components/ServiceAccountAddClusterModal.vue, apps/web/src/services/asset-inventory/components/ServiceAccountAddClusterScriptField.vue, apps/web/src/services/asset-inventory/components/ServiceAccountDeleteModal.vue, apps/web/src/services/asset-inventory/constants/service-account-constant.ts, apps/web/src/services/asset-inventory/pages/ServiceAccountDetailPage.vue, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> fix(QA): small fixes

apps/web/src/services/asset-inventory/components/ServiceAccountAddClusterModal.vue, apps/web/src/services/asset-inventory/components/ServiceAccountAddClusterScriptField.vue, apps/web/src/services/asset-inventory/components/ServiceAccountEditModal.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountDetailPage.vue, apps/web/src/services/asset-inventory/stores/service-account-page-store.ts
=> fix(service-account-edit): refactor edit modal visible & solve issue

apps/web/src/services/asset-inventory/components/ServiceAccountAddClusterModal.vue, apps/web/src/services/asset-inventory/stores/service-account-agent-store.ts, packages/mirinae/src/feedbacks/modals/icon-modal/PIconModal.vue
=> fix(cluster-modal): edit modal style & add new slot to p-icon-modal

apps/web/src/services/workspace-home/components/WorkspaceInfo.vue
=> feat: apply real data and func at workspaceInfo

apps/web/src/common/modules/custom-table/custom-field-modal/CustomFieldModal.vue, apps/web/src/services/asset-inventory/helpers/agent-mode-helper.ts, apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue
=> fix(agent-mode): create service-account agent fields convertor & apply

apps/web/src/services/asset-inventory/pages/ServiceAccountDetailPage.vue
=> fix(service-account-detail): apply service-account scenario feedback

apps/web/src/common/modules/page-layouts/GeneralPageLayout.vue, apps/web/src/services/preference/pages/admin/AdminWorkspacesPage.vue, apps/web/src/services/workspace-home/components/WorkspaceInfo.vue, apps/web/src/services/workspace-home/pages/WorkspaceHomePage.vue
=> feat: apply workspace edit/delete modal at workspace_info section

apps/web/src/services/asset-inventory/components/MetricExplorerChart.vue, apps/web/src/services/asset-inventory/components/MetricExplorerDataTable.vue, apps/web/src/services/asset-inventory/components/MetricExplorerPeriodDropdown.vue, apps/web/src/services/asset-inventory/components/MetricExplorerQuerySection.vue, apps/web/src/services/asset-inventory/helpers/metric-explorer-chart-data-helper.ts, apps/web/src/services/asset-inventory/helpers/metric-explorer-data-helper.ts, apps/web/src/services/asset-inventory/helpers/metric-explorer-data-table-helper.ts, apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: add refreshMetricData flag for refreshing page & show period label and refresh button 

apps/web/src/services/asset-inventory/components/ServiceAccountAddClusterModal.vue
=> fix: edit request field typo

apps/web/src/services/asset-inventory/components/MetricExplorerChart.vue, apps/web/src/services/asset-inventory/components/MetricExplorerGroupBy.vue, apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue, apps/web/src/services/asset-inventory/constants/metric-explorer-constant.ts, apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts
=> feat: set 'unit' to group by

apps/web/src/common/modules/favorites/favorite-button/FavoriteButton.vue, apps/web/src/services/workspace-home/components/UserConfigRecent.vue, apps/web/src/services/workspace-home/components/UserConfigStarred.vue, apps/web/src/services/workspace-home/components/UserConfigsItem.vue
=> feat: apply click event at user configs item

apps/web/src/services/asset-inventory/components/ServiceAccountAddClusterModal.vue, apps/web/src/services/asset-inventory/constants/service-account-constant.ts
=> fix: edit cluster options typo

apps/web/src/services/workspace-home/components/AssetSummary.vue, apps/web/src/services/workspace-home/components/AssetSummaryDailyUpdateItem.vue, apps/web/src/services/workspace-home/components/AssetSummaryItem.vue, apps/web/src/services/workspace-home/types/workspace-home-type.ts
SSIA
Plz check by files changed
=> feat: apply data at asset summary

apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue, apps/web/src/services/asset-inventory/pages/MetricExplorerDetailPage.vue, apps/web/src/services/asset-inventory/pages/MetricExplorerMainPage.vue, apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts
=> feat: add custom breadcrumb

apps/web/src/services/project/ProjectLSB.vue, apps/web/src/services/project/tree/use-project-tree-data.ts
=> fix(project-tree-hook): apply change project-group name

apps/web/src/common/components/badge/AutoSyncState.vue, apps/web/src/services/asset-inventory/components/ServiceAccountAutoSyncMappingMethod.vue, apps/web/src/services/asset-inventory/helpers/dynamic-ui-schema-generator/dynamic-layout-schema-template.ts, apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue, apps/web/src/services/asset-inventory/stores/service-account-page-store.ts, apps/web/src/services/asset-inventory/stores/service-account-schema-store.ts
=> fix: fix auto-sync quest QA

apps/web/src/services/workspace-home/components/AssetSummary.vue, apps/web/src/services/workspace-home/components/UserConfigStarred.vue, apps/web/src/services/workspace-home/components/WorkspaceInfo.vue, apps/web/src/services/workspace-home/routes/admin/routes.ts, apps/web/src/services/workspace-home/routes/routes.ts
=> refactor: route workspace mode app page and apply permission check

apps/web/src/lib/site-initializer/api-client.ts, apps/web/src/services/dashboards/stores/all-reference-type-info-store.ts, apps/web/src/store/reference/all-reference-store.ts, apps/web/src/store/reference/metric-reference-store.ts, apps/web/src/store/reference/namespace-reference-store.ts
=> feat: add referenceStore (namespace, metric)

apps/web/src/lib/helper/router-recent-helper.ts, apps/web/src/lib/reference/referenceRouter.ts, apps/web/src/services/project/ProjectLSB.vue, apps/web/src/services/project/components/ProjectFavoriteList.vue, apps/web/src/services/project/components/ProjectMainTree.vue, apps/web/src/services/project/pages/ProjectMainPage.vue, apps/web/src/services/project/routes/routes.ts, apps/web/src/services/project/tree/use-project-tree-data.ts
=> fix(project): renewal project route structure & create new project lsb

apps/web/src/services/asset-inventory/components/ServiceAccountAddClusterModal.vue, apps/web/src/services/asset-inventory/components/ServiceAccountCluster.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountAddPage.vue, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> fix(agent-qa): apply changed planning & translation

apps/web/src/services/asset-inventory/components/ServiceAccountBaseInformationForm.vue
=> fix: fix baseInformation form validation

apps/web/src/schema/inventory/metric/model.ts, apps/web/src/store/reference/metric-reference-store.ts
=> fix: fix metric reference store

apps/web/src/services/workspace-home/components/Bookmark.vue, apps/web/src/services/workspace-home/components/BookmarkFolderFormModal.vue, apps/web/src/services/workspace-home/components/BookmarkHeader.vue, apps/web/src/services/workspace-home/components/BookmarkLinkFormModal.vue, apps/web/src/services/workspace-home/store/bookmark-store.ts
=> feat: apply folder filter button

packages/language-pack/en.json
=> chore(agent-mode): edit translation

apps/web/src/services/asset-inventory/components/AddCustomMetricModal.vue, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat(custom-metric): apply create api & add unit field

apps/web/src/services/workspace-home/components/Bookmark.vue, apps/web/src/services/workspace-home/components/BookmarkBoard.vue, apps/web/src/services/workspace-home/components/BookmarkHeader.vue, apps/web/src/services/workspace-home/components/BookmarkLinkFormModal.vue, apps/web/src/services/workspace-home/composables/use-bookmark.ts, apps/web/src/services/workspace-home/store/bookmark-store.ts, apps/web/src/services/workspace-home/types/workspace-home-type.ts, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: add show more at bookmark board and fetch link favicon

apps/web/src/common/modules/favorites/favorite-button/store/favorite-store.ts, apps/web/src/common/modules/navigations/lsb/modules/LSBRouterMenuItem.vue, apps/web/src/services/project/ProjectLSB.vue, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat(project-lsb): add project favorite & create project lsb search

apps/web/src/services/project/components/ProjectMainTree.vue, apps/web/src/services/project/tree/TreeItem.vue
=> feat: add tree favorite button & update tree components

apps/web/src/services/asset-inventory/components/MetricExplorerHeader.vue, apps/web/src/services/asset-inventory/components/MetricExplorerQuerySection.vue, apps/web/src/services/asset-inventory/components/MetricExplorerSaveAsModal.vue, apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: add 'save as' metric modal

apps/web/src/services/project/ProjectLSB.vue, apps/web/src/services/project/pages/ProjectDashboardPage.vue, apps/web/src/services/project/routes/route-constant.ts, apps/web/src/services/project/routes/routes.ts, apps/web/src/services/project/tree/use-project-tree-data.ts
=> feat: set project detail router structure

apps/web/src/services/project/ProjectLSB.vue, apps/web/src/services/project/components/ProjectMain.vue
=> feat(project): create new project contents markup

apps/web/src/services/asset-inventory/components/MetricExplorerEditNameModal.vue, apps/web/src/services/asset-inventory/components/MetricExplorerHeader.vue, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: add 'name edit', 'delete' button to header

apps/web/src/services/asset-inventory/components/ServiceAccountAddClusterModal.vue
=> fix: apply reset form

apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue, apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts
Load Metric for LSB setting in detail page
=> fix: apply lsb planning in metric detail page

apps/web/src/services/asset-inventory/components/ServiceAccountAddClusterModal.vue
=> fix(agent-mode): edit wrong usage of endpoint

apps/web/src/services/project/ProjectLSB.vue, apps/web/src/services/project/pages/ProjectDetailPage.vue, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: set project detail LSB

apps/web/src/services/project/components/ProjectMain.vue, apps/web/src/services/project/components/ProjectMainProjectCard.vue, apps/web/src/services/project/components/ProjectMainProjectGroupCard.vue, apps/web/src/services/project/pages/ProjectMainPage.vue, apps/web/src/services/project/types/project-type.ts
=> feat(project-landing): create project landing cards & apply real data

apps/web/src/services/project/components/ProjectMain.vue, apps/web/src/services/project/components/ProjectMainProjectCard.vue, apps/web/src/services/project/components/ProjectMainProjectGroupCard.vue, apps/web/src/services/project/types/project-type.ts, apps/web/src/store/reference/project-reference-store.ts
SSIA
I added `project_type` to project reference data
=> feat(project-landing): apply project type & favorite button visible

apps/web/src/lib/excel-export/constant.ts, apps/web/src/services/asset-inventory/components/MetricExplorerChart.vue, apps/web/src/services/asset-inventory/components/MetricExplorerDataTable.vue, apps/web/src/services/asset-inventory/components/MetricExplorerHeader.vue, apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts
=> feat: apply filters query to metric page & excel export & delete logic

apps/web/src/services/project/components/ProjectMain.vue, apps/web/src/services/project/components/ProjectMainProjectCard.vue, apps/web/src/services/project/components/ProjectMainProjectGroupCard.vue
=> feat(project-landing): create project toolbox & apply text-highlighting

apps/web/src/common/modules/navigations/type.ts, apps/web/src/lib/helper/router-recent-helper.ts, apps/web/src/services/asset-inventory/pages/MetricExplorerMainPage.vue, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
- Add translations
- Add new images
- Apply recent metrics
=> feat: update metric main page

apps/web/src/services/asset-inventory/components/ServiceAccountCredentialsForm.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountAddPage.vue
=> fix: fix credential init bug

apps/web/src/services/cost-explorer/components/CostAnalysisDataTable.vue, apps/web/src/services/cost-explorer/components/CostAnalysisDataTypeDropdown.vue, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat(cost-analysis): apply cost analysis feedback issues

apps/web/src/App.vue
=> fix: fixed router bug

apps/web/src/services/project/components/ProjectMain.vue, apps/web/src/services/project/types/project-type.ts, packages/mirinae/src/navigation/toolbox/PToolbox.vue, packages/mirinae/src/navigation/toolbox/type.ts
=> feat(project-landing): apply new pagination rule

apps/web/src/services/cost-explorer/types/cost-explorer-chart-type.ts, apps/web/src/services/dashboards/widgets/_types/widget-type.ts, apps/web/src/services/workspace-home/components/CostSummary.vue, apps/web/src/services/workspace-home/components/CostSummaryChart.vue
=> feat: apply cost summary chart

apps/web/src/services/landing/components/LandingEmptyContents.vue, apps/web/src/services/workspace-home/components/AssetSummaryDailyUpdateItem.vue, apps/web/src/services/workspace-home/components/WorkspaceInfo.vue
=> feat: apply route

apps/web/src/common/pages/CostReportDetailPage.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountAddPage.vue, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> fix: fix the costReport base information format

apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue, apps/web/src/store/reference/metric-reference-store.ts, apps/web/src/store/reference/namespace-reference-store.ts
=> fix(metric-lsb): (refactor) remove page store and api call in metric lsb, only use reference store

apps/web/src/services/workspace-home/components/Bookmark.vue, apps/web/src/services/workspace-home/components/BookmarkHeader.vue, apps/web/src/services/workspace-home/components/CostSummary.vue, apps/web/src/services/workspace-home/components/UserConfigRecent.vue, apps/web/src/services/workspace-home/components/UserConfigStarred.vue, apps/web/src/services/workspace-home/components/WorkspaceInfo.vue, apps/web/src/services/workspace-home/pages/WorkspaceHomePage.vue, apps/web/src/services/workspace-home/store/workspace-home-page-store.ts
=> chore: move api function to page store

apps/web/src/services/project/ProjectLSB.vue, apps/web/src/services/project/pages/ProjectDetailPage.vue, apps/web/src/services/project/pages/ProjectDetailTabPage.vue, apps/web/src/services/project/routes/routes.ts, apps/web/src/services/project/stores/project-detail-page-store.ts
=> feat: update project detail route structure

apps/web/src/services/asset-inventory/components/MetricExplorerChartLegends.vue, apps/web/src/services/asset-inventory/components/MetricExplorerDataTable.vue, apps/web/src/services/asset-inventory/components/MetricExplorerLineChart.vue, apps/web/src/services/asset-inventory/components/MetricExplorerPeriodDropdown.vue, apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
Please pass the `chore` commits!
=> feat: change default granularity from monthly to daily & update analyze query for excel export

apps/web/src/services/asset-inventory/components/MetricExplorerEditNameModal.vue, apps/web/src/services/asset-inventory/components/MetricExplorerHeader.vue, apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue, apps/web/src/services/asset-inventory/components/MetricExplorerQueryFormModal.vue, apps/web/src/services/asset-inventory/components/MetricExplorerSaveAsModal.vue, apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts
=> feat: use reference store data for metric

apps/web/src/services/workspace-home/components/UserConfigStarred.vue
=> chore: add missed code

apps/web/src/services/workspace-home/components/AssetSummary.vue, apps/web/src/services/workspace-home/components/CostSummary.vue
=> chore: changed text

apps/web/src/schema/inventory/metric-example/api-verbs/create.ts, apps/web/src/schema/inventory/metric-example/api-verbs/delete.ts, apps/web/src/schema/inventory/metric-example/api-verbs/get.ts, apps/web/src/schema/inventory/metric-example/api-verbs/list.ts, apps/web/src/schema/inventory/metric-example/api-verbs/update.ts, apps/web/src/schema/inventory/metric-example/model.ts
=> feat: add metric-example API schema

apps/web/src/services/workspace-home/components/Bookmark.vue, apps/web/src/services/workspace-home/components/BookmarkBoard.vue, apps/web/src/services/workspace-home/components/BookmarkFullMode.vue, apps/web/src/services/workspace-home/components/BookmarkHeader.vue, apps/web/src/services/workspace-home/components/BookmarkLinkFormModal.vue, apps/web/src/services/workspace-home/components/Summaries.vue, apps/web/src/services/workspace-home/components/UserConfigs.vue, apps/web/src/services/workspace-home/components/WorkspaceInfo.vue, apps/web/src/services/workspace-home/constants/workspace-home-constant.ts, apps/web/src/services/workspace-home/store/bookmark-store.ts
=> feat: apply mobile responsiveness

apps/web/src/services/asset-inventory/components/ProviderList.vue, apps/web/src/services/cost-explorer/CostExplorerLSB.vue
=> fix: add beta mark to kubernetes

apps/web/src/lib/site-initializer/api-client.ts, apps/web/src/services/asset-inventory/components/MetricExplorerFiltersPopper.vue, apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue, apps/web/src/services/asset-inventory/components/MetricExplorerQueryFormModal.vue, apps/web/src/services/asset-inventory/pages/MetricExplorerDetailPage.vue, apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts
=> refactor: refactor metric page store & update usage

apps/web/src/services/alert-manager/components/AlertMainDataTable.vue, apps/web/src/services/project/components/ProjectAlertListTab.vue, apps/web/src/services/project/components/ProjectAlertWebhookAddModal.vue, apps/web/src/services/project/pages/ProjectAlertPage.vue, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json, packages/mirinae/src/feedbacks/modals/icon-modal/PIconModal.vue, packages/mirinae/src/inputs/select-card/PSelectCard.vue
=> feat: update alerList, webhook tab

apps/web/src/services/project/components/ProjectMainTree.vue, apps/web/src/services/project/tree/TreeItem.vue, apps/web/src/services/project/tree/TreeView.vue
=> fix(project-tree): renewal tree component(TreeView, TreeItem) and project tree redrawing

apps/web/src/common/modules/favorites/favorite-button/FavoriteButton.vue, apps/web/src/common/modules/favorites/favorite-button/type.ts, apps/web/src/common/modules/navigations/lsb/modules/LSBRouterMenuItem.vue, apps/web/src/services/cost-explorer/CostExplorerLSB.vue, apps/web/src/services/dashboards/DashboardsLSB.vue
- keep starred data
- apply tooltip
=> feat: apply QA about LSB

apps/web/src/services/project/components/ProjectMainProjectGroupDeleteCheckModal.vue, apps/web/src/services/project/components/ProjectMainProjectGroupFormModal.vue, apps/web/src/services/project/pages/ProjectMainPage.vue, apps/web/src/services/project/stores/project-tree-store.ts, apps/web/src/services/project/tree/use-project-tree-data.ts
=> fix(project-tree): refactor tree-redrawing with tree store

apps/web/src/services/project/components/ProjectAlertWebhookAddModal.vue
=> feat: apply guide link & fix minor css

apps/web/src/services/project/components/ProjectAlertEventRuleActionForm.vue, apps/web/src/services/project/pages/ProjectAlertEventRulePage.vue, apps/web/src/services/project/pages/ProjectDetailPage.vue, packages/language-pack/en.json
=> fix: update event rule page

apps/web/src/services/preference/components/WorkspacesCreateModal.vue, apps/web/src/services/workspace-home/components/EmptySummaryData.vue, apps/web/src/services/workspace-home/components/WorkspaceInfo.vue, apps/web/src/services/workspace-home/pages/WorkspaceHomePage.vue, apps/web/src/services/workspace-home/store/workspace-home-page-store.ts
-  layout modification for workspace-info description
- apply loading at workspace home
=> feat: fixed QA issue

apps/web/src/services/workspace-home/components/Bookmark.vue, apps/web/src/services/workspace-home/components/BookmarkBoard.vue, apps/web/src/services/workspace-home/components/BookmarkFullMode.vue, apps/web/src/services/workspace-home/store/bookmark-store.ts, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: apply empty case

apps/web/src/services/workspace-home/components/BookmarkBoard.vue
=> chore: add condition

apps/web/src/services/project/pages/ProjectMainPage.vue, apps/web/src/services/project/stores/project-tree-store.ts
=> feat: add and apply reset treeDisplayMap

apps/web/src/services/asset-inventory/components/MetricExplorerChart.vue, apps/web/src/services/asset-inventory/components/MetricExplorerChartLegends.vue, apps/web/src/services/asset-inventory/components/MetricExplorerHeader.vue, apps/web/src/services/asset-inventory/pages/MetricExplorerDetailPage.vue, apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts
=> feat: implement metric example & update metric page markup

packages/mirinae/src/data-display/tree/tree-view/PTreeItem.vue, packages/mirinae/src/data-display/tree/tree-view/PTreeView.vue, packages/mirinae/src/data-display/tree/tree-view/type.ts
=> feat(mirinae): create PTreeView & PTreeItem components

apps/web/src/services/workspace-home/pages/WorkspaceHomePage.vue, apps/web/src/services/workspace-home/store/bookmark-store.ts, apps/web/src/services/workspace-home/store/workspace-home-page-store.ts
=> fix: resolved the issue with irregular width of bookmark folders

apps/web/src/services/workspace-home/components/BookmarkBoard.vue, apps/web/src/services/workspace-home/components/BookmarkFullMode.vue, apps/web/src/services/workspace-home/components/UserConfigStarred.vue, apps/web/src/services/workspace-home/components/Welcome.vue, packages/language-pack/en.json
=> chore: apply qa issue

packages/mirinae/src/components.ts
=> chore: make new tree components export

apps/web/src/services/project/components/ProjectMainTree.vue
=> chore: apply PTreeView

apps/web/src/services/project/components/ProjectMainTree.vue
=> chore: edit typo

packages/mirinae/src/data-display/dynamic/dynamic-layout/templates/item/index.vue, packages/mirinae/src/inputs/forms/json-schema-form/PJsonSchemaForm.stories.mdx, packages/mirinae/src/inputs/forms/json-schema-form/PJsonSchemaForm.vue, packages/mirinae/src/inputs/forms/json-schema-form/helpers/form-data-refine-helper.ts, packages/mirinae/src/inputs/forms/json-schema-form/helpers/inner-schema-helper.ts, packages/mirinae/src/inputs/forms/json-schema-form/mock.ts, packages/mirinae/src/inputs/forms/json-schema-form/type.ts, packages/mirinae/src/inputs/input/text-input/PTextInput.vue
=> feat(mirinae): add boolean type to jsonSchemaForm

apps/web/src/services/asset-inventory/pages/CloudServicePage.vue, apps/web/src/services/landing/components/LandingContents.vue, apps/web/src/services/workspace-home/components/Welcome.vue, apps/web/src/services/workspace-home/pages/WorkspaceHomePage.vue, packages/language-pack/en.json
=> chore: apply qa

apps/web/src/services/asset-inventory/components/ServiceAccountAutoSync.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountAddPage.vue
=> fix: add plugin_info payload to trusted account api

apps/web/src/common/modules/favorites/favorite-button/type.ts, apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue
=> fix(metric-example): apply design & favorite-button

packages/mirinae/src/data-display/tree/tree-view/PTreeItem.vue
=> fix(p-tree-item): small fix

apps/web/src/services/workspace-home/components/BookmarkHeader.vue, apps/web/src/services/workspace-home/components/BookmarkLinkFormModal.vue, apps/web/src/services/workspace-home/components/EmptySummaryData.vue, apps/web/src/services/workspace-home/components/Welcome.vue, apps/web/src/services/workspace-home/store/bookmark-store.ts
=> feat: apply QA issue about bookmark

apps/web/src/common/modules/favorites/favorite-button/FavoriteButton.vue, apps/web/src/services/preference/constants/workspace-constant.ts
=> chore: update feedback

apps/web/src/services/asset-inventory/components/MetricExplorerHeader.vue, apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue, apps/web/src/services/asset-inventory/components/MetricExplorerQueryFormModal.vue, apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: add 'update' metric api logic & add query form modal to header

apps/web/src/services/workspace-home/components/BookmarkLinkFormModal.vue
=> feat: generate new folder name

apps/web/src/services/asset-inventory/pages/CloudServiceDetailPage.vue
=> chore: add width options at name field

apps/web/src/services/asset-inventory/pages/MetricExplorerMainPage.vue
=> fix: fix css code (metic Explorer recent card)

apps/web/src/schema/inventory/namespace/model.ts, apps/web/src/services/asset-inventory/pages/MetricExplorerMainPage.vue, apps/web/src/store/reference/namespace-reference-store.ts
=> feat: apply namespace icon

apps/web/src/services/project/components/ProjectMainProjectGroupFormModal.vue, apps/web/src/services/project/composables/use-project-tree-data.ts
=> fix(project-main): solve project/project group creating and moving issue

apps/web/src/services/workspace-home/components/BookmarkBoard.vue
=> refactor: changed component

apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue, apps/web/src/services/asset-inventory/components/MetricExplorerLSBMetric.vue, apps/web/src/services/asset-inventory/components/MetricExplorerLSBMetricTree.vue, apps/web/src/services/asset-inventory/types/metric-explorer-type.ts
=> feat(metric-lsb): create metric example search & separate metric lsb tree components

apps/web/src/common/modules/favorites/favorite-button/FavoriteButton.vue, apps/web/src/common/modules/favorites/favorite-button/store/favorite-store.ts, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-favorite/modules/TopBarFavoriteContextMenu.vue, apps/web/src/lib/helper/config-data-helper.ts, apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue
=> feat(metric-favorite): create metric favorite

apps/web/src/services/landing/components/LandingContents.vue, apps/web/src/services/landing/components/LandingHeader.vue, apps/web/src/services/landing/components/LandingSearch.vue, apps/web/src/services/landing/components/LandingWorkspaceBoard.vue, apps/web/src/services/landing/pages/LandingPage.vue
=> feat: apply qa issue at workspace landing

apps/web/src/common/modules/navigations/top-bar/modules/top-bar-header/TopBarWorkspaces.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-profile/TopBarProfile.vue, apps/web/src/services/landing/components/LandingContents.vue, apps/web/src/services/landing/components/LandingEmptyContents.vue, apps/web/src/services/preference/components/WorkspaceManagementTable.vue, apps/web/src/services/preference/pages/admin/AdminWorkspacesPage.vue, packages/mirinae/src/inputs/context-menu/PContextMenu.vue
=> feat: apply qa issue about workspace dropdown 

packages/mirinae/src/layouts/vertical-layout/PVerticalLayout.vue
=> fix: fix UI bug in sidebar that occur in mobile mode

apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/TopBarMyPageToolset.vue, apps/web/src/services/workspace-home/components/AssetSummary.vue, apps/web/src/services/workspace-home/components/BookmarkBoard.vue, apps/web/src/services/workspace-home/components/BookmarkFullMode.vue, apps/web/src/services/workspace-home/components/BookmarkHeader.vue
=> feat: apply minor qa issue

apps/web/src/services/asset-inventory/components/CloudServiceDetail.vue
=> fix: typo error

apps/web/src/services/asset-inventory/components/MetricExplorerFiltersPopper.vue, apps/web/src/services/asset-inventory/components/MetricExplorerQueryFormSidebar.vue, apps/web/src/services/cost-explorer/components/CostAnalysisFiltersPopper.vue, packages/mirinae/src/layouts/sidebar/PSidebar.vue, packages/mirinae/src/layouts/sidebar/story-helper.ts
=> feat: add backdrop props to PSidebar

apps/web/src/services/asset-inventory/pages/MetricExplorerDetailPage.vue, apps/web/src/services/asset-inventory/pages/MetricExplorerMainPage.vue
=> fix: fix metric favorite bug & recent card css

apps/web/src/lib/variable-models/managed/index.ts, apps/web/src/schema/inventory/metric/model.ts, apps/web/src/schema/inventory/metric/type.ts, apps/web/src/services/asset-inventory/components/MetricExplorerChart.vue, apps/web/src/services/asset-inventory/components/MetricExplorerDataTable.vue, apps/web/src/services/asset-inventory/components/MetricExplorerFiltersPopper.vue, apps/web/src/services/asset-inventory/components/MetricExplorerGroupBy.vue, apps/web/src/services/asset-inventory/components/MetricExplorerQueryFormSidebar.vue, apps/web/src/services/asset-inventory/components/MetricExplorerQuerySection.vue, apps/web/src/services/asset-inventory/constants/metric-explorer-constant.ts, apps/web/src/services/asset-inventory/helpers/metric-explorer-data-helper.ts, apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts, apps/web/src/services/asset-inventory/types/metric-explorer-type.ts
=> feat: update MetricModel 'label_keys' type

packages/mirinae/src/data-display/tree/tree-view/PTreeView.vue
=> fix: fix storybook bug

apps/web/src/lib/site-initializer/index.ts, apps/web/src/services/asset-inventory/components/MetricExplorerChartLegends.vue, apps/web/src/services/asset-inventory/components/MetricExplorerDataTable.vue, apps/web/src/services/asset-inventory/components/MetricExplorerNameFormModal.vue, apps/web/src/services/asset-inventory/components/MetricExplorerQueryFormSidebar.vue, apps/web/src/services/asset-inventory/pages/MetricExplorerDetailPage.vue, apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts
=> feat: apply reference label to data table

apps/web/src/services/landing/components/LandingContents.vue
=> chore: add condition for hide recent list

apps/web/src/services/asset-inventory/components/MetricExplorerFiltersPopper.vue, apps/web/src/services/asset-inventory/components/MetricExplorerQuerySection.vue, apps/web/src/services/asset-inventory/pages/MetricExplorerDetailPage.vue, apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts, apps/web/src/services/asset-inventory/types/metric-explorer-type.ts
=> feat: init filters when metric page loaded

apps/web/src/schema/inventory/metric/type.ts, apps/web/src/services/asset-inventory/components/MetricExplorerChart.vue, apps/web/src/services/asset-inventory/components/MetricExplorerDataTable.vue, apps/web/src/services/asset-inventory/components/MetricExplorerHeader.vue, apps/web/src/services/asset-inventory/helpers/metric-explorer-chart-data-helper.ts
=> feat: set link to metric data table

apps/web/src/services/landing/components/LandingContents.vue, apps/web/src/services/workspace-home/components/UserConfigStarred.vue, apps/web/src/services/workspace-home/constants/workspace-home-constant.ts, apps/web/src/services/workspace-home/types/workspace-home-type.ts
=> chore: minor changed

apps/web/src/services/asset-inventory/components/MetricExplorerLSBMetricTree.vue, packages/mirinae/src/inputs/select-button/PSelectButton.vue
=> fix: fix icon-only css bug & remove favorite button at metric tree

apps/web/src/services/asset-inventory/components/CloudServiceMetricButton.vue, apps/web/src/services/asset-inventory/components/MetricExplorerDataTable.vue, apps/web/src/services/asset-inventory/pages/CloudServiceDetailPage.vue, apps/web/src/store/reference/metric-reference-store.ts, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: add metric button to cloud service page

apps/web/src/services/asset-inventory/components/MetricExplorerHeader.vue, apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue, apps/web/src/services/asset-inventory/components/MetricExplorerLSBMetric.vue, apps/web/src/services/asset-inventory/components/MetricExplorerNameFormModal.vue, apps/web/src/services/asset-inventory/pages/MetricExplorerDetailPage.vue, apps/web/src/services/asset-inventory/pages/MetricExplorerMainPage.vue, apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts
=> fix: fix tree bug in metric lsb

apps/web/src/services/asset-inventory/components/MetricExplorerGranularityDropdown.vue, apps/web/src/services/asset-inventory/components/MetricExplorerLSBMetric.vue, apps/web/src/services/asset-inventory/components/MetricExplorerPeriodDropdown.vue, apps/web/src/services/asset-inventory/components/MetricExplorerQuerySection.vue, apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts
=> feat: load metric examples in lsb

apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/TopBarMyPageToolset.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/TopBarToolset.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-admin-toggle-button/TopBarAdminToggleButton.vue, apps/web/src/services/landing/components/LandingHeader.vue, apps/web/src/services/workspace-home/components/Bookmark.vue, apps/web/src/services/workspace-home/components/BookmarkBoard.vue, apps/web/src/services/workspace-home/components/BookmarkFullMode.vue, packages/mirinae/src/inputs/dropdown/select-dropdown/components/dropdown-button.vue
=> refactor: changed components

apps/web/src/common/modules/navigations/top-bar/modules/top-bar-header/TopBarWorkspaces.vue, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: apply search at workspace dropdown

apps/web/src/common/modules/navigations/top-bar/modules/top-bar-header/TopBarWorkspaces.vue
=> chore: add lowercase

apps/web/src/lib/menu/menu-architecture.ts, apps/web/src/schema/inventory/metric/type.ts, apps/web/src/services/asset-inventory/components/CloudServiceMetricButton.vue, apps/web/src/services/asset-inventory/components/MetricExplorerChart.vue, apps/web/src/services/asset-inventory/components/MetricExplorerChartLegends.vue, apps/web/src/services/asset-inventory/components/MetricExplorerDataTable.vue, apps/web/src/services/asset-inventory/components/MetricExplorerGroupBy.vue, apps/web/src/services/asset-inventory/components/MetricExplorerPeriodDropdown.vue, apps/web/src/services/asset-inventory/constants/metric-explorer-constant.ts, apps/web/src/services/asset-inventory/helpers/metric-explorer-chart-data-helper.ts, apps/web/src/services/asset-inventory/helpers/metric-explorer-data-table-helper.ts, apps/web/src/services/asset-inventory/helpers/metric-explorer-period-helper.ts, apps/web/src/services/asset-inventory/pages/MetricExplorerDetailPage.vue, apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts, apps/web/src/services/asset-inventory/types/metric-explorer-type.ts, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: qaqa

apps/web/src/services/preference/components/DomainSettingsTimezoneAndLanguage.vue, apps/web/src/store/modules/domain/mutations.ts
=> fix: update domain settings at store

apps/web/src/services/asset-inventory/pages/MetricExplorerDetailPage.vue, apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts
=> fix: fix default groupby

apps/web/src/services/asset-inventory/pages/MetricExplorerDetailPage.vue, apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts
=> fix: fix default groupby (#3678)

apps/web/src/lib/menu/config.ts, apps/web/src/lib/menu/menu-architecture.ts, apps/web/src/lib/menu/menu-info.ts, apps/web/src/services/cost-explorer/pages/admin/AdminDataSourcePage.vue, apps/web/src/services/cost-explorer/routes/admin/routes.ts, apps/web/src/services/cost-explorer/routes/route-constant.ts, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json, packages/mirinae/src/inputs/link/PLink.stories.mdx
=> feat: create menu

apps/web/src/services/asset-inventory/components/MetricExplorerChart.vue, apps/web/src/services/asset-inventory/components/MetricExplorerChartLegends.vue, apps/web/src/services/asset-inventory/components/MetricExplorerDonutChart.vue, apps/web/src/services/asset-inventory/components/MetricExplorerHorizontalColumnChart.vue, apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue, apps/web/src/services/asset-inventory/components/MetricExplorerLineChart.vue, apps/web/src/services/asset-inventory/components/MetricExplorerTreeMapChart.vue, apps/web/src/services/asset-inventory/helpers/metric-explorer-chart-data-helper.ts
=> chore: fix blinking when changing chart type

apps/web/src/schema/cost-analysis/data-source/api-verbs/list.ts, apps/web/src/schema/monitoring/data-source/model.ts, apps/web/src/services/cost-explorer/components/DataSourceManagementTable.vue, apps/web/src/services/cost-explorer/pages/admin/AdminDataSourcePage.vue, apps/web/src/services/cost-explorer/routes/admin/routes.ts, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: create table

apps/web/src/services/cost-explorer/components/DataSourceManagementTabDetail.vue, apps/web/src/services/cost-explorer/components/DataSourceManagementTabDetailBaseInformation.vue, apps/web/src/services/cost-explorer/components/DataSourceManagementTable.vue, apps/web/src/services/cost-explorer/components/DataSourceManagementTabs.vue, apps/web/src/services/cost-explorer/pages/admin/AdminDataSourcePage.vue, apps/web/src/services/cost-explorer/stores/data-sources-page-store.ts, apps/web/src/services/cost-explorer/types/data-sources-type.ts, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
Re-upload [this PR](https://github.com/cloudforet-io/console/pull/3686) due to authentication issues.
=> feat: create detail tab and use store

apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue
SSIA
[QA](https://mzdevs.atlassian.net/browse/MZ00003-399)
=> fix(metric-lsb): apply changed planning in lsb

apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue, apps/web/src/services/asset-inventory/components/MetricExplorerLSBMetric.vue, apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts
=> fix(metric-lsb-namespace): apply selected namespace scenario 

apps/web/index.html, apps/web/src/services/dashboards/components/DashboardCloneModal.vue, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> fix: fix private dashboard clone bug & add meta tag for noindex 

apps/web/src/services/asset-inventory/components/MetricExplorerChart.vue, apps/web/src/services/asset-inventory/components/MetricExplorerChartLegends.vue, apps/web/src/services/asset-inventory/components/MetricExplorerDataTable.vue, apps/web/src/services/asset-inventory/components/MetricExplorerDonutChart.vue, apps/web/src/services/asset-inventory/components/MetricExplorerFiltersPopper.vue, apps/web/src/services/asset-inventory/components/MetricExplorerGroupBy.vue, apps/web/src/services/asset-inventory/components/MetricExplorerHeader.vue, apps/web/src/services/asset-inventory/components/MetricExplorerHorizontalColumnChart.vue, apps/web/src/services/asset-inventory/components/MetricExplorerLineChart.vue, apps/web/src/services/asset-inventory/components/MetricExplorerNameFormModal.vue, apps/web/src/services/asset-inventory/components/MetricExplorerQueryFormSidebar.vue, apps/web/src/services/asset-inventory/components/MetricExplorerTreeMapChart.vue, apps/web/src/services/asset-inventory/helpers/metric-explorer-chart-data-helper.ts, apps/web/src/services/asset-inventory/pages/MetricExplorerDetailPage.vue, apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts
=> fix: fix modal visible bug after saveas metric & etc

apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue, apps/web/src/services/asset-inventory/components/MetricExplorerLSBMetric.vue, apps/web/src/services/asset-inventory/stores/asset-inventory-settings-store.ts, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json, packages/mirinae/src/data-display/popover/type.ts
=> feat(metric-lsb): create metric-select-popover 

apps/web/src/services/asset-inventory/components/CloudServiceMetricButton.vue
=> chore: show metric button only if metrics exist

apps/web/src/services/asset-inventory/pages/MetricExplorerDetailPage.vue, apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts
=> fix: fix init logic

apps/web/src/common/modules/favorites/favorite-button/FavoriteButton.vue, apps/web/src/common/modules/favorites/favorite-button/store/favorite-store.ts, apps/web/src/common/modules/navigations/gnb/GNBToolbox.vue, apps/web/src/common/modules/navigations/stores/gnb-store.ts, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-favorite/TopBarFavorite.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-favorite/modules/TopBarFavoriteContextMenu.vue, apps/web/src/lib/helper/config-data-helper.ts, apps/web/src/schema/inventory/metric-example/api-verbs/list.ts, apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue, apps/web/src/services/asset-inventory/components/MetricExplorerLSBMetric.vue, apps/web/src/services/asset-inventory/pages/MetricExplorerDetailPage.vue, apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts
=> feat(metric-example): create metric example favorite

apps/web/src/services/cost-explorer/components/DataSourceManagementTabDetailJob.vue, apps/web/src/services/cost-explorer/stores/data-sources-page-store.ts, apps/web/src/services/cost-explorer/types/data-sources-type.ts, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: apply toolbox and error modal

packages/mirinae/src/inputs/forms/json-schema-form/PJsonSchemaForm.vue, packages/mirinae/src/inputs/forms/json-schema-form/helpers/inner-schema-helper.ts, packages/mirinae/src/inputs/forms/json-schema-form/type.ts
=> fix: update appearanceType when PJsonSchema is in array type

apps/web/src/schema/cost-analysis/data-source-account/api-verbs/list.ts, apps/web/src/schema/cost-analysis/data-source-account/model.ts, apps/web/src/services/cost-explorer/components/DataSourceManagementTabDetailJob.vue, apps/web/src/services/cost-explorer/components/DataSourceManagementTabLinkedAccount.vue, apps/web/src/services/cost-explorer/components/DataSourceManagementTabs.vue, apps/web/src/services/cost-explorer/stores/data-sources-page-store.ts, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: create linked workspace table

apps/web/src/services/asset-inventory/components/ServiceAccountClusterDetail.vue
=> feat(agent-cluster-details): add new fields

apps/web/src/services/dashboards/components/DashboardManageVariableTable.vue, apps/web/src/services/dashboards/constants/dashboard-managed-variables-schema.ts, apps/web/src/services/dashboards/dashboard-template/templates/aws-cdn-and-traffic.ts, apps/web/src/services/dashboards/dashboard-template/templates/aws-monthly-cost-summary.ts, apps/web/src/services/dashboards/dashboard-template/templates/azure-monthly-cost-summary.ts, apps/web/src/services/dashboards/dashboard-template/templates/d-clo-compliance-overview.ts, apps/web/src/services/dashboards/dashboard-template/templates/google-monthly-cost-summary.ts, apps/web/src/services/dashboards/dashboard-template/templates/prowler-compliance-overview.ts, apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
=> feat: add 'project_group' variable to dashboard templates

apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue
SSIA
[QA
](https://pyengine.atlassian.net/browse/QA-1594)
=> fix(service-account): handle change-provider account type issue

apps/web/src/services/asset-inventory/components/AssetAnalysisLSB.vue, packages/language-pack/ja.json, packages/language-pack/ko.json
[QA-1598](https://pyengine.atlassian.net/browse/QA-1598)
[QA-1607](https://pyengine.atlassian.net/browse/QA-1607)
=> fix(QA): some QA

apps/web/src/services/asset-inventory/components/AssetAnalysisLSB.vue
=> chore(metric-favorite): add missed code

apps/web/src/services/alert-manager/components/EscalationPolicyForm.vue
=> chore: solve escalation policy project dropdown issue

apps/web/src/store/global-ui/global-ui-store.ts, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> fix: small issues

apps/web/src/services/asset-inventory/components/AssetAnalysisHeader.vue, apps/web/src/services/asset-inventory/components/AssetAnalysisQueryFormSidebar.vue, packages/mirinae/src/components.ts, packages/mirinae/src/inputs/forms/json-schema-form/PJsonSchemaForm.vue, packages/mirinae/src/layouts/overlay-layout/POverlayLayout.stories.mdx, packages/mirinae/src/layouts/overlay-layout/POverlayLayout.vue, packages/mirinae/src/layouts/overlay-layout/story-helper.ts
Create New Component!
https://github.com/cloudforet-io/console/assets/50662170/c39853c8-d792-408a-bfce-371e14c206e3
=> feat(mirinae): create overlay layout component & apply at console

apps/web/src/services/asset-inventory/components/AssetAnalysisLSB.vue, apps/web/src/services/asset-inventory/pages/AssetAnalysisDetailPage.vue
=> fix: solve some small QA

apps/web/src/common/modules/project/ProjectSelectDropdown.vue
=> fix: solve project dropdown visible issue

apps/web/src/services/asset-inventory/components/AssetAnalysisLSB.vue, apps/web/src/services/asset-inventory/components/AssetAnalysisLSBMetric.vue, apps/web/src/services/asset-inventory/types/asset-analysis-type.ts
=> feat(namespace-icon): apply namespace icon to asset-analysis lsb

apps/web/src/services/asset-inventory/components/AssetAnalysisLSB.vue
=> fix(asset-analysis-lsb): add missed code about namespace icon & solve vue fragment issue

apps/web/src/services/asset-inventory/components/ServiceAccountAttachedGeneralAccounts.vue, apps/web/src/services/asset-inventory/components/ServiceAccountAutoSyncDetail.vue, apps/web/src/services/asset-inventory/components/ServiceAccountAutoSyncMappingMethod.vue, apps/web/src/services/asset-inventory/pages/AssetAnalysisMainPage.vue, apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue
=> fix(service-account): fix auto sync section bug & fix QA bugs

apps/web/src/services/asset-inventory/components/ServiceAccountAddClusterModal.vue, apps/web/src/services/asset-inventory/components/ServiceAccountCluster.vue, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> fix(k8s-cluster): apply changed scenario (cluster-add-modal, cluster-reconnect)

apps/web/src/services/asset-inventory/components/AssetAnalysisLSB.vue
=> chore: edit image & image path

apps/web/src/common/modules/navigations/lsb/modules/LSBCollapsibleMenuItem.vue, apps/web/src/services/asset-inventory/components/AssetAnalysisLSB.vue, apps/web/src/services/asset-inventory/components/AssetAnalysisLSBMetric.vue
=> fix: edit usage of common icon & add slot to collapsible lsb menu

apps/web/src/common/modules/navigations/lsb/modules/LSBCollapsibleMenuItem.vue, apps/web/src/services/asset-inventory/components/AssetAnalysisLSB.vue, apps/web/src/services/asset-inventory/components/AssetAnalysisLSBMetric.vue
=> feat: merge qa

apps/web/src/services/asset-inventory/components/AssetAnalysisHeader.vue, apps/web/src/services/asset-inventory/components/AssetAnalysisQueryFormSidebar.vue
=> fix: show query options for managed metric

apps/web/src/services/asset-inventory/components/AssetAnalysisLSBMetric.vue, apps/web/src/services/asset-inventory/components/ServiceAccountCluster.vue
=> chore: add newline code to agent delete script

apps/web/src/router/helpers/route-helper.ts, apps/web/src/services/auth/authenticator/local/template/ID_PW.vue, apps/web/src/services/auth/pages/MultiFactorAuthPage.vue, apps/web/src/services/auth/pages/PasswordPage.vue
=> fix(reset-password-issue): solve reset-password redirect issue

apps/web/src/services/asset-inventory/pages/AssetAnalysisMainPage.vue
=> fix: apply common namespace icon to asset-analysis-main-page

apps/web/src/services/asset-inventory/components/AssetAnalysisDataTable.vue, apps/web/src/services/asset-inventory/helpers/asset-analysis-chart-data-helper.ts
=> feat: set byte formatter to 'bytes' unit

apps/web/src/services/asset-inventory/components/AssetAnalysisDataTable.vue
=> fix: fix byteFormatter in asset analysis

apps/web/src/services/project/components/ProjectFormModal.vue
=> fix: when confirm is active, disable input text validation checks

apps/web/src/services/cost-explorer/components/DataSourceManagementTabDetailJob.vue, apps/web/src/services/cost-explorer/components/DataSourceManagementTabLinkedAccount.vue, apps/web/src/services/cost-explorer/components/DataSourceManagementTable.vue, apps/web/src/services/cost-explorer/components/DataSourceManagementTabs.vue, apps/web/src/services/cost-explorer/pages/admin/AdminDataSourcePage.vue, apps/web/src/services/cost-explorer/stores/data-sources-page-store.ts, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: apply workspace table cols

apps/web/src/services/cost-explorer/components/DataSourceManagementTabDetailBaseInformation.vue, apps/web/src/services/cost-explorer/components/DataSourceManagementTabDetailJob.vue, apps/web/src/services/cost-explorer/components/DataSourceManagementTabLinkedAccount.vue, apps/web/src/services/cost-explorer/components/DataSourceManagementTabLinkedAccountTable.vue, apps/web/src/services/cost-explorer/components/DataSourceManagementTable.vue, apps/web/src/services/cost-explorer/pages/admin/AdminDataSourcePage.vue, apps/web/src/services/cost-explorer/stores/data-sources-page-store.ts
=> refactor: component separation

apps/web/src/schema/cost-analysis/data-source-account/api-verbs/reset.ts, apps/web/src/schema/cost-analysis/data-source-account/api-verbs/update.ts, apps/web/src/services/cost-explorer/components/DataSourceManagementTabDetailJob.vue, apps/web/src/services/cost-explorer/components/DataSourceManagementTabLinkedAccountTable.vue
=> fix: fixed bugs about table

apps/web/src/common/modules/widgets/types/widget-display-type.ts, apps/web/src/schema/dashboard/_types/dashboard-type.ts, apps/web/src/schema/dashboard/_types/widget-type.ts
=> feat(widget-props): create NewWidgetProps and other changed type

apps/web/src/services/cost-explorer/components/DataSourceManagementModal.vue, apps/web/src/services/cost-explorer/components/DataSourceManagementTabLinkedAccount.vue, apps/web/src/services/cost-explorer/components/DataSourceManagementTabLinkedAccountTable.vue, apps/web/src/services/cost-explorer/stores/data-sources-page-store.ts, apps/web/src/services/cost-explorer/types/data-sources-type.ts, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
SSIA
- Reset Modal
- Update Modal
=> feat: apply modal

apps/web/src/common/modules/widgets/_base-widgets/vertical-bar-chart/VerticalBarChart.vue, apps/web/src/common/modules/widgets/_components/WidgetFrame.vue, apps/web/src/common/modules/widgets/types/widget-display-type.ts, apps/web/src/services/dashboards/pages/DashboardPlaygroundPage.vue
=> feat: update `NewWidgetProps` and `WidgetFrameProps`

apps/web/src/common/modules/widgets/_base-widgets/vertical-bar-chart/VerticalBarChart.vue, apps/web/src/common/modules/widgets/_base-widgets/vertical-bar-chart/widget-config.ts, apps/web/src/common/modules/widgets/_components/WidgetFrame.vue, apps/web/src/common/modules/widgets/_composables/use-widget/use-widget-frame.ts, apps/web/src/common/modules/widgets/_constants/widget-config-list-constant.ts, apps/web/src/common/modules/widgets/types/widget-config-type.ts, apps/web/src/common/modules/widgets/types/widget-frame-type.ts, apps/web/src/common/modules/widgets/types/widget-list-type.ts, apps/web/src/schema/dashboard/_types/widget-type.ts, apps/web/src/services/dashboards/pages/DashboardPlaygroundPage.vue
=> feat: update `use-widget-frame` hook

apps/web/src/services/cost-explorer/components/DataSourceManagementTabLinkedAccountTable.vue, apps/web/src/services/cost-explorer/components/DataSourceManagementTable.vue, apps/web/src/services/cost-explorer/pages/admin/AdminDataSourcePage.vue, apps/web/src/services/cost-explorer/stores/data-sources-page-store.ts
=> feat: apply datasource list filter

packages/mirinae/src/layouts/sidebar/PSidebar.vue, packages/mirinae/src/layouts/sidebar/story-helper.ts
=> chore(mirinae): delete unused props from PSidebar

apps/web/src/services/cost-explorer/stores/data-sources-page-store.ts
=> chore: update default value

apps/web/src/common/modules/widgets/_base-widgets/vertical-bar-chart/VerticalBarChart.vue, apps/web/src/common/modules/widgets/_composables/use-widget/use-widget-frame.ts, apps/web/src/common/modules/widgets/_composables/use-widget/use-widget.ts, apps/web/src/common/modules/widgets/types/widget-frame-type.ts, apps/web/src/services/dashboards/pages/DashboardPlaygroundPage.vue
=> feat: delete `widgetLink`, `noData` type from `WidgetFrameProps`

apps/web/src/services/auth/pages/PasswordPage.vue
=> fix(reset-password): apply missed scenario

apps/web/src/common/modules/widgets/_base-widgets/stacked-column-chart/StackedColumnChart.vue, apps/web/src/common/modules/widgets/_base-widgets/stacked-column-chart/widget-config.ts, apps/web/src/common/modules/widgets/_components/WidgetFrame.vue, apps/web/src/common/modules/widgets/_constants/widget-config-list-constant.ts, apps/web/src/services/dashboards/pages/DashboardPlaygroundPage.vue
=> chore: change widget name

apps/web/src/common/modules/widgets/_base-widgets/stacked-column-chart/StackedColumnChart.vue, apps/web/src/common/modules/widgets/_composables/use-widget/use-widget-chart.ts, apps/web/src/common/modules/widgets/_composables/use-widget/use-widget-frame.ts
=> feat: update `use-widget-frame`

apps/web/src/schema/inventory/metric/model.ts, apps/web/src/services/asset-inventory/components/AssetAnalysisDataTable.vue, apps/web/src/services/asset-inventory/stores/asset-analysis-page-store.ts
=> chore: change from `label_keys` to `labels_info`

apps/web/src/common/modules/widgets/_base-widgets/stacked-column-chart/StackedColumnChart.vue, apps/web/src/common/modules/widgets/_composables/use-widget/use-widget-data-state.ts, apps/web/src/schema/dashboard/_types/dashboard-type.ts
=> feat: create `useWidgetDataState`

apps/web/src/common/modules/navigations/gnb/GNBToolbox.vue, apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-favorite/modules/TopBarFavoriteContextMenu.vue
=> fix: fixed api bug

apps/web/src/services/asset-inventory/pages/CloudServicePage.vue, apps/web/src/services/home-dashboard/constants/home-dashboard-constant.ts
=> fix: delete unused label in all summary widget

apps/web/src/common/modules/navigations/top-bar/modules/top-bar-header/TopBarWorkspaces.vue
=> chore: add catch to workspace toggle

apps/web/src/common/modules/widgets/_constants/widget-config-list-constant.ts
=> chore: apply new widget key

apps/web/src/common/modules/widgets/_base-widgets/stacked-column-chart/widget-config.ts, apps/web/src/common/modules/widgets/_composables/use-widget/use-widget-chart.ts, apps/web/src/common/modules/widgets/_composables/use-widget/use-widget-data-state.ts, apps/web/src/common/modules/widgets/_composables/use-widget/use-widget-frame.ts, apps/web/src/common/modules/widgets/_constants/widget-components-constant.ts, apps/web/src/common/modules/widgets/_helpers/widget-component-helper.ts, apps/web/src/common/modules/widgets/types/compliance-type.ts, apps/web/src/common/modules/widgets/types/widget-data-type.ts, apps/web/src/common/modules/widgets/types/widget-display-type.ts, apps/web/src/common/modules/widgets/types/widget-frame-type.ts, apps/web/src/services/dashboards/pages/DashboardPlaygroundPage.vue
=> feat: change from `dateRange` to `baseOnDate`

apps/web/src/common/modules/navigations/top-bar/modules/TopBarSuggestionList.vue
=> chore: apply icon color

apps/web/src/common/modules/widgets/_base-widgets/number-card/widget-config.ts, apps/web/src/common/modules/widgets/_base-widgets/stacked-column-chart/widget-config.ts, apps/web/src/common/modules/widgets/_constants/widget-config-list-constant.ts, apps/web/src/common/modules/widgets/types/widget-config-type.ts, apps/web/src/common/modules/widgets/types/widget-display-type.ts
=> feat: add number card config

apps/web/src/common/modules/widgets/_base-widgets/number-card/widget-config.ts, apps/web/src/common/modules/widgets/_composables/use-widget/use-widget-chart-state.ts, apps/web/src/common/modules/widgets/_composables/use-widget/use-widget-chart.ts, apps/web/src/common/modules/widgets/_composables/use-widget/use-widget-data-state.ts, apps/web/src/common/modules/widgets/types/widget-config-type.ts
=> feat: add `granularity_field` to widget config

apps/web/src/services/asset-inventory/components/AssetAnalysisDataTable.vue, apps/web/src/services/asset-inventory/components/AssetAnalysisGroupBy.vue, apps/web/src/services/asset-inventory/helpers/asset-analysis-chart-data-helper.ts
=> feat: set 0 to undefined data in asset analysis

apps/web/src/store/reference/all-reference-store.ts
=> feat: add snake_case for allReferenceStore

apps/web/src/common/modules/widgets/_composables/use-widget/use-widget-data.ts, apps/web/src/common/modules/widgets/types/widget-display-type.ts, apps/web/src/services/dashboards/pages/DashboardPlaygroundPage.vue
=> fix: refactor `use-widget-data` & edit widget props

packages/language-pack/ko.json
=> fix: fix translation

apps/web/src/schema/cost-analysis/data-source-account/api-verbs/analyze.ts, apps/web/src/schema/cost-analysis/data-source-account/model.ts, apps/web/src/services/cost-explorer/components/DataSourceManagementTabLinkedAccountTable.vue, apps/web/src/services/cost-explorer/components/DataSourceManagementTable.vue, apps/web/src/services/cost-explorer/composables/data-source-converter.ts, apps/web/src/services/cost-explorer/composables/data-source-handler.ts, apps/web/src/services/cost-explorer/stores/data-sources-page-store.ts, apps/web/src/services/cost-explorer/types/data-sources-type.ts
=> feat: apply data source account analyze for linked account

apps/web/src/services/cost-explorer/components/DataSourceManagementTabLinkedAccount.vue, apps/web/src/services/cost-explorer/components/DataSourceManagementTabLinkedAccountTable.vue, apps/web/src/services/cost-explorer/components/DataSourceManagementTable.vue, apps/web/src/services/cost-explorer/components/DataSourceManagementTabs.vue, apps/web/src/services/cost-explorer/pages/admin/AdminDataSourcePage.vue, apps/web/src/services/cost-explorer/stores/data-sources-page-store.ts
=> feat: apply fetchDatasourceList after update linked account

apps/web/src/services/cost-explorer/components/DataSourceManagementModal.vue, apps/web/src/services/cost-explorer/components/DataSourceManagementTable.vue
=> chore: apply minor qa

apps/web/src/store/modules/user/actions.ts
=> fix: solve issue of removal user name

apps/web/src/services/asset-inventory/components/AssetAnalysisChart.vue
=> feat: group pie chart values under 2% into 'Others'

apps/web/src/services/cost-explorer/components/DataSourceManagementModal.vue, apps/web/src/services/cost-explorer/components/DataSourceManagementTabLinkedAccount.vue, apps/web/src/services/cost-explorer/stores/data-sources-page-store.ts
=> refactor: apply loading toast message

packages/language-pack/ja.json, packages/language-pack/ko.json
=> chore: update translations

apps/web/src/services/cost-explorer/components/CostReportOverviewCostTrendChart.vue
=> feat(cost-report): set 'Others' under 2%

apps/web/src/services/cost-explorer/components/CostReportOverviewCostTrendChart.vue
=> chore: delete console.log

apps/web/src/services/asset-inventory/components/AssetAnalysisLSB.vue, apps/web/src/services/asset-inventory/components/AssetAnalysisNameFormModal.vue
=> fix: exclude not common metrics & apply manual sync to metric-example

apps/web/src/common/modules/navigations/gnb/GNBToolbox.vue, apps/web/src/services/asset-inventory/components/CloudServiceLSB.vue
=> fix: fixed favorite bug

apps/web/src/common/composables/amcharts5/index.ts, apps/web/src/common/modules/widgets/_base-widgets/donut-chart/DonutChart.vue
I think it would be good to have a structured meeting in accordance with the changed chart rules.
=> feat: add new piechart

apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue, apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep1.vue, apps/web/src/services/dashboards/pages/DashboardPlaygroundPage.vue, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: add WidgetFormOverlay

apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
=> chore: create widget-generate-store shell

apps/web/src/services/cost-explorer/components/DataSourceManagementTabLinkedAccount.vue, apps/web/src/services/cost-explorer/components/DataSourceManagementTabLinkedAccountTable.vue
=> fix: fixed sorting at table

apps/web/src/services/asset-inventory/components/AssetAnalysisDataTable.vue, apps/web/src/services/asset-inventory/pages/CloudServiceDetailPage.vue
=> fix: fix default filter format

apps/web/src/common/modules/widgets/_components/WidgetFormCostDataSourcePopper.vue, apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue, apps/web/src/common/modules/widgets/_components/WidgetFrame.vue, apps/web/src/common/modules/widgets/_composables/use-widget/use-widget-chart-state.ts, apps/web/src/lib/variable-models/_base/resource-variable-model.ts, apps/web/src/lib/variable-models/managed-model/resource-model/cost-data-source-variable-model.ts, apps/web/src/store/reference/cost-data-source-reference-store.ts, packages/mirinae/src/data-display/popover/PPopover.stories.mdx, packages/mirinae/src/data-display/popover/PPopover.vue, packages/mirinae/src/data-display/popover/story-helper.ts
=> feat: add cost data source popper

packages/mirinae/src/feedbacks/loading/lazy-img/PLazyImg.vue
=> chore: apply height auto when the image is rectangle

packages/mirinae/src/data-display/popover/PPopover.stories.mdx, packages/mirinae/src/data-display/popover/PPopover.vue, packages/mirinae/src/data-display/popover/story-helper.ts
- hide arrow (new)
- hide padding (add prop at storybook)
- hide close button (add prop at storybook)
- esc action (new)
=> feat: update popover spec

apps/web/src/common/modules/widgets/_components/WidgetFormDataSourceCard.vue
=> feat(data-source-card): create data-source card markup

apps/web/src/services/cost-explorer/components/DataSourceManagementTabLinkedAccount.vue, apps/web/src/services/cost-explorer/components/DataSourceManagementTabLinkedAccountTable.vue
=> fix: fixed filter

apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep1.vue
=> feat(chart-type): create chart-type select markup

apps/web/src/common/modules/widgets/_components/WidgetFormAssetSecurityDataSourcePopper.vue, apps/web/src/common/modules/widgets/_components/WidgetFormCostDataSourcePopper.vue, apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue, apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json, packages/mirinae/src/layouts/overlay-layout/POverlayLayout.vue
=> feat: add asset/security data source popper

apps/web/src/services/cost-explorer/components/DataSourceManagementTabLinkedAccount.vue
=> chore: add filter

apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue, apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep1.vue, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> chore: add empty box

apps/web/src/common/modules/widgets/_components/WidgetFormDataSourceAddButton.vue, apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue, apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue, apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: add step2

apps/web/src/common/modules/widgets/_components/WidgetFormDataSourceCard.vue
=> chore: edit selected mark

apps/web/src/services/cost-explorer/components/DataSourceManagementTabLinkedAccountTable.vue, apps/web/src/services/cost-explorer/composables/data-source-handler.ts
=> feat: apply search workspace

apps/web/src/schema/identity/domain/api-verbs/get-auth-info.ts, apps/web/src/services/auth/authenticator/external/GOOGLE_OAUTH2/authenticator/google-auth.ts, apps/web/src/services/auth/authenticator/external/GOOGLE_OAUTH2/template/GOOGLE_OAUTH2.vue, apps/web/src/services/auth/authenticator/external/SAML/authenticator/saml-auth.ts, apps/web/src/services/auth/authenticator/external/SAML/template/SAML.vue, apps/web/src/services/auth/authenticator/index.ts, apps/web/src/services/auth/authenticator/loader.ts, apps/web/src/services/auth/pages/SamlRedirectPage.vue, apps/web/src/services/auth/pages/SignInPage.vue, apps/web/src/services/auth/routes/route-constant.ts, apps/web/src/services/auth/routes/routes.ts, apps/web/src/store/modules/domain/actions.ts, apps/web/src/store/modules/domain/type.ts, apps/web/src/store/modules/user/actions.ts, apps/web/src/store/modules/user/type.ts
This work was done using mock data.
=> feat: add saml login flow

apps/web/src/services/cost-explorer/components/DataSourceManagementTabLinkedAccountTable.vue, apps/web/src/services/cost-explorer/composables/data-source-handler.ts
=> feat: apply table filter(search, pagination)

apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue, apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue, apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
=> feat: add `overlayStep` to page store

apps/web/src/services/cost-explorer/components/DataSourceManagementTabLinkedAccount.vue, apps/web/src/services/cost-explorer/components/DataSourceManagementTabLinkedAccountTable.vue, apps/web/src/services/cost-explorer/stores/data-sources-page-store.ts
=> feat: apply qa filter issue

apps/web/src/services/auth/components/SignInLeftContainer.vue, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: update version badge

apps/web/src/common/modules/widgets/_base-widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue, apps/web/src/common/modules/widgets/_base-widgets/stacked-horizontal-bar-chart/widget-config.ts, apps/web/src/common/modules/widgets/_base-widgets/treemap/Treemap.vue, apps/web/src/common/modules/widgets/_base-widgets/treemap/widget-config.ts
=> feat: add StackedHorizontalBarChart & treemap chart

apps/web/src/services/auth/authenticator/external/GOOGLE_OAUTH2/template/GOOGLE_OAUTH2.vue, apps/web/src/services/auth/authenticator/external/SAML/template/SAML.vue, apps/web/src/services/auth/authenticator/local/template/ID_PW.vue, apps/web/src/services/auth/pages/SignInPage.vue, apps/web/src/store/modules/domain/config.ts, apps/web/src/store/modules/domain/getters.ts, packages/language-pack/en.json
=> fix: fix minor style issue

apps/web/src/common/modules/widgets/_base-widgets/gauge/Gauge.vue, apps/web/src/common/modules/widgets/_base-widgets/heatmap/Heatmap.vue, apps/web/src/common/modules/widgets/_base-widgets/stacked-area-chart/StackedAreaChart.vue
=> feat: add Gauge chart, Heatmap Chart

apps/web/src/common/modules/widgets/types/model.ts, apps/web/src/schema/dashboard/private-data-table/api-verbs/create.ts, apps/web/src/schema/dashboard/private-data-table/api-verbs/load.ts, apps/web/src/schema/dashboard/private-data-table/api-verbs/update.ts, apps/web/src/schema/dashboard/private-widget/api-verbs/load.ts, apps/web/src/schema/dashboard/public-data-table/api-verbs/create.ts, apps/web/src/schema/dashboard/public-data-table/api-verbs/load.ts, apps/web/src/schema/dashboard/public-data-table/api-verbs/update.ts, apps/web/src/schema/dashboard/public-folder/model.ts, apps/web/src/schema/dashboard/public-widget/api-verbs/load.ts
=> feat: apply new widget/data-table model

apps/web/src/services/cost-explorer/components/DataSourceManagementTabLinkedAccount.vue, apps/web/src/services/cost-explorer/components/DataSourceManagementTabLinkedAccountTable.vue
=> chore: changed minor issue

apps/web/src/common/modules/widgets/_base-widgets/pie-chart/PieChart.vue, apps/web/src/services/dashboards/pages/DashboardPlaygroundPage.vue
=> feat: add pieChart as Echart

apps/web/src/common/modules/widgets/_constants/widget-components-constant.ts, apps/web/src/services/dashboards/pages/DashboardPlaygroundPage.vue
=> chore: edit widget playground

apps/web/src/common/modules/navigations/top-bar/modules/top-bar-header/WorkspaceLogoIcon.vue
=> fix: fix Workspace Logo Character bug

apps/web/src/common/modules/widgets/_base-widgets/clustered-column-chart/widget-config.ts, apps/web/src/common/modules/widgets/types/widget-config-type.ts
=> feat: update new widget config

apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue, apps/web/src/common/modules/widgets/_constants/widget-components-constant.ts, apps/web/src/common/modules/widgets/_constants/widget-config-list-constant.ts, apps/web/src/common/modules/widgets/_helpers/widget-config-helper.ts, apps/web/src/common/modules/widgets/types/widget-list-type.ts, apps/web/src/services/dashboards/pages/DashboardPlaygroundPage.vue
=> feat: set chart types in step2

apps/web/src/services/iam/components/UserManagementAddModal.vue, apps/web/src/services/iam/components/UserManagementAddUser.vue, apps/web/src/services/iam/components/UserManagementFormMultiFactorAuth.vue, apps/web/src/services/iam/components/UserManagementHeader.vue, apps/web/src/services/landing/components/DomainLandingStartBanner.vue, apps/web/src/services/landing/components/LandingHeader.vue, apps/web/src/services/landing/pages/DomainLandingPage.vue, apps/web/src/services/preference/components/WorkspacesCreateModal.vue, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: apply function at start banner

apps/web/src/schema/inventory/metric/api-verbs/create.ts, apps/web/src/schema/inventory/namespace/api-verbs/list.ts, apps/web/src/schema/inventory/namespace/model.ts, apps/web/src/schema/inventory/namespace/type.ts, apps/web/src/services/asset-inventory/components/AssetAnalysisHeader.vue, apps/web/src/services/asset-inventory/components/AssetAnalysisLSB.vue, apps/web/src/services/asset-inventory/components/AssetAnalysisLSBMetric.vue, apps/web/src/services/asset-inventory/components/AssetAnalysisQueryFormSidebar.vue, apps/web/src/services/asset-inventory/types/asset-analysis-type.ts, apps/web/src/store/reference/namespace-reference-store.ts
=> feat(asset-analysis): feedback

apps/web/src/schema/inventory/metric/api-verbs/run.ts, apps/web/src/services/asset-inventory/components/AssetAnalysisDataTable.vue, apps/web/src/services/asset-inventory/components/AssetAnalysisQuerySection.vue, apps/web/src/services/asset-inventory/helpers/asset-analysis-chart-data-helper.ts, apps/web/src/services/asset-inventory/pages/AssetAnalysisMainPage.vue, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: enable row click even when total

apps/web/src/services/asset-inventory/components/AssetAnalysisLSB.vue, apps/web/src/services/asset-inventory/components/AssetAnalysisQuerySection.vue, packages/mirinae/src/inputs/buttons/icon-button/PIconButton.vue
=> fix: set resourceType when set selectedNamespace

apps/web/src/common/modules/widgets/_base-widgets/clustered-column-chart/widget-config.ts, apps/web/src/common/modules/widgets/_base-widgets/gauge/widget-config.ts, apps/web/src/common/modules/widgets/_base-widgets/geo-map/widget-config.ts, apps/web/src/common/modules/widgets/_base-widgets/heatmap/widget-config.ts, apps/web/src/common/modules/widgets/_base-widgets/line-chart/widget-config.ts, apps/web/src/common/modules/widgets/_base-widgets/number-card/widget-config.ts, apps/web/src/common/modules/widgets/_base-widgets/pie-chart/widget-config.ts, apps/web/src/common/modules/widgets/_base-widgets/progress-card/widget-config.ts, apps/web/src/common/modules/widgets/_base-widgets/stacked-area-chart/widget-config.ts, apps/web/src/common/modules/widgets/_base-widgets/stacked-column-chart/widget-config.ts, apps/web/src/common/modules/widgets/_base-widgets/stacked-horizontal-bar-chart/widget-config.ts, apps/web/src/common/modules/widgets/_base-widgets/table/widget-config.ts, apps/web/src/common/modules/widgets/_base-widgets/treemap/widget-config.ts, apps/web/src/common/modules/widgets/_helpers/widget-component-helper.ts, apps/web/src/common/modules/widgets/_helpers/widget-config-helper.ts, apps/web/src/common/modules/widgets/types/widget-config-type.ts
=> feat: update widget config

apps/web/src/common/modules/navigations/lsb/modules/LSBCollapsibleMenuItem.vue, apps/web/src/services/asset-inventory/components/AssetAnalysisHeader.vue, apps/web/src/services/asset-inventory/components/AssetAnalysisLSB.vue, apps/web/src/services/asset-inventory/components/AssetAnalysisQueryFormSidebar.vue
=> fix(asset-analysis): feedback

apps/web/src/common/modules/widgets/types/widget-config-type.ts
=> feat: update widget field component type

apps/web/src/services/cost-explorer/components/DataSourceManagementTabLinkedAccount.vue
=> fix: fixed filter bug

apps/web/src/services/asset-inventory/components/AssetAnalysisDonutChart.vue, apps/web/src/services/asset-inventory/components/AssetAnalysisHorizontalColumnChart.vue, apps/web/src/services/asset-inventory/components/AssetAnalysisLineChart.vue, apps/web/src/services/asset-inventory/components/AssetAnalysisTreeMapChart.vue, apps/web/src/services/asset-inventory/helpers/asset-analysis-chart-data-helper.ts
=> chore: fix asset analysis chart data formatter

apps/web/src/common/modules/widgets/_constants/widget-field-components-constant.ts, apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldBasisField.vue, apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldCategoryBy.vue, apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldDataField.vue, apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldGroupBy.vue, apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldLineBy.vue, apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldStackBy.vue, apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTotalField.vue, apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldXAxis.vue, apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/widget-config.ts, apps/web/src/common/modules/widgets/_widgets/gauge/widget-config.ts, apps/web/src/common/modules/widgets/_widgets/geo-map/widget-config.ts, apps/web/src/common/modules/widgets/_widgets/heatmap/widget-config.ts, apps/web/src/common/modules/widgets/_widgets/line-chart/widget-config.ts, apps/web/src/common/modules/widgets/_widgets/number-card/widget-config.ts, apps/web/src/common/modules/widgets/_widgets/pie-chart/widget-config.ts, apps/web/src/common/modules/widgets/_widgets/progress-card/widget-config.ts, apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/widget-config.ts, apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/widget-config.ts, apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/widget-config.ts, apps/web/src/common/modules/widgets/_widgets/table/widget-config.ts, apps/web/src/common/modules/widgets/_widgets/treemap/widget-config.ts, apps/web/src/common/modules/widgets/types/widget-config-type.ts, apps/web/src/services/dashboards/pages/DashboardPlaygroundPage.vue
=> feat: add widget field components

apps/web/src/common/modules/navigations/gnb/GNBNavigationRail.vue
=> feat: fixed minimize button at navigation rail

apps/web/src/services/cost-explorer/components/CostReportMonthlyTotalAmountSummaryCard.vue, apps/web/src/services/cost-explorer/components/CostReportOverviewCostTrendCard.vue, apps/web/src/services/cost-explorer/constants/cost-explorer-constant.ts, apps/web/src/services/preference/components/WorkspaceManagementTable.vue
=> feat: changed groupBy field to workspace_name

apps/web/src/common/modules/widgets/_constants/widget-field-components-constant.ts, apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldMax.vue, apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldMin.vue, apps/web/src/common/modules/widgets/_widgets/gauge/widget-config.ts, apps/web/src/common/modules/widgets/types/widget-config-type.ts
=> feat: add min max widget field components

apps/web/src/common/components/inputs/ColorInput.vue, apps/web/src/common/modules/widgets/_constants/widget-components-constant.ts, apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldFormatRules.vue, apps/web/src/common/modules/widgets/_widgets/gauge/widget-config.ts, apps/web/src/common/modules/widgets/_widgets/heatmap/widget-config.ts, apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue, apps/web/src/common/modules/widgets/_widgets/progress-card/ProgressCard.vue, apps/web/src/common/modules/widgets/_widgets/progress-card/widget-config.ts, apps/web/src/common/modules/widgets/_widgets/table/Table.vue
=> feat: create ColorInput console component

apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue, apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: update step2

apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue, apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue, apps/web/src/common/modules/widgets/_composables/use-widget/use-widget-frame.ts, apps/web/src/common/modules/widgets/_store/widget-generate-store.ts, apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue, apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue, apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue, apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue, apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue, apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue, apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue, apps/web/src/common/modules/widgets/_widgets/progress-card/ProgressCard.vue, apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue, apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue, apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue, apps/web/src/common/modules/widgets/_widgets/table/Table.vue, apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue, apps/web/src/common/modules/widgets/types/widget-display-type.ts, apps/web/src/common/modules/widgets/types/widget-frame-type.ts
=> feat: generate dynamic widget component

apps/web/src/common/modules/widgets/_components/WidgetFormDataSourceCard.vue, apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue, apps/web/src/common/modules/widgets/_constants/widget-constant.ts, apps/web/src/common/modules/widgets/_store/widget-generate-store.ts, apps/web/src/common/modules/widgets/types/widget-model.ts
=> feat(widget-form-data-card): create data-source/group-by field

apps/web/src/common/modules/widgets/_components/WidgetFormDataSourceCard.vue, apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
=> fix(widget-generate-store): replace `setSelectedDataTable` mutation to `setSelectedDataTableId` & solve conflict

apps/web/src/common/components/inputs/ColorInput.vue, apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue, apps/web/src/common/modules/widgets/_constants/widget-field-components-constant.ts, apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldFormatRules.vue, apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldProgressBar.vue, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: add ProgressBar field component

apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
=> chore: small issue

apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-profile/TopBarProfile.vue, packages/language-pack/en.json, packages/language-pack/ja.json, packages/language-pack/ko.json
=> feat: add console home button at top bar profile

apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue, apps/web/src/services/dashboards/components/DashboardCustomize.vue, apps/web/src/services/dashboards/components/DashboardCustomizeSidebar.vue, apps/web/src/services/dashboards/components/DashboardRefreshDropdown.vue, apps/web/src/services/dashboards/pages/DashboardDetailPage.vue
=> chore: fix minor

apps/web/src/common/modules/widgets/_components/WidgetFormDataSourceCard.vue, apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep1.vue, apps/web/src/common/modules/widgets/_store/widget-generate-store.ts, apps/web/src/store/reference/metric-reference-store.ts
=> feat: create data table base markup & small fix
