cloudforet-io/console

- apps/web/src/schema/dashboard/private-dashboard/api-verbs/create.ts
- apps/web/src/schema/dashboard/private-dashboard/api-verbs/update.ts
- apps/web/src/schema/dashboard/public-dashboard/api-verbs/update.ts
- apps/web/src/services/dashboards/components/DashboardDetailHeader.vue
- apps/web/src/services/dashboards/components/DashboardMainBoardList.vue
- apps/web/src/services/dashboards/components/DashboardManageVariableOverlay.vue
- apps/web/src/services/dashboards/components/DashboardVariables.vue
- apps/web/src/services/dashboards/components/DashboardVariablesMoreButton.vue
- apps/web/src/services/dashboards/components/DashboardWidgetContainer.vue
- apps/web/src/services/dashboards/pages/DashboardCreatePage.vue
- apps/web/src/services/dashboards/pages/DashboardCustomizePage.vue
- apps/web/src/services/dashboards/pages/DashboardDetailPage.vue
- apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
- apps/web/src/services/dashboards/widgets/_types/widget-type.ts
In deprecated dashboards...
- NO customize/clone button
- NO dashboard variable manage button
- NO dashboard variable save button
> feat: implement deprecated case for old dashboard

- apps/web/src/common/modules/widgets/_constants/widget-field-components-constant.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldSubTotal.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTotal.vue
- apps/web/src/common/modules/widgets/_widgets/table/widget-config.ts
- apps/web/src/common/modules/widgets/types/widget-config-type.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: add total, subTotal widget fields

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldBasisField.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldCategoryBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldDataField.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldFormatRules.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldGroupBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldLineBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldMax.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldMin.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldProgressBar.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldStackBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTotalField.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldXAxis.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldYAxis.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/widget-config.ts
- apps/web/src/common/modules/widgets/types/widget-config-type.ts
- packages/mirinae/src/inputs/forms/field-group/PFieldGroup.stories.mdx
- packages/mirinae/src/inputs/forms/field-group/PFieldGroup.vue
- packages/mirinae/src/layouts/overlay-layout/POverlayLayout.vue
> feat: add 'dropdown' field to formatRules & update markup

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldBasisField.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldCategoryBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldDataField.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldFormatRules.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldGroupBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldIcon.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldLegend.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldLineBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldMax.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldMin.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldProgressBar.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldStackBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldSubTotal.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTotal.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTotalField.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldXAxis.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldYAxis.vue
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
> feat: update markup and add `fieldValueMap`, `fieldValidationMap`

- apps/web/src/common/modules/widgets/_components/WidgetFormDataSourceCard.vue
> feat: add time-diff form & apply init form

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/common/modules/widgets/_composables/use-widget/use-widget-frame.ts
- apps/web/src/common/modules/widgets/types/widget-display-type.ts
- apps/web/src/common/modules/widgets/types/widget-frame-type.ts
- apps/web/src/services/dashboards/pages/DashboardPlaygroundPage.vue
for `customize` mode
for `view` mode
> feat: add `mode` props to WidgetFrame and Widget

- apps/web/src/services/preference/PreferenceContainer.vue
- apps/web/src/services/preference/PreferenceLSB.vue
- apps/web/src/services/preference/components/BookmarkLSB.vue
- apps/web/src/services/preference/components/BookmarkTree.vue
- apps/web/src/services/preference/routes/admin/routes.ts
- apps/web/src/services/preference/store/bookmark-page-store.ts
> feat: create bookmark lsb

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: add expand button to widget frame

- apps/web/src/common/modules/widgets/_constants/widget-field-components-constant.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldGroupBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldXAxis.vue
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/heatmap/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/line-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/table/widget-config.ts
- apps/web/src/common/modules/widgets/types/widget-config-type.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> refactor: edit widget field name, type name

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFilters.vue
- apps/web/src/store/reference/metric-reference-store.ts
> feat: apply data-table asset filter

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCard.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFilters.vue
> feat: synchronize data-table field

- apps/web/src/services/asset-inventory/components/AssetAnalysisLineChart.vue
- apps/web/src/services/asset-inventory/components/AssetAnalysisQueryFormSidebar.vue
> chore: update minor style issue

- apps/web/src/lib/site-initializer/sso.ts
> fix: rollback reset-password(`sso_access_token`) scenario

- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldBasisField.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldCategoryBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldDataField.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldFormatRules.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldGroupBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldLineBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldProgressBar.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldStackBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTotalField.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldXAxis.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldYAxis.vue
- apps/web/src/common/modules/widgets/types/widget-config-type.ts
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
- apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
> feat: set value, validation emits to widget fields

- apps/web/src/common/modules/widgets/_components/WidgetFormAssetSecurityDataSourcePopper.vue
> refactor: update code according to the changed namespace model

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCard.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardSourceItemDropdown.vue
SSIA
https://github.com/cloudforet-io/console/assets/83635051/18e68ee1-d8ac-4bb5-b3ba-bf33cabde2c3
> fix: create source item dropdown and apply change source scenario

- apps/web/src/schema/dashboard/_types/dashboard-type.ts
- apps/web/src/schema/dashboard/private-dashboard/api-verbs/create.ts
- apps/web/src/schema/dashboard/private-dashboard/api-verbs/update.ts
- apps/web/src/schema/dashboard/public-dashboard/api-verbs/create.ts
- apps/web/src/schema/dashboard/public-dashboard/api-verbs/update.ts
- apps/web/src/services/dashboards/components/DashboardWidgetAddModalDefaultTab.vue
- apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
- apps/web/src/services/dashboards/stores/widget-form-store.ts
> refactor: update code according to changed `layouts` spec

- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldComparison.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldIcon.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldMax.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldMin.vue
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
- apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: add validation to widget fields

- apps/web/src/services/preference/pages/admin/AdminBookmarkPage.vue
> chore: temp code for vercel build

- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldCategoryBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldFormatRules.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldGroupBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldLineBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldStackBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldXAxis.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldYAxis.vue
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/gauge/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/heatmap/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/line-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/pie-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/table/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/treemap/widget-config.ts
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
- apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
> feat: set `default` and `max` to widget fields

- apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep1.vue
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
- apps/web/src/common/modules/widgets/types/widget-model.ts
> feat(data-table): apply real data-table `add/list` API

- apps/web/src/schema/identity/domain/api-verbs/get-auth-info.ts
- apps/web/src/store/modules/domain/getters.ts
> fix(saml): add defense code

- apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCard.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
- apps/web/src/common/modules/widgets/types/widget-model.ts
- apps/web/src/schema/dashboard/public-data-table/api-verbs/delete.ts
> feat: apply real data-table API (add/update/delete)

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
- apps/web/src/common/modules/widgets/_composables/use-widget-init-and-refresh.ts
- apps/web/src/common/modules/widgets/_constants/widget-field-components-constant.ts
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldGranularity.vue
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/gauge/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/geo-map/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/heatmap/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/line-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/number-card/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/pie-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/progress-card/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/table/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/treemap/widget-config.ts
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
- apps/web/src/common/modules/widgets/types/widget-model.ts
> feat: set proper backend spec for dataTarget & add granularity widget field

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
- apps/web/src/common/modules/widgets/types/widget-display-type.ts
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
- apps/web/src/common/modules/widgets/types/widget-model.ts
- apps/web/src/schema/dashboard/private-widget/api-verbs/create.ts
- apps/web/src/schema/dashboard/public-widget/api-verbs/create.ts
- packages/mirinae/src/inputs/link/PLink.vue
> feat: update `WidgetProps` type

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCard.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep1.vue
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
> feat(preview-table): create data-table preview markup (without style) & apply load API 

- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
- apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
- apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
- apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
> feat: prevent import echarts directly

- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldFormatRules.vue
- apps/web/src/common/modules/widgets/_widgets/heatmap/widget-config.ts
- apps/web/src/common/modules/widgets/configs/widget-field-config.ts
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
- apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
> feat: add validation to Format Rules & refactoring

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCard.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
> feat: apply preview table style

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCard.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
- apps/web/src/schema/_common/type.ts
- apps/web/src/schema/dashboard/public-data-table/api-verbs/load.ts
> feat: apply preview table design & apply load options (pagination)

- apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCard.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
> feat: create data-table name form & set default name & add preview sorting

- apps/web/src/common/modules/widgets/_components/WidgetFieldDropdownAndMax.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldCategoryBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldMin.vue
- apps/web/src/common/modules/widgets/_widgets/treemap/widget-config.ts
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: create widgetFieldDropdown and connect widgetField

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCard.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
> feat: apply data-table overflow planning

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
> feat(preview-table): apply label fields sorting

- apps/web/src/common/modules/widgets/_components/WidgetFieldDropdownAndMax.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldCategoryBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldLineBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldStackBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldXAxis.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldYAxis.vue
- apps/web/src/common/modules/widgets/_widgets/heatmap/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/line-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/widget-config.ts
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
> feat: apply widgetFieldDropdown to widgetFields

- apps/web/src/services/asset-inventory/components/CollectorDataDuplicationInner.vue
> chore: apply css

- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/heatmap/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/pie-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/table/widget-config.ts
- apps/web/src/schema/dashboard/public-widget/api-verbs/update.ts
> feat: update widget configs

- apps/web/src/lib/menu/menu-architecture.ts
- apps/web/src/services/preference/routes/admin/routes.ts
> feat: apply hide admin bookmark menu

- apps/web/src/services/info/pages/admin/AdminNoticeDetailPage.vue
> feat: add email button

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/schema/dashboard/_types/dashboard-type.ts
- apps/web/src/services/dashboards/components/DashboardCustomize.vue
- apps/web/src/services/dashboards/components/DashboardVariableDropdown.vue
- apps/web/src/services/dashboards/components/DashboardVariablesV2.vue
- apps/web/src/services/dashboards/components/WidgetFullModeModal.vue
- apps/web/src/services/dashboards/constants/dashboard-managed-variables-schema.ts
- apps/web/src/services/dashboards/pages/DashboardDetailPage.vue
- apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
Dashboard Variables V2 is COMMING!!
> feat: add DashboardVariablesV2 

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCard.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFilters.vue
> feat: apply data-table filters

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/common/modules/widgets/_composables/use-widget/use-widget-frame.ts
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
- apps/web/src/schema/dashboard/_types/dashboard-type.ts
- apps/web/src/services/dashboards/components/DashboardCustomize.vue
- apps/web/src/services/dashboards/components/DashboardWidgetContainer.vue
- apps/web/src/services/dashboards/components/DashboardWidgetContainerV2.vue
- apps/web/src/services/dashboards/pages/DashboardDetailPage.vue
- apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
> feat: add DashboardWidgetContainer V2

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCard.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
> feat: apply data-table form validation & reset

- apps/web/src/common/modules/widgets/_components/WidgetFieldDropdownAndMax.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldBasisField.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldDataField.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldGranularity.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTotalField.vue
> feat: add validation to dropdown widgets

- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldFormatRules.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldGroupBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldIcon.vue
- apps/web/src/common/modules/widgets/_widgets/gauge/widget-config.ts
- apps/web/src/common/modules/widgets/configs/widget-field-config.ts
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
- apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: update format rules field

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep1.vue
> fix: apply data-table area design

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCard.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFilters.vue
- apps/web/src/common/modules/widgets/types/widget-model.ts
> chore: edit 'filters' to 'filter'

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldDataField.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldStackBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldXAxis.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldYAxis.vue
> feat: apply dataTarget to widgetFields

- apps/web/src/services/landing/components/DomainLandingStartBanner.vue
- apps/web/src/services/landing/components/LandingContents.vue
> feat: add workspace button

- apps/web/src/common/modules/widgets/_components/WidgetFieldDropdownAndMax.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldGranularity.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldGroupBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldLineBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
> feat: apply dataTarget to widget fields

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/common/modules/widgets/_composables/use-widget-init-and-refresh.ts
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldGranularity.vue
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
- apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
- apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
- apps/web/src/common/modules/widgets/types/widget-display-type.ts
- apps/web/src/services/dashboards/components/DashboardWidgetContainerV2.vue
- apps/web/src/store/modules/display/getters.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: update widget when click save button in overlay

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCard.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
> feat: apply data to data-table dropdown & create transform data-table card (without style) 

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
- apps/web/src/services/dashboards/components/DashboardControlButtons.vue
- apps/web/src/services/dashboards/components/DashboardCustomizeSidebar.vue
- apps/web/src/services/dashboards/components/DashboardWidgetContainerV2.vue
- apps/web/src/services/dashboards/pages/DashboardDetailPage.vue
- apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
> feat: add reorder sidebar to dashboard detail page

- apps/web/src/services/asset-inventory/pages/AssetAnalysisDetailPage.vue
- apps/web/src/services/workspace-home/components/AssetSummary.vue
- apps/web/src/services/workspace-home/components/AssetSummaryDailyUpdateItem.vue
- apps/web/src/services/workspace-home/components/AssetSummaryDailyUpdates.vue
- apps/web/src/services/workspace-home/components/AssetSummaryProvider.vue
- apps/web/src/services/workspace-home/components/AssetSummaryProviderItem.vue
- apps/web/src/services/workspace-home/types/workspace-home-type.ts
> feat: code separation and api updates

- apps/web/src/common/modules/widgets/_components/WidgetFieldDropdownAndMax.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldCategoryBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldGranularity.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldGroupBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldLineBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldStackBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldXAxis.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldYAxis.vue
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
- apps/web/src/services/dashboards/components/DashboardControlButtons.vue
- apps/web/src/services/dashboards/components/DashboardWidgetContainerV2.vue
> feat: apply saved value to widgetForm (stacked column chart))

- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
- apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
> feat: apply saved value to widgetForm(Table Data Field)

- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldGroupBy.vue
- apps/web/src/services/dashboards/components/DashboardWidgetContainerV2.vue
- apps/web/src/services/dashboards/pages/DashboardDetailPage.vue
- apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
> feat: add features for dashboard widget update

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
- apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
- apps/web/src/schema/dashboard/private-widget/api-verbs/create.ts
- apps/web/src/schema/dashboard/private-widget/api-verbs/update.ts
- apps/web/src/services/dashboards/components/DashboardControlButtons.vue
- apps/web/src/services/dashboards/components/DashboardWidgetContainerV2.vue
- apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: implement private widget case

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAlertModal.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardHeaderTitle.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardSourceForm.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformForm.vue
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
- apps/web/src/common/modules/widgets/types/widget-data-table-type.ts
> feat: create transformed data-table card & separate data-table card inner component & add transformed icon

- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/treemap/widget-config.ts
- apps/web/src/lib/variable-models/managed-model/resource-model/project-variable-model.ts
- apps/web/src/lib/variable-models/managed-model/resource-model/service-account-variable-model.ts
- apps/web/src/lib/variable-models/managed-model/resource-model/workspace-variable-model.ts
- apps/web/src/services/dashboards/components/DashboardVariableDropdown.vue
- apps/web/src/services/dashboards/components/DashboardVariables.vue
- apps/web/src/services/dashboards/components/DashboardVariablesV2.vue
> refactor: use PSelectDropdown!

- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldGroupBy.vue
> fix: fix data format to PSelectDropdown(multiSelectable)

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
> feat: update data_table_id of widget when change it

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardHeaderTitle.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformDataTableDropdown.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformForm.vue
> feat: create transform data-table dropdown

- apps/web/src/common/composables/error/errorHandler.ts
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
- apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
- apps/web/src/common/modules/widgets/types/widget-display-type.ts
> feat: add error toast to UpdatePreview Button

- apps/web/src/common/modules/widgets/_components/WidgetFieldDropdownAndMax.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldCategoryBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldDataField.vue
> feat: apply dataTarget to category by widget & fix dataTableField bug

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformDataTableDropdown.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformForm.vue
- apps/web/src/common/modules/widgets/_constants/data-table-constant.ts
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
- apps/web/src/common/modules/widgets/types/widget-model.ts
> feat: create transform data-table card options markup

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformDataTableDropdown.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformForm.vue
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
- apps/web/src/common/modules/widgets/types/widget-model.ts
> feat: apply transform data-table actions & apply scenario

- apps/web/src/common/modules/widgets/_components/WidgetFieldDropdownAndMax.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldDataField.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldGroupBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
> fix: check menu items according to the data table & modify to set default values

- apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformDataTableDropdown.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformForm.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep1.vue
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
- apps/web/src/common/modules/widgets/types/widget-data-table-type.ts
- apps/web/src/common/modules/widgets/types/widget-model.ts
SSIA
https://github.com/cloudforet-io/console/assets/83635051/9e0f4620-2800-4da3-9c4f-b1c441ad8668
> feat: apply and refactor transformed data-table scenario

- apps/web/src/common/modules/widgets/_components/WidgetFieldDropdownAndMax.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldGroupBy.vue
- packages/core-lib/__tests__/local-storage-accessor/__tests__/index.test.ts
> feat: add isAllWidgetFormValid

- apps/web/src/common/modules/widgets/_composables/use-widget/use-widget-frame.ts
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
- apps/web/src/common/modules/widgets/_widgets/heatmap/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
- apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
- apps/web/src/common/modules/widgets/types/widget-data-type.ts
- apps/web/src/common/modules/widgets/types/widget-display-type.ts
> feat: set proper dateRange to widgets

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
- apps/web/src/services/dashboards/pages/DashboardDetailPage.vue
> feat: implement table loadWidget

- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/common/modules/widgets/_composables/use-widget/use-widget-frame.ts
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
- apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
- apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
- apps/web/src/common/modules/widgets/types/widget-frame-type.ts
> feat: add `basedOnText` to metadata popper

- apps/web/src/lib/helper/config-data-helper.ts
> feat: apply favorite at anomaly detection menu

- apps/web/src/services/info/components/NoticeForm.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: add workspace dropdown

- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldDataField.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
> fix: fix the value format of TableDataField

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/common/modules/widgets/_composables/use-widget/use-widget-frame.ts
- apps/web/src/services/dashboards/components/DashboardWidgetContainerV2.vue
> feat: implement unit, full data link to metadata 

- apps/web/src/common/modules/navigations/top-bar/modules/TopBarSuggestionList.vue
- apps/web/src/services/info/components/NoticeForm.vue
- apps/web/src/services/workspace-home/components/UserConfigsItem.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: apply radio at workspace select dropdown

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/common/modules/widgets/_composables/use-widget/use-widget-frame.ts
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
- apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
- apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
- apps/web/src/common/modules/widgets/types/widget-frame-type.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: add `errorMessage` to WidgetFrame & set `errorMessage` when fetchWidget fails

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep1.vue
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
> fix: self QA & apply step1 data-table form area

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/common/modules/widgets/_composables/use-widget/use-widget-frame.ts
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
- apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
- apps/web/src/common/modules/widgets/types/widget-display-type.ts
- apps/web/src/services/dashboards/components/DashboardWidgetContainerV2.vue
- apps/web/src/services/dashboards/pages/DashboardPlaygroundPage.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: show overlay step2 when click expand button

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
- apps/web/src/common/modules/widgets/_constants/widget-components-constant.ts
- apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
- apps/web/src/services/dashboards/components/DashboardControlButtons.vue
- apps/web/src/services/dashboards/components/DashboardReorderSidebar.vue
- apps/web/src/store/modules/display/getters.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> fix: show widget list in reorder sidebar

- apps/web/src/services/dashboards/DashboardsLSB.vue
- apps/web/src/services/dashboards/components/DashboardCreateScopeForm.vue
- apps/web/src/services/dashboards/components/DashboardCreateStep2.vue
- apps/web/src/services/dashboards/components/DashboardMainSelectFilter.vue
- apps/web/src/services/dashboards/pages/DashboardCreatePage.vue
- apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
> feat: remove 'project' dashboard from dashboard page

- apps/web/src/services/project/ProjectLSB.vue
- apps/web/src/services/project/components/ProjectMainProjectCard.vue
- apps/web/src/services/project/composables/use-project-tree-data.ts
- apps/web/src/services/project/pages/ProjectDashboardPage.vue
- apps/web/src/services/project/pages/ProjectDetailTabPage.vue
- apps/web/src/services/project/routes/route-constant.ts
- apps/web/src/services/project/routes/routes.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: add dashboard tab to project page

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldIcon.vue
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
- apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
> feat: add icon widget field (options)

- apps/web/src/services/cost-explorer/constants/anomaly-detection-constant.ts
- apps/web/src/services/cost-explorer/pages/AnomalyDetectionConfigurationPage.vue
- apps/web/src/services/cost-explorer/pages/AnomalyDetectionHistoryPage.vue
- apps/web/src/services/cost-explorer/pages/AnomalyDetectionPolicyPage.vue
- apps/web/src/services/cost-explorer/routes/routes.ts
- apps/web/src/services/cost-explorer/types/anomaly-detection-type.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: apply each page heading

- apps/web/src/services/cost-explorer/components/AnomalyDetectionConfigurationInformationForm.vue
- apps/web/src/services/cost-explorer/components/AnomalyDetectionConfigurationRecipientsForm.vue
- apps/web/src/services/cost-explorer/constants/anomaly-detection-constant.ts
- apps/web/src/services/cost-explorer/pages/AnomalyDetectionConfigurationCreatePage.vue
- apps/web/src/services/cost-explorer/pages/AnomalyDetectionConfigurationPage.vue
- apps/web/src/services/cost-explorer/routes/route-constant.ts
- apps/web/src/services/cost-explorer/routes/routes.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: mark-up configuration create page

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/common/modules/widgets/_composables/use-widget/use-widget-frame.ts
- apps/web/src/common/modules/widgets/_helpers/widget-width-helper.ts
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
- apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
- apps/web/src/common/modules/widgets/types/widget-display-type.ts
- apps/web/src/common/modules/widgets/types/widget-frame-type.ts
- apps/web/src/schema/dashboard/private-widget/api-verbs/update.ts
- apps/web/src/schema/dashboard/private-widget/model.ts
- apps/web/src/schema/dashboard/public-widget/model.ts
- apps/web/src/services/dashboards/components/DashboardControlButtons.vue
- apps/web/src/services/dashboards/components/DashboardWidgetContainerV2.vue
- apps/web/src/services/dashboards/helpers/widget-width-helper.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
https://github.com/cloudforet-io/console/assets/18563857/118ae427-403a-44fe-9183-f0a23f35aa44
> feat: update widget size when click size toggle button

- apps/web/src/schema/dashboard/_types/dashboard-type.ts
- apps/web/src/services/dashboards/components/DashboardCreateStep1.vue
- apps/web/src/services/dashboards/components/DashboardCreateStep1SearchFilter.vue
- apps/web/src/services/dashboards/dashboard-template/template-list.ts
> feat: delete plugin filter from dashboard create page

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldComparison.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldIcon.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldLegend.vue
- apps/web/src/common/modules/widgets/_widgets/number-card/widget-config.ts
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
- apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: add ComparisonWidgetField and LegendWidgetField (options)

- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/services/dashboards/components/DashboardDetailHeader.vue
- apps/web/src/services/dashboards/components/DashboardMainBoardList.vue
- apps/web/src/services/dashboards/components/DashboardWidgetContainerV2.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: set intersectionObserver to dashboard container

- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldComparison.vue
- apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
> feat: set optional fields to NumberCard widget

- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldSubTotal.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTotal.vue
- apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: add total & sub total WidgetField (options)

- apps/web/src/services/asset-inventory/components/CloudServiceDetail.vue
> fix(feedback): edit only rule in more type field

- apps/web/src/services/asset-inventory/components/CloudServiceDetail.vue
> fix(feedback): handle no-results case in cloud-service detail keys

- apps/web/src/services/asset-inventory/components/CloudServiceDetailMultipleSelectedData.vue
> fix: apply new only rule to multi-case

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldComparison.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldGranularity.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldIcon.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldLegend.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldSubTotal.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTotal.vue
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
- apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
> fix: add default option to legend & fix css

- apps/web/src/services/cost-explorer/components/AnomalyDetectionConfigurationTable.vue
- apps/web/src/services/cost-explorer/components/AnomalyDetectionHistoryTable.vue
- apps/web/src/services/cost-explorer/constants/anomaly-detection-constant.ts
- apps/web/src/services/cost-explorer/pages/AnomalyDetectionHistoryPage.vue
> feat: create history main page

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
- apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
- apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
- apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
- apps/web/src/common/modules/widgets/_widgets/progress-card/ProgressCard.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
- apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
- apps/web/src/common/modules/widgets/types/widget-config-type.ts
> chore(step2): set size, title when change widget type & use PDataLoader in WidgetFrame 

- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/geo-map/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
- apps/web/src/common/modules/widgets/_widgets/heatmap/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
- apps/web/src/common/modules/widgets/_widgets/pie-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/progress-card/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/widget-config.ts
- apps/web/src/services/dashboards/components/DashboardWidgetContainerV2.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: set legend value to widgets

- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
> feat: add StackedHorizontalBarChart

- apps/web/src/common/modules/widgets/_components/WidgetFieldDropdownAndMax.vue
- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/services/dashboards/components/DashboardWidgetContainerV2.vue
Do not see second commit(chore: organize code).
> fix: fix loading bug in dashboard container

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldProgressBar.vue
- apps/web/src/common/modules/widgets/_widgets/table/widget-config.ts
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
- apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
> feat: add ProgressWidgetField (options)

- apps/web/src/services/dashboards/components/DashboardMainBoardList.vue
- apps/web/src/services/dashboards/pages/DashboardDetailPage.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: add deprecated badge and banner

- apps/web/src/common/modules/widgets/_composables/use-widget/use-widget-frame.ts
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
- apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
- apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
> chore: more flexible widget loading

- apps/web/src/common/modules/widgets/_constants/widget-field-components-constant.ts
- apps/web/src/common/modules/widgets/_constants/widget-field-constant.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldColorSchema.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldDataField.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldMax.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldMin.vue
- apps/web/src/common/modules/widgets/_widgets/heatmap/widget-config.ts
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
- apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: add ColorSchemaWidgetField (options)

- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
- apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
- apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
- apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
> feat: add Gauge widget

- apps/web/src/services/cost-explorer/components/AnomalyDetectionConfigurationInformation.vue
- apps/web/src/services/cost-explorer/components/AnomalyDetectionConfigurationInformationForm.vue
- apps/web/src/services/cost-explorer/components/AnomalyDetectionConfigurationRecipients.vue
- apps/web/src/services/cost-explorer/components/AnomalyDetectionConfigurationRecipientsForm.vue
- apps/web/src/services/cost-explorer/components/AnomalyDetectionConfigurationTable.vue
- apps/web/src/services/cost-explorer/constants/anomaly-detection-constant.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: apply changed policy card (design only)

- apps/web/src/common/components/bookmark/BookmarkFolderFormModal.vue
> chore: update import file

- apps/web/src/services/cost-explorer/components/DataSourceManagementTabAccessRestriction.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: add modal (design only)

- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldFormatRules.vue
- apps/web/src/common/modules/widgets/_widgets/gauge/widget-config.ts
> feat: add FormatRulesWidgetField (options)

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
- apps/web/src/common/modules/widgets/_composables/use-widget/use-widget-frame.ts
- apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
> feat: set min, max, format rules to Gauge widget

- apps/web/src/services/cost-explorer/components/AnomalyDetectionHistoryTable.vue
- apps/web/src/services/cost-explorer/constants/anomaly-detection-constant.ts
- apps/web/src/services/cost-explorer/pages/AnomalyDetectionHistoryPage.vue
> feat: add custom date modal (design only)

- apps/web/src/common/modules/widgets/_helpers/widget-date-helper.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
- apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat(table-data-field): add criteria to table data field 

- apps/web/src/services/cost-explorer/components/AnomalyDetectionHistoryDetail.vue
- apps/web/src/services/cost-explorer/components/AnomalyDetectionHistoryDetailTrend.vue
- apps/web/src/services/cost-explorer/components/AnomalyDetectionHistoryTable.vue
- apps/web/src/services/cost-explorer/composables/anomaly-detection-handler.ts
- apps/web/src/services/cost-explorer/pages/AnomalyDetectionHistoryDetailPage.vue
- apps/web/src/services/cost-explorer/routes/route-constant.ts
- apps/web/src/services/cost-explorer/routes/routes.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: add temp history detail page (design only)

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
- apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
- apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
- apps/web/src/common/modules/widgets/_widgets/table/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
- apps/web/src/common/modules/widgets/types/widget-config-type.ts
- apps/web/src/services/dashboards/components/DashboardDetailHeader.vue
- apps/web/src/services/dashboards/components/DashboardReorderSidebar.vue
- apps/web/src/services/dashboards/components/DashboardWidgetContainerV2.vue
> fix: fix echarts sync problem

- apps/web/src/services/workspace-home/components/CostSummary.vue
- apps/web/src/services/workspace-home/components/CostSummaryChart.vue
> fix: fixed loading bug

- apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
SORTING IS COMMING!!!!!!!!!!!!!
> feat: sorting is comming

- apps/web/src/services/auth/authenticator/external/GOOGLE_OAUTH2/template/GOOGLE_OAUTH2.vue
- apps/web/src/services/auth/authenticator/external/KEYCLOAK_OIDC/template/KEYCLOAK_OIDC.vue
- apps/web/src/services/auth/authenticator/external/SAML/template/SAML.vue
- apps/web/src/services/auth/authenticator/local/template/ID_PW.vue
- apps/web/src/services/auth/components/SignInContainer.vue
- apps/web/src/services/auth/components/SignInLeftContainer.vue
- apps/web/src/services/auth/components/SignInRightContainer.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> fix: fix saml design issues

- apps/web/src/common/modules/widgets/_helpers/widget-date-helper.ts
- apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
- apps/web/src/common/modules/widgets/types/widget-data-type.ts
- apps/web/src/lib/site-initializer/echarts.ts
- apps/web/src/services/dashboards/components/DashboardWidgetContainerV2.vue
- apps/web/src/store/reference/region-reference-store.ts
> feat: add GeoMap widget

- apps/web/src/common/modules/widgets/_composables/use-widget/use-widget-frame.ts
- apps/web/src/common/modules/widgets/_widgets/progress-card/ProgressCard.vue
- apps/web/src/services/workspace-home/components/AssetSummary.vue
- apps/web/src/services/workspace-home/components/AssetSummaryDailyUpdateItem.vue
- apps/web/src/services/workspace-home/components/AssetSummaryProviderItem.vue
> feat: add Progress Card widget

- apps/web/src/services/auth/components/SignInLeftContainer.vue
- packages/language-pack/ko.json
> fix: fix image bug

- apps/web/src/common/components/bookmark/BookmarkDeleteModal.vue
- apps/web/src/services/cost-explorer/pages/CostReportPage.vue
- apps/web/src/services/landing/components/DomainLandingNotification.vue
- apps/web/src/services/landing/components/LandingContents.vue
- apps/web/src/services/workspace-home/components/BookmarkBoard.vue
- apps/web/src/services/workspace-home/components/BookmarkFullMode.vue
- apps/web/src/services/workspace-home/components/BookmarkHeader.vue
- apps/web/src/services/workspace-home/components/WorkspaceInfo.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: apply minor qa (design only)

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
> fix: form group header's align and cursor style

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep1.vue
- apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
- apps/web/src/services/dashboards/DashboardsLSB.vue
- apps/web/src/services/dashboards/components/DashboardCreateScopeForm.vue
- apps/web/src/services/dashboards/components/DashboardDetailHeader.vue
- apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
- apps/web/src/services/project/ProjectLSB.vue
- apps/web/src/services/project/components/ProjectMainProjectGroupFormModal.vue
- apps/web/src/services/project/pages/ProjectDetailTabPage.vue
- apps/web/src/services/project/pages/ProjectMainPage.vue
- apps/web/src/services/project/routes/routes.ts
- packages/mirinae/src/inputs/context-menu/context-menu-item/PContextMenuItem.vue
> fix: fix minor bugs in project & dashboards

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldGroupBy.vue
> feat: add dependencies option to widgetForm

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
- apps/web/src/common/modules/widgets/_widgets/heatmap/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/line-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/progress-card/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/widget-config.ts
- apps/web/src/common/modules/widgets/types/widget-config-type.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: add default validation modal

- apps/web/src/schema/board/post/api-verbs/create.ts
- apps/web/src/schema/board/post/api-verbs/list.ts
- apps/web/src/schema/board/post/api-verbs/send.ts
- apps/web/src/schema/board/post/api-verbs/update.ts
- apps/web/src/schema/board/post/model.ts
- apps/web/src/services/info/components/NoticeDetail.vue
- apps/web/src/services/info/components/NoticeForm.vue
- apps/web/src/services/info/components/NoticeListItem.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: apply updated notice api

- apps/web/src/schema/cost-analysis/data-source/api-verbs/get.ts
- apps/web/src/schema/cost-analysis/data-source/api-verbs/update-permissions.ts
- apps/web/src/schema/monitoring/data-source/model.ts
- apps/web/src/services/cost-explorer/components/DataSourceManagementTabAccessRestriction.vue
- apps/web/src/services/cost-explorer/components/DataSourceManagementTable.vue
- apps/web/src/services/cost-explorer/stores/data-sources-page-store.ts
> feat: apply update permission api

- apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformDataTableDropdown.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformForm.vue
- apps/web/src/common/modules/widgets/_constants/data-table-constant.ts
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
- apps/web/src/common/modules/widgets/types/widget-data-table-type.ts
- apps/web/src/common/modules/widgets/types/widget-model.ts
> fix: apply tramsform API & refactor data-table dropdown and join type

- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldSubTotal.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
- apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
- apps/web/src/common/modules/widgets/types/widget-data-table-type.ts
- apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
> feat: create table widget data-fetching and data-converting & edit table field options(subTotal, dataField)

- apps/web/src/services/workspace-home/components/Welcome.vue
> chore: update image name

- apps/web/src/services/cost-explorer/components/DataSourceManagementTabAccessRestriction.vue
- apps/web/src/services/workspace-home/components/BookmarkBoard.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: apply changed api at datasource page

- apps/web/src/schema/dashboard/_types/dashboard-type.ts
- apps/web/src/services/dashboards/components/DashboardCreateStep1.vue
- apps/web/src/services/dashboards/components/DashboardCreateTemplateBoard.vue
> feat: add blank template to dashboard create page

- apps/web/src/services/info/components/NoticeForm.vue
- apps/web/src/services/info/components/NoticeList.vue
- apps/web/src/services/info/components/NoticeWorkspaceDropdown.vue
- apps/web/src/services/info/types/notice-type.ts
SSIA
Plz skip the first commit!
> feat: apply select dropdown at notice list

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
- apps/web/src/common/modules/widgets/_constants/widget-constant.ts
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
- apps/web/src/common/modules/widgets/_widgets/table/widget-config.ts
- apps/web/src/common/modules/widgets/types/widget-data-type.ts
> feat: apply separate date to Table widget & apply data-table reference updating

- apps/web/src/services/info/components/NoticeDetail.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: apply popover

- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
- apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
- apps/web/src/common/modules/widgets/types/widget-frame-type.ts
- apps/web/src/services/dashboards/components/DashboardCreateStep1.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: show 'ETC'

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformDataTableDropdown.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep1.vue
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
- apps/web/src/common/modules/widgets/types/widget-data-table-type.ts
> feat: apply Join restriction case

- apps/web/src/services/info/pages/admin/AdminNoticeDetailPage.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: apply send api

- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldDataField.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldGroupBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
> fix: fix the default value setting logic (tableDataField, GroupBy, DataField)

- apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
- apps/web/src/common/modules/widgets/_composables/use-widget-init-and-refresh.ts
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
- apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
- apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
- apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
- apps/web/src/common/modules/widgets/_widgets/progress-card/ProgressCard.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
- apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
- apps/web/src/common/modules/widgets/types/widget-display-type.ts
- apps/web/src/services/dashboards/components/DashboardNameEditModal.vue
- apps/web/src/services/dashboards/components/DashboardReorderSidebar.vue
- apps/web/src/services/dashboards/components/DashboardWidgetContainerV2.vue
- apps/web/src/services/dashboards/pages/DashboardDetailPage.vue
- apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
- apps/web/src/store/dashboard/dashboard-store.ts
> fix: fix vars when load widget

- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
- apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
> feat: create base widget-data-table

- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
- apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
- apps/web/src/common/modules/widgets/types/widget-frame-type.ts
> fix: set multiple full data link, units in metadata popover

- apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
- apps/web/src/common/modules/widgets/_helpers/widget-date-helper.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldDataField.vue
- apps/web/src/lib/config/index.ts
- apps/web/src/services/dashboards/components/DashboardReorderSidebar.vue
- apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
> fix: fix reorder dashboard layouts & fix init bug when change data table id

- apps/web/src/services/cost-explorer/components/AnomalyDetectionHistoryTable.vue
- apps/web/src/services/cost-explorer/composables/anomaly-detection-handler.ts
- apps/web/src/services/cost-explorer/constants/anomaly-detection-constant.ts
- apps/web/src/services/cost-explorer/pages/AnomalyDetectionHistoryDetailPage.vue
> feat: define the notify level for system alerts

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
- apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
- apps/web/src/common/modules/widgets/types/widget-data-type.ts
- packages/mirinae/src/foundation/icons/icon-assets/ic_arrow-down-bold-alt.svg
- packages/mirinae/src/foundation/icons/p-icons/ic_arrow-down-bold-alt.js
- packages/mirinae/src/foundation/icons/p-icons/index.js
> feat: add comparison data converting & apply comparison field

- apps/web/src/services/info/components/NoticeList.vue
- apps/web/src/services/info/components/NoticeWorkspaceDropdown.vue
> chore: changed dropdown width

- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
- apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
- apps/web/src/lib/site-initializer/api-client.ts
- apps/web/src/services/project/ProjectLSB.vue
- apps/web/src/services/project/components/ProjectMainTree.vue
- apps/web/src/services/project/composables/use-project-tree-data.ts
- apps/web/src/services/project/pages/ProjectDetailPage.vue
https://mzdevs.atlassian.net/browse/MZ00003-643
https://mzdevs.atlassian.net/browse/MZ00003-610
https://mzdevs.atlassian.net/browse/MZ00003-612
> fix: fix qa things of project page

- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTotal.vue
- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
- apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
> feat(table-widget): create converted total data and apply

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
> fix: add default group by (project ...)

- apps/web/src/common/modules/widgets/_components/WidgetFieldDropdownAndMax.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldBasisField.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldColorSchema.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldFormatRules.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldGroupBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldLineBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldProgressBar.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldStackBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTotalField.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldXAxis.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldYAxis.vue
> fix(step2WidgetForm): fix options field css bug

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFilters.vue
> fix: add missing filter items to data-table filter form

- apps/web/src/services/cost-explorer/components/CostAnalysisFiltersPopper.vue
- apps/web/src/services/cost-explorer/constants/managed-cost-analysis-query-sets.ts
> fix(cost-analysis): fix setting saved filters

- apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
> fix: apply private data-table

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/common/modules/widgets/_composables/use-widget-init-and-refresh.ts
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
- apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
- apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
- apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
- apps/web/src/common/modules/widgets/_widgets/progress-card/ProgressCard.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
- apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
- apps/web/src/common/modules/widgets/types/widget-display-type.ts
- apps/web/src/schema/dashboard/_types/dashboard-type.ts
- apps/web/src/schema/dashboard/private-dashboard/api-verbs/create.ts
- apps/web/src/schema/dashboard/private-dashboard/model.ts
- apps/web/src/schema/dashboard/private-widget/api-verbs/load.ts
- apps/web/src/schema/dashboard/public-dashboard/api-verbs/create.ts
- apps/web/src/schema/dashboard/public-dashboard/model.ts
- apps/web/src/schema/dashboard/public-widget/api-verbs/load.ts
- apps/web/src/services/dashboards/components/DashboardVariableDropdown.vue
- apps/web/src/services/dashboards/components/DashboardVariablesV2.vue
- apps/web/src/services/dashboards/components/DashboardWidgetContainerV2.vue
- apps/web/src/services/dashboards/pages/DashboardDetailPage.vue
- apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
> fix: fix dashboard vars save bug

- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldGroupBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
> fix: rollback useGranularityMenuItems composable

- apps/web/src/services/preference/pages/admin/AdminDomainSettingsAutoDormancyConfigurationPage.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: create auto-dormancy-configuration-page (design-only)

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardHeaderTitle.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
> feat: add previewWidgetValueMap to widget-generate store

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
- apps/web/src/common/modules/widgets/_constants/widget-constant.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
- apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
> feat: apply small issues and design changes

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFilters.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
- apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
> feat: apply data-table field validation & other fix

- apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFooter.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardHeaderTitle.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep1.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
- apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
- apps/web/src/services/dashboards/components/DashboardReorderSidebar.vue
> chore: fix minor things

- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
- apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
> refactor: table widget data converting

- apps/web/src/common/components/bookmark/BookmarkFolderFormModal.vue
- apps/web/src/common/components/bookmark/BookmarkLinkFormModal.vue
- apps/web/src/services/workspace-home/components/BookmarkBoard.vue
- apps/web/src/services/workspace-home/components/BookmarkFullMode.vue
- apps/web/src/services/workspace-home/components/BookmarkHeader.vue
- apps/web/src/services/workspace-home/store/bookmark-store.ts
> feat: apply changed bookmark design

- apps/web/src/common/modules/widgets/_composables/use-granularity-menu-items.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldGroupBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
> fix: fix the useGranularityMenuItems composable

- apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformForm.vue
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
- apps/web/src/common/modules/widgets/types/widget-data-table-type.ts
- apps/web/src/common/modules/widgets/types/widget-model.ts
> fix(evaluate): edit transform eval model

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
- apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
> feat: add load after transform updated

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep1.vue
- apps/web/src/common/modules/widgets/_composables/use-granularity-menu-items.ts
- apps/web/src/common/modules/widgets/_helpers/widget-field-helper.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldCategoryBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldGroupBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldLineBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldStackBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldXAxis.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldYAxis.vue
- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
> feat: apply widget data labels_info key sorting & set initial load to step1

- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
- apps/web/src/services/dashboards/components/DashboardDetailHeader.vue
- apps/web/src/services/dashboards/components/DashboardShareWithCodeModal.vue
- apps/web/src/services/dashboards/helpers/dashboard-share-helper.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: add 'Share to all workspaces' button & separate to helper

- apps/web/src/common/components/bookmark/BookmarkFolderFormModal.vue
- apps/web/src/common/components/bookmark/BookmarkLinkFormModal.vue
- apps/web/src/common/components/bookmark/type/type.ts
- apps/web/src/services/cost-explorer/components/DataSourceManagementTabLinkedAccount.vue
- apps/web/src/services/workspace-home/components/BookmarkBoard.vue
- apps/web/src/services/workspace-home/components/BookmarkHeader.vue
- apps/web/src/services/workspace-home/store/bookmark-store.ts
> feat: fixed minor bugs

- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
- apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
- apps/web/src/common/modules/widgets/types/widget-model.ts
> feat: apply table widget unit tooltip

- apps/web/src/common/modules/widgets/_components/WidgetFieldDropdownAndMax.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/common/modules/widgets/_composables/use-widget-init-and-refresh.ts
- apps/web/src/common/modules/widgets/_helpers/widget-field-helper.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldCategoryBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldGranularity.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldGroupBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldLineBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldStackBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldXAxis.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldYAxis.vue
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/heatmap/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/line-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/pie-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/table/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/treemap/widget-config.ts
- apps/web/src/common/modules/widgets/types/widget-display-type.ts
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
https://github.com/cloudforet-io/console/assets/18563857/4661b187-ae5a-45c5-9015-ac384b5c8503
> feat: add `defaultIndex`, `excludeDateField` to widget fields

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFilters.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep1.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/common/modules/widgets/_helpers/widget-date-helper.ts
> fix: update variable models map in step1

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
> feat(data-table): apply changed planning

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
https://github.com/cloudforet-io/console/assets/50662170/2ee1e6d3-5cbd-495b-9349-ae58b7790b94
> feat: add error modal to TableDataField for label error case

- apps/web/src/common/components/bookmark/BookmarkFolderFormModal.vue
- apps/web/src/common/components/bookmark/BookmarkLinkFormModal.vue
> chore: apply workspace member case

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
> chore: fix bugs in GeoMap and expand overlay

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFilters.vue
- apps/web/src/lib/variable-models/_base/resource-variable-model.ts
- apps/web/src/lib/variable-models/_base/types.ts
- apps/web/src/lib/variable-models/variable-model-menu-handler.ts
- apps/web/src/services/cost-explorer/components/CostAnalysisFiltersPopper.vue
> fix: add primary filter options to variable model

- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldCategoryBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldLineBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldStackBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldXAxis.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldYAxis.vue
> feat: apply useGranularityMenuItem hook & set default value for tableDataField

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFooter.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
- apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
- apps/web/src/services/dashboards/components/DashboardCloneModal.vue
- apps/web/src/services/dashboards/components/DashboardDetailHeader.vue
- apps/web/src/services/dashboards/components/DashboardShareWithCodeModal.vue
- apps/web/src/services/dashboards/helpers/dashboard-share-helper.ts
- apps/web/src/services/dashboards/types/dashboard-api-schema-type.ts
- apps/web/src/services/dashboards/types/shared-dashboard-type.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: update dashboard clone logic

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep1.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- packages/mirinae/src/feedbacks/alert/notice-alert/PNoticeAlert.vue
- packages/mirinae/src/feedbacks/alert/toast-alert/PToastAlert.vue
> chore: edit margin of toast, notice & fix minor

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
> fix: fix widgetField dependency flow bug

- apps/web/src/common/modules/widgets/_composables/use-granularity-menu-items.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
- apps/web/src/common/modules/widgets/_widgets/table/widget-config.ts
> fix: fix error modal emit bug

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
- apps/web/src/common/modules/widgets/_constants/widget-components-constant.ts
- apps/web/src/common/modules/widgets/_helpers/widget-component-helper.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldFormatRules.vue
- apps/web/src/services/dashboards/components/DashboardDetailHeader.vue
- apps/web/src/services/dashboards/components/DashboardWidgetContainerV2.vue
> feat: hide progress card from dashboard widgets

- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/services/dashboards/components/DashboardWidgetContainerV2.vue
> fix: fix widget frame sync bug

- apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep1.vue
Fix a minor design issue with the Add Button in step 1.
> fix: step1 add button's design

- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
- apps/web/src/services/dashboards/components/DashboardCloneModal.vue
- apps/web/src/services/dashboards/components/DashboardDetailHeader.vue
- apps/web/src/services/dashboards/components/DashboardMainBoardList.vue
> feat: dashboard clone modal

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFilters.vue
- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
- apps/web/src/common/modules/widgets/types/widget-display-type.ts
- apps/web/src/services/dashboards/components/DashboardCloneModal.vue
> fix: solve data-table filter bug

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
- apps/web/src/common/modules/widgets/_widgets/heatmap/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/line-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/pie-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/treemap/widget-config.ts
- apps/web/src/common/modules/widgets/types/widget-config-type.ts
- apps/web/src/common/modules/widgets/types/widget-model.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: modify rule for error modal visibility (default case / geoMap / progressCard)

- apps/web/src/services/project/components/ProjectMainTree.vue
- apps/web/src/services/project/stores/project-tree-store.ts
- apps/web/src/services/project/tree/type.ts
- packages/mirinae/src/data-display/tree/tree-view/PTreeItem.vue
> refactor: improved creating-tree-data logic of project-tree

- apps/web/src/common/modules/navigations/gnb/GNBToolbox.vue
- apps/web/src/services/project/components/ProjectMainTree.vue
> chore: solve project breadcrumbs bug

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
> feat: add widgetDefaultValidation to step2WidgetForm & fix img file bug

- apps/web/src/schema/repository/dashboard-template/api-verbs/list.ts
- apps/web/src/schema/repository/dashboard-template/model.ts
- apps/web/src/schema/repository/dashboard-template/type.ts
- apps/web/src/services/dashboards/components/DashboardCloneModal.vue
- apps/web/src/services/dashboards/components/DashboardCreateScopeForm.vue
- apps/web/src/services/dashboards/components/DashboardCreateStep1.vue
- apps/web/src/services/dashboards/components/DashboardCreateStep2.vue
- apps/web/src/services/dashboards/components/DashboardCreateTemplateBoard.vue
- apps/web/src/services/dashboards/components/DashboardShareWithCodeModal.vue
- apps/web/src/services/dashboards/helpers/dashboard-share-helper.ts
- apps/web/src/services/dashboards/pages/DashboardCreatePage.vue
- apps/web/src/services/dashboards/stores/dashboard-create-page-store.ts
> feat: update dashboard create page

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
- apps/web/src/services/dashboards/components/DashboardToolsetDateDropdown.vue
> fix: fix default rule of tableDataField 

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
- apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
> fix: solve scroll issue and data-table load issue

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
> fix(data-table-preview): apply ascending sorting

- apps/web/src/common/modules/widgets/_constants/widget-components-constant.ts
- apps/web/src/common/modules/widgets/_constants/widget-config-list-constant.ts
- apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/widget-config.ts
> feat: loadWidget without group by in line charts

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep1.vue
- apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
- apps/web/src/services/project/pages/ProjectDetailPage.vue
SSIA
- resize bar position issue
- new widget unshift issue
- project detail page back button
> fix: solve some issues

- apps/web/src/common/modules/widgets/_helpers/widget-date-helper.ts
SSIA
Applied 'endOf'
- daily: input - '2024-06' -> output - '2024-06-30'
- monthly: input - '2024-06' -> output - '2024-12'
> fix: edit `getWidgetBasedOnDate` helper

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep1.vue
- apps/web/src/store/reference/project-reference-store.ts
> fix: solve critical QAs

- apps/web/src/common/modules/widgets/_helpers/widget-date-helper.ts
> chore: edit base-on-date helper

- apps/web/src/common/modules/popup/notice/NoticePopup.vue
> fix: fix notice popup bug

- apps/web/src/common/modules/favorites/favorite-button/FavoriteButton.vue
- apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-favorite/modules/TopBarFavoriteContextMenu.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
- apps/web/src/common/modules/widgets/_composables/use-widget-init-and-refresh.ts
- apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
- apps/web/src/common/modules/widgets/types/widget-display-type.ts
- apps/web/src/services/dashboards/helpers/dashboard-share-helper.ts
- apps/web/src/services/workspace-home/components/UserConfigRecent.vue
- apps/web/src/store/dashboard/dashboard-store.ts
> fix: fix widget mount bug in widget overlay

- apps/web/src/lib/menu/menu-architecture.ts
- apps/web/src/services/preference/routes/admin/routes.ts
> feat: apply bookmark menu

- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/services/dashboards/components/DashboardControlButtons.vue
> feat: add DASHBOARD_EDIT_DISABLE config

- apps/web/src/common/modules/widgets/_helpers/widget-config-helper.ts
- apps/web/src/services/dashboards/components/DashboardCreateScopeForm.vue
- apps/web/src/services/dashboards/components/DashboardCreateStep2.vue
- apps/web/src/services/dashboards/components/DashboardRefreshDropdown.vue
- apps/web/src/services/dashboards/components/DashboardReorderSidebar.vue
- apps/web/src/services/dashboards/components/DashboardToolsetDateDropdown.vue
- apps/web/src/services/dashboards/pages/DashboardCreatePage.vue
- apps/web/src/services/dashboards/stores/dashboard-create-page-store.ts
> fix: fix reorder sidebar bug & fix bug in dashboard create page

- apps/web/src/services/preference/components/BookmarkLSB.vue
- apps/web/src/services/preference/components/BookmarkManagementTable.vue
- apps/web/src/services/preference/pages/admin/AdminBookmarkPage.vue
- apps/web/src/services/preference/store/bookmark-page-store.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: apply list API

- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
- apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
- apps/web/src/common/modules/widgets/types/widget-data-table-type.ts
> feat: apply asset(size) value formatter to table widget

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardHeaderTitle.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
- apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
- apps/web/src/services/asset-inventory/components/MetricExplorerDataTable.vue
- apps/web/src/services/asset-inventory/constants/asset-analysis-constant.ts
> feat: apply size formatter to data-table preview table

- apps/web/src/schema/cost-analysis/data-source/model.ts
- apps/web/src/store/reference/cost-data-source-reference-store.ts
> feat: add `permissions` to CostDataSourceModel

- apps/web/src/common/components/bookmark/BookmarkFolderFormModal.vue
- apps/web/src/common/components/bookmark/BookmarkLinkFormModal.vue
- apps/web/src/common/components/bookmark/store/bookmark-store.ts
- apps/web/src/common/components/bookmark/type/type.ts
- apps/web/src/services/cost-explorer/components/DataSourceManagementTable.vue
- apps/web/src/services/preference/components/BookmarkLSB.vue
- apps/web/src/services/preference/components/BookmarkManagementTable.vue
- apps/web/src/services/preference/components/BookmarkTree.vue
- apps/web/src/services/preference/pages/admin/AdminBookmarkPage.vue
- apps/web/src/services/preference/store/bookmark-page-store.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: apply API for create global bookmark and LSB

- apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts
- apps/web/src/services/asset-inventory/pages/MetricExplorerDetailPage.vue
- apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts
- apps/web/src/services/asset-inventory/types/metric-explorer-url-query-type.ts
[[Major][Dashboard] Metadata 에서 full link 클릭시, Filter가 안먹히는 이슈](https://mzdevs.atlassian.net/browse/MZ00003-739)
> fix: set proper filter to full data link in metadata 

- apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
> chore: update date range logic

- apps/web/src/common/components/bookmark/BookmarkLinkFormModal.vue
- apps/web/src/services/preference/components/BookmarkManagementTable.vue
- apps/web/src/services/preference/store/bookmark-page-store.ts
> feat: table detail - workspace col, name col, loading

- apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts
- apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
- apps/web/src/schema/cost-analysis/data-source/model.ts
- apps/web/src/services/asset-inventory/pages/MetricExplorerDetailPage.vue
- apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts
- apps/web/src/services/asset-inventory/types/metric-explorer-url-query-type.ts
- apps/web/src/store/reference/cost-data-source-reference-store.ts
> feat(feature-project-workspace-home): merge to master branch

- apps/web/src/services/preference/components/BookmarkContainer.vue
- apps/web/src/services/preference/components/BookmarkManagementTable.vue
- apps/web/src/services/preference/components/BookmarkTree.vue
- apps/web/src/services/preference/composables/bookmark-data-helper.ts
- apps/web/src/services/preference/routes/admin/routes.ts
- apps/web/src/services/preference/routes/route-constant.ts
> chore: minor changed for refactor

- apps/web/src/services/preference/components/BookmarkContainer.vue
- apps/web/src/services/preference/components/BookmarkManagementDetailTable.vue
- apps/web/src/services/preference/pages/admin/AdminBookmarkDetailPage.vue
- apps/web/src/services/preference/pages/admin/AdminBookmarkPage.vue
- apps/web/src/services/preference/routes/admin/routes.ts
- apps/web/src/services/preference/store/bookmark-page-store.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
SSIA
I used the existing code for detail page.
> feat: create bookmark detail page - group

- apps/web/src/common/modules/widgets/_components/WidgetFormCostDataSourcePopper.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
- apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
- packages/mirinae/src/data-display/tooltips/PTooltip.pcss
> feat: apply new cost unit & apply compact formatter and fix small issues

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAlertModal.vue
- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
- apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
- apps/web/src/common/modules/widgets/types/widget-frame-type.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: add noData to widgetFrame

- apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardHeaderTitle.vue
- apps/web/src/common/modules/widgets/_helpers/widget-data-table-helper.ts
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
> feat: apply changed transform name planning

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
- apps/web/src/services/cost-explorer/components/CostAnalysisDataTypeDropdown.vue
> chore: apply changed cost alias

- apps/web/src/services/info/pages/admin/AdminNoticeDetailPage.vue
> chore: hide loading msg

- apps/web/src/services/info/components/NoticeForm.vue
> chore: fix notice update bug

- apps/web/src/services/preference/components/BookmarkDetailContainer.vue
- apps/web/src/services/preference/components/BookmarkTree.vue
- apps/web/src/services/preference/pages/admin/AdminBookmarkDetailPage.vue
- apps/web/src/services/preference/routes/admin/routes.ts
- apps/web/src/services/preference/routes/route-constant.ts
> refactor: only code refactor (route, component)

- apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue
- apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts
- apps/web/src/lib/menu/menu-architecture.ts
- apps/web/src/services/asset-inventory/components/MetricExplorerLSBMetric.vue
- apps/web/src/services/asset-inventory/pages/MetricExplorerDetailPage.vue
- apps/web/src/services/asset-inventory/routes/admin/routes.ts
- apps/web/src/store/modules/display/getters.ts
metric explorer is coming to admin mode!!!
> feat: metric explorer is coming to admin mode! & fix admin widget full data link 

- apps/web/src/services/dashboards/DashboardsLSB.vue
- apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
- apps/web/src/store/dashboard/dashboard-store.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> fix: fix lsb structure & dashboard item list order & remove deprecated ashboard name from duplicated rule

- apps/web/src/services/info/components/NoticeForm.vue
- apps/web/src/services/info/pages/admin/AdminNoticeDetailPage.vue
> feat: apply minor notice qa

- apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue
- apps/web/src/store/dashboard/dashboard-store.ts
>  chore: edit wrong usage of edit params issue 

- apps/web/src/services/preference/components/BookmarkDetailContainer.vue
- apps/web/src/services/preference/pages/admin/AdminBookmarkDetailPage.vue
- apps/web/src/services/preference/store/bookmark-page-store.ts
> feat: apply folder detail page api and header button

- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts
- apps/web/src/common/modules/widgets/_composables/use-widget-init-and-refresh.ts
- apps/web/src/common/modules/widgets/_helpers/widget-date-helper.ts
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
- apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
- apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
- apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
- apps/web/src/common/modules/widgets/_widgets/progress-card/ProgressCard.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
- apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
> feat: do not load unless widget has all required fields

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFilters.vue
> fix: apply project to admin dashboard

- apps/web/src/common/modules/widgets/_helpers/widget-date-helper.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldFormatRules.vue
- apps/web/src/common/modules/widgets/_widgets/gauge/widget-config.ts
> fix: check null, undefined, '' of widget options

- apps/web/src/services/dashboards/DashboardsLSB.vue
> fix: fix favorite in dashboard LSB

- apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
> fix(table-widget): apply reference label to table field

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
- apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
> chore: add missing changes

- apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
> fix: remove setting project dashboard variables and variable schema

- apps/web/src/services/dashboards/components/DashboardCreateStep1.vue
- apps/web/src/services/dashboards/constants/dashboard-labels.ts
> fix: fix the dashboard create step1 UI bug

- apps/web/src/common/modules/monitoring/MetricChart.vue
- apps/web/src/common/modules/monitoring/Monitoring.vue
- apps/web/src/services/project/components/ProjectSummaryAllSummaryWidget.vue
- apps/web/src/services/project/components/ProjectSummaryAllSummaryWidgetRegionService.vue
- apps/web/src/services/project/components/ProjectSummaryBillingWidget.vue
- apps/web/src/services/project/pages/ProjectDashboardPage.vue
> feat: add charts

- apps/web/src/common/components/bookmark/BookmarkDeleteModal.vue
- apps/web/src/common/components/bookmark/BookmarkFolderFormModal.vue
- apps/web/src/common/components/bookmark/BookmarkLinkFormModal.vue
- apps/web/src/common/components/bookmark/store/bookmark-store.ts
- apps/web/src/services/preference/components/BookmarkContainer.vue
- apps/web/src/services/preference/components/BookmarkDetailContainer.vue
- apps/web/src/services/preference/components/BookmarkManagementDetailTable.vue
- apps/web/src/services/preference/components/BookmarkManagementTable.vue
- apps/web/src/services/preference/pages/admin/AdminBookmarkPage.vue
- apps/web/src/services/preference/store/bookmark-page-store.ts
> feat: apply heading function for detail page

- apps/web/src/services/cost-explorer/pages/admin/AdminDataSourcePage.vue
- apps/web/src/services/landing/components/DomainLandingRecommendation.vue
- apps/web/src/services/landing/components/DomainLandingTitle.vue
- apps/web/src/services/workspace-home/components/Welcome.vue
> chore: fixed link

- apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
> chore: apply changed project dashboard planning

- apps/web/src/services/preference/components/BookmarkContainer.vue
- apps/web/src/services/preference/components/BookmarkManagementDetailTable.vue
- apps/web/src/services/preference/components/BookmarkManagementTable.vue
- apps/web/src/services/preference/store/bookmark-page-store.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: apply table col function

- apps/web/src/common/modules/navigations/lsb/modules/LSBCollapsibleMenuItem.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormCostDataSourcePopper.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue
> chore: solve small issues

- apps/web/src/services/preference/components/BookmarkManagementDetailTable.vue
- apps/web/src/services/preference/components/BookmarkTree.vue
> feat: apply breadcrumbs, tree, col-name at table

- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
- apps/web/src/common/modules/widgets/types/widget-display-type.ts
- apps/web/src/common/modules/widgets/types/widget-frame-type.ts
- apps/web/src/services/dashboards/components/DashboardControlButtons.vue
- apps/web/src/services/dashboards/components/DashboardDetailHeader.vue
- apps/web/src/services/dashboards/components/DashboardRefreshDropdown.vue
- apps/web/src/services/dashboards/components/DashboardToolsetDateDropdown.vue
- apps/web/src/services/dashboards/components/DashboardWidgetContainerV2.vue
- apps/web/src/services/dashboards/pages/DashboardDetailPage.vue
- apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
- apps/web/src/store/dashboard/dashboard-store.ts
> feat: add `disableManageButtons` to dashboard-detail-info-store, widget frame

- apps/web/src/services/dashboards/DashboardsLSB.vue
> fix: update deprecated menuItem rules

- packages/language-pack/ja.json
- packages/language-pack/ko.json
> Fix translation

- apps/web/src/schema/board/post/model.ts
- apps/web/src/services/info/components/NoticeForm.vue
- apps/web/src/services/landing/components/DomainLandingNotification.vue
- apps/web/src/services/workspace-home/components/AssetSummaryProvider.vue
- apps/web/src/services/workspace-home/store/workspace-home-page-store.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: fixed minor bug at notice, analyze api

- apps/web/src/common/modules/widgets/types/widget-model.ts
- apps/web/src/schema/dashboard/private-widget/api-verbs/create.ts
- apps/web/src/schema/dashboard/private-widget/api-verbs/update.ts
- apps/web/src/schema/dashboard/private-widget/model.ts
- apps/web/src/schema/dashboard/public-widget/api-verbs/create.ts
- apps/web/src/schema/dashboard/public-widget/api-verbs/update.ts
- apps/web/src/schema/dashboard/public-widget/model.ts
> feat: apply widget state to model and parameters

- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
- apps/web/src/common/modules/widgets/types/widget-model.ts
- apps/web/src/schema/dashboard/private-widget/api-verbs/create.ts
- apps/web/src/schema/dashboard/private-widget/api-verbs/update.ts
- apps/web/src/schema/dashboard/private-widget/model.ts
- apps/web/src/schema/dashboard/public-widget/api-verbs/create.ts
- apps/web/src/schema/dashboard/public-widget/api-verbs/update.ts
- apps/web/src/schema/dashboard/public-widget/model.ts
> chore: edit widget state type name & create status getter

- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts
- apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
- apps/web/src/common/modules/widgets/types/widget-frame-type.ts
- apps/web/src/services/asset-inventory/pages/MetricExplorerDetailPage.vue
- apps/web/src/services/dashboards/components/DashboardWidgetContainerV2.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> chore: edit periodText in metadata tooltip 

- apps/web/src/services/preference/components/BookmarkLSB.vue
- apps/web/src/services/preference/components/BookmarkManagementDetailTable.vue
- apps/web/src/services/preference/components/BookmarkManagementTable.vue
- apps/web/src/services/preference/composables/bookmark-data-helper.ts
- apps/web/src/services/preference/constants/bookmark-constant.ts
- apps/web/src/services/preference/store/bookmark-page-store.ts
> feat: apply search at LSB, tables

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardHeaderTitle.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
> feat: update widget `state` when changing or updating dataTable

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/common/modules/widgets/_helpers/widget-date-helper.ts
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
- apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
> feat: get proper date range even if user select wrong date range 

- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldLineBy.vue
> feat: update the lineByField to optional

- apps/web/src/services/dashboards/DashboardsLSB.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> fix: update DashboardLSB to new design

- apps/web/src/services/dashboards/components/DashboardCloneModal.vue
> fix: fix dashboard clone bug

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
> fix: fix mount bug in widget overlay & fix etc bug in clursteredColumnChart 

- apps/web/src/services/cost-explorer/components/AnomalyDetectionPolicyRuleCard.vue
- apps/web/src/services/cost-explorer/pages/AnomalyDetectionPolicyPage.vue
- apps/web/src/services/cost-explorer/stores/anomaly-detection-policy-page-store.ts
> feat: create PolicyRuleCard (only markup)

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
- apps/web/src/common/modules/widgets/types/widget-display-type.ts
- apps/web/src/common/modules/widgets/types/widget-frame-type.ts
- apps/web/src/common/modules/widgets/types/widget-model.ts
- apps/web/src/schema/dashboard/private-widget/api-verbs/create.ts
- apps/web/src/schema/dashboard/private-widget/api-verbs/update.ts
- apps/web/src/schema/dashboard/private-widget/model.ts
- apps/web/src/schema/dashboard/public-widget/api-verbs/create.ts
- apps/web/src/schema/dashboard/public-widget/api-verbs/update.ts
- apps/web/src/schema/dashboard/public-widget/model.ts
- apps/web/src/services/dashboards/components/DashboardWidgetContainerV2.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> fix: fix resizeObserver error

- apps/web/src/common/modules/widgets/_constants/widget-field-components-constant.ts
> fix: remove dynamic import in WIDGET_FIELD_COMPONENT

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
- apps/web/src/services/dashboards/components/DashboardWidgetContainerV2.vue
> fix: fix comparing object value in overlay step2

- apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
- apps/web/src/services/dashboards/components/DashboardCreateStep2.vue
- apps/web/src/services/dashboards/components/DashboardCreateTemplateBoard.vue
- apps/web/src/services/dashboards/components/DashboardWidgetContainerV2.vue
- apps/web/src/services/dashboards/helpers/dashboard-share-helper.ts
- apps/web/src/services/dashboards/stores/dashboard-create-page-store.ts
> feat: implement `state` to dashboard widgets

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
- apps/web/src/common/modules/widgets/_composables/use-widget-option-validation.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldBasisField.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldCategoryBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldColorSchema.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldComparison.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldDataField.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldFormatRules.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldGranularity.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldGroupBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldIcon.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldLegend.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldLineBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldMax.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldMin.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldProgressBar.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldStackBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldSubTotal.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTotal.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTotalField.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldXAxis.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldYAxis.vue
- apps/web/src/common/modules/widgets/_widgets/pie-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/treemap/widget-config.ts
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
SSIA
- Create `use-widget-option-validation` hook!!!
> feat: create widget-option-validation hook & small fix

- apps/web/src/common/components/bookmark/BookmarkDeleteModal.vue
- apps/web/src/common/components/bookmark/BookmarkFolderFormModal.vue
- apps/web/src/common/components/bookmark/BookmarkLinkFormModal.vue
- apps/web/src/common/components/bookmark/store/bookmark-store.ts
- apps/web/src/services/preference/components/BookmarkContainer.vue
- apps/web/src/services/preference/components/BookmarkDetailContainer.vue
- apps/web/src/services/preference/components/BookmarkManagementTable.vue
- apps/web/src/services/preference/components/BookmarkTree.vue
- apps/web/src/services/preference/pages/admin/AdminBookmarkPage.vue
- apps/web/src/services/preference/store/bookmark-page-store.ts
- apps/web/src/services/workspace-home/components/Bookmark.vue
- apps/web/src/services/workspace-home/components/BookmarkBoard.vue
- apps/web/src/services/workspace-home/components/BookmarkFullMode.vue
- apps/web/src/services/workspace-home/components/BookmarkHeader.vue
- apps/web/src/services/workspace-home/pages/WorkspaceHomePage.vue
- apps/web/src/services/workspace-home/store/workspace-home-page-store.ts
> refactor: refactor bookmark store

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
> Minor CSS issues

- apps/web/src/common/modules/widgets/_components/WidgetFieldDropdownAndMax.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
- apps/web/src/common/modules/widgets/_helpers/widget-field-helper.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldDataField.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldGroupBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
- apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
- apps/web/src/common/modules/widgets/_widgets/pie-chart/widget-config.ts
- apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
> feat: create `getInitialSelectedMenuItem` for widget field

- apps/web/src/common/modules/widgets/_constants/widget-components-constant.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
- apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
> fix: solve small issues

- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
> fix: apply static table sorting

- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
> fix: revert table sorting

- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldDataField.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldGroupBy.vue
- apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
> fix: initValue in dataField & sorting

- apps/web/src/services/preference/components/BookmarkManagementDetailTable.vue
- apps/web/src/services/preference/components/BookmarkManagementTable.vue
- apps/web/src/services/preference/store/bookmark-page-store.ts
- apps/web/src/services/workspace-home/components/BookmarkBoard.vue
- apps/web/src/services/workspace-home/components/BookmarkHeader.vue
- apps/web/src/services/workspace-home/store/workspace-home-page-store.ts
> feat: apply admin bookmark at user mode (UI)

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
- apps/web/src/common/modules/widgets/_constants/data-table-constant.ts
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldDataField.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldGroupBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
> chore: small issues

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
> fix: add clearing data table when CREATING widget deleted

- apps/web/src/common/components/bookmark/store/bookmark-store.ts
- apps/web/src/services/preference/components/WorkspacesCreateModal.vue
> feat: create a default bookmark when creating a workspace

- apps/web/src/services/dashboards/components/DashboardDetailHeader.vue
- apps/web/src/services/dashboards/components/DashboardMainBoardList.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> chore: language issue

- apps/web/src/common/components/bookmark/BookmarkDeleteModal.vue
- apps/web/src/services/preference/components/BookmarkContainer.vue
- apps/web/src/services/preference/components/BookmarkDetailContainer.vue
- apps/web/src/services/preference/components/BookmarkManagementDetailTable.vue
- apps/web/src/services/preference/components/BookmarkManagementTable.vue
- apps/web/src/services/preference/components/BookmarkTree.vue
- apps/web/src/services/preference/constants/bookmark-constant.ts
- apps/web/src/services/preference/pages/admin/AdminBookmarkPage.vue
- apps/web/src/services/preference/store/bookmark-page-store.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
- packages/mirinae/src/data-display/tables/data-table/PDataTable.vue
SSIA
Plz skip the chore commits!
> feat: apply minor qa and fix bugs

- apps/web/src/services/project/components/ProjectAlertEventRuleConditionForm.vue
- apps/web/src/services/project/components/ProjectWebhookTab.vue
- packages/mirinae/.gitignore
> feat: update project feedback issue

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
- apps/web/src/services/asset-inventory/components/MetricExplorerQueryFormSidebar.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
- packages/mirinae/src/layouts/overlay-layout/POverlayLayout.vue
- packages/mirinae/src/layouts/overlay-layout/story-helper.ts
> fix: apply CREATING widget deleting scenario & edit POverlayLayout component

- apps/web/src/common/modules/widgets/_composables/use-granularity-menu-items.ts
> fix: update useGranularityMenuItems hook

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
SSIA
This issue..
https://cloudone-mz.slack.com/archives/C02U6M1L0LX/p1720450277054379
> fix: solve array value field changed-validation issue

- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
> fix: apply widget sorting policy

- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
> fix: apply widget sorting policy (clusterd-column-chart)

- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
> fix: apply clustered-column-chart sorting

- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
> fix: apply table widget sorting

- apps/web/src/services/asset-inventory/components/MetricExplorerLSBMetricTree.vue
> fix: apply metric/metric-example favorite button to metric tree item

- apps/web/src/common/modules/navigations/top-bar/modules/top-bar-header/WorkspaceLogoIcon.vue
- apps/web/src/services/preference/components/BookmarkContainer.vue
- apps/web/src/services/preference/components/BookmarkManagementDetailTable.vue
- apps/web/src/services/preference/components/BookmarkManagementTable.vue
- apps/web/src/services/preference/components/BookmarkTree.vue
- apps/web/src/services/preference/pages/admin/AdminBookmarkDetailPage.vue
- apps/web/src/services/preference/store/bookmark-page-store.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: apply qa issues

- apps/web/src/common/modules/navigations/lsb/type.ts
- apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue
- apps/web/src/services/asset-inventory/components/MetricExplorerLSBMetric.vue
> fix: add load-metric in selecting namespace

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldLineBy.vue
- apps/web/src/services/project/components/ProjectMainProjectCard.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> fix: apply widget overlay close scenario (inactive widget)

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFilters.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardSourceForm.vue
> chore: solve data-table dropdown context menu style issue

- packages/language-pack/ja.json
- packages/language-pack/ko.json
> chore: Add translation

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardHeaderTitle.vue
- apps/web/src/services/cost-explorer/components/DataSourceManagementTabAccessRestriction.vue
- apps/web/src/services/cost-explorer/stores/data-sources-page-store.ts
- apps/web/src/services/cost-explorer/types/data-sources-type.ts
> fix(data-source): apply cost-data-source meta data to cost name & small fix

- apps/web/src/store/reference/project-reference-store.ts
> refactor: add project-group reference store to project-reference store

- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/services/cost-explorer/components/CostAnalysisFiltersAddMoreButton.vue
- apps/web/src/services/cost-explorer/components/CostAnalysisGroupBy.vue
- apps/web/src/services/cost-explorer/stores/cost-analysis-page-store.ts
- packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.stories.mdx
- packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
- packages/mirinae/src/inputs/dropdown/select-dropdown/components/dropdown-button.vue
- packages/mirinae/src/inputs/dropdown/select-dropdown/story-helper.ts
- packages/mirinae/src/inputs/dropdown/select-dropdown/type.ts
> feat: update cost analysis groupby

- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldSubTotal.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTotal.vue
- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
- apps/web/src/common/modules/widgets/_widgets/table/widget-config.ts
> fix: solve table total freeze issue & apply default table total field freeze

- apps/web/src/common/components/custom-date-modal/CustomDateModal.vue
- apps/web/src/common/modules/widgets/_helpers/widget-date-helper.ts
- apps/web/src/services/asset-inventory/components/MetricExplorerChart.vue
- apps/web/src/services/asset-inventory/components/MetricExplorerDataTable.vue
- apps/web/src/services/asset-inventory/components/MetricExplorerDonutChart.vue
- apps/web/src/services/asset-inventory/components/MetricExplorerHorizontalColumnChart.vue
- apps/web/src/services/asset-inventory/components/MetricExplorerLineChart.vue
- apps/web/src/services/asset-inventory/components/MetricExplorerMapChart.vue
echarts is comming to metric explorer!!!!!!
> refactor: change from amcharts to echarts

- apps/web/src/services/preference/pages/admin/AdminDomainSettingsAutoDormancyConfigurationPage.vue
- apps/web/src/services/preference/types/domain-settings-type.ts
- apps/web/src/store/domain-settings/domain-settings-store.ts
> feat: changed domain config name

- apps/web/src/services/preference/components/BookmarkManagementDetailTable.vue
- apps/web/src/services/preference/components/BookmarkManagementTable.vue
- apps/web/src/services/preference/components/WorkspaceManagementTable.vue
- apps/web/src/services/preference/constants/workspace-constant.ts
- apps/web/src/services/preference/pages/admin/AdminDomainSettingsAutoDormancyConfigurationPage.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: create select status at workspace page

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/store/reference/project-reference-store.ts
> fix(widget-overlay): add overlay warning modal trigger (options changed case) & fix project reference store bug

- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldComparison.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldIcon.vue
- apps/web/src/common/modules/widgets/_widgets/number-card/widget-config.ts
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
- apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
> fix: edit number card default optional field value & refactor icon/comparison field

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
- apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
> fix: apply table widget feedback (header sticky, overlay close planning)

- apps/web/src/common/modules/project/ProjectSelectDropdown.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep1.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> fix: apply data-table guide & edit data-table card design 

- apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue
- apps/web/src/services/project/pages/ProjectDetailPage.vue
- apps/web/src/services/project/pages/ProjectDetailTabPage.vue
> chore: style fix

- apps/web/src/services/cost-explorer/components/AnomalyDetectionConfigurationInformation.vue
- apps/web/src/services/cost-explorer/components/AnomalyDetectionConfigurationInformationForm.vue
- apps/web/src/services/cost-explorer/components/AnomalyDetectionConfigurationRecipients.vue
- apps/web/src/services/cost-explorer/components/AnomalyDetectionConfigurationRecipientsForm.vue
- apps/web/src/services/cost-explorer/components/AnomalyDetectionConfigurationTable.vue
- apps/web/src/services/cost-explorer/components/AnomalyDetectionConfigurationTrend.vue
- apps/web/src/services/cost-explorer/components/AnomalyDetectionHistoryDetail.vue
- apps/web/src/services/cost-explorer/components/AnomalyDetectionHistoryTable.vue
- apps/web/src/services/cost-explorer/components/AnomalyDetectionPolicyRuleCard.vue
- apps/web/src/services/cost-explorer/components/CostAnalysisLSB.vue
- apps/web/src/services/cost-explorer/constants/anomaly-detection-constant.ts
- apps/web/src/services/cost-explorer/pages/AnomalyDetectionConfigurationCreatePage.vue
- apps/web/src/services/cost-explorer/pages/AnomalyDetectionConfigurationDetailPage.vue
- apps/web/src/services/cost-explorer/pages/AnomalyDetectionConfigurationPage.vue
- apps/web/src/services/cost-explorer/pages/AnomalyDetectionHistoryDetailPage.vue
- apps/web/src/services/cost-explorer/pages/AnomalyDetectionHistoryPage.vue
- apps/web/src/services/cost-explorer/pages/AnomalyDetectionPolicyPage.vue
- apps/web/src/services/preference/components/BookmarkDetailContainer.vue
- apps/web/src/services/preference/components/BookmarkManagementDetailTable.vue
- apps/web/src/services/preference/components/BookmarkManagementTable.vue
- apps/web/src/services/preference/components/DomainSettingsContainer.vue
- apps/web/src/services/preference/composables/bookmark-data-helper.ts
- apps/web/src/services/preference/constants/workspace-constant.ts
- apps/web/src/services/preference/pages/admin/AdminBookmarkPage.vue
- apps/web/src/services/preference/pages/admin/AdminDomainSettingsAutoDormancyConfigurationPage.vue
> chore: changed mirinae

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
> fix: apply cost-data-source metadata additional_info

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
> fix: apply cost-data-source metadata additional label

- apps/web/src/lib/reference/referenceFieldFormatter.ts
- apps/web/src/lib/reference/referenceRouter.ts
- apps/web/src/schema/identity/service-account/constant.ts
- apps/web/src/schema/identity/service-account/model.ts
- apps/web/src/schema/identity/service-account/type.ts
- apps/web/src/services/asset-inventory/components/ServiceAccountAttachedGeneralAccounts.vue
- apps/web/src/services/asset-inventory/components/ServiceAccountUsageOverview.vue
- apps/web/src/services/asset-inventory/constants/service-account-constant.ts
- apps/web/src/services/asset-inventory/helpers/dynamic-ui-schema-generator/dynamic-layout-schema-template.ts
- apps/web/src/services/asset-inventory/helpers/dynamic-ui-schema-generator/index.ts
- apps/web/src/services/asset-inventory/pages/ServiceAccountDetailPage.vue
- apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: apply dormancy data at service account page

- apps/web/src/schema/identity/workspace/model.ts
- apps/web/src/services/landing/components/LandingAllWorkspaces.vue
- apps/web/src/services/landing/components/LandingContents.vue
- apps/web/src/services/landing/components/LandingRecentVisits.vue
- apps/web/src/services/landing/components/LandingWorkspaceBoard.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
- packages/mirinae/src/data-display/popover/PPopover.vue
> feat: apply dormant state at workspace list landing

- apps/web/src/common/modules/navigations/top-bar/modules/top-bar-header/TopBarWorkspaces.vue
- apps/web/src/schema/identity/workspace/model.ts
- apps/web/src/services/asset-inventory/components/WorkspaceDropdown.vue
- apps/web/src/services/cost-explorer/components/BudgetCreateTargetSelect.vue
- apps/web/src/services/cost-explorer/components/BudgetMainListCard.vue
- apps/web/src/services/cost-explorer/components/CostAnalysisFiltersPopper.vue
- apps/web/src/services/cost-explorer/components/DataSourceManagementTabLinkedAccountTable.vue
- apps/web/src/services/dashboards/components/DashboardVariableDropdown.vue
- apps/web/src/services/iam/components/UserManagementAddAdminRole.vue
- apps/web/src/services/iam/components/UserManagementTabWorkspace.vue
- apps/web/src/services/info/components/NoticeWorkspaceDropdown.vue
- apps/web/src/services/preference/components/BookmarkDetailContainer.vue
- apps/web/src/services/preference/components/BookmarkTree.vue
- apps/web/src/services/preference/composables/refined-table-data.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: apply dormancy state

- apps/web/src/services/preference/pages/admin/AdminDomainSettingsDomainInformationPage.vue
> chore: fixed minor bug

- apps/web/src/services/project/pages/ProjectDetailPage.vue
> chore: add favorite button to project detail header

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFilters.vue
> chore: small fix

- apps/web/src/services/cost-explorer/components/CostAnalysisGroupBy.vue
- apps/web/src/services/cost-explorer/stores/cost-analysis-page-store.ts
> feat: apply cost data source metadata additional_info

- apps/web/src/services/dashboards/components/DashboardWidgetContainerV2.vue
- packages/mirinae/src/inputs/context-menu/context-menu-item/PContextMenuItem.vue
> chore: edit margin of context menu icon 

- apps/web/src/services/asset-inventory/components/ServiceAccountAttachedGeneralAccounts.vue
- apps/web/src/services/asset-inventory/components/ServiceAccountBaseInformationDetail.vue
- apps/web/src/services/asset-inventory/helpers/dynamic-ui-schema-generator/dynamic-layout-schema-template.ts
- apps/web/src/services/asset-inventory/pages/ServiceAccountDetailPage.vue
- apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue
- apps/web/src/services/iam/components/UserManagementTabWorkspace.vue
- apps/web/src/services/preference/components/WorkspaceManagementTable.vue
> chore: apply pr review

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldComparison.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> fix: edit cost-additional-info label planning & table-widget comparison disabled

- apps/web/src/common/modules/widgets/_helpers/widget-field-helper.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldComparison.vue
- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
> feat(table-widget): add total data to comparison field & apply date-field helper to comparison field

- apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> fix: apply multi unit to sub_total & translation

- apps/web/src/common/modules/navigations/lsb/modules/LSBStarredMenuItem.vue
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
- apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
- apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
- packages/mirinae/src/feedbacks/alert/toast-alert/PToastAlert.vue
> chore: edit options/style of widget charts

- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
- apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
- apps/web/src/services/asset-inventory/components/MetricExplorerLineChart.vue
- apps/web/src/services/asset-inventory/pages/MetricExplorerDetailPage.vue
- apps/web/src/services/dashboards/components/DashboardReorderSidebar.vue
- apps/web/src/styles/colorsets.ts
> chore: change colorset of echarts

- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
- apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
> feat: add sorting to table widget

- apps/web/src/App.vue
- apps/web/src/lib/site-initializer/sso.ts
- apps/web/src/router/constant.ts
- apps/web/src/router/external-routes.ts
- apps/web/src/router/helpers/route-helper.ts
- apps/web/src/router/index.ts
- apps/web/src/router/integral-routes.ts
> fix: refactor accessToken process & fix cost-report bug

- apps/web/src/common/modules/widgets/_composables/use-widget-init-and-refresh.ts
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
- apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
- apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
- apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
- apps/web/src/common/modules/widgets/_widgets/progress-card/ProgressCard.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
- apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
- apps/web/src/common/modules/widgets/types/widget-display-type.ts
> fix: remove unnecessary argument of loadWidget & edit loadWidget type

- apps/web/src/services/workspace-home/components/AccountSummary.vue
> chore: apply tooltip

- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
- apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
SSIA
https://github.com/user-attachments/assets/70a99ffc-ab53-4140-9a50-cf853e961aca
> feat: apply pagination to table widget

- apps/web/src/services/cost-explorer/components/CostReportReportsTab.vue
> fix(cost-report): set pageStart, pageLimit on init

- apps/web/src/common/modules/navigations/lsb/modules/LSBCollapsibleMenuItem.vue
- apps/web/src/common/modules/navigations/lsb/modules/LSBTopTitleMenuItem.vue
- apps/web/src/common/modules/navigations/lsb/type.ts
- apps/web/src/services/dashboards/DashboardsLSB.vue
`LSBCollapsibleMenuItem`: `showSubItemCount`
`LSBItem` type: `subText`
> feat: add dashboard count to dashboard LSB & add lsb item spec (subText, showSubItemCount)

- apps/web/src/services/project/pages/ProjectDashboardPage.vue
- apps/web/src/store/dashboard/dashboard-store.ts
> feat: apply project dashboard mechanically

- apps/web/src/lib/menu/menu-info.ts
> feat: update menu highlight tag

- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
> fix: apply Y-Axis desc display

- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/common/modules/widgets/_composables/use-widget-option-validation.ts
- apps/web/src/common/modules/widgets/_constants/widget-field-components-constant.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldPieChartType.vue
- apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
- apps/web/src/common/modules/widgets/_widgets/pie-chart/widget-config.ts
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: add pie chart type option field

- apps/web/src/common/pages/AlertPublicDetailPage.vue
- apps/web/src/router/constant.ts
- apps/web/src/router/external-routes.ts
- apps/web/src/services/alert-manager/components/AlertDetailInfoTable.vue
- apps/web/src/services/alert-manager/constants/alert-constant.ts
> feat: create alertPublicDetailPage component

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep1.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/services/dashboards/components/DashboardReorderSidebar.vue
> feat: set resizer to step2

- apps/web/src/common/modules/widgets/_helpers/widget-date-helper.ts
- apps/web/src/common/pages/CostReportDetailPage.vue
- apps/web/src/services/asset-inventory/components/MetricExplorerLineChart.vue
- apps/web/src/services/asset-inventory/helpers/asset-analysis-data-table-helper.ts
- apps/web/src/services/cost-explorer/components/CostAnalysisChart.vue
- apps/web/src/services/cost-explorer/components/CostAnalysisGroupBy.vue
- apps/web/src/services/cost-explorer/components/CostAnalysisStackedColumnChart.vue
- apps/web/src/services/cost-explorer/components/CostReportMonthlyTotalAmountSummaryCard.vue
- apps/web/src/services/cost-explorer/components/CostReportOverviewCostTrendChart.vue
- apps/web/src/services/cost-explorer/helpers/cost-explorer-chart-data-helper.ts
- apps/web/src/services/cost-explorer/types/cost-analyze-type.ts
> refactor: change from am5 to echarts

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep1.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldLineBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldPieChartType.vue
- apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
- apps/web/src/common/modules/widgets/_widgets/pie-chart/widget-config.ts
- apps/web/src/services/dashboards/components/DashboardReorderSidebar.vue
> chore: change default value of pie chart type & revert

- apps/web/src/services/project/pages/ProjectDashboardPage.vue
- apps/web/src/store/dashboard/dashboard-store.ts
> feat: create project dashboard contents

- apps/web/src/services/dashboards/components/DashboardVariablesV2.vue
- apps/web/src/services/project/pages/ProjectDashboardPage.vue
> feat: set project dashboard variables

- apps/web/src/common/components/scoped-notification/ScopedNotification.vue
- apps/web/src/services/cost-explorer/components/CostAnalysisStackedColumnChart.vue
> fix: fix minor issue

- apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
- apps/web/src/services/project/pages/ProjectDashboardPage.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: create project dashboard empty & remove total comparison percentage in table widget

- apps/web/src/services/cost-explorer/components/BudgetDetailSummaryChart.vue
> refactor(budget): change from am5 to echarts

- apps/web/src/schema/dashboard/_types/dashboard-type.ts
- apps/web/src/schema/dashboard/public-dashboard/api-verbs/share.ts
- apps/web/src/schema/dashboard/public-dashboard/model.ts
- apps/web/src/services/dashboards/components/DashboardDetailHeader.vue
- apps/web/src/services/dashboards/components/DashboardMainBoardList.vue
- apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
- apps/web/src/store/dashboard/dashboard-store.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: add `scope` to dashboard model

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
- apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
- apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
- apps/web/src/common/modules/widgets/types/widget-frame-type.ts
> feat: set `unit` to widget tooltip

- apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
- apps/web/src/services/project/pages/ProjectDashboardPage.vue
> feat: apply project vars to project dashboard

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
> chore: handle no-reference-name case in data table preview

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
- apps/web/src/services/project/pages/ProjectDashboardPage.vue
> fix: apply project_id filter and disable-management to project dashboard

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: set name, description to widget options

- apps/web/src/services/preference/pages/admin/AdminDomainSettingsAnomalyDetectionConfigurationPage.vue
> fix: fix domain config value bug

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
- apps/web/src/common/modules/widgets/_helpers/widget-helper.ts
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
- apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
- apps/web/src/common/modules/widgets/types/widget-model.ts
> feat: apply New timediff

- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts
- apps/web/src/common/modules/widgets/types/widget-display-type.ts
- apps/web/src/common/modules/widgets/types/widget-model.ts
- apps/web/src/schema/dashboard/private-widget/api-verbs/create.ts
- apps/web/src/schema/dashboard/public-widget/api-verbs/create.ts
- apps/web/src/services/dashboards/components/DashboardWidgetContainerV2.vue
- apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat(dashboard): create widget clone

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
> fix: solve widget form valid-map issue

- apps/web/src/services/project/components/ProjectDetailTab.vue
- apps/web/src/services/project/components/ProjectWebhookTab.vue
- apps/web/src/services/project/pages/ProjectDetailTabPage.vue
- apps/web/src/services/project/stores/project-detail-page-store.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: apply changed plan at webhook main page

- apps/web/src/schema/monitoring/event-rule/api-verbs/create.ts
- apps/web/src/services/project/components/ProjectAlertEventRuleActionForm.vue
- apps/web/src/services/project/components/ProjectAlertEventRuleConditionForm.vue
- apps/web/src/services/project/components/ProjectAlertEventRuleForm.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: apply changed design at event rule form

- apps/web/src/services/my-page/components/NotificationAddForm.vue
- apps/web/src/services/my-page/components/NotificationAddFormData.vue
- apps/web/src/services/my-page/components/NotificationAddMemberGroup.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: apply radio group at project notification

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
> chore(widget-form): solve small issues

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
- apps/web/src/services/dashboards/components/DashboardWidgetContainerV2.vue
> chore: apply new widget title to widget-clone & small fix

- apps/web/src/schema/monitoring/webhook/model.ts
- apps/web/src/services/project/components/ProjectAlertEventRuleConditionForm.vue
- apps/web/src/services/project/components/ProjectAlertEventRuleForm.vue
- apps/web/src/services/project/components/ProjectAlertWebhookTab.vue
- apps/web/src/services/project/pages/ProjectDetailTabPage.vue
> feat: preparation for API integration

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
- apps/web/src/common/modules/widgets/types/widget-model.ts
> feat: apply new plan about timediff (day is deprecated)

- apps/web/src/services/project/components/ProjectAlertWebhookCreateStep2.vue
- apps/web/src/services/project/pages/ProjectAlertWebhookCreatePage.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: apply metadata API

- apps/web/src/services/project/components/ProjectAlertWebhookCreateStep2.vue
- apps/web/src/services/project/components/ProjectAlertWebhookUpdateModal.vue
- apps/web/src/services/project/pages/ProjectDetailTabPage.vue
SSIA
- add version
- add WebhookId, Plugin cols
> feat: apply changed design

- apps/web/src/services/iam/components/UserManagementAddModal.vue
- apps/web/src/services/iam/components/UserManagementAddPassword.vue
- apps/web/src/services/iam/components/UserManagementAddUser.vue
- apps/web/src/services/iam/constants/user-constant.ts
- apps/web/src/services/iam/types/user-type.ts
> feat: remove email format when adding users

- apps/web/src/services/project/components/ProjectAlertWebhookCreateStep2.vue
> chore: hide metadata option_schema

- apps/web/src/services/asset-inventory/components/MetricExplorerDonutChart.vue
- apps/web/src/services/asset-inventory/components/MetricExplorerHorizontalColumnChart.vue
- apps/web/src/services/asset-inventory/components/MetricExplorerLineChart.vue
- apps/web/src/services/asset-inventory/components/MetricExplorerMapChart.vue
- apps/web/src/services/dashboards/components/DashboardDetailHeader.vue
- apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
> feat: delete `DASHBOARD_EDITABLE_DOMAINS` config

- apps/web/src/services/asset-inventory/components/MetricExplorerDonutChart.vue
- apps/web/src/services/asset-inventory/components/MetricExplorerHorizontalColumnChart.vue
- apps/web/src/services/asset-inventory/components/MetricExplorerLineChart.vue
- apps/web/src/services/asset-inventory/components/MetricExplorerMapChart.vue
> fix: fix metric chart bug

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
- apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
- apps/web/src/services/dashboards/components/DashboardWidgetContainerV2.vue
> feat: apply new timediff expression plan

- apps/web/src/services/workspace-home/components/AssetSummaryProvider.vue
> feat: apply sort

- apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue
> feat: hide starred section from admin metric

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
- apps/web/src/services/dashboards/DashboardsLSB.vue
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> fix: fix minor of title, description in step2

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
> fix: fix error modal message

- apps/web/src/common/modules/custom-table/custom-field-modal/CustomFieldModal.vue
- apps/web/src/common/pages/AlertPublicDetailPage.vue
- apps/web/src/services/alert-manager/components/AlertMainDataTable.vue
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> fix: fix minor qa bug & add redirection case if user login

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
- apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldDataField.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetHeaderField.vue
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
- apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
- apps/web/src/schema/dashboard/private-dashboard/model.ts
- apps/web/src/schema/dashboard/private-widget/api-verbs/create.ts
- apps/web/src/schema/dashboard/private-widget/api-verbs/update.ts
- apps/web/src/schema/dashboard/public-dashboard/model.ts
- apps/web/src/schema/dashboard/public-widget/api-verbs/create.ts
- apps/web/src/schema/dashboard/public-widget/api-verbs/update.ts
- apps/web/src/services/dashboards/components/DashboardDetailHeader.vue
- apps/web/src/services/dashboards/components/DashboardMainBoardList.vue
- apps/web/src/services/dashboards/components/DashboardWidgetContainerV2.vue
> feat: add widget header field

- apps/web/src/services/dashboards/components/DashboardVariablesV2.vue
- apps/web/src/services/project/pages/ProjectDashboardPage.vue
> fix: solve project dashboard issue

- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/services/project/pages/ProjectDashboardPage.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> chore: translation & small fix

- apps/web/src/services/my-page/components/NotificationAddFormData.vue
- apps/web/src/services/my-page/components/NotificationChannelItemData.vue
- apps/web/src/services/project/pages/ProjectDetailTabPage.vue
- apps/web/src/store/reference/plugin-reference-store.ts
- apps/web/src/store/reference/type.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: apply docs empty case

- apps/web/src/common/modules/widgets/_helpers/widget-date-helper.ts
- apps/web/src/services/asset-inventory/components/MetricExplorerChart.vue
- apps/web/src/services/asset-inventory/components/MetricExplorerDonutChart.vue
- apps/web/src/services/asset-inventory/components/MetricExplorerHorizontalColumnChart.vue
- apps/web/src/services/asset-inventory/components/MetricExplorerLineChart.vue
- apps/web/src/services/asset-inventory/components/MetricExplorerMapChart.vue
- apps/web/src/services/cost-explorer/components/CostAnalysisChart.vue
- apps/web/src/services/cost-explorer/components/CostAnalysisGroupBy.vue
- apps/web/src/services/cost-explorer/components/CostAnalysisStackedColumnChart.vue
- apps/web/src/services/cost-explorer/stores/cost-analysis-page-store.ts
> fix: fix additional info keys & etc

- apps/web/src/schema/repository/plugin/model.ts
- apps/web/src/services/project/components/ProjectAlertWebhookCreateStep1.vue
- apps/web/src/services/project/components/ProjectAlertWebhookCreateStep2.vue
- apps/web/src/services/project/components/ProjectAlertWebhookCreatedModal.vue
- apps/web/src/services/project/pages/ProjectDetailTabPage.vue
- apps/web/src/services/project/stores/project-detail-page-store.ts
- apps/web/src/store/reference/plugin-reference-store.ts
- apps/web/src/store/reference/type.ts
> feat: apply markdown

- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
- apps/web/src/services/project/pages/ProjectDashboardPage.vue
> fix: solve some problems

- apps/web/src/services/dashboards/components/DashboardWidgetContainerV2.vue
> chore: apply changed widget title, description

- apps/web/src/common/modules/widgets/_widget-fields/WidgetHeaderField.vue
- apps/web/src/schema/dashboard/private-dashboard/model.ts
- apps/web/src/schema/dashboard/private-widget/model.ts
- apps/web/src/schema/dashboard/public-dashboard/model.ts
- apps/web/src/schema/dashboard/public-widget/model.ts
- apps/web/src/services/dashboards/helpers/dashboard-share-helper.ts
- apps/web/src/services/dashboards/types/shared-dashboard-type.ts
> fix: update models & fix widget header validation 

- apps/web/src/services/dashboards/components/DashboardWidgetContainerV2.vue
> chore: apply widget header value to widget-clone

- apps/web/src/services/dashboards/components/DashboardDetailHeader.vue
> chore: edit wrong project share case

- apps/web/src/services/asset-inventory/components/MetricExplorerChart.vue
> fix: fix metric critical issue

- apps/web/src/services/project/components/ProjectAlertWebhookCreateStep1.vue
- apps/web/src/services/project/components/ProjectAlertWebhookTab.vue
> feat: apply minor feedback

- apps/web/src/services/my-page/components/NotificationChannelItemSchedule.vue
- apps/web/src/services/project/components/ProjectAlertEventRuleActionForm.vue
- packages/mirinae/src/feedbacks/modals/button-modal/PButtonModal.vue
> fix: fixed bug at webhook/notification

- apps/web/src/services/project/pages/ProjectDashboardPage.vue
> feat: get legacy project dashboard

- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: update design of widget frame buttons

- apps/web/src/services/dashboards/components/DashboardDetailHeader.vue
- apps/web/src/services/dashboards/components/DashboardMainBoardList.vue
> chore: hide 'share to project' button from dashboard

- apps/web/src/common/modules/widgets/_constants/widget-field-components-constant.ts
- apps/web/src/common/modules/widgets/_constants/widget-field-constant.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldDateFormat.vue
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
- apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
> feat(widget-field): create date format field

- apps/web/src/common/modules/widgets/_constants/widget-field-constant.ts
- apps/web/src/common/modules/widgets/_helpers/widget-date-helper.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldDateFormat.vue
- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
- apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
- apps/web/src/common/modules/widgets/_widgets/table/widget-config.ts
- apps/web/src/common/modules/widgets/types/widget-data-table-type.ts
- apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
> feat: apply date format to Table widget

- apps/web/src/lib/reference/referenceRouter.ts
> chore: update project dashboard route

- apps/web/src/services/cost-explorer/stores/cost-analysis-page-store.ts
> fix(cost-analysis): handle `additional_info` empty case

- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldDateFormat.vue
- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
- apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
> fix: edit date format field value

- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts
- apps/web/src/common/modules/widgets/_constants/widget-field-components-constant.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldAbbreviation.vue
- apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
- apps/web/src/common/modules/widgets/_widgets/number-card/widget-config.ts
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
- apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
- apps/web/src/common/modules/widgets/types/widget-frame-type.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: add `abbreviation` field

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
- apps/web/src/common/modules/widgets/_widgets/heatmap/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
- apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
- apps/web/src/common/modules/widgets/_widgets/pie-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
- apps/web/src/common/modules/widgets/_widgets/treemap/widget-config.ts
- apps/web/src/common/modules/widgets/types/widget-frame-type.ts
- apps/web/src/services/dashboards/components/DashboardMainBoardList.vue
- apps/web/src/services/dashboards/components/DashboardReorderSidebar.vue
> feat: apply date format field to widgets

- apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
> fix: fix etc bug in pie chart

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
> fix: handle `additional_info` empty case

- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
> chore: show widget description

- apps/web/src/services/cost-explorer/stores/cost-analysis-page-store.ts
> chore(cost-analysis): apply additional-info-keys group by to admin mode

- apps/web/src/services/cost-explorer/types/cost-explorer-chart-type.ts
- apps/web/src/services/workspace-home/components/CostSummary.vue
- apps/web/src/services/workspace-home/components/CostSummaryChart.vue
- apps/web/src/services/workspace-home/components/Summaries.vue
- apps/web/src/services/workspace-home/composables/use-workspace-home.ts
- apps/web/src/services/workspace-home/constants/workspace-home-constant.ts
- apps/web/src/services/workspace-home/types/workspace-home-type.ts
> feat: apply chart data at cost summary chart

- apps/web/src/common/modules/widgets/_widget-fields/WidgetHeaderField.vue
> chore: fix update bug of widget title

- apps/web/src/services/workspace-home/components/CostSummary.vue
> chore: apply project id

- apps/web/src/schema/identity/workspace/api-verbs/update.ts
- apps/web/src/services/advanced/components/WorkspaceTagManagementTabContents.vue
- apps/web/src/services/advanced/components/WorkspacesUserManagementTab.vue
> feat: add tag tab  to workspaceManagementTab

- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/widget-config.ts
> chore(widget): edit max count of stackBy

- apps/web/src/common/modules/widgets/_helpers/widget-helper.ts
Group By Sorting
- As is : Date > Group By ascending sorting (a, b, c...)
- To be : Date > Group By order by selecting
> fix(widget-field): apply changed group by sorting

- apps/web/src/common/modules/widgets/_constants/widget-field-components-constant.ts
- apps/web/src/common/modules/widgets/_constants/widget-field-constant.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldNumberFormat.vue
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
- apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
- package-lock.json
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
- packages/utils/package.json
- packages/utils/src/index.ts
> feat: add "Number Format" widget field

- apps/web/src/services/asset-inventory/pages/MetricExplorerMainPage.vue
> chore: fix link

- apps/web/src/services/workspace-home/components/CostSummaryChart.vue
> fix: fixed chart bug

- apps/web/src/services/iam/components/UserManagementAddUser.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> fix: fixed id format validation

- apps/web/src/common/modules/widgets/_constants/widget-field-components-constant.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldDisplayAnnotation.vue
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
- apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: add `Display Annotation` widget field

- apps/web/src/services/asset-inventory/helpers/dynamic-ui-schema-generator/index.ts
- apps/web/src/services/auth/pages/SamlRedirectPage.vue
> fix: fix build file path & fix saml login error flow

- packages/mirinae/src/components.ts
- packages/mirinae/src/inputs/slider/PSlider.mdx
- packages/mirinae/src/inputs/slider/PSlider.stories.ts
- packages/mirinae/src/inputs/slider/PSlider.vue
- packages/mirinae/src/inputs/slider/story-helper.ts
> feat: add `PSlider` component

- apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCard.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardHeaderTitle.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep1.vue
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
- Add `Apply All` button to Widget form step1
- Change `data-table` load condition
- Add `all-data-table-validation` for `Apply All` button disabled
- Refactor `data-table` reference-updating condition
> feat: add `Apply All` button & apply new planning about `Apply All`

- apps/web/src/common/modules/widgets/_constants/widget-field-components-constant.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldComparison.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldDisplaySeriesLabel.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
- apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
- apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
- packages/mirinae/src/inputs/slider/PSlider.vue
> feat: add `Display Series Label` field 

- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldDisplayAnnotation.vue
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/gauge/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/geo-map/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/heatmap/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/line-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/number-card/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/pie-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/progress-card/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/table/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/treemap/widget-config.ts
- apps/web/src/common/modules/widgets/types/widget-frame-type.ts
> feat: set `displayAnnotation` field to all widgets

- apps/web/src/services/dashboards/components/DashboardControlButtons.vue
- apps/web/src/services/dashboards/components/DashboardDetailHeader.vue
- apps/web/src/services/dashboards/components/DashboardLabels.vue
- apps/web/src/services/dashboards/components/DashboardLabelsButton.vue
- apps/web/src/services/dashboards/components/DashboardRefreshDropdown.vue
- apps/web/src/services/dashboards/components/DashboardToolsetDateDropdown.vue
- apps/web/src/services/dashboards/components/DashboardVariablesV2.vue
- apps/web/src/services/dashboards/pages/DashboardDetailPage.vue
SSIA
https://github.com/user-attachments/assets/bbcf7801-6a6a-4ff4-9a30-47a4a1f7c70f
> feat(dashbaord): create new fixed dashboard header

- apps/web/src/common/modules/widgets/_helpers/widget-date-helper.ts
- apps/web/src/common/modules/widgets/_helpers/widget-helper.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldNumberFormat.vue
- apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
- apps/web/src/common/modules/widgets/_widgets/gauge/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
- apps/web/src/common/modules/widgets/_widgets/number-card/widget-config.ts
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
> feat(number-card/gauge): apply numberFormat field 

- apps/web/src/services/asset-inventory/pages/admin/AdminCollectorHistoryPage.vue
> fix: add apiQueryHelper logic

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
- apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
- apps/web/src/common/modules/widgets/_widgets/table/widget-config.ts
> feat: apply number format field to Table widget 

- apps/web/src/common/modules/widgets/_constants/widget-field-components-constant.ts
- apps/web/src/common/modules/widgets/_constants/widget-field-constant.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldDataFieldHeatmapColor.vue
- apps/web/src/common/modules/widgets/_widgets/table/widget-config.ts
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
- apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: create data-field-heatmap-color field component

- apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
> chore: solve table number-formatting issue

- apps/web/src/common/modules/portals/HandbookButton.vue
- apps/web/src/services/iam/components/RoleUpdateFormAccess.vue
- apps/web/src/services/iam/components/RoleUpdateFormBaseInformation.vue
- apps/web/src/services/iam/components/RoleUpdateFormPermissionForm.vue
- apps/web/src/services/iam/components/RoleUpdateFormRoleType.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: add read-only permissions (mark-up)

- apps/web/src/services/advanced/components/WorkspaceGroupHeader.vue
- apps/web/src/services/advanced/components/WorkspaceGroupTab.vue
- apps/web/src/services/advanced/components/WorkspaceGroupTabGroupUser.vue
- apps/web/src/services/advanced/components/WorkspaceGroupTable.vue
- apps/web/src/services/advanced/components/WorkspaceGroupTableToolbox.vue
- apps/web/src/services/advanced/constants/workspace-group-constant.ts
- apps/web/src/services/advanced/pages/admin/AdminWorkspaceGroupPage.vue
- packages/language-pack/en.json
https://github.com/cloudforet-io/console/pull/4504
SSIA
Sorry, I deleted the branch before it merged.
> feat: markup workspace group page header, table 

- apps/web/src/common/modules/widgets/_constants/widget-field-constant.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldDataFieldHeatmapColor.vue
- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
- apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
- apps/web/src/lib/helper/color-convert-helper.ts
- Apply `dataFieldHeatmapColor` field to Table Widget
- Create `hexToRgba` helper
> feat: apply data-field-heatmap-color to Table widget 

- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
- apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
- ASIS: Total data is current page total
- TOBE: Total data is full page total
> feat(table-widget): create full page total data

- apps/web/src/lib/reference/referenceRouter.ts
- apps/web/src/services/asset-inventory/components/CollectorHistoryJobTaskTable.vue
> feat: update project reference router

- apps/web/src/common/modules/widgets/_constants/widget-field-constant.ts
- apps/web/src/common/modules/widgets/_helpers/widget-helper.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldNumberFormat.vue
- apps/web/src/services/dashboards/components/DashboardDetailHeader.vue
- apps/web/src/services/dashboards/components/DashboardLabelsButton.vue
> fix: some QAs

- apps/web/src/common/components/inputs/ColorInput.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/services/dashboards/components/DashboardToolsetDateDropdown.vue
- apps/web/src/services/dashboards/components/DashboardVariablesV2.vue
- apps/web/src/services/dashboards/components/WidgetFullModeModal.vue
- apps/web/src/services/dashboards/pages/DashboardDetailPage.vue
- Dashboard Detail Page: new design
- Widget Form: old design (rollback)
> fix: rollback dashboard header items

- apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-profile/TopBarProfile.vue
> fix: fix avatar display condition on GNB

- apps/web/src/services/advanced/components/WorkspaceGroupAddUsersModal.vue
- apps/web/src/services/advanced/components/WorkspaceGroupAddWorkspacesModal.vue
- apps/web/src/services/advanced/components/WorkspaceGroupCreateModal.vue
- apps/web/src/services/advanced/components/WorkspaceGroupDeleteModal.vue
- apps/web/src/services/advanced/components/WorkspaceGroupDeleteStatusModal.vue
- apps/web/src/services/advanced/components/WorkspaceGroupEditModal.vue
- apps/web/src/services/advanced/components/WorkspaceGroupHeader.vue
- apps/web/src/services/advanced/components/WorkspaceGroupTab.vue
- apps/web/src/services/advanced/components/WorkspaceGroupTabGroupUser.vue
- apps/web/src/services/advanced/components/WorkspaceGroupTabWorkspace.vue
- apps/web/src/services/advanced/components/WorkspaceGroupTable.vue
- apps/web/src/services/advanced/components/WorkspaceGroupTableToolbox.vue
- apps/web/src/services/advanced/constants/workspace-group-constant.ts
- apps/web/src/services/advanced/pages/admin/AdminWorkspaceGroupPage.vue
- apps/web/src/services/advanced/store/workspace-group-page-store.ts
- packages/language-pack/en.json
> feat: markup workspace group page(tab, modals)

- .gitignore
- packages/mirinae/package.json
> fix(mirinae): fix build output options

- apps/web/src/services/asset-inventory/pages/CloudServiceDetailPage.vue
- packages/mirinae/src/data-display/dynamic/dynamic-layout/type/layout-schema.ts
> feat: add defaultFilter spec to CloudServiceDetailPage

- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
> chore: rollback sm widget height

- vercel.json
> fix: update vercel.json

- apps/web/src/common/modules/widgets/_constants/widget-field-constant.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldDisplaySeriesLabel.vue
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
- apps/web/src/common/modules/widgets/_widgets/pie-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/widget-config.ts
- apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
> feat: apply `DisplaySeriesLabel` to widgets

- apps/web/src/services/asset-inventory/components/CollectorBaseInfoSection.vue
- apps/web/src/services/asset-inventory/components/CollectorCollectorStep2.vue
- apps/web/src/services/asset-inventory/components/CollectorCreateMultipleProviderForm.vue
- apps/web/src/services/asset-inventory/components/CollectorCreateStep1.vue
- apps/web/src/services/asset-inventory/components/CollectorCreateStep1SearchFilter.vue
- apps/web/src/services/asset-inventory/components/CollectorCreateStep3.vue
- apps/web/src/services/asset-inventory/components/CollectorCreateStep4.vue
- apps/web/src/services/asset-inventory/components/CollectorDetailAttachedServiceAccounts.vue
- apps/web/src/services/asset-inventory/components/CollectorDetailNameEditModal.vue
- apps/web/src/services/asset-inventory/components/CollectorDetailOptionsSection.vue
- apps/web/src/services/asset-inventory/components/CollectorDetailScheduleSection.vue
- apps/web/src/services/asset-inventory/components/CollectorDetailServiceAccountsSection.vue
- apps/web/src/services/asset-inventory/components/CollectorFormAttachedServiceAccount.vue
- apps/web/src/services/asset-inventory/components/CollectorFormName.vue
- apps/web/src/services/asset-inventory/components/CollectorFormOptions.vue
- apps/web/src/services/asset-inventory/components/CollectorFormSchedule.vue
- apps/web/src/services/asset-inventory/components/CollectorFormTag.vue
- apps/web/src/services/asset-inventory/components/CollectorFormVersion.vue
- apps/web/src/services/asset-inventory/components/CollectorMainScheduleModal.vue
- apps/web/src/services/asset-inventory/pages/CollectorDetailPage.vue
- apps/web/src/services/asset-inventory/pages/admin/AdminCollectorDetailPage.vue
- apps/web/src/services/asset-inventory/stores/collector-detail-page-store.ts
- apps/web/src/services/asset-inventory/stores/collector-form-store.ts
> refactor(collector-form-store): change to setup script

- apps/web/src/services/iam/components/RoleManagementTabDetail.vue
- apps/web/src/services/iam/components/RoleUpdateFormAccess.vue
- apps/web/src/services/iam/components/RoleUpdateFormPermissionForm.vue
- apps/web/src/services/iam/helpers/role-page-access-menu-list.ts
- apps/web/src/services/iam/types/role-type.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: changed permissions design at role create page

- apps/web/src/services/asset-inventory/components/CollectorCreateFormRule.vue
- apps/web/src/services/asset-inventory/components/CollectorCreateStep3.vue
- apps/web/src/services/asset-inventory/stores/collector-form-store.ts
- apps/web/src/services/asset-inventory/types/type.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: apply collectorCreateFormRule markup

- apps/web/src/services/iam/components/RoleManagementTabDetail.vue
- apps/web/src/services/iam/components/RoleUpdateFormAccess.vue
- apps/web/src/services/iam/types/role-type.ts
> feat: apply changed design at role detail table

- apps/web/src/services/info/pages/admin/AdminNoticeDetailPage.vue
> chore: add visible case

- vercel.json
> feat: add rewrites option to vercel.json

- apps/web/src/common/modules/widgets/_constants/widget-field-components-constant.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableColumnWidth.vue
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
- apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
> feat(widget-field): create table-column-width field

- apps/web/src/common/modules/widgets/_helpers/widget-helper.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/widget-config.ts
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
- apps/web/src/services/dashboards/pages/DashboardDetailPage.vue
> feat: add hide option to `ConfigurableDataField`

- apps/web/src/common/modules/widgets/_helpers/widget-date-helper.ts
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/widget-config.ts
- apps/web/src/common/modules/widgets/types/widget-data-type.ts
> feat: set `TableDataField` to LineChart

- apps/web/src/services/asset-inventory/pages/CloudServiceDetailPage.vue
> fix: initialize search tag according to cloudServiceName

- apps/web/src/common/modules/widgets/_constants/widget-field-components-constant.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldCustomTableColumnWidth.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableColumnWidth.vue
- apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
> feat(widget-field): create custom-table-column-width field

- apps/web/src/services/asset-inventory/pages/CloudServiceDetailPage.vue
- packages/mirinae/src/data-display/dynamic/dynamic-layout/type/layout-schema.ts
> feat(feature-default-filter): merge to master

- apps/web/src/common/modules/widgets/_constants/widget-field-constant.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldCustomTableColumnWidth.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableColumnWidth.vue
- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
- apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
- apps/web/src/common/modules/widgets/_widgets/table/widget-config.ts
> feat(table-widget): apply column-width fields to Table widget 

- apps/web/src/services/asset-inventory/components/MetricExplorerHeader.vue
> fix: solve metric duplicate error in admin mode

- apps/web/src/common/modules/widgets/_constants/widget-field-constant.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldDisplaySeriesLabel.vue
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
- apps/web/src/common/modules/widgets/_widgets/pie-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
- apps/web/src/common/modules/widgets/_widgets/treemap/widget-config.ts
- apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
> feat: apply `numberFormat`, `displaySeriesLabel` to widgets

- apps/web/src/services/landing/components/LandingContents.vue
- apps/web/src/services/landing/components/LandingRecentVisits.vue
- apps/web/src/services/landing/components/LandingWorkspaceRecentList.vue
> feat(landing-recent-visits): apply new design

- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
- apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
- apps/web/src/common/modules/widgets/_widgets/table/widget-config.ts
> feat(table-widget): apply text-wrap field

- apps/web/src/schema/identity/workspace-group/api-verbs/create.ts
- apps/web/src/schema/identity/workspace-group/api-verbs/delete.ts
- apps/web/src/schema/identity/workspace-group/api-verbs/list.ts
- apps/web/src/schema/identity/workspace-group/api-verbs/update.ts
- apps/web/src/schema/identity/workspace-group/model.ts
- apps/web/src/services/landing/components/LandingAllWorkspaces.vue
- apps/web/src/services/landing/components/LandingContents.vue
- apps/web/src/services/landing/components/LandingGroupWorkspaces.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
- packages/mirinae/src/navigation/tabs/button-tab/PButtonTab.vue
- packages/mirinae/src/navigation/tabs/button-tab/story-helper.ts
> feat: add base markup to landing page

- apps/web/src/services/landing/components/LandingGroupWorkspaces.vue
- apps/web/src/services/landing/components/LandingWorkspaceRecentList.vue
- packages/mirinae/src/navigation/tabs/button-tab/PButtonTab.vue
https://github.com/user-attachments/assets/bea830fc-6b4c-44a0-bc13-9897fb3dbaa5
> feat: add x-scroll & group-button-list toggle button

- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldLegend.vue
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
- apps/web/src/common/modules/widgets/_widgets/geo-map/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
- apps/web/src/common/modules/widgets/_widgets/pie-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
- apps/web/src/common/modules/widgets/_widgets/table/widget-config.ts
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
- apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
right or bottom position of legend
> feat: set legend position to pie chart

- apps/web/src/services/cost-explorer/components/CostAnalysisChart.vue
- apps/web/src/services/cost-explorer/components/CostAnalysisStackedColumnChart.vue
> fix(cost-analysis): fix daily accumulated chart

- apps/web/src/schema/identity/workspace-group-details/api-verbs/add-users.ts
- apps/web/src/schema/identity/workspace-group-details/api-verbs/add-workspaces.ts
- apps/web/src/schema/identity/workspace-group-details/api-verbs/delete.ts
- apps/web/src/schema/identity/workspace-group-details/api-verbs/find-users.ts
- apps/web/src/schema/identity/workspace-group-details/api-verbs/get-workspace-groups.ts
- apps/web/src/schema/identity/workspace-group-details/api-verbs/remove-users.ts
- apps/web/src/schema/identity/workspace-group-details/api-verbs/remove-workspaces.ts
- apps/web/src/schema/identity/workspace-group-details/api-verbs/update.ts
- apps/web/src/schema/identity/workspace-group-details/model.ts
- apps/web/src/schema/identity/workspace-group/api-verbs/create.ts
- apps/web/src/schema/identity/workspace-group/model.ts
- apps/web/src/services/advanced/components/WorkspaceGroupCreateModal.vue
- apps/web/src/services/advanced/composables/use-select-drop-down-list.ts
- apps/web/src/services/advanced/store/workspace-group-page-store.ts
- apps/web/src/services/landing/components/LandingContents.vue
- apps/web/src/services/landing/components/LandingGroupWorkspaces.vue
- apps/web/src/services/landing/components/LandingWorkspaceGroupManageOverlay.vue
- apps/web/src/services/landing/components/LandingWorkspaceGroupTab.vue
- apps/web/src/services/landing/components/LandingWorkspaceGroupTabGroupUser.vue
- apps/web/src/services/landing/components/LandingWorkspaceGroupTabWorkspace.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: add workspaceGroupManageTab markup

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
- apps/web/src/common/modules/widgets/_helpers/widget-date-helper.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
- apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
- Add dynamically generated field dropdown
- Add widget props (`widgetId`, `dateRange`)
> feat(table-data-field): create dynamic field dropdown with dynamic generating

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/services/dashboards/components/DashboardCloneModal.vue
- apps/web/src/services/dashboards/components/DashboardDetailHeader.vue
- apps/web/src/services/dashboards/components/DashboardVariablesV2.vue
- apps/web/src/services/dashboards/stores/dashboard-create-page-store.ts
- apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
- packages/mirinae/src/feedbacks/modals/button-modal/PButtonModal.vue
[[Major][Dashboard] 대시보드 코드로 공유 > 코드가 길어지면 모달창이 탑바에 가려짐](https://mzdevs.atlassian.net/browse/MZ00003-1018)
[[Minor][Dashboard] 대시보드 필터 선택시 초기화 버튼 비활성화](https://mzdevs.atlassian.net/browse/MZ00003-1019)
[[Critical][Dashboard] Variable 반영 / 저장 이슈](https://mzdevs.atlassian.net/browse/MZ00003-1021)
[[Minor] Dashboard > 어드민이 공유한 대시보드 복제 불가](https://mzdevs.atlassian.net/browse/MZ00003-919)
> fix: fix reset bug in widget overlay

- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
- ASIS: generate dynamic field from real data
- TOBE: generate dynamic field by field option value (`tableDataField.dynamicFieldValue`)
> feat(table): apply new dynamic field to Table

- apps/web/src/schema/identity/workspace-group/api-verbs/add-users.ts
- apps/web/src/services/advanced/components/WorkspaceGroupAddUsersModal.vue
- apps/web/src/services/advanced/components/WorkspaceGroupAddWorkspacesModal.vue
- apps/web/src/services/advanced/components/WorkspaceGroupCreateModal.vue
- apps/web/src/services/advanced/components/WorkspaceGroupDeleteModal.vue
- apps/web/src/services/advanced/components/WorkspaceGroupDeleteStatusModal.vue
- apps/web/src/services/advanced/components/WorkspaceGroupEditModal.vue
- apps/web/src/services/advanced/components/WorkspaceGroupTabGroupUser.vue
- apps/web/src/services/advanced/components/WorkspaceGroupTable.vue
- apps/web/src/services/advanced/composables/use-select-drop-down-list.ts
- apps/web/src/services/advanced/pages/admin/AdminWorkspaceGroupPage.vue
- apps/web/src/services/advanced/store/workspace-group-page-store.ts
- apps/web/src/store/reference/workspace-group-reference-store.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: apply userUsers api

- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
> chore: solve table etc data issue

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldColorSchema.vue
- apps/web/src/services/dashboards/components/DashboardToolsetDateDropdown.vue
- apps/web/src/services/dashboards/components/DashboardVariablesV2.vue
> chore: add circle marker to color schema field

- apps/web/src/services/asset-inventory/constants/asset-analysis-constant.ts
> fix: fix operator of metric average

- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts
- apps/web/src/common/modules/widgets/_constants/widget-field-components-constant.ts
- apps/web/src/common/modules/widgets/_constants/widget-field-constant.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldWidgetHeight.vue
- apps/web/src/common/modules/widgets/_widgets/number-card/widget-config.ts
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
- apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
- apps/web/src/common/modules/widgets/types/widget-frame-type.ts
- Add widget-height field
- Add `WidgetOptions` to  `WidgetFrameProps`
- Edit default height of full size widget
> feat: create widget-height field and apply & edit WidgetFrameProps

- apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCard.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFooter.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardLoadingContents.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep1.vue
- apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldDataFieldHeatmapColor.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldNumberFormat.vue
- apps/web/src/common/modules/widgets/types/widget-model.ts
- Edit gap of multi-data-field field
- Add data-table loading & create data-table skeleton card
- etc..
> fix(dashboard): solve some QA

- apps/web/src/lib/access-control/config.ts
- apps/web/src/lib/access-control/page-access-helper.ts
- apps/web/src/services/advanced/components/BookmarkDetailContainer.vue
- apps/web/src/services/advanced/components/BookmarkManagementDetailTable.vue
- apps/web/src/services/advanced/components/BookmarkManagementTable.vue
- apps/web/src/services/advanced/components/WorkspaceManagementTable.vue
- apps/web/src/services/advanced/components/WorkspaceTagManagementTabContents.vue
- apps/web/src/services/advanced/components/WorkspacesUserManagementTab.vue
- apps/web/src/services/advanced/pages/admin/AdminBookmarkPage.vue
- apps/web/src/services/advanced/pages/admin/AdminDomainSettingsAppearancePage.vue
- apps/web/src/services/advanced/pages/admin/AdminDomainSettingsAutoDormancyConfigurationPage.vue
- apps/web/src/services/advanced/pages/admin/AdminDomainSettingsDomainInformationPage.vue
- apps/web/src/services/advanced/pages/admin/AdminWorkspacesPage.vue
- apps/web/src/services/iam/components/RoleManagementTabDetail.vue
- apps/web/src/services/iam/components/RoleUpdateFormAccess.vue
- apps/web/src/services/iam/components/RoleUpdateFormPermissionForm.vue
- apps/web/src/services/iam/helpers/role-page-access-menu-list.ts
- apps/web/src/services/info/pages/admin/AdminNoticeDetailPage.vue
- apps/web/src/services/info/pages/admin/AdminNoticeMainPage.vue
- apps/web/src/store/modules/user/getters.ts
The page permission implementation is the same as in the previous PR.
> chore: changed name and apply read_write access

- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldLegend.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldMissingValue.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldNumberFormat.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
- apps/web/src/services/dashboards/components/DashboardToolsetDateDropdown.vue
> feat: change value type of Missing Value

- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldCustomTableColumnWidth.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldSubTotal.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableColumnWidth.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTextWrap.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldWidgetHeight.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> fix: apply changed sub-total planning & field translation

- apps/web/src/common/modules/widgets/_helpers/widget-date-helper.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldMissingValue.vue
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
> feat: apply dynamic field value to widgets

- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
- apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
- apps/web/src/common/modules/widgets/_widgets/table/widget-config.ts
> feat: apply missing value to table widget

- apps/web/src/schema/identity/workspace-group/model.ts
- apps/web/src/services/advanced/components/WorkspaceGroupAddUsersModal.vue
- apps/web/src/services/advanced/components/WorkspaceGroupAddWorkspacesModal.vue
- apps/web/src/services/advanced/components/WorkspaceGroupCreateModal.vue
- apps/web/src/services/advanced/components/WorkspaceGroupDeleteModal.vue
- apps/web/src/services/advanced/components/WorkspaceGroupDeleteStatusModal.vue
- apps/web/src/services/advanced/components/WorkspaceGroupTabGroupUser.vue
- apps/web/src/services/advanced/components/WorkspaceGroupTabWorkspace.vue
- apps/web/src/services/advanced/composables/use-select-drop-down-list.ts
- apps/web/src/services/advanced/constants/workspace-group-constant.ts
- apps/web/src/services/advanced/pages/admin/AdminWorkspaceGroupPage.vue
- apps/web/src/services/advanced/store/workspace-group-page-store.ts
- apps/web/src/services/advanced/types/admin-workspace-group-type.ts
> fix: fix AdminWorkspaceGroupPage api connection & minor bugs

- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/line-chart/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
- apps/web/src/common/modules/widgets/_widgets/table/widget-config.ts
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
- apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
> fix: remove table-data-field count value & edit table widget-config

- apps/web/src/schema/identity/role-binding/model.ts
- apps/web/src/schema/identity/role/model.ts
- apps/web/src/schema/identity/workspace-user/model.ts
- apps/web/src/services/advanced/components/WorkspaceGroupAddUsersModal.vue
- apps/web/src/services/advanced/components/WorkspaceGroupDeleteStatusModal.vue
- apps/web/src/services/advanced/components/WorkspaceGroupTabGroupUser.vue
- apps/web/src/services/advanced/components/WorkspaceGroupTabWorkspace.vue
- apps/web/src/services/advanced/constants/workspace-group-constant.ts
- apps/web/src/services/advanced/store/workspace-group-page-store.ts
- apps/web/src/services/iam/components/UserManagementTable.vue
- apps/web/src/services/iam/helpers/get-role-binding-id-from-role-binding-info.ts
- apps/web/src/services/iam/store/user-page-store.ts
> feat: show all roleBinding information

- apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFooter.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
> fix(dashboard-qa): solve some QAs

- apps/web/src/common/modules/widgets/_helpers/widget-helper.ts
- apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
> feat(widget-options): create sanitizing-wrong-options helper and apply & remove length check

- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldLegend.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldNumberFormat.vue
- apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> chore: add top/left position to field legend

- apps/web/src/services/advanced/components/WorkspaceGroupAddWorkspacesModal.vue
- apps/web/src/services/iam/components/UserManagementTabDetail.vue
- apps/web/src/services/iam/components/UserManagementTable.vue
- apps/web/src/services/iam/composables/refined-table-data.ts
- apps/web/src/store/reference/all-reference-store.ts
- apps/web/src/store/reference/workspace-group-reference-store.ts
> feat: apply roleBindingInfo data to UserManagementTabDetail

- apps/web/src/common/modules/widgets/_constants/widget-field-components-constant.ts
- apps/web/src/common/modules/widgets/_constants/widget-field-constant.ts
- apps/web/src/common/modules/widgets/_helpers/widget-helper.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldAdvancedFormatRules.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldLegend.vue
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
- apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
- `field` type
- `textThreshold` type
> feat: add 'Advanced Format Rules' field

- apps/web/src/schema/identity/role/api-verbs/disable.ts
- apps/web/src/schema/identity/role/api-verbs/enable.ts
- apps/web/src/services/iam/components/AppManagementTable.vue
- apps/web/src/services/iam/components/RoleDeleteModal.vue
- apps/web/src/services/iam/components/RoleManagementTable.vue
- apps/web/src/services/iam/components/RoleStateUpdateModal.vue
- apps/web/src/services/iam/constants/role-constant.ts
- apps/web/src/services/iam/store/role-page-store.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: add state field at search, action button, table

- apps/web/src/services/advanced/components/WorkspaceGroupTable.vue
- apps/web/src/services/advanced/constants/workspace-group-constant.ts
> feat: apply autoComplete search at workspaceGroup

- apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/modules/top-bar-search-dropdown/TopBarSearchDropdown.vue
- apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/modules/top-bar-search-dropdown/modules/TopBarSearchServiceTab.vue
- apps/web/src/services/asset-inventory/components/CloudServiceHistoryDetailNoteTab.vue
- apps/web/src/services/iam/components/UserManagementTable.vue
> feat: apply page access permissions

- apps/web/src/common/pages/ErrorPage.vue
- apps/web/src/router/index.ts
> feat: update 403 error page and restrict access

- apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-profile/TopBarProfile.vue
- apps/web/src/lib/site-initializer/api-client.ts
- apps/web/src/lib/variable-models/managed-model-config/base-managed-model-config.ts
- apps/web/src/lib/variable-models/managed-model/resource-model/role-variable-model.ts
- apps/web/src/store/reference/all-reference-store.ts
- apps/web/src/store/reference/role-reference-store.ts
> feat: add roleBindings information to TopBarProfile

- apps/web/src/schema/identity/app/api-verbs/create.ts
- apps/web/src/services/iam/components/AppManagementFormModal.vue
- apps/web/src/services/iam/components/AppManagementStatusModal.vue
- apps/web/src/services/iam/components/AppManagementTable.vue
- apps/web/src/services/iam/constants/app-constant.ts
> feat: apply member app api

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformForm.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformFormEvaluate.vue
- apps/web/src/common/modules/widgets/_constants/data-table-constant.ts
- apps/web/src/common/modules/widgets/types/widget-data-table-type.ts
- apps/web/src/common/modules/widgets/types/widget-model.ts
> feat(data-table): create new evaluate data-table 

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformFormEvaluate.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat(evaluate): create expression-delete modal 

- apps/web/src/common/modules/widgets/_composables/use-widget-option-validation.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldAdvancedFormatRules.vue
- apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
> feat: fix bug and change field name(rules -> value)

- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
- apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> fix: solve table QA (style, group by sorting) 

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformFormEvaluate.vue
> fix(data-table): add new evaluate-expression-delete planning

- apps/web/src/schema/identity/token/model.ts
- apps/web/src/services/iam/components/RoleUpdateFormPermissionForm.vue
- apps/web/src/store/modules/user/actions.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: apply qa about page permissions

- apps/web/src/common/modules/widgets/_composables/use-widget-option-validation.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldAdvancedFormatRules.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldColorSchema.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldDataField.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldGroupBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldLegend.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldMax.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldMin.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
- apps/web/src/services/dashboards/components/DashboardDetailHeader.vue
> feat: delete field validation from `useWidgetOptionValidation`

- apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
- apps/web/src/common/modules/widgets/_composables/use-widget-options-complex-validation.ts
> refactor: change hook name

- apps/web/src/services/landing/components/LandingWorkspaceGroupTabGroupUser.vue
- apps/web/src/store/app-context/app-context-store.ts
- apps/web/src/store/reference/role-reference-store.ts
> feat: apply UI based on UserRole

- .github/workflows/dispatch_preview_deploy_with_vercel.yml
> feat: add github action for vercel deploy

- apps/web/src/common/modules/widgets/_composables/use-widget-options-complex-validation.ts
- apps/web/src/services/dashboards/components/DashboardToolsetDateDropdown.vue
> fix: fix validation bug of geomap

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
> fix(data-table): apply legacy-evaluate compatible code

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFilters.vue
- apps/web/src/lib/variable-models/_base/resource-variable-model.ts
- apps/web/src/lib/variable-models/_base/types.ts
- Add `presetValues` property to `generateProperty` method
- Fix pagination bug in variable model's `stat` method
> fix: add preset values to `variableModel` stat results & apply cost-data-source presetValues to data-table filter 

- apps/web/src/schema/identity/token/model.ts
- apps/web/src/services/advanced/components/WorkspaceGroupHeader.vue
- apps/web/src/services/advanced/components/WorkspaceGroupTabGroupUser.vue
- apps/web/src/services/advanced/components/WorkspaceGroupTabWorkspace.vue
- apps/web/src/services/advanced/components/WorkspaceGroupTable.vue
- apps/web/src/services/advanced/pages/admin/AdminWorkspaceGroupPage.vue
- apps/web/src/services/iam/components/RoleManagementTable.vue
- apps/web/src/services/iam/components/UserManagementTabProjects.vue
- apps/web/src/services/iam/components/UserManagementTabWorkspace.vue
- apps/web/src/services/iam/components/UserManagementTable.vue
- apps/web/src/services/iam/constants/role-constant.ts
- apps/web/src/store/modules/user/actions.ts
> feat: apply page access permission and revert role info

- apps/web/src/store/reference/role-reference-store.ts
> chore: delete console log

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFooter.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardHeaderTitle.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformDataTableDropdown.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformForm.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformFormEvaluate.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: merge feature-dashboard-v2 to master

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformFormEvaluate.vue
- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
> chore: fix minor issue

- .github/workflows/dispatch_preview_deploy_with_vercel.yml
- .gitignore
- apps/web/src/lib/config/index.ts
> fix: fix vercel deploy action

- packages/utils/src/index.ts
> feat: create `getContrastingColor` util

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformFormEvaluate.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
- apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
- apps/web/src/services/dashboards/DashboardsLSB.vue
> fix: solve some dashboard QAs

- packages/utils/src/index.ts
> chore: set return type

- apps/web/src/common/pages/CostReportDetailPage.vue
> feat(cost-report-detail-page): update new feature

- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
- packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.mdx
- packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.stories.ts
- packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
- packages/mirinae/src/inputs/dropdown/select-dropdown/story-helper.ts
> fix: refactor clear-selection in PSelectDropdown & apply

- apps/web/src/services/iam/components/RoleUpdateForm.vue
- apps/web/src/services/iam/components/RoleUpdateFormPermissionForm.vue
- apps/web/src/services/iam/components/RoleUpdateFormPolicy.vue
- apps/web/src/services/iam/pages/admin/AdminRoleCreatePage.vue
- apps/web/src/services/iam/pages/admin/AdminRoleUpdatePage.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: revert api permissions section

- apps/web/src/common/modules/widgets/_constants/widget-components-constant.ts
- apps/web/src/common/modules/widgets/_constants/widget-config-list-constant.ts
- apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/ColorCodedHeatmap.vue
- apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
- apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/widget-config.ts
- apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: add Color-coded Table Heatmap

- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldDataFieldHeatmapColor.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldNumberFormat.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableColumnWidth.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
> fix(QA): solve some qAs

- apps/web/src/services/asset-inventory/components/CollectorAdditionalRule.vue
- apps/web/src/services/asset-inventory/pages/CollectorDetailPage.vue
- apps/web/src/services/asset-inventory/stores/collector-form-store.ts
- apps/web/src/services/asset-inventory/types/type.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: add empty additional rule card

- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/services/dashboards/helpers/widget-migration-helper.ts
- apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
> feat: add migration code for changed widget fields

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformFormEvaluate.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldCustomTableColumnWidth.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldDataFieldHeatmapColor.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldDisplaySeriesLabel.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldNumberFormat.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableColumnWidth.vue
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
- apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
- apps/web/src/services/dashboards/DashboardsLSB.vue
- apps/web/src/services/dashboards/helpers/widget-migration-helper.ts
- apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
- packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.mdx
- packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.stories.ts
- packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
- packages/mirinae/src/inputs/dropdown/select-dropdown/story-helper.ts
> feat(dashboard): merge feature-dashboard-v2 to master

- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
> fix: fix xAxis sorting of clusteredColumnChart & table api filter bug

- apps/web/src/common/modules/widgets/_helpers/widget-date-helper.ts
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
> fix: get full date range when its separated date

- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
> fix: fix table api filter bug

- apps/web/src/common/modules/widgets/_constants/widget-config-list-constant.ts
- apps/web/src/common/modules/widgets/_helpers/widget-load-helper.ts
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/widget-config.ts
- apps/web/src/services/dashboards/helpers/widget-migration-helper.ts
> feat: get `tableDataField` to stackedColumnChart

- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/widget-config.ts
- apps/web/src/services/dashboards/helpers/widget-migration-helper.ts
> feat: apply `tableDataField` to horizontalBarChart

- apps/web/src/services/cost-explorer/components/CostAnalysisStackedColumnChart.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
Remove 'Accumulated' from 'Daily (Accumulated)'
> feat: remove (accumulated) text and function from cost analysis

- apps/web/src/schema/inventory/collector-rule/api-verbs/change-order.ts
- apps/web/src/schema/inventory/collector-rule/api-verbs/create.ts
- apps/web/src/schema/inventory/collector-rule/api-verbs/delete.ts
- apps/web/src/schema/inventory/collector-rule/api-verbs/get.ts
- apps/web/src/schema/inventory/collector-rule/api-verbs/list.ts
- apps/web/src/schema/inventory/collector-rule/api-verbs/update.ts
- apps/web/src/schema/inventory/collector-rule/constant.ts
- apps/web/src/schema/inventory/collector-rule/model.ts
- apps/web/src/schema/inventory/collector-rule/type.ts
- apps/web/src/services/asset-inventory/components/CollectorAdditionalRule.vue
- apps/web/src/services/asset-inventory/components/CollectorAdditionalRuleContent.vue
- apps/web/src/services/asset-inventory/types/type.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: create CollectorAdditionalRuleContent

- apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
- apps/web/src/common/modules/widgets/_widgets/heatmap/widget-config.ts
- apps/web/src/services/dashboards/helpers/widget-migration-helper.ts
> feat: apply `tableDataField` to heatmap

- apps/web/src/services/iam/components/AppManagementTable.vue
> fix: fixed undefined error

- apps/web/src/services/asset-inventory/components/MetricExplorerDataTable.vue
> fix: set reference data when export excel

- apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
- apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/widget-config.ts
- apps/web/src/services/dashboards/helpers/widget-migration-helper.ts
- data field is comming!
- Css has changed a lot😅
> feat: apply tableDataField to colorCodedTableHeatmap

- apps/web/src/services/asset-inventory/components/WorkspaceDropdown.vue
- apps/web/src/services/cost-explorer/components/BudgetCreateTargetSelect.vue
- apps/web/src/services/cost-explorer/components/CostAnalysisFiltersPopper.vue
- apps/web/src/services/cost-explorer/components/DataSourceManagementTabLinkedAccountTable.vue
- apps/web/src/services/dashboards/components/DashboardVariableDropdown.vue
- apps/web/src/services/iam/components/UserManagementAddAdminRole.vue
- apps/web/src/services/info/components/NoticeListItem.vue
- apps/web/src/services/info/components/NoticeWorkspaceDropdown.vue
> feat: apply dormant filter at workspace dropdown

- apps/web/src/services/asset-inventory/pages/CloudServiceDetailPage.vue
https://github.com/user-attachments/assets/91c645de-281a-49d6-ae48-abd6884533ce
> fix(cloudServiceDetailPage): fix reset bug of query tags

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFilters.vue
- apps/web/src/lib/variable-models/_base/resource-variable-model.ts
- apps/web/src/lib/variable-models/_base/types.ts
- apps/web/src/lib/variable-models/variable-model-menu-handler.ts
- apps/web/src/services/asset-inventory/components/MetricExplorerFiltersPopper.vue
- apps/web/src/services/cost-explorer/components/CostAnalysisFiltersPopper.vue
- apps/web/src/services/dashboards/components/DashboardVariableDropdown.vue
- apps/web/src/services/dashboards/components/DashboardWidgetOptionDropdown.vue
> feat: set `is_dormant: false` if it's workspace model

- apps/web/src/schema/inventory/collector-rule/constant.ts
- apps/web/src/schema/inventory/collector-rule/model.ts
- apps/web/src/schema/inventory/collector-rule/type.ts
- apps/web/src/services/asset-inventory/components/CollectorAdditionalRule.vue
- apps/web/src/services/asset-inventory/components/CollectorAdditionalRuleContent.vue
- apps/web/src/services/asset-inventory/components/CollectorAdditionalRuleForm.vue
- apps/web/src/services/asset-inventory/components/CollectorAdditionalRuleFormOperatorDropdown.vue
- apps/web/src/services/asset-inventory/stores/collector-form-store.ts
- apps/web/src/services/project/components/ProjectAlertEventRuleConditionForm.vue
- apps/web/src/services/project/components/ProjectAlertEventRuleForm.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
SSIA 
+ ) Create CollectorAdditionalRuleFormOperatorDropdown
> feat: create AdditionalRuleForm &  add default Condition section UI

- apps/web/src/common/modules/widgets/_constants/widget-field-components-constant.ts
- apps/web/src/common/modules/widgets/_widget-fields/table-data-field/WidgetFieldTableDataField.vue
- apps/web/src/common/modules/widgets/_widget-fields/table-data-field/type.ts
- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
- apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
- apps/web/src/services/dashboards/helpers/widget-migration-helper.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
- Create and apply new version of table data field (V1)
- Add migration code (table-data-field)
- Update field design
- Refactor field dir structure
> feat(table-data-field): Create new version & apply migration code and new design & change field dir structure

- apps/web/src/common/modules/widgets/_composables/use-widget-options-complex-validation.ts
- apps/web/src/common/modules/widgets/_helpers/widget-load-helper.ts
- apps/web/src/common/modules/widgets/_widget-fields/table-data-field/WidgetFieldTableDataField.vue
> fix: apply changed tableDataField value to missed file

- apps/web/src/schema/inventory/cloud-service-type/api-verbs/stat.ts
- apps/web/src/services/asset-inventory/components/CollectorAdditionalRule.vue
- apps/web/src/services/asset-inventory/components/CollectorAdditionalRuleForm.vue
- apps/web/src/services/asset-inventory/helpers/cloud-service-analyze-query-helper.ts
- apps/web/src/services/asset-inventory/pages/CollectorDetailPage.vue
- apps/web/src/services/asset-inventory/stores/collector-form-store.ts
- apps/web/src/services/asset-inventory/types/type.ts
- packages/core-lib/src/space-connector/type.ts
> feat: connect form state to click-done event & apply search to value dropdown

- apps/web/src/common/modules/widgets/_constants/widget-field-components-constant.ts
- apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldProgressBar.vue
- apps/web/src/common/modules/widgets/_widget-fields/advanced-format-rules/WidgetFieldAdvancedFormatRules.vue
- apps/web/src/common/modules/widgets/_widget-fields/advanced-format-rules/type.ts
- apps/web/src/common/modules/widgets/_widget-fields/category-by/WidgetFieldCategoryBy.vue
- apps/web/src/common/modules/widgets/_widget-fields/category-by/type.ts
- apps/web/src/common/modules/widgets/_widget-fields/color-schema/WidgetFieldColorSchema.vue
- apps/web/src/common/modules/widgets/_widget-fields/color-schema/type.ts
- apps/web/src/common/modules/widgets/_widget-fields/format-rules/WidgetFieldFormatRules.vue
- apps/web/src/common/modules/widgets/_widget-fields/format-rules/type.ts
- apps/web/src/common/modules/widgets/_widget-fields/table-data-field/type.ts
- apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/ColorCodedHeatmap.vue
- apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
- apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
- apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
- apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
- apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
SSIA
- `Advanced Format Rules`
- `Format Rules`
- `Category By`
- `Color Schema`
> refactor: edit widget field dir structure

- apps/web/src/common/modules/widgets/_helpers/widget-date-helper.ts
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/services/dashboards/helpers/widget-migration-helper.ts
> feat: migrate LineChart, ClusteredColumnChart

- apps/web/src/common/modules/widgets/_composables/use-widget-options-complex-validation.ts
- apps/web/src/common/modules/widgets/_helpers/widget-date-helper.ts
- apps/web/src/common/modules/widgets/_helpers/widget-load-helper.ts
- apps/web/src/common/modules/widgets/_widget-fields/table-data-field/WidgetFieldTableDataField.vue
- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
- apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
> fix: fix `dateRange` for separated date

- apps/web/src/services/my-page/components/UserAccountBaseInformation.vue
- apps/web/src/services/my-page/components/UserAccountMultiFactorAuth.vue
- apps/web/src/services/my-page/components/UserAccountMultiFactorAuthItems.vue
- apps/web/src/services/my-page/pages/UserAccountPage.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat(my-page): apply base mark-up at mfa

- apps/web/src/services/cost-explorer/components/CostAnalysisDataTypeDropdown.vue
- apps/web/src/services/cost-explorer/components/CostAnalysisQuerySection.vue
> chore: fix select dropdown style

- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/table/Table.vue
- apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
> chore: fix typescript error

- apps/web/src/services/project/ProjectLSB.vue
- apps/web/src/services/project/components/ProjectMainTree.vue
- apps/web/src/services/project/components/ProjectMemberInviteModal.vue
- apps/web/src/services/project/pages/ProjectDetailPageNew.vue
> feat(project-detail): create new project detail page & apply new planning

- apps/web/src/services/project/components/ProjectTagsInputGroup.vue
- apps/web/src/services/project/components/ProjectTagsModal.vue
- apps/web/src/services/project/pages/ProjectDetailPageNew.vue
> feat: create new project tags modal & add update/move

- apps/web/src/common/modules/widgets/_widget-fields/comparison/WidgetFieldComparison.vue
- apps/web/src/schema/dashboard/_types/dashboard-type.ts
- apps/web/src/schema/dashboard/private-folder/api-verbs/create.ts
- apps/web/src/schema/dashboard/private-folder/api-verbs/delete.ts
- apps/web/src/schema/dashboard/private-folder/api-verbs/update.ts
- apps/web/src/schema/dashboard/public-folder/api-verbs/create.ts
- apps/web/src/schema/dashboard/public-folder/api-verbs/delete.ts
- apps/web/src/schema/dashboard/public-folder/api-verbs/update.ts
- apps/web/src/services/dashboards/components/dashboard-main/DashboardMainFolderFormModal.vue
- apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
- apps/web/src/services/dashboards/types/dashboard-folder-type.ts
- apps/web/src/store/dashboard/dashboard-store.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
- packages/mirinae/src/data-display/tree/tree-view/PTreeItem.vue
- packages/mirinae/src/data-display/tree/tree-view/PTreeView.vue
- packages/mirinae/src/data-display/tree/tree-view/type.ts
https://github.com/user-attachments/assets/f2c9a406-da74-40d3-9f07-5b5b78fc21bd
real api is comming!!!!!!!
Please ignore `chore` commits!!!
> feat: apply real api to folder modal

- apps/web/src/schema/identity/workspace-group-user/api-verbs/remove.ts
- apps/web/src/services/landing/components/workspace-landing/landing-group-workspaces/LandingWorkspaceGroupRemoveUserModal.vue
- apps/web/src/services/landing/components/workspace-landing/landing-group-workspaces/LandingWorkspaceGroupTabGroupUser.vue
- apps/web/src/services/landing/store/landing-page-store.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: create removeGroupUser modal

- apps/web/src/schema/identity/workspace-group-user/api-verbs/update-role.ts
- apps/web/src/services/landing/components/workspace-landing/landing-group-workspaces/LandingWorkspaceGroupTabGroupUser.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: apply updateRole api

- apps/web/src/services/landing/components/workspace-landing/landing-group-workspaces/LandingGroupWorkspaces.vue
- apps/web/src/services/landing/components/workspace-landing/landing-group-workspaces/LandingWorkspaceGroupManageOverlay.vue
- apps/web/src/services/landing/components/workspace-landing/landing-group-workspaces/LandingWorkspaceGroupRemoveUserModal.vue
- apps/web/src/services/landing/components/workspace-landing/landing-group-workspaces/LandingWorkspaceGroupTabGroupUser.vue
- apps/web/src/services/landing/components/workspace-landing/landing-group-workspaces/LandingWorkspaceGroupTabWorkspace.vue
- apps/web/src/services/landing/store/landing-page-store.ts
> feat: add workspaceTab to LandingOverlay

- apps/web/src/services/advanced/components/WorkspaceGroupAddUsersModal.vue
- apps/web/src/services/advanced/components/WorkspaceGroupAddWorkspacesModal.vue
- apps/web/src/services/advanced/components/WorkspaceGroupDeleteStatusModal.vue
- apps/web/src/services/advanced/components/WorkspaceGroupTabGroupUser.vue
- apps/web/src/services/advanced/components/WorkspaceGroupTabWorkspace.vue
- apps/web/src/services/advanced/components/WorkspaceGroupTable.vue
- apps/web/src/services/advanced/composables/use-select-drop-down-list.ts
- apps/web/src/services/advanced/pages/admin/AdminWorkspaceGroupPage.vue
- apps/web/src/services/advanced/store/workspace-group-page-store.ts
- apps/web/src/store/reference/workspace-reference-store.ts
> fix(admin-workspace-group-page): change the fetch method

- apps/web/src/schema/dashboard/private-dashboard/api-verbs/update.ts
- apps/web/src/schema/dashboard/public-dashboard/api-verbs/update.ts
- apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderDeleteModal.vue
- apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderMoveModal.vue
- apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTree.vue
- apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTreeItem.vue
- apps/web/src/services/dashboards/components/dashboard-folder/DashboardMainFolderFormModal.vue
- apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
- apps/web/src/services/dashboards/stores/dashboard-main-page-store.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: add folder delete, move modal

- apps/web/src/services/advanced/components/WorkspaceGroupAddUsersModal.vue
- apps/web/src/services/advanced/components/WorkspaceGroupCreateModal.vue
- apps/web/src/services/advanced/components/WorkspaceGroupDeleteModal.vue
- apps/web/src/services/advanced/components/WorkspaceGroupHeader.vue
- apps/web/src/services/advanced/components/WorkspaceGroupTable.vue
- apps/web/src/services/advanced/pages/admin/AdminWorkspaceGroupPage.vue
- apps/web/src/services/advanced/store/workspace-group-page-store.ts
> fix: fix workspaceGroup delete modal store logic

- apps/web/src/schema/dashboard/_types/dashboard-type.ts
- apps/web/src/schema/dashboard/private-dashboard/api-verbs/change-folder.ts
- apps/web/src/schema/dashboard/public-dashboard/api-verbs/change-folder.ts
- apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderMoveModal.vue
- apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTree.vue
> feat: apply new api "change-folder"

- apps/web/src/services/advanced/components/WorkspaceGroupAddUsersModal.vue
- apps/web/src/services/advanced/components/WorkspaceGroupAddWorkspacesModal.vue
- apps/web/src/services/advanced/components/WorkspaceGroupCreateModal.vue
- apps/web/src/services/advanced/components/WorkspaceGroupTabWorkspace.vue
- apps/web/src/services/advanced/components/WorkspaceGroupTable.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> fix: fix UI bugs (workspace group page)

- apps/web/src/schema/identity/workspace-user/model.ts
- apps/web/src/services/advanced/components/WorkspaceGroupTabWorkspace.vue
- apps/web/src/services/iam/components/UserManagementTab.vue
- apps/web/src/services/iam/components/UserManagementTable.vue
- apps/web/src/services/iam/helpers/role-binding-helpers.ts
- apps/web/src/services/iam/store/user-page-store.ts
> fix: fix user page according to changed RoleBinding api

- apps/web/src/schema/dashboard/_types/folder-type.ts
- apps/web/src/schema/dashboard/_types/widget-type.ts
- apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderDeleteModal.vue
- apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTreeItem.vue
- apps/web/src/services/dashboards/components/dashboard-folder/DashboardMainFolderFormModal.vue
- apps/web/src/services/dashboards/stores/dashboard-main-page-store.ts
- apps/web/src/store/dashboard/dashboard-store.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> chore: move codes to store getters

- apps/web/src/services/iam/components/AppManagementFormModal.vue
> chore: add active condition

- apps/web/src/common/modules/navigations/top-bar/modules/top-bar-header/TopBarWorkspaces.vue
- apps/web/src/lib/access-control/page-access-helper.ts
- apps/web/src/lib/menu/config.ts
- apps/web/src/services/advanced/pages/admin/AdminWorkspacesPage.vue
- apps/web/src/services/dashboards/DashboardsLSB.vue
- apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
- apps/web/src/services/workspace-home/components/WorkspaceInfo.vue
- apps/web/src/store/modules/user/actions.ts
- apps/web/src/store/modules/user/getters.ts
- apps/web/src/store/modules/user/type.ts
> feat: apply access permissions at each pages

- apps/web/src/services/advanced/components/WorkspaceGroupTabWorkspace.vue
- apps/web/src/services/advanced/components/WorkspaceManagementTable.vue
- apps/web/src/services/advanced/pages/admin/AdminDomainSettingsAutoDormancyConfigurationPage.vue
- apps/web/src/services/advanced/store/workspace-group-page-store.ts
- apps/web/src/services/advanced/store/workspace-page-store.ts
- apps/web/src/services/asset-inventory/components/ServiceAccountUsageOverview.vue
- apps/web/src/services/asset-inventory/pages/ServiceAccountDetailPage.vue
- apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue
- apps/web/src/services/asset-inventory/stores/service-account-page-store.ts
> fix: fixed currency store

- apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-profile/TopBarProfile.vue
- apps/web/src/lib/site-initializer/workspace.ts
- apps/web/src/services/landing/components/workspace-landing/landing-group-workspaces/LandingGroupWorkspaces.vue
- apps/web/src/store/app-context/app-context-store.ts
- apps/web/src/store/app-context/workspace/user-workspace-store.ts
> fix: fix TopBarProfile role field

- packages/mirinae/src/hooks/tab/index.ts
- packages/mirinae/src/navigation/tabs/tab/PTab.mdx
- packages/mirinae/src/navigation/tabs/tab/PTab.stories.ts
- packages/mirinae/src/navigation/tabs/tab/PTab.vue
- packages/mirinae/src/navigation/tabs/tab/story-helper.ts
- packages/mirinae/src/navigation/tabs/tab/type.ts
- Add `header-right-contents` slot
- Apply overflow tab menu design
- Apply `folder` type tab
https://github.com/user-attachments/assets/c49a617e-338d-482d-9cf2-d5fa4c101f70
https://github.com/user-attachments/assets/bafc70ce-8e83-42f9-aed5-14a30ea54166
> feat(p-tab): renewal `PTab` component

- apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderCloneModal.vue
- apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderDeleteModal.vue
- apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderMoveModal.vue
- apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTree.vue
- apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
- apps/web/src/services/dashboards/stores/dashboard-main-page-store.ts
- apps/web/src/services/dashboards/types/dashboard-folder-type.ts
> refactor(folder-tree): use props instead of page store

- apps/web/src/services/asset-inventory/components/CloudServiceHistoryDetailNoteTab.vue
> chore: add readonly condition

- apps/web/src/services/project/components/ProjectDetailTab.vue
- apps/web/src/services/project/pages/ProjectDashboardPage.vue
- apps/web/src/services/project/pages/ProjectDetailTabPage.vue
- apps/web/src/services/project/pages/ProjectSummaryPage.vue
- apps/web/src/services/project/routes/routes.ts
- apps/web/src/store/dashboard/dashboard-store.ts
> feat(project-dashboard): create project-dashboard tab and page

- apps/web/src/services/dashboards/DashboardsLSB.vue
- apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderCloneModal.vue
- apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderFormModal.vue
- apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTree.vue
- apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTreeItem.vue
- apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTreeTitle.vue
- apps/web/src/services/dashboards/components/dashboard-main/DashboardLSBTree.vue
- apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
- apps/web/src/services/dashboards/stores/dashboard-main-page-store.ts
- apps/web/src/services/dashboards/types/dashboard-folder-type.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
- folder title
- show all button
- new mark
- Dashboard LSB
> feat: add folder tree title & new mark & dashboard lsb & show all button

- apps/web/src/schema/monitoring/webhook/api-verbs/list.ts
- apps/web/src/services/project/pages/ProjectDetailPageNew.vue
> feat(project-dashboard): apply alert/webhook planning

- apps/web/src/services/project/pages/ProjectDetailPageNew.vue
- apps/web/src/services/project/pages/ProjectDetailTabPage.vue
- apps/web/src/services/project/pages/ProjectSummaryPage.vue
- apps/web/src/services/project/routes/routes.ts
- packages/mirinae/src/navigation/tabs/tab/PTab.vue
> chore(project-dashboard): solve small issues

- apps/web/src/services/project/components/ProjectMain.vue
- apps/web/src/services/project/components/ProjectMainProjectCard.vue
- apps/web/src/services/project/components/ProjectMainProjectGroupCard.vue
- apps/web/src/services/project/pages/ProjectMainPage.vue
> fix(project-landing): edit project-landing page design

- apps/web/src/services/dashboards/DashboardsLSB.vue
- apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderFormModal.vue
- apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
- apps/web/src/services/dashboards/stores/dashboard-main-page-store.ts
Admin Dashboard is coming!!!!!!
>  feat: apply admin mode dashboard

- apps/web/package.json
- apps/web/src/services/cost-explorer/components/CostAnalysisDataTypeDropdown.vue
- apps/web/src/services/cost-explorer/components/CostAnalysisQuerySection.vue
- package-lock.json
- package.json
- packages/mirinae/package.json
> chore: Merge branch 'master' into feature-feedback-v2

- apps/web/src/services/my-page/components/UserAccountMultiFactorAuth.vue
- apps/web/src/services/my-page/components/UserAccountMultiFactorAuthItems.vue
- apps/web/src/services/my-page/components/UserAccountMultiFactorAuthModal.vue
- apps/web/src/services/my-page/components/UserAccountMultiFactorAuthModalEmailInfo.vue
- apps/web/src/services/my-page/components/UserAccountMultiFactorAuthModalFolding.vue
- apps/web/src/services/my-page/types/multi-factor-auth-type.ts
> feat: add mfa type (MS) - only Mark up

- apps/web/src/services/cost-explorer/components/CostAnalysisChart.vue
- apps/web/src/services/cost-explorer/components/CostAnalysisStackedColumnChart.vue
> feat: apply accumulated toggle to cost analysis chart

- apps/web/src/common/modules/favorites/favorite-button/FavoriteButton.vue
- apps/web/src/lib/menu/menu-info.ts
- apps/web/src/services/cost-explorer/components/DataSourceManagementTabLinkedAccountTable.vue
> chore: apply minor feedback (style, type)

- apps/web/src/services/advanced/components/WorkspaceGroupAddUsersModal.vue
- apps/web/src/services/advanced/components/WorkspaceGroupEditModal.vue
- apps/web/src/services/iam/components/UserManagementAddAdminRole.vue
- apps/web/src/services/iam/components/UserManagementAddModal.vue
- apps/web/src/services/iam/types/user-type.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
- packages/mirinae/src/feedbacks/modals/button-modal/PButtonModal.vue
> feat: add workspaceGroup select option to Add User Modal

- apps/web/src/services/advanced/components/WorkspaceManagementTable.vue
- apps/web/src/services/advanced/constants/workspace-constant.ts
- apps/web/src/services/advanced/store/workspace-page-store.ts
> fix: update data mapping of user_count field

- apps/web/src/services/advanced/components/WorkspaceGroupAddUsersModal.vue
- apps/web/src/services/advanced/components/WorkspaceGroupAddWorkspacesModal.vue
- apps/web/src/services/advanced/components/WorkspaceGroupDeleteStatusModal.vue
- apps/web/src/services/advanced/components/WorkspaceGroupTabGroupUser.vue
- apps/web/src/services/advanced/composables/use-select-drop-down-list.ts
- apps/web/src/services/landing/components/workspace-landing/landing-group-workspaces/LandingWorkspaceGroupAddUsersModal.vue
> feat: remove added workspace in workspace dropdown menu

- apps/web/src/common/modules/widgets/_helpers/widget-load-helper.ts
- apps/web/src/services/dashboards/DashboardsLSB.vue
- apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderDeleteModal.vue
> chore(dashboard): fix minors

- apps/web/src/services/project/components/ProjectMainDeleteModal.vue
- apps/web/src/services/project/components/ProjectMainProjectCard.vue
- apps/web/src/services/project/components/ProjectMainProjectGroupCard.vue
- apps/web/src/services/project/pages/ProjectMainPage.vue
- apps/web/src/services/project/stores/project-page-store.ts
SSIA
[Prev PR](https://github.com/cloudforet-io/console/pull/4742) will be a good reference
> fix(project-main-page): apply global action state to project group

- apps/web/src/services/my-page/components/UserAccountMultiFactorAuth.vue
- apps/web/src/services/my-page/components/UserAccountMultiFactorAuthItems.vue
- apps/web/src/services/my-page/components/UserAccountMultiFactorAuthModal.vue
- apps/web/src/services/my-page/components/UserAccountMultiFactorAuthModalEmailInfo.vue
- apps/web/src/services/my-page/components/UserAccountMultiFactorAuthModalFolding.vue
- apps/web/src/services/my-page/components/UserAccountMultiFactorAuthModalMSInfo.vue
- apps/web/src/services/my-page/types/multi-factor-auth-type.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: apply re-sync modal and changed modal state

- apps/web/src/services/project/ProjectLSB.vue
- apps/web/src/services/project/components/ProjectMain.vue
- packages/mirinae/src/inputs/context-menu/PContextMenu.vue
> fix(project-main): apply new design

- apps/web/src/services/asset-inventory/components/CollectorAdditionalRuleContent.vue
- apps/web/src/store/reference/project-reference-store.ts
> fix(collector-detail-page): fix project routing in admin mode

- apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderCloneModal.vue
- apps/web/src/store/dashboard/dashboard-store.ts
> refactor: move codes to store

- apps/web/src/lib/site-initializer/api-client.ts
- apps/web/src/store/reference/all-reference-store.ts
- apps/web/src/store/reference/public-folder-reference-store.ts
> feat(folder): create public folder reference store

- apps/web/src/common/modules/favorites/favorite-button/FavoriteButton.vue
- apps/web/src/common/modules/favorites/favorite-button/store/favorite-store.ts
- apps/web/src/lib/helper/config-data-helper.ts
SSIA
Reference: https://systorage.tistory.com/entry/Typescript-typescript%EC%97%90%EC%84%9C-type%EA%B3%BC-interface%EC%9D%98-%EC%86%8D%EC%84%B1%EC%9D%84-%EC%9E%AC%EC%A0%95%EC%9D%98%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95-typescript-Overriding
> fix: fix incorrect types and allow favorite updates without reference data

- apps/web/src/common/modules/project/ProjectSelectDropdown.vue
- apps/web/src/common/modules/workspace/WorkspaceSelectDropdown.vue
- apps/web/src/services/asset-inventory/components/CollectorAdditionalRuleContent.vue
- apps/web/src/services/asset-inventory/components/CollectorAdditionalRuleForm.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: add workspaceSelectDropdown to additional Rule form

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFiltersItem.vue
> chore: apply data-table operator design

- apps/web/src/common/components/scoped-notification/ScopedNotification.vue
- apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/modules/top-bar-search-dropdown/modules/TopBarSearchWorkspaceFilter.vue
- apps/web/src/services/advanced/components/WorkspaceGroupAddUsersModal.vue
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> fix: update new UI of WorkspaceGroupAddUsersModal

- apps/web/src/common/modules/widgets/_widget-fields/table-data-field/WidgetFieldTableDataField.vue
- apps/web/src/services/dashboards/components/dashboard-create/DashboardCreateStep1.vue
- apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
- apps/web/src/services/dashboards/stores/dashboard-main-page-store.ts
- apps/web/src/services/project/pages/ProjectDetailPage.vue
- apps/web/src/services/project/pages/ProjectMainPage.vue
> feat: set back button to project detail page

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFilters.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFiltersItem.vue
- apps/web/src/common/modules/widgets/_constants/data-table-constant.ts
Data Table Filters
- Contain(`contain_in`, `not_contain_in`) -> keyword filter
- Equal(`in`, `not_in`) -> select filter
> feat(data-table): create keyword filter (`contain_in`, `not_contain_in`)

- apps/web/src/common/modules/navigations/lsb/modules/LSBStarredMenuItem.vue
- apps/web/src/common/modules/widgets/_widget-fields/display-series-label/WidgetFieldDisplaySeriesLabel.vue
- apps/web/src/common/modules/widgets/_widget-fields/display-series-label/type.ts
- apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
- apps/web/src/common/modules/widgets/_widgets/pie-chart/widget-config.ts
- apps/web/src/common/modules/widgets/types/widget-field-type.ts
- apps/web/src/services/dashboards/pages/DashboardCreatePage.vue
- apps/web/src/services/dashboards/routes/admin/routes.ts
- apps/web/src/services/dashboards/routes/routes.ts
- apps/web/src/services/project/ProjectContainer.vue
- apps/web/src/services/project/ProjectLSB.vue
- apps/web/src/services/project/components/ProjectFormModal.vue
- apps/web/src/services/project/components/ProjectMain.vue
- apps/web/src/services/project/components/ProjectMainProjectGroupFormModal.vue
- apps/web/src/services/project/pages/ProjectDetailPage.vue
- apps/web/src/services/project/pages/ProjectMainPage.vue
- apps/web/src/services/project/stores/project-page-store.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: apply format field to PieChart

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFilters.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFiltersItem.vue
- apps/web/src/common/modules/widgets/_constants/data-table-constant.ts
> fix(data-table-filter): apply keyword-filter disabled

- apps/web/src/lib/menu/config.ts
- apps/web/src/lib/menu/menu-info.ts
- apps/web/src/services/cost-explorer/components/CostAdvancedSettingsContainer.vue
- apps/web/src/services/cost-explorer/components/CostAdvancedSettingsLSB.vue
- apps/web/src/services/cost-explorer/routes/admin/routes.ts
- apps/web/src/services/cost-explorer/routes/route-constant.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: add currency converter menu

- apps/web/src/services/advanced/components/WorkspaceGroupAddUsersModal.vue
- apps/web/src/services/advanced/components/WorkspaceGroupAddWorkspacesModal.vue
> feat: disable workspaces of other workspaceGroup & add ellipsis & tooltip

- apps/web/src/common/modules/widgets/_components/WidgetCustomLagend.vue
- apps/web/src/common/modules/widgets/_widget-fields/display-annotation/WidgetFieldDisplayAnnotation.vue
- apps/web/src/common/modules/widgets/_widget-fields/number-format/WidgetFieldNumberFormat.vue
- apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/ColorCodedHeatmap.vue
- apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
- apps/web/src/common/modules/widgets/types/widget-legend-typs.ts
> feat: add `WidgetCustomLegend` and apply it to widget

- apps/web/src/common/modules/favorites/favorite-button/FavoriteButton.vue
- apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-favorite/modules/TopBarFavoriteContextMenu.vue
- apps/web/src/services/dashboards/DashboardsLSB.vue
- apps/web/src/services/dashboards/components/dashboard-create/DashboardCreateStep1.vue
- apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderBundleMoveModal.vue
- apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderCloneModal.vue
- apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderDeleteModal.vue
- apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderFormModal.vue
- apps/web/src/services/dashboards/components/dashboard-main/DashboardLSBTree.vue
- apps/web/src/services/dashboards/components/dashboard-main/DashboardMainBoardList.vue
- apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
- apps/web/src/services/dashboards/stores/dashboard-main-page-store.ts
- apps/web/src/services/workspace-home/components/UserConfigRecent.vue
- apps/web/src/store/dashboard/dashboard-store.ts
> feat: get dashboard from page store

- apps/web/src/services/project/ProjectContainer.vue
- apps/web/src/services/project/ProjectLSB.vue
- apps/web/src/services/project/components/ProjectDetailTabHeader.vue
- apps/web/src/services/project/components/ProjectFormModal.vue
- apps/web/src/services/project/components/ProjectMainProjectGroupCard.vue
- apps/web/src/services/project/components/ProjectMainProjectGroupFormModal.vue
- apps/web/src/services/project/pages/ProjectMainPage.vue
> fix(project): update usage of form modal (project, projectGroup)

- apps/web/src/lib/site-initializer/api-client.ts
- apps/web/src/services/project/components/ProjectDetailTabHeader.vue
- apps/web/src/services/project/components/ProjectMemberInviteModal.vue
> feat(project-dashboard): add remove users

- apps/web/src/services/advanced/pages/admin/AdminWorkspacesPage.vue
- apps/web/src/services/iam/components/UserManagementAddModal.vue
- apps/web/src/services/iam/components/UserManagementAddUser.vue
- apps/web/src/services/iam/components/UserManagementFormAdminRole.vue
- apps/web/src/services/iam/components/UserManagementFormInfoForm.vue
- apps/web/src/services/iam/components/UserManagementFormModal.vue
- apps/web/src/services/iam/components/UserManagementFormMultiFactorAuth.vue
- apps/web/src/services/iam/components/UserManagementFormPasswordForm.vue
- apps/web/src/services/iam/components/UserManagementHeader.vue
- apps/web/src/services/iam/components/UserManagementStatusModal.vue
- apps/web/src/services/iam/components/UserManagementTab.vue
- apps/web/src/services/iam/components/UserManagementTabDetail.vue
- apps/web/src/services/iam/components/UserManagementTabProjects.vue
- apps/web/src/services/iam/components/UserManagementTabTag.vue
- apps/web/src/services/iam/components/UserManagementTabWorkspace.vue
- apps/web/src/services/iam/components/UserManagementTable.vue
- apps/web/src/services/iam/components/UserManagementTableToolbox.vue
- apps/web/src/services/iam/pages/UserMainPage.vue
- apps/web/src/services/iam/store/user-page-store.ts
- apps/web/src/services/workspace-home/components/WorkspaceInfo.vue
> fix(user-page-store): update to setup store

- apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
- apps/web/src/services/dashboards/DashboardsLSB.vue
- apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderCloneModal.vue
- apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderShareModal.vue
- apps/web/src/services/dashboards/components/dashboard-main/DashboardLSBTree.vue
- apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
- apps/web/src/services/dashboards/stores/dashboard-main-page-store.ts
> fix: do not show project dashboards in workspace mode

- apps/web/src/services/dashboards/helpers/widget-migration-helper.ts
- apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
SSIA
ASIS: Update widget data by API (`updateWidget` function)
TOBE: Convert widget data without API
> fix(dashboard-widgets): update widget-migration helper (update -> convert)

- apps/web/src/services/cost-explorer/pages/admin/AdminAdvancedSettingsCurrencyConverterPage.vue
- apps/web/src/services/cost-explorer/routes/admin/routes.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
> feat: create currency converter page (only Mark-up)

- apps/web/src/services/asset-inventory/pages/CloudServicePage.vue
> chore(cloud-service-page): small design fix

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFilters.vue
- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardSourceForm.vue
- apps/web/src/services/asset-inventory/components/MetricExplorerHeader.vue
- apps/web/src/services/cost-explorer/components/CostAnalysisFiltersAddMoreButton.vue
- apps/web/src/services/cost-explorer/components/CostAnalysisGranularityPeriodDropdown.vue
- apps/web/src/services/cost-explorer/components/CostAnalysisPeriodSelectDropdown.vue
- apps/web/src/services/cost-explorer/components/CostAnalysisQuerySection.vue
- apps/web/src/services/dashboards/components/DashboardCostWidgetValueOptionDropdown.vue
- apps/web/src/services/dashboards/components/DashboardVariablesMoreButton.vue
- apps/web/src/services/dashboards/components/DashboardWidgetMoreOptions.vue
- apps/web/src/services/project/pages/ProjectMainPage.vue
- apps/web/src/services/workspace-home/components/BookmarkHeader.vue
- packages/mirinae/src/data-display/popover/PPopover.vue
- packages/mirinae/src/hooks/context-menu-controller/__tests__/index.test.ts
- packages/mirinae/src/hooks/context-menu-controller/index.ts
- packages/mirinae/src/hooks/context-menu-fixed-style/index.ts
- packages/mirinae/src/inputs/dropdown/filterable-query-dropdown/PFilterableQueryDropdown.vue
- packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.stories.ts
- packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
- packages/mirinae/src/inputs/dropdown/select-dropdown/story-helper.ts
- packages/mirinae/src/inputs/input/query-input/PQueryInput.vue
- packages/mirinae/src/inputs/search/search/PSearch.vue
- packages/mirinae/src/navigation/breadcrumbs/modules/BreadcrumbsEllipsisItem.vue
> feat(mirinae): apply floatingUI lib on context-menu-fixed-style hook

- apps/web/src/common/modules/widgets/DailyUpdates.vue
- apps/web/src/services/asset-inventory/components/CloudServiceListCard.vue
- apps/web/src/services/asset-inventory/components/CloudServices.vue
- apps/web/src/services/asset-inventory/components/MetricExplorerDataTable.vue
- apps/web/src/services/asset-inventory/constants/cloud-service-constant.ts
- apps/web/src/services/asset-inventory/pages/CloudServicePage.vue
- apps/web/src/services/asset-inventory/types/cloud-service-page-type.ts
- apps/web/src/services/cost-explorer/components/CostAnalysisDataTable.vue
- apps/web/src/services/dashboards/widgets/_composables/use-widget/use-widget-location.ts
- apps/web/src/services/project/components/ProjectSummaryAllSummaryWidget.vue
- apps/web/src/services/project/components/ProjectSummaryAllSummaryWidgetRegionService.vue
- apps/web/src/services/project/components/ProjectSummaryServiceAccountsWidget.vue
- apps/web/src/services/project/components/ProjectSummaryTrustedAdvisorWidget.vue
> fix(cloud-service): apply new query spec

- apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/ColorCodedHeatmap.vue
- apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
- apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
- apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
- apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
- apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
- apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
- apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
- apps/web/src/common/modules/widgets/_widgets/progress-card/ProgressCard.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
- apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
- apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
- apps/web/src/services/dashboards/DashboardsLSB.vue
- apps/web/src/services/dashboards/components/dashboard-detail/DashboardLabels.vue
- apps/web/src/services/dashboards/components/dashboard-detail/DashboardNameEditModal.vue
- apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
- apps/web/src/services/dashboards/stores/dashboard-main-page-store.ts
- packages/language-pack/en.json
- packages/language-pack/ja.json
- packages/language-pack/ko.json
[[Minor][Dashboard] 즐겨찾기 리스트에 목록이 안뜨는 현상](https://mzdevs.atlassian.net/browse/MZ00003-1248)
[[Major][Project] 대시보드를 프로젝트에 공유시 폴더 제외하고 리스트에서 대시보드 사라짐](https://mzdevs.atlassian.net/browse/MZ00003-1249)
[[Minor][Dashboard] 대시보드 이름 수정 후 Confirm 클릭시 text input이 잠깐 invalid 상태로 보임](https://mzdevs.atlassian.net/browse/MZ00003-1245)
[[Major][Dashboard] 툴팁 가려지는 이슈](https://mzdevs.atlassian.net/browse/MZ00003-1131) 
[[Major][Dashboard] 금액이 표시가 로딩 과정에서 변경되는 이슈](https://mzdevs.atlassian.net/browse/MZ00003-1143)
[[Minor][Dashboard] Read-Only 권한만 있는 유저에게는 Label이 없을 때 empty 스테이트 보여주기](https://mzdevs.atlassian.net/browse/MZ00003-1051)
> fix: fix starred menu bug in dashboard LSB

- apps/web/src/services/dashboards/DashboardsLSB.vue
- apps/web/src/services/dashboards/components/dashboard-main/DashboardLSBTree.vue
- apps/web/src/services/dashboards/stores/dashboard-main-page-store.ts
- apps/web/src/store/dashboard/dashboard-store.ts
> fix: fix shared project dashboard bug

- apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFilters.vue
- apps/web/src/services/cost-explorer/components/CostAnalysisFiltersPopper.vue
- apps/web/src/services/cost-explorer/stores/cost-analysis-page-store.ts
> fix: solve saved preset filter item bug & apply cost-data-source metadata enums to cost-analysis page
