cloudforet-io/console

src/services/auth/authenticator/index.ts

**원인**
1. 토큰을 리프레시할 때 잠시 로컬스토리지에 `spaceConnector/isRefreshing` 값을 넣어 중복 리프레시를 막음. 리프레시가 끝나면 이 값을 다시 삭제함
2. 그런데 무슨 이유에선지 로컬스토리지에서 이 값이 삭제되지 않아, 리프레시를 아예 시도하지 못함
**해결**
일단 사용자의 로컬 스토리지에 저 값이 남아있는 게 제일 큰 문제이기 때문에 signIn 할 때 로컬스토리지에서 `spaceConnector/isRefreshing` 값을 삭제
리프레시 플로우를 탈 때 어디선가 문제가 생겨 로컬스토리지 값을 비워주지 못한 것 같습니다. 원인 찾아볼 예정

fix(auth): unsetRefreshingState in SignIn

---

src/common/modules/navigations/gnb/modules/gnb-search/modules/GNBSearchDropdown.vue

gnb 검색이 없는 경우 아래와 같은 두 종류의 도움말이 노출 됩니다. 아래 스크린샷의 빨강박스 도움말은 검색어 입력시 노출되어야 하는 영역으로 수정하였습니다.

fix(gnb-search-dropdown): fix no-data exposure conditions

---

src/services/asset-inventory/service-account/modules/ServiceAccountCredentials.vue
src/services/asset-inventory/service-account/modules/ServiceAccountCredentialsForm.vue
src/services/asset-inventory/service-account/service-account-add/ServiceAccountAddPage.vue

- attach trust account 질문 추가
- account type 별로 secret 가져오기

fix(service-account): get secrets by service account type

---

src/services/asset-inventory/service-account/ServiceAccountPage.vue
src/services/asset-inventory/service-account/config.ts
src/services/asset-inventory/service-account/modules/ServiceAccountBadge.vue
src/services/asset-inventory/service-account/type.ts

serviceAccount에서 중복 사용되는 배지를 컴포넌트로 생성하였습니다.
props
- accountType : AccountType 주입 시, 해당하는 배지를 렌더링합니다.

feat(service-account-badge): create service-account-badge

---

src/services/asset-inventory/service-account/ServiceAccountPage.vue
src/services/asset-inventory/service-account/config.ts
src/services/asset-inventory/service-account/modules/ServiceAccountBadge.vue
src/services/asset-inventory/service-account/type.ts

- 사용되지 않는 상태 제거
- is_managed를 위해 받아온 데이터 전처리
-> accountType이 TRUSTED 이며 tags.is_managed가 true 일 때 managed가 추가됩니다.

feat(service-account-table): add preprocessor for is_managed badge

---

src/lib/reference/referenceRouter.ts

referenceRouter에서 projectLinkFormatter의 id가 없을 시 빈 object를 반환하도록 했습니다. (vue-warning 해결)
다른 linkFormatter들도 warning 일어나는 곳이 있는지 확인 필요

fix(referenceRouter): fix empty object when project id is undefined

---

src/services/asset-inventory/service-account/ServiceAccountPage.vue
src/services/asset-inventory/service-account/type.ts

- account type에서 manage의 추가로 binding을 위한 모델이 클라이언트에서 사용되고 있어 따로 분리하였습니다. (ServiceAccountModelForBinding 라는 타입)
- account type 필터를 api에 연결하였습니다.
- 검색에서의 account type은 종민님께서 빼주신다고 하셨습니다.

feat(account-type-filter): add a filter for query to api & add sa type

---

package.json

기존 `serve:init` 은 비효율적인 것 같아, `node_modules` 를 삭제하는 부분을 따로 분리하였습니다.
으로 디펜던시 관련하여  BREAKING CHANGES 가 있을 때 `npm run serve:wipe` 하시면 될 것 같습니다

build: split `serve:init` to `serve:wipe`

---

src/services/asset-inventory/service-account/modules/ServiceAccountCredentialsForm.vue

AWS가 아니면 credentials에서 이 항목 숨기기

fix(service-account-credentials): hide attached trusted account when its not aws

---

packages/cloudforet/language-pack/console-translation.babel
packages/cloudforet/language-pack/en.json
packages/cloudforet/language-pack/ja.json
packages/cloudforet/language-pack/ko.json
src/services/asset-inventory/service-account/modules/ServiceAccountAccountType.vue

service account create 시에 있던 info 에서, here 에 대한 링크가 제공되지 않는 것으로 바뀌어, 삭제하였습니다.

fix(service-account): remove detail infos about account type

---

src/common/components/modals/DoubleCheckModal.vue
src/services/asset-inventory/service-account/service-account-detail/ServiceAccountDetailPage.vue
src/services/cost-explorer/budget/budget-detail/modules/BudgetDeleteModal.vue

- create `double-check-modal` in console
- apply `double-check-modal` to `service-account-detail-page` & `budget-delete-modal`
- need to remove square brackets on both sides of the account in babel edit

feat(double-check-modal): create double-check-modal & apply to service-account-detail-page

---

src/services/asset-inventory/service-account/modules/ServiceAccountCredentials.vue
src/services/asset-inventory/service-account/modules/ServiceAccountCredentialsForm.vue

서비스 어카운트 디테일 페이지에서 credential 수정 시, 기존 데이터가 폼에 적용되도록 개선함

fix(service-account): set origin data when edit credentials

---

packages/cloudforet/language-pack/console-translation.babel
packages/cloudforet/language-pack/en.json
packages/cloudforet/language-pack/ja.json
packages/cloudforet/language-pack/ko.json
src/services/asset-inventory/service-account/modules/ServiceAccountCredentialsForm.vue

Trusted Account 필드그룹에 help-text 추가

fix(service-account): add help text to trusted account

---

src/services/asset-inventory/routes.ts

- fix [QA-276](https://pyengine.atlassian.net/browse/QA-276) [RC1][Asset Inventory > Service Account] Page Permission을 가진 project Viewer 유저가 service Account detail에 접속 불가

fix(service-account): allow to access detail page with view permission (QA-276)

---

src/services/cost-explorer/CostExplorerLNB.vue

lnb의 Cost Analysis와 Budget 메뉴가 2depth로 렌더되어, `padding-left`간격이 벌어진 것으로 파악했습니다. 1depth로 렌더 되도록 수정하였습니다 [(QA-265)](https://pyengine.atlassian.net/browse/QA-265)
**전**
**후**

fix(cost-explorer): fix cost-explore-lnb rendering

---

src/services/asset-inventory/service-account/modules/ServiceAccountAttachedGeneralAccounts.vue

attached general accounts 에 누락된 sort options 를 추가하였습니다.
현재 PDatatable sort 기능에 문제가 있는 것 같습니다. 
해당 컴포넌트 수정 후 재확인이 필요합니다
Collector Page 에서 다수개 Collector 선택 > Selected Data 가 PDatatable 을 참조하는데, sort 가 작동하지 않음
Role Page 에서 한 개 Role 선택  > Details 하단의 API Policy Attachment 가 PDatatable 을 참조하는데, sort 가 작동하지 않음
스토리북에서도 작동하지 않습니다

fix(service-account): sorting attached general accounts [WIP]

---

src/services/cost-explorer/cost-analysis/modules/CostAnalysisHeader.vue

`<cost-analysis-query-filter />` 컴포넌트의 상하 간격이 디자인과 상이하였습니다. 해당 컴포넌트 상하에 `<p-button-modal />` 컴포넌트가 `display:inline-block;`으로 스타일링 되고 있어 default spacing을 가지고 있었습니다. 하여 `display:block;`으로 수정하여 간격을 조정했습니다. [(QA-269)](https://pyengine.atlassian.net/browse/QA-269)

fix(cost-analysis): fix 'cost-analysis-query-filter' vertical spacing

---

src/services/asset-inventory/service-account/ServiceAccountPage.vue
src/services/asset-inventory/service-account/service-account-add/ServiceAccountAddPage.vue
src/services/asset-inventory/service-account/service-account-detail/ServiceAccountDetailPage.vue
src/services/asset-inventory/service-account/service-account-detail/modules/ServiceAccountDeleteModal.vue

qa 277 작업에 1, 3번 문제입니다.
query search에서 valueHandlerMap에 따로 분리되어있던 provider 가 필터로 적용되지 않아 모든 검색결과가 나왔었습니다.
어카운트를 삭제 추가 시, 리스트페이지로 다시 돌아가는데 그때 추가/삭제된 provider로 가지 않고 default provider로 넘겨져 수정하였습니다.

fix(service-account): add provider filter to valueHandlerMap & add queryString for next path

---

src/services/auth/sign-in/modules/SignInLeftContainer.vue

[[RC1][Sign In] '여기로 문의주세요' 버튼이 클릭되지 않음](https://pyengine.atlassian.net/browse/QA-284) 이슈 수정
PAnchor 컴포넌트를 사용하여 mail link 를 걸면 동작하지 않습니다.
target 이 고정되어서 그렇습니다.
PAnchor 개선이 필요해보입니다.
우선 a tag를 사용하도록 수정해두었습니다.

fix(sign-in): change to use a tag with mail link(QA-284)

---

package-lock.json
package.json
src/services/cost-explorer/cost-analysis/CostAnalysisPage.vue

costExplorer에서 라우트 이동 시, cost Analysis의 필터들이 store에 남아있어 init과정에 추가적인 조건을 부여하였습니다.
기존엔 queryString이 존재하거나 저장된 쿼리에대해 초기화를 진행하는 두가지 분기만 있었고,
이번 PR에서 queryString과 queryId 둘다 없을땐 store를 초기화하도록 수정하였습니다.

fix(cost-analysis-page): initializes store when approaching url without queryString

---

src/services/cost-explorer/budget/modules/budget-form/budget-form-amount-plan/BudgetFormAmountPlanAutofillModal.vue

budget 생성 시, 예산 자동 입력 모달의 visible state가 작동하지 않아 수정하였습니다.

fix(budget-auto-fill-modal): fix non-working visible state (qa-288)

---

packages/cloudforet/core-lib/src/space-connector/api.ts
src/common/composables/error/errorHandler.ts

- [promise case error handling PR](https://github.com/cloudforet-io/console/pull/154) 의 내용을 일부 revert 했습니다. 해당 PR은 근본 원인을 해결한 것이 아니라 일어나는 현상만 막았기 때문입니다.
- promise error 를 반환하는 root cause 를 찾아 해결했습니다. api.ts 에서 axios response 인터셉터에 프라미스 객체로 감싸서 에러를 리턴해야 합니다. 그런데 `this.handleRequestError` 함수가 Promise 객체를 리턴하는 함수로 바뀌면서, 프라미스 객체가 다시 한 번 프라미스 객체를 감싸는 형태로 리턴하게 되었습니다. 
이 문제를 수정하였습니다.

fix(api, error-handler): do not reject error as promise instance

---

src/common/components/modals/DoubleCheckModal.vue
src/services/asset-inventory/service-account/service-account-add/ServiceAccountAddPage.vue

- QA-291
- 이름 앞뒤에 공백이있는 service account 를 삭제할 때 생기는 이슈 해결
- service account 등록 시 이름에 `trim()` 적용 
- 삭제 시 비교 대상이되는 기존 `verificationText` 및 `inputText` 값에 모두 `trim()` 적용
- 추후 백엔드 측에서도 trim 처리할 예정이지만 현재 만들어진 service account 와 혹시 모를 상황을 위해 `double check modal` 에서 관련된 모든 부분에 `trim()` 처리를 하였음 
(추후 수정 필요  ex. `inputText`에서는 trim을 적용하지만 `verificationText`는 공백이 없는 값만 생성이 될 것이므로 trim 제거)

fix(double-check-modal): add trim for service account name space issue

---

packages/cloudforet/core-lib/src/space-connector/api.ts

access token 만료 시, 401이 뜨는경우에 refreshAccessToken 함수가 실행되는데 이때 리턴하는 값에 따라 던져지는 Error타입이 다릅니다.
이 때, 리턴 타입에 false, true, undefined가 있었는데 이로인해 분기문이 잘못 타져 undefined를 제거하였습니다.
토큰 재발급을
했으면 true
하고있어도 true
못헀으면 false
실패했어도 false

fix(space-connector): fix return value of refreshAccessToken function

---

src/services/info/notice/modules/NoticeForm.vue

전체 도메인 대상의 공지사항일 경우, 수정 시 domain 항목 비우기
[[Info > Notice] For posts created for the all domain, the name is not visible on the notice Edit page](https://github.com/spaceone-dev/feedback/issues/144)

fix(notice): do not show domain-id when its for all domain

---

src/common/composables/file-uploader/index.ts
src/lib/file-manager/index.ts
src/services/info/notice/modules/NoticeForm.vue

- `useFileUploader` 훅 추가
- file add 시에 `domain_id` 정보를 reactive하게 반영하기 위함
- 백엔드 개발이 아직 완료되지 않아서, 테스트 후 머지하겠습니다

feat(file-manager): give domain information when adding file

---

src/common/modules/navigations/gnb/modules/gnb-recent-favorite/modules/GNBFavorite.vue
src/common/modules/navigations/gnb/modules/gnb-recent-favorite/modules/GNBRecent.vue
src/services/administration/iam/role/modules/role-managemnet-table/modules/RoleDeleteModal.vue
src/services/administration/iam/user/modules/user-management-tab/UserAssignedRole.vue
src/services/asset-inventory/cloud-service/CloudServicePage.vue
src/services/cost-explorer/budget/budget-detail/modules/budget-info/BudgetDetailInfo.vue
src/services/cost-explorer/budget/modules/budget-list/BudgetListCard.vue
src/services/cost-explorer/budget/modules/budget-toolbox/BudgetToolbox.vue
src/services/cost-explorer/cost-analysis/modules/CostAnalysisDataTable.vue
src/services/cost-explorer/widgets/BudgetUsageWithForecast.vue
src/services/dashboard/modules/FavoritesWidget.vue
src/services/project/ProjectPage.vue
src/services/project/project-detail/project-member/modules/ProjectMemberTab.vue
src/store/modules/reference/getters.ts
src/store/modules/reference/project-group/actions.ts
src/store/modules/reference/project-group/index.ts
src/store/modules/reference/project-group/type.ts
src/store/modules/reference/project/type.ts
src/store/modules/reference/provider/actions.ts

- reference store에서 projectGroup의 초기값을 `{}`에서 `undefined`로 변경
- reference 데이터에 `key` property 추가

refactor(store): change init data of projectGroup from {} to undefined

---

src/services/asset-inventory/service-account/modules/ServiceAccountAttachedGeneralAccounts.vue

서비스 어카운트 디테일 페이지의 Attached General Accounts 항목에서 초기 로딩 시 짧게 'No Data' 텍스트가 보이는 버그 수정

fix(service-account): hide 'no data' at initial loading

---

src/services/cost-explorer/cost-analysis/modules/CostAnalysisGroupByFilter.vue
src/services/cost-explorer/cost-analysis/modules/CostAnalysisGroupByFilterMore.vue
src/services/cost-explorer/cost-analysis/modules/CostAnalysisGroupByFilterMoreModal.vue
src/services/cost-explorer/type.ts

more groupby 버튼 생성 (mock 데이터임)
기존 filter는 string[]로 저장되었는데, 태그는 object입니다.
기존
```typescript
{ regions: ['ap-north2'], projects: ['p-sdfsf', 'p-12313'] }
```
```typescript
{ tags: [{name: 'team', label: 'Team' }] }
```
타입 에러로 지금은 태그도 일단 name만 string[]로 저장하도록 했는데...고민중

fix(cost-analysis): add more group-by buttons

---

src/services/asset-inventory/service-account/ServiceAccountPage.vue

서비스 어카운트 페이지에서, 데이터 테이블 row hover 시 pointer:cursor로 보이도록 수정
(기존 default pointer는 클릭 가능한 아이템인지 유저가 모를 수 있음)

fix(service-account): set `cursor: pointer` to dataTable row

---

src/services/asset-inventory/service-account/modules/ServiceAccountProviderList.vue

- add low count provider (under 6) case style
before
- there is space, but scroll-bar occurs.
- cause is grid box have 6 columns.
after
- other way to solve this issue ?
- is `low-count-provider-list` class-name appropriate ?

fix(service-account-provider-list): fix low count provider layout issue

---

packages/cloudforet/core-lib/src/space-connector/api.ts
src/services/auth/authenticator/index.ts

버그를 해결하기 위해 SignIn 시 `API.unsetRefreshingState()` 하는 코드를 추가했는데, 사전 지식 없이는 코드를 이해하기 어렵다는 의견이 있었습니다.
이해의 장벽을 낮추기 위해 해당 코드를 좀더 관련성 있는 파일로 옮겼습니다.

fix(space-connector): use `unsetRefreshingState` in `setToken`

---

package-lock.json
src/common/modules/popup/notice/NoticePopup.vue
src/common/modules/popup/notice/modules/NoticePopupItem.vue

세션 만료 혹은 로그아웃 등으로 token 이 expired 되었을 때,
notice-popup 에서 don't show me again 클릭 시,
userConfig 가 set 되지 않아, 팝업이 다시 뜨는 버그가 존재하였고,
이에 대한 해결 방법으로 token 이 expired 되었을 때 popup 을 숨기는 것으로 조치하였습니다.
---
토큰 만료 시 다시 로그인하는 케이스가 더 많을 것 같다고 판단하였고, 
app.vue 에 물려있는 파일이라 렌더링에 조금이나마 부하를 방지하고자 
`v-show` 로 작성하였습니다.

fix(notice-popup): do not show popup when session is expired

---

package-lock.json
package.json
src/services/asset-inventory/service-account/modules/ServiceAccountCredentialsForm.vue

- 미리내 버전을 올렸습니다. JsonSchemForm의 genrate_id form이 편집 가능하도록 기획 변경사항에 대응하기 위함입니다.
- 추가적으로 ServiceAccountCredentialsForm.vue 에서 text input 컴포넌트에 width를 66%로 고정하여 generate_id 폼만 더 늘어나는 현상이 있었습니다. 따라서 text input컴포넌트의 width는 100%로 부여하고, 컨테이너(json schema form 컴포넌트의 루트 div)에 width를 66% 고정하는 방식으로 수정하였습니다.
https://user-images.githubusercontent.com/26986739/195279656-b7b4fcad-d986-409f-a168-2a250094eadd.mov
- json schema form 은 스키마에 따라 폼을 렌더하는 것이므로 내부의 요소에 css를 부여하는 경우는 신중해야 합니다.
- 내부 요소에 전체적으로 특정한 width, height를 부여해야 하는 경우에는 컨테이너에 값을 부여함으로써 해결할 수 있는 방법이 없는지 먼저 고민해보면 좋을 것 같습니다.

hotfix(service-account): make generate_id editable

---

src/router/index.ts

router beforeEach에서, `routeAccessLevel`이 `userAccessLevel`보다 높으면
1) 토큰을 refresh하고
2) refresh에 실패하면 signOut 시킵니다.
토큰이 이미 있는 경우에도 이러한 과정을 거치기 때문에 불필요한 refresh라 간주하여 `isTokenAlive`가 false일 때만 실행하도록 수정했습니다.

fix(router): check `isTokenAlive` before refreshing token

---

package-lock.json
package.json
src/common/modules/tags/tags-panel/TagsPanel.vue
src/common/modules/tags/tags-panel/modules/TagsOverlay.vue
src/services/asset-inventory/cloud-service/cloud-service-detail/modules/CloudServiceTagsPanel.vue

이번 Tag 개선 사항을 반영하기위해 TagsPanel을 조금 수정하였습니다.
목적
- 기존 일관된 tag의 형태와 다른 type과 provider에대한 추가 속성이 부여된 tag들을 보여줘야함 (api도 따로 만들어짐)
개선 방식
- 태그 수정 overlay가 그대로 사용되어야 해서, 새로운 컴포너트를 만들지 않고 기존 TagsPanel을 수정했습니다.
- TagsPanel의 props들([custom-fields, custom-items, custom-tags])을 추가 하였고, 이들이 있을 때 isCustomMode가 `true`입니다.
- custom-xxx props가 추가된 이유는 패널에 보여지는 태그는 기존 패널 내부의 api요청과는 다른 api를 쏴야하기 때문입니다.
(기존에는 custom 태그들만 보여졌고, 개선 후엔 Managed 태그를 포함하여 보여줘야하기 때문에 다른 api가 필요)
다음 PR에서 table의 col 관련 slot을 외부에서 반영 가능하도록 TagsPanel의 추가 개선이 진행 되어야합니다.(현재 데이터만 테이블에 보여지고 있으며, 배지 UI가 반영되어있지 않습니다)
혹시, 기존 TagsPanel을 사용하지 않는 방향으로 가야될지 궁굼합니다.

feat(cloud-service-tags-panel): improve TagsPanel for reflect improvements

---

src/common/modules/tags/tags-panel/TagsPanel.vue
src/services/asset-inventory/cloud-service/cloud-service-detail/modules/CloudServiceTagsPanel.vue

- cloudServiceTagsPanel에서 type, provider 데이터에 badge를 적용하였습니다.

feat(cloud-service-tags-panel): apply badge ui to table value

---

src/services/asset-inventory/service-account/modules/ServiceAccountCredentialsForm.vue

Attach Trusted Account 항목이 'no'라면, Trusted Account 인풋박스를 숨김

fix(service-account): hide trustedAccount input when select `no`

---

src/services/cost-explorer/cost-analysis/lib/helper.ts
src/services/cost-explorer/cost-analysis/modules/CostAnalysisChart.vue
src/services/cost-explorer/cost-analysis/modules/CostAnalysisFilterItem.vue
src/services/cost-explorer/cost-analysis/modules/CostAnalysisQueryFilter.vue
src/services/cost-explorer/cost-analysis/type.ts
src/services/cost-explorer/cost-dashboard/lib/helper.ts
src/services/cost-explorer/lib/config.ts
src/services/cost-explorer/modules/CostExplorerSetFilterModal.vue
src/services/cost-explorer/store/cost-analysis/actions.ts
src/services/cost-explorer/store/cost-analysis/getters.ts
src/services/cost-explorer/store/cost-analysis/index.ts
src/services/cost-explorer/store/cost-analysis/mutations.ts
src/services/cost-explorer/store/cost-analysis/type.ts
src/services/cost-explorer/type.ts

cost-explorer > cost-analysis 스토어에서 filters의 타입을 `object`에서 `object[]`로 바꾸었습니다.
**바꾸게 된 이유**
기존에 저장되던 데이터는 이렇습니다.
```typescript
{
region_code: ['ap-north-02', 'ap-south-01'],
provider: ['aws', 'google_cloud'],
}
```
그러나 tags와 additional_info 등, key:value 타입의 데이터가 들어오게 되면서, 다음과 같이 바꾸게 되었습니다.
```typescript
[
{ category: 'region_code', resourceName: 'ap-north-02', value: 'ap-north-02' },
{ category: 'region_code', resourceName: 'ap-south-01', value: 'ap-south-01' },
// tags의 경우
{ category: 'tags', resourceName: 'tags.team', key: 'team', value: 'spaceOne' },
]
```
`object[]`가 그대로 url에 들어가게 되는데 너무 데이터가 커서 좀 걱정입니다;;
url로 보낼 땐 데이터를 다시 이렇게 컨버팅할까 생각중이에요.
```typescript
{
region_code: ['ap-north-02', 'ap-south-01'],
provider: ['aws', 'google_cloud'],
'tags.team': ['spaceOne'],
}
```

fix(cost-explorer): change filters' type from `object` to `object[]`

---

package-lock.json
package.json
src/common/modules/survey/SurveyModal.vue
src/services/administration/iam/role/update-role/modules/RoleUpdatePageBaseInformation.vue
src/services/asset-inventory/service-account/modules/ServiceAccountAccountType.vue
src/services/cost-explorer/budget/modules/budget-form/budget-form-amount-plan/BudgetFormAmountPlanUnitSelect.vue
src/services/cost-explorer/cost-dashboard/cost-dashboard-create/modules/CostDashboardCreateWithDashboard.vue
src/services/cost-explorer/cost-dashboard/cost-dashboard-create/modules/CostDashboardCreateWithLayout.vue
src/services/project/project-detail/project-alert/project-alert-settings/modules/ProjectAutoRecoveryUpdateModal.vue
src/services/project/project-detail/project-alert/project-alert-settings/modules/ProjectNotificationPolicyUpdateModal.vue
src/services/project/project-detail/project-alert/project-webhook/modules/WebhookAddFormModal.vue

https://github.com/cloudforet-io/mirinae/pull/85
tab-index 를 반영하여 keyboard event (선택하는 ux) 를 적용하였습니다.
구조적인 한계로, `SelectCard` 의 sibling 에 다른 요소가 섞여있는 경우, (ex: costdashboardcreate) 작동하지 않습니다.
우선 TODO 주석처리 해 두었습니다. 양해 부탁드립니다 (__)
`SelectCard` 의 silbing 에 다른 요소가 섞여있는 경우, 어떻게 해야할 지 고민입니다.
`classname` 에 `p-select-card` 가 있는지 체크하는 로직을 섞으면 바로 해결될 것 같기는 한데,
구조가 많이 복잡해질 것 같아 걱정됩니다

feat(select-card): apply `tab-index` for keyboard event

---

src/services/cost-explorer/budget/modules/budget-list/BudgetList.vue
src/services/cost-explorer/budget/modules/budget-stat/BudgetStat.vue
src/services/cost-explorer/widgets/BudgetUsageSummary.vue

상위/하위 컴포넌트에서 모두 `filters`라는 변수가 쓰이는데 둘의 타입이 달라 구분하기 위해 하위 props 이름을 바꾸었습니다.

chore(budget): change props name from `filters` to `queryStoreFilters`

---

src/services/cost-explorer/cost-analysis/modules/CostAnalysisChart.vue
src/services/cost-explorer/modules/CostExplorerFilterTags.vue
src/services/cost-explorer/modules/CostExplorerSetFilterModal.vue

ViewFilterModal에서는 태그 삭제 버튼을 숨겨야 하기 때문에 `deletable` props를 적용했습니다.

fix(cost-explorer): add `deletable` props to filter tags

---

package-lock.json
package.json
src/services/cost-explorer/cost-analysis/modules/CostAnalysisFilterItem.vue
src/services/cost-explorer/cost-analysis/type.ts

- cost analysis filter modal에 `tags`와 `additional-info` 필터가 추가되었습니다.
(새로 개발된 `p-query-search-dropdown`이 적용되었습니다.)
- `p-query-search-dropdown`은 `tags`와 `additional-info` type의 분기가 적용됩니다.
- `tags`와 `additional-info`에 적용되기 위한 `querySearchHandlerState`가 추가되었습니다.
- `tags`와 `additional-info`의 리소스를 받아오기 위한 api요청이 추가되었습니다.

feat(cost-analysis-filter-item): add filter in tags and additional-info case

---

src/services/asset-inventory/AssetInventoryLNB.vue

문제: Role에서 asset inventory -> cloudService에 따로 권한을 주지 않았는데, lnb에서 노출되고 있었음. (lnb컴포넌트에서 권한 체크 함수를 타지 않고있었음)
asset inventory의 LNB에서 menuSet 설정 시, cloudService만 따로 `filterLNBMenuByPermission` 을 타지 않고 computed되고 있었습니다. 
cloudService의 경우 디테일 페이지를 위한 lnb의 추가적인 뎁스가 존재했는데 이 부분에서 누락되었던 것 같습니다.

fix(asset-inventory): fix permission bug in LNB

---

src/services/cost-explorer/cost-analysis/modules/CostAnalysisChart.vue
src/services/cost-explorer/cost-analysis/modules/CostAnalysisDataTable.vue
src/services/cost-explorer/cost-analysis/modules/CostAnalysisGroupByFilterMoreModal.vue
src/services/cost-explorer/widgets/lib/widget-data-helper.ts

more group by api 데이터 적용
보낼 땐 'tags.Name' 으로 보내고, 받을 땐 'tags_Name'으로 옵니다. 이에 따른 대응이 되어 있는데, 다른 분들이 볼 때 이게 뭐지 싶을 것 같아 설명을 추가합니다.
api request는 group_by 항목을 **string[]** 로 보내 dot이 들어가도 괜찮지만,
api response는 **object property**여서 dot을 사용하지 못하여 이런 값이 옵니다.

fix(cost-anlysis): update `more_group_by` to get api data

---

src/services/cost-explorer/modules/CostExplorerFilterItem.vue

- `query-search-dropdown` 이 `collapsible-pannel`의 css를 상속받는 문제 ([QA-310-1](https://pyengine.atlassian.net/jira/software/projects/QA/boards/23?selectedIssue=QA-310))
-  `v-deep`으로 `word-beak` 초기화로 해결하였읍니다
before
after

fix(cost-explorer-filter-item): fix dropdown key word break issue

---

src/services/cost-explorer/cost-analysis/CostAnalysisPage.vue
src/services/cost-explorer/cost-analysis/lib/config.ts
src/services/cost-explorer/cost-analysis/modules/CostAnalysisChart.vue
src/services/cost-explorer/cost-analysis/modules/CostAnalysisChartQuerySection.vue
src/services/cost-explorer/cost-analysis/modules/CostAnalysisDataTable.vue
src/services/cost-explorer/cost-analysis/type.ts
src/services/cost-explorer/store/cost-analysis/actions.ts
src/services/cost-explorer/store/cost-analysis/getters.ts
src/services/cost-explorer/store/cost-analysis/mutations.ts
src/services/cost-explorer/store/cost-analysis/type.ts
src/services/cost-explorer/type.ts
src/services/cost-explorer/widgets/lib/widget-data-helper.ts

- CostAnalysisChart에서 filter, legend 부분 모듈로 분리
- 이번에 새로 추가된 `moreGroupBy`가 url query에 저장되도록 함
> 커밋 별로 보시는 것을 추천합니다. 그리고 첫번째 커밋은 안 보셔도 됨다. 그냥 코드분리라서.

fix(cost-analysis): split codes and save `moreGroupBy` to url query

---

src/common/modules/tags/tags-panel/TagsPanel.vue
src/services/asset-inventory/cloud-service/cloud-service-detail/modules/CloudServiceTagsPanel.vue

custom tags만 수정가능 함으로 수정을 위해 overlay에서도 custom tags만 나타나야합니다.
(기존 managed 태그 까지 나타나 저장시 커스텀 태그로 다시 저장되었습니다.)
현재 태그 리스트 쪽에서 어떤 필터를 지정하여도 custom tag만 나타나도록 수정하였습니다.

fix(cloud-service-tags): fix so that only custom tags appear in overlay

---

src/services/asset-inventory/cloud-service/cloud-service-detail/modules/cloud-service-usage-overview/CloudServiceUsageOverviewDetailModal.vue

- [QA-300 [RC1][Cloud Service > Service > Show Charts] 차트 깜빡임](https://pyengine.atlassian.net/browse/QA-300) 이슈 해결
- 필터도 함께 watch 하여 이전 필터와 같으면 데이터를 다시 불러오지 않게 함으로써 차트 깜빡임 이슈 해결
- 그 밖의 UX 개선
- 모달을 닫을 때 항상 차트 데이터를 비워주던 것을, 모달이 닫혀있을 때 스키마가 이전 스키마와 다른 경우에 비우도록 변경. 이렇게 함으로써 스키마와 필터가 변경되지 않은 경우에, 데이터를 다시 가져오지 않고 재사용 가능하도록 함.
- 모달을 닫을 때 loading 상태를 true로 바꿔줌으로써, 모달이 뜰 때 일시적으로 loading UI가 아닌 빈 화면이 보이는 어색함을 해소함.
https://user-images.githubusercontent.com/26986739/196943682-088f8142-fc05-4a4e-9082-e86ef542bd50.mov

fix(cloud-service): do not get data when filters are the same in overview detail(QA-300)

---

src/common/modules/tags/tags-panel/TagsPanel.vue
src/services/asset-inventory/cloud-service/cloud-service-detail/modules/CloudServiceTagsPanel.vue

어째서인지.. 오전엔 tagPanel에서 custom tag만 불러오는걸로 확인한 api 가 managed까지 불러와 직접 필터하는 로직을 추가하였습니다.

fix(cloud-service-tags-panel): add filtered custom tags to Tags panel

---

packages/cloudforet/core-lib/src/space-connector/index.ts
packages/cloudforet/core-lib/src/space-connector/service-api.ts
packages/cloudforet/core-lib/src/space-connector/token-api.ts

console api endpoint가 2개로 나뉘어 관리되어야 하는데, 토큰은 하나로 관리되어야 해서 
service-api와  token-api를 분리함.
이후에 따라올 작업을 위한 리팩토링.

refactor(core-lib): separate token api and service api

---

src/common/components/widgets/modules/WidgetFrame.vue

Widget Frame의 마크업위주의 작업입니다.
디자인 시스템의 PCard를 사용하지 않고 직접 작성하였습니다.
- header: header right 슬롯이 존재합니다. 아직 디자인 작업 진행중이라 슬롯이 아닌 selectButton(ds 없는 기능으로 추가되어야 함)으로 대체될 수 있습니다. 
- body: 위젯의 **차트**와 **테이블**이 추가 될 **default슬롯**입니다.
- footer: 위젯의 필터입니다. 
- 오늘 회의하시는거 조금 들었는데, 아마 goupby같은 필터가 추가될 수 있다고 합니다.
- date는 type이 range로 되어있습니다. (혹시 다른 타입 커스텀이 필요하다면 props를 뚫겠습니다)
- footer-right 슬롯이 존재합니다.

feat(widget-frame): create widgetFrame (only markup)

---

src/services/asset-inventory/service-account/modules/ServiceAccountProviderList.vue

- service account 페이지의 provider list에서 하단에 스크롤이 없을 때 스크롤이 생기는 이슈를 해결했습니다
- `overflow-x: scroll` => `overflow-x: auto`

fix(provider-list): solve scroll issue where there is no need for scroll

---

src/common/components/widgets/modules/WidgetDataTable.vue
src/common/components/widgets/modules/WidgetFrame.vue
src/common/components/widgets/type.ts

일단 마무리 된 부분까지 먼저 올렸습니다.
- WidgetFrame에 필터프롭을 연결
- widgetDataTable 생성
- 기존 costExplorer에서 위젯 만들 때 사용하던 CostDashboardDataTable을 그대로 가져온 컴포넌트입니다.
- 추후 스펙이 확정되면 그때 수정하고, 현재는 마크업만 진행하기위해 복붙하기로 결정하였습니다.
WidgetFrame에서 slot은 3가지가 있습니다.
- defalut slot (body에 해당합니다.)
- header-right
- footer-right
예시
구조설계에대한 제안은 언제나 환영입니다

feat(widget): configure Widget Default Components

---

src/common/modules/navigations/gnb/GNB.vue
src/common/modules/navigations/gnb/modules/gnb-menu/GNBMenu.vue
src/common/modules/navigations/gnb/modules/gnb-menu/GNBSubMenu.vue
src/common/modules/navigations/gnb/modules/gnb-menu/modules/dashboard-recent-favorite/modules/GNBDashboardFavorite.vue
src/common/modules/navigations/gnb/modules/gnb-menu/modules/dashboard-recent-favorite/modules/GNBDashboardRecent.vue
src/services/project/project-detail/project-summary/modules/ProjectTrustedAdvisor.vue

- 기존 GNBRecentFavorite에 들어가는 컴포넌트를 일단 복사하고 GNBMenu에 맞게 수정하였습니다.
- 마크업만 존재하는 상태입니다. 
위와 같은 subMenu가 모든 탭에 동일하게 존재해야 해서 PTab컴포넌트의 모든 탭에 공통 적용되는 slot을 하나 추가하면 좋을 것 같습니다.
혹시, 슬롯이 추가되었을 때 우려되는 점이 있다면 코멘트 부탁드려요

feat(gnb-dashboard): create dashboard-menu as custom-menu-wrapper

---

package-lock.json
package.json
src/common/modules/navigations/gnb/modules/gnb-menu/GNBMenu.vue
src/common/modules/navigations/gnb/modules/gnb-menu/modules/dashboard-recent-favorite/modules/GNBDashboardFavorite.vue
src/common/modules/navigations/gnb/modules/gnb-menu/modules/dashboard-recent-favorite/modules/GNBDashboardMenu.vue

대시보드로 이동하는 메뉴를 푸터에 추가하였습니다. 일단 이동에 불편함이 없도록 라우팅 작업만 바로 올렸습니다. 메뉴가 안꺼진다거나 이런 버그가 있을 예정인데, 다음 기능과 함께 수정하여 올리겠습니다.
(이전까지 url로 직접 이동해주셔서 감사..)
GNBMenu가 앞으로 천천히 두꺼워질 것 같아 dashboard의 favorite과 recent도 따로 묶어 분리하였습니다.

feat(gnb-dashboard): add dashboard routing to gnbDashboardMenu footer

---

package-lock.json
package.json
public/config/default.json
src/lib/site-initializer/amcharts5.ts
src/lib/site-initializer/index.ts

amcharts5 도입
- 훨씬 빨라짐 (SVG -> canvas)
- 훨씬 가벼워진 라이브러리 (22.8MB -> 14.9MB)
- 최신화된 문서들
- 기존에 차트 옵션들을 한줄 한줄 코드로 작성했던 것과 달리, object로 작성할 수 있어 공통 부분을 config화 하기에 훨씬 수월
- 모든 것(차트)은 `root`로부터 시작됨. 기존의 chartRef가 `root`라고 보면됨. 실제 div의 id나 element를 받아 생성 가능.
- `root`는 core 패키지의 일부로, 차트를 만들 땐 항상 `root`를 먼저 생성해야 함
```typescript
const chartRoot = am5.Root.new(chartContext);
const chart = chartRoot.container.children.push(am5xy.XYChart.new(chartRoot, {
panX: true,
panY: true,
wheelX: 'panX',
wheelY: 'panY',
}));
```
- root가 있어야 하기 때문에 기존처럼 site-initializer에서 theme 글로벌로 적용 불가능 (헬퍼 함수나 훅으로 만들어야 할듯)

feat(amcharts5): add `amcharts5` initAmcharts5 to site-initializer

---

src/common/modules/navigations/gnb/modules/gnb-menu/modules/dashboard-recent-favorite/modules/GNBDashboardFavorite.vue
src/common/modules/navigations/gnb/modules/gnb-menu/modules/dashboard-recent-favorite/modules/GNBDashboardMenu.vue
src/common/modules/navigations/lnb/LNB.vue
src/common/modules/navigations/lnb/modules/LNBMenuItem.vue
src/common/modules/navigations/lnb/type.ts
src/services/dashboards/DashboardsContainer.vue
src/services/dashboards/DashboardsLNB.vue
src/services/dashboards/route-config.ts
src/services/dashboards/routes.ts

Dashboards LNB 마크업 작업
- LNB의 `MENU_ITEM_TYPE`에 `top-title`과 `favorite-only`가 추가되었습니다.
- Top-title 이 한번 이상 사용됨에 따라 메뉴 타입에 추가되었으나, 현 Dashboards LNB에만 우선 적용되었습니다.
(다른 LNB에서는 차근차근 리펙토링이 필요합니다.)
- LNB의 `header` 도 아이콘이 추가됨에 따라 변경이 필요합니다. 현재는 `slot`으로 임시 작업해놓았고 추가 작업예정입니다.
- Favorite only toggle이 LNB에 추가되었습니다. 쨴님이 앞으로 _"비슷한 토글이 다른 목적으로 추가되거나 여러개가 추가될 수 있다"_ 가능성을 내비치셔서 `LNBMenuItem`의 스펙으로 추가하진 않았습니다.
Dashboards All page에 해당하는 path가 변경되었습니다. `/dashboards` => `/dashboards/all`
**`GNBDashboardFavorite`, `GNBDashboardMenu` 파일은 무시하셔도 됩니다.**

feat(dashboards): create dashboards LNB & make some changes at routes

---

package-lock.json
src/services/dashboards/dashboard-create/DashboardCreatePage.vue
src/services/dashboards/dashboard-create/modules/DashboardScopeForm.vue

Continues https://github.com/cloudforet-io/console/pull/295#discussion_r1018582432
네이밍 컨벤션이 맞지 않은 부분 수정하였습니다.
또한 잘못된 project-select-dropdown 에서 emit 되는 type 을 수정하였습니다. (`Array<string>` -> `Array<ProjectItemResp>`)
dashboard-create-page(project) <-> dashboard-scope-form(emit 시 projects를 project로 컨버팅) <-> project-select-dropdown(projects)

fix(dashboard-create): fix wrong naming, types on dashboardScopeForm

---

src/common/modules/navigations/gnb/modules/gnb-menu/modules/dashboard-recent-favorite/modules/GNBDashboardFavorite.vue
src/common/modules/navigations/gnb/modules/gnb-menu/modules/dashboard-recent-favorite/modules/GNBDashboardRecent.vue
src/store/modules/favorite/actions.ts
src/store/modules/favorite/mutations.ts
src/store/modules/recent/actions.ts
src/store/modules/recent/mutations.ts

gnb-menu에서 favorite과 recent의 api 를 연결하였습니다.
현재 dashboard에 대한 api가 나오지 않은 상태여서, dashboardList는 더미로 진행하였습니다.
- favorite add/remove/list
- favorite sorting
- recent list
추후 dashboard api가 나오면 추가 수정이 필요한 부분
- 기존 더미데이터에대한 데이터 삭제
- projectDashboard, domainDashboard list와 연동
- lnb에서 추가 삭제한 favorite 반영확인
- recent add 로직 추가

feat(dashboard-menu-api): apply api for gnb dashboard menu

---

src/services/cost-explorer/cost-dashboard/cost-dashboard-customize/modules/CostDashboardCustomizeDefaultWidgetTab.vue

cost explorer dashboard custom modal 에서 require 관련 발생 에러를 처리하였습니다.
svg 이미지는 아직 작업 진행 중에 있습니다.

fix(cost-widget): require error in cost-widget customize tab [WIP]

---

src/common/modules/navigations/gnb/modules/gnb-menu/GNBMenu.vue
src/services/dashboards/widgets/_components/WidgetFrame.vue

WidgetFrame에 full 사이즈 옵션과 width를 받아 설정할 수 있도록 수정하였습니다.
width는 WidgetSize 별로 추가적인 config를 구성하면 좋을 것 같은데, 민서님 Dashboard 위젯 정렬때 편한 구조로 정하는게 좋아보여 일단 값으로만 추가하였고 따로 type, config는 생성하지 않았습니다.
(추가로 gnb에 클릭 범위 수정 스윽 넣었습니다)

feat(widget-frame): add width prop and full size markup

---

src/services/cost-explorer/cost-dashboard/cost-dashboard-customize/modules/CostDashboardCustomizeDefaultWidgetTab.vue

Continue from #318 
`<template>` 내에서 import 혹은 async 를 사용할 수 없어서, 
init 시에 imgList 를 state 에 저장한 후
`index` 로 접근하도록 변경하였습니다.

fix(cost-widget): fix widget image broken

---

package-lock.json
package.json
src/services/dashboards/routes.ts
src/services/dashboards/widgets/WidgetsPreviewPage.vue
src/services/dashboards/widgets/monthly-cost/MonthlyCostWidget.vue
src/services/dashboards/widgets/use-widget-data.ts
vite.config.js

- vite-plugin-vue-type-imports 모듈을 추가하였습니다. 
- 추가한 이유 참고: https://github.com/vuejs/core/issues/4294
- 뷰에서 공식적으로 해결해주기 전까지 위 모듈을 사용할 예정입니다.
- use-widget-data 훅을 추가하였습니다.
- 개별 위젯에서 config와 data들을 병합하기로 하였으므로, 이에 따라 모든 위젯에 동일하게 사용될 것으로 예상되는 값들을 이 훅이 리턴하도록 반영하였습니다.
- 예시로 monthly cost 위젯 컴포넌트를 script setup 방식으로 작성했습니다.
- script setup 작성 방식 및 이를 도입한 이유 참고: https://vuejs.org/api/sfc-script-setup.html
- dashboards/widgets/:widgetId path로 들어왔을 때 특정 위젯을 띄워줄 수 있도록 WidgetPreviewPage 를 추가하였습니다.
- 테스트용으로 추가했으나, 이후 widget detail view로 발전 가능성이 있어보입니다.
- ![image](https://user-images.githubusercontent.com/26986739/202666606-f628517b-6038-4fe0-9d10-728f7006fe6a.png)
위젯 컴포넌트들은 script setup 방식으로 작성하고 싶습니다.
- props 이중으로(typescript, props 객체) 작성 및 관리하지 않고, typescript 하나만으로 해결하기 위해
- Vue3에서 지원하는 보다 간결한 문법이며, …

feat: add use-widget-data hook & write monthly cost widget with script setup as sample

---

src/services/dashboards/widgets/_components/WidgetFrame.vue
src/services/project/ProjectPage.vue

- We don't need to think about portals anymore.(slot is added.)
- The added attributes were applied as the structure of the 'Widget Frame' was changed.
- The displayed value varies depending on the value passed through 'props.dateRange'.
Features to add
- Edit mode is added.
- Edit/delete is opened through modals.
- The full view feature is added.
----
- 포탈은 사용되지 않습니다. (slot이 추가됨)
- '위젯 프레임'의 구조가 변경됨에 따라 추가된 속성들을 적용하였습니다.
- `props.dateRange`를 통해 넘어오는 값에 따라 디스플레이되는 값이 다릅니다.
추가될 예정인 기능
- editMode가 추가될 예정입니다.
- edit/delete는 모달을 통해 열어줍니다.
- 전체보기 기능이 추가됩니다.
- ![image](https://user-images.githubusercontent.com/50662170/202998917-da58b3c4-8a11-4251-9c22-4dd416680e94.png)

fix(widget-frame): refactoring for changed specifications

---

src/common/composables/amcharts5/index.ts
src/services/dashboards/widgets/WidgetsPreviewPage.vue
src/services/dashboards/widgets/_base/base-pie/BasePieWidget.vue
src/services/dashboards/widgets/config.ts
src/services/dashboards/widgets/monthly-cost/MonthlyCostWidget.vue
src/services/dashboards/widgets/use-widget-lifecycle.ts
src/services/dashboards/widgets/use-widget-state.ts
src/services/dashboards/widgets/view-config.ts

- Add `useWidgetLifecycle` hook for initiating widget
- Add `view-config.ts` to manage constants that are needed for display contents, not the real data
- Rename `useWidgetData` to `useWidgetState`
- add `currencyRates` to `widgetProps`
- update `useAmchart5` hook argument `chartContext` to take `null` and `undefined`. If `chartContext` is not given, hook automatically generate it.
- implement `basePieWidget` as a reference for widget implementation and usage of hooks
- add refresh button to `widgetPreviewPage` for test
Result:
https://user-images.githubusercontent.com/26986739/203456540-2ec55689-3499-406e-a004-ece7017dd078.mov
I guess there is some bugs in `DataLoader` component that the loader does not disappear even if the `loading` prop is `false`. 
I will check it on Mirinae project …

feat: add widget lifecycle hook and update basePieWidget for reference 

---

src/services/dashboards/widgets/WidgetsPreviewPage.vue
src/services/dashboards/widgets/_base/base-pie/BasePieWidget.vue

- Add props binding from `WidgetPreviewPage.vue` to Widget components - `dashboardOptions`, `inheritOptions` 
- FIx to use toRefs to sustain reactivity of each of items in reactive state (`BasePie.vue`)

feat: Add props binding from WidgetPreviewPage.vue to Widget components - dashboardOptions, inheritOptions

---

src/common/composables/amcharts5/index.ts
src/services/dashboards/widgets/_base/base-trend/BaseTrendWidget.vue

There's some bug in tooltip of amcharts5. ([Tooltips staying after clear](https://github.com/amcharts/amcharts5/issues/593))
**You have to `refreshRoot()` when refresh widget!**

fix(base-trend-widget): refreshRoot() when refresh widget

---

src/services/dashboards/dashboard-detail/modules/DashboardWidgetFrameContainer.vue
src/services/dashboards/widgets/_components/WidgetFrame.vue

- I've connected widgetFrame width. It is pretty cool 
- I've changed `eventlistener('resize')` to `resizeObserver`. Becuase, `eventlistener('resize')` cannot detect width changes caused by LNB
There is needed some margins between widgetFrame. (`margin: 8px`).
So, I need to minus 16px (8px * 2).
But I am confusing that which stage (widgetFrameContainer? widgetFrae?) to perform minus.

feat(widget-frame): connect widgetFrame width

---

packages/cloudforet/core-lib/__tests__/space-connector/__tests__/index.test.ts
packages/cloudforet/core-lib/src/space-connector/index.ts
packages/cloudforet/core-lib/src/space-connector/type.ts
public/config/default.json
src/lib/site-initializer/api-client.ts

- Add SpaceConnector client2 for serviceApiV2
- Add CONSOLE_API_V2 to default config

feat(core-lib): add client2 for serviceApiV2 in SpaceConnector & update usages

---

package-lock.json
package.json
src/services/dashboards/widgets/_base/base-pie/BasePieWidget.vue
src/services/dashboards/widgets/_components/WidgetDataTable.vue

- Customize no data case of widget-data-table to show table header in no data case
https://user-images.githubusercontent.com/26986739/205538364-e38067da-8e91-4029-b06a-6ebea6cc0b42.mov

fix(widget-data-table): don't use dataLoader's no-data slot

---

package-lock.json
package.json
src/common/modules/dropdown/currency-select-dropdown/CurrencySelectDropdown.vue
src/services/dashboards/dashboard-customize/DashboardCustomizePage.vue

Add defaultMode for currency select dropdown.
There would be default currency for dashboard. So, I've made `defaultMode` with `defaultCurrency`.
With defaultMode, default Currency will be selected on the first load. 
Also, badge has added.

feat(currency): add `defaultMode` in dropdown

---

src/services/cost-explorer/cost-analysis/CostAnalysisPage.vue
src/services/cost-explorer/cost-analysis/modules/CostAnalysisHeader.vue
src/services/cost-explorer/lib/__tests__/helper.test.ts
src/services/cost-explorer/lib/helper.ts
src/services/cost-explorer/store/cost-analysis/actions.ts
src/services/cost-explorer/type.ts

This is a preliminary work to remove `primary_group_by` and `more_group_by` properties from CostAnalysis `QuerySetOptions`.

feat: add converter for costQuerySet from older version to new one

---

src/services/cost-explorer/cost-analysis/CostAnalysisPage.vue
src/services/cost-explorer/cost-analysis/lib/config.ts
src/services/cost-explorer/cost-analysis/type.ts
src/services/cost-explorer/store/cost-analysis/getters.ts

Changed the URL Query specification of the `CostAnalysisPage` to be the same as the CostQuerySet Options specification changed as in the [previous PR](https://github.com/cloudforet-io/console/pull/437).

feat: update CostAnalysisPage url query spec

---

src/services/cost-explorer/cost-analysis/CostAnalysisPage.vue
src/services/cost-explorer/cost-analysis/modules/CostAnalysisHeader.vue
src/services/cost-explorer/store/cost-analysis/actions.ts

CostAnalysisPage has store states.
All values marked with red boxes in the image below are managed by the store state.
All values are reflected in the url query whenever the user changes them.
Also, users can save them as saved queries.
When entering this page, the query must be parsed from the URL and reflected in the store state.
Also, even if a saved query is loaded, the query must be parsed and reflected in the store state.
Url query & saved query options' structure are the same.
But the store state structure is different from them.
**This PR updated the converter between them**
(URL Query & Saved Query <--------> Store States)
| UI | URL Query | Saved Query | Store States | Description |
| - | - | - | - | - |
| Granularity | granularity | granularity | granularity | - |
| Stack | …

feat(cost-analysis): refine query options when saving and setting states

---

src/services/cost-explorer/cost-dashboard/modules/CostDashboardMoreMenu.vue
src/services/dashboards/dashboard-detail/DashboardDetailPage.vue
src/services/dashboards/dashboard-detail/modules/DashboardCloneModal.vue
src/services/dashboards/dashboard-detail/modules/DashboardControlButtons.vue
src/services/dashboards/dashboard-detail/modules/DashboardMoreMenu.vue

https://cloudone-mz.slack.com/archives/C044D55N2V9/p1670830618334959
1. Contrary to cost-dashboard, duplicating dashboard feature would be executed by 'clone' button. (At cost-dashboard, duplicating feature has been provided by duplicate context item)
2. So I've applied it to codes and refactored names

refactor(dashboard): rename 'duplicate' to 'clone'

---

src/services/asset-inventory/collector/CollectorPage.vue

There is a bug in p-button in mirinae. 
But to not upgrade mirinae version, This PR added some defense code.

fix: add defense code for p-button component click event

---

src/services/dashboards/DashboardsLNB.vue
src/services/dashboards/all-dashboards/modules/DashboardBoardList.vue
src/store/modules/dashboard/actions.ts
src/store/modules/dashboard/getters.ts
src/store/modules/dashboard/type.ts

First, just link Dashboard favorite. Not that difficult.
**Second, difficult things..**
Dashboard project LNB items have to be grouped, but that data don't have project-group data.
So, project data in reference store was imported and processed by mash-up.
Description
- Project LNB item may or may not have a group.
- So, no-group items just need to be converted to LNBItem.
- Group items should be sorted by group compared to reference store's project-id and converted to LNBItem.
- And two data need to be merged.
- Please check `mashUpProjectGroup` function.

feat(dashboard-LNB): set project dashboard LNB group

---

src/common/components/layouts/PdfDownloadOverlay/PdfDownloadOverlay.vue
src/services/cost-explorer/cost-analysis/modules/CostAnalysisChart.vue

There was critical bug in Cost Analysis pdf download.
- CostAnalysisChart component emitted 'rendered' event with parameters that includes Vue component, not HTML element. 
So I this PR fixed it to event parameters include only elements.
- To fix this bug, it was pretty hard. Error messages from PdfDownloadOverlay component was not helpful because try/catch statement was not written where it really needed to be written.
So this PR adds try/catch statement to PdfDownloadOverlay component's some functions.

fix(cost-analysis): access to element by $el in component ref

---

src/common/modules/page-layouts/VerticalPageLayout.vue

'scroll event(for hide contextMenu)' did not work intermittently on components using the existing useFixedMenu.
Even if the scroll event is bound in the VerticalPageLayout of each existing PageContainer, it does not work, so I modified it.

fix(vertical-page-layout): fix overflow property for search scroll event

---

src/services/dashboards/dashboard-detail/DashboardDetailPage.vue
src/services/dashboards/dashboard-detail/modules/DashboardDeleteModal.vue

was: More menu, includes `delete` / `set as home dashboard`
now: Delete icon button
`set as home dashboard` feature is decided to not provide in this dashboard

feat(dashboard): replace more-menu to delete-button

---

src/common/components/buttons/PdfDownloadButton.vue
src/services/dashboards/dashboard-detail/DashboardDetailPage.vue
src/services/dashboards/dashboard-detail/modules/DashboardControlButtons.vue
src/services/dashboards/dashboard-detail/modules/DashboardDetailPreview.vue
src/services/dashboards/dashboard-detail/modules/DashboardWidgetContainer.vue

First of all, I only connected the pdfExport button.
the preview component has been created and additional application is required after configuring the detail page later.
I'm thinking about how to configure widget placement for pdf..

feat(dashboard-pdf-export): connect pdf overlay to dashboardDetailPage

---

package-lock.json
src/common/composables/amcharts5/tree-map-helper.ts
src/services/dashboards/widgets/cost-map/CostMapWidget.vue

* Add `getConvertedChartData` to set background-color to each rectangle and tooltip color
* Add ellipsis to label text
* Fix chart height

fix(cost-map-widget): add getConvertedChartData and minor css

---

src/services/dashboards/dashboard-customize/DashboardCustomizePage.vue
src/services/dashboards/dashboard-customize/modules/VariableSelectorDropdown.vue

SSIA
- Delete button has been added.
- Since data received as props and type actually used are different, it goes through a complicated two-way conversion process in `onMounted`, `watch`.
- `MenuItem` is a temporary code that will soon be deleted.
https://user-images.githubusercontent.com/83635051/209894836-3afb2a17-df90-4c52-8402-5cf55eef1d24.mov

feat(variable-selector): apply context-menu-controller & bind customize page

---

packages/cloudforet/core-lib/src/index.ts
src/common/composables/amcharts5/xy-chart-helper.ts
src/services/dashboards/widgets/_base/base-trend/BaseTrendWidget.vue
src/services/dashboards/widgets/_components/WidgetDataTable.vue
src/services/dashboards/widgets/_components/type.ts
src/services/dashboards/widgets/monthly-cost/MonthlyCostWidget.vue
src/services/dashboards/widgets/type.ts
src/services/dashboards/widgets/widget-chart-helper.ts
src/services/dashboards/widgets/widget-helper.ts
src/services/dashboards/widgets/widget-table-helper.ts

- DataTable of base trend widget
- xychart tooltip is improved!
- before
- after
currency has not been applied to data table, yet :)
maybe @sulmoJ will

fix(base-trend-widget): apply converted data

---

package-lock.json
package.json
src/services/dashboards/dashboard-customize/DashboardCustomizePage.vue
src/services/dashboards/dashboard-customize/modules/VariableMoreButtonDropdown.vue
src/services/dashboards/dashboard-customize/modules/VariableSelectorDropdown.vue

SSIA
- Use status of each variable is applied after the dropdown is hidden.
- Emits 'change' of selected according to the status of the visible menu.
https://user-images.githubusercontent.com/83635051/209916317-f4f2f053-a37e-4cdd-83d8-14f2d27db21a.mov
As you can see from the description above, 
as `visibleMenu` changes, 'change' event is emitted even if there is no change in selected. 
Could there be a better way?

feat(variable-more-dropdown): apply context-menu-controller & bind variables data

---

src/services/dashboards/dashboard-customize/DashboardCustomizePage.vue
src/services/dashboards/dashboard-customize/modules/DashboardCustomizeSidebar.vue
src/services/dashboards/dashboard-detail/DashboardDetailPage.vue
src/services/dashboards/dashboard-detail/lib/type.ts
src/services/dashboards/dashboard-detail/modules/DashboardWidgetContainer.vue

- Use DashboardContainerWidgetInfo in DashboardWidgetContainer.vue to use widgetKey as widget element's id not to initiate every time when drag & drop occurs.
https://user-images.githubusercontent.com/26986739/210030891-4a3bfe0b-72d6-4d75-ae96-91c3dbfcefa4.mov

feat: add DashboardContainerWidgetInfo that has widgetKey

---

src/services/dashboards/dashboard-customize/DashboardCustomizePage.vue
src/services/dashboards/dashboard-detail/DashboardDetailPage.vue
src/services/dashboards/dashboard-detail/store/dashboard-detail-info.ts

Changed DashboardsDetail & DashboardsCustomize pages to use pinia store.
This is previous work for page structure rearrangement that is to avoid recreation the WidgetContainer when moving between the detail page and the customize page.

feat: add dashboard detail info store

---

src/services/dashboards/dashboard-customize/DashboardCustomizePage.vue
src/services/dashboards/dashboard-customize/modules/dashboard-manage-variable-overlay/DashboardManageVariableOverlay.vue
src/services/dashboards/dashboard-customize/modules/dashboard-manage-variable-overlay/modules/DashboardManageVariableForm.vue
src/services/dashboards/dashboard-customize/modules/dashboard-manage-variable-overlay/modules/DashboardManageVariableTable.vue
src/services/dashboards/dashboard-customize/modules/dashboard-manage-variable-overlay/type.ts

SSIA
- Bind variable schema to overlay.
- Separate table from overlay, and name `DashboardManageVariableTable`.
- Some refactors - rename, table field setting... etc.
https://user-images.githubusercontent.com/83635051/210201500-54c7b00c-df83-427b-adc5-9bd77d22526e.mov

feat(manage-variable): bind variable schema to overlay & component separation

---

src/common/composables/breadcrumbs/index.ts
src/services/dashboards/dashboard-detail/store/dashboard-detail-info.ts
src/services/dashboards/routes.ts
src/shims-vue-router.d.ts

- Add setDashboardInfo and resetDashboardSettings to dashboard-detail-info store
- Make customize page's last breadcrumb optional
- Update dashboards route hierarchy
- add breadcrumbs function to router meta and use-breadcrumbs composable
-

feat(dashboard-detail-info-store): add setDashboardInfo

---

src/services/asset-inventory/service-account/service-account-add/ServiceAccountAddPage.vue

There was an issue in service-account-add-page.
The issue was, there was no loading or button blocking when request is pending.
So user could click create button multiple times, and create request was multiple too.
So I've added loading props on button
https://user-images.githubusercontent.com/29014433/210212061-5a8b9ba9-7024-44fd-aedd-2daa6f77a49d.mov

fix(service-account): add loading for no duplicated create request

---

src/services/dashboards/dashboard-customize/DashboardCustomizePage.vue
src/services/dashboards/dashboard-detail/DashboardDetailPage.vue
src/services/dashboards/dashboard-detail/modules/DashboardControlButtons.vue
src/services/dashboards/dashboard-detail/modules/DashboardDetailPreview.vue
src/services/dashboards/dashboard-detail/modules/DashboardWidgetContainer.vue
src/services/dashboards/dashboard-detail/store/dashboard-detail-info.ts

- Refactor DashboardWidgetContainer.vue to use dashboard-detail-info store 
- Apply changed usage of DashboardWidgetContainer.vue to detail & customize pages
- Hide pdf export buttons

refactor: use dashboard-detail-info store in dashboard widget container

---

package-lock.json
package.json
src/services/dashboards/dashboard-customize/DashboardCustomizePage.vue
src/services/dashboards/dashboard-detail/modules/DashboardDetailPreview.vue
src/services/dashboards/dashboard-detail/modules/DashboardWidgetContainer.vue
src/services/dashboards/dashboard-detail/store/dashboard-detail-info.ts
src/services/dashboards/widgets/_base/base-pie/BasePieWidget.vue
src/services/dashboards/widgets/_base/base-trend/BaseTrendWidget.vue
src/services/dashboards/widgets/aws-cloud-front-cost/AWSCloudFrontCost.vue
src/services/dashboards/widgets/aws-data-transfer-by-region/AWSDataTransferByRegion.vue
src/services/dashboards/widgets/budget-status/BudgetStatusWidget.vue
src/services/dashboards/widgets/budget-usage-summary/BudgetUsageSummaryWidget.vue
src/services/dashboards/widgets/budget-usage-with-forecast/BudgetUsageWithForecastWidget.vue
src/services/dashboards/widgets/config.ts
src/services/dashboards/widgets/cost-by-region/CostByRegion.vue
src/services/dashboards/widgets/cost-map/CostMapWidget.vue
src/services/dashboards/widgets/monthly-cost/MonthlyCostWidget.vue
src/services/dashboards/widgets/type.ts
src/services/dashboards/widgets/use-widget-state.ts

- Upgrade vue version
- Update initWidget() type
- Add WidgetExpose type for defineExpose generic type
- Add data types to all widgets
- Add widgetDataMap state to dashboard-detail-info store 
- Update DashboardWidgetContainer to use dashboard-detail-info store
- Update DashboardWidgetContainer to give data parameter when calling initWidget() of each widget from widgetDataMap store state
- Add reusePreviousData prop to DashboardWidgetContainer to decide whether to reuse previous data if exists.

feat(widgets): use data param if exist in intWidget()

---

src/services/dashboards/config.ts
src/services/dashboards/dashboard-create/DashboardCreatePage.vue
src/services/dashboards/dashboard-customize/DashboardCustomizePage.vue
src/services/dashboards/dashboard-customize/modules/DashboardCustomizePageName.vue
src/services/dashboards/dashboard-detail/DashboardDetailPage.vue
src/services/dashboards/dashboard-detail/store/dashboard-detail-info.ts
src/services/dashboards/model.ts

I need `project_id` for `dashboardScope`.
Because when creating dashboard through customize-page, there is no way to know `dashboardScope`.
`create()` api is not tested yet.
Sorry for unkind mixed codes..

fix(dashboard): put projectId to store

---

src/services/dashboards/dashboard-customize/DashboardCustomizePage.vue
src/services/dashboards/dashboard-customize/modules/VariableMoreButtonDropdown.vue

- Refactor more-dropdown, now more-dropdown accesses store directly without using props from customize page.
- Variable's use change has to be reflected after dropdown is closed, so changed selected items are temporarily saved in `selectedForUpdate`.

feat(variable-more-dropdown): refactor more-dropdown

---

src/services/dashboards/widgets/_base/base-pie/BasePieWidget.vue
src/services/dashboards/widgets/_base/base-trend/BaseTrendWidget.vue
src/services/dashboards/widgets/_components/WidgetDataTable.vue
src/services/dashboards/widgets/aws-cloud-front-cost/AWSCloudFrontCost.vue
src/services/dashboards/widgets/aws-data-transfer-by-region/AWSDataTransferByRegion.vue
src/services/dashboards/widgets/aws-data-transfer-cost-trend/AWSDataTransferCostTrend.vue
src/services/dashboards/widgets/budget-status/BudgetStatus.vue
src/services/dashboards/widgets/budget-usage-summary/BudgetUsageSummaryWidget.vue
src/services/dashboards/widgets/cost-by-region/CostByRegion.vue
src/services/dashboards/widgets/cost-map/CostMapWidget.vue
src/services/dashboards/widgets/monthly-cost/MonthlyCostWidget.vue

* add 'p-data-loader' skeleton to widgets
* add 'loader-backdrop-opacity=1' to all widgets

fix: add 'p-data-loader' skeleton to widgets

---

src/common/modules/dropdown/currency-select-dropdown/CurrencySelectDropdown.vue
src/services/dashboards/dashboard-detail/DashboardDetailPage.vue
src/services/dashboards/dashboard-detail/store/dashboard-detail-info.ts
src/services/dashboards/modules/dashboard-toolset/DashboardToolset.vue

At dashboard-detail-page, user can set currency / date-range / variables.
But those have volatility on dashboard-detail-page. 
(When leaving the page, such as going to customize page, should revert dashboard original data)

feat(dashboard): add `revertDashboardStore`

---

src/services/dashboards/dashboard-customize/modules/DashboardAddDefaultWidgetRightArea.vue
src/services/dashboards/dashboard-customize/stores/widget-form.ts
src/services/dashboards/dashboard-detail/modules/DashboardWidgetContainer.vue
src/services/dashboards/dashboard-detail/store/dashboard-detail-info.ts
src/services/dashboards/widgets/_helpers/widget-helper.ts
src/services/dashboards/widgets/_helpers/widget-validation-helper.ts

`getWidgetInheritOptionsErrorMap()` is comming!💗
With this helper, you can get **error message map** of specific widget! like...
```typescript
{
'filters.provider': 'This property does not exist on the dashboard variables.',
'filters.project_id': 'This property has a different type from the dashboard variable.',
}
```

fix(widget-helper): add `getWidgetInheritOptionsErrorMap()`

---

src/services/dashboards/dashboard-detail/modules/DashboardWidgetContainer.vue
src/services/dashboards/widgets/_components/WidgetFrame.vue
src/services/dashboards/widgets/_configs/config.ts
src/services/dashboards/widgets/_hooks/use-widget-frame-props.ts

fix: add `error-mode` props to widgets

---

src/services/dashboards/dashboard-customize/DashboardCustomizePage.vue
src/services/dashboards/dashboard-detail/DashboardDetailPage.vue

- New data is not fetched from customize page In `detail-customize-save` & `create-customize-save` scenario.
- Now new data is fetched by force when entering dashboard-detail page.

fix(dashboard-customize): edit get-data scenario

---

src/services/dashboards/modules/DashboardCloneModal.vue

Fix that widgets are not copied when clone dashboard.
BE variable names are `snake_case`,  and FE variable names are `camelCase`.
It is little bit hard . T^T

fix(dashboard): clone also widgets

---

src/common/composables/amcharts5/index.ts
src/services/dashboards/widgets/_base/base-pie/BasePieWidget.vue
src/services/dashboards/widgets/_base/base-trend/BaseTrendWidget.vue
src/services/dashboards/widgets/_hooks/use-widget-lifecycle.ts
src/services/dashboards/widgets/aws-cloud-front-cost/AWSCloudFrontCost.vue
src/services/dashboards/widgets/aws-data-transfer-by-region/AWSDataTransferByRegion.vue
src/services/dashboards/widgets/aws-data-transfer-cost-trend/AWSDataTransferCostTrend.vue
src/services/dashboards/widgets/budget-usage-summary/BudgetUsageSummaryWidget.vue
src/services/dashboards/widgets/cost-by-region/CostByRegion.vue
src/services/dashboards/widgets/cost-map/CostMapWidget.vue
src/services/dashboards/widgets/monthly-cost/MonthlyCostWidget.vue

refresh widget only its' inherit option changed
**Please see first commit only!!!**
https://user-images.githubusercontent.com/18563857/212304826-a9e78524-2ddf-49e8-9154-bc93ca17bed7.mov

fix(use-widget-lifecycle): refresh only widget's inherit options changed

---

src/services/dashboards/modules/dashboard-label/DashboardLabels.vue

In design, height is `1.5rem`. But I've added only `min-height: 1.5rem`

fix(dashboard): label input height

---

src/common/modules/project/ProjectSelectDropdown.vue

There was a problem that delete all button was not appeared. 
That was because of the FilterableDropdown component's readonly prop was always true.
So This PR add readonly prop to ProjectSelectDropdown and bound it with FilterableDropdown.

fix(project-select-dropdown): bind readonly state with props

---

src/services/dashboards/dashboard-customize/modules/VariableMoreButtonDropdown.vue

SSIA
- Because more dropdown's watcher was working with `immediate`, variable uses were clear when entering customize page.

fix(dashboard-dropdown): fix no default variable issue in customize page

---

src/common/modules/navigations/gnb/modules/gnb-menu/modules/dashboard-recent-favorite/modules/GNBDashboardFavorite.vue
src/common/modules/navigations/gnb/modules/gnb-menu/modules/dashboard-recent-favorite/modules/GNBDashboardRecent.vue
src/lib/site-initializer/api-client.ts
src/services/dashboards/dashboard-customize/modules/DashboardDefaultWidgetTab.vue
src/services/dashboards/dashboard-customize/modules/dashboard-widget-input-form/DashboardWidgetInputForm.vue
src/services/dashboards/dashboard-customize/modules/dashboard-widget-input-form/composables/use-reference-store.ts
src/services/dashboards/dashboard-customize/modules/dashboard-widget-input-form/composables/use-widget-name-input.ts
src/services/dashboards/widgets/_components/DashboardWidgetEditModal.vue

- (fix) make gnb dashboard recent, favorite css the same
- (fix) make use mock info endpoints in api client in mock mode
- (refactor) separate widget title(name) input logic as composable from DashboardWidgetInputForm.vue
- (refactor) separate reference store logics as composable from DashboardWidgetInputForm.vue
This PR includes some refactoring tasks. They are pre tasks of developing the inherit validation feature.

fix: make gnb dashboard recent, favorite css the same

---

src/services/dashboards/dashboard-customize/modules/dashboard-manage-variable-overlay/DashboardManageVariableOverlay.vue
src/services/dashboards/dashboard-customize/modules/dashboard-manage-variable-overlay/modules/DashboardManageVariableTable.vue

SSIA
Solve [QA - 314 - 1](https://pyengine.atlassian.net/browse/QA-314)
- Replace entire connection to conditional connection between table data and store data, because variable table data is linked to store and always converting to appropriate type that fits table. That kept causing new rendering and weird move.
- Watcher is watching variable-order, and cause conditional rendering in only deletion case or forced refresh.
https://user-images.githubusercontent.com/83635051/212932525-80f9084e-fe48-4244-8f69-9114993c9ed1.mov

refactor(variable-table): fix show more toggle issue

---

src/services/dashboards/routes.ts

There was a problem at dashboard-route and it causes wrong dashboardId.
When user wants to create a dashboard, url is '/project/customize'.
But it was recognized as `customize` is dashboardId.
So I've fixed it.

fix(dashboard): wrong route causing wrong dashboardId

---

packages/cloudforet/core-lib/src/space-connector/index.ts
packages/cloudforet/core-lib/src/space-connector/token-api.ts
src/services/dashboards/dashboard-customize/modules/DashboardAddWidgetModal.vue
src/services/dashboards/dashboard-customize/modules/dashboard-widget-input-form/DashboardWidgetInputForm.vue
src/services/dashboards/dashboard-customize/modules/dashboard-widget-input-form/DashboardWidgetMoreOptions.vue
src/services/dashboards/dashboard-customize/modules/dashboard-widget-input-form/helpers.ts
src/services/dashboards/dashboard-customize/stores/widget-form.ts
src/services/dashboards/dashboard-detail/store/dashboard-detail-info.ts
src/services/dashboards/default-dashboard/helper.ts
src/services/dashboards/default-dashboard/templates/cdn-and-traffic-cost.ts
src/services/dashboards/default-dashboard/templates/monthly-cost-summary.ts
src/services/dashboards/widgets/_components/DashboardWidgetEditModal.vue
src/services/dashboards/widgets/_configs/config.ts

- (fix) core-lib > token api: init refreshing state on token api creation
- (fix) do not generate widget_key if exists
- (fix) resolve some type errors in dashboard template creation helpers
- (feat) add default_schema_properties to widget info

feat: add default_schema_properties to widget info

---

src/services/dashboards/dashboard-customize/modules/DashboardCustomizePageName.vue
src/services/dashboards/dashboard-detail/DashboardDetailPage.vue
src/services/dashboards/widgets/monthly-cost/MonthlyCostWidget.vue

- update MonthlyCostWidget empty case
- update MonthlyCostWidget loading UI
- add skeleton loader to page title when title is empty

fix: fix monthly cost widget loading, empty case and dashboard title loading case

---

src/services/dashboards/widgets/aws-data-transfer-by-region/AWSDataTransferByRegionWidget.vue
src/services/dashboards/widgets/cost-by-region/CostByRegion.vue

* fix blinking map charts because of adding 1px border to `.chart`

fix: fix chart width and height for blinking map charts

---

src/services/dashboards/all-dashboards/modules/DashboardBoardList.vue

SSIA
Fix wrong prop name. `current-page` => `this-page`

fix(dashboard-pagination): fix wrong property name

---

src/services/dashboards/dashboard-detail/lib/__tests__/index.test.ts
src/services/dashboards/dashboard-detail/lib/config.ts
src/services/dashboards/dashboard-detail/lib/width-helper.ts
src/services/dashboards/dashboard-detail/modules/DashboardWidgetContainer.vue

For less losing teeth,
1. Widget width range was supported by `+80px` -> `+16px`
as-is: sm: 320, 400, 480
to-be: sm: 320, 336, 352, 368 ... 464, 480 
2. Widget max width was `default + 160px`-> `default + 560px`
as-is: 
- sm: 320 ~ 480
- md: 480 ~ 640
...
to-be: 
- sm: 320 ~ 880 
- md: 480 ~ 960
...
Please look below beautiful screenshot.

feat(widget-container): support more specific widget width range

---

src/lib/reference/reference-config.ts
src/services/dashboards/dashboard-customize/modules/VariableMoreButtonDropdown.vue
src/services/dashboards/dashboard-customize/modules/dashboard-manage-variable-overlay/DashboardManageVariableOverlay.vue
src/services/dashboards/dashboard-customize/modules/dashboard-widget-input-form/DashboardWidgetInputForm.vue
src/services/dashboards/dashboard-customize/modules/dashboard-widget-input-form/composables/use-reference-store.ts
src/services/dashboards/dashboard-customize/modules/dashboard-widget-input-form/schema-helpers.ts
src/services/dashboards/managed-variables-schema.ts
src/services/dashboards/widgets/__tests__/widget-helper.test.ts
src/services/dashboards/widgets/_configs/config.ts
src/services/dashboards/widgets/_configs/widget-schema-config.ts
src/services/dashboards/widgets/_helpers/widget-filters-helper.ts
src/services/dashboards/widgets/_helpers/widget-schema-helper.ts
src/services/dashboards/widgets/_helpers/widget-validation-helper.ts
src/services/dashboards/widgets/_hooks/use-widget-state.ts
src/services/dashboards/widgets/aws-cloud-front-cost/widget-config.ts
src/services/dashboards/widgets/aws-data-transfer-by-region/widget-config.ts
src/services/dashboards/widgets/aws-data-transfer-cost-trend/widget-config.ts
src/services/dashboards/widgets/budget-status/widget-config.ts
src/services/dashboards/widgets/budget-usage-by-target/widget-config.ts
src/services/dashboards/widgets/budget-usage-summary/widget-config.ts
src/services/dashboards/widgets/cost-analysis-query/widget-config.ts
src/services/dashboards/widgets/cost-by-region/widget-config.ts
src/services/dashboards/widgets/cost-donut/widget-config.ts
src/services/dashboards/widgets/cost-map/widget-config.ts
src/services/dashboards/widgets/cost-pie/widget-config.ts
src/services/dashboards/widgets/cost-trend-stacked/widget-config.ts
src/services/dashboards/widgets/cost-trend/widget-config.ts
src/services/dashboards/widgets/monthly-cost/widget-config.ts
src/store/modules/reference/getters.ts
src/store/modules/reference/type.ts

- Add WidgetOptionsSchema type for typescript checking
- Refactor not to use reference key (such as 'project_id') as widget options schema property name. Change them to use reference type (such as 'project') 
All dashboard data MUST be changed after this PR merged.

refactor: do not use reference key as widget schema property key

---

src/lib/access-control/page-permission-helper.ts
src/lib/menu/menu-info.ts
src/services/info/notice/modules/NoticeForm.vue

Resolves #332 
Every feature is working fine. 
There is a problem that,
`DOMAIN_VIEWER` would have `ADMIN_PERMISSION`.
So, `DOMAIN_VIEWER` can access to notice create page. 😱
But create api is not working for them 👍

fix(notice): allow popup/pin for domain_admin

---

src/services/dashboards/dashboard-create/DashboardCreatePage.vue
src/services/dashboards/dashboard-customize/modules/DashboardCustomizePageName.vue
src/services/dashboards/dashboard-detail/store/dashboard-detail-info.ts
src/store/modules/dashboard/getters.ts

There was a bug that 
as-is: When creating dashboard, the dashboard template's name has been set. 
to-be: While creating dashboard, dashboard name should be empty.

fix(dashboard): dashboard name bug while creating

---

src/services/dashboards/dashboard-customize/modules/DashboardCustomizePageName.vue
src/services/dashboards/dashboard-customize/modules/DashboardCustomizeSidebar.vue

[QA-396](https://pyengine.atlassian.net/browse/QA-396)
- Now dashboard validation state watch name invalid state in `DashboardCostomizePageName`
- Apply name validation state to dashboard customize save button 
https://user-images.githubusercontent.com/83635051/217193732-0f73bd50-223f-4bb3-a06a-d66f23b45b88.mov

fix(dashboard-customize): apply dashboard name valid state

---

src/services/dashboards/dashboard-detail/store/dashboard-detail-info.ts

Signed-off-by: Yongtae Park <samuel.park@mz.co.kr>
[QA-397](https://pyengine.atlassian.net/browse/QA-397)
- Object `delete` can't be updating the DOM
- So, use `Vue.delete` 
https://user-images.githubusercontent.com/83635051/217208159-02e30775-1cd9-4f62-b8cb-63b410270872.mov
Is this a good way?
If not, try using below sample code in comment.

fix(dashboard-customize): change object delete property method

---

src/services/dashboards/dashboard-customize/stores/widget-form.ts
src/services/dashboards/widgets/_hooks/use-widget-state.ts

widgetConfig's schema property names are different from api query filter keys.
This PR Convert filter keys to api query spec(e.g. project -> project_id).
It occurs in cases below:
1. When widget options.filters are updated by user interaction. 
2. When each widget's options(which is from api) are applied to each widget's state. 
The second case codes are the compatible codes that make work even the data from api is wrong. (e.g. 'region_code' is correct key, but the previous version(<1.11.0.2) data has 'region' as the key.)

fix: use filter data key for api query not property name

---

src/services/dashboards/dashboard-customize/modules/dashboard-widget-input-form/DashboardWidgetInputForm.vue

Signed-off-by: Dahyun Yu <yuda@megazone.com>
- set `inherit`: `false` when add widget options

fix(widget-input-form): set inherit `false` when add widget option

---

src/services/alert-manager/alert/alert-detail/modules/AlertNote.vue
src/services/alert-manager/alert/alert-detail/modules/alert-key-info/modules/AlertInfoDescription.vue
src/services/asset-inventory/cloud-service/cloud-service-detail/modules/cloud-service-history-detail/CloudServiceHistoryDetailNoteTab.vue

fix: apply text beautifier to alert note, change history note, alert description

---

src/common/modules/navigations/gnb/modules/gnb-menu/modules/dashboard-recent-favorite/modules/GNBDashboardMenu.vue
src/lib/access-control/config.ts
src/lib/access-control/index.ts
src/lib/access-control/page-permission-helper.ts
src/router/index.ts
src/services/dashboards/routes.ts
src/shims-vue-router.d.ts

*Add `accessInfo` to supplement `accessLevel`'s exception case*
```
meta: {
accessLevel: ACCESS_LEVEL.MANAGE_PERMISSION,
accessInfo: {
referenceRouteNames: [DASHBOARDS_ROUTE.PROJECT._NAME, DASHBOARDS_ROUTE.WORKSPACE._NAME ]
}
}
```
*accessInfo* (optional)
- Dashboard route has *different hierarchy route case* than before.
- So we decide to solve this issue through `accessInfo`.
- `accessInfo` is created to supplement problems that could not be covered by `accessLevel`
- And current problem is solved through `referenceRouteNames`.
- If you are curious about how it works, check it out through this PR.
++ Another issue is fixed
- Create New Dashboard button's permission in GNB was not working.
- FIx misuse of `computed`.

fix(dashboard-route): handle a case of route with reference routes

---

packages/cloudforet/language-pack/console-translation.babel
packages/cloudforet/language-pack/en.json
packages/cloudforet/language-pack/ja.json
packages/cloudforet/language-pack/ko.json
src/services/dashboards/DashboardsContainer.vue
src/services/dashboards/dashboard-create/DashboardCreatePage.vue
src/services/dashboards/dashboard-create/modules/DashboardCreateHeader.vue
src/services/dashboards/dashboard-create/modules/DashboardScopeForm.vue
src/services/dashboards/dashboard-create/modules/DashboardTemplateForm.vue
src/services/dashboards/dashboard-create/modules/DashboardViewerForm.vue
src/services/dashboards/routes.ts
src/shims-vue-router.d.ts

* Add `<div class="centered-page-layout"/>` to show new page layout.
* Separate create dashboard page into two steps.
* Show dashboard template lists depending on selected scope on first step.
* `<centered-page-layout/>` component will be developed in the other quest. Because it will be reused reset password page and workspace page. And there are different things from existing page layout components (`<general-page-layout/>`, `<vertical-page-layout/>`). I think it's better to add new layout rather than to customize existing page layout components
* New layout has no LNB and FNB. 
* Content of New layout has `max-width`.
* ~~I will add translation code.~~

feat(dashboard-create): show dashboard templates depending on selected scope and fix UI

---

apps/web/src/services/dashboards/config.ts
apps/web/src/services/dashboards/dashboard-customize/modules/VariableSelectorDropdown.vue
apps/web/src/services/dashboards/dashboard-customize/modules/dashboard-manage-variable-overlay/modules/DashboardManageVariableForm.vue
apps/web/src/services/dashboards/dashboard-customize/modules/dashboard-manage-variable-overlay/modules/DashboardManageVariableOptionsField.vue
apps/web/src/services/dashboards/dashboard-customize/modules/dashboard-manage-variable-overlay/type.ts

Create `Manual Entry` options form.
This code is subject to change in next PR with `Search Data Source` options.
For compatibility with legacy options, discussion is necessary.
This is temporary code.
Breaking Changes
- Options: `string[]` => `Object[]` (this need discussion and revision)
- Form's options field is separated from Form component.
**Can be changed**
- Type (`config.ts`)
- Option Validation
- **Code that handles legacy options type**
- etc..
https://user-images.githubusercontent.com/83635051/227507781-8812bd40-44c6-4d0d-9828-5d5f3d746eb9.mov

feat(dashboard-variable): create MANUAL options form

---

apps/web/dev.dockerfile
apps/web/dev.dockerfile.dockerignore
apps/web/package.json
apps/web/preview.dockerfile
apps/web/preview.dockerfile.dockerignore

Those files enable to use different dockerfiles in multiple situations.
When we want to share outputs with coworkers very quickly in dev mode by using local `node_modules`, we can use `dev.dockerfile` by running command below:
```bash
docker build -f apps/web/dev.dockerfile -t console-web:dev .
docker run -d -p 8080:8080 --rm --name console-web console-web:dev 
```
If we want to share outputs for preview in prod mode pretty quickly by using local `node_modules`, then we can use `preview.dockerfile` by running command below:
```bash
docker build -f apps/web/preview.dockerfile -t console-web:preview . --build-arg TURBO_TEAM="<team_name>" --build-arg TURBO_TOKEN="<token>"
docker run -d -p 8080:8080 --rm --name console-web console-web:preview
```
If we want to share outputs which is exactly …

ci: add dev and preview dockerfiles for skaffold run

---

apps/web/src/services/dashboards/dashboard-customize/modules/VariableSelectorDropdown.vue
apps/web/src/services/dashboards/store/dashboard-detail-info.ts

Add `convertDashboardInfoByChangedVariableSchema` action in `dashboard-detail-info.ts`.
- This work in `getDashboardInfo` action, before `setDashboardInfo` action.
- This makes legacy `variable_schema` data (from backend) compatible.

fix(dashboard-variable): add `convertDashboardInfoByChangedVariableSchema` action to handle legacy variable data

---

packages/mirinae/src/inputs/dropdown/filterable-dropdown/PFilterableDropdown.vue
packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue

[Quest-13-dashboard-variable QA-461](https://pyengine.atlassian.net/browse/QA-461)
- Apply `onClickOutside`
- Refactor `PSelectDropdown` to `script setup`
- Add `badge-type` in `PFilterableDropdown`

fix(widget-form): apply outside click & add badge type in filterable dropdown

---

apps/web/src/services/dashboards/dashboard-customize/modules/dashboard-manage-variable-overlay/DashboardManageVariableOverlay.vue

[Quest-13-dashboard-variable QA-462](https://pyengine.atlassian.net/browse/QA-462)
In `Edit` and `Add` type content, when clicking go-back button, changing to `LIST` type overlay, not closing overlay

fix(manage-variable-overlay): change overlay escape scenario

---

apps/web/src/services/dashboards/dashboard-customize/modules/VariableMoreButtonDropdown.vue

[Quest-13-dashboard-variable QA-460](https://pyengine.atlassian.net/browse/QA-460)
In `VariableMoreButtonDropdown`,
clear-selection was not working.
- We must check there are Custom variable and whether they affect widgets or not
- So I add **Clear selection case with custom variable affecting widgets**
- Then handle that case
https://user-images.githubusercontent.com/83635051/233534182-76a7f3c0-d1f6-4594-b141-70142f57e5e9.mov

fix(manage-variable): handle clear selection scenario

---

apps/web/src/services/my-page/my-account/user-account/modules/ChangePassword.vue

- apply error message when the current password is the same

feat(my-page): apply error message when the current password is the same

---

apps/web/src/App.vue
apps/web/src/common/modules/button/verify-button/VerifyButton.vue
apps/web/src/common/modules/modals/NotificationEmailModal.vue
apps/web/src/common/modules/page-layouts/CenteredPageLayout.vue
apps/web/src/services/administration/iam/user/modules/UserManagementTable.vue
apps/web/src/services/administration/iam/user/modules/user-management-modal/UserManagementModal.vue
apps/web/src/services/administration/iam/user/modules/user-management-modal/modules/NotificationEmailForm.vue
apps/web/src/services/administration/iam/user/modules/user-management-modal/modules/PasswordForm.vue
apps/web/src/services/auth/password/PasswordPage.vue
apps/web/src/services/dashboards/dashboard-create/DashboardCreatePage.vue

- App
- Re-send verification email when user sign-in
- Administration
- Create user
- Show success message
- Update user
- Add verification status badge
- Change conditions for enabling reset password radio button based on email verification status
- Reset password
- Limit animation loop upon successful verification email transmission

feat(reset-password_notification-email): planning qa

---

apps/web/src/lib/helper/verify-email-helper.ts
apps/web/src/services/administration/iam/user/modules/user-management-modal/modules/NotificationEmailForm.vue
apps/web/src/services/auth/password/PasswordPage.vue
apps/web/src/services/auth/password/modules/PasswordForm.vue

- Change the notification email verification scenario API condition during user update.
- Modify the enter event during password reset.
- Display verify email error message when user does not have permission.

feat(reset-password_notification-email): planning qa, changed scenario

---

apps/web/src/services/dashboards/config.ts
apps/web/src/services/dashboards/modules/dashboard-toolset/DashboardCurrencySelectDropdown.vue
apps/web/src/services/dashboards/modules/dashboard-toolset/DashboardToolset.vue
apps/web/src/services/dashboards/store/dashboard-detail-info.ts
apps/web/src/services/dashboards/widgets/_hooks/use-widget-state.ts

Added "**DEFAULT**" currency!! This currency depends on the user's currency.
(`DashboardCurrencySelectDropdown.vue` is almost like a `CurrencySelectDropdown.vue`. So you don't have to look carefully.)
https://user-images.githubusercontent.com/18563857/234820923-ae4d9ff7-0899-470d-86f8-d583164deda9.mov

feat: add dashboard currency dropdown which has `DEFAULT` value

---

apps/web/src/services/cost-explorer/cost-dashboard/cost-dashboard-customize/modules/CostDashboardCustomizeCostQuery.vue

Resolve the issue of `group_by` values being entered as an `array` instead of a `string`

fix(cost-dashboard-groupby): fix bug

---

apps/web/src/services/dashboards/dashboard-detail/DashboardDetailPage.vue
apps/web/src/services/dashboards/store/dashboard-detail-info.ts
apps/web/src/services/dashboards/store/widget-form.ts
apps/web/src/services/dashboards/widgets/_components/WidgetFrame.vue
apps/web/src/services/dashboards/widgets/_components/WidgetViewModeModal.vue

- There's no visible change.
- Modal is moved from `WidgetFrame` to `DashboardDetailPage`
- Modal uses **store data** instead of props.

feat: move view mode modal from `WidgetFrame` to `DashboardDetailPage`

---

apps/web/src/services/administration/iam/user/modules/UserManagementTable.vue
apps/web/src/services/administration/iam/user/modules/user-management-modal/UserManagementModal.vue
apps/web/src/store/modules/user/actions.ts

- fixed the bug where the reset-password email is not being sent during user update
- even if the 'email-verified' value is false, modify it so that the 'email-verified' value is assigned

fix: fixed notification-email & user-update bug

---

packages/mirinae/src/feedbacks/alert/toast-alert/PToastAlert.vue

- Applying 'important' to resolve the issue where CSS is not being applied due to a change in the timing of the loading of 'vue-notification-group' during build.
- Fixing the issue where the success icon is not being displayed.

fix(toast-message): fixing 'vue-notification-group' css issue

---

package-lock.json
packages/mirinae/cli/build.js
packages/mirinae/cli/generate.js
packages/mirinae/cli/icon.tpl.txt
packages/mirinae/cli/svg-gen.js
packages/mirinae/cli/svgo.js
packages/mirinae/package.json

SSIA
- Now, we use `svg-gen`-`build` instead of `vsvg`.
- After vue 3 migration, `build` will be replaced to `generate`.

build(svg-icon): create svg icons object builder cli

---

package-lock.json
packages/mirinae/cli/build.js
packages/mirinae/cli/generate.js
packages/mirinae/cli/icon.tpl.txt
packages/mirinae/cli/svg-gen.js
packages/mirinae/cli/svgo.js
packages/mirinae/package.json

SSIA
- Now, we use svg-gen-build instead of vsvg.
- After vue 3 migration, build will be replaced to generate.

build(svg-icon): create svg icons object builder cli (#1138)

---

apps/web/src/services/asset-inventory/collector/create-collector/CreateCollectorPage.vue
apps/web/src/services/asset-inventory/collector/create-collector/modules/CreateCollectorStep1.vue
apps/web/src/services/asset-inventory/collector/modules/CollectPluginContents.vue
apps/web/src/services/asset-inventory/store/collector-form-store.ts

- Separated CollectorPluginContents component
- Updated the plug-in list style additionally
before
after
I was so confused because the css styling and mirinae component styles were mixed.. 😭 😭

feat(collector): separate the CollectorPluginContents for reuse

---

apps/web/src/services/asset-inventory/collector/collector-detail/CollectorDetailPage.vue
apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorBaseInfoSection.vue
apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorOptionsSection.vue
apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorScheduleSection.vue
apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorServiceAccountsSection.vue

- Added markups to collector detail page
- Splitted page secions into several section components

feat: add sections in collector detail page (just markups)

---

packages/mirinae/src/data-display/dynamic/dynamic-layout/mock.ts
packages/mirinae/src/data-display/tables/definition-table/PDefinitionTable.stories.mdx
packages/mirinae/src/data-display/tables/definition-table/PDefinitionTable.vue
packages/mirinae/src/data-display/tables/definition-table/definition/type.ts

1. There was an issue in `DefinitionTable` that object values are not shown in tags.
That was because `DefinitionTable` always used `default` slot of `Definition` component.
`Definition` component automatically render object values as tags, but by using `default` slot of it, it didn't work.
This is an example of showing an object values in tags well.
2. Removed origin data and replaced them with random values using fakerjs.

fix(definition-table): do not use default slot in every case

---

apps/web/src/services/dashboards/widgets/_base/base-count-of-findings/BaseCountOfFindingsWidget.vue
apps/web/src/services/dashboards/widgets/_base/base-count-of-findings/widget-config.ts
apps/web/src/services/dashboards/widgets/count-of-fail-findings/widget-config.ts

**Before**
- `CountOfPassAndFailFindings`
**After**
- `BaseCountOfFindingsWidget`
- `CountOfPassAndFailFindings`
- `CountOfFailFindings`

feat: split a widget into 2 widgets(pass and fail & fail)

---

packages/mirinae/src/styles/tailwind.pcss

[quest-340](https://pyengine.atlassian.net/browse/QUEST-340)
Solve the above issue.
Storybook postcss loader can't read tailwind css instruction with 2 or more depth.
So we changed tailwind @import path directly to dist.
There aren't other side effects in Console, Mirinae.

build(tailwindcss): solve tailwind css issue in storybook

---

apps/web/src/services/asset-inventory/collector/CollectorPage.vue
apps/web/src/services/asset-inventory/collector/modules/CollectorContents.vue
apps/web/src/services/asset-inventory/collector/modules/CollectorItemInfo.vue
apps/web/src/services/asset-inventory/collector/type.ts
apps/web/src/services/asset-inventory/store/collector-page-store.ts

- Resolve loading of `p-data-loader` at collector landing page
**KEYPOINT**
When the page is rendered, we check the 'hasCollectorList' value through the collector list API to determine whether it has been filtered by the provider or not.
1. When there is no collector list data.
commit: b8e38dc
---
2. When there is no collector list based on the selected provider + apply contents loader.
commit: 0e3e1985203187b6a9056298ad8238a7c20bebb4
🐱: The content and code I submitted in the previous PR are almost similar, but there have been some changes in the positioning and a few additions to apply the page's initial entry …

feat(collector-landing-page): resolve loading of p-data-loader at landing page

---

apps/web/src/services/asset-inventory/collector/CollectorPage.vue
apps/web/src/services/asset-inventory/collector/modules/CollectorContents.vue
apps/web/src/services/asset-inventory/collector/modules/CollectorItemInfo.vue
apps/web/src/services/asset-inventory/store/collector-page-store.ts

- Apply the remaining time of the fastest collector schedule.
`the fastest collector schedule - current time`
- Linking each collector to its history detail page.
- Apply the export function to Excel.

feat(collector-landing): apply schedule data at the current status

---

apps/web/package.json
apps/web/src/lib/site-initializer/dayjs.ts
apps/web/src/services/dashboards/widgets/_components/WidgetFrame.vue
package-lock.json

There was a bug in `WidgetFrame` component since `dayjs` can not parse the string whose format is 'YY-MM-DD'.

fix: do not use 'YY-MM-DD' format string for dayjs argument

---

apps/web/src/services/asset-inventory/collector/create-collector/modules/CreateCollectorStep1.vue
apps/web/src/services/asset-inventory/collector/create-collector/modules/CreateCollectorStep2.vue
apps/web/src/services/asset-inventory/store/collector-form-store.ts

There was wrong concept between collector and plugin in CreateCollectorStep1, 2 and collector-form-store.
plugin is not the collector. collector includes plugin. 
`collector.plugin_info === plugin`
So I changed several things.
- add `pluginInfo` state to the form store.
- change to set pluginInfo, not originCollector in create step 1.
- change to pass plugin as `CollectorPluginContents` component's `plugin` prop, not the collector in create step 2.
I guess, we all missed this since there wasn't any type declaration of `CollectorModel` or `CollectorPluginModel` in previous PRs.
Let's use typescript more tightly!! …

fix: plugin and collector is different

---

apps/web/src/services/dashboards/dashboard-customize/modules/dashboard-widget-input-form/DashboardWidgetInputForm.vue
packages/mirinae/src/inputs/buttons/toggle-button/PToggleButton.vue
packages/mirinae/src/inputs/forms/json-schema-form/PJsonSchemaForm.stories.mdx
packages/mirinae/src/inputs/forms/json-schema-form/PJsonSchemaForm.vue
packages/mirinae/src/inputs/forms/json-schema-form/components/GenerateIdFormat.vue
packages/mirinae/src/inputs/forms/json-schema-form/mock.ts
packages/mirinae/src/inputs/forms/json-schema-form/story-helper.ts

- Added `uniformWidth` prop to `JsonSchemaForm` to reduce codes that makes all the input form's width the same.
- Updated `DashboardWidgetInputForm` to use `uniformWidth` of `JsonSchemaForm`
- Also, fixed a style bug in `DashboardWidgetInputForm` that is related to `PToggleButton` component.
- Also, changed from 'flex' to 'inline-flex' in 'PToggleButton' and remove double declaration for display css property.
- Toggle buttons are often used right next to other elements. Therefore, it is much more advantageous in terms of usability to make `inline-flex` rather than `flex`.
There are some bugs in `PSelectDropdown` …

feat(mirinae): add uniformWidth prop to JsonSchemaForm and update DashboardWidgetInputForm

---

apps/web/src/common/modules/monitoring/Monitoring.vue
apps/web/src/common/modules/monitoring/config.ts
apps/web/src/common/modules/monitoring/type.ts
apps/web/src/services/asset-inventory/collector/collector-detail/CollectorDetailPage.vue
apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorBaseInfoSection.vue
apps/web/src/services/asset-inventory/collector/collector-history/collect-job/modules/JobBasicInformation.vue
apps/web/src/services/asset-inventory/collector/create-collector/modules/CreateCollectorStep1.vue
apps/web/src/services/asset-inventory/collector/create-collector/modules/CreateCollectorStep2.vue
apps/web/src/services/asset-inventory/collector/create-collector/modules/CreateCollectorStep3.vue
apps/web/src/services/asset-inventory/collector/shared/CollectorPluginContents.vue
apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorScheduleForm.vue
apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorVersionForm.vue
apps/web/src/services/asset-inventory/collector/shared/collector-forms/collector-form-store.ts
apps/web/src/services/asset-inventory/collector/type.ts
apps/web/src/services/project/project-detail/project-alert/project-webhook/modules/WebhookAddFormModal.vue
apps/web/src/store/modules/reference/plugin/actions.ts
apps/web/src/store/modules/reference/plugin/type.ts
apps/web/src/store/modules/reference/type.ts

- Updated reference store > plugin item spec.
```javascript
// As Is
{
key: pluginInfo.plugin_id,
label: pluginInfo.tags.description || pluginInfo.name,
name: pluginInfo.name,
icon: assetUrlConverter(pluginInfo.tags.icon),
}
// To Be
{
key: pluginInfo.plugin_id,
label: pluginInfo.name,
name: pluginInfo.name,
icon: assetUrlConverter(pluginInfo.tags.icon),
link: pluginInfo.tags.link,
description: pluginInfo.tags.description,
}
```
- Separate `PluginModel` interface into `CollectorPluginModel` and `RepositoryPluginModel`. Refer to backend api spec.
- [repository plugin …

refactor: update store's plugin reference item spec, update collector and plugin types

---

apps/web/src/common/composables/go-back/index.ts

There are two cases that users can come to pages:
1. They came from the other site.
2. They came from the other page in the app.
The browser back always go back to the previous url in all cases.
**But the back button inside the application must works differently for each case:**
1. Must go to the main page of the service.
2. Must go to the previous page.
To fulfill those requirements, this PR adds the useGoBack composable.

feat: add useGoBack composable

---

apps/web/src/services/asset-inventory/collector/collector-detail/CollectorDetailPage.vue

This PR applies the `useGoBack` composable to `CollectorDetailPage`.
`CollectorDetailPage` uses `beforeRouteEnter` hook of `vue-router` to get the previous path.
There is a problem that eslint works wrong with two `<script>` blocks.
The disabled comments will be deleted after eslint's bug is fixed.

feat: apply useGoBack composable to CollectorDetailPage

---

apps/web/src/services/asset-inventory/collector/collector-detail/CollectorDetailPage.vue

- Fix link of collector history button in `CollectorDetailPage`
- Add delete, edit button to `CollectorDetailPage` (markup only)

feat: add delete, edit button to CollectorDetailPage

---

packages/core-lib/src/space-connector/error.ts

This PR adds `makeApiError` function.
It helps when we use `ErrorHandler.handleRequestError()` and there is no api binding.
(If the error is not an instance of `ApiError`, it doesn't work. So the error toast does not pop up.)
**This is only for testing when api is not ready.**

feat(core-lib): add makeApiError function to make mock api error

---

packages/mirinae/package.json
packages/mirinae/tsconfig.alias.json

There was a critical issue that alias '@' is not resolved.
This PR fix this issue.

build(mirinae): fix to transpile import alias to relative path

---

apps/web/src/services/asset-inventory/collector/collector-create/CollectorCreatePage.vue
apps/web/src/services/asset-inventory/collector/collector-create/modules/CreateCollectorStep1.vue
apps/web/src/services/asset-inventory/collector/collector-create/modules/CreateCollectorStep2.vue
apps/web/src/services/asset-inventory/collector/collector-create/modules/CreateCollectorStep4.vue

The values in the input forms from step 2 to step 4 will be retained. 
If you go back to step 1 and reselect the plugin, the form will be reset.
https://github.com/cloudforet-io/console/assets/50662170/df4e5036-1d34-4f09-a6af-a42bfb81d94e

feat(collector-create-page): apply keep-alive to steps

---

packages/mirinae/src/inputs/dropdown/filterable-dropdown/PFilterableDropdown.vue
packages/mirinae/src/inputs/forms/json-schema-form/PJsonSchemaForm.stories.mdx
packages/mirinae/src/inputs/forms/json-schema-form/helper.ts

If a disabled form has a default value, the default value will be stored in the `formData`.

fix(p-json-schema-form): fix return value of refineValueByProperty

---

apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorBaseInfoSection.vue

fix: check if plugin_info is empty in CollectorBaseInfoSection

---

apps/web/src/services/dashboards/dashboard-customize/modules/dashboard-widget-input-form/DashboardWidgetInputForm.vue
apps/web/src/services/dashboards/widgets/asset-widgets/compliance-check-status/widget-config.ts

1. feat: set default value to fixedProperties of widget
[QA-528 대시보드 생성 > 대시보드 커스터마이즈 > 위젯 추가 모달 > 일부 위젯에서 default값이 지정되지 않음](https://pyengine.atlassian.net/browse/QA-528)
2. fix: update json form data when delete widget options
[QA-511 대시보드 생성 > 대시보드 커스터마이즈 > 위젯 추가 모달 > 다른 위젯으로 변경 시, validation rule이 초기화 되지 않음](https://pyengine.atlassian.net/browse/QA-511)
3. fix: add 'region' property to compliance check widget
[QA-522 대시보드 > Compliance Check Status 위젯에 Region 옵션 없음 ](https://pyengine.atlassian.net/browse/QA-522)

fix: fix bugs in asset dashboard

---

apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorServiceAccountsSection.vue
apps/web/src/services/asset-inventory/collector/shared/collector-forms/AttachedServiceAccountForm.vue

1. [fix: update appearance of service account dropdown](https://github.com/cloudforet-io/console/commit/9219fd600ce3283c211e476c0ec5ef0bfd503e99)
2. [fix: apply service accounts filter if exist](https://github.com/cloudforet-io/console/commit/0d9778793374f9c9563d41e14e368ef63ef05375)

fix: apply service accounts filter if exist and update appearance of service account dropdown

---

apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/CloudServiceDetailPage.vue
apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/cloud-service-usage-overview/CloudServiceUsageOverview.vue
apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/cloud-service-usage-overview/CloudServiceUsageOverviewDetailModal.vue

CloudServiceUsageOverview component operated like below:
1. takes `filters` prop. it is shown as query tags.
2. call get-schema api. given schema has `default_filter`.
3. call get data api with `default_filter` and `filters`.
It changed to as below:
1. takes `filters` and `hiddenFilter` props. only `filters` will be shown as query tags.
2. call get-schema api. given schema has `default_filter`.
3. call get data api with `default_filter`, `filters` and `hiddenFilter`.

feat: apply hidden filters to cloud service usage overview

---

apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorVersionForm.vue

The purpose is to set autoUpgrade to true when creating a collector.

fix(collector-version-form): fix autoUpgrade version initialization

---

apps/web/src/services/asset-inventory/cloud-service/CloudServicePage.vue
apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/cloud-service-usage-overview/CloudServiceUsageOverview.vue
apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisChart.vue
apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisDataTable.vue
apps/web/src/services/dashboards/widgets/_base/base-count-of-findings/BaseCountOfFindingsWidget.vue
apps/web/src/services/dashboards/widgets/_base/base-pie/BasePieWidget.vue
apps/web/src/services/dashboards/widgets/_base/base-trend/BaseTrendWidget.vue
apps/web/src/services/dashboards/widgets/asset-widgets/compliance-check-status/ComplianceCheckStatusWidget.vue
apps/web/src/services/dashboards/widgets/asset-widgets/severity-status-by-service/SeverityStatusByServiceWidget.vue
apps/web/src/services/dashboards/widgets/asset-widgets/total-failure-and-severity/TotalFailureAndSeverityWidget.vue
apps/web/src/services/dashboards/widgets/asset-widgets/trend-of-pass-and-fail-findings/TrendOfPassAndFailFindingsWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/aws-cloud-front-cost/AWSCloudFrontCostWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-by-region/AWSDataTransferByRegionWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-cost-trend/AWSDataTransferCostTrendWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/budget-status/BudgetStatus.vue
apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-by-target/BudgetUsageByTarget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-summary/BudgetUsageSummaryWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region/CostByRegionWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/cost-map/CostMapWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/monthly-cost/MonthlyCostWidget.vue

Whenever the Dashboard Variable at the top is modified, the widget reloads the API. However, if the variable is continuously modified, API requests accumulate, causing issues with the proper display of the dashboard. Therefore, cancelToken is applied to all widgets.
상단의 Dashboard Variable이 수정될 때마다 위젯에서 api를 다시 불러오는데, variable을 계속 수정할 경우 **api request가 쌓여 대시보드가 제대로 보이지 않는 현상 발생**. 고로 모든 위젯에 cancelToken을 적용함

refactor: set cancelToken to all widgets

---

apps/web/src/services/asset-inventory/collector/collector-create/modules/CreateCollectorStep4.vue
apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorScheduleForm.vue

1. show hours readonly UI only when the schedule power is on.
2. change the name of prop 'disableFirstLoading' to 'disableLoading' because the loading state always return false if this prop is true.
3. change the CreateCollectorStep4 component to bind prop in correct way.

fix: don't delegate page requirements to ScheduleForm component

---

apps/web/src/services/dashboards/dashboard-detail/modules/dashboard-widget-container/DashboardWidgetContainer.vue
apps/web/src/services/dashboards/store/dashboard-detail-info.ts
apps/web/src/services/dashboards/widgets/asset-widgets/compliance-check-status/widget-config.ts
apps/web/src/services/dashboards/widgets/asset-widgets/count-of-fail-findings/widget-config.ts
apps/web/src/services/dashboards/widgets/asset-widgets/count-of-pass-and-fail-findings/widget-config.ts
apps/web/src/services/dashboards/widgets/asset-widgets/severity-status-by-service/widget-config.ts
apps/web/src/services/dashboards/widgets/asset-widgets/total-failure-and-severity/widget-config.ts
apps/web/src/services/dashboards/widgets/asset-widgets/trend-of-pass-and-fail-findings/widget-config.ts

- disable 'service account' in asset dashboard & asset widgets (**backend is not ready!!!**)
- fix dashboard clone bug

feat: disable 'service_account' in asset widgets & fix dashboard clone bug

---

apps/web/src/services/dashboards/config.ts
apps/web/src/services/dashboards/default-dashboard/helper.ts
apps/web/src/services/dashboards/default-dashboard/templates/cdn-and-traffic-cost.ts
apps/web/src/services/dashboards/default-dashboard/templates/compliance-overview.ts
apps/web/src/services/dashboards/default-dashboard/templates/monthly-cost-summary.ts
apps/web/src/services/dashboards/default-dashboard/templates/type.ts
apps/web/src/services/dashboards/store/dashboard-detail-info.ts

Please see order by commits.
대시보드 생성 시 템플릿을 선택하는데, 템플릿마다 바뀌는 것이 다음 두가지입니다.
- widget list
- dashboard variables schema
기존의 템플릿 config 파일에서는, widget list는 config 파일에서, variables schema는 store에서 generate 시켜주기 때문에 혼동이 많았습니다.
고로 스토어에서 템플릿의 variables schema를 가져오는 부분을 그대로 helper 함수로 뺐습니다.
1줄요약: 요상한데서 불러오던 variables schema를 제대로 부르게됨
---
When creating a dashboard, you can choose a template, and there are two things that change depending on the template.
- widget list
- dashboard variables schema
In the template config file, the widget list is specified in the config file itself, while the variables schema is generated …

feat: get variables schema of dashboard template in template config

---

apps/web/src/services/dashboards/shared/dashboard-widget-input-form/DashboardWidgetInputForm.vue
apps/web/src/services/dashboards/widgets/_hooks/use-widget-lifecycle.ts
apps/web/src/services/dashboards/widgets/asset-widgets/compliance-check-status/ComplianceCheckStatusWidget.vue

1. Fixed the css issue below. (inherit button must be aligned to right side.)
2. Updated `useWidgetLifecycle` hook.
- Added `redrawChart` and `redrawOnLanguageChange` to `UseWidgetLifecycleOptions`
3. Updated `ComplianceCheckStatusWidget`.
- Updated to redraw the chart on the language change.
https://github.com/cloudforet-io/console/assets/26986739/18ba049e-557d-4b2d-a1e2-5b0d5fc02a59
- Updated to clear children before draw chart not to draw the chart based on previous chart.
- Updated not to pass the error to the `ErrorHandler` if the error is caused by api cancellation.

fix: redraw ComplianceCheckStatusWidget on language change

---

apps/web/src/router/index.ts

There was a bug that clears top notification bar even there is 403 error on the page.
To fix this issue, move the initialization logic for authorization error visible state to the router.beforeEach hook.

fix: clear authorization error visible state before each router changes

---

apps/web/src/services/dashboards/shared/dashboard-widget-input-form/helpers/schema-helper.ts

Hide widget options if there's **no matched dashboard variables**.
Before
After

fix: hide widget option if there's no matched variable

---

apps/web/src/common/modules/page-layouts/CenteredPageLayout.vue

I checked every pages this page layout component used and all were fine.

refactor(centered-page-layout): use mirinae layout component

---

apps/web/src/services/dashboards/dashboard-customize/DashboardCustomizePage.vue
apps/web/src/services/dashboards/dashboard-customize/modules/DashboardCustomize.vue

This PR is previous PR to reuse DashboardCustomize component in DashbardCreatePage's third step.

refactor(dashboard-customize): separate it from page to reuse

---

apps/web/src/services/dashboards/dashboard-create/DashboardCreatePage.vue
apps/web/src/services/dashboards/dashboard-customize/modules/DashboardCustomizePageName.vue
apps/web/src/services/dashboards/dashboard-customize/modules/DashboardCustomizeSidebar.vue

Added step 3 for dashboard create page.
Originally, the url was changed to 'customize' page for step3. 
It is updated not to change the url.
https://github.com/cloudforet-io/console/assets/26986739/a5844550-c402-4ec9-9c32-baa3283e9c1a

feat(dashboard-create-page): add third step (customize step)

---

packages/mirinae/src/data-display/tables/definition-table/PDefinitionTable.vue

When determining `isNoData`, during the process of checking all the values in the table, `false` values themselves are considered as representing no data, resulting in the absence of data representation.

fix(p-definition-table): fix display error if the value is false

---

apps/web/src/services/dashboards/dashboard-create/DashboardCreatePage.vue
packages/mirinae/src/layouts/centered-layout/PCenteredLayout.vue

Add div inside of the wrapper div element to observe contents area's height changes.

fix(centered-layout): observe layout contents resize

---

apps/web/src/common/modules/navigations/gnb/modules/gnb-noti/GNBNoti.vue
apps/web/src/services/dashboards/shared/DashboardRefreshDropdown.vue

Refactored to use vueuse composable for consistency.
1. GNB Notification
https://github.com/cloudforet-io/console/assets/26986739/d1c3256c-8dfe-4313-9671-3f2eedcafdf0
2. Dashboard Refresh
https://github.com/cloudforet-io/console/assets/26986739/88b121e6-454d-4c25-a489-187194b12ce4

refactor: use useDocumentVisibility composable

---

apps/web/src/services/dashboards/dashboard-detail/DashboardDetailPage.vue
apps/web/src/services/dashboards/shared/dashboard-widget-container/DashboardWidgetContainer.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/DashboardWidgetMoreOptions.vue
apps/web/src/services/dashboards/widgets/_components/WidgetViewModeModal.vue
apps/web/src/services/dashboards/widgets/_components/WidgetViewModeSidebar.vue
apps/web/src/services/dashboards/widgets/_hooks/use-widget-lifecycle.ts

- Reflect the changes **immediately** whenever the widget form is modified.
- refresh widget when close the view modal
https://github.com/cloudforet-io/console/assets/18563857/796c5550-2087-4d2c-bc92-f1fc1d4a82b8

feat: reflect the changes immediately and refresh when close view modal

---

apps/web/src/services/asset-inventory/collector/collector-detail/CollectorDetailPage.vue
apps/web/src/services/asset-inventory/collector/collector-detail/modules/AttachedServiceAccounts.vue
apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/CollectorDataModal.vue
apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/collector-data-modal-store.ts
apps/web/src/services/asset-inventory/collector/shared/collector-data-modal/modules/CollectorDataDefaultInner.vue

- remove `secrets` state at collect-data-modal store
- API call inside the modal.
- apply account name at single account collector's table
- fixed the bug of modal display when there are no jobs

fix: fixed collect-data modal state

---

apps/web/src/services/asset-inventory/collector/collector-detail/CollectorDetailPage.vue
apps/web/src/services/asset-inventory/collector/collector-detail/collector-job-store.ts
apps/web/src/services/asset-inventory/collector/collector-detail/modules/AttachedServiceAccounts.vue
apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectDataButtonGroup.vue
apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectorBaseInfoSection.vue
apps/web/src/services/asset-inventory/collector/collector-detail/modules/PluginSummaryCards.vue
apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContentItem.vue
apps/web/src/services/asset-inventory/collector/collector-main/modules/CollectorContents.vue
apps/web/src/services/asset-inventory/collector/collector-main/type.ts
apps/web/src/services/asset-inventory/collector/model.ts
apps/web/src/services/asset-inventory/collector/shared/RecentCollectorJobList.vue

Make `recentJobs` in `collector-job-store` and `CollectorContents` undefinedable.
That is to display loading case in `RcentCollectorJobList`.
Make recent job list in the detail page the same with the main page. (show recent 5 items within 5 days)
Filter in-progress job from `RcentCollectorJobList`.

fix: make recentJobs undefindable for loading UI

---

apps/web/src/services/asset-inventory/collector/shared/CollectorJobStatusIcon.vue

router-link component does not stop the click event.
To stop the click event, this PR uses custom prop.
The parent `<span>` tag of `<a>` tags will be the root element.

fix: make router-link custom inside of CollectorJobStatusIcon

---

apps/web/src/services/auth/authenticator/index.ts
apps/web/src/services/auth/sign-in/external/GOOGLE_OAUTH2/authenticator/google-auth.ts
apps/web/src/services/auth/sign-in/external/KB_SSO/authenticator/kb-auth.ts
apps/web/src/services/auth/sign-in/external/KEYCLOAK/authenticator/keycloak-auth.ts
apps/web/src/services/auth/sign-in/local/authenticator/space-auth.ts
apps/web/src/services/auth/sign-in/local/template/ID_PW.vue
apps/web/src/store/modules/user/actions.ts
apps/web/src/store/modules/user/index.ts
apps/web/src/store/modules/user/mutations.ts
apps/web/src/store/modules/user/type.ts
packages/mirinae/src/inputs/buttons/button/PButton.stories.mdx
packages/mirinae/src/inputs/buttons/button/PButton.vue
packages/mirinae/src/styles/colorsets.ts

1. Update button component's loading spinner style type.
2. Show loading spinner for all auth cases.
See the preview.

fix(web, mirinae): apply sign-in loader for external auth cases & differentiate style type of spinner for each button style type

---

packages/mirinae/src/data-display/heading/PHeading.vue

If the user copies the contents of the header, the &zwnj is copied along, causing confusion.

fix(p-heading): add &zwnj if title length is 0

---

apps/web/src/services/asset-inventory/collector/shared/CollectorPluginContents.vue
apps/web/src/services/asset-inventory/collector/shared/collector-forms/CollectorScheduleForm.vue

fix: apply loading to PLazyImg in CollectorPluginContents & make reset when enableHoursEdit prop is changed in CollectorScheduleForm

---

apps/web/src/services/asset-inventory/collector/collector-detail/CollectorDetailPage.vue
apps/web/src/services/asset-inventory/collector/collector-detail/modules/CollectDataButtonGroup.vue
apps/web/tests/asset-inventory/collector/collector-details/collect-data.spec.ts
packages/mirinae/src/data-display/popover/PPopover.stories.mdx
packages/mirinae/src/data-display/popover/PPopover.vue
packages/mirinae/src/data-display/popover/story-helper.ts

1. Add `ignoreOutsideClick` prop into `PPopver` component.
https://github.com/cloudforet-io/console/assets/26986739/478af228-c549-4215-ae67-2188bb90d2bf
2. Make popover open when collect data button is clicked in `CollectDataButtonGroup`.
See the preview.
collector detail page > collect data button click - popover must be shown.

feat: add ignoreOutsideClick prop into PPopver & make popover open when collect data button is clicked 

---

apps/web/.stylelintcache
apps/web/package.json
apps/web/src/services/auth/sign-in/SignInPage.vue
apps/web/src/services/auth/sign-in/local/template/ID_PW.vue
apps/web/src/services/home-dashboard/modules/ResourceMap.vue
apps/web/src/services/home-dashboard/modules/ServiceAccounts.vue
apps/web/src/services/home-dashboard/modules/TopProjects.vue
apps/web/src/services/home-dashboard/modules/all-summary/AllSummary.vue
package-lock.json
packages/mirinae/package.json

- Updated amcharts4 version
- Updated to use onBeforUnmount for chart dispose logics 
- Updated NOT to use deep reactivity system for chart registry to prevent maximum call stack

fix(home-dashboard): dispose chart on before unmount and do not declare chart as deep reactive state

---

packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.stories.mdx
packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue

fix(select-dropdown): remove min-width at transparent style type

---

apps/web/src/services/alert-manager/alert/modules/AlertTableBottomFilters.vue
packages/mirinae/src/data-display/tables/toolbox-table/PToolboxTable.stories.mdx
packages/mirinae/src/inputs/select-status/PSelectStatus.stories.mdx
packages/mirinae/src/inputs/select-status/PSelectStatus.vue
packages/mirinae/src/inputs/select-status/story-helper.ts

fix: use selected prop as v-model arg for p-select-status component

---

apps/web/src/services/administration/iam/role/role-update/modules/RoleUpdatePageBaseInformation.vue
apps/web/src/services/alert-manager/alert/modules/AlertTableBottomFilters.vue
apps/web/src/services/project/project-detail/modules/MaintenanceWindowFormModal.vue
packages/eslint-config-custom/index.js
packages/mirinae/src/feedbacks/loading/lazy-img/PLazyImg.vue
packages/mirinae/src/foundation/icons/PI.vue
packages/mirinae/src/inputs/select-button/PSelectButton.stories.mdx
packages/mirinae/src/inputs/select-button/PSelectButton.vue
packages/mirinae/src/inputs/select-button/story-helper.ts
packages/mirinae/src/inputs/select-card/PSelectCard.stories.mdx
packages/mirinae/src/inputs/select-card/PSelectCard.vue
packages/mirinae/src/inputs/select-card/story-helper.ts

SSIA
This PR updates eslint rule.
for more information, look [here](https://github.com/typescript-eslint/typescript-eslint/blob/1cf9243/docs/getting-started/linting/FAQ.md#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors).

fix: use selected prop as v-model arg for p-select-card, p-select-button component

---

apps/web/src/common/components/guidance/InfoMessage.vue
apps/web/src/services/cost-explorer/widgets/modules/CostDashboardSimpleCardWidget.vue
apps/web/src/services/project/project-detail/project-alert/project-alert-event-rule/modules/EventRuleConditionForm.vue
apps/web/src/services/project/project-detail/project-alert/project-alert-event-rule/modules/EventRuleForm.vue

fix: resolving Build Error Due to Variable Usage in defineProps

---

apps/web/src/common/modules/navigations/lnb/modules/LNBDividerMenuItem.vue
apps/web/src/common/modules/navigations/lnb/modules/LNBMenuItem.vue
apps/web/src/common/modules/navigations/lnb/modules/LNBRouterMenuItem.vue

SSIA
- separated for additional usage of LNB item

fix(l-n-b-menu-item): separate LNBMenuItem component

---

apps/web/src/services/cost-explorer/cost-analysis/CostAnalysisPage.vue
apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisHeader.vue
apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisQueryFilter.vue
apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisQueryFormModal.vue
apps/web/src/services/cost-explorer/store/cost-analysis-l-n-b-store.ts
apps/web/src/services/cost-explorer/store/cost-analysis-page-store.ts

SSIA
- Create `cost-analysis-l-n-b-store`. Add Data-Source state
- Separate Cost-Query logic from `cost-analysis-page-store`. (to `cost-analysis-l-n-b-store`)

feat(cost-analysis-l-n-b-store): create cost-analysis-l-n-b-store

---

apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisChart.vue
apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisChartQuerySection.vue
apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisQueryFilter.vue
apps/web/src/services/cost-explorer/cost-analysis/type.ts
apps/web/src/services/cost-explorer/lib/__tests__/helper.test.ts
apps/web/src/services/cost-explorer/lib/helper.ts
apps/web/src/services/cost-explorer/store/cost-analysis-page-store.ts
apps/web/src/services/cost-explorer/type.ts

feat: delete `primary_group_by` & change `primaryGroupBy` to `chartGroupBy`

---

apps/web/src/App.vue
apps/web/src/common/modules/navigations/lnb/modules/LNBRouterMenuItem.vue

- Fixed bug that shows session expired modal again while routing to sign-in page.
- Refactored App.vue to use script setup.

fix: do not show session expired modal while routing to sign-in page

---

apps/web/src/services/dashboards/shared/dashboard-widget-container/DashboardWidgetContainer.vue
apps/web/src/services/dashboards/store/dashboard-detail-info.ts
apps/web/src/services/dashboards/widgets/_components/WidgetFrame.vue
apps/web/src/services/dashboards/widgets/_components/WidgetViewModeModal.vue
apps/web/src/services/dashboards/widgets/_configs/config.ts
apps/web/src/services/dashboards/widgets/_helpers/widget-chart-helper.ts
apps/web/src/services/dashboards/widgets/_helpers/widget-helper.ts
apps/web/src/services/dashboards/widgets/_hooks/use-cost-widget-frame-header-dropdown.ts
apps/web/src/services/dashboards/widgets/_hooks/use-widget-lifecycle-new.ts
apps/web/src/services/dashboards/widgets/_hooks/use-widget-pagination.ts
apps/web/src/services/dashboards/widgets/_hooks/use-widget/use-cost-widget-state.ts
apps/web/src/services/dashboards/widgets/_hooks/use-widget/use-cost-widget.ts
apps/web/src/services/dashboards/widgets/_hooks/use-widget/use-widget-base-state.ts
apps/web/src/services/dashboards/widgets/_hooks/use-widget/use-widget-frame.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-map/CostMapWidget.vue

- Split widget state hook into several hooks
- Added useWidget to integrate hooks that always used together (frame props, widget state)
- Applied to CostMapWidget

refactor: split widget state into several hooks and added new lifecycle hook

---

apps/web/src/common/modules/navigations/lnb/LNB.vue
apps/web/src/common/modules/navigations/lnb/type.ts
apps/web/src/services/cost-explorer/CostExplorerLNB.vue
apps/web/src/store/modules/favorite/type.ts

SSIA
+ Add favorite type
It is first time that`show-more` has been created in LNB.
I think this case can be created again, but there is no specific usage. 
So I add extra-menu `<slot>` and `extra` menu type for creating this `show-more` item.

feat(show-more): add show-more button in cost-explorer LNB & add extra spec in LNB

---

apps/web/src/services/asset-inventory/cloud-service/cloud-service-detail/modules/CloudServiceHistoryDateSelectDropdown.vue
apps/web/src/services/asset-inventory/service-account/modules/ServiceAccountCredentialsForm.vue
apps/web/src/services/cost-explorer/budget/budget-main/modules/budget-toolbox/BudgetToolbox.vue
apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisChartLegends.vue
apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisGroupByFilter.vue
apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisPeriodSelectDropdown.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/DashboardWidgetInputForm.vue
packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.stories.mdx
packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
packages/mirinae/src/inputs/dropdown/select-dropdown/components/dropdown-button.vue
packages/mirinae/src/inputs/forms/json-schema-form/helper.ts
packages/mirinae/src/inputs/forms/json-schema-form/type.ts

SSIA
For the following reasons, I have made changes to the existing 'selectDropdown' so that 'selected' can now accept an array, string, or number, and it is internally processed as an array within the component:
- When 'selected' is singular, forcing the user to create an array to pass it in is not user-friendly. For better usability, it seems more reasonable for the component to handle this.
- Ultimately, since the processed array is what goes into the context menu or dropdown button, it does not significantly compromise code internal consistency while potentially improving usability.

refactor: change the type of 'selectedItem' to allow for both string and number and style

---

apps/web/src/services/cost-explorer/budget/budget-main/modules/budget-list/BudgetList.vue
apps/web/src/services/cost-explorer/budget/budget-main/modules/budget-toolbox/BudgetToolbox.vue

- `more` pagination in budget list page

feat: apply `more` to budget list page

---

apps/web/src/services/dashboards/shared/DashboardCustomDateRangeModal.vue
apps/web/src/services/dashboards/shared/dashboard-toolset/DashboardDateDropdown.vue
apps/web/src/services/dashboards/shared/dashboard-toolset/DashboardToolset.vue
apps/web/src/services/dashboards/store/dashboard-detail-info.ts
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

- `CustomDateRangeModal` is changed. So, I create New `DashboardCustomDateRangeModal.vue`.
- Currency and date-range-badge is removed.
- Remove default date range in `dashboard-detail-info` store. default value is `undefined`, that is shown as `Current Month`.
- Changed Toolset
- New Modal
Please, see order by commits.
**_Dropdown's new design will be applied in next PR_**

feat(dashboard-date-range-modal): create new custom date range modal & renewal toolset

---

packages/mirinae/src/inputs/datetime-picker/PDatetimePicker.stories.mdx
packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.stories.mdx
packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
packages/mirinae/src/inputs/dropdown/select-dropdown/components/dropdown-button.vue
packages/mirinae/src/inputs/dropdown/select-dropdown/composables/select-dropdown-button-display.ts
packages/mirinae/src/inputs/dropdown/select-dropdown/story-helper.ts
packages/mirinae/src/navigation/toolbox/PToolbox.vue

- Revert to Index mode for admin role logic
- Apply proxySelectedItem from dropdown-button 
- minor fixed

feat: index mode revival and apply proxySelectedItem from dropdown-button 

---

apps/web/src/services/cost-explorer/budget/shared/budget-form/BudgetForm.vue
apps/web/src/services/cost-explorer/budget/shared/budget-form/budget-form-amount-plan/BudgetFormAmountPlan.vue
apps/web/src/services/cost-explorer/budget/shared/budget-form/budget-form-amount-plan/BudgetFormAmountPlanLastMonthsCost.vue

- Change client version from v1 to v2.
- Apply dataSource currency to budgetFormAmountPlanLastMonthsCost

fix(budget-create-page): apply datasource currency & apply v2 api

---

apps/web/src/services/asset-inventory/collector/collector-create/modules/CreateCollectorStep1.vue
packages/mirinae/src/inputs/search/search/PSearch.vue

[Quest-733](https://pyengine.atlassian.net/browse/QUEST-733)
- Add `delete` event to `PSearch`.
- ~Prevent duplicated `getPlugins` call case by using `isInitialLoad` state.~
- Solve `PSearch` issue
- It didin't use internal `proxyValue`, just used `props.value` and emitted `update:value`.
- So, refactored this, `props.value` => `proxyValue`
- Now, removed `isInitialLoad` that added prev commits.
- By using `keyword` from `PSearch` and not synced `inputValue`, handled duplicated call `getPlugins`. 
New video
https://github.com/cloudforet-io/console/assets/83635051/ed1b567d-5d99-4d70-8b50-22c6572e00dc

fix(collector-create): solve searched-list issue

---

apps/web/src/services/dashboards/shared/DashboardCustomDateRangeModal.vue
apps/web/src/services/dashboards/shared/dashboard-toolset/DashboardDateDropdown.vue

[QA - 748](https://pyengine.atlassian.net/browse/QA-748)
- Edit `dateType` to `yearToMonth`.
- Fix current month mis operation case.
https://github.com/cloudforet-io/console/assets/83635051/c905bbc1-64c8-4367-930d-5ecd2a27eb0b

fix(dashboard-period): edit 'yearToMonth' dateType & refactor setting current month

---

apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisFiltersPopper.vue
apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisQueryFilter.vue
apps/web/src/services/cost-explorer/lib/helper.ts
apps/web/src/services/cost-explorer/store/cost-analysis-page-store.ts

fix: reset filters to origin data not `{}`

---

apps/web/src/common/modules/navigations/gnb/modules/gnb-recent-favorite/modules/GNBFavorite.vue
apps/web/src/lib/helper/config-data-helper.ts
apps/web/src/services/cost-explorer/CostExplorerLNB.vue
apps/web/src/services/cost-explorer/cost-analysis/config.ts
apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisHeader.vue
apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisQueryFilter.vue
apps/web/src/services/cost-explorer/routes.ts
apps/web/src/services/cost-explorer/store/cost-analysis-page-store.ts
apps/web/src/services/cost-explorer/store/cost-query-set-store.ts
apps/web/src/services/cost-explorer/type.ts

**Problem** 
- `manged-cost-query-set` didn't have unique `cost_query_set_id`. But each dataSource have `managed-cost-query-set`.
- It still works, but in favorite case, not.
**Solution**
- Every time dataSource changed, `cost-query-set-store` convert manged `cost_query_set_id` to new `cost_query_set_id` with dataSource like `managed_<data_source_id>_<cost_query_set_id>`.
- When we convert favorite config in `GNBFavorite`, we can distinguish that this is managed item by prefix `managed_`, and we can use both `<data_source_id>` and `<cost_query_set_id>`.
Please see order by commits.

fix(cost-analysis-favorite): handle managed-cost-query-set favorite case

---

apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisFiltersPopper.vue

[QA - 804](https://pyengine.atlassian.net/browse/QA-804)
In `PFilterableDropdown.vue`, handler call autocomplete api with inputValue. But, in this case, **It was not working**.
The cause was that autocomplete api's response. **Response was like `{ name: 'no label key...blah blah', label: 'same as name'}`.** 
Originally that api filtered results with `inputValue` and `label`, But **results had no `label`** to be filtered by `inputValue`.
Thus, I added logic to filter results by using `inputValue` outside api. Handler no longer directly uses inputValue in the process of requesting autocomplete api.
**Please see …

fix(cost-filter): fix filterable-dropdown keyword issue

---

apps/web/src/services/dashboards/widgets/_configs/widget-schema-config.ts
packages/mirinae/src/inputs/forms/json-schema-form/PJsonSchemaForm.vue
packages/mirinae/src/inputs/forms/json-schema-form/helpers/form-data-refine-helper.ts
packages/mirinae/src/inputs/forms/json-schema-form/helpers/inner-schema-helper.ts
packages/mirinae/src/inputs/forms/json-schema-form/helpers/json-input-helper.ts
packages/mirinae/src/inputs/forms/json-schema-form/helpers/raw-form-data-helper.ts
packages/mirinae/src/inputs/forms/json-schema-form/mock.ts
packages/mirinae/src/inputs/forms/json-schema-form/type.ts

Many things are very tightly connected, so it was impossible to split into several PRs. 
Instead, I split into several commits, so **Please review in order by commits**.

feat: init form data with reference handler at PJsonSchemaForm - added default_path to reference

---

apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisQueryFormModal.vue

SSIA
Because of limited duplication name range, we don't need to request all cost-query-set list without `dataSourceId`.

fix(query-set-name): cost-query-set's name duplication validation is limited to the same data source

---

apps/web/src/services/dashboards/shared/dashboard-variables/DashboardVariablesDropdown.vue
apps/web/src/services/dashboards/shared/dashboard-variables/DashboardVariablesSelectDropdown.vue
apps/web/src/services/dashboards/shared/dashboard-widget-container/DashboardWidgetContainer.vue
apps/web/src/services/dashboards/shared/dashboard-widget-container/WidgetViewModeModal.vue
apps/web/src/services/dashboards/widgets/_base/base-count-of-findings/BaseCountOfFindingsWidget.vue
apps/web/src/services/dashboards/widgets/_base/base-pie/BasePieWidget.vue
apps/web/src/services/dashboards/widgets/_base/base-trend/BaseTrendWidget.vue
apps/web/src/services/dashboards/widgets/_configs/config.ts
apps/web/src/services/dashboards/widgets/_hooks/use-widget-lifecycle.ts
apps/web/src/services/dashboards/widgets/asset-widgets/compliance-status/ComplianceStatusWidget.vue
apps/web/src/services/dashboards/widgets/asset-widgets/severity-status-by-service/SeverityStatusByServiceWidget.vue
apps/web/src/services/dashboards/widgets/asset-widgets/total-fail-findings-status/TotalFailFindingsStatusWidget.vue
apps/web/src/services/dashboards/widgets/asset-widgets/trend-of-pass-and-fail-findings/TrendOfPassAndFailFindingsWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/aws-cloud-front-cost/AWSCloudFrontCostWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-by-region/AWSDataTransferByRegionWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-cost-trend/AWSDataTransferCostTrendWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/budget-status/BudgetStatusWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-by-target/BudgetUsageByTargetWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-summary/BudgetUsageSummaryWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region/CostByRegionWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/cost-map/CostMapWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/monthly-cost/MonthlyCostWidget.vue

1. change to use prop & event binding way to init widget from calling initWidget directly
2. fix bug at DashboardVariableDropdown. change to redefine new object for reactivity for variableInitMap.

feat: change to use prop & event binding way to init widget from calling initWidget directly

---

apps/web/src/services/dashboards/shared/helpers/dashboard-widget-info-helper.ts
packages/core-lib/src/index.ts

add isObjectEqual to core-lib which considers undefined property and absent property are the same.

fix: apply isObjectEqual to dashboard widget info helper

---

apps/web/src/services/dashboards/dashboard-customize/modules/DashboardCustomize.vue
apps/web/src/services/dashboards/shared/dashboard-widget-container/DashboardWidgetContainer.vue
apps/web/src/services/dashboards/store/dashboard-detail-info.ts

fix: do not start observing before all widgets are mounted

---

apps/web/src/services/dashboards/widgets/__tests__/_helpers/widget-schema-helper.test.ts
apps/web/src/services/dashboards/widgets/_helpers/widget-schema-helper.ts
apps/web/src/services/dashboards/widgets/_hooks/use-widget/use-merged-widget-state.ts

1. schema properties must be always refined. (with initiated properties)
2. If widget options are set, that property must be also added to schema properties.

fix: refine schema properties with getRefinedSchemaProperties

---

apps/web/src/services/dashboards/widgets/cost-widgets/monthly-cost/MonthlyCostWidget.vue

[QA - 826](https://pyengine.atlassian.net/browse/QA-826)
Add `IAxisLabelSettings` options (`oversizedBehavior`, `maxWidth`), when drawing MonthlyCostWidget chart.
In each case using different `timeUnit`, label's `maxWith` might be changed...

fix(monthly-cost-widget): fix amcharts xAxis label issue

---

apps/web/src/services/dashboards/shared/dashboard-variables/DashboardVariablesDropdown.vue

[QA - 830](https://pyengine.atlassian.net/browse/QA-830)
At the time of dashboard variable initializing, variable (that has `default_path` and `SEARCH_RESOURCE` type) always reset to `default_path`. Even when they have a selected value.
So, I handled that case, if that variable has existing selected value.
Do you understand the name `existingVariableInfoValue`?

fix(variable): handle exception case that default variable value already exists

---

apps/web/src/services/dashboards/shared/dashboard-widget-container/WidgetViewModeModal.vue
apps/web/src/services/dashboards/shared/dashboard-widget-container/WidgetViewModeSidebar.vue
apps/web/src/services/dashboards/store/dashboard-detail-info.ts
apps/web/src/services/dashboards/widgets/_helpers/widget-schema-helper.ts
apps/web/src/services/dashboards/widgets/_helpers/widget-validation-helper.ts
apps/web/src/services/dashboards/widgets/_hooks/use-widget-lifecycle.ts
apps/web/src/services/dashboards/widgets/_hooks/use-widget/use-widget-frame.ts
packages/core-lib/src/index.ts

Main bug fix:
- commit: [fix: check schemaProperties instead of widgetOptions when validating …](https://github.com/cloudforet-io/console/commit/c434878b9ebfb9e9645200d16924fa284fed42df)
- updated `getNonInheritedWidgetOptionsAmongUsedVariables` since requirement is updated. 
- original: if the inherit option enabled property has the value in widgetOptions -> it is non inherited option
- updated: if the property in schemaProperties has enabled inherit option -> it will automatically inherit option
Others are minor bug fix.

fix: widget options must be updated when variable schema is updated by schema properties

---

apps/web/src/common/composables/amcharts5/xy-chart-helper.ts
apps/web/src/services/dashboards/widgets/_base/base-trend/BaseTrendWidget.vue
apps/web/src/services/dashboards/widgets/_helpers/widget-chart-data-helper.ts
apps/web/src/services/dashboards/widgets/_helpers/widget-chart-helper.ts
apps/web/src/services/dashboards/widgets/cost-widgets/aws-cloud-front-cost/AWSCloudFrontCostWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-by-region/AWSDataTransferByRegionWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-cost-trend/AWSDataTransferCostTrendWidget.vue

fix: apply usage_unit to AWS usage type related widgets

---

apps/web/src/lib/menu/config.ts
apps/web/src/services/cost-explorer/CostExplorerContainer.vue
apps/web/src/services/cost-explorer/CostExplorerHome.vue
apps/web/src/services/cost-explorer/route-config.ts
apps/web/src/services/cost-explorer/routes.ts
packages/language-pack/console-translation-2.8.babel
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

Commit message says it all.
I handled no-data-source case by using cost-explorer routes `beforeEnter`. How do you think about it?

feat(cost-explorer): apply cost-explorer landing page

---

apps/web/src/services/cost-explorer/cost-analysis/CostAnalysisPage.vue
apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisGranularityPeriodDropdown.vue
apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisPeriodSelectDropdown.vue
apps/web/src/services/cost-explorer/cost-analysis/modules/CostAnalysisQueryFilter.vue
apps/web/src/services/cost-explorer/type.ts

I have removed unexpected logic from the CostAnalysisPeriodSelectDropdown and separated the dependent components(Granularity dropdown, PeriodDropdown).
I think it's hard to understand. Let's get together and have a chat.

refactor(cost-analysis): separate granularity, period dropdown component concerns 

---

apps/web/src/services/administration/iam/user/modules/user-management-modal/UserManagementModal.vue
apps/web/src/services/administration/iam/user/modules/user-management-modal/modules/UserInfoForm.vue
apps/web/src/services/administration/iam/user/type.ts

A bug occurs when adding a user in 'Administration', where if the userID is checked and subsequently modified, the updated userID is not applied. To address this issue, I have modified it so that when the userID is changed, a recheck is required, and the confirm button remains disabled until the recheck is completed.
1. Enter userID and check.
2. Edit userID after checking.
Plz check by commits!!

fix: fixing the checkId bug when adding a user

---

apps/web/src/common/modules/custom-table/custom-field-modal/CustomFieldModal.vue

[issue](https://pyengine.atlassian.net/browse/QUEST-814)
When customizing table fields, the depth option for keys was fixed. I have now modified it to align with the functionality.

fix(custom-field-modal): fix key_depth calculation logic

---

packages/core-lib/src/space-connector/index.ts

API_LIST_Vn is applied even if only MOK.ENDPOINT exists.
I want to turn it on and off only with MOCK.REFLECTION.

fix(core-lib): fix SpaceConnector setting when in mock mode

---

apps/web/src/services/dashboards/widgets/_base/base-count-of-findings/BaseCountOfFindingsWidget.vue
apps/web/src/services/dashboards/widgets/_base/base-pie/BasePieWidget.vue
apps/web/src/services/dashboards/widgets/_base/base-trend/BaseTrendWidget.vue
apps/web/src/services/dashboards/widgets/_helpers/widget-chart-data-helper.ts
apps/web/src/services/dashboards/widgets/_helpers/widget-chart-helper.ts
apps/web/src/services/dashboards/widgets/_helpers/widget-table-helper.ts
apps/web/src/services/dashboards/widgets/_hooks/use-widget/use-widget-state.ts
apps/web/src/services/dashboards/widgets/asset-widgets/trend-of-pass-and-fail-findings/TrendOfPassAndFailFindingsWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/aws-cloud-front-cost/AWSCloudFrontCostWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/aws-data-transfer-by-region/AWSDataTransferByRegionWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/budget-status/BudgetStatusWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region/CostByRegionWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region/cost-by-region-data-hleper.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-map/CostMapWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/cost-map/costmap-chart-data-helper.ts

`groupBy` -> `dataField` / `parsedDataField`
Please see order by commits!

refactor: use `dataField` and `parsedDataField` rather than `groupBy` & delete `groupBy` from widgetState, widget helpers

---

apps/web/src/services/dashboards/dashboard-customize/modules/dashboard-widget-add-modal/DashboardWidgetAddModal.vue
apps/web/src/services/dashboards/shared/DashboardWidgetEditModal.vue
apps/web/src/services/dashboards/shared/dashboard-widget-container/WidgetViewModeSidebar.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/DashboardWidgetForm.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/DashboardWidgetMoreOptions.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/composables/use-widget-title-input.ts
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionDropdown.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/dashboard-widget-options-form/DashboardWidgetOptionsForm.vue
apps/web/src/services/dashboards/shared/dashboard-widget-input-form/widget-form-store.ts
apps/web/src/services/dashboards/widgets/_base/base-trend/BaseTrendWidget.vue

This refactoring was started to fix title validation bug.
I think setup store way is far better than option api way because it is far flexible.
We don't know that the store need another store or composable for the first time.
I suggest not to strictly use option store..!

refactor: change to setup store to use composable in widget-form-store

---

apps/web/src/common/modules/button/verify-button/VerifyButton.vue
apps/web/src/services/administration/iam/user/modules/user-management-tab/UserDetail.vue
apps/web/src/services/my-page/my-account/user-account/modules/NotificationEmail.vue

Previously, the 'verifyButton' existed solely for the 'notificationModal.'
However, with the introduction of MFA, the 'verifyButton' is now also used in this component.
To apply a broader scope, we have separated the 'modal' component from 'verifyButton' using slots.
plz check only the last commit

refactor: separate the 'modal' from the 'verify-button'

---

apps/web/src/services/administration/components/UserManagementFormModal.vue
apps/web/src/services/administration/components/UserManagementFormMultiFactorAuth.vue
apps/web/src/services/administration/components/UserManagementTabDetail.vue

- [disabled copy button at user tab detail](https://pyengine.atlassian.net/browse/QA-937)
- [changing attribute values for detecting only toggle state changes](https://pyengine.atlassian.net/browse/QA-942)
- Disabling MFA toggle and applying disable-MFA, then updating user information.
- Updating user information only when there is no change in the MFA toggle state.

fix: apply qa at administration page

---

apps/web/src/lib/menu/menu-architecture.ts
apps/web/src/router/index.ts
apps/web/src/services/auth/pages/KB_SSOPage.vue
apps/web/src/services/auth/pages/MultiFactorAuthPage.vue
apps/web/src/services/auth/pages/SignInPage.vue
apps/web/src/services/home-dashboard/routes/admin/routes.ts
apps/web/src/services/home-dashboard/routes/routes.ts

SSIA
- Now, user role is generated after grant, so we can't find `hadPermission` before grant. 
I handled this by using workspaceList.
- Added menuId to `home-dashboard` route

fix(sign-in): solve sign-in redirect issue

---

apps/web/src/services/dashboards/components/DashboardCreateStep1SearchFilter.vue

SSIA
[QA-1485: Create Dashboard step 1 > Dropdown 프로바이더 아이콘 왼쪽 옆에 여백이 있음](https://pyengine.atlassian.net/browse/QA-1485)

fix: edit dashboard template filter dropdown menu data

---

packages/mirinae/src/data-display/board-item/PBoardItem.vue

[QA-1536](https://pyengine.atlassian.net/browse/QA-1536)

fix: prevent board-item dropdown icon menu's native event in tablet mode

---

apps/web/public/config/development.json.sample

apps/web/public/config/development.sample.json has a JSON typo
- Change CONSLE_API (http://127.0.0.1:8081)
- Change CONSOLE_API_V2 (http://127.0.0.1:8082)
- Remove JSON typo error
The developer guides has typo and hard to debugging. Fix the wrong sample.

Fix wrong sample code (#3394)

---

apps/web/src/services/cost-explorer/components/CostAnalysisDataTypeDropdown.vue

If the alias for `cost` is 'Pay as you Go', it'll be displayed as 'Cost (Pay as you go)'!

feat(cost-analysis): set alias to cost data type dropdown

---

packages/mirinae/src/data-display/tree/tree-view/PTreeItem.vue
packages/mirinae/src/data-display/tree/tree-view/PTreeView.vue

SSIA
Add `useDefaultIndent` props to `PTreeView`, `PTreeItem`

fix(tree-components): add default indent props

---

apps/web/src/common/composables/amcharts5/tree-map-helper.ts
apps/web/src/services/asset-inventory/components/MetricExplorerHorizontalColumnChart.vue
apps/web/src/services/asset-inventory/helpers/metric-explorer-data-table-helper.ts
apps/web/src/services/dashboards/widgets/cost-widgets/cost-map/CostMapWidget.vue

fix: fix data formatter of metric data table

---

apps/web/src/schema/cost-analysis/cost-query-set/type.ts
apps/web/src/services/asset-inventory/components/AssetAnalysisChart.vue
apps/web/src/services/asset-inventory/components/AssetAnalysisDataTable.vue
apps/web/src/services/asset-inventory/components/AssetAnalysisDonutChart.vue
apps/web/src/services/asset-inventory/components/AssetAnalysisHeader.vue
apps/web/src/services/asset-inventory/components/AssetAnalysisHorizontalColumnChart.vue
apps/web/src/services/asset-inventory/components/AssetAnalysisLineChart.vue
apps/web/src/services/asset-inventory/components/AssetAnalysisNameFormModal.vue
apps/web/src/services/asset-inventory/components/AssetAnalysisQuerySection.vue
apps/web/src/services/asset-inventory/components/AssetAnalysisTreeMapChart.vue
apps/web/src/services/asset-inventory/stores/asset-analysis-page-store.ts
apps/web/src/services/cost-explorer/components/BudgetDetailInfo.vue
apps/web/src/services/cost-explorer/components/CostAnalysisQuerySection.vue
apps/web/src/services/cost-explorer/stores/cost-analysis-page-store.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: set query filter only if there're value & fix qa things

---

apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
apps/web/src/services/dashboards/components/DashboardCreateStep1.vue
apps/web/src/services/dashboards/components/DashboardCreateStep1SearchFilter.vue

- Edit Table Widget style
- Apply new dashboard label filter planning

fix(dashboard-qa): solve some QAs

---

apps/web/src/services/landing/components/LandingGroupWorkspaces.vue
apps/web/src/services/landing/components/LandingWorkspaceGroupManageOverlay.vue
apps/web/src/services/landing/components/LandingWorkspaceGroupTab.vue
apps/web/src/services/landing/components/LandingWorkspaceGroupTabGroupUser.vue
apps/web/src/services/landing/store/landing-page-store.ts
apps/web/src/store/app-context/workspace/user-workspace-group-store.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

https://github.com/user-attachments/assets/2921290a-f297-40a2-a93a-33b2f525417b

feat(WorkspaceGroupUser): apply workspaceGroupUser api & UI

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFilters.vue
apps/web/src/lib/variable-models/_base/resource-variable-model.ts
apps/web/src/lib/variable-models/_base/types.ts

feat: merge dashboard-september to master

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFooter.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardHeaderTitle.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformDataTableDropdown.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformForm.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformFormEvaluate.vue
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

fix: create legacy evaluate expression & add legacy-warning UI

---

apps/web/src/services/cost-explorer/components/CostAnalysisChart.vue
apps/web/src/services/cost-explorer/components/CostAnalysisStackedColumnChart.vue

There was an issue where the loading screen appeared during chart rendering, but intermittently showed 'No Data Available' during data loading. 
This issue occurred because multiple API calls were made, and when an earlier API call was canceled, the loading state would incorrectly switch to false. 
The issue was resolved by ensuring the loading state is only set to false when the API call returns a success or an error.

fix: prevent setting loading to false on api cancellation in CostAnalysisChart

---

apps/web/src/services/cost-explorer/components/CostAnalysisChart.vue
apps/web/src/services/cost-explorer/components/CostAnalysisStackedColumnChart.vue

There was an issue on the cost analysis page where the chart legend was not syncing correctly when selecting or deselecting groupBy or filter options. 
The primary cause was that the legend was only updated to match the data when it was empty. 
This has been resolved by ensuring the legend is updated on every interaction.

fix: update cost analysis chart legend based on data

---

apps/web/src/common/modules/widgets/_helpers/widget-date-helper.ts
apps/web/src/common/modules/widgets/_widgets/table/Table.vue

- Edit date-range helper
If you select October (not current month) in date dropdown and select daily (granularity), 
date-range must be converted `2024-10-01`-`2024-10-31`, but it was not. 
It was converted to `2024-09-05`-`2024-10-04`,  as if you chose current month in date dropdown.

fix(widget): solve widget date-range bug

---

apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesFormModal.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesMoreButton.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesV2.vue

fix: show only `use: true` vars properties

---

apps/web/src/common/modules/widgets/_components/WidgetFormAssetSecurityDataSourcePopper.vue

[Feedback](https://www.notion.so/130bfa76599680aba950d898159c2b98?pvs=4)

fix: solve missing asset category issue in datatable-datasource popper

---

apps/web/src/common/composables/form-validator/__tests__/index.test.ts
apps/web/src/common/composables/form-validator/index.ts

Enhance `useFormValidator` for Flexible Validation and External State Control
This PR improves `useFormValidator` by allowing external injection of field validator, providing greater flexibility in form validation scenario. Previously, `useFormValidator` managed validation as a single unit, which limited adaptability when specific form fields required unique validation behavior. By accepting `useFieldValidator` directly for individual fields, `useFormValidator` now supports custom validation scenarios within a single form setup without the need for redundant instances.
- **Flexible Validator Handling**: Updated the `forms` option to accept `useFieldValidator` instances directly for specific fields, supporting unique validation logic and enabling field-level customization within a single …

feat: enhance useFormValidator for flexible field-level control

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardHeaderTitle.vue
apps/web/src/common/modules/widgets/_widget-fields/advanced-format-rules/WidgetFieldAdvancedFormatRules.vue
apps/web/src/common/modules/widgets/_widget-fields/custom-table-column-width/WidgetFieldCustomTableColumnWidth.vue
apps/web/src/common/modules/widgets/_widget-fields/format-rules/WidgetFieldFormatRules.vue
apps/web/src/common/modules/widgets/_widget-fields/max/WidgetFieldMax.vue
apps/web/src/common/modules/widgets/_widget-fields/min/WidgetFieldMin.vue
apps/web/src/common/modules/widgets/_widget-fields/table-column-width/WidgetFieldTableColumnWidth.vue
apps/web/src/services/advanced/pages/admin/AdminDomainSettingsAutoDormancyConfigurationPage.vue
apps/web/src/services/alert-manager/components/EscalationPolicyFormRulesInput.vue
apps/web/src/services/asset-inventory/components/MetricExplorerQueryFormSidebar.vue
apps/web/src/services/cost-explorer/components/CostReportSettingsModal.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesFormManual.vue
apps/web/src/services/info/components/NoticeForm.vue
apps/web/src/services/project/components/ProjectGroupMemberManagementModal.vue
packages/mirinae/src/inputs/input/text-input/PTextInput.stories.ts
packages/mirinae/src/inputs/input/text-input/PTextInput.vue
packages/mirinae/src/inputs/input/text-input/story-helper.ts

Feature update
- Added a `type` prop to allow specifying input types like text, password, etc.
- Introduced a `block` class to enable full-width styling of the input element.
- Updated story helper to include new type options for better component configurability.
Apply changes
- Removed unnecessary width styling from custom components.
- Added `block` property to improve layout consistency.

fix: fix PTextInput style bug

---

packages/mirinae/src/feedbacks/modals/button-modal/PButtonModal.vue
packages/mirinae/src/feedbacks/modals/button-modal/story-helper.ts
packages/mirinae/src/layouts/overlay-layout/POverlayLayout.vue
packages/mirinae/src/layouts/overlay-layout/story-helper.ts
packages/mirinae/src/layouts/sidebar/PSidebar.mdx
packages/mirinae/src/layouts/sidebar/PSidebar.stories.ts
packages/mirinae/src/layouts/sidebar/PSidebar.vue
packages/mirinae/src/layouts/sidebar/story-helper.ts

feat(mirinae): emit 'closed' event after modal transition ends & add backdrop feature to PSidebar component

---

apps/web/package.json
apps/web/src/common/modules/navigations/new-lsb/LSBContainer.vue
apps/web/src/common/modules/navigations/new-lsb/LSBDivider.vue
apps/web/src/common/modules/navigations/new-lsb/LSBRouterButton.vue
apps/web/src/common/modules/navigations/new-lsb/LSBRouterItem.vue
apps/web/src/common/modules/navigations/new-lsb/LSBTopTitle.vue
apps/web/src/common/modules/navigations/new-lsb/composables/use-lsb-router-item-state.ts
apps/web/src/common/modules/navigations/new-lsb/type.ts
package-lock.json

```html
<l-s-b-container>
<l-s-b-router-button icon="ic_dots-4-square">
All Categories
</l-s-b-router-button>
<l-s-b-divider />
<l-s-b-top-title>Category</l-s-b-top-title>
<l-s-b-router-item id="test"
to="/test"
>
Test
</l-s-b-router-item>
</l-s-b-container>
```
1. **New LSB Navigation Components Added**
- **`LSBContainer`**: Base container for padding
- **`LSBDivider`**: Divider between items
- **`LSBTopTitle`**: Displays the top title of the LSB
- **`LSBRouterButton`**: Single router button
- **`LSBRouterItem`**: Repeatedly rendered router item
2. **LSB Router Item State Hook Added**
- Common hook to manage routing state (current path, active status, etc.)
---
1. **새로운 LSB 내비게이션 컴포넌트 추가**
- **`LSBContainer`**: padding 처리용 기본 컨테이너
- **`LSBDivider`**: 항목 간 구분선
- **`LSBTopTitle`**: LSB 상단 …

feat: add new LSB navigation components and router item state management

---

apps/web/src/common/components/modals/ConfirmBackModal.vue
apps/web/src/common/components/modals/DeleteModal.vue
apps/web/src/common/composables/confirm-route-leave/index.ts
apps/web/src/common/composables/go-back/index.ts
apps/web/src/common/modules/navigations/new-lsb/LSBLoadingSpinner.vue
packages/mirinae/src/controls/forms/field-group/PFieldGroup.mdx
packages/mirinae/src/controls/forms/field-group/PFieldGroup.stories.ts
packages/mirinae/src/controls/forms/field-group/PFieldGroup.vue
packages/mirinae/src/controls/forms/field-group/story-helper.ts
packages/mirinae/src/data-display/badge/PBadge.vue
packages/mirinae/src/data-display/badge/type.ts

feat: add confirm-route-leave composable

---

apps/web/src/services/alert-manager-v2/components/ServiceDetailTabs.vue
apps/web/src/services/alert-manager-v2/components/ServiceDetailTabsOverviewEscalationPolicy.vue
apps/web/src/services/alert-manager-v2/components/ServiceDetailTabsOverviewNotification.vue
apps/web/src/services/alert-manager-v2/components/ServiceDetailTabsOverviewWebhook.vue
apps/web/src/services/alert-manager-v2/components/ServiceList.vue
apps/web/src/services/alert-manager-v2/store/service-detail-page-store.ts
apps/web/src/services/workspace-home/components/WorkspaceInfo.vue

I implemented it by using the query string to replace the tab since clicking the details button in the overview tab needs to navigate to the corresponding tab.

feat: apply tab switching when the details button in the overview tab is clicked

---

apps/web/src/services/asset-inventory/components/CollectorBaseInfoSection.vue
apps/web/src/services/asset-inventory/components/CollectorCreateStep4.vue
apps/web/src/services/asset-inventory/components/CollectorDataModal.vue
apps/web/src/services/asset-inventory/components/CollectorDetailNameEditModal.vue
apps/web/src/services/asset-inventory/components/CollectorDetailOptionsSection.vue
apps/web/src/services/asset-inventory/components/CollectorDetailScheduleSection.vue
apps/web/src/services/asset-inventory/components/CollectorDetailServiceAccountsSection.vue
apps/web/src/services/asset-inventory/components/CollectorFormOptions.vue
apps/web/src/services/asset-inventory/components/CollectorFormSchedule.vue
apps/web/src/services/asset-inventory/components/CollectorHistoryJobTaskTable.vue
apps/web/src/services/asset-inventory/components/ServiceAccountBaseInformationForm.vue
apps/web/src/services/asset-inventory/pages/CollectHistoryJobPage.vue
apps/web/src/services/asset-inventory/pages/CollectorDetailPage.vue
apps/web/src/services/asset-inventory/pages/CollectorHistoryPage.vue
apps/web/src/services/asset-inventory/pages/CollectorMainPage.vue
apps/web/src/services/asset-inventory/pages/ServiceAccountAddPage.vue
apps/web/src/services/asset-inventory/pages/admin/AdminCollectHistoryJobPage.vue
apps/web/src/services/asset-inventory/pages/admin/AdminCollectorDetailPage.vue
apps/web/src/services/asset-inventory/pages/admin/AdminCollectorHistoryPage.vue
apps/web/src/services/asset-inventory/pages/admin/AdminCollectorMainPage.vue
apps/web/src/services/asset-inventory/stores/collector-data-modal-store.ts
apps/web/src/services/asset-inventory/stores/collector-detail-page-store.ts
apps/web/src/services/asset-inventory/stores/collector-job-store.ts
apps/web/src/services/asset-inventory/stores/collector-page-store.ts
apps/web/src/store/reference/collector-reference-store.ts

feat: update API call to use inventory V2

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
apps/web/src/common/modules/widgets/types/widget-model.ts

- remove deprecated data-table options (additional label, separate date)
- apply new timediff-planning

fix(add-data-table): remove deprecated data-table options (additional label, separate date) & apply new timediff-planning

---

apps/web/src/common/modules/widgets/_composables/use-widget-date-range.ts
apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/ColorCodedHeatmap.vue
apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
apps/web/src/common/modules/widgets/_widgets/heatmap/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
apps/web/src/common/modules/widgets/_widgets/line-chart/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/table/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
apps/web/src/common/modules/widgets/_widgets/treemap/widget-config.ts

feat(widget-config): refactor widget-config & refactor date-range composable

---

apps/web/package.json
apps/web/src/translations/index.ts
package-lock.json
packages/mirinae/src/data-display/badge/PBadge.vue
packages/mirinae/src/data-display/badge/type.ts

1. Added violet200 style to badge component
2. Added getParticle() helper of i18n to convert korean particle such as '은, 는, 을, 를, 이, 가'

feat(badge): add violet color mixin to PBadge component

---

apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/default-value-registry.ts
apps/web/src/common/modules/widgets/_widget-field-value-manager/index.ts
apps/web/src/schema/dashboard/private-widget/api-verbs/load.ts
apps/web/src/schema/dashboard/public-widget/api-verbs/load.ts
apps/web/src/services/dashboards/components/dashboard-detail/DashboardWidgetContainerV2.vue
apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts

- Apply `WidgetFieldValueManager` to widget form.
- Refactor `WidgetFieldValueManager` data (Proxy -> Ref).
- Apply new `widget.load` params.

feat(widget-form): apply field-value-manager to widget form & refactor field-value-manager

---

apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts
apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue

refactor(number-card): use new widget/load-sum api

---

apps/web/src/common/modules/user/UserSelectDropdown.vue
apps/web/src/common/modules/user/typte.ts
apps/web/src/lib/variable-models/managed-model-config/base-managed-model-config.ts
apps/web/src/lib/variable-models/managed-model/resource-model/user-group-variable-model.ts
apps/web/src/services/dashboards/stores/all-reference-type-info-store.ts
apps/web/src/store/reference/all-reference-store.ts
apps/web/src/store/reference/user-group-reference-store.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: update user select dropdown

---

packages/mirinae/src/data-display/dynamic/dynamic-layout/PDynamicLayout.mdx
packages/mirinae/src/data-display/dynamic/dynamic-layout/templates/item/index.vue
packages/mirinae/src/data-display/dynamic/dynamic-layout/templates/item/item.mdx
packages/mirinae/src/data-display/dynamic/dynamic-layout/type/index.ts

A new specification has been added to the Item Dynamic Layout, which previously did not function without the existing field option.
If the field option does not exist and the root data is in the form of an object, the object itself is displayed to fit the Item layout.
<br/>
기존 field 옵션이 없으면 작동하지 않는 Item Dynamic Layout에 스펙이 추가되었습니다.
field 옵션이 존재하지 않으면서 root data가 객체 형태로 존재하게 되면, 객체 자체를 Item 레이아웃에 맞게 보여줍니다.

feat(dynamic-layout): add no-field case spec to Dynamic Layout(item-type)

---

apps/web/src/lib/site-initializer/initTaskManagementTemplate.ts
apps/web/src/store/reference/all-reference-store.ts
apps/web/src/store/reference/plugin-reference-store.ts
apps/web/src/store/reference/role-reference-store.ts

fix: add user session check in task management template initialization and remove reactive from getters of plugin, role  reference store

---

apps/web/src/services/ops-flow/stores/admin/package-store.ts

fix(package-store): update items array to trigger reactivity on default package change

---

apps/web/src/common/modules/widgets/_composables/use-widget-options-complex-validation.ts
apps/web/src/common/modules/widgets/_helpers/widget-date-helper.ts
apps/web/src/common/modules/widgets/_helpers/widget-load-helper.ts
apps/web/src/schema/dashboard/private-widget/api-verbs/load.ts
apps/web/src/schema/dashboard/public-widget/api-verbs/load.ts

feat: delete unused widget helper and validation code

---

apps/web/src/services/auth/authenticator/index.ts
apps/web/src/services/ops-flow/components/BoardTaskComment.vue
apps/web/src/services/ops-flow/composables/use-mention.ts

refactor: separate mention functionality from comment input component

---

.github/workflows/pull_request_deploy_preview.yaml

I have added a GitHub Action to enable optional deployment of a preview environment for PRs.
When a user from the cloudforet-io organization comments /preview on a PR, the deployment will be triggered. 
Once the deployment is complete, the preview URL will be added as a new comment.
---
PR에서 preview환경이 필요한 경우 선택적으로 배포되도록 github-action을 추가하였습니다.
PR에서 댓글로 /preview를 작성 시, cloudforet-io 조직 유저의 경우 배포가 가능합니다. 
배포 완료 시, url이 comment로 추가 생성 될 것입니다.

ci(github-action): add workflow for deploy preview on PR comment

---

apps/web/src/lib/menu/menu-info.ts
apps/web/src/schema/opsflow/_types/task-field-type.ts
apps/web/src/services/ops-flow/components/AssociatedTasks.vue
apps/web/src/services/ops-flow/components/BoardTaskNameField.vue
apps/web/src/services/ops-flow/components/BoardTaskTable.vue
apps/web/src/services/ops-flow/components/TaskContentBaseForm.vue
apps/web/src/services/ops-flow/routes/routes.ts
apps/web/src/services/ops-flow/task-fields-configuration/stores/use-task-field-metadata-store.ts
apps/web/src/services/ops-flow/task-fields-form/composables/use-task-field-validation.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

fix: update icons and add workspaceId prop to task components

---

apps/web/src/common/modules/user/UserSelectDropdown.vue
apps/web/src/router/alert-manager-v1-admin-routes.ts
apps/web/src/router/alert-manager-v1-workspace-routes.ts
apps/web/src/services/ops-flow/components/BoardTaskFilters.vue
apps/web/src/services/ops-flow/components/TaskTypeForm.vue
apps/web/src/services/ops-flow/task-fields-form/field-templates/UserTaskField.vue

feat: apply user select dropdown at opsFlow

---

apps/web/src/common/modules/user/UserSelectDropdown.vue

feat: apply empty data at user select dropdown

---

apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts
apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/ColorCodedHeatmap.vue
apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
apps/web/src/common/modules/widgets/_widgets/sankey-chart/SankeyChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
apps/web/src/common/modules/widgets/_widgets/table/Table.vue
apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

fix(widget-error): apply no-data-table error case & refactor useWidgetFrame

---

apps/web/src/services/iam/components/UserGroupChannelSetInputForm.vue
apps/web/src/services/iam/components/UserGroupDeleteDoubleCheckModal.vue
apps/web/src/services/iam/components/UserGroupManagementAddUsersModal.vue
apps/web/src/services/iam/components/UserGroupManagementTabNotificationChannel.vue
apps/web/src/services/iam/components/UserGroupManagementTabUsers.vue
apps/web/src/services/iam/components/UserGroupManagementTable.vue
apps/web/src/services/iam/components/UserPerGroupRemoveDoubleCheckModal.vue
apps/web/src/services/iam/composables/user-data-helper.ts
apps/web/src/services/iam/constants/user-group-constant.ts
apps/web/src/services/iam/pages/UserGroupMainPage.vue
apps/web/src/services/iam/store/user-group-page-store.ts

- [issue1](https://mzdevs.atlassian.net/browse/MZ00003-1483)
- [issue2](https://mzdevs.atlassian.net/browse/MZ00003-1494)
- [issue3](https://mzdevs.atlassian.net/browse/MZ00003-1495)
- [issue4](https://mzdevs.atlassian.net/browse/MZ00003-1500)
- [issue5](https://mzdevs.atlassian.net/browse/MZ00003-1563)
- [issue6](https://mzdevs.atlassian.net/browse/MZ00003-1565)
- [issue7](https://mzdevs.atlassian.net/browse/MZ00003-1568)
- [issue8](https://mzdevs.atlassian.net/browse/MZ00003-1571)
- [issue9](https://mzdevs.atlassian.net/browse/MZ00003-1580)
- [issue10](https://mzdevs.atlassian.net/browse/MZ00003-1581)

Feat: apply qa issue

---

apps/web/src/common/modules/navigations/top-bar/modules/TopBarSuggestionList.vue
apps/web/src/lib/file-manager/index.ts
apps/web/src/services/info/stores/notice-detail-store.ts

fix(notice-detail-store): prevent duplicate requests while loading data

---

packages/mirinae/src/layouts/vertical-layout/PVerticalLayout.vue

Refactor: changing resizer line to fatter when it hoverd

---

apps/web/src/schema/alert-manager/webhook/api-verbs/update-message-format.ts
apps/web/src/schema/alert-manager/webhook/model.ts
apps/web/src/schema/alert-manager/webhook/type.ts
apps/web/src/services/alert-manager/components/AlertDetailTabsTimeline.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRule.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsWebhookDetailTabs.vue
apps/web/src/services/alert-manager/components/ServiceList.vue
apps/web/src/services/alert-manager/constants/common-constant.ts
apps/web/src/services/alert-manager/constants/webhook-table-constant.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: apply webhook message tab

---

apps/web/src/services/iam/components/UserGroupDeleteDoubleCheckModal.vue
apps/web/src/services/iam/components/UserManagementStatusModal.vue

- before update 
- after update

feat: fix bug of badge in double check table modal

---

apps/web/src/schema/alert-manager/event-rule/type.ts
apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRuleConditionForm.vue
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: add operator

---

apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRuleActionAsset.vue

chore: changed css

---

.github/workflows/pull_request_random_reviewer_assignment.yaml
.github/workflows/pull_request_review_labeler.yaml
apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRuleActionAsset.vue
apps/web/src/store/reference/collector-reference-store.ts
apps/web/src/store/reference/region-reference-store.ts

* ci: add check for PR author organization membership and assign them (#5521)
* chore: for ci test
* ci: add check for PR author organization membership and assign them
* ci: update pull request review labeler to handle reopened events
* ci: enhance pull request review labeler to handle missing review state
---------
* chore: ci test (#5522)
* fix(reference-store): correct logic for selecting fetcher based on version (#5536)
- Inverted the condition for determining the collector and region fetchers
- Ensured correct API client is used based on alert manager version
* chore: changed css (#5537)
---------

feat: apply alert manager (#5539)

---

apps/web/src/services/alert-manager/components/AlertDetailTabsTimeline.vue
apps/web/src/services/alert-manager/components/AlertDetailTabsTimelineModal.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRuleFormCard.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsWebhookDetail.vue
apps/web/src/services/alert-manager/constants/alert-table-constant.ts
apps/web/src/services/alert-manager/constants/webhook-table-constant.ts

fix: fixed qa bug

---

apps/web/src/services/my-page/components/UserAccountMultiFactorAuthFormModal.vue
apps/web/src/services/my-page/pages/UserAccountPage.vue
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

fix(user-account-page): apply changed planning (password-check, set mfa)

---

apps/web/src/services/cost-explorer/constants/cost-explorer-constant.ts

fix(cost-analysis): add project-group filter

---

packages/mirinae/src/controls/input/query-input/PQueryInput.vue

The issue occurred because the changes made to the useContextMenuStyle composable were not reflected in PQueryItem.

fix: reflect the latest changes in composable to the queryInput

---

apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRuleFormCard.vue

fix: fixed bug with missing data in event rule condition edits

---

.github/workflows/dispatch_master_to_develop.yaml
.github/workflows/dispatch_release.yaml
.github/workflows/pull_request_check_revert_candidate_commits.yaml

chore: create workflows merge from master to develop and check commits

---

package-lock.json
package.json
turbo.json

<details>
<summary>Turbo 2.3.4 Breaking changes</summary>
- Ignore turbo field in package.json ([PR](https://github.com/vercel/turbo/pull/8023))
- Turborepo’s default disk cache location moved to .turbo/cache from node_modules/.cache ([PR](https://github.com/vercel/turbo/pull/8126))
- pipeline key in turbo.json renamed to tasks ([PR](https://github.com/vercel/turbo/pull/8157))
- File globs for directories in inputs/outputs include the directory's contents (e.g. dist anddist/ equal dist/**) ([PR](https://github.com/vercel/turbo/pull/8180))
- outputMode key renamed to outputLogs for clarity and to match the --output-logs flag ([PR](https://github.com/vercel/turbo/pull/8149))
- This change will be reflected in Run Summaries in resolvedTaskConfig
- Error on environment variable syntax in …

build: update turbo to version 2.3.4

---

apps/web/src/common/components/forms/pairs-form/PairsForm.vue
apps/web/src/common/components/forms/pairs-input-group/PairsInputGroup.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsWebhookDetailMessageOverlay.vue

- Format messages when updating the 'Service' design because the request requires a longer text input width
- common component `PairsForm` & `PairsInputGroup` are used in this page
- All pages using that component will not be affected by this update, except when using the 'is-long-value' prop.
- without `is-longer-value` 
- with `is-longer-value`

feat: update pairsForm & pairsInputGroup component

---

packages/mirinae/src/layouts/overlay-layout/POverlayLayout.vue
packages/mirinae/src/layouts/overlay-layout/story-helper.ts

feat: add header slot at overlay layout

---

.github/workflows/pull_request_review_state_labeler.yaml

GITHUB_TOKEN doesn't have write permission for issue label for the pr review event.
So changed to use FGPT.

ci: update PR review labeler workflow token name

---

apps/web/src/api-clients/_common/composables/use-scoped-query.ts
apps/web/src/common/modules/widgets/_composables/use-widget-form-query.ts
apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/ColorCodedHeatmap.vue
apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
apps/web/src/common/modules/widgets/_widgets/sankey-chart/SankeyChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
apps/web/src/common/modules/widgets/_widgets/table/Table.vue
apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardLabelsButton.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardRefreshDropdown.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardWidgetContainerV2.vue
apps/web/src/services/dashboards/composables/use-dashboard-detail-query.ts
apps/web/src/services/dashboards/composables/use-dashboard-query.ts
apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
apps/web/src/services/project-v1/pages/ProjectDashboardPage.vue

- Create `use-scoped-query` to handle api scope
- Refactor minor things

feat(vue-query): create global useQuery composable (`use-scoped-query`) & refactor dashboard

---

apps/web/src/api-clients/_common/composables/use-scoped-query.ts
apps/web/src/api-clients/dashboard/public-widget/schema/model.ts
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts
apps/web/src/common/modules/widgets/_helpers/widget-helper.ts
apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/default-value-registry.ts
apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/validator-registry.ts
apps/web/src/common/modules/widgets/_widget-field-value-manager/index.ts
apps/web/src/common/modules/widgets/_widget-field-value-manager/type.ts
apps/web/src/common/modules/widgets/_widget-fields/data-field/WidgetFieldDataField.vue
apps/web/src/common/modules/widgets/_widget-fields/format-rules/WidgetFieldFormatRules.vue
apps/web/src/common/modules/widgets/_widget-fields/group-by/WidgetFieldGroupBy.vue
apps/web/src/common/modules/widgets/_widget-fields/sankey-dimensions/WidgetFieldSankeyDimensions.vue
apps/web/src/common/modules/widgets/_widget-fields/sankey-dimensions/type.ts
apps/web/src/common/modules/widgets/_widgets/sankey-chart/widget-config.ts

feat(widget-options-architecture): apply advanced architecture

---

apps/web/src/services/alert-manager/components/AlertDetailInfoTable.vue
apps/web/src/services/alert-manager/components/AlertsManagementTable.vue
apps/web/src/services/alert-manager/components/ServiceListContent.vue
apps/web/src/services/asset-inventory-v1/components/CloudServiceAlertsTab.vue

fix(alert-manager): solve alert-manager empty page issue

---

apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep1.vue
apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardDetailHeader.vue
apps/web/src/services/dashboards/composables/use-dashboard-control-menu-items.ts
apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts

fix(dashboard): solve dashboard toolset dropdown issue & small fix

---

apps/web/src/lib/config/composables/use-is-alert-manager-v2-enabled.ts
apps/web/src/services/project-v1/components/ProjectDetailTabHeader.vue
apps/web/src/services/project-v1/pages/ProjectDetailTabPage.vue
apps/web/src/services/project-v1/pages/ProjectSummaryPage.vue
apps/web/src/store/reference/escalation-policy-reference-store.ts
apps/web/src/store/reference/service-reference-store.ts
apps/web/src/store/reference/webhook-reference-store.ts

fix(alert-v2): solve service store bug

---

packages/mirinae/src/data-display/cards/card/PCard.vue
packages/mirinae/src/data-display/cards/card/config.ts

- update `PCard` spec (add gray200 at header)

feat: add spec of `PCard`header color

---

apps/web/src/services/asset-inventory/components/CollectorHistoryJobTaskErrorList.vue

Potential fix for [https://github.com/cloudforet-io/console/security/code-scanning/30](https://github.com/cloudforet-io/console/security/code-scanning/30)
To fix the problem, we need to ensure that all leading newline characters are removed from the string `result`. The best way to achieve this is by using a regular expression with the global flag (`g`) to match all occurrences of the newline character at the beginning of the string. This will ensure that all leading newline characters are removed, regardless of how many there are.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Potential fix for code scanning alert no. 30: Incomplete string escaping or encoding

---

apps/web/src/services/cost-explorer/components/CostAnalysisDataTable.vue

- cost analysis page > Data Table Total Footer bug

fix: fix to prevent string concatenation in data table footer totals

---

apps/web/src/api-clients/identity/domain/composables/use-domain-api.ts
apps/web/src/api-clients/identity/project-group/composables/use-project-group-api.ts
apps/web/src/api-clients/identity/project/composables/use-project-api.ts
apps/web/src/api-clients/identity/provider/composables/use-provider-api.ts
apps/web/src/api-clients/identity/service-account/composables/use-service-account-api.ts
apps/web/src/api-clients/identity/token/composables/use-token-api.ts
apps/web/src/api-clients/identity/trusted-account/composables/use-trusted-account-api.ts
apps/web/src/api-clients/identity/user-group/composables/use-user-group-api.ts
apps/web/src/api-clients/identity/user-profile/composables/use-user-profile-api.ts
packages/mirinae/src/controls/input/text-input/PTextInput.vue

feat: add composables for identity API clients

---

apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/default-value-registry.ts
apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilter.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterNumberInput.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesV2.vue
apps/web/src/services/dashboards/pages/DashboardDetailPage.vue
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

chore(dashboard-variable): rollback reverted changes

---

apps/web/src/services/alert-manager/v2/components/AlertDetailTabsTimelineModal.vue
apps/web/src/services/alert-manager/v2/pages/ServiceDetailPage.vue

feat: set service name at breadcrumbs

---

apps/web/src/services/alert-manager/v2/components/AlertsManagementTable.vue
apps/web/src/services/alert-manager/v2/constants/alert-table-constant.ts

feat: add service_name, description fields at alert excel

---

apps/web/src/services/alert-manager/v2/components/AlertsManagementTable.vue

chore: apply webhook/app name at alert excel

---

apps/web/src/services/alert-manager/v2/components/AlertsManagementTable.vue
apps/web/src/services/alert-manager/v2/constants/alert-table-constant.ts

fix: fixed reference fields (alert excel)

---

apps/web/src/services/advanced/routes/admin/routes.ts
apps/web/src/services/alert-manager/v2/routes/routes.ts
apps/web/src/services/asset-inventory/routes/admin/routes.ts
apps/web/src/services/asset-inventory/routes/routes.ts
apps/web/src/services/ops-flow/components/BoardTaskFilters.vue
apps/web/src/services/ops-flow/components/BoardTaskTable.vue
apps/web/src/services/ops-flow/composables/use-task-ids-field.ts
apps/web/src/services/ops-flow/pages/TaskDetailPage.vue
apps/web/src/services/ops-flow/stores/task-content-form-store.ts
apps/web/src/services/ops-flow/task-fields-form/TaskFieldsForm.vue
apps/web/src/services/ops-flow/types/task-filters-type.ts
packages/mirinae/src/controls/context-menu/PContextMenu.vue

chore: merge develop to master

---

apps/web/src/lib/site-initializer/index.ts
apps/web/src/lib/site-initializer/mode-setting.ts
apps/web/src/services/configurator.ts
apps/web/src/store/display/display-store.ts

fix: fixed route bug

---

apps/web/src/services/dashboard-shared/core/actions/use-dashboard-clone-action.ts
apps/web/src/services/dashboard-shared/core/actions/use-dashboard-delete-action.ts
apps/web/src/services/dashboard-shared/core/actions/use-dashboard-folder-delete-action.ts
apps/web/src/services/dashboard-shared/dashboard-detail/DashboardDetailBody.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardCloneModal.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardDetailHeader.vue
apps/web/src/services/dashboards/helpers/dashboard-tree-data-helper.ts
apps/web/src/services/project/v2/components/ProjectDashboard.vue
apps/web/src/services/project/v2/components/ProjectDashboardChangeFolderModal.vue
apps/web/src/services/project/v2/components/ProjectDashboardCloneModal.vue
apps/web/src/services/project/v2/components/ProjectDashboardDeleteModal.vue
apps/web/src/services/project/v2/components/ProjectDashboardFolderFormModal.vue
apps/web/src/services/project/v2/components/ProjectDashboardNameEditModal.vue
apps/web/src/services/project/v2/components/ProjectDetailTab.vue
apps/web/src/services/project/v2/composables/queries/use-project-dashboard-folder-query.ts
apps/web/src/services/project/v2/composables/queries/use-project-dashboard-query.ts
apps/web/src/services/project/v2/pages/ProjectMainPage.vue
apps/web/src/services/project/v2/stores/project-page-modal-store.ts

feat(project-dashboard): create project-dashboard actions

---

apps/web/src/lib/config/global-config/feature-schema-manager.ts
apps/web/src/lib/config/global-config/types/type.ts
apps/web/src/services/iam/components/UserGroupManagementTabUsers.vue
apps/web/src/services/iam/configurator.ts
apps/web/src/services/ops-flow/configurator.ts

fix: fixed minor bug (global-config)

---

apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/TopBarToolset.vue
apps/web/src/lib/config/global-config/feature-schema-manager.ts
apps/web/src/lib/config/global-config/types/type.ts
apps/web/src/lib/site-initializer/index.ts
apps/web/src/lib/site-initializer/initTaskManagementTemplate.ts
apps/web/src/lib/site-initializer/merge-config.ts
apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEventRuleCard.vue
apps/web/src/services/asset-inventory/components/CloudServiceDetailTabs.vue
apps/web/src/services/auth/authenticator/index.ts
apps/web/src/services/cost-explorer/pages/BudgetDetailPage.vue
apps/web/src/services/my-page/components/NotificationAddForm.vue
apps/web/src/services/my-page/components/NotificationChannelList.vue
apps/web/src/services/my-page/composables/notification-item.ts
apps/web/src/services/ops-flow/configurator.ts
apps/web/src/services/ops-flow/task-management-templates/stores/use-task-management-template-store.ts

fix: fixed minor bug

---

apps/web/src/api-clients/cost-analysis/budget/schema/api-verbs/create.ts
apps/web/src/common/modules/user/UserSelectDropdown.vue
apps/web/src/services/cost-explorer/components/BudgetLastThreeMonthCostTrendBarChart.vue
apps/web/src/services/cost-explorer/components/BudgetMainList.vue
apps/web/src/services/cost-explorer/components/BudgetMainToolset.vue
apps/web/src/services/cost-explorer/stores/budget-detail-page-store.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: update budget minor changes

---

apps/web/src/services/service-account/components/ServiceAccountCredentialsForm.vue

Fixes a bug where the ‘secret type’ field didn't appear in the Service Account form.

fix: fix initiating service account `secret type` form

---

apps/web/src/services/cost-explorer/components/BudgetCreateStep2.vue
apps/web/src/services/cost-explorer/components/BudgetCreateStep3.vue
apps/web/src/services/cost-explorer/components/BudgetDetailBaseInformation.vue
apps/web/src/services/cost-explorer/components/BudgetLastThreeMonthCostTrendBarChart.vue
apps/web/src/services/cost-explorer/components/BudgetMainList.vue
apps/web/src/services/cost-explorer/components/BudgetMainToolset.vue
apps/web/src/services/cost-explorer/components/BudgetUsageTrendMonthlyChart.vue
apps/web/src/services/cost-explorer/components/BudgetUsageTrendMonthlyTable.vue
apps/web/src/services/cost-explorer/components/BudgetUsageTrendTotalTable.vue
apps/web/src/services/cost-explorer/components/CostAnalysisContent.vue
apps/web/src/services/cost-explorer/components/CostAnalysisFiltersPopper.vue
apps/web/src/services/cost-explorer/routes/routes.ts
apps/web/src/services/cost-explorer/stores/budget-detail-page-store.ts
apps/web/src/services/service-account/components/ServiceAccountBaseInformationForm.vue
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

chore(budget-qa): fix critical & major bugs

---

apps/web/src/services/cost-explorer/components/BudgetCreateStep2.vue
apps/web/src/services/cost-explorer/components/BudgetDetailBaseInformation.vue
apps/web/src/services/cost-explorer/routes/admin/routes.ts

chore(budget-qa): fix major & minor bugs

---

apps/web/src/App.vue
apps/web/src/_dev-tools/vue-query-console-debug.ts

Add Vue Query Console Debugger for Enhanced Developer Observability
This PR introduces a custom in-browser console-based debugging utility for inspecting the internal state of Vue Query.
- Global debug tool exposed as window.__QUERY_DEBUG__
- dump() prints a clean table of all queries, showing:
- appContext (admin or workspace)
- resourceIdentifier (dashboard/widget/etc.)
- contextKey (additional context namespace)
- params (serialized query params)
- observers, isActive, and more
- log() prints all queries in full detail (grouped)
- inspect(index) prints a specific query with raw query object
- Filtering support in dump():
- appContext(`string`), resourceIdentifier(`string`), activeOnly(`boolean`)
- isActive is calculated based on query result availability, usage, and enabled flag
- …

feat(console-query-debugger): create console query debugger

---

apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
apps/web/src/common/modules/widgets/_composables/use-data-table-cascade-update.ts
apps/web/src/common/modules/widgets/_composables/use-widget-data-table-list-query.ts

fix(dashboard-bug): solve dashboard widget field and data table issues

---

apps/web/src/services/cost-explorer/components/BudgetCreateStep1.vue
apps/web/src/services/cost-explorer/components/BudgetCreateStep2.vue
apps/web/src/services/cost-explorer/components/BudgetCreateStep3.vue
apps/web/src/services/cost-explorer/components/BudgetMainList.vue
apps/web/src/services/cost-explorer/components/BudgetMainToolset.vue
apps/web/src/services/cost-explorer/components/BudgetUsageTrendMonthly.vue
apps/web/src/services/cost-explorer/components/BudgetUsageTrendMonthlyChart.vue
apps/web/src/services/cost-explorer/components/BudgetUsageTrendMonthlyTable.vue
apps/web/src/services/cost-explorer/components/BudgetUsageTrendTotalTable.vue
apps/web/src/services/cost-explorer/components/CostAnalysisContent.vue
apps/web/src/services/cost-explorer/components/CostAnalysisFiltersPopper.vue

chore(budget-qa): fix major & minor bug

---

apps/web/src/schema/alert-manager/service/constants.ts
apps/web/src/schema/alert-manager/service/model.ts
apps/web/src/schema/alert-manager/service/type.ts
apps/web/src/services/alert-manager/v2/components/ServiceDetailHeader.vue
apps/web/src/services/alert-manager/v2/components/ServiceList.vue
apps/web/src/services/alert-manager/v2/stores/service-list-page-store.ts

Feat: update service landing page - pagination as service_healthy

---

apps/web/src/api-clients/cost-analysis/cost-report-config/composables/mutations/use-cost-report-update-mutation.ts
apps/web/src/services/cost-explorer/components/CostReportSettingsModal.vue
apps/web/src/services/cost-explorer/composables/queries/use-cost-report-config-query.ts

refactor: use VueQuery rather than SpaceConnector

---

apps/web/src/services/alert-manager/v2/components/ServiceDetailHeader.vue
apps/web/src/services/alert-manager/v2/components/ServiceList.vue
apps/web/src/services/alert-manager/v2/stores/service-list-page-store.ts

chore(service-pagination): fix bug about queryTag with pagination

---

.github/workflows/pull_request_random_reviewer_assignment.yaml

feat: merge to master

---

apps/web/src/services/service-account/components/ServiceAccountAttachedGeneralAccounts.vue

feat: add column at service account attached general accounts table

---

apps/web/src/services/cost-explorer/components/AdvancedSettingsSetAdjustmentsOverlay.vue
apps/web/src/services/cost-explorer/composables/queries/use-report-adjustment-policy-query.ts

fix: fix promise bug when save adjustments

---

apps/web/src/common/modules/popup/notice/modules/NoticePopupItem.vue
apps/web/src/services/cost-explorer/components/AdvancedSettingsAdjustmentsForm.vue
apps/web/src/services/cost-explorer/components/CostReportReportsTab.vue
apps/web/src/services/cost-explorer/stores/advanced-settings-page-store.ts

Hotfix cost report

---

apps/web/src/services/cost-explorer/components/AdvancedSettingsCostReportConfiguration.vue
apps/web/src/services/cost-explorer/components/AdvancedSettingsSetAdjustmentsOverlay.vue

fix: set min value from 0 to 1 (adjustment period)

---

apps/web/src/common/pages/CostReportDetailPage.vue
apps/web/src/services/cost-explorer/components/CostReportReportsTab.vue

hotfix: delete `is_confirmed` filter from cost report analyze API

---

apps/web/src/common/pages/CostReportDetailPage.vue

feat: show all provider in 'Details By Product' section

---

apps/web/src/services/alert-manager/v2/components/ServiceList.vue
apps/web/src/services/alert-manager/v2/components/ServiceListContent.vue
apps/web/src/services/alert-manager/v2/stores/service-list-page-store.ts

**Update pagination behavior for better UX:**
- Unhealthy services: fixed to 12 items per page
- Healthy services: now responsive — 6 or 8 items per page based on window size
- desktop size
- laptop size
This change addresses feedback that the previous fixed pagination (10/6 items) felt buggy or inconsistent.

feat(alert-service): enhance pagination logic in service page

---

apps/web/src/common/modules/navigations/top-bar/TopBar.vue
apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-integration/TopBarIntegration.vue
apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-notice/TopBarNotice.vue
apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-notifications/TopBarNotifications.vue
apps/web/src/common/modules/portals/TopNotification.vue

fix(top-bar): resolve menu display issue (missing store changes)

---

apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEventRuleActionAsset.vue
apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEventRuleCard.vue
apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEventRuleFormCard.vue
apps/web/src/services/cost-explorer/pages/admin/AdminAnomalyDetectionConfigurationPage.vue
packages/language-pack/ko.json

chore: fixed minor issue

---

apps/web/src/services/service-account/components/ServiceAccountAutoSyncForm.vue

- Problem: saved values for additional options in Trusted Account auto-sync settings were not displayed in the form due to missing initial value initialization.
- Solution: replaced redundant local state with direct usage of store-managed formState to ensure proper value initialization.

fix(trusted-account): solve trusted-account auto-sync additional option update bug

---

apps/web/src/common/modules/monitoring/MetricChart.vue

SSIA
- `state.chartData` is an array with at least one element in `MetricChart.vue`

fix(cloud-service-monitoring): solve wrong usage of data-loader in metric-chart

---

apps/web/src/services/iam/configurator.ts

feat: modify user group menu condition

---

apps/web/src/query/resource-query/reference-model/composables/use-reference-data-model.ts
apps/web/src/query/resource-query/reference-model/core/repository-registry.ts

- Fixed an issue where multiple `ReferenceRepository` instances were being created per resource, leading to redundant API calls.
- Introduced a **Repository Registry pattern** to ensure that each resource has a single shared `Repository` instance across the entire application.
- Added `repositoryRegistry.ts`, a centralized registry using a `Map` to store and reuse `ReferenceRepository` instances
- Replaced all `new ReferenceRepository(...)` instantiations with `getRepository(...)` calls
- This change ensures batching and deduplication happen at the global level
- Improves API efficiency, prevents redundant network requests, and maintains cache consistency
- Even when multiple components request the same resource at the same time, only **a single deduplicated API call** will be made
- …

feat(reference-data-model): refactor single pipeline for reference repository
