apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/ColorCodedHeatmap.vue

feat: edit minor

---

apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/modules/top-bar-search-dropdown/TopBarSearchDropdown.vue
apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue

fix: fix PTab emit bug

---

apps/web/src/services/dashboards/DashboardsLSB.vue

chore: solve dashboard-l-s-b bug

---

apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
apps/web/src/services/advanced/components/BookmarkManagementDetailTable.vue
apps/web/src/services/advanced/components/BookmarkManagementTable.vue
apps/web/src/services/alert-manager/components/AlertDetailNote.vue
apps/web/src/services/asset-inventory/components/MetricExplorerFiltersPopper.vue
apps/web/src/services/asset-inventory/components/MetricExplorerHeader.vue
apps/web/src/services/cost-explorer/components/BudgetCreateTargetSelect.vue
apps/web/src/services/cost-explorer/components/CostAnalysisFiltersPopper.vue
apps/web/src/services/cost-explorer/components/CostAnalysisQuerySection.vue
apps/web/src/services/info/components/NoticeWorkspaceDropdown.vue
apps/web/src/services/workspace-home/components/BookmarkBoard.vue
packages/mirinae/src/hooks/context-menu-controller/index.ts
packages/mirinae/src/hooks/context-menu-fixed-style/index.ts
packages/mirinae/src/inputs/context-menu/PContextMenu.vue
packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
packages/mirinae/src/navigation/breadcrumbs/modules/BreadcrumbsEllipsisItem.vue

fix(mirinae): let position set by floatingUI automatically

---

apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardLabelsButton.vue
apps/web/src/services/project/components/ProjectMainProjectCard.vue

chore: solve dashboard QAs

---

apps/web/src/services/project/components/ProjectMainDeleteModal.vue
packages/mirinae/src/feedbacks/modals/button-modal/PButtonModal.vue
packages/mirinae/src/hooks/context-menu-fixed-style/index.ts
packages/mirinae/src/inputs/dropdown/select-dropdown/components/dropdown-button.vue

fix: fix minor bugs - dropdown, cotext-menu-style, modal header style, etc.

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFiltersItem.vue
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json
packages/mirinae/src/navigation/tabs/tab/PTab.vue

chore(dashboard): small fix (data-table filter, `p-tab` translation)

---

apps/web/src/common/modules/widgets/_widget-fields/table-data-field/WidgetFieldTableDataField.vue
apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderShareModal.vue
apps/web/src/store/dashboard/dashboard-store.ts

fix: fix request query of folder/list

---

.github/workflows/dispatch_release.yaml

fix: remove unnecessary job (dispatch_release)

---

.github/workflows/dispatch_release.yaml

chore(release-workflow): small fix

---

packages/mirinae/src/navigation/tabs/tab/PTab.vue

chore: edit `p-tab` translation

---

apps/web/src/common/modules/project/ProjectSelectDropdown.vue
apps/web/src/services/asset-inventory/components/CollectorAdditionalRuleContent.vue
apps/web/src/services/asset-inventory/components/CollectorAdditionalRuleForm.vue
apps/web/src/services/asset-inventory/stores/collector-form-store.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: update new UI of additionalRuleForm

---

apps/web/src/services/project/components/ProjectMainProjectCard.vue
packages/mirinae/src/navigation/tabs/tab/components/FolderTab.vue

chore(project-main): solve translation computed bug

---

apps/web/src/services/asset-inventory/components/CollectorAdditionalRule.vue
apps/web/src/services/asset-inventory/components/CollectorAdditionalRuleContent.vue
apps/web/src/services/asset-inventory/components/CollectorAdditionalRuleForm.vue

fix: fix form bug of CollectorAdditionalRule

---

apps/web/src/services/asset-inventory/components/MetricExplorerQuerySection.vue
apps/web/src/services/cost-explorer/components/CostAnalysisQuerySection.vue
packages/mirinae/src/feedbacks/modals/button-modal/PButtonModal.vue
packages/mirinae/src/hooks/context-menu-fixed-style/index.ts

fix(mirinae): set max height as available height on context menu style hook

---

apps/web/src/common/pages/CostReportDetailPage.vue

feat: add Global Variable option to costReportDetail page

---

apps/web/src/schema/dashboard/_types/dashboard-type.ts
apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
apps/web/src/services/dashboards/stores/dashboard-page-control-store.ts

feat: apply search to dashboard main page

---

apps/web/src/services/asset-inventory/pages/CloudServiceDetailPage.vue

fix: fix infinite loop bug in cloud service page (default filter case)

---

apps/web/src/services/asset-inventory/components/CollectorAdditionalRule.vue
apps/web/src/services/asset-inventory/pages/CollectorDetailPage.vue

fix(collector-detail-page): fix edit validation bug

---

apps/web/src/services/asset-inventory/components/CloudServiceFilterSearchDropdown.vue
apps/web/src/services/asset-inventory/components/CloudServiceLSBDropdownMenuItem.vue

SSIA
ASIS: Click `done` then apply filter
TOBE: As soon as you select menu in dropdown, apply filter

fix: edit usage of cloud-service-lsb filter dropdown

---

packages/core-lib/src/space-connector/type.ts

feat(core-lib): add AnalyzeQuery type

---

apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue

chore(table-widget): add base opacity value (heatmap)  to handle zero value case

---

apps/web/src/schema/cost-analysis/unified-cost/api-verbs/analyze.ts
apps/web/src/schema/cost-analysis/unified-cost/api-verbs/get.ts
apps/web/src/schema/cost-analysis/unified-cost/api-verbs/list.ts
apps/web/src/schema/cost-analysis/unified-cost/api-verbs/stat.ts
apps/web/src/schema/cost-analysis/unified-cost/model.ts
apps/web/src/services/cost-explorer/types/unified-cost-type.ts
apps/web/src/services/workspace-home/components/CostSummary.vue
packages/core-lib/src/space-connector/type.ts

feat(workspace-home): change new api spec

---

apps/web/src/common/modules/navigations/top-bar/modules/top-bar-header/TopBarWorkspaces.vue
packages/mirinae/src/hooks/context-menu-controller/index.ts
packages/mirinae/src/hooks/context-menu-style/index.ts
packages/mirinae/src/hooks/index.ts
packages/mirinae/src/inputs/context-menu/PContextMenu.vue
packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.mdx
packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.stories.ts
packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
packages/mirinae/src/inputs/dropdown/select-dropdown/story-helper.ts

fix: add menuWidth prop to select dropdown to fix workspace top bar dropdown bug

---

apps/web/src/services/dashboards/components/dashboard-create/DashboardCreateStep1.vue
apps/web/src/services/dashboards/components/dashboard-create/DashboardCreateStep1SearchFilter.vue
apps/web/src/services/dashboards/components/dashboard-create/DashboardCreateStep2BundleCase.vue
apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTree.vue
apps/web/src/services/dashboards/components/dashboard-main/DashboardBundleCloneModal.vue
apps/web/src/services/dashboards/components/dashboard-main/DashboardBundleDeleteModal.vue
apps/web/src/services/dashboards/components/dashboard-main/DashboardBundleMoveModal.vue
apps/web/src/services/dashboards/components/dashboard-main/DashboardBundleShareModal.vue
apps/web/src/services/dashboards/pages/DashboardsMainPage.vue

AS IS
TO BE (**Delete "Existing Dashboard"**)

feat: delete start option from dashboard create page

---

apps/web/src/services/auth/components/SignInContainer.vue
apps/web/src/services/auth/pages/MultiFactorAuthPage.vue
apps/web/src/services/auth/routes/routes.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: apply changed design at mfa page (UI only)

---

packages/language-pack/en.json

fix typo and avoid using plural form in resource names

---

apps/web/src/services/iam/pages/AppMainPage.vue

https://cloudone-mz.slack.com/archives/C02U6M1L0LX/p1728264601548249

fix(app): fix wrong usage of tab

---

apps/web/src/services/my-page/components/UserAccountBaseInformation.vue
apps/web/src/services/my-page/components/UserAccountChangePassword.vue
apps/web/src/services/my-page/components/UserAccountModuleContainer.vue
apps/web/src/services/my-page/components/UserAccountMultiFactorAuth.vue
apps/web/src/services/my-page/components/UserAccountNotificationEmail.vue
apps/web/src/services/my-page/pages/UserAccountPage.vue

refactor: refactor user account page layout

---

apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
apps/web/src/services/project/components/ProjectDetailTabHeader.vue
apps/web/src/services/project/components/ProjectMainProjectCard.vue
apps/web/src/services/project/components/ProjectMainProjectGroupCard.vue
packages/mirinae/src/inputs/dropdown/select-dropdown/components/dropdown-button.vue

fix: set white background to dropdown icon button 

---

apps/web/src/services/cost-explorer/components/CostAnalysisChart.vue
apps/web/src/services/cost-explorer/components/CostAnalysisStackedColumnChart.vue

fix: modify skeleton area

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFiltersItem.vue

fix(data-table): temporarily remove contain operator

---

apps/web/src/schema/cost-analysis/cost-query-set/type.ts
apps/web/src/services/cost-explorer/components/CostAnalysisChart.vue
apps/web/src/services/cost-explorer/components/CostAnalysisDataTable.vue
apps/web/src/services/cost-explorer/components/CostAnalysisFiltersPopper.vue
apps/web/src/services/cost-explorer/components/CostAnalysisLSB.vue
apps/web/src/services/cost-explorer/components/CostAnalysisQuerySection.vue
apps/web/src/services/cost-explorer/constants/cost-explorer-constant.ts
apps/web/src/services/cost-explorer/pages/admin/AdminAdvancedSettingsCurrencyConverterPage.vue
apps/web/src/services/cost-explorer/stores/cost-analysis-page-store.ts

- Add unified Cost option to DataSource filter (lsb)
- Add Scope(workspace) filter to costAnalysis page in admin mode
- Apply unifiedCost api

feat: add Scope filter to costAnalysis page

---

apps/web/src/services/my-page/components/UserAccountMultiFactorAuth.vue
apps/web/src/services/my-page/components/UserAccountMultiFactorAuthFormModal.vue
apps/web/src/services/my-page/components/UserAccountMultiFactorAuthItems.vue
apps/web/src/services/my-page/components/UserAccountMultiFactorAuthModalEmailInfo.vue
apps/web/src/services/my-page/components/UserAccountMultiFactorAuthModalFolding.vue
apps/web/src/services/my-page/stores/multi-factor-authentication-store.ts

refactor: change to a state store usage approach

---

apps/web/src/common/modules/navigations/gnb/GNBNavigationRail.vue

fix: fix gnbNavigationRail selected case bug

---

apps/web/src/services/my-page/components/UserAccountMultiFactorAuth.vue
apps/web/src/services/my-page/components/UserAccountMultiFactorAuthFormModal.vue
apps/web/src/services/my-page/components/UserAccountMultiFactorAuthItems.vue
apps/web/src/services/my-page/components/UserAccountMultiFactorAuthModalEmailInfo.vue
apps/web/src/services/my-page/stores/multi-factor-auth-store.ts

feat: apply re-sync function

---

apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesMoreButton.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesV2.vue
apps/web/src/services/dashboards/components/legacy/DashboardManageVariableOverlay.vue
apps/web/src/services/dashboards/components/legacy/DashboardManageVariableTable.vue
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: markup 'Manage Variables' overlay

---

apps/web/src/services/cost-explorer/components/CostAnalysisContent.vue
apps/web/src/services/cost-explorer/components/CostReportSettingsModal.vue
apps/web/src/services/cost-explorer/pages/admin/AdminAdvancedSettingsCurrencyConverterPage.vue
apps/web/src/services/cost-explorer/stores/cost-analysis-page-store.ts

fix: fix unified cost qa issues

---

apps/web/src/services/dashboards/types/global-variable-type.ts

feat: create global-variable model 

---

apps/web/src/services/asset-inventory/components/MetricExplorerFiltersPopper.vue

fix: apply metric id filter to metric filter list

---

apps/web/src/common/pages/CostReportDetailPage.vue
apps/web/src/services/cost-explorer/components/CostReportMonthlyTotalAmountSummaryCard.vue
apps/web/src/services/cost-explorer/components/CostReportOverviewCostTrendCard.vue
apps/web/src/services/cost-explorer/components/CostReportOverviewCostTrendChart.vue

chore: fix cost report feedback

---

apps/web/src/lib/helper/multi-factor-auth-helper.ts
apps/web/src/services/my-page/components/UserAccountMultiFactorAuthFormModal.vue
apps/web/src/services/my-page/components/UserAccountMultiFactorAuthItems.vue
apps/web/src/services/my-page/components/UserAccountMultiFactorAuthModalMSInfo.vue
apps/web/src/services/my-page/stores/multi-factor-auth-store.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: apply API for MS qr code

---

apps/web/src/services/dashboards/types/global-variable-type.ts

chore: apply gv method

---

apps/web/src/common/modules/widgets/_components/WidgetFieldDropdownAndMax.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFiltersItem.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformForm.vue
apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
apps/web/src/common/modules/widgets/_widget-fields/advanced-format-rules/WidgetFieldAdvancedFormatRules.vue
apps/web/src/common/modules/widgets/_widget-fields/color-schema/WidgetFieldColorSchema.vue
apps/web/src/common/modules/widgets/_widget-fields/comparison/WidgetFieldComparison.vue
apps/web/src/common/modules/widgets/_widget-fields/data-field-heatmap-color/WidgetFieldDataFieldHeatmapColor.vue
apps/web/src/common/modules/widgets/_widget-fields/data-field/WidgetFieldDataField.vue
apps/web/src/common/modules/widgets/_widget-fields/date-format/WidgetFieldDateFormat.vue
apps/web/src/common/modules/widgets/_widget-fields/display-series-label/WidgetFieldDisplaySeriesLabel.vue
apps/web/src/common/modules/widgets/_widget-fields/granularity/WidgetFieldGranularity.vue
apps/web/src/common/modules/widgets/_widget-fields/group-by/WidgetFieldGroupBy.vue
apps/web/src/common/modules/widgets/_widget-fields/icon/WidgetFieldIcon.vue
apps/web/src/common/modules/widgets/_widget-fields/legend/WidgetFieldLegend.vue
apps/web/src/common/modules/widgets/_widget-fields/number-format/WidgetFieldNumberFormat.vue
apps/web/src/common/modules/widgets/_widget-fields/progress-bar/WidgetFieldProgressBar.vue
apps/web/src/common/modules/widgets/_widget-fields/table-data-field/WidgetFieldTableDataField.vue
apps/web/src/services/asset-inventory/components/ServiceAccountCredentialsForm.vue
packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.mdx
packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.stories.ts
packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
packages/mirinae/src/inputs/dropdown/select-dropdown/story-helper.ts

feat(p-select-dropdown): add 'block' props

---

apps/web/src/App.vue
apps/web/src/common/components/scoped-notification/ScopedNotification.vue
apps/web/src/common/modules/page-layouts/LayoutContainer.vue
apps/web/src/services/cost-explorer/components/CostAnalysisContent.vue
apps/web/src/services/cost-explorer/components/CostAnalysisHeader.vue
apps/web/src/services/cost-explorer/components/CostAnalysisLSB.vue
apps/web/src/services/cost-explorer/components/CostAnalysisQuerySection.vue
apps/web/src/services/cost-explorer/components/CostReportSettingsModal.vue
apps/web/src/services/cost-explorer/constants/cost-explorer-constant.ts
apps/web/src/services/cost-explorer/stores/cost-analysis-page-store.ts
apps/web/src/store/domain/domain-store.ts

fix: fix qa issues (unified-cost)

---

apps/web/src/services/dashboards/components/legacy/DashboardWidgetContainer.vue

fix: incorrect fetching of dashboardWidgetInfoList

---

apps/web/src/services/iam/components/UserManagementTabDetail.vue

chore: update modal visible type

---

apps/web/src/services/asset-inventory/components/ServiceAccountAttachedGeneralAccounts.vue
apps/web/src/services/asset-inventory/components/ServiceAccountAutoSync.vue
apps/web/src/services/asset-inventory/components/ServiceAccountBaseInformation.vue
apps/web/src/services/asset-inventory/components/ServiceAccountBaseInformationForm.vue
apps/web/src/services/asset-inventory/components/ServiceAccountCluster.vue
apps/web/src/services/asset-inventory/components/ServiceAccountCredentials.vue
apps/web/src/services/asset-inventory/pages/ServiceAccountDetailPage.vue
apps/web/src/services/asset-inventory/pages/admin/AdminCollectorDetailPage.vue

fix: fix side effect of PHeading & PHeadingLayout

---

packages/mirinae/src/layouts/overlay-layout/POverlayLayout.vue

Apply [managed](https://www.notion.so/z-index-b6f6541a8d7e4873959894da740c1cc9?pvs=4) z-index (`fixed` - 1030) to `POverlayLayout`.

chore(p-overlay-layout): apply managed z-index

---

apps/web/src/common/modules/navigations/gnb/GNBNavigationRail.vue
apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
apps/web/src/common/modules/widgets/types/widget-field-type.ts
apps/web/src/services/dashboards/helpers/widget-migration-helper.ts
apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts

feat: add `migrateAllWidgets` for legacy widget header

---

apps/web/src/services/cost-explorer/components/CostAnalysisDataTable.vue

fix: fix value formatting in cost analysis data table

---

apps/web/src/services/cost-explorer/components/CostAnalysisChart.vue
apps/web/src/services/cost-explorer/components/CostAnalysisDataTable.vue
apps/web/src/services/cost-explorer/components/CostAnalysisLSB.vue
apps/web/src/services/cost-explorer/components/CostReportUpcomingReportCard.vue
apps/web/src/services/cost-explorer/constants/cost-explorer-constant.ts
apps/web/src/services/cost-explorer/constants/managed-cost-analysis-query-sets.ts
apps/web/src/services/cost-explorer/pages/admin/AdminAdvancedSettingsCurrencyConverterPage.vue
apps/web/src/services/cost-explorer/routes/admin/routes.ts
apps/web/src/services/cost-explorer/stores/cost-analysis-page-store.ts

fix: fix unified-cost issues

---

apps/web/src/common/modules/widgets/_widget-fields/header/WidgetHeaderField.vue
apps/web/src/common/modules/widgets/_widget-fields/header/type.ts
apps/web/src/services/dashboards/helpers/widget-migration-helper.ts

fix(widget): fix widgetHeader bug

---

apps/web/src/services/cost-explorer/stores/cost-analysis-page-store.ts
apps/web/src/services/iam/components/UserManagementTab.vue
apps/web/src/services/iam/components/UserManagementTabDetail.vue
apps/web/src/services/iam/components/UserManagementTable.vue
apps/web/src/services/iam/types/user-type.ts

fix: fix group by list(unified-cost) & fix sort key value(userPage)

---

apps/web/src/common/components/scoped-notification/ScopedNotification.vue
apps/web/src/services/cost-explorer/components/CostAnalysisQuerySection.vue
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: add notification modal when checking the all workspace option

---

apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts
apps/web/src/common/modules/widgets/_widget-fields/display-annotation/WidgetFieldDisplayAnnotation.vue
apps/web/src/common/modules/widgets/_widget-fields/display-series-label/WidgetFieldDisplaySeriesLabel.vue
apps/web/src/common/modules/widgets/_widget-fields/header/WidgetHeaderField.vue

fix(widget-field): do not init when there's no value

---

apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesFormDynamic.vue
apps/web/src/services/dashboards/components/legacy/DashboardVariables.vue
apps/web/src/services/dashboards/constants/managed-dashboard-global-variables.ts
apps/web/src/services/dashboards/types/global-variable-type.ts

feat: create `MANAGED_DASHBOARD_GLOBAL_VARIABLES_SCHEMA`

---

apps/web/src/services/auth/authenticator/external/GOOGLE_OAUTH2/template/GOOGLE_OAUTH2.vue
apps/web/src/services/auth/authenticator/local/template/ID_PW.vue
apps/web/src/services/auth/components/CollapsibleContentsOTP.vue
apps/web/src/services/auth/pages/KeycloakPage.vue
apps/web/src/services/auth/pages/MultiFactorAuthPage.vue
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: apply page after OTP user login

---

apps/web/src/services/dashboards/components/legacy/DashboardManageVariableTable.vue
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: set managed GV to GV overlay table 

---

apps/web/src/services/cost-explorer/components/CostAnalysisDataTable.vue

fix: fix original data bug

---

apps/web/src/services/iam/components/UserManagementFormMultiFactorAuth.vue
apps/web/src/services/iam/components/UserManagementFormNotificationEmailForm.vue
apps/web/src/services/iam/constants/user-constant.ts

feat: apply mfa type toggle button at user edit modal

---

apps/web/src/services/my-page/components/UserAccountMultiFactorAuthItems.vue
packages/language-pack/en.json

fix: fixed toggle bug at my page

---

apps/web/src/services/asset-inventory/components/ServiceAccountBaseInformationForm.vue
apps/web/src/services/asset-inventory/types/service-account-page-type.ts

fix: fix serviceAccountBaseInformation validation bug

---

packages/mirinae/src/feedbacks/scoped-notification/PScopedNotification.mdx
packages/mirinae/src/feedbacks/scoped-notification/PScopedNotification.stories.ts
packages/mirinae/src/feedbacks/scoped-notification/PScopedNotification.vue
packages/mirinae/src/feedbacks/scoped-notification/story-helper.ts

feat: create `PScopedNotification`

---

apps/web/src/services/iam/components/UserManagementTabDetail.vue

feat: apply mfa type at user detail tab

---

apps/web/src/services/auth/pages/MultiFactorAuthPage.vue
apps/web/src/services/iam/components/UserManagementTabDetail.vue
apps/web/src/services/my-page/components/UserAccountMultiFactorAuthFormModal.vue
apps/web/src/services/my-page/components/UserAccountMultiFactorAuthModalFolding.vue

fix: fixed minor bug about mfa

---

apps/web/src/schema/dashboard/_types/dashboard-type.ts
apps/web/src/services/dashboards/components/dashboard-create/DashboardCreateStep1.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardDetailHeader.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardToolsetScope.vue
apps/web/src/services/dashboards/pages/DashboardCreatePage.vue
apps/web/src/services/dashboards/pages/DashboardDetailPage.vue
apps/web/src/services/dashboards/stores/dashboard-create-page-store.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: add 'dashboard type' for to admin mode

---

apps/web/src/services/dashboards/components/dashboard-detail/DashboardWidgetContainerV2.vue
apps/web/src/services/dashboards/helpers/widget-migration-helper.ts

fix: fix undefined error in widget-migration-helper

---

apps/web/src/services/dashboards/components/dashboard-detail/DashboardManageVariableOverlay.vue

refactor: toolbox + datatable -> PToolboxTable

---

apps/web/src/services/dashboards/components/dashboard-detail/DashboardToolsetScope.vue

chore: change to PScopedNotification

---

apps/web/src/services/dashboards/components/dashboard-detail/DashboardManageVariableOverlay.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesFormDynamic.vue
apps/web/src/services/dashboards/helpers/dashboard-global-variable-helper.ts
apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts

fix: get/set correct sourceFrom value / get managed GV from dashboard data 

---

apps/web/src/services/dashboards/components/dashboard-detail/DashboardManageVariableImportModal.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesMoreButton.vue
apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts

feat: apply real data to 'import GV' modal & more button

---

apps/web/src/schema/identity/user/model.ts
apps/web/src/services/iam/components/UserManagementFormModal.vue
apps/web/src/services/my-page/components/UserAccountMultiFactorAuth.vue
apps/web/src/services/my-page/components/UserAccountMultiFactorAuthFormModal.vue
apps/web/src/services/my-page/components/UserAccountMultiFactorAuthItems.vue
apps/web/src/services/my-page/stores/multi-factor-auth-store.ts
apps/web/src/store/modules/user/type.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

SSIA
https://mzdevs.atlassian.net/browse/MZ00003-1338

feat: apply changes to mfa method switch scenario

---

apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
apps/web/src/common/modules/widgets/_constants/widget-field-components-constant.ts
apps/web/src/common/modules/widgets/_widget-fields/data-aggregation-options/WidgetFieldDateAggregationOptions.vue
apps/web/src/common/modules/widgets/_widget-fields/data-aggregation-options/constant.ts
apps/web/src/common/modules/widgets/_widget-fields/data-aggregation-options/type.ts
apps/web/src/common/modules/widgets/_widget-fields/date-range/WidgetFieldDateRange.vue
apps/web/src/common/modules/widgets/types/widget-field-type.ts
apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat(date-aggregation-options): create date-aggregation-options field

---

apps/web/src/services/iam/components/UserManagementTable.vue
apps/web/src/services/my-page/components/UserAccountMultiFactorAuthItems.vue
apps/web/src/services/my-page/components/UserAccountMultiFactorAuthModalEmailInfo.vue
apps/web/src/services/my-page/components/UserAccountMultiFactorAuthModalMSInfo.vue

- https://mzdevs.atlassian.net/browse/MZ00003-1344
- https://mzdevs.atlassian.net/browse/MZ00003-1342
- https://mzdevs.atlassian.net/browse/MZ00003-1340
- https://mzdevs.atlassian.net/browse/MZ00003-1341

feat: apply qa issue (mobile, minor issue)

---

apps/web/src/common/modules/widgets/_composables/use-widget-date-range.ts
apps/web/src/common/modules/widgets/_widget-fields/date-range/WidgetFieldDateRange.vue
apps/web/src/common/modules/widgets/_widgets/table/Table.vue
apps/web/src/common/modules/widgets/_widgets/table/widget-config.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

- Edit `date-range` field design
- Create `useWidgetDateRange` hook

feat(widget-date-range): edit date-range field design & create date-range hook

---

packages/mirinae/src/feedbacks/modals/button-modal/PButtonModal.vue

chore: resolving the issue of text-indent not being applied on mobile

---

apps/web/src/common/modules/widgets/_widget-fields/date-range/WidgetFieldDateRange.vue
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

chore(widget-date-range-field): add invalid text

---

apps/web/src/common/modules/widgets/_composables/use-widget-date-range.ts
apps/web/src/services/dashboards/helpers/widget-migration-helper.ts

fix(widget-date-range): add date-range migration code & handle overflowing date case

---

apps/web/src/common/modules/widgets/_composables/use-widget-date-range.ts
apps/web/src/common/modules/widgets/_widget-fields/date-range/constant.ts

SSIA
- Remove `Last 2 Months`, `Last 2 Years` preset key

fix(widget-date-range): fix policy of date-range preset key

---

apps/web/src/common/modules/widgets/_helpers/widget-date-helper.ts
apps/web/src/common/modules/widgets/_widgets/table/Table.vue

feat(comparison): create `getPreviousDateRange` helper for comparison

---

apps/web/src/common/modules/widgets/_helpers/widget-date-helper.ts

chore(previous-date-range): small fix

---

apps/web/src/lib/menu/menu-info.ts
apps/web/src/services/advanced/components/BookmarkDetailContainer.vue
apps/web/src/services/advanced/pages/admin/AdminBookmarkPage.vue

SSIA
- menu 'new' badge
- header alignment
- context menu

fix: bug fixes registered in feedback (admin-bookmark & menu)

---

apps/web/src/common/modules/widgets/_helpers/widget-date-helper.ts

fix(previous-date-range): edit helper range issue

---

apps/web/src/common/modules/widgets/_helpers/widget-date-helper.ts
apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/ColorCodedHeatmap.vue
apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
apps/web/src/common/modules/widgets/_widgets/gauge/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
apps/web/src/common/modules/widgets/_widgets/geo-map/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
apps/web/src/common/modules/widgets/_widgets/heatmap/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
apps/web/src/common/modules/widgets/_widgets/line-chart/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
apps/web/src/common/modules/widgets/_widgets/number-card/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
apps/web/src/common/modules/widgets/_widgets/pie-chart/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
apps/web/src/common/modules/widgets/_widgets/treemap/widget-config.ts

feat: apply date range field to all widgets

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFilters.vue
apps/web/src/common/modules/widgets/_helpers/widget-date-helper.ts
apps/web/src/common/modules/widgets/_widget-fields/table-data-field/WidgetFieldTableDataField.vue

fix: remove dynamic date value (fixed)

---

apps/web/src/common/modules/widgets/_components/WidgetFieldDropdownAndMax.vue
apps/web/src/common/modules/widgets/_widget-fields/group-by/WidgetFieldGroupBy.vue
apps/web/src/common/modules/widgets/_widget-fields/table-data-field/WidgetFieldTableDataField.vue
apps/web/src/common/modules/widgets/_widget-fields/x-axis/WidgetFieldXAxis.vue
apps/web/src/common/modules/widgets/_widget-fields/y-axis/WidgetFieldYAxis.vue

fix: add invalid status to duplicated field dropdown

---

apps/web/src/common/modules/widgets/_widget-fields/date-range/WidgetFieldDateRange.vue
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

fix: add date-range info & edit style

---

apps/web/src/services/dashboards/helpers/widget-migration-helper.ts

chore: fix dashboard load bug

---

apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesFormDynamic.vue
apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts

feat: save `selectionType` to dynamic GV

---

apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
apps/web/src/services/dashboards/pages/DashboardDetailPage.vue

fix: fix gauge chart color

---

apps/web/src/common/modules/tags/tags-panel/modules/TagsOverlay.vue
apps/web/src/services/asset-inventory/components/CloudServiceHistoryDetailOverlay.vue

chore: change the z-index of the overlay applied to p-pane-layout

---

apps/web/src/services/info/components/NoticeDetail.vue
apps/web/src/services/info/pages/admin/AdminNoticeDetailPage.vue
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

New feature
Bug fixed
- before
- after

feat: create confirm modal for send email

---

apps/web/src/services/asset-inventory/components/CollectorCreateMultipleProviderForm.vue
apps/web/src/services/asset-inventory/components/CollectorCreateStep1SearchFilter.vue
apps/web/src/services/dashboards/components/dashboard-create/DashboardCreateStep1SearchFilter.vue
apps/web/src/services/iam/components/RoleUpdateFormAccess.vue
apps/web/src/services/my-page/components/NotificationAddSchedule.vue
apps/web/src/services/my-page/components/NotificationAddTopic.vue
apps/web/src/services/project/components/ProjectMainProjectGroupMoveModal.vue
packages/mirinae/src/inputs/checkbox-group/PCheckboxGroup.vue
packages/mirinae/src/inputs/radio-group/PRadioGroup.vue

feat (checkbox-group, radio group): changed gap

---

apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue

chore: new mark to date config field

---

apps/web/src/services/dashboards/helpers/widget-migration-helper.ts

chore: edit date-range migration

---

packages/mirinae/src/inputs/buttons/button/PButton.vue
packages/mirinae/src/inputs/buttons/icon-button/type.ts

feat: changed icon size (icon-button, button)

---

apps/web/src/services/dashboards/components/dashboard-detail/DashboardCloneModal.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardShareWithCodeModal.vue

fix: fix wrong usage of `migrateLegacyWidgetOptions`

---

apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesV2.vue
apps/web/src/services/dashboards/components/dashboard-main/DashboardBundleCloneModal.vue

feat: hide dashboard variables dropdown

---

apps/web/src/schema/dashboard/_types/dashboard-global-variable-type.ts
apps/web/src/services/dashboards/components/dashboard-create/DashboardCreateStep2BundleCase.vue
apps/web/src/services/dashboards/components/dashboard-create/DashboardCreateStep2SingleCase.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardCloneModal.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardManageVariableOverlay.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardShareWithCodeModal.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesV2.vue
apps/web/src/services/dashboards/constants/dashboard-vars-schema-preset.ts
apps/web/src/services/dashboards/types/shared-dashboard-type.ts
apps/web/src/store/dashboard/dashboard-store.ts

feat: set preset `vars_schema` when create dashboard

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformFormEvaluate.vue
apps/web/src/common/modules/widgets/types/widget-data-table-type.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: add 'else' field to EVAL

---

apps/web/src/services/dashboards/components/dashboard-detail/DashboardManageVariableOverlay.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesFormModal.vue

feat: delete vars when update/delete vars schema

---

apps/web/src/services/dashboards/components/dashboard-detail/DashboardToolsetScope.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesFormDynamic.vue
apps/web/src/services/dashboards/pages/DashboardDetailPage.vue
apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts

feat: set scoped workspace switching to admin dashboard

---

apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterNumberInput.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterTextInput.vue

feat(gv-filter): create global-variable-filter (number-any)

---

apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts

fix: set proper vars

---

apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterNumberSlider.vue
packages/mirinae/src/inputs/slider/PSlider.mdx
packages/mirinae/src/inputs/slider/PSlider.stories.ts
packages/mirinae/src/inputs/slider/PSlider.vue
packages/mirinae/src/inputs/slider/story-helper.ts

- Create `number-any-slider` gv-filter
- Add New Props to `PSlider` (`step`, `show-value`)

feat(gv-filter): create global-variable-filter (number-any-slider) & add new props to `PSlider`

---

apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterNumberInput.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterTextInput.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardManageVariableImportModal.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardManageVariableOverlay.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesFormModal.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesV2.vue
apps/web/src/services/dashboards/helpers/dashboard-global-variables-helper.ts

fix: apply styles directly due to intermittent scoped style issues

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformForm.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformFormEvaluate.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableGlobalVariableViewButton.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterReference.vue
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: create gv-preveiw-button & apply gv-view button (EVAL, QUERY) 

---

apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesFormManual.vue

chore: fix minor style issue

---

apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterReference.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardManageVariableOverlay.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesFormModal.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesMoreButton.vue

feat: update vars and vars of dashboard when update vars_schema

---

apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterEnum.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterReference.vue

fix: edit gv-filter select bug

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue

fix: fix data table bug (data-field-name)

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFilters.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFiltersItem.vue
apps/web/src/common/modules/widgets/_constants/data-table-constant.ts
apps/web/src/common/modules/widgets/types/widget-data-table-type.ts

feat: add dataTable gv filter

---

apps/web/src/schema/dashboard/_types/dashboard-type.ts
apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterEnum.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesMoreButton.vue

fix: store selected value from 'number-enum' dropdown as number

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFiltersItem.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterReference.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesMoreButton.vue

fix: edit reference gv filter default value issue

---

apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterEnum.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterReference.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesV2.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardWidgetContainerV2.vue
apps/web/src/services/dashboards/components/legacy/DashboardVariableDropdown.vue
apps/web/src/services/dashboards/components/legacy/DashboardVariables.vue

feat: delete `setVariablesInitMap` in gv dropdown

---

apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesFormManual.vue

chore: parseFloat number input when create vars_schema

---

apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterEnum.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterNumberInput.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterNumberSlider.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterReference.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterTextInput.vue

refactor: refactor number-any filter & refactor number-input floating menu

---

apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardRefreshDropdown.vue
apps/web/src/services/project/pages/ProjectDashboardPage.vue
apps/web/src/services/project/pages/ProjectSummaryPage.vue

fix: rerender project dashboard widgets when project is changed

---

apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesFormManual.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesMoreButton.vue

fix: fix click-show-more bug & enum form bug

---

apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterEnum.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterNumberInput.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterNumberSlider.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterReference.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterTextInput.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardManageVariableOverlay.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesFormModal.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesMoreButton.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesV2.vue
apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts

- Change timing of vars update (when dashboard is updated)
- Refactor initial watch and schema watch in gv filter component

refactor: refactor gv filter initial and schema watch 

---

apps/web/src/services/dashboards/components/dashboard-create/DashboardCreateStep1.vue
apps/web/src/services/dashboards/components/dashboard-create/DashboardCreateStep2BundleCase.vue
apps/web/src/services/dashboards/components/dashboard-create/DashboardCreateStep2SingleCase.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardManageVariableOverlay.vue
apps/web/src/services/dashboards/constants/dashboard-global-variable-preset.ts
apps/web/src/services/dashboards/constants/dashboard-vars-schema-preset.ts
apps/web/src/services/dashboards/helpers/dashboard-global-variables-helper.ts

feat: delete gv preset for admin

---

apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterEnum.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterReference.vue

fix: set optional code

---

apps/web/src/services/dashboards/DashboardsContainer.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardWidgetContainerV2.vue
apps/web/src/services/dashboards/stores/dashboard-settings-store.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat(dashboard): add 'Do not show again' checkbox to scoped noti

---

apps/web/src/services/dashboards/components/dashboard-detail/DashboardToolsetDateDropdown.vue

fix: fix style issue of dashboard date dropdown

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformForm.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformFormEvaluate.vue
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

chore: set 'Use Condition' toggle button to EVAL form

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardHeaderTitle.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardLabels.vue
packages/mirinae/src/inputs/input/text-input/PTextInput.vue

feat: apply height adjustment for 'sm size'

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardHeaderTitle.vue
apps/web/src/services/asset-inventory/components/CollectorCreateMultipleProviderForm.vue
apps/web/src/services/asset-inventory/components/CollectorCreateStep1SearchFilter.vue
apps/web/src/services/dashboards/components/dashboard-create/DashboardCreateStep1SearchFilter.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardLabels.vue
apps/web/src/services/iam/components/RoleUpdateFormAccess.vue
apps/web/src/services/my-page/components/NotificationAddSchedule.vue
apps/web/src/services/my-page/components/NotificationAddTopic.vue
apps/web/src/services/project/components/ProjectMainProjectGroupMoveModal.vue
packages/mirinae/src/inputs/buttons/button/PButton.vue
packages/mirinae/src/inputs/buttons/icon-button/type.ts
packages/mirinae/src/inputs/checkbox-group/PCheckboxGroup.vue
packages/mirinae/src/inputs/input/text-input/PTextInput.vue
packages/mirinae/src/inputs/radio-group/PRadioGroup.vue

feat: apply mirinae issue

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformFormEvaluate.vue

fix: fix EVAL apply button bug

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformForm.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformFormEvaluate.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardWidgetContainerV2.vue
packages/language-pack/en.json

fix: apply dashboard widgetLoading 

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformForm.vue
apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
apps/web/src/schema/dashboard/public-data-table/api-verbs/add.ts
apps/web/src/schema/dashboard/public-data-table/api-verbs/load.ts
apps/web/src/schema/dashboard/public-data-table/api-verbs/transform.ts
apps/web/src/schema/dashboard/public-data-table/api-verbs/update.ts

feat: set `vars` parameter to data-table/load,add,transform,update 

---

apps/web/src/common/modules/widgets/_widget-fields/number-format/WidgetFieldNumberFormat.vue
apps/web/src/services/landing/components/workspace-landing/LandingContainer.vue

feat: apply feedback(blackout, guide button)

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFilters.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFiltersItem.vue
apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
apps/web/src/common/modules/widgets/_constants/data-table-constant.ts
apps/web/src/common/modules/widgets/_helpers/global-variable-helper.ts
apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
apps/web/src/common/modules/widgets/types/widget-model.ts
apps/web/src/schema/dashboard/private-data-table/model.ts
apps/web/src/schema/dashboard/public-data-table/model.ts
apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterNumberInput.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterNumberSlider.vue

fix: add new DataTable field & apply DataTable load-failed state & fix gv filter bug

---

apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterNumberInput.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesFormManual.vue

fix: fix validation of GV number input

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

fix: apply dataTable unavailable state

---

apps/web/package.json

feat: raise max_old_space_size to 12288

---

apps/web/src/common/modules/widgets/_components/WidgetFrame.vue

chore: change position of period text in widget frame

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue

chore: edit unavailable data-table design

---

apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterNumberSlider.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterTextInput.vue

chore: periodtext

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep1.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardWidgetContainerV2.vue

chore: solve dashboard issues

---

apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesFormDynamic.vue

chore: disable values from until select data source

---

apps/web/src/services/dashboards/components/dashboard-detail/DashboardWidgetContainerV2.vue
apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts

fix: fix setting vars

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue

chore: delete timediff 3 years

---

apps/web/src/common/components/bookmark/BookmarkDeleteModal.vue
apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-favorite/TopBarFavorite.vue
apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-integration/TopBarIntegration.vue
apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-notice/TopBarNotice.vue
apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-notifications/TopBarNotifications.vue
apps/web/src/services/asset-inventory/components/CollectorAdditionalRuleForm.vue
apps/web/src/services/iam/components/UserManagementStatusModal.vue

chore: apply error modal message

---

apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
apps/web/src/services/dashboards/components/dashboard-detail/DashboardDetailHeader.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterEnum.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterNumberInput.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterNumberSlider.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterReference.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterTextInput.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardManageVariableOverlay.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardRefreshDropdown.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardToolsetDateDropdown.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesFormModal.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesMoreButton.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesV2.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardWidgetContainerV2.vue
apps/web/src/services/dashboards/components/legacy/DashboardVariables.vue
apps/web/src/services/dashboards/pages/DashboardDetailPage.vue
apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
apps/web/src/services/dashboards/stores/widget-form-store.ts
apps/web/src/services/project/pages/ProjectDashboardPage.vue

- Fix load-fetching with wrong `vars`
- Integrate loading (dashboard get, widget list in detail page)
- Change usage of refined widget list state

refactor: refactor dashboard store state management 

---

apps/web/src/lib/variable-models/_base/resource-variable-model.ts

feat(resource-variable-model): delete unused arguments

---

apps/web/src/services/cost-explorer/components/DataSourceManagementTabDataCollectionHistory.vue
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: apply quick state filter

---

apps/web/src/services/dashboards/components/dashboard-detail/DashboardWidgetContainerV2.vue

feat: apply widget intersection observer

---

apps/web/src/services/advanced/components/WorkspaceGroupTabWorkspace.vue
apps/web/src/services/iam/components/UserManagementTable.vue

fix: apply optional data

---

apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
apps/web/src/services/dashboards/components/dashboard-detail/DashboardDetailHeader.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterEnum.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterNumberInput.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterNumberSlider.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterReference.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardGlobalVariableFilterTextInput.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardManageVariableOverlay.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardRefreshDropdown.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardToolsetDateDropdown.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesFormModal.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesMoreButton.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesV2.vue
apps/web/src/services/dashboards/components/legacy/DashboardVariables.vue
apps/web/src/services/dashboards/pages/DashboardDetailPage.vue
apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
apps/web/src/services/dashboards/stores/widget-form-store.ts

refactor: refactor dashboard-detail-store dashboardInfo (state -> getters)

---

apps/web/src/schema/cost-analysis/data-source/api-verbs/sync.ts
apps/web/src/services/cost-explorer/components/DataSourceManagementTabDataCollectionHistory.vue
apps/web/src/services/cost-explorer/components/DataSourceManagementTabDataCollectionHistoryModal.vue
apps/web/src/services/cost-explorer/stores/data-sources-page-store.ts

feat: apply re-sync api

---

apps/web/src/services/landing/components/workspace-landing/LandingContainer.vue

fix: fix bug causing blackout on workspace landing

---

apps/web/src/services/advanced/components/WorkspaceTagManagementTabContents.vue
apps/web/src/services/advanced/components/WorkspacesCreateModal.vue
apps/web/src/services/iam/components/UserManagementTabTag.vue

fix: fix workspace & user tag update bug

---

apps/web/src/common/modules/navigations/gnb/GNBToolbox.vue
apps/web/src/common/modules/navigations/top-bar/modules/top-bar-header/TopBarWorkspaces.vue
apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-admin-toggle-button/TopBarAdminToggleButton.vue
apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-profile/TopBarProfile.vue
apps/web/src/lib/site-initializer/api-client.ts
apps/web/src/router/index.ts
apps/web/src/services/advanced/components/WorkspacesUserManagementTabContents.vue
apps/web/src/services/auth/pages/SignInPage.vue
apps/web/src/services/iam/pages/UserMainPage.vue
apps/web/src/services/landing/components/DomainLandingStartBanner.vue
apps/web/src/services/landing/components/workspace-landing/LandingContainer.vue
apps/web/src/services/landing/routes/routes.ts
apps/web/src/store/modules/user/actions.ts
apps/web/src/store/modules/user/mutations.ts

fix: fixed explore workspace route

---

apps/web/src/services/cost-explorer/components/DataSourceManagementTabDataCollectionHistory.vue
apps/web/src/services/cost-explorer/components/DataSourceManagementTable.vue
apps/web/src/services/cost-explorer/composables/data-source-handler.ts
apps/web/src/services/cost-explorer/constants/datasource-constant.ts
apps/web/src/services/cost-explorer/stores/data-sources-page-store.ts

- datasource table: state
- job table: progress

feat: add cols at datasource page tables

---

apps/web/src/services/dashboards/components/dashboard-create/DashboardCreateStep1.vue

chore: delete unused code

---

apps/web/src/schema/cost-analysis/job/api-verbs/cancel.ts
apps/web/src/services/cost-explorer/components/DataSourceManagementTabDataCollectionHistory.vue
apps/web/src/services/cost-explorer/components/DataSourceManagementTabDataCollectionHistoryModal.vue
apps/web/src/services/cost-explorer/stores/data-sources-page-store.ts
apps/web/src/services/iam/pages/UserMainPage.vue
apps/web/src/services/iam/store/user-page-store.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: apply cancel API

---

apps/web/src/services/dashboards/components/dashboard-detail/DashboardWidgetContainerV2.vue

chore: fix template type error

---

apps/web/src/common/modules/navigations/gnb/GNBToolbox.vue
apps/web/src/common/modules/navigations/top-bar/modules/top-bar-header/TopBarWorkspaces.vue
apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-admin-toggle-button/TopBarAdminToggleButton.vue
apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-profile/TopBarProfile.vue
apps/web/src/lib/site-initializer/api-client.ts
apps/web/src/router/index.ts
apps/web/src/services/advanced/components/WorkspacesUserManagementTabContents.vue
apps/web/src/services/auth/pages/SignInPage.vue
apps/web/src/services/iam/pages/UserMainPage.vue
apps/web/src/services/landing/components/DomainLandingStartBanner.vue
apps/web/src/services/landing/components/workspace-landing/LandingContainer.vue
apps/web/src/services/landing/routes/routes.ts
apps/web/src/store/modules/user/actions.ts
apps/web/src/store/modules/user/mutations.ts

* refactor: refactor landing page route
* refactor: refactor landing route redirection
* chore: fixed optional error
* fix: fixed explore workspace route
* fix: deleting remaining data
* fix: user permission application
* chore: remove console.log
---------
This PR merges the two branches to streamline QA and deployment processes.

fix: fixed explore workspace route (#5031)

---

apps/web/src/common/modules/navigations/top-bar/modules/top-bar-header/TopBarWorkspaces.vue
apps/web/src/services/landing/components/DomainLandingRecommendation.vue
apps/web/src/services/landing/components/DomainLandingStartBanner.vue
apps/web/src/services/workspace-home/components/WorkspaceInfo.vue

Remove admin privilege buttons from USER-scoped pages.

feat: remove admin role button at domain landing, workspace dropdown

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardHeaderTitle.vue
apps/web/src/common/modules/widgets/_widget-fields/advanced-format-rules/WidgetFieldAdvancedFormatRules.vue
apps/web/src/common/modules/widgets/_widget-fields/custom-table-column-width/WidgetFieldCustomTableColumnWidth.vue
apps/web/src/common/modules/widgets/_widget-fields/format-rules/WidgetFieldFormatRules.vue
apps/web/src/common/modules/widgets/_widget-fields/max/WidgetFieldMax.vue
apps/web/src/common/modules/widgets/_widget-fields/min/WidgetFieldMin.vue
apps/web/src/common/modules/widgets/_widget-fields/table-column-width/WidgetFieldTableColumnWidth.vue
apps/web/src/services/advanced/pages/admin/AdminDomainSettingsAutoDormancyConfigurationPage.vue
apps/web/src/services/alert-manager/components/EscalationPolicyFormRulesInput.vue
apps/web/src/services/asset-inventory/components/MetricExplorerQueryFormSidebar.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesFormManual.vue
apps/web/src/services/project/components/ProjectGroupMemberManagementModal.vue

feat: delete style custom of PTextInput

---

apps/web/src/services/advanced/components/WorkspaceGroupTabWorkspace.vue
apps/web/src/services/advanced/components/WorkspaceManagementTable.vue
apps/web/src/services/asset-inventory/components/MetricExplorerDataTable.vue
apps/web/src/services/cost-explorer/components/CostAnalysisDataTable.vue
packages/mirinae/src/data-display/tables/data-table/PDataTable.mdx
packages/mirinae/src/data-display/tables/data-table/PDataTable.stories.ts
packages/mirinae/src/data-display/tables/data-table/PDataTable.vue
packages/mirinae/src/data-display/tables/data-table/story-helper.ts
packages/mirinae/src/data-display/tables/toolbox-table/PToolboxTable.vue

- add datatable footer about total or average etc.
- add **slot** `foot` & `tf-col-format`
- add **props** `showFooter`

fix: add datatable spec (foot)

---

apps/web/src/services/cost-explorer/components/DataSourceManagementTabDataCollectionHistory.vue

fix: fix import path

---

apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesV2.vue
apps/web/src/services/dashboards/pages/DashboardDetailPage.vue

feat: apply new dashboard floating header UI

---

apps/web/src/services/asset-inventory/components/MetricExplorerDataTable.vue

fix: display '--' for empty date data

---

apps/web/src/common/modules/widgets/_constants/widget-field-components-constant.ts
apps/web/src/common/modules/widgets/_widget-fields/tooltip-number-format/WidgetFieldTooltipNumberFormat.vue
apps/web/src/common/modules/widgets/_widget-fields/tooltip-number-format/type.ts
apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
apps/web/src/common/modules/widgets/_widgets/line-chart/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
apps/web/src/common/modules/widgets/_widgets/pie-chart/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
apps/web/src/common/modules/widgets/_widgets/treemap/widget-config.ts
apps/web/src/common/modules/widgets/types/widget-field-type.ts
apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: add TooltipNumberFormat widget field

---

apps/web/src/services/asset-inventory/components/CollectorDetailSectionHeader.vue
apps/web/src/services/cost-explorer/components/DataSourceManagementModal.vue
apps/web/src/services/cost-explorer/components/DataSourceManagementTabLinkedAccount.vue
apps/web/src/services/info/components/NoticeForm.vue
apps/web/src/services/info/components/NoticeList.vue
apps/web/src/services/info/components/NoticeWorkspaceDropdown.vue
apps/web/src/services/landing/components/workspace-landing/landing-group-workspaces/LandingWorkspaceGroupTabGroupUser.vue

- [feat: apply PHeadingLayout](https://www.notion.so/Collector-edit-129bfa765996809dbf1cf4484d235caa?pvs=4)
- [fix: fixed text clipping on select dropdown button](https://www.notion.so/130bfa765996808f9e32c4619d2687e1?pvs=4)

fix: fixed feedback bug

---

apps/web/src/services/dashboards/components/dashboard-detail/DashboardWidgetContainerV2.vue

fix(dashboard-widget): solve widget clone bug

---

apps/web/src/services/cost-explorer/components/DataSourceManagementTabDataCollectionHistory.vue
apps/web/src/services/cost-explorer/components/DataSourceManagementTabDataCollectionHistoryModal.vue
apps/web/src/services/cost-explorer/pages/admin/AdminDataSourcePage.vue

- [Add a message when the status is Failure](https://mzdevs.atlassian.net/browse/MZ00003-1365)
- [Add action to the confirm button in the error check modal](https://mzdevs.atlassian.net/browse/MZ00003-1366)
- [Apply a date range setting in the re-sync modal](https://mzdevs.atlassian.net/browse/MZ00003-1367)
- [Apply animation to the in-progress icon](https://mzdevs.atlassian.net/browse/MZ00003-1368)
- [Disable the toggle button during API transmission in the re-sync modal](https://mzdevs.atlassian.net/browse/MZ00003-1372)
- [Remove the count of selected data in the data source table](https://mzdevs.atlassian.net/browse/MZ00003-1374)

feat: fixed minor qa issue

---

apps/web/src/services/cost-explorer/components/DataSourceManagementTabDataCollectionHistory.vue
apps/web/src/services/cost-explorer/components/DataSourceManagementTabDataCollectionHistoryModal.vue
apps/web/src/services/cost-explorer/stores/data-sources-page-store.ts

- SSIA
https://mzdevs.atlassian.net/browse/MZ00003-1373

fix: fix intermittent issue of job data disappearing from the data source

---

apps/web/src/common/modules/navigations/top-bar/constants/constant.ts
apps/web/src/store/admin/__tests__/domain-config-store.test.ts
apps/web/src/store/admin/domain-config-store.ts
apps/web/src/store/domain/constant.ts
apps/web/src/store/domain/domain-store.ts
apps/web/src/store/domain/type.ts
apps/web/src/store/preferences/preferences-store.ts

feat(domain-config): implement domain config store and related tests

---

apps/web/src/common/modules/widgets/_widget-fields/comparison/WidgetFieldComparison.vue
apps/web/src/common/modules/widgets/_widget-fields/comparison/type.ts
apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
apps/web/src/common/modules/widgets/_widgets/table/Table.vue
apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
apps/web/src/services/dashboards/helpers/widget-migration-helper.ts

feat(comparison): update widgets and migration helper

---

apps/web/src/services/cost-explorer/components/DataSourceManagementTabDataCollectionHistoryModal.vue
apps/web/src/services/workspace-home/components/WorkspaceInfo.vue

feat: change re-sync scenario

---

apps/web/src/services/dashboards/components/dashboard-detail/DashboardReorderSidebar.vue

fix: add widget layout updating trigger

---

packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

chore: update translation

---

apps/web/src/services/advanced/pages/admin/AdminDomainSettingsAutoDormancyConfigurationPage.vue
apps/web/src/services/cost-explorer/pages/admin/AdminAdvancedSettingsAnomalyDetectionConfigurationPage.vue
apps/web/src/store/domain/constant.ts

refactor: add `DOMAIN_CONFIG_TYPE` keys

---

apps/web/src/schema/cost-analysis/cost-report-config/api-verbs/update-recipients.ts
apps/web/src/schema/cost-analysis/cost-report-config/model.ts
apps/web/src/services/cost-explorer/components/CostReportRecipientsCard.vue

chore(cost-report): delete useless code & make `emails` field optional

---

packages/mirinae/src/feedbacks/modals/button-modal/PButtonModal.vue
packages/mirinae/src/feedbacks/modals/button-modal/story-helper.ts

feat(button-modal): add slot for customizable header title in modal

---

apps/web/src/services/cost-explorer/CostExplorerContainer.vue

fix: skip cost-query-set/list if workspaceId or dataSourceId is unchanged

---

apps/web/src/services/asset-inventory/components/ServiceAccountBaseInformationForm.vue
apps/web/src/services/asset-inventory/pages/ServiceAccountAddPage.vue
apps/web/src/services/asset-inventory/stores/service-account-page-store.ts

I removed the deduplication code that was causing bugs

fix(service-account): fix the bug of serviceAccoutCreateHandler

---

packages/language-pack/ja.json
packages/language-pack/ko.json

fix(cloud-service-detail): update filter description translations

---

apps/web/src/common/composables/data-source/use-cost-data-source-filter-menu-items.ts
apps/web/src/services/cost-explorer/components/CostAnalysisFiltersAddMoreButton.vue
apps/web/src/services/cost-explorer/components/CostAnalysisFiltersPopper.vue
apps/web/src/services/cost-explorer/components/CostAnalysisGroupBy.vue
apps/web/src/services/cost-explorer/stores/cost-analysis-page-store.ts

feat(cost-analysis): use hook to calculate groupby items directly

---

apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue
apps/web/src/services/asset-inventory/components/MetricExplorerLSBMetricTree.vue

- Changed the data filtering approach to resolve reactivity problems
- Previously: Filtered data directly from the store
- Now: Filter data immediately before rendering to LSB
- This change ensures proper reactive updates in the Vue component

fix: fix reactivity issue for real-time LSB updates

---

apps/web/src/common/composables/data-source/use-cost-data-source-filter-menu-items.ts
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesFormDynamic.vue

chore: change hook variable name

---

apps/web/src/common/modules/widgets/_constants/widget-field-components-constant.ts
apps/web/src/common/modules/widgets/_widget-fields/comparison/WidgetFieldComparison.vue
apps/web/src/common/modules/widgets/_widget-fields/comparison/type.ts
apps/web/src/common/modules/widgets/_widget-fields/tooltip-number-format/WidgetFieldTooltipNumberFormat.vue
apps/web/src/common/modules/widgets/_widget-fields/tooltip-number-format/type.ts
apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
apps/web/src/common/modules/widgets/_widgets/line-chart/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
apps/web/src/common/modules/widgets/_widgets/pie-chart/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/table/Table.vue
apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
apps/web/src/common/modules/widgets/_widgets/treemap/widget-config.ts
apps/web/src/common/modules/widgets/types/widget-field-type.ts
apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
apps/web/src/services/dashboards/helpers/widget-migration-helper.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: add TooltipNumberFormat widget field & update widgets and migration helper

---

apps/web/src/services/cost-explorer/components/CostAnalysisGroupBy.vue
apps/web/src/services/cost-explorer/components/CostAnalysisHeader.vue
apps/web/src/services/cost-explorer/components/CostAnalysisQuerySection.vue
apps/web/src/services/cost-explorer/stores/cost-analysis-page-store.ts

fix: listCostQueryList() after update querySet & calculate group-by items with appropriate types 

---

apps/web/src/services/asset-inventory/components/MetricExplorerLSBMetricTree.vue

- fix metric disappeared issue at user mode

fix: fix metric disappeared issue

---

apps/web/src/common/modules/workspace/WorkspaceSelectDropdown.vue
apps/web/src/services/advanced/components/WorkspaceGroupAddWorkspacesModal.vue
apps/web/src/services/advanced/components/WorkspaceGroupCreateModal.vue
apps/web/src/services/asset-inventory/components/CollectorAdditionalRuleForm.vue
apps/web/src/services/asset-inventory/components/WorkspaceDropdown.vue
apps/web/src/store/modules/user/actions.ts
packages/language-pack/ja.json
packages/language-pack/ko.json

fix: fixed minor feedback

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue

chore: typo error

---

apps/web/src/common/modules/navigations/top-bar/constants/constant.ts
apps/web/src/services/advanced/pages/admin/AdminDomainSettingsAutoDormancyConfigurationPage.vue
apps/web/src/services/cost-explorer/pages/admin/AdminAdvancedSettingsAnomalyDetectionConfigurationPage.vue
apps/web/src/store/admin/__tests__/domain-config-store.test.ts
apps/web/src/store/admin/domain-config-store.ts
apps/web/src/store/domain/__tests__/domain-config-store.test.ts
apps/web/src/store/domain/constant.ts
apps/web/src/store/domain/domain-config-store.ts
apps/web/src/store/domain/domain-store.ts
apps/web/src/store/domain/type.ts
apps/web/src/store/preferences/preferences-store.ts

feat(domain-config-store): update domain config store to use new keys and getters

---

apps/web/src/services/dashboards/components/dashboard-detail/DashboardWidgetContainerV2.vue

fix: update width of widgets when resize window

---

apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts
apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/ColorCodedHeatmap.vue
apps/web/src/common/modules/widgets/types/widget-display-type.ts
apps/web/src/services/dashboards/DashboardsLSB.vue

refactor: unify usage with `widgetEmit` type

---

apps/web/src/common/modules/workspace/WorkspaceSelectDropdown.vue
apps/web/src/schema/inventory/metric/model.ts
apps/web/src/services/advanced/components/WorkspaceGroupAddWorkspacesModal.vue
apps/web/src/services/advanced/components/WorkspaceGroupCreateModal.vue
apps/web/src/services/advanced/pages/admin/AdminDomainSettingsDomainInformationPage.vue
apps/web/src/services/asset-inventory/components/CollectorAdditionalRuleForm.vue
apps/web/src/services/asset-inventory/components/CollectorCreateMultipleProviderForm.vue
apps/web/src/services/asset-inventory/components/CollectorCreateStep1SearchFilter.vue
apps/web/src/services/asset-inventory/components/CollectorDetailSectionHeader.vue
apps/web/src/services/asset-inventory/components/MetricExplorerHeader.vue
apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue
apps/web/src/services/asset-inventory/components/MetricExplorerLSBMetric.vue
apps/web/src/services/asset-inventory/components/MetricExplorerLSBMetricTree.vue
apps/web/src/services/asset-inventory/components/WorkspaceDropdown.vue
apps/web/src/services/asset-inventory/pages/MetricExplorerDetailPage.vue
apps/web/src/services/asset-inventory/routes/admin/routes.ts
apps/web/src/services/cost-explorer/components/DataSourceManagementModal.vue
apps/web/src/services/cost-explorer/components/DataSourceManagementTabLinkedAccount.vue
apps/web/src/services/info/components/NoticeForm.vue
apps/web/src/services/info/components/NoticeList.vue
apps/web/src/services/info/components/NoticeWorkspaceDropdown.vue
apps/web/src/services/landing/components/workspace-landing/landing-group-workspaces/LandingWorkspaceGroupTabGroupUser.vue
apps/web/src/services/my-page/components/UserAccountBaseInformation.vue
apps/web/src/store/modules/user/actions.ts
apps/web/src/store/reference/all-reference-store.ts
apps/web/src/store/reference/metric-reference-store.ts

feat: apply additional feedback

---

apps/web/src/services/dashboards/components/dashboard-create/DashboardCreateStep1.vue

chore: update deprecated css

---

apps/web/src/services/dashboards/components/dashboard-create/DashboardCreateStep1.vue

chore: update deprecated css (#5108)

---

apps/web/src/common/modules/navigations/new-lsb/LSBRouterButton.vue
apps/web/src/common/modules/navigations/new-lsb/LSBRouterItem.vue
apps/web/src/common/modules/navigations/new-lsb/composables/use-lsb-router-item-state.ts

feat(navigation): enhance router item state with useRoute integration

---

apps/web/src/services/alert-manager-v2/AlertManagerContainer.vue
apps/web/src/services/alert-manager-v2/components/ServiceList.vue
apps/web/src/services/alert-manager-v2/pages/ServiceMainPage.vue
apps/web/src/services/alert-manager-v2/routes/routes.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: mark-up service main page

---

apps/web/src/services/asset-inventory/components/MetricExplorerDataTable.vue
apps/web/src/services/cost-explorer/components/CostAnalysisDataTable.vue

- Cost Analysis Page: resolve groupby sum display issue in data table tf-col-format slot
- Metric Analysis Page: fix Total cell of datatable footer bug

fix: fix datatable footer bug

---

apps/web/src/services/asset-inventory/components/MetricExplorerDataTable.vue
apps/web/src/services/cost-explorer/components/CostAnalysisDataTable.vue

* fix: resolve groupby sum display issue in data table tf-col-format slot
* fix: fix Total cell of datatable footer bug
---------
- resolve groupby sum display issue in data table of CostAnalysis Page
(after updated)
- fix Total cell of datatable footer bug of MetricAnalysis Page

fix: fix datatable footer bug (#5106)

---

apps/web/src/services/alert-manager-v2/components/ServiceList.vue

feat: apply click event at service item card and change card component

---

apps/web/src/services/alert-manager-v2/components/ServiceDetailHeader.vue
apps/web/src/services/alert-manager-v2/components/ServiceList.vue
apps/web/src/services/alert-manager-v2/pages/ServiceDetailPage.vue
apps/web/src/services/alert-manager-v2/routes/routes.ts
packages/language-pack/en.json

feat: create header at service detail page

---

apps/web/src/common/modules/navigations/new-lsb/LSBRouterButton.vue
apps/web/src/common/modules/navigations/new-lsb/LSBRouterItem.vue
apps/web/src/common/modules/navigations/new-lsb/composables/use-lsb-router-item-state.ts
apps/web/src/common/modules/navigations/new-lsb/type.ts

feat(navigation): add predicate support to router item state management

---

apps/web/src/services/cost-explorer/components/BudgetDetailSummaryChart.vue
apps/web/src/services/cost-explorer/components/BudgetDetailSummaryTable.vue

fix: calculate correct values based on amount planning

---

packages/mirinae/src/controls/datetime-picker/PDatetimePicker.mdx
packages/mirinae/src/controls/datetime-picker/PDatetimePicker.stories.ts
packages/mirinae/src/controls/datetime-picker/PDatetimePicker.vue
packages/mirinae/src/controls/datetime-picker/story-helper.ts
packages/mirinae/src/controls/datetime-picker/type.ts

feat(datetime-picker): add disabled state to datetime picker component

---

apps/web/src/services/alert-manager-v2/components/ServiceCreateStep1.vue
apps/web/src/services/alert-manager-v2/components/ServiceCreateStepContainer.vue
apps/web/src/services/alert-manager-v2/pages/ServiceCreatePage.vue
apps/web/src/services/alert-manager-v2/store/service-form-store.ts

refactor: apply componentization for common parts in the service creation page

---

apps/web/src/services/alert-manager-v2/components/ServiceCreateStep1.vue
apps/web/src/services/alert-manager-v2/components/ServiceCreateStep2.vue
apps/web/src/services/alert-manager-v2/components/ServiceCreateStep2CreatedWebhook.vue
apps/web/src/services/alert-manager-v2/components/ServiceCreateStep2SelectWebhookType.vue
apps/web/src/services/alert-manager-v2/components/ServiceCreateStep2WebhookForm.vue
apps/web/src/services/alert-manager-v2/components/ServiceCreateStepContainer.vue
apps/web/src/services/alert-manager-v2/pages/ServiceCreatePage.vue
apps/web/src/services/alert-manager-v2/store/service-form-store.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: markup for step 2 of the service creation page

---

packages/mirinae/src/controls/context-menu/PContextMenu.vue
packages/mirinae/src/controls/context-menu/context-menu-item/PContextMenuItem.vue
packages/mirinae/src/controls/datetime-picker/PDatetimePicker.mdx
packages/mirinae/src/controls/datetime-picker/PDatetimePicker.stories.ts
packages/mirinae/src/controls/datetime-picker/PDatetimePicker.vue
packages/mirinae/src/controls/datetime-picker/story-helper.ts
packages/mirinae/src/controls/datetime-picker/type.ts
packages/mirinae/src/controls/dropdown/select-dropdown/PSelectDropdown.mdx
packages/mirinae/src/controls/dropdown/select-dropdown/PSelectDropdown.stories.ts
packages/mirinae/src/controls/dropdown/select-dropdown/PSelectDropdown.vue
packages/mirinae/src/controls/dropdown/select-dropdown/components/dropdown-button.vue
packages/mirinae/src/controls/input/text-input/PTextInput.mdx
packages/mirinae/src/controls/input/text-input/PTextInput.stories.ts
packages/mirinae/src/controls/input/text-input/PTextInput.vue
packages/mirinae/src/controls/textarea/PTextarea.mdx
packages/mirinae/src/controls/textarea/PTextarea.stories.ts
packages/mirinae/src/controls/textarea/PTextarea.vue
packages/mirinae/src/controls/textarea/story-helper.ts

feat: improve disabled & readonly state of mirinae control components & add resize to textarea

---

apps/storybook/package.json
apps/storybook/postcss.config.cjs
apps/storybook/tailwind.config.cjs
apps/storybook/tailwind.config.js
package-lock.json

Regarding turbo repo, it is generally discouraged to specify dependencies using relative paths.

build: update dependency tree

---

apps/storybook/package.json
apps/storybook/postcss.config.js
apps/storybook/tailwind.config.cjs
apps/storybook/tailwind.config.js
package-lock.json

The build succeeds in storybook, but the Dynamic Import fails. so rolls back.

Revert "build: update dependency tree (#5131)"

---

apps/web/src/services/alert-manager-v2/components/ServiceCreateStep2.vue
apps/web/src/services/alert-manager-v2/components/ServiceCreateStep3.vue
apps/web/src/services/alert-manager-v2/components/ServiceCreateStep3SelectProtocol.vue
apps/web/src/services/alert-manager-v2/components/ServiceCreateStepContainer.vue
apps/web/src/services/alert-manager-v2/pages/ServiceCreatePage.vue
apps/web/src/services/alert-manager-v2/store/service-form-store.ts

feat: markup for step 3-1 of the service creation page

---

apps/web/src/services/alert-manager-v2/components/ServiceCreateStep1.vue
apps/web/src/services/alert-manager-v2/components/ServiceCreateStep2.vue
apps/web/src/services/alert-manager-v2/components/ServiceCreateStep2CreatedWebhook.vue
apps/web/src/services/alert-manager-v2/components/ServiceCreateStep2SelectWebhookType.vue
apps/web/src/services/alert-manager-v2/components/ServiceCreateStep2WebhookForm.vue
apps/web/src/services/alert-manager-v2/components/ServiceCreateStep3.vue
apps/web/src/services/alert-manager-v2/components/ServiceCreateStep3SelectProtocol.vue
apps/web/src/services/alert-manager-v2/components/ServiceCreateStepContainer.vue
apps/web/src/services/alert-manager-v2/components/ServiceDetailTabs.vue
apps/web/src/services/alert-manager-v2/components/ServiceDetailTabsWebhook.vue
apps/web/src/services/alert-manager-v2/components/ServiceDetailTabsWebhookDetailTabs.vue
apps/web/src/services/alert-manager-v2/composables/refined-table-data.ts
apps/web/src/services/alert-manager-v2/constants/alert-manager-constant.ts
apps/web/src/services/alert-manager-v2/pages/ServiceCreatePage.vue
apps/web/src/services/alert-manager-v2/store/service-create-form-store.ts
apps/web/src/services/alert-manager-v2/types/alert-manager-type.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: markup for the webhook tab of the service detail page

---

apps/web/src/services/alert-manager-v2/components/ServiceDetailTabs.vue
apps/web/src/services/alert-manager-v2/components/ServiceDetailTabsNotifications.vue
apps/web/src/services/alert-manager-v2/components/ServiceDetailTabsNotificationsDetailTabs.vue
apps/web/src/services/alert-manager-v2/constants/alert-manager-constant.ts

feat: markup for the notifications tab of the service detail page

---

packages/mirinae/src/layouts/overlay-layout/POverlayLayout.vue
packages/mirinae/src/layouts/overlay-layout/story-helper.ts

fix(p-overlay-layout): add sm size & edit md size

---

apps/web/src/common/modules/widgets/_widget-fields/advanced-format-rules/_WidgetFieldFormatRules.vue
apps/web/src/common/modules/widgets/_widget-fields/data-field/_WidgetFieldDataField.vue
apps/web/src/common/modules/widgets/types/widget-field-type.ts

feat(format-rules): create new integrated formatRules field (formatRules + advancedFormatRules)

---

.github/workflows/pull_request_code_warning.yml

ci: add github action 'Code Warning'

---

apps/web/src/services/alert-manager-v2/components/ServiceCreateStepContainer.vue
apps/web/src/services/alert-manager-v2/components/ServiceDetailHeader.vue
apps/web/src/services/alert-manager-v2/components/ServiceDetailTabsNotifications.vue
apps/web/src/services/alert-manager-v2/components/ServiceDetailTabsWebhook.vue
apps/web/src/services/alert-manager-v2/components/ServiceList.vue
apps/web/src/services/alert-manager-v2/pages/ServiceDetailNotificationsCreatePage.vue
apps/web/src/services/alert-manager-v2/pages/ServiceDetailWebhookCreatePage.vue
apps/web/src/services/alert-manager-v2/pages/ServiceMainPage.vue
apps/web/src/services/alert-manager-v2/routes/route-constant.ts
apps/web/src/services/alert-manager-v2/routes/routes.ts

- create webhook / notifications creation pag
- apply routing at buttons (TODO item)

feat: create webhook / notifications creation page and apply routing

---

apps/web/src/lib/access-control/page-access-helper.ts

This is the same as what 'sulmo' worked on previously.

fix: apply menu list by version at page access

---

apps/web/src/common/components/vertical-timeline/VerticalTimelineItem.vue

Added Console Component 
(Cannot load image.... ㅠㅠ)

feat: add vertical timeline item component with customizable styles

---

apps/web/src/App.vue
apps/web/src/services/auth/pages/SignInPage.vue
apps/web/src/services/auth/types/sign-in-page-type.ts
apps/web/src/services/landing/components/workspace-landing/landing-group-workspaces/LandingWorkspaceBoard.vue
apps/web/src/services/landing/pages/WorkspaceLandingPage.vue
apps/web/src/services/landing/store/landing-page-store.ts
apps/web/src/services/landing/type/workspace-landing-page-type.ts

feat(landing): add redirect path handling for workspace navigation and fix bug of routing logic 

---

apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-favorite/modules/TopBarFavoriteContextMenu.vue
apps/web/src/services/asset-inventory-v2/routes/route-constant.ts
apps/web/src/services/cost-explorer/components/CostAnalysisDataTable.vue
apps/web/src/services/workspace-home/components/UserConfigRecent.vue
apps/web/src/services/workspace-home/components/UserConfigStarred.vue
apps/web/src/services/workspace-home/components/UserConfigsItem.vue

feat: remove routes to CloudServiceDetail

---

apps/web/src/store/user/user-store.ts

chore: for vercel deployment

---

apps/web/src/common/modules/widgets/_components/_WidgetFieldDropdownAndMax.vue
apps/web/src/common/modules/widgets/_widget-fields/advanced-format-rules/_WidgetFieldFormatRules.vue
apps/web/src/common/modules/widgets/_widget-fields/advanced-format-rules/type.ts
apps/web/src/common/modules/widgets/_widget-fields/category-by/_WidgetFieldCategoryBy.vue
apps/web/src/common/modules/widgets/_widget-fields/category-by/type.ts
apps/web/src/common/modules/widgets/_widget-fields/data-field/type.ts
apps/web/src/common/modules/widgets/_widget-fields/stack-by/_WidgetFieldStackBy.vue
apps/web/src/common/modules/widgets/_widget-fields/stack-by/type.ts
apps/web/src/common/modules/widgets/_widget-fields/x-axis/_WidgetFieldXAxis.vue
apps/web/src/common/modules/widgets/_widget-fields/x-axis/type.ts
apps/web/src/common/modules/widgets/_widget-fields/y-axis/_WidgetFieldYAxis.vue
apps/web/src/common/modules/widgets/_widget-fields/y-axis/type.ts
apps/web/src/common/modules/widgets/types/widget-field-type.ts

fix(widget-field): refactor dropdown fields

---

apps/web/package.json
apps/web/src/lib/site-initializer/index.ts
apps/web/src/router/index.ts
apps/web/src/store/reference/all-reference-store.ts
apps/web/src/store/reference/cloud-service-type-reference-store.ts
apps/web/src/store/reference/cloue-service-query-set-reference-store.ts
apps/web/src/store/reference/collector-reference-store.ts
apps/web/src/store/reference/cost-data-source-reference-store.ts
apps/web/src/store/reference/escalation-policy-reference-store.ts
apps/web/src/store/reference/metric-reference-store.ts
apps/web/src/store/reference/namespace-reference-store.ts
apps/web/src/store/reference/plugin-reference-store.ts
apps/web/src/store/reference/project-group-reference-store.ts
apps/web/src/store/reference/project-reference-store.ts
apps/web/src/store/reference/protocol-reference-store.ts
apps/web/src/store/reference/provider-reference-store.ts
apps/web/src/store/reference/public-dashboard-reference-store.ts
apps/web/src/store/reference/public-folder-reference-store.ts
apps/web/src/store/reference/region-reference-store.ts
apps/web/src/store/reference/role-reference-store.ts
apps/web/src/store/reference/secret-reference-store.ts
apps/web/src/store/reference/service-account-reference-store.ts
apps/web/src/store/reference/trusted-account-reference-store.ts
apps/web/src/store/reference/user-reference-store.ts
apps/web/src/store/reference/webhook-reference-store.ts
apps/web/src/store/reference/workspace-group-reference-store.ts
apps/web/src/store/reference/workspace-reference-store.ts
apps/web/src/store/user/user-store.ts
package-lock.json

feat: delete vuex from package.json

---

apps/web/src/store/display/display-store.ts
apps/web/src/store/display/type.ts
apps/web/src/store/reset-pinia-store.ts
apps/web/src/store/user/type.ts
apps/web/src/store/user/user-store.ts

feat: delete unused file 'reset-pinia-store.ts' & use reactive getters 

---

packages/mirinae/src/controls/select-card/PSelectCard.mdx
packages/mirinae/src/controls/select-card/PSelectCard.stories.ts
packages/mirinae/src/controls/select-card/PSelectCard.vue
packages/mirinae/src/controls/select-card/story-helper.ts

feat: apply showSelectMarker at PSelectCard

---

apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/default-value-registry.ts
apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/validator-registry.ts
apps/web/src/common/modules/widgets/_widget-field-value-manager/type.ts
apps/web/src/common/modules/widgets/_widget-fields/color-schema/_WidgetFieldColorSchema.vue
apps/web/src/common/modules/widgets/_widget-fields/color-schema/type.ts
apps/web/src/common/modules/widgets/_widget-fields/comparison/_WidgetFieldComparison.vue
apps/web/src/common/modules/widgets/_widget-fields/custom-table-column-width/_WidgetFieldCustomTableColumnWidth.vue
apps/web/src/common/modules/widgets/_widget-fields/custom-table-column-width/type.ts

fix(widget-field): refactor widget fields (comparison, colorSchema, customTableColumnWidth)

---

apps/web/src/store/display/display-store.ts

chore: add missing code to the display store

---

apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/default-value-registry.ts
apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/validator-registry.ts
apps/web/src/common/modules/widgets/_widget-field-value-manager/type.ts
apps/web/src/common/modules/widgets/_widget-fields/display-series-label/_WidgetFieldDisplaySeriesLabel.vue
apps/web/src/common/modules/widgets/_widget-fields/granularity/_WidgetFieldGranularity.vue
apps/web/src/common/modules/widgets/_widget-fields/group-by/_WidgetFieldGroupBy.vue
apps/web/src/common/modules/widgets/_widget-fields/group-by/type.ts

fix(widget-field): refactor widget field (display-series-label, granularity, group-by)

---

apps/web/src/services/my-page/components/UserAccountMultiFactorAuthFormModal.vue

fix: fix MFA update logic

---

apps/web/src/services/cost-explorer/components/BudgetDetailNotificationsConditionSettingModal.vue
apps/web/src/services/cost-explorer/types/budget-form-type.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: markup for the redesigned notification settings modal

---

apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/default-value-registry.ts
apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/validator-registry.ts
apps/web/src/common/modules/widgets/_widget-field-value-manager/type.ts
apps/web/src/common/modules/widgets/_widget-fields/max/_WidgetFieldMax.vue
apps/web/src/common/modules/widgets/_widget-fields/min/_WidgetFieldMin.vue
apps/web/src/common/modules/widgets/_widget-fields/missing-value/_WidgetFieldMissingValue.vue
apps/web/src/common/modules/widgets/_widget-fields/missing-value/type.ts
apps/web/src/common/modules/widgets/_widget-fields/number-format/_WidgetFieldNumberFormat.vue

fix(widget-field): refactor widget field (min, max, missingValue, numberFormat)

---

packages/mirinae/src/controls/datetime-picker/PDatetimePicker.mdx
packages/mirinae/src/controls/datetime-picker/PDatetimePicker.stories.ts
packages/mirinae/src/controls/datetime-picker/PDatetimePicker.vue
packages/mirinae/src/controls/datetime-picker/story-helper.ts
packages/mirinae/src/controls/datetime-picker/type.ts
packages/mirinae/src/controls/dropdown/select-dropdown/components/dropdown-button.vue

feat(datetime-picker): add placeholder support to datetime picker component

---

apps/web/src/common/modules/project/ProjectSelectDropdown.vue

feat(project-select-dropdown): add readonly and block props for enhanced control

---

apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/default-value-registry.ts
apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/validator-registry.ts
apps/web/src/common/modules/widgets/_widget-field-value-manager/type.ts
apps/web/src/common/modules/widgets/_widget-fields/text-wrap/_WidgetFieldTextWrap.vue
apps/web/src/common/modules/widgets/_widget-fields/tooltip-number-format/_WidgetFieldTooltipNumberFormat.vue
apps/web/src/common/modules/widgets/_widget-fields/widget-height/_WidgetFieldWidgetHeight.vue
apps/web/src/common/modules/widgets/_widget-fields/widget-height/type.ts

fix(widget-field): refactor widget field (text-wrap, tooltip-number-format, widget-height)

---

apps/web/src/services/advanced/components/BookmarkManagementTable.vue
apps/web/src/services/advanced/components/WorkspaceManagementTable.vue
apps/web/src/services/iam/components/RoleManagementTable.vue
packages/mirinae/src/data-display/tables/data-table/PDataTable.vue

fix(data-table): invert selection logic for row enable/disable state

---

apps/web/src/common/modules/user/UserSelectDropdown.vue

feat: add user selection dropdown component with multi/single select options

---

apps/web/src/common/components/buttons/ActionMenuButton.vue

feat: add ActionMenuButton component for context menu actions

---

apps/web/src/services/dashboards/components/dashboard-detail/DashboardWidgetContainerV2.vue

fix: update width of widgets when resize window (#5093)

---

apps/web/src/common/components/vertical-timeline/VerticalTimelineItem.vue

feat(vertical-timeline): add non-collapsible slot to VerticalTimelineItem component

---

apps/web/src/common/modules/modals/notification-email-modal/NotificationEmailModal.vue
apps/web/src/lib/helper/verify-email-helper.ts
apps/web/src/router/integral-routes.ts
apps/web/src/services/alert-manager/routes/routes.ts
apps/web/src/services/asset-inventory/routes/routes.ts
apps/web/src/services/cost-explorer/routes/routes.ts
apps/web/src/services/iam/routes/routes.ts
apps/web/src/services/info/routes/routes.ts
apps/web/src/services/my-page/routes/routes.ts

feat: invoke user store within redirect callback

---

apps/web/src/services/asset-inventory/components/CloudServiceHistory.vue
apps/web/src/services/asset-inventory/components/CloudServiceToolbox.vue
apps/web/src/services/asset-inventory/components/CollectorHistoryJobTaskTable.vue
apps/web/src/services/asset-inventory/pages/admin/AdminCollectorHistoryPage.vue
apps/web/src/services/cost-explorer/components/BudgetMainToolbox.vue

fix: fix wrong import path for `KeyItemSet`

---

apps/web/src/common/modules/monitoring/Monitoring.vue
apps/web/src/services/alert-manager/components/AlertDashboardProjectSearchWidget.vue
apps/web/src/services/alert-manager/components/AlertDashboardTop5ProjectActivityWidget.vue
apps/web/src/services/asset-inventory/components/CloudServiceHistory.vue
apps/web/src/services/auth/authenticator/external/KEYCLOAK_OIDC/template/KEYCLOAK_OIDC.vue
apps/web/src/services/auth/components/SignInRightContainer.vue
apps/web/src/services/auth/pages/PasswordPage.vue
apps/web/src/services/iam/components/UserManagementStatusModal.vue

refactor: replace `vm` with alternate hooks or functions

---

apps/web/src/services/alert-manager/components/AlertDetailNote.vue

chore: edit button icon

---

apps/web/src/common/composables/timezone-date/__tests__/index.test.ts
apps/web/src/common/composables/timezone-date/index.ts
apps/web/src/common/modules/project/ProjectLinkButton.vue

feat(timezone-date): add composable for handling timezone-aware dates & add ProjectLinkButton

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformFormEvaluate.vue
apps/web/src/common/modules/widgets/_constants/data-table-constant.ts
apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
apps/web/src/common/modules/widgets/types/widget-data-table-type.ts
apps/web/src/common/modules/widgets/types/widget-model.ts

feat(data-table): add new transform data tables type

---

apps/web/src/schema/inventory-v2/namespace-group/api-verbs/create.ts
apps/web/src/schema/inventory-v2/namespace-group/api-verbs/delete.ts
apps/web/src/schema/inventory-v2/namespace-group/api-verbs/get.ts
apps/web/src/schema/inventory-v2/namespace-group/api-verbs/list.ts
apps/web/src/schema/inventory-v2/namespace-group/api-verbs/update.ts
apps/web/src/schema/inventory-v2/namespace-group/model.ts
apps/web/src/schema/inventory-v2/namespace/api-verbs/create.ts
apps/web/src/schema/inventory-v2/namespace/api-verbs/delete.ts
apps/web/src/schema/inventory-v2/namespace/api-verbs/get.ts
apps/web/src/schema/inventory-v2/namespace/api-verbs/list.ts
apps/web/src/schema/inventory-v2/namespace/api-verbs/update.ts
apps/web/src/schema/inventory-v2/namespace/constant.ts
apps/web/src/schema/inventory-v2/namespace/model.ts
apps/web/src/schema/inventory-v2/namespace/type.ts

feat(inventory-v2): create inventory-v2 namespace & namespaceGroup api schema

---

apps/web/src/store/display/display-store.ts

chore: delete console.debug in display-store

---

apps/web/src/services/alert-manager-v2/components/ServiceCreateStep1.vue
apps/web/src/services/alert-manager-v2/components/ServiceCreateStepContainer.vue
apps/web/src/services/alert-manager-v2/stores/service-create-form-store.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: apply service create API

---

packages/mirinae/src/data-display/avatar/PAvatar.vue
packages/mirinae/src/data-display/avatar/type.ts

feat: create xs size at PAvatar

---

packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: delete unused languages

---

apps/web/src/services/alert-manager-v2/components/ServiceList.vue

feat: apply service list API

---

apps/web/src/lib/menu/menu-architecture.ts

chore: fixed merge bug

---

apps/web/src/services/alert-manager-v2/components/AlertDetailInfoTable.vue
apps/web/src/services/alert-manager-v2/components/AlertsManagementTable.vue
apps/web/src/services/alert-manager-v2/components/ServiceDetailTabsNotifications.vue
apps/web/src/services/alert-manager-v2/components/ServiceDetailTabsOverviewStatusTable.vue
apps/web/src/services/alert-manager-v2/components/ServiceDetailTabsWebhook.vue
apps/web/src/services/alert-manager-v2/constants/alert-manager-constant.ts
apps/web/src/services/alert-manager-v2/pages/ServiceDetailPage.vue
apps/web/src/services/alert-manager-v2/stores/service-detail-page-store.ts
apps/web/src/services/alert-manager-v2/types/alert-manager-type.ts

feat: apply service get API

---

apps/web/src/schema/inventory-v2/namespace-group/api-verbs/list.ts
apps/web/src/schema/inventory-v2/namespace-group/model.ts
apps/web/src/services/asset-inventory/stores/metric-explorer-l-s-b-store.ts

feat(metric-explorer-l-s-b-store): create lsb store to replace using reference-data

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformForm.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformFormAddLabels.vue
apps/web/src/common/modules/widgets/types/widget-data-table-type.ts
apps/web/src/common/modules/widgets/types/widget-model.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: markup 'Add Labels'

---

apps/web/src/services/dashboards/helpers/widget-migration-helper.ts

fix: fix optional

---

apps/web/src/services/asset-inventory/components/CollectorAdditionalRuleForm.vue
apps/web/src/store/reference/region-reference-store.ts

refactor(asset-inventory): update region fetch logic for v2 support

---

apps/web/src/services/alert-manager-v2/components/ServiceDetailDeleteModal.vue

fix: bug fix for fetch timing

---

apps/web/src/common/modules/navigations/gnb/GNBNavigationRail.vue

fix: fix admin NavigationRail for no costDataSource

---

apps/web/src/common/modules/navigations/lsb/modules/LSBCollapsibleMenuItem.vue
apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue
apps/web/src/services/asset-inventory/components/MetricExplorerLSBMetric.vue
apps/web/src/services/asset-inventory/stores/metric-explorer-l-s-b-store.ts

- Apply new namespaceGroup/namespace/metric (inventory v2) to MetricExplorerLSB.
- Replace `reference-store(namespace, metric, metric-example)` to realtime fetching.
- Apply `namespaceGroup`

feat(metric-explorer-l-s-b): renewal metric lsb (inventory v2)

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformDataTableDropdown.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformPivotForm.vue
apps/web/src/common/modules/widgets/_constants/data-table-constant.ts
apps/web/src/common/modules/widgets/types/widget-data-table-type.ts
apps/web/src/common/modules/widgets/types/widget-model.ts

feat(transform-data-table): improved transform-data-table structure

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformPivotForm.vue
apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/default-value-registry.ts
apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/validator-registry.ts
apps/web/src/common/modules/widgets/_widget-field-value-manager/index.ts
apps/web/src/common/modules/widgets/_widget-field-value-manager/type.ts
apps/web/src/common/modules/widgets/_widget-fields/date-range/_WidgetFieldDateRange.vue
apps/web/src/common/modules/widgets/_widget-fields/date-range/constant.ts
apps/web/src/common/modules/widgets/_widget-fields/date-range/helper.ts
apps/web/src/common/modules/widgets/types/widget-field-type.ts

fix(date-range): refactor date-range widget field

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
apps/web/src/common/modules/widgets/types/widget-data-table-type.ts

fix: fix transform reset button

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformAddLabels.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformConcatenate.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformEvaluate.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformJoin.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformPivotForm.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformQuery.vue
apps/web/src/common/modules/widgets/_constants/widget-field-constant.ts
apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/validator-registry.ts
apps/web/src/common/modules/widgets/_widget-fields/advanced-format-rules/WidgetFieldFormatRules.vue
apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/widget-config.ts
apps/web/src/common/modules/widgets/types/widget-data-table-type.ts

refactor: validate form in each transform components

---

apps/web/src/common/modules/widgets/_widgets/table/Table.vue
apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue

fix: apply new widget-form flow to Table widget

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue

feat(data-table-timediff): add timediff data_name field

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformAddLabels.vue
apps/web/src/common/modules/widgets/types/widget-frame-type.ts

fix: fix validation bug in ADD_LABELS

---

apps/web/src/common/modules/widgets/_components/WidgetFieldDropdownAndMax.vue
apps/web/src/common/modules/widgets/_components/__WidgetFieldDropdownAndMax.vue
apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/default-value-registry.ts
apps/web/src/common/modules/widgets/_widget-fields/category-by/WidgetFieldCategoryBy.vue
apps/web/src/common/modules/widgets/_widget-fields/category-by/__WidgetFieldCategoryBy.vue
apps/web/src/common/modules/widgets/_widget-fields/stack-by/WidgetFieldStackBy.vue
apps/web/src/common/modules/widgets/_widget-fields/stack-by/__WidgetFieldStackBy.vue
apps/web/src/common/modules/widgets/_widget-fields/x-axis/WidgetFieldXAxis.vue
apps/web/src/common/modules/widgets/_widget-fields/x-axis/__WidgetFieldXAxis.vue
apps/web/src/common/modules/widgets/_widget-fields/y-axis/WidgetFieldYAxis.vue
apps/web/src/common/modules/widgets/_widget-fields/y-axis/__WidgetFieldYAxis.vue

fix(field-default-value): update widget-field default value setter

---

apps/web/src/services/alert-manager-v2/components/AlertCreateModal.vue
apps/web/src/services/alert-manager-v2/components/AlertsManagementTable.vue
apps/web/src/services/alert-manager-v2/constants/alert-management-table-constant.ts
apps/web/src/services/alert-manager-v2/constants/alert-manager-constant.ts
apps/web/src/services/alert-manager-v2/pages/AlertsMainPage.vue
apps/web/src/services/alert-manager-v2/stores/alert-page-store.ts
apps/web/src/services/alert-manager-v2/types/alert-manager-type.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: create alert creation modal

---

apps/web/src/services/alert-manager-v2/components/AlertsManagementTable.vue
apps/web/src/services/alert-manager-v2/constants/alert-management-table-constant.ts

- apply custom fields / excel download / search

feat: apply toolbox function

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue

chore(data-table): fix timediff bug

---

apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
apps/web/src/common/modules/widgets/_widget-fields/advanced-format-rules/WidgetFieldFormatRules.vue
apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
apps/web/src/common/modules/widgets/_widgets/gauge/widget-config.ts

refactor(gauge): use new `widget/load-sum` api

---

apps/web/src/common/modules/widgets/_widget-fields/display-annotation/WidgetFieldDisplayAnnotation.vue
apps/web/src/common/modules/widgets/_widget-fields/legend/WidgetFieldLegend.vue
apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
apps/web/src/common/modules/widgets/_widgets/pie-chart/widget-config.ts

refactor(pie): use new `widget/load` api

---

apps/web/src/lib/excel-export/constant.ts
apps/web/src/services/alert-manager-v2/components/ServiceDetailTabs.vue
apps/web/src/services/alert-manager-v2/components/ServiceDetailTabsWebhook.vue
apps/web/src/services/alert-manager-v2/constants/webhook-table-constant.ts

feat: apply webhook api at service detail webhook tab

---

apps/web/src/services/alert-manager-v2/components/ServiceDetailTabs.vue
apps/web/src/services/alert-manager-v2/components/ServiceDetailTabsWebhook.vue
apps/web/src/services/alert-manager-v2/stores/service-detail-page-store.ts

fix: fixed emit value type error and changed minor issue

---

apps/web/src/schema/alert-manager/webhook/type.ts
apps/web/src/services/alert-manager-v2/components/ServiceCreateStep2.vue
apps/web/src/services/alert-manager-v2/components/WebhookCreateForm.vue
apps/web/src/services/alert-manager-v2/components/WebhookCreateTypeSelector.vue
apps/web/src/services/alert-manager-v2/pages/ServiceCreatePage.vue
apps/web/src/services/alert-manager-v2/stores/service-create-form-store.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: apply webhook create API

---

apps/web/src/services/alert-manager-v2/components/ServiceDetailTabsNotifications.vue
apps/web/src/services/alert-manager-v2/components/ServiceDetailTabsSettingsEscalationPolicy.vue
apps/web/src/services/alert-manager-v2/components/ServiceDetailTabsWebhook.vue
apps/web/src/services/alert-manager-v2/constants/escalation-policy-table-constant.ts
apps/web/src/services/alert-manager-v2/constants/notification-table-constant.ts

- webhook / notification (service channel) / escalation poiicy

feat: apply API at service detail tabs

---

apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue

refactor(treemap): use new `widget/load` api

---

apps/web/src/lib/access-control/page-access-helper.ts
apps/web/src/lib/access-control/redirect-route-helper.ts
apps/web/src/lib/menu/menu-architecture.ts
apps/web/src/lib/site-initializer/index.ts
apps/web/src/router/alert-manager-v1-admin-routes.ts
apps/web/src/router/alert-manager-v1-integral-routes.ts
apps/web/src/router/alert-manager-v1-workspace-routes.ts
apps/web/src/router/workspace-routes.ts
apps/web/src/services/iam/helpers/role-page-access-menu-list.ts
apps/web/src/store/display/display-store.ts
apps/web/src/store/reference/collector-reference-store.ts
apps/web/src/store/reference/region-reference-store.ts

fix: change service version range(alert v2, inventory v1)

---

apps/web/src/common/modules/favorites/favorite-button/store/favorite-store.ts
apps/web/src/services/asset-inventory-v1/components/CloudServiceLSB.vue
apps/web/src/services/asset-inventory-v1/components/SecurityLSB.vue
apps/web/src/services/asset-inventory/components/CloudServiceLSB.vue

refactor: remove unused favorite store references

---

apps/web/src/services/alert-manager-v2/components/NotificationsCreateForm.vue
apps/web/src/services/alert-manager-v2/components/NotificationsCreateTypeSelector.vue
apps/web/src/services/alert-manager-v2/components/ServiceDetailTabs.vue
apps/web/src/services/alert-manager-v2/components/ServiceDetailTabsNotifications.vue
apps/web/src/services/alert-manager-v2/components/ServiceDetailTabsWebhook.vue
apps/web/src/services/alert-manager-v2/components/WebhookCreateForm.vue
apps/web/src/services/alert-manager-v2/pages/ServiceDetailNotificationsCreatePage.vue
apps/web/src/services/alert-manager-v2/stores/service-create-form-store.ts
apps/web/src/services/alert-manager-v2/types/alert-manager-type.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: apply API at notification create page

---

apps/web/src/common/components/editor/TextEditorViewer.vue

fix(editor): update markdown processing to use sanitized HTML output

---

apps/web/src/services/alert-manager-v2/components/ServiceList.vue
apps/web/src/services/alert-manager-v2/constants/alert-management-table-constant.ts
apps/web/src/services/alert-manager-v2/constants/escalation-policy-table-constant.ts
apps/web/src/services/alert-manager-v2/constants/notification-table-constant.ts
apps/web/src/services/alert-manager-v2/constants/webhook-table-constant.ts
apps/web/src/services/alert-manager-v2/pages/ServiceCreatePage.vue
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: apply detail (search, escalation policy, style)

---

apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/default-value-registry.ts
apps/web/src/common/modules/widgets/_widget-fields/data-field/type.ts

fix(widget-field): add allSelected options spec to dataField

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformEvaluate.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformValueMapping.vue

chore: edit minor design

---

apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/default-value-registry.ts
apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/validator-registry.ts
apps/web/src/common/modules/widgets/_widget-field-value-manager/index.ts
apps/web/src/common/modules/widgets/_widget-field-value-manager/type.ts
apps/web/src/common/modules/widgets/_widget-fields/header/WidgetHeaderField.vue

fix: fix widget apply bug (header -> widgetHeader)

---

apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue

fix: fix apply button

---

apps/web/src/services/auth/authenticator/index.ts

feat(authenticator): initialize task management template on sign-in

---

apps/web/src/schema/alert-manager/service-channel/type.ts
apps/web/src/schema/alert-manager/user-channel/type.ts
apps/web/src/schema/alert-manager/user-group-channel/type.ts
apps/web/src/services/alert-manager-v2/components/NotificationsCreateForm.vue
apps/web/src/services/alert-manager-v2/components/ServiceList.vue

chore: fixed minor issue

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformValueMapping.vue
apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/default-value-registry.ts
apps/web/src/common/modules/widgets/_widget-fields/group-by/WidgetFieldGroupBy.vue
apps/web/src/common/modules/widgets/_widgets/gauge/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue

refactor(geomap): use new widget/load api

---

packages/mirinae/src/data-display/tooltips/PTooltip.pcss

chore: changed tooltip inner white space style

---

apps/web/src/services/ops-flow/components/TaskContentBaseForm.vue
apps/web/src/services/ops-flow/task-fields-configuration/stores/use-task-field-metadata-store.ts
apps/web/src/services/ops-flow/task-management-templates/stores/use-task-management-template-store.ts

fix(task-management): remove unnecessary scope from sharedConfigStore call

---

apps/web/src/services/ops-flow/components/BoardTaskFilters.vue
apps/web/src/services/ops-flow/task-management-templates/stores/use-task-management-template-store.ts

fix(task-management): remove unnecessary parameter from sharedConfigStore set method

---

apps/web/src/services/dashboards/pages/DashboardsMainPage.vue

feat: show `shared` dashboards to workspace members

---

apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
apps/web/src/common/modules/widgets/_helpers/widget-load-helper.ts
apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue

feat: set `sort` and `page` to widgets

---

apps/web/package.json
apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
apps/web/src/common/modules/widgets/_constants/widget-constant.ts
apps/web/src/common/modules/widgets/_helpers/widget-data-table-helper.ts
apps/web/src/common/modules/widgets/_widget-fields/custom-table-column-width/WidgetFieldCustomTableColumnWidth.vue
apps/web/src/common/modules/widgets/_widget-fields/table-column-width/WidgetFieldTableColumnWidth.vue
apps/web/src/common/modules/widgets/_widgets/table/Table.vue
apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
apps/web/src/common/modules/widgets/types/widget-display-type.ts
apps/web/src/main.ts
apps/web/src/schema/dashboard/private-widget/api-verbs/load-sum.ts
apps/web/src/schema/dashboard/public-widget/api-verbs/load-sum.ts
package-lock.json

- Applied Vue Query!! (only table-widget)
- Refactor widget load (table)

feat(table-widget & vue-query): refactor table widget & apply vue query

---

apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue

feat(clusteredColumnChart): set `sort` and `page` to widgets

---

apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/line-chart/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/widget-config.ts

chore: add allSelected: true to dataField of XY charts & fix Geomap validation

---

apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
apps/web/src/common/modules/widgets/_widgets/heatmap/widget-config.ts

fix(heatmap): refactor heatmap widget & apply vue query

---

apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/ColorCodedHeatmap.vue
apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue

fix(color-coded-table-heatmap): refactor color-coded-table-heatmap widget & apply vue query

---

apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
apps/web/src/common/modules/widgets/_composables/use-widget-options-complex-validation.ts
apps/web/src/common/modules/widgets/_widget-field-value-manager/index.ts
apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/ColorCodedHeatmap.vue
apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
apps/web/src/common/modules/widgets/_widgets/table/Table.vue

chore(table-widget): fix table reactivity bug & fix other issues

---

apps/web/src/services/asset-inventory/AssetInventoryLSB.vue
packages/core-lib/src/space-connector/service-api.ts

fix(space-connector): ensure authorization header is set only if token exists

---

apps/web/src/schema/dashboard/public-folder/model.ts
apps/web/src/services/dashboards/DashboardsLSB.vue
apps/web/src/services/dashboards/components/dashboard-create/DashboardCreateStep2BundleCase.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardCloneModal.vue
apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTree.vue
apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
apps/web/src/services/dashboards/stores/dashboard-page-control-store.ts
apps/web/src/services/project/pages/ProjectDetailTabPage.vue

feat: update dashboard for workspace members 

---

apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue

fix(line-chart): apply vue query to line chart

---

apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue

chore: add missing query code

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue

refactor: refactor DT transform

---

apps/web/src/services/asset-inventory-v1/components/CloudServiceLSB.vue
apps/web/src/services/asset-inventory-v1/constants/cloud-service-constant.ts
apps/web/src/services/asset-inventory-v1/pages/CloudServicePage.vue
apps/web/src/services/asset-inventory-v1/stores/cloud-service-page-store.ts

feat(cloud-service): add unidentified provider handling

---

apps/web/src/common/components/schedule-setting-form/ScheduleSettingForm.vue
apps/web/src/services/alert-manager-v2/components/ServiceCreateStep2.vue
apps/web/src/services/alert-manager-v2/components/ServiceCreateStep3.vue
apps/web/src/services/alert-manager-v2/components/ServiceDetailTabsNotificationsDetailTabs.vue
apps/web/src/services/alert-manager-v2/components/ServiceList.vue
apps/web/src/services/alert-manager-v2/stores/service-create-form-store.ts

feat: fix schedule setting bug, update create page

---

apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/table/widget-config.ts

fix(stacked-column-chart): apply vue query

---

apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue

fix(clustered-column-chart): apply vue query

---

apps/web/src/schema/dashboard/public-folder/model.ts
apps/web/src/services/dashboards/DashboardsLSB.vue
apps/web/src/services/dashboards/components/dashboard-create/DashboardCreateStep2BundleCase.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardCloneModal.vue
apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTree.vue
apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
apps/web/src/services/dashboards/stores/dashboard-page-control-store.ts
apps/web/src/services/project/pages/ProjectDetailTabPage.vue

feat: update dashboard for workspace members  (#5302)

---

apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue

fix(vue-query): apply vue query to widgets (pie-chart, stacked-horizontal-bar-chart, treemap)

---

apps/web/src/common/modules/widgets/_store/widget-generate-store.ts

- Create dataTableReferenceMap getter
- Create data-table cascade update actions

feat(data-table-reference-update): apply cascade update to reference update of data tables

---

apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
apps/web/src/common/modules/widgets/_widgets/table/Table.vue
apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue

fix(vue-query): apply vue query to widget (gauge, geo-map, number-card, treemap)

---

apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
apps/web/src/common/modules/widgets/_widget-fields/data-field/WidgetFieldDataField.vue
apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
apps/web/src/schema/dashboard/private-data-table/model.ts
apps/web/src/schema/dashboard/public-data-table/model.ts

fix(pivot-keys): apply data-table pivot_keys to preview table and data-field

---

apps/web/src/common/modules/widgets/_widget-fields/comparison/WidgetFieldComparison.vue
apps/web/src/common/modules/widgets/_widget-fields/custom-table-column-width/WidgetFieldCustomTableColumnWidth.vue
apps/web/src/common/modules/widgets/_widget-fields/data-field/WidgetFieldDataField.vue
apps/web/src/common/modules/widgets/_widget-fields/format-rules/WidgetFieldFormatRules.vue
apps/web/src/common/modules/widgets/_widget-fields/sub-total/WidgetFieldSubTotal.vue

chore: remove TODO annotation

---

apps/web/src/common/modules/widgets/_widget-fields/data-field-heatmap-color/WidgetFieldDataFieldHeatmapColor.vue
apps/web/src/common/modules/widgets/_widget-fields/group-by/WidgetFieldGroupBy.vue
apps/web/src/common/modules/widgets/_widget-fields/x-axis/WidgetFieldXAxis.vue
apps/web/src/common/modules/widgets/_widget-fields/y-axis/WidgetFieldYAxis.vue

chore: fix import error & delete comments

---

apps/web/src/common/modules/widgets/_constants/widget-field-components-constant.ts
apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/default-value-registry.ts
apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/validator-registry.ts
apps/web/src/common/modules/widgets/_widget-field-value-manager/type.ts
apps/web/src/common/modules/widgets/_widget-fields/comparison/WidgetFieldComparison.vue
apps/web/src/common/modules/widgets/_widget-fields/custom-table-column-width/WidgetFieldCustomTableColumnWidth.vue
apps/web/src/common/modules/widgets/_widget-fields/custom-table-column-width/type.ts
apps/web/src/common/modules/widgets/_widget-fields/table-column-comparison/WidgetFieldTableColumnComparison.vue
apps/web/src/common/modules/widgets/_widget-fields/table-column-comparison/type.ts
apps/web/src/common/modules/widgets/_widgets/table/Table.vue
apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
apps/web/src/common/modules/widgets/_widgets/table/widget-config.ts
apps/web/src/common/modules/widgets/types/widget-field-type.ts

feat(table-column-comparison): create table column comparison field & apply new comparison field to table widget

---

apps/web/src/schema/opsflow/comment/model.ts
apps/web/src/schema/opsflow/comment/type.ts
apps/web/src/schema/opsflow/event/model.ts
apps/web/src/schema/opsflow/event/type.ts
apps/web/src/services/ops-flow/components/BoardTaskComment.vue

feat(comment): add optional fields and mention source to comment model

---

apps/web/src/services/dashboards/DashboardsLSB.vue

fix: fix dashboard LSB

---

apps/web/src/schema/opsflow/event/type.ts
apps/web/src/services/ops-flow/components/PackageDeleteModal.vue
apps/web/src/services/ops-flow/components/PackagePanel.vue
apps/web/src/services/ops-flow/components/TaskCategoryDeleteModal.vue
apps/web/src/services/ops-flow/components/TaskCategoryPanel.vue
apps/web/src/services/ops-flow/components/TaskContentBaseForm.vue
apps/web/src/services/ops-flow/components/TaskDeleteModal.vue
apps/web/src/services/ops-flow/components/TaskProgressEventView.vue
apps/web/src/services/ops-flow/components/TaskProgressTab.vue
apps/web/src/services/ops-flow/components/TaskStatusTree.vue
apps/web/src/services/ops-flow/composables/use-task-status-field.ts
apps/web/src/services/ops-flow/constants/task-status-label-constant.ts
apps/web/src/services/ops-flow/pages/BoardPage.vue
apps/web/src/services/ops-flow/pages/OpsFlowLandingPage.vue
apps/web/src/services/ops-flow/pages/TaskCreatePage.vue
apps/web/src/services/ops-flow/pages/TaskDetailPage.vue
apps/web/src/services/ops-flow/stores/admin/task-category-store.ts
apps/web/src/services/ops-flow/stores/admin/task-management-page-store.ts
apps/web/src/services/ops-flow/stores/task-content-form-store.ts
apps/web/src/services/ops-flow/stores/task-detail-page-store.ts
apps/web/src/services/ops-flow/task-fields-form/field-templates/DateTaskField.vue
apps/web/src/services/ops-flow/task-fields-form/field-templates/ProjectTaskField.vue
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat(event): add status change interface and update event handling logic

---

apps/web/src/services/project/components/ProjectDetailTabHeader.vue
apps/web/src/services/project/pages/ProjectDetailTabPage.vue

fix: fix project tab sync

---

apps/web/src/lib/site-initializer/api-client.ts
apps/web/src/lib/variable-models/managed-model-config/base-managed-model-config.ts
apps/web/src/lib/variable-models/managed-model/resource-model/service-variable-model.ts
apps/web/src/services/alert-manager-v2/components/AlertCreateModal.vue
apps/web/src/services/alert-manager-v2/components/AlertsManagementTable.vue
apps/web/src/services/alert-manager-v2/components/ServiceCreateStep1.vue
apps/web/src/services/alert-manager-v2/components/ServiceDetailEditModal.vue
apps/web/src/services/alert-manager-v2/stores/service-detail-page-store.ts
apps/web/src/services/dashboards/stores/all-reference-type-info-store.ts
apps/web/src/store/reference/all-reference-store.ts
apps/web/src/store/reference/service-reference-store.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: apply service to reference store

---

apps/web/src/common/modules/favorites/favorite-button/FavoriteButton.vue
apps/web/src/common/modules/favorites/favorite-button/store/favorite-store.ts
apps/web/src/common/modules/favorites/favorite-button/type.ts
apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-favorite/modules/TopBarFavoriteContextMenu.vue
apps/web/src/lib/helper/config-data-helper.ts
apps/web/src/lib/menu/menu-info.ts
apps/web/src/services/alert-manager-v2/components/ServiceDetailTabsWebhookDeleteModal.vue
apps/web/src/services/alert-manager-v2/pages/ServiceDetailPage.vue
apps/web/src/services/alert-manager-v2/routes/routes.ts
apps/web/src/services/alert-manager-v2/stores/alert-page-store.ts
apps/web/src/services/workspace-home/components/UserConfigStarred.vue
apps/web/src/services/workspace-home/components/UserConfigsItem.vue
apps/web/src/services/workspace-home/constants/workspace-home-constant.ts

feat: apply favorite, breadcrumbs

---

apps/web/src/services/iam/components/SelectChannelCard.vue
apps/web/src/services/iam/components/UserGroupChannelSetInputForm.vue
apps/web/src/services/iam/components/UserGroupManagementHeader.vue
apps/web/src/services/iam/components/UserGroupManagementTab.vue
apps/web/src/services/iam/components/UserGroupManagementTabNotificationChannel.vue
apps/web/src/services/iam/components/UserGroupManagementTabUsers.vue
apps/web/src/services/iam/components/UserManagementTable.vue
apps/web/src/services/iam/pages/UserGroupMainPage.vue

Feat: add ReadWriteAccess of UserGroupPage and update minor revision

---

apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/TopBarToolset.vue
apps/web/src/services/alert-manager-v2/components/AlertsManagementTable.vue
apps/web/src/services/cost-explorer/pages/BudgetDetailPage.vue

chore: apply RWD at alert main page, remove topbar/budget notification

---

apps/web/src/services/alert-manager/components/AlertDetailInfoTableDescription.vue
apps/web/src/services/alert-manager/components/AlertDetailNote.vue
apps/web/src/services/alert-manager/components/AlertDetailSummary.vue
apps/web/src/services/alert-manager/components/AlertsDetailHeader.vue
apps/web/src/services/alert-manager/components/ServiceDetailHeader.vue
apps/web/src/services/alert-manager/components/ServiceDetailMemberModal.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsNotifications.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsSettings.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEscalationPolicy.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsWebhook.vue
apps/web/src/services/alert-manager/pages/AlertsMainPage.vue
apps/web/src/services/alert-manager/pages/ServiceMainPage.vue

feat: apply read write access

---

apps/web/src/services/alert-manager/components/AlertCreateModal.vue
apps/web/src/services/alert-manager/components/AlertDetailEditModal.vue
apps/web/src/services/alert-manager/components/NotificationsCreateForm.vue
apps/web/src/services/alert-manager/components/ServiceCreateStep1.vue
apps/web/src/services/alert-manager/components/ServiceCreateStep3.vue
apps/web/src/services/alert-manager/components/ServiceDetailEditModal.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsNotificationsUpdateModal.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEscalationPolicy.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEscalationPolicyFormModal.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsWebhookUpdateModal.vue
apps/web/src/services/alert-manager/components/WebhookCreateForm.vue
apps/web/src/services/alert-manager/pages/ServiceDetailNotificationsCreatePage.vue

feat: apply create forward channel API, validation check

---

apps/web/src/lib/excel-export/constant.ts
apps/web/src/schema/alert-manager/alert/api-verbs/list.ts
apps/web/src/schema/alert-manager/alert/api-verbs/update.ts
apps/web/src/schema/alert-manager/alert/constants.ts
apps/web/src/schema/alert-manager/alert/model.ts
apps/web/src/schema/alert-manager/alert/type.ts
apps/web/src/services/alert-manager/components/AlertDetailInfoTable.vue
apps/web/src/services/alert-manager/components/AlertDetailNote.vue
apps/web/src/services/alert-manager/components/AlertDetailSummary.vue
apps/web/src/services/alert-manager/components/AlertsDetailHeader.vue
apps/web/src/services/alert-manager/components/AlertsManagementTable.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsNotifications.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsOverviewStatusTable.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEscalationPolicy.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEscalationPolicyFormModal.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsWebhook.vue
apps/web/src/services/alert-manager/composables/alert-table-data.ts
apps/web/src/services/alert-manager/constants/alert-table-constant.ts
apps/web/src/services/alert-manager/constants/escalation-policy-table-constant.ts
apps/web/src/services/alert-manager/constants/notification-table-constant.ts
apps/web/src/services/alert-manager/constants/service-table-constant.ts
apps/web/src/services/alert-manager/pages/AlertsDetailPage.vue
apps/web/src/services/alert-manager/types/alert-manager-type.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: apply excel download function, apply alert note API

---

apps/web/src/common/modules/widgets/_helpers/global-variable-helper.ts
apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/ColorCodedHeatmap.vue
apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
apps/web/src/common/modules/widgets/_widgets/table/Table.vue
apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue

fix(widget-query-key): serialize query-key (vars)

---

apps/web/src/schema/alert-manager/user-group-channel/api-verbs/create.ts
apps/web/src/schema/alert-manager/user-group-channel/api-verbs/update.ts
apps/web/src/schema/alert-manager/user-group-channel/model.ts
apps/web/src/services/iam/components/SelectChannelCard.vue
apps/web/src/services/iam/components/UserGroupChannelAddFormData.vue
apps/web/src/services/iam/components/UserGroupChannelCreateModal.vue
apps/web/src/services/iam/components/UserGroupChannelScheduleSetForm.vue
apps/web/src/services/iam/components/UserGroupChannelSetInputForm.vue
apps/web/src/services/iam/components/UserGroupChannelSetModal.vue
apps/web/src/services/iam/components/UserGroupDeleteDoubleCheckModal.vue
apps/web/src/services/iam/components/UserGroupManagementTabNotificationChannel.vue
apps/web/src/services/iam/components/UserGroupManagementTabUsers.vue
apps/web/src/services/iam/components/UserGroupManagementTable.vue
apps/web/src/services/iam/components/UserPerGroupRemoveDoubleCheckModal.vue
apps/web/src/services/iam/constants/user-group-constant.ts
apps/web/src/services/iam/store/notification-channel-create-form-store.ts
apps/web/src/services/iam/store/user-group-page-store.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

Feat: update minor changes and UserGroupChannel details

---

apps/web/src/services/ops-flow/OpsFlowContainer.vue
apps/web/src/services/ops-flow/pages/OpsFlowLandingPage.vue
apps/web/src/services/ops-flow/task-management-templates/stores/use-task-management-template-store.ts
apps/web/src/services/ops-flow/task-management-templates/translations/en.json
apps/web/src/services/ops-flow/task-management-templates/translations/ja.json
apps/web/src/services/ops-flow/task-management-templates/translations/ko.json
apps/web/src/services/ops-flow/task-management-templates/translations/task-management-template-2.8.babel

feat(ops-flow): add landing description and improve layout for landing page

---

apps/web/src/services/ops-flow/routes/routes.ts

feat(routes): restructure board route to include nested children components

---

apps/web/src/common/components/schedule-setting-form/ScheduleSettingForm.vue

fix: fixed schedule setting form bug

---

apps/web/src/services/alert-manager/components/AlertDetailInfoTable.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsNotificationsDetailTabs.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsOverview.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsOverviewEscalationPolicy.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsOverviewNotification.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEscalationPolicyFormChannelDropdown.vue
apps/web/src/services/alert-manager/constants/notification-table-constant.ts
apps/web/src/services/alert-manager/pages/AlertsDetailPage.vue
apps/web/src/services/alert-manager/pages/ServiceDetailPage.vue

feat: apply minor issue

---

apps/web/src/schema/alert-manager/user-group-channel/type.ts
apps/web/src/services/iam/components/UserGroupChannelScheduleSetForm.vue
apps/web/src/services/iam/components/UserGroupChannelSetModal.vue
apps/web/src/services/iam/components/UserGroupManagementTabNotificationChannel.vue
apps/web/src/services/iam/store/notification-channel-create-form-store.ts

Fix: fix code according to schedule type change

---

apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/default-value-registry.ts
apps/web/src/common/modules/widgets/_widget-fields/table-column-comparison/WidgetFieldTableColumnComparison.vue
apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
apps/web/src/common/modules/widgets/_widgets/table/widget-config.ts

fix(table-column-comparison): apply detail planning to table-column-comparison-ui field

---

apps/web/src/common/components/schedule-setting-form/ScheduleSettingForm.vue
apps/web/src/services/alert-manager/components/NotificationsCreateTypeSelector.vue
apps/web/src/services/alert-manager/components/WebhookCreateTypeSelector.vue

chore: apply min-height

---

apps/web/src/services/alert-manager/components/AlertDetailInfoTable.vue
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: changed account info to service info at alert detail

---

apps/web/src/common/modules/widgets/_widgets/sankey-chart/SankeyChart.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardReorderSidebar.vue

chore: set noData to SankeyChart & fix reorder sidebar

---

apps/web/src/services/cost-explorer/components/CostAnalysisHeader.vue
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat(cost-analysis): improve translation text for unified-cost page

---

apps/web/src/common/modules/widgets/_widget-field-value-manager/index.ts
apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/ColorCodedHeatmap.vue
apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
apps/web/src/common/modules/widgets/_widgets/sankey-chart/SankeyChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
apps/web/src/common/modules/widgets/_widgets/table/Table.vue
apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue

fix(widget): refactor loading & error message

---

apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/table/Table.vue
apps/web/src/common/modules/widgets/types/widget-data-type.ts

chore: solve widget load bugs

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
apps/web/src/common/modules/widgets/_widget-fields/table-column-comparison/WidgetFieldTableColumnComparison.vue
apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
apps/web/src/common/modules/widgets/_widgets/table/Table.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardWidgetContainerV2.vue
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: apply vue-query to preview table (data table) & refactor table & numberCard widgets

---

apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
apps/web/src/common/modules/widgets/_widgets/sankey-chart/SankeyChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue

fix: solve widget drawChart bug

---

apps/web/src/common/modules/user/UserSelectDropdown.vue
apps/web/src/services/iam/components/SelectChannelCard.vue
apps/web/src/services/iam/components/UserAssignToGroupModal.vue
apps/web/src/services/iam/components/UserGroupChannelDeleteDoubleCheckModal.vue
apps/web/src/services/iam/components/UserGroupChannelSetModal.vue
apps/web/src/services/iam/components/UserGroupManagementAddUsersModal.vue
apps/web/src/services/iam/components/UserGroupManagementEditModal.vue
apps/web/src/services/iam/components/UserGroupManagementTabNotificationChannel.vue
apps/web/src/services/iam/components/UserGroupManagementTable.vue
apps/web/src/services/iam/components/UserManagementHeader.vue
apps/web/src/services/iam/store/user-group-page-store.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: apply qa issue (user group & user)

---

apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue

chore: set series name to clustered chart tooltip & reverse order of horizontal bar chart

---

apps/web/src/common/modules/widgets/_widgets/sankey-chart/SankeyChart.vue

chore: edit sankey tooltip

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformDataTableDropdown.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformPivotForm.vue
apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue

feat(pivot): prevent selection of pivot when trying transform & apply new pivot planning

---

apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/ColorCodedHeatmap.vue
apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
apps/web/src/common/modules/widgets/_widgets/sankey-chart/SankeyChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
apps/web/src/common/modules/widgets/_widgets/table/Table.vue
apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
apps/web/src/common/modules/widgets/types/widget-data-type.ts
apps/web/src/schema/dashboard/private-data-table/model.ts
apps/web/src/schema/dashboard/public-data-table/model.ts

fix(widget-load): update widget load data type

---

apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/default-value-registry.ts
apps/web/src/common/modules/widgets/_widget-fields/data-field/WidgetFieldDataField.vue
apps/web/src/common/modules/widgets/_widget-fields/sub-total/WidgetFieldSubTotal.vue
apps/web/src/common/modules/widgets/_widget-fields/table-column-comparison/WidgetFieldTableColumnComparison.vue
apps/web/src/common/modules/widgets/_widgets/table/Table.vue
apps/web/src/common/modules/widgets/_widgets/table/widget-config.ts

fix(pivot): apply new pivot planning to table widget and widget form

---

apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts
apps/web/src/common/modules/widgets/_helpers/widget-load-helper.ts
apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/ColorCodedHeatmap.vue
apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTreeItem.vue
apps/web/src/services/dashboards/components/dashboard-main/DashboardLSBTree.vue

feat: refactor xy charts with pivot data

---

apps/web/src/schema/identity/user-group/constants.ts
apps/web/src/schema/identity/user-group/type.ts
apps/web/src/services/iam/components/SelectChannelCard.vue
apps/web/src/services/iam/components/UserAssignToGroupModal.vue
apps/web/src/services/iam/components/UserGroupChannelAddFormData.vue
apps/web/src/services/iam/components/UserGroupChannelCreateModal.vue
apps/web/src/services/iam/components/UserGroupChannelSetInputForm.vue
apps/web/src/services/iam/components/UserGroupChannelSetModal.vue
apps/web/src/services/iam/components/UserGroupDeleteDoubleCheckModal.vue
apps/web/src/services/iam/components/UserGroupManagementAddUsersModal.vue
apps/web/src/services/iam/components/UserGroupManagementTabNotificationChannel.vue
apps/web/src/services/iam/components/UserGroupManagementTabUsers.vue
apps/web/src/services/iam/components/UserGroupManagementTable.vue
apps/web/src/services/iam/components/UserManagementHeader.vue
apps/web/src/services/iam/components/UserManagementStatusModal.vue
apps/web/src/services/iam/components/UserManagementTable.vue
apps/web/src/services/iam/constants/user-group-constant.ts
apps/web/src/services/iam/store/notification-channel-create-form-store.ts

- don't have to see commit `update qa (ing)`
- [link1](https://mzdevs.atlassian.net/issues/MZ00003-1478?jql=parent%20%3D%20MZ00003-1440%20AND%20assignee%20%3D%20currentUser%28%29%20ORDER%20BY%20rank%20ASC)
- [link2](https://mzdevs.atlassian.net/issues/MZ00003-1479?jql=parent%20%3D%20MZ00003-1440%20AND%20assignee%20%3D%20currentUser%28%29%20ORDER%20BY%20rank%20ASC)
- [link3](https://mzdevs.atlassian.net/issues/MZ00003-1480?jql=parent%20%3D%20MZ00003-1440%20AND%20assignee%20%3D%20currentUser%28%29%20ORDER%20BY%20rank%20ASC)
- [link4](https://mzdevs.atlassian.net/issues/MZ00003-1483?jql=parent%20%3D%20MZ00003-1440%20AND%20assignee%20%3D%20currentUser%28%29%20ORDER%20BY%20rank%20ASC)
- [link5](https://mzdevs.atlassian.net/issues/MZ00003-1484?jql=parent%20%3D%20MZ00003-1440%20AND%20assignee%20% …

Feat: Alert Manager v2 - IAM QA 2

---

apps/web/src/services/advanced/pages/admin/AdminWorkspacesPage.vue
apps/web/src/services/iam/components/UserManagementAddUser.vue

fix: display user-add Modal after creating workspace and add condition

---

apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue

fix: fix resize bug in heatmap table

---

apps/web/src/common/modules/widgets/_constants/widget-field-constant.ts
apps/web/src/common/modules/widgets/_helpers/widget-load-helper.ts
apps/web/src/common/modules/widgets/_widget-fields/custom-table-column-width/WidgetFieldCustomTableColumnWidth.vue
apps/web/src/common/modules/widgets/_widget-fields/data-field/WidgetFieldDataField.vue
apps/web/src/common/modules/widgets/_widget-fields/sub-total/WidgetFieldSubTotal.vue
apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
apps/web/src/common/modules/widgets/_widgets/table/Table.vue
apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue

fix(sub-total): apply new subTotal planning

---

apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
apps/web/src/common/modules/widgets/_helpers/widget-helper.ts
apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/default-value-registry.ts
apps/web/src/common/modules/widgets/_widget-fields/number-format/WidgetFieldNumberFormat.vue
apps/web/src/common/modules/widgets/_widget-fields/number-format/type.ts
apps/web/src/common/modules/widgets/_widget-fields/sub-total/WidgetFieldSubTotal.vue
apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
apps/web/src/common/modules/widgets/_widgets/sankey-chart/SankeyChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue

fix(number-format): apply new pivot planning to number format

---

apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
apps/web/src/common/modules/widgets/_widgets/sankey-chart/SankeyChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue

chore: fix minor in sankey & apply reference label to charts

---

apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEscalationPolicyForm.vue

feat: apply drag at escalation policy rule card

---

apps/web/src/common/modules/widgets/_widgets/table/Table.vue
apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue

fix: apply reference field name to tale widget

---

apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/default-value-registry.ts

chore: fix groupBy field bug

---

apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue

fix: fix gauge data format

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformFormWrapper.vue

chore: minor style issue

---

apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue

chore: set proper code

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformValueMapping.vue
apps/web/src/common/modules/widgets/_constants/data-table-constant.ts
apps/web/src/common/modules/widgets/types/widget-model.ts

fix(value-mapping): apply changed value-mapping schema

---

apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue

chore: do not show 0 on series label

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformValueMapping.vue
apps/web/src/common/modules/widgets/_constants/data-table-constant.ts

chore(value-mapping): edit default value & edit validation rule

---

apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue

fix(number-card): fix previous data issue

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformJoin.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformValueMapping.vue

chore(transform): edit typo

---

apps/web/src/services/dashboards/helpers/dashboard-share-helper.ts

chore: add missing transform operator to dashboard-share code

---

apps/web/src/services/dashboards/components/dashboard-detail/DashboardWidgetContainerV2.vue
apps/web/src/services/dashboards/helpers/dashboard-share-helper.ts

fix: fix widget clone

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformPivotForm.vue

fix(pivot): fix pivot fixed fiels bug

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformPivotForm.vue
apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
apps/web/src/common/modules/widgets/_helpers/global-variable-helper.ts
apps/web/src/common/modules/widgets/_helpers/widget-data-table-helper.ts
apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/ColorCodedHeatmap.vue
apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
apps/web/src/common/modules/widgets/_widgets/sankey-chart/SankeyChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
apps/web/src/common/modules/widgets/_widgets/table/Table.vue
apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
apps/web/src/common/modules/widgets/types/widget-display-type.ts
apps/web/src/services/dashboards/components/dashboard-detail/DashboardWidgetContainerV2.vue

fix(widget): improve query-key with referenced dataTable map & apply refetching scenario & solve bugs

---

apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue

chore(widget): add defensive code

---

apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
apps/web/src/common/modules/widgets/_widget-fields/date-range/WidgetFieldDateRange.vue

fix(dashboard-widget): update missing UI

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformPivotForm.vue
apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/default-value-registry.ts
apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/validator-registry.ts
apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/heatmap/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/line-chart/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/pie-chart/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/widget-config.ts

fix(pivot): allowed pivot even if there is only one label field case

---

apps/storybook/.eslintrc.js
apps/storybook/tailwind.config.js

refactor(storybook): update config exports and tailwind setup

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue
apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/validator-registry.ts
apps/web/src/common/modules/widgets/_widget-field-value-manager/index.ts
apps/web/src/common/modules/widgets/_widget-fields/format-rules/WidgetFieldFormatRules.vue
apps/web/src/common/modules/widgets/_widget-fields/format-rules/type.ts
apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/widget-config.ts

fix(dashboard): solve QAs (data-source-popover, color-coded-heatmap)

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue

chore(dashboard): apply custom design (select-card)

---

apps/web/src/services/iam/components/UserManagementAddModal.vue
apps/web/src/services/iam/components/UserManagementAddUser.vue

fix: added event occurrence logic when clicking user in the workspace list

---

apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
apps/web/src/common/modules/widgets/_constants/widget-constant.ts
apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/default-value-registry.ts
apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue

fix(dashboard): solve dashboard QAs (pivot, number-card, table)

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformPivotForm.vue
apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
apps/web/src/common/modules/widgets/_composables/use-widget-date-range.ts
apps/web/src/common/modules/widgets/_widget-fields/header/WidgetHeaderField.vue
apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue

fix(dashboard): solve dashboard bugs

---

apps/web/src/common/composables/editor-content-transformer/index.ts
apps/web/src/common/modules/popup/notice/modules/NoticePopupItem.vue
apps/web/src/lib/helper/file-download-helper/index.ts
apps/web/src/services/info/components/NoticeDetail.vue
apps/web/src/services/info/components/NoticeForm.vue

fix(editor-content-transformer): update editor content transformer and notice popup item to update only changed

---

apps/web/src/common/components/select/DataSelector.vue
apps/web/src/lib/variable-models/_base/resource-variable-model.ts
apps/web/src/lib/variable-models/managed-model/resource-model/cloud-service-variable-model.ts
apps/web/src/services/ops-flow/components/BoardLSB.vue
apps/web/src/services/ops-flow/task-fields-form/field-templates/AssetTaskField.vue
packages/core-lib/src/query/index.ts
packages/language-pack/en.json
packages/language-pack/ko.json

feat: enhance CloudService models with improved handling

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformEvaluate.vue

fix(evaluate): apply changed EVAL name validation planning

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformEvaluate.vue

chore(dashboard-evaluate): temporarily remove duplicated eval name validation

---

apps/web/src/services/iam/components/UserGroupDeleteDoubleCheckModal.vue
apps/web/src/services/iam/components/UserManagementStatusModal.vue
apps/web/src/store/reference/escalation-policy-reference-store.ts

- self qa issue about deleting user & userGroup table checking modal about not showing data

feat: self qa issue & escalation-policy-reference-store update

---

apps/web/src/services/alert-manager/components/ServiceDetailTabsNotificationsDetailTabs.vue

fix: fixed time display bug

---

apps/web/src/services/ops-flow/OpsFlowContainer.vue
apps/web/tsconfig.json

fix: handle optional chaining for lsbVisible in OpsFlowContainer.vue

---

apps/web/src/schema/alert-manager/webhook/api-verbs/update-message-format.ts
apps/web/src/schema/alert-manager/webhook/model.ts
apps/web/src/schema/alert-manager/webhook/type.ts
apps/web/src/services/alert-manager/components/AlertDetailTabsTimeline.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRule.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsWebhookDetailTabs.vue
apps/web/src/services/alert-manager/components/ServiceList.vue
apps/web/src/services/alert-manager/constants/common-constant.ts
apps/web/src/services/alert-manager/constants/webhook-table-constant.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

Reverts cloudforet-io/console#5467

Revert "feat: apply webhook message tab"

---

apps/web/src/schema/alert-manager/webhook/api-verbs/update-message-format.ts
apps/web/src/schema/alert-manager/webhook/model.ts
apps/web/src/schema/alert-manager/webhook/type.ts
apps/web/src/services/alert-manager/components/AlertDetailTabsTimeline.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRule.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsWebhookDetailTabs.vue
apps/web/src/services/alert-manager/components/ServiceList.vue
apps/web/src/services/alert-manager/constants/common-constant.ts
apps/web/src/services/alert-manager/constants/webhook-table-constant.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: apply webhook message tab

---

apps/web/src/common/modules/user/UserSelectDropdown.vue
apps/web/src/schema/alert-manager/user-channel/api-verbs/update.ts
apps/web/src/schema/alert-manager/user-channel/type.ts
apps/web/src/services/iam/components/UserManagementTab.vue
apps/web/src/services/my-page/components/NotificationAddForm.vue
apps/web/src/services/my-page/components/NotificationAddFormData.vue
apps/web/src/services/my-page/components/NotificationAddSchedule.vue
apps/web/src/services/my-page/components/NotificationChannelItem.vue
apps/web/src/services/my-page/components/NotificationChannelItemData.vue
apps/web/src/services/my-page/components/NotificationChannelItemLevel.vue
apps/web/src/services/my-page/components/NotificationChannelItemName.vue
apps/web/src/services/my-page/components/NotificationChannelItemSchedule.vue
apps/web/src/services/my-page/components/NotificationChannelItemTopic.vue
apps/web/src/services/my-page/components/NotificationChannelList.vue
apps/web/src/services/my-page/composables/notification-item.ts
apps/web/src/services/my-page/types/notification-channel-item-type.ts

Feat: update AlertManager API-V2 at myPage notification & apply minor qa issue

---

apps/web/src/services/alert-manager/components/AlertsDetailHeader.vue
apps/web/src/services/alert-manager/components/ServiceDetailDeleteModal.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsWebhookDetail.vue
apps/web/src/services/alert-manager/constants/webhook-table-constant.ts
apps/web/src/services/alert-manager/stores/service-detail-page-store.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: apply webhook error tab, service delete modal table

---

apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEscalationPolicyFormChannelDropdown.vue

feat: apply notification icon at escalation policy channel dropdown

---

apps/web/src/services/iam/components/UserGroupDeleteDoubleCheckModal.vue
apps/web/src/services/iam/components/UserGroupManagementTabNotificationChannel.vue
apps/web/src/services/iam/components/UserManagementStatusModal.vue
apps/web/src/services/my-page/components/NotificationChannelItemSchedule.vue

* feat: update async/await after update userChannel schedule
* feat: add each protocol icon at userGroupChannel table
* feat: update delete double check table modal of user and userGroup
* fix: remove unnecessary code
* fix: remove korean comments
---------

Feat: apply qa issue (#5481)

---

apps/web/Dockerfile

- Improve security vulnerabilities (Non-root user setting - `USER 1001`, chown NGINX config file and log folder)
- Applied to comply with Docker best practices
---
- USER 1001: 비루트 사용자로 실행되도록 설정
- chown: NGINX 설정 파일과 로그 폴더 권한을 비루트 사용자로 조정
- **로그 리디렉션**: NGINX 로그를 표준 출력으로 연결하여 로그 관리 효율화
- **폴더 및 파일 접근성 보장**: 비루트 사용자도 정상적으로 파일에 접근 가능하도록 소유권 변경
- **보안 강화**:
-  컨테이너 내에서 root 권한을 제거하여 침해 시 피해를 최소화
- 권한이 분리되어 공격자의 활동 범위가 제한
- **Docker 모범 사례 준수**:
- 비루트 사용자 실행은 보안 강화를 위한 Dockerfile의 권장 사항
- 기존 기능은 모두 유지하면서 권한과 보안 설정만 개선되었습니다.

fix(web-dockerfile): enhance security by improving security vulnerabilities

---

apps/web/src/schema/alert-manager/alert/api-verbs/list.ts
apps/web/src/services/asset-inventory-v1/components/CloudServiceAlertsTab.vue
apps/web/src/services/asset-inventory-v1/components/CloudServiceDetailTabs.vue
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: add CloudServiceAlertsTab component for viewing at cloudService

---

apps/web/src/services/auth/authenticator/local/template/ID_PW.vue
apps/web/src/services/auth/components/SignInRightContainer.vue
apps/web/src/services/my-page/components/UserAccountChangePassword.vue
apps/web/src/store/display/display-store.ts
apps/web/src/store/display/type.ts
packages/core-lib/src/space-connector/service-api.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

- Refactor `SpaceConnector` error handling (401)

fix(sign-in-block): apply sign-in block scenario

---

apps/web/public/lottie.js

fix(console): refactor lottie.js(app/web) with security vulnerability

---

.github/workflows/pull_request_random_reviewer_assignment.yaml

ci: add pr random reviewer workflow

---

apps/web/src/services/auth/authenticator/local/template/ID_PW.vue
packages/mirinae/src/controls/input/text-input/PTextInput.stories.ts
packages/mirinae/src/controls/input/text-input/PTextInput.vue
packages/mirinae/src/controls/input/text-input/story-helper.ts

fix(text-input): add `skipMaskToggleTabIndex` props and apply

---

.github/workflows/pull_request_random_reviewer_assignment.yaml

ci: move environment variables into job definition for clarity

---

.github/workflows/pull_request_random_reviewer_assignment.yaml

ci: remove 'reopened' event from pull request reviewer assignment workflow

---

.github/workflows/pull_request_random_reviewer_assignment.yaml

chore: remove unnecessary whitespace in workflow file for test ci

---

apps/web/src/services/iam/helpers/generate-helper.ts

chore: solve biased random number issue

---

apps/web/Dockerfile

chore(Dockerfile): apply non-root user setting

---

apps/web/Dockerfile

chore(Dockerfile): apply non-root user setting (change user switching)

---

.github/workflows/pull_request_random_reviewer_assignment.yaml
.github/workflows/pull_request_review.yaml

chore: add newline at the end of pull_request_random_reviewer_assignment.yaml for ci test

---

.github/workflows/pull_request_random_reviewer_assignment.yaml

ci: test PR for random pick reviewer

---

.github/workflows/pull_request_random_reviewer_assignment.yaml

ci: fix status of random reviewer picker

---

.github/workflows/pull_request_random_reviewer_assignment.yaml

chore: add newline at the end of pull_request_random_reviewer_assignment for test

---

.github/workflows/pull_request_random_reviewer_assignment.yaml

fix: update status check for adding reviewers in pull_request_random_reviewer_assignment.yaml

---

.github/workflows/pull_request_random_reviewer_assignment.yaml

fix: response status check for reviewer assignment workflow

---

.github/workflows/pull_request_random_reviewer_assignment.yaml

ci: improve error handling in random reviewer assignment workflow

---

apps/web/public/lottie.js

chore(lottie.js): replace lottie.js to lottie-light.js for security-vulnerability

---

packages/mirinae/src/controls/input/text-input/PTextInput.stories.ts
packages/mirinae/src/controls/input/text-input/PTextInput.vue
packages/mirinae/src/controls/input/text-input/story-helper.ts

feat: apply hide spin button at text-input

---

.github/workflows/pull_request_random_reviewer_assignment.yaml

ci: update label name in pull_request_random_reviewer_assignment.yaml

---

.github/workflows/pull_request_random_reviewer_assignment.yaml

ci: remove unnecessary newline at the end of pull_request_random_reviewer_assignment.yaml for test

---

.github/workflows/pull_request_random_reviewer_assignment.yaml
.github/workflows/pull_request_review_label_cleanup.yaml
.github/workflows/pull_request_review_labeler.yaml

chore: add missing newline at the end of pull_request_random_reviewer_assignment.yaml for test

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/pull_request_random_reviewer_assignment.yaml
.github/workflows/pull_request_review.yaml
.github/workflows/pull_request_review_label_cleanup.yaml
.github/workflows/pull_request_review_labeler.yaml

ci: add pr reviewer random picker & labeler & label cleaner workflows

---

.github/workflows/pull_request_review_labeler.yaml

chore: ci test

---

apps/web/Dockerfile

chore(Dockerfile): solve nginx dir permission issue

---

apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRule.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRuleActionForm.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRuleCard.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRuleConditionForm.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRuleFormCard.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRuleSidebar.vue

feat: apply mobile responsive design to the event rules page

---

apps/web/Dockerfile

chore(dockerfile): solve dockerfile user permission issue

---

apps/web/Dockerfile

chore(dockerfile): set log file write permission

---

apps/web/Dockerfile

chore(dockerfile): give user local custom permission

---

apps/web/src/common/components/select/DataSelector.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRuleActionAsset.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRuleFormCard.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRuleSidebar.vue
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: apply match asset dropdown

---

apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRuleActionAsset.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRuleCard.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRuleSidebar.vue

feat: update mobile responsive design of event rules page

---

apps/web/src/store/reference/collector-reference-store.ts
apps/web/src/store/reference/region-reference-store.ts

fix(reference-store): correct logic for selecting fetcher based on version

---

apps/web/src/services/my-page/pages/UserAccountPage.vue

chore(user-account-page): remove unnecessary button in external user case

---

apps/web/Dockerfile
apps/web/pkg/proxy.conf

build: update nginx conf & set custom nginx user permission

---

apps/web/Dockerfile

build(nginx): update nginx image version

---

apps/web/Dockerfile

build(nginx): remove adduser addgroup

---

apps/web/Dockerfile

build(dockerfile-nginx): set port 80 without root user permission

---

apps/web/Dockerfile
apps/web/pkg/nginx.conf

build(nginx): set proper permission to nginx

---

apps/web/Dockerfile

build: rollback Dockerfile to 2.0.dev285

---

apps/web/src/services/my-page/components/UserAccountBaseInformation.vue
apps/web/src/services/my-page/components/UserAccountChangePassword.vue

chore(user-account-page): edit some design changes

---

apps/web/Dockerfile
apps/web/package.json
apps/web/pkg/nginx.conf
apps/web/pkg/proxy.conf
apps/web/src/services/my-page/components/UserAccountBaseInformation.vue
apps/web/src/services/my-page/components/UserAccountChangePassword.vue
package-lock.json
package.json

feat(security-vulnerability): merge to develop

---

apps/web/src/services/alert-manager/components/ServiceDetailTabsWebhookDetail.vue

chore: apply sort

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformValueMapping.vue
apps/web/src/common/modules/widgets/_widget-fields/group-by/WidgetFieldGroupBy.vue
apps/web/src/common/modules/widgets/_widgets/sankey-chart/widget-config.ts

fix(dashboard): solve dashboard QAs

---

apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/ColorCodedHeatmap.vue
apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
apps/web/src/common/modules/widgets/_widgets/sankey-chart/SankeyChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
apps/web/src/common/modules/widgets/_widgets/table/Table.vue
apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue

fix(widget): solve widget QAs

---

apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRuleSidebar.vue

chore(event-rule): apply 'hasReadWriteAccess' at order button

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformValueMapping.vue
apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
apps/web/src/common/modules/widgets/_widget-fields/group-by/WidgetFieldGroupBy.vue
apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/ColorCodedHeatmap.vue
apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
apps/web/src/common/modules/widgets/_widgets/sankey-chart/SankeyChart.vue
apps/web/src/common/modules/widgets/_widgets/sankey-chart/widget-config.ts
apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
apps/web/src/common/modules/widgets/_widgets/table/Table.vue
apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesMoreButton.vue
apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesV2.vue

feat(dashboard-middle-qa): merge to develop

---

apps/web/src/services/alert-manager/components/AlertDetailSummary.vue
apps/web/src/services/alert-manager/components/ServiceList.vue
apps/web/src/services/alert-manager/components/ServiceListContent.vue
apps/web/src/services/project-v1/components/ProjectAlertSettingsEscalationPolicyChangeModal.vue

feat: apply reference store data at service item, alert detail summary

---

apps/web/src/schema/identity/user-profile/api-verbs/update-password.ts
apps/web/src/services/auth/pages/PasswordPage.vue
apps/web/src/services/my-page/components/UserAccountChangePassword.vue

chore(reset-password): apply new update password api to reset-password page

---

apps/web/src/services/alert-manager/components/AlertDetailSummary.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsSettings.vue

feat: apply escalation policy link

---

apps/web/src/services/my-page/components/UserAccountMultiFactorAuthFormModal.vue
apps/web/src/services/my-page/pages/UserAccountPage.vue
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

fix(user-account-page): apply changed planning (password-check, set mfa)

---

packages/mirinae/src/layouts/vertical-layout/PVerticalLayout.vue

Refactor: changing resizer line to fatter when it hoverd (#5458)

---

packages/mirinae/src/controls/input/query-input/PQueryInput.vue

fix: reflect the latest changes in composable to the queryInput

---

apps/web/src/common/composables/data-source/use-cost-data-source-filter-menu-items.ts
apps/web/src/services/asset-inventory-v1/components/MetricExplorerGroupBy.vue
apps/web/src/services/cost-explorer/constants/cost-explorer-constant.ts
apps/web/src/services/cost-explorer/constants/managed-cost-analysis-query-sets.ts
apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesV2.vue
apps/web/src/services/dashboards/constants/dashboard-vars-schema-preset.ts

feat(project-group-filter): apply project-group filter to metric-explorer/cost-analysis/dashboard

---

.github/workflows/pull_request_random_reviewer_assignment.yaml

ci: fix random reviewer assignment workflow job execution condition

---

apps/web/src/common/pages/AlertPublicDetailPage.vue
apps/web/src/schema/monitoring/alert/model.ts
apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRule.vue
apps/web/src/services/alert-manager/components/ServiceList.vue
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

- [update alert public page with v2 division](https://mzdevs.atlassian.net/browse/MZ00003-1725)
- [update title not to be displayed if there's no data](https://mzdevs.atlassian.net/browse/MZ00003-1748)
- [fix bug about hasReadWriteAccess of button](https://mzdevs.atlassian.net/browse/MZ00003-1749)

feat: update Alert Public Page with V2 & apply qa issue

---

apps/web/src/common/components/forms/pairs-input-group/PairsInputGroup.vue

fix: fixed convert function bug

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
apps/web/src/services/asset-inventory-v1/components/MetricExplorerFiltersPopper.vue
apps/web/src/services/asset-inventory-v1/components/MetricExplorerGroupBy.vue
apps/web/src/services/asset-inventory-v1/constants/asset-analysis-constant.ts
apps/web/src/services/cost-explorer/constants/cost-explorer-constant.ts
apps/web/src/services/dashboards/constants/dashboard-vars-schema-preset.ts

fix(project-group-filter): apply project group filter (data-table, metric-explorer)

---

apps/web/src/common/composables/data-source/use-cost-data-source-filter-menu-items.ts
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
apps/web/src/services/asset-inventory-v1/components/MetricExplorerFiltersPopper.vue
apps/web/src/services/asset-inventory-v1/components/MetricExplorerGroupBy.vue
apps/web/src/services/asset-inventory-v1/constants/asset-analysis-constant.ts
apps/web/src/services/cost-explorer/constants/cost-explorer-constant.ts
apps/web/src/services/cost-explorer/constants/managed-cost-analysis-query-sets.ts
apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesV2.vue
apps/web/src/services/dashboards/constants/dashboard-vars-schema-preset.ts

feat(project-group): merge to develop

---

packages/mirinae/src/data-display/collapsible/collapsible-panel/PCollapsiblePanel.vue
packages/mirinae/src/data-display/collapsible/collapsible-panel/type.ts

refactor: add component props type

---

apps/web/src/router/admin-routes.ts
apps/web/src/services/dashboards/helpers/dashboard-global-variables-helper.ts

chore(admin-route): solve wrong inventory-v2 route bug

---

apps/web/src/services/alert-manager/components/AlertsManagementTable.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsContainer.vue

fix: fixed qa bug

---

apps/web/src/services/dashboards/constants/dashboard-global-variable-preset.ts
apps/web/src/services/dashboards/helpers/dashboard-global-variables-helper.ts

chore(dashboard-variable): add project group variable

---

apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsContainer.vue

chore: apply immediate at watch

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformPivotForm.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformValueMapping.vue

chore(data-table): apply design detail to dropdown (transform-data-table)

---

apps/web/src/store/reference/collector-reference-store.ts
apps/web/src/store/reference/region-reference-store.ts

chore(reference-store): remove wrong branching code (inventory v2)

---

apps/web/src/services/dashboards/stores/dashboard-page-control-store.ts
apps/web/src/store/dashboard/dashboard-store.ts

chore(dashboard): apply new sorting policy to dashboard and dashboard-folder

---

apps/web/package.json
package-lock.json
package.json

chore: version 2.0.dev302

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFilters.vue

chore(data-table): solve data-table project-group filter bug

---

apps/web/Dockerfile

fix(dockerfile): add missing console log path

---

.github/workflows/dispatch_master_to_develop.yaml
.github/workflows/dispatch_release.yaml
.github/workflows/pull_request_check_revert_candidate_commits.yaml

- [] Self-merge allowed for solo developers or urgent changes

chore: create workflows merge from master to develop and check commits

---

apps/web-storybook/.gitignore
vercel.json

chore(vercel): remove specific app option from vercel.json

---

apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts

fix(widget): solve widget link bug

---

.github/workflows/dispatch_deploy_unfied_storybook.yaml
turbo.json

chore(build): add a GitHub Actions workflow to deploy unified-storybook

---

apps/web/src/lib/menu/menu-architecture.ts

fix(menu): add ops flow menu items to alertV2MenuList

---

packages/mirinae/src/layouts/overlay-layout/POverlayLayout.vue

chore: changed style section

---

apps/web/src/services/asset-inventory-v1/components/CloudServiceDetailTabs.vue

fix: add task management tab to cloud service detail view

---

apps/web/src/schema/cost-analysis/data-source/model.ts
apps/web/src/schema/cost-analysis/data-source/type.ts
apps/web/src/services/cost-explorer/components/DataSourceManagementTable.vue

fix(data-source): apply changed CostDataSource model (state)

---

apps/web/src/schema/alert-manager/webhook/model.ts
apps/web/src/services/alert-manager/components/ServiceDetailTabsOverviewInfo.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsOverviewWebhookBarChartDaily.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsOverviewWebhookChart.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsOverviewWebhookChartDaily.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsOverviewWebhookChartMonthly.vue
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

Feat: mark-up and api connect daily chart of wehbook

---

apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts
apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/ColorCodedHeatmap.vue
apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
apps/web/src/common/modules/widgets/_widgets/sankey-chart/SankeyChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
apps/web/src/common/modules/widgets/_widgets/table/Table.vue
apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
apps/web/src/services/asset-inventory-v1/components/MetricExplorerPeriodDropdown.vue
apps/web/src/services/asset-inventory-v1/components/MetricExplorerQuerySection.vue
apps/web/src/services/asset-inventory-v1/pages/MetricExplorerDetailPage.vue
apps/web/src/services/asset-inventory-v1/stores/metric-explorer-page-store.ts

fix(metric-explorer): solve widget metric link bug & refactor metric page

---

apps/web/src/services/cost-explorer/components/CostAnalysisDataTable.vue

fix(cost-analysis): apply project/service-account link to cost data table

---

apps/web/src/common/modules/widgets/_constants/data-table-constant.ts

fix(data-table-tags): remove tags item (project)

---

apps/web/src/common/components/forms/pairs-form/PairsForm.vue
apps/web/src/services/asset-inventory-v1/components/CloudServiceHistoryDetailOverlay.vue
apps/web/src/services/asset-inventory/components/CloudServiceHistoryDetailOverlay.vue

SSIA
- [feedback](https://www.notion.so/Tag-183bfa76599680d89d9af8aa72d8ca3e?pvs=4)

chore: changed z-index at custom overlay

---

apps/web/src/services/cost-explorer/components/CostAnalysisDataTable.vue

chore(cost-analysis): solve usage unit total issue

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue

chore: apply no limit query to service account tags

---

apps/web/src/services/workspace-home/components/Bookmark.vue

fix: fixed bookmark name edit bug

---

apps/web/src/common/modules/widgets/_components/WidgetFormAssetSecurityDataSourcePopper.vue

fix(asset-data-source): temporarily remove dataSourceDomain filter

---

apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
apps/web/src/common/modules/widgets/_helpers/widget-helper.ts
apps/web/src/common/modules/widgets/_widget-field-value-manager/index.ts
apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
apps/web/src/common/modules/widgets/_widgets/sankey-chart/SankeyChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue

feat(widget-form): solve widget form bugs

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCard.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep1.vue
apps/web/src/common/modules/widgets/_composables/use-data-table-cascade-update.ts
apps/web/src/common/modules/widgets/_helpers/widget-data-table-helper.ts
apps/web/src/common/modules/widgets/_helpers/widget-helper.ts
apps/web/src/services/dashboards/components/dashboard-detail/DashboardWidgetContainerV2.vue
apps/web/src/services/dashboards/composables/use-dashboard-query.ts
apps/web/src/services/dashboards/pages/DashboardsMainPage.vue

fix(dashboard): solve dashboard list bug & refactor dataTable updating ux

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFooter.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
apps/web/src/common/modules/widgets/_composables/use-data-table-cascade-update.ts
apps/web/src/common/modules/widgets/_store/widget-generate-store.ts

chore(data-table): solve transform data-table update bug

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFilters.vue
apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
apps/web/src/common/modules/widgets/_components/WidgetFormUnifiedCostDataSourcePopper.vue
apps/web/src/common/modules/widgets/_constants/data-table-constant.ts
apps/web/src/common/modules/widgets/types/widget-model.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat(unified-cost): apply unified cost data source to data table creating & solve dashboard layout issue

---

apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/ColorCodedHeatmap.vue
apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
apps/web/src/common/modules/widgets/_widgets/sankey-chart/SankeyChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
apps/web/src/common/modules/widgets/_widgets/table/Table.vue
apps/web/src/common/modules/widgets/types/widget-display-type.ts
apps/web/src/services/dashboards/components/dashboard-detail/DashboardWidgetContainerV2.vue
apps/web/src/services/dashboards/helpers/dashboard-share-helper.ts

fix(dashboard-clone): solve dashboard clone bug

---

apps/web/src/services/dashboards/pages/DashboardDetailPage.vue

chore(dashboard): solve dashboard call issue (detail page)

---

.github/workflows/pull_request_random_reviewer_assignment.yaml

chore(workflow): improve random reviewer assignment logic

---

apps/web/src/services/alert-manager/components/ServiceDetailTabsOverviewInfo.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsOverviewInfoAlertAverageTimeByUrgencyBarChart.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsOverviewMostTriggeredAlertsTable.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsOverviewWebhookBarChartDaily.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsOverviewWebhookBarChartMonthly.vue
apps/web/src/services/alert-manager/composables/alert-table-data.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

- You only need to pay close attention to that **feat: update Bar chart section about average duration of alerts** (the other commits are minor).
- update Average Acknowledged & Resolved Time by Urgency

Feat: update Service > Overview Tab (Average Acknowledged & Resolved Time by Urgency)

---

apps/web/src/services/dashboards/components/dashboard-main/DashboardLSBTree.vue
apps/web/src/services/project-v1/components/ProjectMainTree.vue

chore(lsb-tree): apply default indent (project, dashboard)

---

apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTreeItem.vue

chore: edit dashboard tree item layout

---

packages/mirinae/src/data-display/dynamic/dynamic-field/templates/dict/index.vue

chore(p-dynamic-field): fix minor style (dict field)

---

apps/web/src/services/alert-manager/components/CustomMonthRangeModal.vue
apps/web/src/services/alert-manager/components/ServiceDetailHeader.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsOverviewInfo.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsOverviewInfoAlertAverageTimeByUrgencyBarChart.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsOverviewMostTriggeredAlertsTable.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsOverviewStatusTable.vue
apps/web/src/services/alert-manager/components/ServiceDetailTabsOverviewWebhook.vue
apps/web/src/services/iam/components/UserGroupManagementTabNotificationChannel.vue
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

- <img width="863" alt="image" src="https://github.com/user-attachments/assets/8ea9c34a-4d89-49b2-8b07-219437495d22" />
--
- ![image](https://github.com/user-attachments/assets/10fe973c-0272-4186-8912-482945828c2f)
- ![image](https://github.com/user-attachments/assets/346790b1-53fd-47d8-b641-be1fa257c255)
- ![image](https://github.com/user-attachments/assets/da0c7d3c-f7f4-43f3-afc9-380e86cfdcaf)

Feat: update Service Overview Tab after design improvement

---

.github/workflows/pull_request_random_reviewer_assignment.yaml

fix(ci): add optional chaining to prevent null user login errors in PR reviewer assignment workflow

---

apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardHeaderTitle.vue
apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
apps/web/src/common/modules/widgets/_helpers/widget-helper.ts
apps/web/src/common/modules/widgets/_helpers/widget-options-helper.ts
apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/default-value-registry.ts

chore(widget): solve dependency cycle

---

apps/web/src/common/modules/widgets/_widgets/table/Table.vue

chore: improve table widget loading state

---

apps/web/src/common/modules/widgets/_composables/use-widget-date-range.ts

fix(widget-date-range): apply date-range api query policy

---

.github/workflows/dispatch_storybook_release.yaml

fix(workflow): update storybook filter in build command

---

apps/web/src/services/alert-manager/v1/components/AlertDashboardAlertStateWidget.vue
apps/web/src/services/alert-manager/v1/components/AlertDashboardProjectSearchWidgetAlertList.vue
apps/web/src/services/alert-manager/v1/components/AlertDashboardTop5ProjectActivityWidgetTooltip.vue
apps/web/src/services/alert-manager/v1/components/AlertDetailResponder.vue
apps/web/src/services/alert-manager/v1/components/AlertMainAcknowledgeModal.vue
apps/web/src/services/alert-manager/v1/components/AlertMainDataTableActions.vue
apps/web/src/services/alert-manager/v1/components/AlertMainResolveModal.vue
apps/web/src/services/project/v1/components/ProjectSummaryAlertWidget.vue

chore: changed schema mode name

---

apps/web/src/api-clients/identity/service-account/schema/api-verbs/create.ts
apps/web/src/api-clients/identity/service-account/schema/api-verbs/update.ts
apps/web/src/api-clients/identity/service-account/schema/model.ts
apps/web/src/services/asset-inventory/components/ServiceAccountBaseInformation.vue
apps/web/src/services/asset-inventory/components/ServiceAccountBaseInformationForm.vue
apps/web/src/services/asset-inventory/helpers/dynamic-ui-schema-generator/dynamic-layout-schema-template.ts
apps/web/src/services/asset-inventory/pages/ServiceAccountAddPage.vue
apps/web/src/services/asset-inventory/types/service-account-page-type.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

Feat: add features related to service account manager

---

apps/web/src/api-clients/api-client-manager.ts
apps/web/src/common/composables/contents-accessibility/index.ts
apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue
apps/web/src/services/configurator.ts
apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesFormDynamic.vue
apps/web/src/services/project/v1/components/ProjectDetailTabHeader.vue
apps/web/src/services/project/v1/components/ProjectSummaryAllSummaryWidget.vue
apps/web/src/services/project/v1/components/ProjectSummaryAllSummaryWidgetRegionService.vue
apps/web/src/services/project/v1/components/ProjectSummaryServiceAccountsWidget.vue
apps/web/src/services/project/v1/pages/ProjectDetailTabPage.vue
apps/web/src/services/project/v1/pages/ProjectSummaryPage.vue
apps/web/src/services/workspace-home/components/Summaries.vue
apps/web/src/store/reference/escalation-policy-reference-store.ts
apps/web/src/store/reference/webhook-reference-store.ts

feat: hide content of disabled services

---

apps/web/src/common/modules/navigations/stores/gnb-store.ts
apps/web/src/lib/config/global-config/feature-schema-manager.ts
apps/web/src/lib/config/global-config/type.ts
apps/web/src/lib/site-initializer/api-client.ts
apps/web/src/services/asset-inventory/components/CloudServiceDetailTabs.vue
apps/web/src/services/asset-inventory/stores/cloud-service-detail-page-store.ts
apps/web/src/services/cost-explorer/stores/budget-detail-page-store.ts
apps/web/src/services/my-page/stores/my-page-store.ts
apps/web/src/services/project/v1/stores/project-detail-page-store.ts

feat: apply opsFlow tab at cloud service

---

apps/web/public/config/default.json
apps/web/public/config/development.json.sample

chore: add services config at default.json

---

apps/web/public/config/default.json
apps/web/src/api-clients/api-client-manager.ts
apps/web/src/api-clients/config/public-config/schema/constant.ts
apps/web/src/lib/site-initializer/api-client.ts
apps/web/src/lib/site-initializer/index.ts
apps/web/src/lib/site-initializer/merge-config.ts
apps/web/src/services/configurator.ts
apps/web/src/store/display/composables/useAdvancedMenuDisplay.ts
apps/web/src/store/display/display-store.ts

feat: modify to allow override of setting data by domain

---

apps/web/src/lib/site-initializer/merge-config.ts

fix: handle 404 error gracefully by setting default values

---

apps/web/src/api-clients/cost-analysis/budget/schema/type.ts
apps/web/src/common/modules/user/UserSelectDropdown.vue
apps/web/src/services/cost-explorer/components/BudgetCreateManagerSelect.vue
apps/web/src/services/cost-explorer/components/BudgetCreateScopeSelect.vue
apps/web/src/services/cost-explorer/components/BudgetCreateStep1.vue
apps/web/src/services/cost-explorer/components/BudgetCreateStep2.vue
apps/web/src/services/cost-explorer/components/BudgetCreateStep3.vue
apps/web/src/services/cost-explorer/components/BudgetDeleteCheckModal.vue
apps/web/src/services/cost-explorer/pages/BudgetCreatePage.vue
apps/web/src/services/cost-explorer/pages/BudgetLastThreeMonthCostTrendBarChart.vue
apps/web/src/services/cost-explorer/stores/budget-create-page-store.ts

Feat: update budget create page with reactivity chart

---

apps/web/src/lib/access-control/page-access-helper.ts
apps/web/src/lib/config/global-config/type.ts
apps/web/src/services/iam/components/RoleManagementTabDetail.vue
apps/web/src/services/iam/components/RoleUpdateFormPermissionForm.vue
apps/web/src/services/iam/constants/role-constant.ts
apps/web/src/services/iam/helpers/role-page-access-menu-list.ts
apps/web/src/services/iam/types/role-type.ts

fix: fixed page access menu

---

apps/web/src/services/asset-inventory/routes/admin/route-constant.ts

fix(collector-job): add missing route name prefix (admin collector job page)

---

apps/web/src/services/advanced/routes/admin/routes.ts
apps/web/src/services/alert-manager/v2/routes/routes.ts
apps/web/src/services/asset-inventory/routes/admin/routes.ts
apps/web/src/services/asset-inventory/routes/routes.ts

chore(route-config): fix wrong route config usage

---

packages/mirinae/src/controls/context-menu/PContextMenu.vue

- before
https://github.com/user-attachments/assets/01faf6e7-2595-40c6-a6f7-7f4d5a5ed022
- after
https://github.com/user-attachments/assets/331e4790-9df2-4559-b9c4-688505fda415

feat: do not hide search when there're no menu

---

apps/web/src/services/alert-manager/v2/constants/alert-table-constant.ts

chore: add type at alert excel field

---

packages/mirinae/src/controls/buttons/button/PButton.mdx
packages/mirinae/src/controls/buttons/button/PButton.stories.ts
packages/mirinae/src/controls/buttons/button/PButton.vue
packages/mirinae/src/controls/buttons/button/story-helper.ts
packages/mirinae/src/controls/buttons/button/type.ts
packages/mirinae/src/controls/buttons/icon-button/PIconButton.vue
packages/mirinae/src/controls/dropdown/select-dropdown/PSelectDropdown.mdx
packages/mirinae/src/controls/dropdown/select-dropdown/PSelectDropdown.stories.ts
packages/mirinae/src/controls/dropdown/select-dropdown/PSelectDropdown.vue
packages/mirinae/src/controls/dropdown/select-dropdown/components/dropdown-button.vue
packages/mirinae/src/controls/dropdown/select-dropdown/story-helper.ts
packages/mirinae/src/hooks/index.ts
packages/mirinae/src/hooks/use-text-ellipsis/type.ts
packages/mirinae/src/hooks/use-text-ellipsis/use-text-ellipsis.stories.ts
packages/mirinae/src/hooks/use-text-ellipsis/use-text-ellipsis.ts
packages/mirinae/src/hooks/use-text-ellipsis/useTextEllipsis.mdx

- Implement new hook for text overflow detection
- Add Storybook examples and documentation
- Add type definitions
- Add active state to PButton component
- Update PIconButton component
- Update related stories and documentation
- Improve dropdown button component
- Update stories and documentation
---
- 텍스트 오버플로우 감지를 위한 새로운 훅 구현
- 스토리북 및 문서화 추가
- 타입 정의 추가
- PButton 컴포넌트 active 상태 추가
- PIconButton 컴포넌트 업데이트
- 관련 스토리 및 문서 업데이트
- 드롭다운 버튼 컴포넌트 개선
- 스토리 및 문서 업데이트

feat(mirinae): add text ellipsis detection hook and improve button components

---

apps/web/src/common/modules/favorites/favorite-button/FavoriteButton.vue
apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-favorite/modules/TopBarFavoriteContextMenu.vue
apps/web/src/services/workspace-home/components/UserConfigRecent.vue

chore(dashboard-query): apply optimization (global component)

---

apps/web/src/services/asset-inventory/components/CollectorHistoryJobTaskTable.vue

chore: solve job history page issue (missing var)

---

apps/web/src/api-clients/dashboard/private-dashboard/composables/use-private-dashboard-api.ts
apps/web/src/api-clients/dashboard/private-data-table/composables/use-private-data-table-api.ts
apps/web/src/api-clients/dashboard/private-folder/composables/use-private-folder-api.ts
apps/web/src/api-clients/dashboard/private-widget/composables/use-private-widget-api.ts
apps/web/src/api-clients/dashboard/public-dashboard/composables/use-public-dashboard-api.ts
apps/web/src/api-clients/dashboard/public-data-table/composables/use-public-data-table-api.ts
apps/web/src/api-clients/dashboard/public-folder/composables/use-public-folder-api.ts
apps/web/src/api-clients/dashboard/public-widget/composables/use-public-widget-api.ts

chore: remove query key in api client composable

---

apps/web/src/api-clients/_common/composables/use-scoped-query.ts
packages/mirinae/src/navigation/tabs/tab/PTab.vue

fix: update useScopedQuery to handle undefined queryEnabled state and add slot props to Tab component 

---

apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-favorite/TopBarFavorite.vue
apps/web/src/services/cost-explorer/components/BudgetCreateFormBaseInfo.vue
apps/web/src/services/cost-explorer/components/BudgetMainToolbox.vue
apps/web/src/services/cost-explorer/components/CostAnalysisChartLegends.vue
apps/web/src/services/cost-explorer/components/CostAnalysisFiltersAddMoreButton.vue
apps/web/src/services/dashboards/components/dashboard-create/DashboardCreateStep2BundleCase.vue
apps/web/src/services/dashboards/components/dashboard-create/DashboardCreateStep2SingleCase.vue
apps/web/src/services/dashboards/widgets/_base-widgets/base-pie/BasePieWidget.vue
apps/web/src/services/dashboards/widgets/_base-widgets/base-trend/BaseTrendWidget.vue
apps/web/src/services/dashboards/widgets/asset-widgets/compliance-status/ComplianceStatusWidget.vue
apps/web/src/services/dashboards/widgets/asset-widgets/severity-status-by-service/SeverityStatusByServiceWidget.vue
apps/web/src/services/dashboards/widgets/asset-widgets/total-fail-findings-history/TotalFailFindingsHistoryWidget.vue
apps/web/src/services/dashboards/widgets/asset-widgets/total-fail-findings-status/TotalFailFindingsStatusWidget.vue
apps/web/src/services/dashboards/widgets/asset-widgets/trend-of-pass-and-fail-findings/TrendOfPassAndFailFindingsWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/budget-status/BudgetStatusWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-by-target/BudgetUsageByTargetWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-summary/BudgetUsageSummaryWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region-multi-fields/CostByRegionMultiFieldsWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region/CostByRegionWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/cost-map/CostMapWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/cost-summary-multi-fields/CostSummaryMultiFieldsWidget.vue
apps/web/src/services/dashboards/widgets/cost-widgets/monthly-cost/MonthlyCostWidget.vue
apps/web/src/services/service-account/components/ServiceAccountEditModal.vue
packages/mirinae/src/data-display/tree/he-tree-vue/components/Tree.vue
packages/mirinae/src/layouts/centered-layout/centered-layout-header/PCenteredLayoutHeader.vue

chore: remove unnecessary import (defineEmits)

---

apps/web/src/api-clients/cost-analysis/budget/schema/api-verbs/set-notification.ts
apps/web/src/api-clients/cost-analysis/budget/schema/api-verbs/update.ts
apps/web/src/api-clients/cost-analysis/budget/schema/model.ts
apps/web/src/services/cost-explorer/components/BudgetCreateStep3.vue
apps/web/src/services/cost-explorer/components/BudgetDeleteCheckModal.vue
apps/web/src/services/cost-explorer/components/BudgetDetailDeleteModal.vue
apps/web/src/services/cost-explorer/components/BudgetMainList.vue
apps/web/src/services/cost-explorer/constants/budget-constant.ts
apps/web/src/services/cost-explorer/stores/budget-detail-page-store.ts

feat: update budget main page

---

apps/web/src/services/cost-explorer/components/BudgetCreateStep3.vue
apps/web/src/services/cost-explorer/components/BudgetLastThreeMonthCostTrendBarChart.vue

feat: update unifiedCost trend chart at budget create page

---

apps/web/src/services/cost-explorer/components/BudgetAlertsModal.vue
apps/web/src/services/cost-explorer/components/BudgetCreateStep3.vue
apps/web/src/services/cost-explorer/components/BudgetDetailBaseInformation.vue
apps/web/src/services/cost-explorer/components/BudgetDetailDeleteModal.vue
apps/web/src/services/cost-explorer/components/BudgetDetailHeading.vue
apps/web/src/services/cost-explorer/components/BudgetMainList.vue
apps/web/src/services/cost-explorer/components/BudgetNameEditModal.vue
apps/web/src/services/cost-explorer/components/BudgetUsageTrend.vue
apps/web/src/services/cost-explorer/components/BudgetUsageTrendMonthly.vue
apps/web/src/services/cost-explorer/components/BudgetUsageTrendMonthlyChart.vue
apps/web/src/services/cost-explorer/components/BudgetUsageTrendMonthlyTable.vue
apps/web/src/services/cost-explorer/components/BudgetUsageTrendTotal.vue
apps/web/src/services/cost-explorer/components/BudgetUsageTrendTotalChart.vue
apps/web/src/services/cost-explorer/components/BudgetUsageTrendTotalTable.vue
apps/web/src/services/cost-explorer/pages/BudgetDetailPage.vue
apps/web/src/services/cost-explorer/stores/budget-create-page-store.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

feat: add budget detail page & fix minor changes

---

apps/web/src/services/_shared/dashboard/core/composables/use-dashboard-control-menu-helper.ts
apps/web/src/services/project/v2/components/ProjectDashboardBundleCloneModal.vue
apps/web/src/services/project/v2/components/ProjectDashboardEditListOverlay.vue
apps/web/src/services/project/v2/composables/queries/use-project-dashboard-folder-query.ts
apps/web/src/services/project/v2/stores/Project-dashboard-modal-store.ts

chore: solve project-dashboard bugs

---

apps/web/src/services/_shared/dashboard/dashboard-create/components/DashboardCreateBlankBoardItem.vue
apps/web/src/services/_shared/dashboard/dashboard-create/components/DashboardCreateStep2.vue
apps/web/src/services/_shared/dashboard/dashboard-create/contextual-components/DashboardCreateStep2SingleCase.vue
apps/web/src/services/project/v2/pages/ProjectMainPage.vue

chore(project): apply changed UX writing

---

apps/web/src/services/_shared/dashboard/core/composables/use-dashboard-control-menu-helper.ts
apps/web/src/services/_shared/dashboard/dashboard-create/contextual-components/DashboardCreateScopeForm.vue
apps/web/src/services/_shared/dashboard/dashboard-create/contextual-components/DashboardCreateStep1.vue
apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTree.vue
apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTreeItem.vue
apps/web/src/services/project/v2/components/ProjectDashboardEditListOverlay.vue

chore: solve dashboard create bug

---

apps/web/src/query/composables/use-scoped-query.ts
apps/web/src/services/_shared/dashboard/dashboard-detail/components/DashboardWidgetContainerV2.vue

chore(dashboard-qa): small fix

---

apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTree.vue
apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTreeItem.vue
apps/web/src/services/dashboards/components/dashboard-main/DashboardBundleDeleteModal.vue
apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
apps/web/src/services/project/v2/components/ProjectDashboardEditListOverlay.vue
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

fix(dashboard-tree): apply text highlighting UI

---

apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTree.vue
apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTreeItem.vue
apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
apps/web/src/services/project/v2/components/ProjectDashboardEditListOverlay.vue
apps/web/src/services/project/v2/pages/ProjectMainPage.vue

refactor: extract internal event (click tree item)

---

apps/web/src/api-clients/cost-analysis/budget/schema/model.ts
apps/web/src/api-clients/cost-analysis/budget/schema/type.ts
apps/web/src/services/cost-explorer/components/BudgetAlertsModal.vue
apps/web/src/services/cost-explorer/components/BudgetCreateManagerSelect.vue
apps/web/src/services/cost-explorer/components/BudgetCreateScopeSelect.vue
apps/web/src/services/cost-explorer/components/BudgetCreateStep1.vue
apps/web/src/services/cost-explorer/components/BudgetCreateStep2.vue
apps/web/src/services/cost-explorer/components/BudgetCreateStep3.vue
apps/web/src/services/cost-explorer/components/BudgetDetailBaseInformation.vue
apps/web/src/services/cost-explorer/components/BudgetLastThreeMonthCostTrendBarChart.vue
apps/web/src/services/cost-explorer/components/BudgetMainList.vue
apps/web/src/services/cost-explorer/components/BudgetNameEditModal.vue
apps/web/src/services/cost-explorer/components/BudgetUsageTrend.vue
apps/web/src/services/cost-explorer/components/BudgetUsageTrendMonthly.vue
apps/web/src/services/cost-explorer/components/BudgetUsageTrendMonthlyChart.vue
apps/web/src/services/cost-explorer/components/BudgetUsageTrendMonthlyTable.vue
apps/web/src/services/cost-explorer/components/BudgetUsageTrendTotal.vue
apps/web/src/services/cost-explorer/components/BudgetUsageTrendTotalChart.vue
apps/web/src/services/cost-explorer/components/BudgetUsageTrendTotalTable.vue
apps/web/src/services/cost-explorer/constants/budget-table-constant.ts
apps/web/src/services/cost-explorer/pages/BudgetCreatePage.vue
apps/web/src/services/cost-explorer/pages/BudgetDetailPage.vue
apps/web/src/services/cost-explorer/pages/admin/AdminBudgetDetailPage.vue

chore(budget-qa): fix budget qa

---

apps/web/src/lib/config/global-config/api-client-manager.ts
apps/web/src/lib/site-initializer/api-client.ts
apps/web/src/lib/site-initializer/index.ts
apps/web/src/store/reference/escalation-policy-reference-store.ts
packages/core-lib/src/space-connector/index.ts
packages/core-lib/src/space-connector/service-api.ts

refactor: apply merged config to service-api

---

apps/web/src/services/cost-explorer/components/BudgetCreateStep2.vue
apps/web/src/services/cost-explorer/components/BudgetDetailBaseInformation.vue
apps/web/src/services/cost-explorer/components/BudgetMainList.vue
apps/web/src/services/cost-explorer/components/BudgetMainToolset.vue
apps/web/src/services/cost-explorer/stores/budget-detail-page-store.ts
apps/web/src/services/service-account/components/ServiceAccountBaseInformationForm.vue
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

chore(budget-qa): fix critical & major & minor & trivial bugs

---

apps/web/src/services/cost-explorer/components/BudgetCreateStep2.vue
apps/web/src/services/cost-explorer/components/BudgetCreateStep3.vue
apps/web/src/services/cost-explorer/components/BudgetLastThreeMonthCostTrendBarChart.vue
apps/web/src/services/cost-explorer/components/BudgetUsageTrendMonthlyChart.vue
apps/web/src/services/cost-explorer/components/BudgetUsageTrendMonthlyTable.vue
apps/web/src/services/cost-explorer/components/BudgetUsageTrendTotalTable.vue
apps/web/src/services/cost-explorer/components/CostAnalysisContent.vue
apps/web/src/services/cost-explorer/components/CostAnalysisFiltersPopper.vue
apps/web/src/services/cost-explorer/routes/routes.ts

chore(budget-qa): fix critical & minor bug

---

apps/web/src/services/cost-explorer/components/BudgetCreateStep2.vue

chore(budget-qa): fix major bug of budget create error

---

apps/web/src/services/_shared/dashboard/dashboard-create/composables/use-dashboard-template-query.ts
apps/web/src/services/_shared/dashboard/dashboard-create/contextual-components/DashboardCreateStep1.vue
apps/web/src/services/_shared/dashboard/dashboard-create/contextual-components/DashboardCreateStep2BundleCase.vue

fix(dashboard-template): edit wrong query usage

---

apps/web/src/services/cost-explorer/components/BudgetCreateStep2.vue
apps/web/src/services/cost-explorer/components/BudgetDetailBaseInformation.vue
apps/web/src/services/cost-explorer/routes/admin/routes.ts

chore(budget-qa): fix major & minor bug

---

apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTreeItem.vue

fix(dashboard-tree): apply shared dashboard ux writing

---

apps/web/src/services/project/v2/composables/use-user-info.ts

Fixed incorrect usage of userItems in useUserInfo and updated the hook accordingly.

chore: use proper value in `useUserInfo`

---

apps/web/src/services/_shared/dashboard/core/composables/mutations/use-dashboard-folder-share-mutation.ts
apps/web/src/services/_shared/dashboard/core/composables/mutations/use-dashboard-share-mutation.ts
apps/web/src/services/_shared/dashboard/dashboard-detail/contextual-components/DashboardDetailHeader.vue
apps/web/src/services/dashboards/components/dashboard-main/DashboardBundleShareModal.vue

chore: solve dashboard minor bug

---

apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue

fix(widget): solve widget field data bug

---

apps/web/src/services/alert-manager/v2/components/AlertsManagementTable.vue
apps/web/src/services/alert-manager/v2/composables/alert-table-data.ts

fix: fixed calculate duration bug

---

apps/web/src/services/cost-explorer/components/BudgetCreateStep2.vue

chore(budget-qa): fix major bug about budget create step2

---

apps/web/src/services/cost-explorer/components/AdvancedSettingsCurrencyConverter.vue
apps/web/src/services/cost-explorer/pages/admin/AdminAdvancedSettingsPage.vue
apps/web/src/services/cost-explorer/routes/admin/routes.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

chore: remove subpages and display all components in the parent page

---

packages/mirinae/src/data-display/tables/definition-table/PDefinitionTable.vue

fix: disableCopy not working properly in PDefinitionTable

---

apps/web/src/schema/alert-manager/service/constants.ts
apps/web/src/schema/alert-manager/service/model.ts
apps/web/src/schema/alert-manager/service/type.ts
apps/web/src/services/alert-manager/v2/components/ServiceDetailHeader.vue
apps/web/src/services/alert-manager/v2/components/ServiceList.vue
apps/web/src/services/alert-manager/v2/stores/service-list-page-store.ts

feat: update service landing page - pagination as service_healthy

---

apps/web/src/api-clients/cost-analysis/cost-report-config/schema/api-verbs/list.ts
apps/web/src/api-clients/cost-analysis/cost-report-config/schema/api-verbs/update.ts
apps/web/src/api-clients/cost-analysis/cost-report-config/schema/model.ts
apps/web/src/services/cost-explorer/components/AdvancedSettingsCostReportConfiguration.vue
apps/web/src/services/cost-explorer/composables/queries/use-cost-report-config-query.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

chore: markup "cost report configuration" section

---

apps/web/src/services/cost-explorer/components/AdvancedSettingsCostReportConfiguration.vue
apps/web/src/services/cost-explorer/components/AdvancedSettingsSetAdjustmentsOverlay.vue
apps/web/src/services/cost-explorer/stores/cost-explorer-settings-store.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json
packages/mirinae/src/controls/dropdown/select-dropdown/PSelectDropdown.vue
packages/mirinae/src/controls/dropdown/select-dropdown/components/dropdown-button.vue
packages/mirinae/src/layouts/overlay-layout/POverlayLayout.vue

feat: add 'Cost Report Adjustments' overlay

---

apps/web/src/api-clients/_common/constants/api-doc-constant.ts
apps/web/src/api-clients/cost-analysis/report-adjustment-policy/composables/use-report-adjustment-policy-api.ts
apps/web/src/api-clients/cost-analysis/report-adjustment-policy/schema/api-verbs/change-order.ts
apps/web/src/api-clients/cost-analysis/report-adjustment-policy/schema/api-verbs/create.ts
apps/web/src/api-clients/cost-analysis/report-adjustment-policy/schema/api-verbs/delete.ts
apps/web/src/api-clients/cost-analysis/report-adjustment-policy/schema/api-verbs/get.ts
apps/web/src/api-clients/cost-analysis/report-adjustment-policy/schema/api-verbs/list.ts
apps/web/src/api-clients/cost-analysis/report-adjustment-policy/schema/api-verbs/update.ts
apps/web/src/api-clients/cost-analysis/report-adjustment-policy/schema/model.ts
apps/web/src/api-clients/cost-analysis/report-adjustment-policy/schema/type.ts
apps/web/src/api-clients/cost-analysis/report-adjustment/composables/use-report-adjustment-api.ts
apps/web/src/api-clients/cost-analysis/report-adjustment/schema/api-verbs/change-order.ts
apps/web/src/api-clients/cost-analysis/report-adjustment/schema/api-verbs/create.ts
apps/web/src/api-clients/cost-analysis/report-adjustment/schema/api-verbs/delete.ts
apps/web/src/api-clients/cost-analysis/report-adjustment/schema/api-verbs/get.ts
apps/web/src/api-clients/cost-analysis/report-adjustment/schema/api-verbs/list.ts
apps/web/src/api-clients/cost-analysis/report-adjustment/schema/api-verbs/update.ts
apps/web/src/api-clients/cost-analysis/report-adjustment/schema/model.ts
apps/web/src/api-clients/cost-analysis/report-adjustment/schema/type.ts

feat: update model of report adjustment

---

apps/web/src/services/cost-explorer/components/AdvancedSettingsAdjustmentForm.vue
apps/web/src/services/cost-explorer/components/AdvancedSettingsSetAdjustmentsOverlay.vue

chore: markup adjustment form

---

apps/web/src/services/alert-manager/v2/components/ServiceList.vue

feat(alert-service-list): update service list pagination improvement

---

apps/web/src/services/alert-manager/v2/components/ServiceDetailHeader.vue
apps/web/src/services/alert-manager/v2/components/ServiceList.vue

chore(alert-service): update service main page pagination

---

apps/web/src/services/ops-flow/task-management-templates/translations/ja.json

chore: apply jp at ops-flow

---

apps/web/src/services/alert-manager/v2/components/AlertsManagementTable.vue

feat: changed excel export API

---

apps/web/src/services/cost-explorer/components/AdvancedSettingsAdjustmentGroupForm.vue
apps/web/src/services/cost-explorer/components/AdvancedSettingsSetAdjustmentsOverlay.vue
apps/web/src/services/cost-explorer/composables/queries/use-report-adjustment-policy-query.ts
apps/web/src/services/cost-explorer/composables/queries/use-report-adjustment-query.ts
apps/web/src/services/cost-explorer/stores/advanced-settings-page-store.ts
apps/web/src/services/cost-explorer/types/report-adjustment-type.ts

refactor: use vuequery rather than api list

---

apps/web/src/services/alert-manager/v2/components/ServiceDetailHeader.vue
apps/web/src/services/alert-manager/v2/components/ServiceList.vue

feat(service-pagination): update service main page pagination

---

apps/web/src/services/alert-manager/v2/components/ServiceList.vue

feat: remove unnecessary console log

---

.github/workflows/pull_request_random_reviewer_assignment.yaml

chore: edit random-reviewer-assignment CI

---

apps/web/src/services/cost-explorer/components/AdvancedSettingsCostReportConfiguration.vue
apps/web/src/services/cost-explorer/components/CostReportUpcomingReportCard.vue
apps/web/src/services/cost-explorer/helpers/cost-report-issue-date-helper.ts
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

Added confirmation date to the existing design, which previously only included issue date.
발행일(Issue Date)만 있던 기존 디자인에서 확정일(Confirmation Date) 추가

feat: implement confirmation date for report

---

apps/web/src/services/alert-manager/v2/composables/alert-table-data.ts

fix: fix timezone-aware time bug

---

apps/web/src/api-clients/cost-analysis/report-adjustment-policy/schema/api-verbs/create.ts
apps/web/src/api-clients/cost-analysis/report-adjustment-policy/schema/api-verbs/update.ts
apps/web/src/services/cost-explorer/components/AdvancedSettingsAdjustmentGroupForm.vue
apps/web/src/services/cost-explorer/components/CostReportUpcomingReportCard.vue
apps/web/src/services/cost-explorer/stores/advanced-settings-page-store.ts
apps/web/src/services/cost-explorer/types/report-adjustment-type.ts

feat: add isAllWorkspaceSelected to policy data

---

apps/web/src/services/service-account/components/ServiceAccountAttachedGeneralAccounts.vue

SSIA
- Feedback: https://www.notion.so/Created_at-ca0df1a13add4aec8310711e1a16b3f1?pvs=4

fix: fixed time bug

---

apps/web/src/api-clients/cost-analysis/report-adjustment/schema/type.ts
apps/web/src/services/cost-explorer/components/AdvancedSettingsAdjustmentsForm.vue
apps/web/src/services/cost-explorer/components/AdvancedSettingsSetAdjustmentsOverlay.vue
apps/web/src/services/cost-explorer/composables/queries/use-report-adjustment-query.ts
apps/web/src/services/cost-explorer/stores/advanced-settings-page-store.ts
apps/web/src/services/cost-explorer/types/report-adjustment-type.ts

feat: create/update/delete/change-order adjustment items

---

apps/web/src/services/advanced/pages/admin/AdminDomainSettingsAutoDormancyConfigurationPage.vue
apps/web/src/services/advanced/store/workspace-group-page-store.ts
apps/web/src/services/advanced/store/workspace-page-store.ts
apps/web/src/services/cost-explorer/composables/queries/use-cost-report-config-query.ts
apps/web/src/services/cost-explorer/stores/cost-report-page-store.ts
apps/web/src/services/service-account/stores/service-account-page-store.ts
apps/web/src/services/workspace-home/shared/composables/use-cost-report-config-query.ts

feat: set sort(created_at/asc) to cost-report-config/list

---

apps/web/src/common/pages/CostReportDetailPage.vue

refactor: refactor code

---

apps/web/src/common/pages/CostReportDetailPage.vue

feat: update provider section

---

apps/web/src/services/_shared/dashboard/dashboard-detail/components/DashboardToolsetScope.vue
apps/web/src/services/_shared/dashboard/dashboard-detail/stores/dashboard-detail-info-store.ts

fix(dashboard): edit admin dashboard workspace vars-filter scenario

---

apps/web/src/lib/site-initializer/index.ts
apps/web/src/services/asset-inventory/components/CollectorHistoryJobStatusChart.vue

fix: apply minor feedback

---

apps/web/src/services/cost-explorer/stores/advanced-settings-page-store.ts

fix: fix adjustment addition error

---

apps/web/src/services/alert-manager/v2/components/AlertCreateModal.vue
apps/web/src/services/alert-manager/v2/components/AlertDetailDeleteModal.vue
apps/web/src/services/alert-manager/v2/components/AlertDetailNote.vue
apps/web/src/services/alert-manager/v2/components/AlertDetailTabsTimeline.vue
apps/web/src/services/alert-manager/v2/components/AlertsManagementTable.vue
apps/web/src/services/alert-manager/v2/components/ServiceDetailHeader.vue
apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettings.vue
apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsContainer.vue
apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEscalationPolicy.vue
apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEscalationPolicyDeleteModal.vue
apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEscalationPolicyFormModal.vue
apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEventRule.vue
apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEventRuleActionAlert.vue
apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEventRuleActionAsset.vue
apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEventRuleActionService.vue
apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEventRuleCard.vue
apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEventRuleDeleteModal.vue
apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEventRuleFormCard.vue
apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEventRuleSidebar.vue
apps/web/src/services/alert-manager/v2/composables/use-event-rule-get-query.ts
apps/web/src/services/alert-manager/v2/composables/use-event-rule-list-query.ts
apps/web/src/services/alert-manager/v2/pages/ServiceDetailPage.vue
apps/web/src/services/alert-manager/v2/stores/service-detail-page-store.ts
apps/web/src/services/alert-manager/v2/types/alert-manager-type.ts
apps/web/src/services/asset-inventory/components/CloudServiceAlertsTab.vue

feat: apply vue-query to "event rule, note" api

---

apps/web/src/services/cost-explorer/components/AdvancedSettingsCostReportConfiguration.vue
apps/web/src/services/cost-explorer/components/AdvancedSettingsSetAdjustmentsOverlay.vue

fix: incorrect policy id in adjustment creation request

---

apps/web/src/common/modules/popup/notice/modules/NoticePopupItem.vue
apps/web/src/services/cost-explorer/components/AdvancedSettingsAdjustmentsForm.vue
apps/web/src/services/cost-explorer/components/CostReportReportsTab.vue
apps/web/src/services/cost-explorer/stores/advanced-settings-page-store.ts

feat: feat: load ADJUSTING and DONE items in admin mode & etc

---

apps/web/src/services/cost-explorer/components/AdvancedSettingsAdjustmentsForm.vue
apps/web/src/services/cost-explorer/components/AdvancedSettingsSetAdjustmentsOverlay.vue
apps/web/src/services/cost-explorer/stores/advanced-settings-page-store.ts

fix: handle async timing issue (adjustment) & etc

---

.github/workflows/dispatch_release_hotfix.yaml

This workflow enables emergency hotfix releases based on older image versions, especially when unreleased changes already exist in master.
It allows a temporary patch without affecting the latest master builds.

fix(release-hofix): create temporarily hotfix workflow

---

.github/workflows/dispatch_release_hotfix.yaml

chore(release-hotfix): apply changed version convention regex

---

apps/web/src/services/alert-manager/v2/components/ServiceList.vue
apps/web/src/services/alert-manager/v2/composables/use-service-list-pagination-query.ts

- Please check only the feat commits.

feat: update vue query pagination at service landing page

---

apps/web/src/services/alert-manager/v2/components/AlertsManagementTable.vue

fix: split link component tag

---

apps/web/public/images/budget-charts/ic_accumulated_usage_over.svg
apps/web/public/images/budget-charts/ic_accumulated_usage_under.svg
apps/web/public/images/budget-charts/ic_actual_spend.svg
apps/web/public/images/budget-charts/ic_planned_budget.svg
apps/web/src/services/cost-explorer/components/BudgetUsageTrendMonthlyChart.vue
apps/web/src/services/cost-explorer/components/BudgetUsageTrendTotalChart.vue
packages/language-pack/en.json
packages/language-pack/ja.json
packages/language-pack/ko.json

- just UI update of chart legends

feat(budget): apply design feedback about budget detail chart

---

apps/web/src/services/iam/components/SelectChannelCard.vue
apps/web/src/services/iam/components/UserGroupChannelDeleteDoubleCheckModal.vue
apps/web/src/services/iam/components/UserGroupChannelSetModal.vue
apps/web/src/services/iam/components/UserGroupManagementTabNotificationChannel.vue
apps/web/src/services/iam/components/UserGroupManagementTable.vue
apps/web/src/services/iam/store/user-group-page-store.ts

feat: apply vue-query to user group channel api

---

apps/web/src/api-clients/alert-manager/service-channel/composables/use-service-channel-api.ts
apps/web/src/services/alert-manager/v2/components/ServiceCreateStep3.vue
apps/web/src/services/alert-manager/v2/components/ServiceDetailMemberModal.vue
apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsNotifications.vue
apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsNotificationsDeleteModal.vue
apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsNotificationsDetail.vue
apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsNotificationsTableModal.vue
apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsNotificationsUpdateModal.vue
apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsOverviewNotification.vue
apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEscalationPolicyFormChannelDropdown.vue
apps/web/src/services/alert-manager/v2/composables/use-service-channel-create-mutation.ts
apps/web/src/services/alert-manager/v2/composables/use-service-channel-list-query.ts
apps/web/src/services/alert-manager/v2/pages/ServiceDetailNotificationsCreatePage.vue
apps/web/src/services/alert-manager/v2/stores/service-detail-page-store.ts

feat: apply vue-query to service channel api

---

apps/web/src/services/alert-manager/v2/components/ServiceCreateStep2.vue
apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsOverviewWebhook.vue
apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEventRuleScopeModal.vue
apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsWebhook.vue
apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsWebhookDeleteModal.vue
apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsWebhookDetail.vue
apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsWebhookTableModal.vue
apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsWebhookUpdateModal.vue
apps/web/src/services/alert-manager/v2/composables/use-webhook-create-mutation.ts
apps/web/src/services/alert-manager/v2/composables/use-webhook-list-pagination-query.ts
apps/web/src/services/alert-manager/v2/composables/use-webhook-list-query.ts
apps/web/src/services/alert-manager/v2/pages/ServiceDetailWebhookCreatePage.vue

feat: apply vue-query to webhook api

---

apps/web/src/services/cost-explorer/CostExplorerContainer.vue
apps/web/src/services/cost-explorer/components/CostAnalysisChart.vue
apps/web/src/services/cost-explorer/components/CostAnalysisDataTable.vue
apps/web/src/services/cost-explorer/components/CostAnalysisDataTypeDropdown.vue
apps/web/src/services/cost-explorer/components/CostAnalysisFiltersAddMoreButton.vue
apps/web/src/services/cost-explorer/components/CostAnalysisFiltersPopper.vue
apps/web/src/services/cost-explorer/components/CostAnalysisGranularityPeriodDropdown.vue
apps/web/src/services/cost-explorer/components/CostAnalysisGroupBy.vue
apps/web/src/services/cost-explorer/components/CostAnalysisHeader.vue
apps/web/src/services/cost-explorer/components/CostAnalysisLSB.vue
apps/web/src/services/cost-explorer/components/CostAnalysisPeriodSelectDropdown.vue
apps/web/src/services/cost-explorer/components/CostAnalysisQueryFormModal.vue
apps/web/src/services/cost-explorer/components/CostAnalysisQuerySection.vue
apps/web/src/services/cost-explorer/composables/queries/use-cost-query-set-query.ts
apps/web/src/services/cost-explorer/pages/CostAnalysisPage.vue
apps/web/src/services/cost-explorer/stores/cost-analysis-page-store.ts
apps/web/src/services/cost-explorer/stores/cost-query-set-store.ts

refactor: move API calls from store to vue query

---

apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEventRuleActionAsset.vue
apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEventRuleCard.vue
apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEventRuleFormCard.vue
apps/web/src/services/cost-explorer/pages/admin/AdminAnomalyDetectionConfigurationPage.vue
packages/language-pack/ko.json

chore: apply minor issue

---

apps/web/src/services/asset-inventory/components/CloudServiceDetail.vue

- [Jira-Ticket](https://mzdevs.atlassian.net/browse/SBE-441)

fix: prevent query filter cleared on change at cloud service page

---

apps/web/src/api-clients/_common/constants/api-doc-constant.ts
apps/web/src/api-clients/add-ons/page-schema/composables/use-page-schema-api.ts
apps/web/src/api-clients/add-ons/page-schema/schema/api-verbs/get.ts
apps/web/src/api-clients/add-ons/page-schema/schema/model.ts
apps/web/src/api-clients/inventory/cloud-service/composables/use-cloud-service-api.ts
apps/web/src/api-clients/inventory/cloud-service/schema/api-verbs/get-data.ts
apps/web/src/query/service-query/pagination/pagination-query-helper.ts
apps/web/src/query/service-query/pagination/use-scoped-pagination-query.ts
apps/web/src/services/_shared/dashboard/dashboard-detail/composables/use-cloud-service-detail-menu-set.ts
apps/web/src/services/asset-inventory/components/CloudServiceAdmin.vue
apps/web/src/services/asset-inventory/components/CloudServiceDetail.vue
apps/web/src/services/asset-inventory/components/CloudServiceDetailMultipleSelectedData.vue
apps/web/src/services/asset-inventory/components/CloudServiceDetailTabs.vue
apps/web/src/services/asset-inventory/components/CloudServiceLSB.vue
apps/web/src/services/asset-inventory/components/CloudServiceTagsPanel.vue
apps/web/src/services/asset-inventory/composables/use-cloud-service-detail-menu-set.ts
apps/web/src/services/asset-inventory/composables/use-cloud-service-get-data-pagination-query.ts
apps/web/src/services/asset-inventory/composables/use-cloud-service-get-query.ts
apps/web/src/services/asset-inventory/composables/use-cloud-service-page-schema-get-query.ts
apps/web/src/services/asset-inventory/composables/use-cloud-service-pagination-query.ts
apps/web/src/services/asset-inventory/composables/use-cloud-service-type-list-query.ts
apps/web/src/services/asset-inventory/pages/CloudServiceDetailPage.vue
apps/web/src/services/asset-inventory/types/cloud-service-detail-page-type.ts

feat(cloud-service-detail): apply vue-query

---

apps/web/src/services/asset-inventory/components/CollectorAdditionalRule.vue
apps/web/src/services/asset-inventory/components/CollectorBaseInfoSection.vue
apps/web/src/services/asset-inventory/components/CollectorCurrentStatus.vue
apps/web/src/services/asset-inventory/components/CollectorDetailAttachedServiceAccounts.vue
apps/web/src/services/asset-inventory/components/CollectorDetailCollectDataButtonGroup.vue
apps/web/src/services/asset-inventory/components/CollectorDetailOptionsSection.vue
apps/web/src/services/asset-inventory/components/CollectorDetailPluginSummaryCards.vue
apps/web/src/services/asset-inventory/components/CollectorDetailScheduleSection.vue
apps/web/src/services/asset-inventory/components/CollectorDetailServiceAccountsSection.vue
apps/web/src/services/asset-inventory/components/CollectorFormAttachedServiceAccount.vue
apps/web/src/services/asset-inventory/components/CollectorFormOptions.vue
apps/web/src/services/asset-inventory/components/CollectorFormSchedule.vue
apps/web/src/services/asset-inventory/components/CollectorFormVersion.vue
apps/web/src/services/asset-inventory/components/CollectorMainContentItem.vue
apps/web/src/services/asset-inventory/components/CollectorMainContents.vue
apps/web/src/services/asset-inventory/components/CollectorMainItemSchedule.vue
apps/web/src/services/asset-inventory/components/CollectorMainScheduleModal.vue
apps/web/src/services/asset-inventory/components/RecentCollectorJobList.vue
apps/web/src/services/asset-inventory/helpers/collector-editable-value-helper.ts
apps/web/src/services/asset-inventory/pages/CollectorDetailPage.vue
apps/web/src/services/asset-inventory/pages/admin/AdminCollectorDetailPage.vue
apps/web/src/services/asset-inventory/stores/collector-form-store.ts
apps/web/src/services/asset-inventory/types/collector-main-page-type.ts

refactor: use `collectorGetQuery` instead of using store

---

apps/web/src/services/advanced/components/WorkspaceGroupAddWorkspacesModal.vue
apps/web/src/services/advanced/components/WorkspaceGroupCreateModal.vue
apps/web/src/services/advanced/components/WorkspaceManagementTable.vue
apps/web/src/services/advanced/components/WorkspaceTagManagementTabContents.vue
apps/web/src/services/advanced/components/WorkspacesCreateModal.vue
apps/web/src/services/advanced/components/WorkspacesDeleteModal.vue
apps/web/src/services/advanced/components/WorkspacesSetEnableModal.vue
apps/web/src/services/advanced/components/WorkspacesUserManagementTab.vue
apps/web/src/services/advanced/components/WorkspacesUserManagementTabContents.vue
apps/web/src/services/advanced/composables/use-workspace-list-pagination-query.ts
apps/web/src/services/advanced/composables/use-workspace-user-list-pagination-query.ts
apps/web/src/services/advanced/pages/admin/AdminWorkspacesPage.vue
apps/web/src/services/advanced/store/workspace-page-store.ts
apps/web/src/services/iam/components/UserManagementAddModal.vue

feat: apply vue query at workspace 'list' API and cleanup store

---

apps/web/src/api-clients/inventory/job-task/composables/use-job-task-api.ts
apps/web/src/api-clients/repository/plugin/composables/use-plugin-api.ts
apps/web/src/services/asset-inventory/components/CollectorBaseInfoSection.vue
apps/web/src/services/asset-inventory/components/CollectorCollectorStep2.vue
apps/web/src/services/asset-inventory/components/CollectorDetailNameEditModal.vue
apps/web/src/services/asset-inventory/components/CollectorFormVersion.vue
apps/web/src/services/asset-inventory/components/CollectorHistoryJobTaskTable.vue
apps/web/src/services/asset-inventory/composables/use-inventory-job-task-list-query.ts
apps/web/src/services/asset-inventory/composables/use-plugin-get-versions-query.ts
apps/web/src/services/asset-inventory/stores/collector-form-store.ts

refactor: use vue query instead of using api directly

---

apps/web/src/services/asset-inventory/components/MetricExplorerChart.vue
apps/web/src/services/asset-inventory/components/MetricExplorerChartLegends.vue
apps/web/src/services/asset-inventory/components/MetricExplorerDataTable.vue
apps/web/src/services/asset-inventory/components/MetricExplorerFiltersPopper.vue
apps/web/src/services/asset-inventory/components/MetricExplorerGroupBy.vue
apps/web/src/services/asset-inventory/components/MetricExplorerHeader.vue
apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue
apps/web/src/services/asset-inventory/components/MetricExplorerNameFormModal.vue
apps/web/src/services/asset-inventory/components/MetricExplorerQueryFormSidebar.vue
apps/web/src/services/asset-inventory/composables/use-metric-get-query.ts
apps/web/src/services/asset-inventory/composables/use-namespace-list-query.ts
apps/web/src/services/asset-inventory/pages/MetricExplorerDetailPage.vue
apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts

refactor: apply vue query to metric pages

---

apps/web/src/services/asset-inventory/pages/CollectorHistoryPage.vue

fix: change job history to display overall progress as a percentage

---

apps/web/src/api-clients/cost-analysis/cost-report/schema/type.ts
apps/web/src/common/pages/CostReportDetailPage.vue
apps/web/src/services/cost-explorer/components/CostReportReportsTab.vue

feat: apply cost report status(adjusting, expired)

---

apps/web/src/services/ops-flow/components/TaskCategoryDeleteModal.vue

fix: fix the wrong import

---

apps/web/src/services/asset-inventory/components/MetricExplorerFiltersPopper.vue
apps/web/src/services/asset-inventory/components/MetricExplorerHeader.vue
apps/web/src/services/asset-inventory/components/MetricExplorerLSBMetric.vue
apps/web/src/services/asset-inventory/components/MetricExplorerNameFormModal.vue
apps/web/src/services/asset-inventory/composables/use-metric-example-get-query.ts
apps/web/src/services/asset-inventory/pages/MetricExplorerDetailPage.vue
apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts

Please review commit by commit.

refactor: use vue query for metric example

---

apps/web/src/services/iam/components/UserManagementAddModal.vue
apps/web/src/services/iam/components/UserManagementRemoveModal/UserManagementOnlyRemoveWorkspaceGroupTypeModal.vue
apps/web/src/services/iam/components/UserManagementStatusModal.vue
apps/web/src/services/iam/composables/use-user-group-list-query.ts

- not yet about button CRUD vue query at admin mode page (ASAP)

refactor(user): apply vue query in modal at user page

---

apps/web/src/api-clients/cost-analysis/data-source-account/composables/use-data-source-account-api.ts
apps/web/src/api-clients/cost-analysis/data-source-account/schema/api-verbs/analyze.ts
apps/web/src/api-clients/cost-analysis/data-source/composables/use-data-source-api.ts
apps/web/src/api-clients/cost-analysis/job/composables/use-job-api.ts
apps/web/src/services/cost-explorer/composables/use-cost-job-list-query.ts
apps/web/src/services/cost-explorer/composables/use-data-source-account-analyze-query.ts
apps/web/src/services/cost-explorer/composables/use-data-source-list-query.ts

feat: add vue query hooks for data source page

---

apps/web/src/api-clients/inventory/metric-data/schema/api-verbs/analyze.ts
apps/web/src/services/asset-inventory/components/MetricExplorerChart.vue
apps/web/src/services/asset-inventory/components/MetricExplorerDataTable.vue
apps/web/src/services/asset-inventory/components/MetricExplorerLineChart.vue
apps/web/src/services/asset-inventory/components/MetricExplorerQuerySection.vue
apps/web/src/services/asset-inventory/composables/use-metric-data-analyze-query.ts
apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts
apps/web/src/services/workspace-home/shared/composables/use-asset-daily-updates.ts
apps/web/src/services/workspace-home/shared/composables/use-asset-summary-providers.ts

refactor: apply metric-data/analyze vue query to components

---

apps/web/src/services/cost-explorer/components/AdvancedSettingsCurrencyConverter.vue
apps/web/src/services/cost-explorer/components/CostAnalysisDataTable.vue
apps/web/src/services/cost-explorer/composables/use-data-source-get-query.ts
apps/web/src/services/cost-explorer/composables/use-data-source-list-query.ts

feat: add data-source/get vue query

---

apps/web/src/services/cost-explorer/components/DataSourceManagementTabAccessRestriction.vue
apps/web/src/services/cost-explorer/components/DataSourceManagementTabDataCollectionHistory.vue
apps/web/src/services/cost-explorer/components/DataSourceManagementTabDataCollectionHistoryModal.vue
apps/web/src/services/cost-explorer/components/DataSourceManagementTabDetailBaseInformation.vue
apps/web/src/services/cost-explorer/components/DataSourceManagementTabLinkedAccount.vue
apps/web/src/services/cost-explorer/components/DataSourceManagementTabLinkedAccountTable.vue
apps/web/src/services/cost-explorer/components/DataSourceManagementTable.vue
apps/web/src/services/cost-explorer/components/DataSourceManagementTabs.vue
apps/web/src/services/cost-explorer/pages/admin/AdminDataSourcePage.vue
apps/web/src/services/cost-explorer/stores/data-sources-page-store.ts

refactor: apply dataSource query to page/components 

---

apps/web/src/services/iam/components/UserManagementTab.vue
apps/web/src/services/iam/components/UserManagementTabDetail.vue
apps/web/src/services/iam/components/UserManagementTable.vue
apps/web/src/services/iam/composables/use-role-list-query.ts
apps/web/src/services/iam/composables/use-user-get-query.ts
apps/web/src/services/iam/composables/use-user-list-query.ts
apps/web/src/services/iam/pages/UserMainPage.vue
apps/web/src/services/iam/store/user-page-store.ts

refactor: apply vue query at role api and improve reactivity of showing tab detail(s) of user

---

apps/web/src/api-clients/identity/trusted-account/schema/api-verbs/create.ts
apps/web/src/api-clients/identity/trusted-account/schema/api-verbs/update.ts
apps/web/src/api-clients/identity/trusted-account/schema/constant.ts
apps/web/src/api-clients/identity/trusted-account/schema/model.ts
apps/web/src/api-clients/identity/trusted-account/schema/type.ts
apps/web/src/services/service-account/components/ServiceAccountAutoSync.vue
apps/web/src/services/service-account/components/ServiceAccountAutoSyncMappingMethod.vue
apps/web/src/services/service-account/constants/auto-sync-options-contant.ts
apps/web/src/services/service-account/pages/ServiceAccountAddPage.vue
apps/web/src/services/service-account/stores/service-account-page-store.ts

Add New Workspace Mapping method for Azure account auto-sync.
- Top-level Management Group -> Workspace
- Leaf-level Management Group -> Workspace (in this case, remove project group mapping option)

feat(azure-account): apply changed azure account workspace mapping method

---

apps/web/src/api-clients/identity/user-profile/composables/use-user-profile-api.ts
apps/web/src/services/iam/components/UserGroupManagementAddUsersModal.vue
apps/web/src/services/landing/components/workspace-landing/LandingContents.vue
apps/web/src/services/landing/components/workspace-landing/landing-group-workspaces/LandingGroupWorkspaces.vue
apps/web/src/services/landing/composables/use-user-profile-get-workspace-groups-query.ts
apps/web/src/services/landing/composables/use-user-profile-get-workspaces-query.ts
apps/web/src/services/landing/store/landing-page-store.ts

refactor: apply vue query to landing workspace group section

---

apps/web/src/services/landing/components/workspace-landing/LandingContents.vue
apps/web/src/services/landing/components/workspace-landing/LandingRecentVisits.vue
apps/web/src/services/landing/components/workspace-landing/LandingSearchedWorkspaces.vue

chore: change component file name
